### ISSUE TITLE
Use infinite scroll instead of high limits in rest APIs

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#1011]
Currently there is often a workaround like the one commented [here](https://github.com/sulu-io/sulu/commit/03f32ea1231298e0040686bce2840a2edf36abfc#commitcomment-10734936)

Instead of this high limit numbers on the APIs the infinite scroll should be used.

**Comment by danrot** [comment]
I currently think of the column navigation (although I am sure there are more occurrences of this).
@wachterjohannes Please add other components affected by this (if you know any)

**Comment by wachterjohannes** [comment]
@danrot at the moment i only think about column-navigation ... perhaps an own view for the datagrid ... but nothing else ...

**Comment by alexander-schranz** [comment]
The controller which allow to return infinity data are using now:

```
        // disable pagination to simplify tree handling
        $listBuilder->limit(null);
```

e.g. CategoryController

So there are no longer hardcoded `limit=9999` in 2.0 codebase
