### ISSUE TITLE
Use symfony translations for title in xml templates

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#1048]
A property in the xml templates currently look like the following:

``` xml
<property name="title" type="text_line" mandatory="true">
    <meta>
        <title lang="de">Titel</title>
        <title lang="en">Title</title>
     </meta>
     <tag name="sulu.rlp.part"/>
</property>
```

Instead of the meta tag with the titles it would be nice to use the translation mechnism from symfony.

**Comment by patkar** [comment]
Please for all stuff, which can have a translation.

**Comment by wachterjohannes** [comment]
nice it would be to provide both of it!

**Comment by patkar** [comment]
jup :+1:

**Comment by danrot** [comment]
I think this issue should be prioritized even higher now, since we also define forms like [contacts](https://github.com/sulu/sulu/blob/e001895/src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml#L7) and accounts using this style now.

If we do not support that now, external contributors won't be able to translate these fields without touching our files, and that's actually what we would like to avoid and use some other online tools instead (i.e. https://lingohub.com/)
