### ISSUE TITLE
Rename image converter commands

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#1054]
Currently the "Converter" are named Commands. For example `CropCommand`. This should be renamed to "Converter".

The problem is that the term command is used in the `format-options.xml` file which is public API.

**Comment by alexander-schranz** [comment]
The Converter is the ImagineImageConverter.php and the Crop, Resize, Scale are the ConverterCommands I don't agree to rename the command classes, also they are in the ImageConverter namespace so it is redundant.

**Comment by wachterjohannes** [comment]
@alexander-schranz but thats weird they are in the namespace `converter` but are named `command`? that sounds a bit "inconsistent" (=

**Comment by danrot** [comment]
Especially in a symfony environment it is very strange, since commands are something completely different here. That's just confusing for symfony developers having a deeper look at Sulu.

**Comment by patkar** [comment]
At first look it's really confusing

**Comment by chirimoya** [comment]
BC-Break, currently not worth it.

**Comment by danrot** [comment]
Decided on the name `Transformer`, but still not doable before 2.0
