### ISSUE TITLE
[RFC] Improve the sulu:build command for new installations

### ISSUE THREAD

**Issue by EmiiKhaos** [sulu/sulu#1056]
How about an installer command which does all the stuff which is written in the docs and asks you, if you want to install the demo data or not. Maybe some more complex demo data.

**Comment by danrot** [comment]
What exactly should this installer do for you? We already have the `sulu:build` command which is doing quite a lot for you. We also had a bash script once, doing a bit more, but IMHO it's also some work to maintain it...

**Comment by patkar** [comment]
Yes. But it can be improved. Missing:

* copying the needed dist xml files in the correct places. With this they could reside in a fixtures dir in the sulu project instead of sulu-standard
* Asking you if you want to load the fixtures/demo data
* More complex demo data
* While copying the webspace.xml.dist asking the user for name, key (or generate it) and url.
* Create first user and role (internal call the role and user commands) on install mode.
* Check system requirements, if they are met for Sulu

**Comment by dantleech** [comment]
> copying the needed dist xml files in the correct places. With this they could reside in a fixtures dir in the sulu project instead of sulu-standard

+1

> Asking you if you want to load the fixtures/demo data, more complex demo data

I like this idea. I guess this could maybe be "bootstrap" bundle or something. The DeveloperBundle would be more for developers -- generating data for benchmarking, etc. The demo would be something polished.

> While copying the webspace.xml.dist asking the user for name, key (or generate it) and url.


> Create first user and role (internal call the role and user commands) on install mode.

Do we not already do this in the build command?

> Check system requirements, if they are met for Sulu

+1

**Comment by patkar** [comment]
> I like this idea. I guess this could maybe be "bootstrap" bundle or something. The DeveloperBundle would be more for developers -- generating data for benchmarking, etc. The demo would be something polished.

I don't think it needs a whole new bundle. A fixtures dir in every bundle with doctrine fixtures and then load it with them. Like in Sylius ;)

> Do we not already do this in the build command?

Nope

**Comment by dantleech** [comment]
Hmm. But then we are distributing this demo content everywhere. If we have a "demo" installation, then all the content should be in the same place in order that it is focused and coherent - it is a demonstration installation, not a bunch of fixtures for functional testing (which I guess is the purpose of the Sylius setup).

I am certain that the build command creates at least the "admin" user and the "admin" role :)

**Comment by danrot** [comment]
It creates a user if you use the `dev` build target, in `prod` no user is created.

**Comment by danrot** [comment]
And I am against just copying the dist files automatically, because they have to to be adapted for every project anyway. But I see that a command or something to bootstrap certain files might be handy, so +1 on this.

**Comment by dantleech** [comment]
I would say that the default template that is used by the homepage should be copied, as the goal is to have the system at least working after doing this.

A demo installation would of course create more templates. Maybe @berndhep has some input on that, it could be similar to the Sulu homepage for example.

**Comment by danrot** [comment]
In most projects none of the dist templates are used, so I would think it is a bit annoying to have these automatically copied, since you have to delete them in almost all realistic use cases anyway. But maybe we can include that in a separate build target?

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu/issues/2078

**Comment by sagikazarmark** [comment]
Not sure if this is still the right issue, but I would also mention regular deployment tasks here too. Neither of the current build targets (dev, prod, maintain) is right for that purpose. I am a little bit confused about prod as I would expect that it's the target that I should invoke during a regular live deployment, but it also installs fixtures which I definitely don't want. Don't know if there is a proper way of doing this at the moment at all and it's just missing documentation.

Right now I have the following configuration:

``` bash
massive_build:
    targets:
        deploy:
            dependencies:
                database: ~
                phpcr: ~
                phpcr_migrations: ~
```

Can someone give me some feedback on it?

**Comment by sagikazarmark** [comment]
I rather ended up putting my dev fixtures in a DeveloperBundle not loaded in prod mode.

**Comment by danrot** [comment]
@sagikazarmark Currently this is only used for initializations, and not for recurring deployment tasks... We would have to adjust that a bit, or you could introduce another build target. But if you solution works it's also fine.

**Comment by danrot** [comment]
Since most of the pain points described in here are already solved in other ways I am closing this issue.

E.g. there are no dist files to copy anymore, and if you want to have demo data, you can install our demo project.
