### ISSUE TITLE
Move description of checkbox

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu#1063]
Please move the description / title of a checkbox to the left side of it

Example:
[  ] Checkbox Title

Actually the title of the checkbox is on top of it.
![bildschirmfoto 2015-05-05 um 14 56 09](https://cloud.githubusercontent.com/assets/8446518/7472901/4aa3745a-f337-11e4-846e-ac894b4e96dd.png)

**Comment by wachterjohannes** [comment]
we have to adjust the checkbox template to use following ht structure:

```html
<label for="checkbox1">
    <div class="custom-checkbox">
        <input name="nameForForm" id="checkbox1" type="checkbox" class="form-element">
        <span class="icon"></span>
    </div>
    Checkbox 1
</label>
```

**Comment by dmetzler1988** [comment]
Oh, can you create a small info-description field on bottom of the checkbox?

Example:
[  ] finished contest
     Check this, if the contest is finished

**Comment by wachterjohannes** [comment]
@berndhep do you have a design for something like this?

**Comment by berndhep** [comment]
@wachterjohannes Yes of course… take a look at the Mothership ;-)

**Comment by wachterjohannes** [comment]
@berndhep then we could use the "info-text" of the template for that! I think that could be a good usecase for that.

**Comment by berndhep** [comment]
There should exists a text label next to the checkbox. That's what they want, don´t they?
 
![bildschirmfoto 2015-05-12 um 08 25 06](https://cloud.githubusercontent.com/assets/7425459/7581216/897f471e-f880-11e4-9acd-7597f2798a4c.png)

**Comment by wachterjohannes** [comment]
you i have understand and see it (= i had only written that we could use the info-text (which is already configurable) for that (=

**Comment by danrot** [comment]
Togglers and Checkboxes can be used without a label and only a text right next to it in Sulu 2.0.
