### ISSUE TITLE
Portalredirect not working correctly for subfolder portals

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1068]
When I have a portal `sulu.lo/forum/{localization}`:  
`http://sulu.lo/forum/` redirects me to `http://sulu.lo/forum/en/forum` instead of `http://sulu.lo/forum/en`

**Comment by danrot** [comment]
This bug is only partially fixed. The described problem here is fixed, but if you go just to `sulu.lo/en` you'll end up with an endless loop of redirects.
