### ISSUE TITLE
Support multiple webspaces in the sitemap

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1129]
A sitemap should support more then one webspace

**Comment by chirimoya** [comment]
I'm not sure, if this is really a requirement.

**Comment by alexander-schranz** [comment]
maybe a better solution instead of one sitemap for all webspace for specific domains is a sitemapIndex file (http://www.sitemaps.org/protocol.html#index) same rules as for the sitemap (show only the webspaces under the requested domain)

**Comment by danrot** [comment]
@chirimoya I know it is an edge case, but what about two different webspaces with URLs like `www.example.org/webspace1` and `www.example.org/webspace2`? That's possible with our system, and so `www.example.org/sitemap.xml` should probably show the content of both webspaces. The mentioned sitemap index would also be my suggestion to solve this.
