### ISSUE TITLE
Error in massive:search:index:rebuild when content tree contains data from deleted webspace

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1166]
When running `app/console massive:search:index:rebuild` the following error appear

``` bash
PHP Fatal error:  Call to a member function getAllLocalizations() on a non-object in
/var/data/websites/sulu.lo/vendor/sulu/sulu/src/Sulu/Component/Content/Mapper/ContentMapper.php
on line 1633 
```

The error appears because for some pages $webspaceKey the `phpcr_workspace` name is used instead of the webspaceKey name:
``` php
 $webspace = $this->webspaceManager->findWebspaceByKey($webspaceKey);
```

Edit:

The error appears because of old data for a deleted webspace existed under /cmf/deleted_webspace/.

**Comment by chirimoya** [comment]
@dantleech can you have a look together with @alexander-schranz

**Comment by dantleech** [comment]
@alexander-schranz can you tell me the name of the `webspace`, and ideally provide a stack trace?

**Comment by alexander-schranz** [comment]
@dantleech @chirimoya the bug was that there was an old import with pages under /cmf/old_none_exist_webspace/cmf in the Content Repository would be that the search rebuild command only go on active webspaces.

**Comment by danrot** [comment]
@alexander-schranz What does that mean? Can this issue be closed now?

**Comment by alexander-schranz** [comment]
@danrot for me it need to be fixed that it only build the searchindex for configurated webspaces and don't watch on content repository which nodes are under /cmf

**Comment by dantleech** [comment]
This should not happen now with the latest release as the reindexer is been refactored and no longer scans the `/cmf` node.
