### ISSUE TITLE
Provide a way to retrieve all locale strings

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#1179]
Currently it is necessray to inject the `WebspaceManager` or `LocalizationManager` and do something like

``` php
$locales = array();
foreach ($manager->getAllLocalizations() as $localization) {
    $locales[] = $localization->getLocalization();
}
```

This means that client classes need to know about the `Localization` object, when all they need is an array of `locale` strings.

``` php
$locales = $manager->getAllLocales();
```

**Comment by alexander-schranz** [comment]
fixed by #4691
