### ISSUE TITLE
Fonts occasionally not loaded correctly in admin interface

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#1200]
Sometimes (rarely) the "Awesome" font set in the backoffice is not loaded, and you see bizzare characters instead of icons.

**Comment by danrot** [comment]
Could IMO be caused by a failing request, or as @3rfan suggested by a timing issue in the javascript code...

**Comment by danrot** [comment]
Although this sometimes also happens in the new UI, they appear after the font is loaded. I think that is good enough.
