### ISSUE TITLE
Preview: No error message for invalid HTML

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#1202]
For example:

````jinja
<ul>
    Hello
</ul>
`````

Is invalid HTML and will not work ("Hello" will not be displayed at all). 

There should be an error message.

**Comment by danrot** [comment]
Just tested, even if I have some content like this it works:

```html
<ul>Hello
```

So this should be solved... @wachterjohannes Is that correct? Are we using a less strict crawler now? If yes please close this issue.

**Comment by wachterjohannes** [comment]
yes we are not using the dom-parser after the refactoring. so this should be fixed.
