### ISSUE TITLE
Removal of "internal" content types

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#1220]
Internal content types are used for the "internal link" and "external link" forms.

Ostensibly they allow the user to customize these forms.

They have the following issues:
- RLP (resource locator) tag is used to nominate the field which should be used as the "reference" to the linked thing.
- `view`,  `controller` , etc elements serve no purpose. The internal types are used only to represent forms.
- The name of the property with the linked resource is mutable -- it would be better if this was a constant.
- They require that the "template" is changed if the "state" of the node is changed to be a redirect (internal or external). This causes issues and we had to introduce the `originTemplate` property as a work-around.

In their defense:
- They allow users to customize the forms  (but what use cases are there for this?)

I propose:
- We drop these types and let the redirect by an integral part of a document and the forms become immutable.

**Comment by danrot** [comment]
I also think that we should drop this, I don't see any value in making this configureable.

**Comment by dantleech** [comment]
The "internal" flag is also used for "excerpt". I am not sure what the implications of removing this are for that.

**Comment by wachterjohannes** [comment]
i think for the internal and external link its ok to drop it! but the excerpt should be customizable! perhaps we should think about dans idea to extract the "form" configuration out of the XML-Template to make it abstracter and let the usecase of the excerpt could then be done with an abstract "form"

**Comment by wachterjohannes** [comment]
@dantleech i have started with the fix for that and there i have a problem with the excerpt template:

https://github.com/sulu-io/sulu/pull/1040

**Comment by danrot** [comment]
This also causes a serious bug in the copy language function. If a language is copied for an internal link, the new copied page has no URL at all, and is not accessible on the website.

**Comment by wachterjohannes** [comment]
i have tested it now with current develop branch: the copied internal-link will be displayed in navigation and smart-content (smart-content ignores link-title => i will fix that today) in both are the right url without redirect!

**Comment by wachterjohannes** [comment]
@i have removed milestone because its not absolutely necessary to do that before 1.0! all related bugs are fixed! but still it should be done because its really a "shit" construct (=

**Comment by chirimoya** [comment]
ping @wachterjohannes @danrot

**Comment by wachterjohannes** [comment]
the only "internal" content-template which we use currently is the "excerpt" template which should be extensible. With our page-template system it is at least "overwritable". We have currently no possibility to migrate this to another feature. We  should really think about implementing a "form" template which could be used for this

**Comment by danrot** [comment]
Since only the excerpt tab seems to be left, I have added the removal of content types into the title of #4384, and I am going to close this one.
