### ISSUE TITLE
Media Sync Service

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1226]
A Service that can be configured to send notification to external urls that a new asset was uploaded or delete from sulu.

The notification contains the whole Media Api JSON Object so the external service can download the media store titles or something else.

E.g. For a Video Streaming Server

**Comment by danrot** [comment]
A little bit more information would be nice, I also don't know what the linked PR exactly does :wink:

**Comment by alexander-schranz** [comment]
Description updated, Example configuration added to PR.

**Comment by patkar** [comment]
Sadly the PR got closed. Sounds interesting, maybe useful for my owncloud integration

**Comment by danrot** [comment]
@patkar Doesn't mean that it is not implemented one day :-) As I have already written in the PR, it would be nice to not restrict that to the MediaBundle. I would like to see a general WebhookBundle (or something similar), which can be reused across a lot of bundles.

**Comment by patkar** [comment]
The point I want to make is that, if it is not done when I start it, maybe I can submit parts to move this feature forward ;)

**Comment by webmozart** [comment]
@patkar Go ahead! :) :+1:

**Comment by danrot** [comment]
The open question before we can start implementing this IMO is if we implement this a more generic `SuluWebhookBundle`, so that also other parts of the system can provide a service like this.

**Comment by alexander-schranz** [comment]
As we are now providing events in #5939 they can be used to send assets or other things to external services.
