### ISSUE TITLE
Websocket configuration in wrong bundle

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#1232]
The setting if the websocket should be used is located at `sulu_content.preview.websocket`, whereby it should be located somewhere under the `sulu_websocket` section.

**Comment by wachterjohannes** [comment]
i think it could be because its the same client in the frontend ... perhaps we should remove the `sulu_content` (:

**Comment by danrot** [comment]
Has been fixed in https://github.com/sulu/sulu/pull/2299
