### ISSUE TITLE
Flat navigation will not work on depth > 1

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#1252]
The `NavigationMapper` will not work on depths > 1, as it orders on the `sulu:order` and ignores the depth of all of the nodes found.

This was covered by a test in `ContentMappertest`, but it was using mocks and not the real data.

**Comment by danrot** [comment]
Looks to me like the nodes are read depth-first in pre order. How else should that be read? I would be in favour of closing this issue, since there is no clear way to do this. But at least all the selected items appear of all levels. /cc @chirimoya
