### ISSUE TITLE
Navigation/Breadcrumb Page from type internal link has uuid from linked site

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1271]
/cc @quehnie

**Comment by danrot** [comment]
@alexander-schranz can you describe further?

**Comment by alexander-schranz** [comment]
Example Navigation

 - Point 1 (Internal Link to Point 1.1) (false marked as current page)
  - Point 1.1(`active site`) (marked as current page)
  - Point 1.2 
 - Point 2 
  - Point 2.1 (Internal Link to Point 1.1) (false marked as current page)

To check which site is active in the navigation loop we check `uuid == navigationItem.uuid`
as Point 2.1 and Point 1 link to the current site they are also marked as current site.

Don't know whats correct uuid we should return. In this case you need the real uuid and not the linked, but in other cases you maybe need the linked site.

**Comment by danrot** [comment]
So the real issue you want to have solved is probably https://github.com/sulu-io/sulu/issues/492 (although I think the behavior should be like you described).

**Comment by alexander-schranz** [comment]
yeah #492 would fix this problem and the uuid would not be needed.
we should also keep in mind to flag the current page as `active` and the parent pages maybe as `activeParent` or `hasActiveChild`. The difference is sometimes needed e.g. to show the submenu as open when a child page is active.

**Comment by alexander-schranz** [comment]
As #492 is the real issue I close this issue. The current work around is using the path instead of the uuid for active navigation:

```
{% if path ~ '/' starts with item.path ~ '/' -%}
    class="active"
{%- endif %}
```
