### ISSUE TITLE
Deactivate download counting for backend downloads

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1284]
Maybe we should deactivate to increase the downloadcounter when a media is downloaded from sulu backend (media overlay, media overlay history). This can be done by adding the parameter `&no-count=1` to the url.

On the otherside maybe content manager just copy to embed it and will forget to delete `&no-count=1` and so the downloadcounter will not increased. 

The best solution would be to check if the user is logged into sulu backend and only increase it when not.

**Comment by danrot** [comment]
Not sure about the last suggestion. Especially if you use the SuluCommunityBundle the user might be logged in but the download counter should probably still increase... Can this be solved in any good way? Either we accept that the user might copy a URL with the `no-count` parameter, or we don't implement this, right?

**Comment by alexander-schranz** [comment]
As never requested, I will close this issue.
