### ISSUE TITLE
Change properties visibility definition from private to protected

### ISSUE THREAD

**Issue by sRmarcos** [sulu/sulu#1286]
We are having great problems trying to extend the functionality of different Classes. It would be great if you could change all (most) of the private properties and methods to protected, so it is possible to overwrite them or use them in child classes.

**Comment by danrot** [comment]
Which classes and properties are you talking about? There might be (maybe even a lot) cases where this makes sense, but I would not like to just make everything protected.

If you are mainly talking about our models, I can tell you that this will drastically improve in https://github.com/sulu-io/sulu/pull/1230, at least for the contacts. However, after this PR it is quite easy for us to adapt other models in this way as well, and we will progressively introduce this feature for other models. If you tell us which ones you need we might be able to plan accordingly.

**Comment by dantleech** [comment]
See also https://en.wikipedia.org/wiki/Composition_over_inheritance and http://ocramius.github.io/blog/when-to-declare-classes-final

**Comment by joemoe** [comment]
@sRmarcos, as you are creating some issues here on github, we would also like to invite you to our slack channel. if you want to join it just send me an email (johannes (at) sulu.io) and we'll invite you.

**Comment by sRmarcos** [comment]
One of the things that we tried is to extend the logic of the snippetBundle. We stoppt it when we realize that we were overwriting most of the classes. We also had issues extending some components. I agree that composition is better than inheritance, but I believe that it is really hard to do it always like this (or with a great overload).

**Comment by danrot** [comment]
In the latest release you should see that we introduced the `DocumentManager`, which should make this a lot easier: https://github.com/sulu-io/sulu/pull/1090

You can also find some documentation here: http://docs.sulu.io/en/latest/reference/components/document-manager/index.html

**Comment by sRmarcos** [comment]
I'll will give it a try and give you feedback. Thanks.

**Comment by danrot** [comment]
I think it still makes sense to keep certain properties and functions to private, otherwise we'll have a BC nightmare. And I think we should decide from case to case if something is private or protected, and cannot say that everything has to be declared the same way... So I am going to close this issue.
