### ISSUE TITLE
Twig function sulu_content_root_path(full = true) protocol missing

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1291]
sulu_content_root_path(full = true) will return sulu.lo/en without http://

**Comment by danrot** [comment]
Do you need the protocol here? I guess the browser will just use the already used one.

**Comment by alexander-schranz** [comment]
its the full url when there is no protocol e.g. you are on `sulu.lo/en/test` and you link to `sulu.lo/en` you will end on `sulu.lo/en/sulu.lo/en`

**Comment by wachterjohannes** [comment]
hmm perhaps we should append `//`i think this will use the current protocol

**Comment by danrot** [comment]
This seems to be fixed now.
