### ISSUE TITLE
Massive-search: Overriding search configuration does not work

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#1349]
When i want to extend the e.g. SuluContactBundle:Account Entity with SuluContactExtensionBundle:Account by overriding the massive-search/Account.xml file, it does not have any impact.
it still doesn't find any results.

**Comment by dantleech** [comment]
Did you rebuild the search index? `massive:search:index:rebuild` ?

**Comment by turbo-ele** [comment]
yes. that's actually how i tested if it works:
Rebuilding: Sulu\Bundle\ContactBundle\Entity\Account [OK] 0 entities indexed

**Comment by dantleech** [comment]
Ah ok. So you want to change the class FQN of the Account entity? and you want to do that by overriding (and/or extending) the original `Account.xml` file?

If so could you create an issue in MassiveSearchBundle?

**Comment by turbo-ele** [comment]
Yes, thats exactly what i wanted to do.
That's what i did so far:
https://github.com/sulu-io/SuluContactExtensionBundle/pull/18

**Comment by chirimoya** [comment]
@turbo-ele still an issue?

**Comment by turbo-ele** [comment]
Don't know what the outcoming of the discussion in https://github.com/massiveart/MassiveSearchBundle/issues/55 was. But for me this is not an issue anymore, since both the account entities are indexed.

**Comment by wachterjohannes** [comment]
currently it should work if you extend the entity. but if you want to add some "meta value" like concatenations which you want to use in the website you have to use the PRE_INDEX event where you can edit the "Document" which will be indexed. This is maybe the way we want to publish, but i would thought that there could be a better way. /cc @dantleech maybe i overseen something?

**Comment by danrot** [comment]
@turbo-ele @wachterjohannes @dantleech Anything left to do here?

**Comment by dantleech** [comment]
@wachterjohannes i think you can add those "meta" fields in the XML mapping no? Otherwise I think this discussion can be ended.

**Comment by wachterjohannes** [comment]
hmm yes thats right for the core team but not for a external developer which want to extend some indexing data.

**Comment by dantleech** [comment]
But is it not the case that the external developer can register their
own entity which extends the one they want to modify and change the
mapping there?

**Comment by wachterjohannes** [comment]
if you dont want to add properties but you want to add information which will be indexed.

**Comment by danrot** [comment]
Since this is more a MassiveSearch issue, and there is already an issue for that (massiveart/MassiveSearchBundle#55) I am going to close this issue.
