### ISSUE TITLE
SecurityChecker does not support anonymous users

### ISSUE THREAD

**Issue by kriswillis** [sulu/sulu#1361]
I've enabled the `SymfonySecurityBundle` in my `WebsiteKernel` in order to use the Sulu auth on the website side, however `SecurityChecker` does not work with anonymous users.

`SecurityContextVoter::vote` is expecting the user to be an object, but is the string `anon.` for anonymous users.

https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Component/Security/Authorization/SecurityContextVoter.php#L112

**Comment by danrot** [comment]
We should probably add some kind of configuration, to say what is happening if an anonymous user tries to access something.

Or what is your use case? I could also imagine that we just deny access as soon as there is any security for anonymous users.

**Comment by kriswillis** [comment]
My specific use case at the moment is implementing [FOSCommentBundle](https://github.com/FriendsOfSymfony/FOSCommentBundle); I've extended its `ThreadController` to implement Sulu's security functionality to allow anonymous users to add comments, but only authorised users can edit / delete them from within the admin.

I was expecting something like an HTTP 401 when attempting to edit a comment as an unauthorised user.

**Comment by danrot** [comment]
Ok, that should be possible of course... The question only is what the result for anonymous users should be in general... I am not sure about that.

**Comment by kriswillis** [comment]
I think HTTP 401 across the board makes sense. If they're trying to access a resource that requires authorisation and they don't have it, they should get a "401: Unauthorized" response.

**Comment by danrot** [comment]
I just tried it again, and could not reproduce the issue... Therefore closing it.
