### ISSUE TITLE
Support formatting of datetime fields in the table view

### ISSUE THREAD

**Issue by kriswillis** [sulu/sulu#1405]
When a field has a type of `date`, its contents are formatted as `n/j/Y`, however `datetime` type fields show the date as given in the JSON response, generally ISO 8601 (e.g. `2015-07-12T15:21:32+0100`)

**Comment by chirimoya** [comment]
What is your expected format for the list? Are you only missing the time?

**Comment by kriswillis** [comment]
I'd imagine `n/j/Y H:i:s` would be suitable for a `datetime` field?

**Comment by danrot** [comment]
You are definitely right, this way some information is lost...

**Comment by wachterjohannes** [comment]
we should introduce a `datetime` and `time` field type in datagrid which would be very easy! then the developer can define what he want to display.

**Comment by wachterjohannes** [comment]
this was introduced by https://github.com/massiveart/husky/commit/d710f3da8a095ad0d8e93e64b5e6313f54460ca4
