### ISSUE TITLE
Text editor allow default configuration for all editors

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1461]
Add a config.yml parameters to TextEditorContentType for Default Configuration.

In most cases when you want configured the texteditor you want that for all templates.
Currently you need to configured it for each text editor property in each template.

**Comment by wachterjohannes** [comment]
Hmm perhaps we should provide a config section in webspaces xml file for that! I thought about a lot of other stuff to put into this!

**Comment by danrot** [comment]
We should decide wether to put this into the webspace xml file, or in the app config. Or even in both? I suggest that you can have this setting in the app config, and it can be overridden by the webspace and template configuration. /cc @chirimoya @wachterjohannes

**Comment by wachterjohannes** [comment]
:+1:

**Comment by chirimoya** [comment]
+1

**Comment by danrot** [comment]
In Sulu 2.0 with CKEditor5 it is possible to extend the entire editor in JS, I think that somehow solves this issue.
