### ISSUE TITLE
Validation error does not scroll to invalid field

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#1470]
When i don't fill the mandatory fields in a template and press save. The template doesn't scroll to the fields, it just feels like nothing happens. No Error, no Submit. So what if mandatory fields are at the bottom of a Template? Shouldn't it scroll down or give some error feedback?

**Comment by danrot** [comment]
Related to https://github.com/sulu-io/sulu/issues/408

**Comment by danrot** [comment]
In Sulu 2.0 the form shows an error if there is an invalid field
