### ISSUE TITLE
Removing some permissions from user groups causes errors on other interfaces

### ISSUE THREAD

**Issue by kriswillis** [sulu/sulu#1482]
# Reproducing

If you were to remove all categories permissions from a group, users within that group then get errors within other interfaces (that use categories) that they do have permission for. If you were to navigate to edit a person, an alert with "Operation forbidden. The available permissions are not sufficient for this operation" is displayed, and the category selection has an infinite loading animation (due to the XHR failing with a 401).

Similarly, this also happens when removing "Organizations" permissions from a user; when they they try to edit a user an error alert is shown.

Again, removing permissions for "Tags" has a similar effect.
# What should happen

When a user doesn't have any permissions on an entity, controls for this entity should not be displayed. For example, having removed all permissions on "Categories", when navigating to edit a Person, the Category selection should not be visible, if they only have "view" permissions, the selection should be displayed read-only, etc.

**Comment by danrot** [comment]
Disabling elements in the interface the user is not allowed to use is on our list, but I am not sure if we want e.g. the categories to be hidden then completely...

**Comment by danrot** [comment]
This also occurs when the user has no permission to view roles and he tries to update the security for collections:

![image](https://cloud.githubusercontent.com/assets/405874/15185844/fd6cc7b6-179a-11e6-82f5-76960a8a0654.png)

And the same goes for the permission tab in pages, ...:
![image](https://cloud.githubusercontent.com/assets/405874/15185857/0fd991fe-179b-11e6-88ed-bfaa5d6a2584.png)

**Comment by danrot** [comment]
We have mitigated this issue, by using the `EDIT` permission to decide if a navigation item should show up. So you can keep the `VIEW` permission selected on every entity that is needed by the user to successfully work with the system.

Hiding fields based on the permissions raises new questions and making stuff more complicated as it currently is, so we are not fixing it this way.
