### ISSUE TITLE
Unable to change a single_internal_link if the referenced node has been deleted

### ISSUE THREAD

**Issue by kriswillis** [sulu/sulu#1495]
1. Create an external link node
2. Create a new page with a template that has a `single_internal_link` content type
3. Select node created in 1 within a `single_internal_link`
4. Save page
5. Delete node created in step 1
6. Edit page created in step 2
7. XHR looking up the linked node returns a 404, "Select single internal link" modal has infinite loading animation

**Comment by danrot** [comment]
I think the problem is that the `SingleInternalLink` class uses the `SimpleContentType`. This means that the value is saved as simple string in PHPCR instead as a reference. If it would be a reference the property would be cleared, when the referenced node gets deleted.

**Comment by kriswillis** [comment]
Would changing this to a reference also cause the BC break described in #545 ?

**Comment by danrot** [comment]
Yeah exactly, that would be a BC break, but I don't see another good way to fix this... The data would not be the problem, it's quite easy to write migrations for that, would be a single command to update, but all the twig templates using this content type would have been to be updated...

**Comment by wachterjohannes** [comment]
currently this bug is partly fixed you can remove the wrong value or change it.the next question is should we use "weak" references here?

**Comment by chirimoya** [comment]
@danrot ... please validate if still is a bug and add a new issue for a clean solution with references. thx

**Comment by danrot** [comment]
The described problem does not occur anymore, and as long as the [sulu:link tag](https://github.com/sulu/sulu-standard/blob/655a8ddbd87d4405a82e946d45bc1576add63942/src/Client/Bundle/WebsiteBundle/Resources/themes/default/templates/example.html.twig#L127) is used to render it on the page there is also no error on the website when the page gets deleted. So I think we can consider this issue solved.

For the issue with the reference we still have https://github.com/sulu/sulu/issues/545
