### ISSUE TITLE
Homepage is never shown in navigation

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#1527]
The homepage of the website is not returned as part of the navigation (doesn't matter if tree of flat), even if it has some navigation contexts.

**Comment by wachterjohannes** [comment]
how should this be handled? In my opinion a homepage should be handled like the other pages.

But this will be a BC break - at least when you call `get_navigation` without context

/cc @danrot @chirimoya how should we handle this?

**Comment by wachterjohannes** [comment]
it would be quite easy to fix - we only have to add a additional `or issamenode` condition here https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationQueryBuilder.php#L45

**Comment by danrot** [comment]
If I think about it again it doesn't make too much sense to have a navigation context on the homepage. It would basically mean that there is always only one item on the most top level, if you retrieve the navigation as a tree. It would basically only make sense for the flat representation. Maybe we should not display this dropdown for homepages at all, and if somebody wants to have the homepage as a navigation item, an internal link has to be created?

**Comment by alexander-schranz** [comment]
when then the homepage should be on the same level as the content pages. but would agree not to display the dropdown on homepages. internal link seems for me a good solution for this who want the homepage in a navigation.

**Comment by danrot** [comment]
@chirimoya That's actually also interesting for the new UI. Do you think the navigation dropdown should be shown in the settings tab of the homepage? Or should the return value of the navigation be fixed in someway.

**Comment by PhilippSchreiber** [comment]
Just jumping in from a user perspective: 

If someone adds the home page to a nav context (like I did just 60min ago) it should appear there. If the user gets a tree with only the home page on the top level he would know what just happened. If the home page simply does not appear everyone will search for a bug and then after 60min debugging his own code base will do a google search and find this issue on github ;)

In my case I want to get a flat navigation and now it's a pain for me to add the home page (from a SEO perspective an internal link with a 301 redirect is a really bad solution!).

Please do not "protect" the users.

**Comment by alexander-schranz** [comment]
@PhilippSchreiber sorry that you had to fight with this issue. Just want to mention it that when creating a Page from Type Internal Link add it to the Navigation there will be no 301 Redirect as it will directly link to the homepage so there will be no difference or SEO issue. Else your dev did maybe use the false attribute to create the navigation, please check that the navigation is build using the `url` attribute and not the path attribute.

**Comment by PhilippSchreiber** [comment]
OK, please forget the part with 301 (I did not test that, sorry).

**Comment by danrot** [comment]
Fixed in #5232
