### ISSUE TITLE
Logged out while editing, lost all changes

### ISSUE THREAD

**Issue by joemoe** [sulu/sulu#1536]
Reproduce:
Got to a site or something. Edit stuff. Wait some time. Klick back in the window. You'll be redirected to the login-page. After login in all the changes are lost.

What I expected: 
Don't log out till I hit save. A warning message. Auto-Draft saves. Something like this.

What happened:
Was redirected to the login screen, everything was lost after login.

**Comment by berndhep** [comment]
Offer new login in an overlay window when session has expired.

**Comment by chirimoya** [comment]
already fix in the development branch
