### ISSUE TITLE
Incorrect output of the url in the SEO tab

### ISSUE THREAD

**Issue by c00n84** [sulu/sulu#1542]
I get the url from EN, but I'm in DE. I should get '/de/test-1' in the SEO preview.

<img width="862" alt="bildschirmfoto 2015-08-31 um 15 10 54" src="https://cloud.githubusercontent.com/assets/841720/9579462/13514720-4ff3-11e5-8fc2-29438d52b631.png">

**Comment by crash0verride** [comment]
@c00n84 and it looks like the URL is not updated when I change it for a page, it still displays the URL from the URL history (and not the current URL)
