### ISSUE TITLE
The column-view gets started by the same parent-view as the content-edit

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#1553]
The column-view of the content-bundle has the same parent-view (`content/main.js`) as the content-edit, although the column-view needs barely any code of `content/main.js`.

```
// list all contents for a language
sandbox.mvc.routes.push({
    route: 'content/contents/:webspace/:language',
    callback: function(webspace, language) {
        return '<div data-aura-component="content@sulucontent" data-aura-webspace="' + webspace + '" data-aura-language="' + language + '" data-aura-display="column" data-aura-preview="false"/>';
    }
});
```

At the moment the main responsibilities of `content/main.js` are to start the header and the preview, both for the content-edit. Loading data is currently the only functionality which gets used by the column-view as well as the content-edit and is implemented in `content/main.js`. However loading necessary data would in my opinion better be implemented in an own requre-js-component.

**Comment by marcelmoosbrugger** [comment]
The content-bundle would profit a lot from the new front-end architecture as implemented in the media-bundle and the contact-bundle.

**Comment by danrot** [comment]
With the latest refactoring I don't believe that we do anything about that.
