### ISSUE TITLE
content-block frontend behaviour is implemented in validation-type

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#1554]
In every other more complex content-type the frontend behaviour is implemented in an aurajs-component. The validation-type's responsibility is it to tell the mapper how to pass data to and retrieve data from the aurajs-component.

Like for example the smart-content has an own aurajs-component which does the rendering and handles the overlay etc. The validation-type of the smart-content essentially consists of getters and setters for plain data.

For the content-blocks, however, rendering, handling of visual effects and validation is all done in the validation-type.

**Comment by wachterjohannes** [comment]
hmm we could think about that but then its harder to manage the subforms in a single block ... for me its another type of content type as smart-content.

**Comment by danrot** [comment]
Again, because of the latest refactorings I don't think we'll change something here.
