### ISSUE TITLE
UserRepository:loadUserByUsername should be renamed...

### ISSUE THREAD

**Issue by rs2487** [sulu/sulu#1555]
... to loadUserByUsernameAndSystem, because the name suggests, that only the username is a credential for loading the user. But when the System does not match, no user is returned.

**Comment by wachterjohannes** [comment]
we need that function to provide the login functionality for symfony: http://api.symfony.com/2.7/Symfony/Component/Security/Core/User/UserProviderInterface.html#method_loadUserByUsername and the system is included there ... maybe we should extract this provider functionality in an own service! /cc @danrot @chirimoya

**Comment by danrot** [comment]
I don't see the point here... also if you put that into an own service, the name still has to be kept, because that's what the interface says. Therefore it's not possible to rename this method.

**Comment by rs2487** [comment]
I will not be the last, who uses this function to load a user, without knowing that the correct system is needed. Why is the system checked in this method?

**Comment by danrot** [comment]
Then it has to be documented, but I don't see a way around this. The system is checked because only users being in the Sulu system are allowed to log into Sulu. And as said we can't change the name because the interface is defined this way in Symfony.

**Comment by rs2487** [comment]
I understand that the method name can't be changed but limitation on a system - in my view - is a kind of authorization check that should not be handled in this method.

**Comment by wachterjohannes** [comment]
you cannot rename the function but you can circumnavigate this problem with extracting a `UserProvider`.

* Rename function in the `UserRepository` to `findUserByUsernameAndSystem`
* Remove Interface from `UserRepository`
* Create a `UserProvider` which uses the `UserRepository`

**Comment by danrot** [comment]
The `UserRepository` doesn't have this method anyway anymore :slightly_smiling_face:
