### ISSUE TITLE
Preview in content-edit is not on own aura-component

### ISSUE THREAD

**Issue by marcelmoosbrugger** [sulu/sulu#1561]
In the content-bundle the preview should - with all its (frontend-)functionality and visual parts - be encapsulated in an own aura-component. At the moment there exists a requirejs-module which contains some of the functionality. Rendering however is done in the 'content/main.js' file.

**Comment by marcelmoosbrugger** [comment]
@wachterjohannes Is this issue fixed with the implementation of the PreviewBundle?

**Comment by wachterjohannes** [comment]
Yes this is fixed (:
