### ISSUE TITLE
Lots of duplicated code in the js-views

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#1563]
In the frontend-views of the bundles we have a lot of duplicated code, which increases the complexity. This is a major hurdle for external developers. We may have some hooks like 'header' and 'layout', which take care of some of the visual tasks a view has, but for the main functionality, like e.g. saving data, a developer of a bundle doesn't get much support.

@danrot implemented an 'itembox' type-extension (in the husky-framework), which gets used by the internal-links-component and the media-selection component as they share a lot of functionality.
(https://github.com/massiveart/husky/blob/develop/husky_extensions/itembox.js)

For views and tab-views we could make use of the same mechanism. In the admin-bundle we should implement e.g a basic 'sulu-view' extension which holds some "abstract" methods like 'render', as well as a 'sulu-saving-view' extension, which extends the 'sulu-view' with some methods.

In the return block of view in a bundle a external developer could then just type the following.

```
return {
    type: 'sulu-saving-view';

     // here would follow the component-methods
}
```

This would then inject the methods of the 'sulu-saving-view' into the bundle-component.

If we create a 'sulu-main-view' and 'sulu-tab-view' it may be possible to handle to whole communication between tabs and their main-views in the extensions.

**Comment by wachterjohannes** [comment]
i have extracted a lot of functionality for default options, templates, translations and events into an extension. https://github.com/sulu-io/sulu/pull/1606

**Comment by danrot** [comment]
Gonna close this, since the react rewrite should fix this :-)
