### ISSUE TITLE
Warn about potential content loss when changing tabs

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1574]
When you write an article and want to set the SEO, Sulu will not warn that you should save before switching to another tab.

**Comment by danrot** [comment]
#730 has already implemented that, but this PR is probably not easy to make mergeable anymore.

**Comment by reflexxion** [comment]
+1

Would be really appreciated.

**Comment by stein189** [comment]
+1

**Comment by alexander-schranz** [comment]
@danrot @chirimoya do we have still this behaviour in 2.0 that you loses your changes when switching a tab?

**Comment by chirimoya** [comment]
yes, the behaviour will stay the same.

**Comment by danrot** [comment]
Has been done in #4430
