### ISSUE TITLE
collapsed labels do not display a label counter like uncollapsed labels

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#1603]
see label counter "7"
![labels_uncoll](https://cloud.githubusercontent.com/assets/13310795/9961473/0ab196c4-5e21-11e5-93b8-e0d39e0b0567.PNG)
![labels_collapse](https://cloud.githubusercontent.com/assets/13310795/9961472/0ab03144-5e21-11e5-8145-de6adfe8c848.PNG)

this should be implemented in the husky labale-component

**Comment by danrot** [comment]
I don't think we'll change that in the old UI :see_no_evil:
