### ISSUE TITLE
Live preview loses smart content value

### ISSUE THREAD

**Issue by joemoe** [sulu/sulu#1608]
I got a content type with a smart content and an image (compare to the sulu.io Blog).
In the smart content my user is selected via a tag.
When I update the image the live preview loses my user and changes to the default user.

At first:
![bildschirmfoto 2015-09-21 um 13 43 15](https://cloud.githubusercontent.com/assets/68620/9991094/4023c42e-6067-11e5-85d5-2686d400de30.png)

But after updating:
![bildschirmfoto 2015-09-21 um 13 43 35](https://cloud.githubusercontent.com/assets/68620/9991102/543cf78c-6067-11e5-8ffe-cf92331f01a0.png)

**Comment by wachterjohannes** [comment]
maybe fixed with this PR https://github.com/sulu-io/sulu/pull/1597 which is not finished

**Comment by wachterjohannes** [comment]
@danrot do you have testet this after merging #1597 ?

**Comment by danrot** [comment]
I kept the issue open, guess the easiest way to test this, is to update sulu.io, and repeat the steps @joemoe described.

**Comment by chirimoya** [comment]
@wachterjohannes @danrot ping

**Comment by danrot** [comment]
@chirimoya Has sulu.io been updated since the last comment? Then we could test this behavior there.

**Comment by wachterjohannes** [comment]
this should be fixed but we have to test it! there was a bug which causes non serialized blocks. i think this is the same issue and therefor should it be fixed.

**Comment by danrot** [comment]
This seems to be fixed in Sulu 2.0 :slightly_smiling_face:
