### ISSUE TITLE
Roles with spaces generated key have also spaces

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1616]
E.g. Role `Client Website` -> `ROLE_SULU_Client Website` It should be  `ROLE_SULU_Client_Website` so it can be used correctly in the security.yml

**Comment by chirimoya** [comment]
@danrot fixed?

**Comment by danrot** [comment]
No... The problem here is uniqueness. If we transform the role name as suggested by @alexander-schranz it's not possible to have a role `Client Website` and a role `Client_Website` at the same time. Might be an edge case, but this might get even worse if we start to escape other characters as well.

**Comment by danrot** [comment]
If we want to support the usage of these roles in `security.yml` (which is probably a good thing, although I am a bit sceptical... What happens if the role gets deleted? Maybe it's not the best idea to directly use these user generated roles in the `security.yml) it might be better to not allow character not being usable there at all.

**Comment by wachterjohannes** [comment]
hmm in my opinion it should be useable in the security.yml! but then it has to be possible to set permissions on it that it cannot be changed anymore. We should also add a `key` field which cannot be changed anymore once set. This key can then be used to generate role names

**Comment by danrot** [comment]
How do you generate the role names for roles without keys? That solution has some edge cases which are quite hard to solve. As said, if we want to support this feature, the name should not be allowed to contain spaces and other problematic characters. And the roles used this way have to be protected even more efficient as it would be done by the security, absolutely nobody should be allowed to delete these roles. So we would probably have to introduce a flag somewhere in the system.

**Comment by alexander-schranz** [comment]
would be fixed if the symfony roles are not longer generated by the sulu role name: #3675

**Comment by danrot** [comment]
Can we boil that down to only one of these two issues?

**Comment by danrot** [comment]
Closing in favour of #3675
