### ISSUE TITLE
Introduce categories component to capsule datagrid configuration

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#1628]
See https://github.com/sulu-io/sulu/blob/aa88f37a5a5560daa14ed71da2db794b82f646bb/src/Sulu/Bundle/CategoryBundle/Resources/views/Template/content-types/category_list.html.twig

**Comment by danrot** [comment]
Can you elaborate a bit more what this is about?

**Comment by wachterjohannes** [comment]
we should create a `category-select` component to capsule the configuration for the datagrid ... if you want to include categories into a form you have to include the datagrid with the whole configuration and not only the `category-select` component (:

**Comment by danrot** [comment]
I don't think we'll change that in the old UI anymore :slightly_smiling_face:
