### ISSUE TITLE
Can't get Number of total items in paginated smartcontent

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#1629]
Hey Sulu Team,

I just created a paginated Smartcontent like this:

![bildschirmfoto 2015-09-25 um 11 44 20](https://cloud.githubusercontent.com/assets/8446502/10097653/d7290580-637a-11e5-9218-d46113838e4f.png)

But it isn't possible to give me back the total amount of items in the smartcontent on my twig page.
I only can get smartcontent|length and this is always 8 or less (last page).
Can we add a variable like total_items?

**Comment by danrot** [comment]
Actually this is not possible for performance reasons... So I am going to close this issue.
