### ISSUE TITLE
Property::__get($property) not required?

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#165]
https://github.com/sulu-cmf/sulu/blob/develop/src/Sulu/Component/Content/Property.php#L296

Implements a method `magic getter for twig template`. But this should not be necessary as Twig already will automatically interpret `foo.bar` as `foo->getBar`

**Comment by danrot** [comment]
Anybody wants to take this one? It shouldn't be too much work, and I am trying to lowering the number of our issues :-)

**Comment by danrot** [comment]
Since this class has now been moved to a `Compat` namespace, and I don't want to make this change I consider breaking before 3.0, I am going to close this issue. This entire namespace should be gone in 3.0 anyway.
