### ISSUE TITLE
No error message shown in the UI when there is an Ajax 500

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#1652]
Currently the exists still an issue when there is a 500 error from an AJAX request and the UI just hangs and does nothing without giving any feedback.

I think this is a regression, as before there was at least a red banner saying that there was an error. It should also display the primary error message form the exception.

This is really important when developing (it would save ALOT of time and frustration) and also from a user perspective - as they would be better able to report errors, and so make fixing bugs easier.

**Comment by berndhep** [comment]
We will discuss this for the 1.2 release. The error message has been removed because it frustrated the content managers. But I understand that it might be useful for devs.

**Comment by dantleech** [comment]
> The error message has been removed because it frustrated the content managers

Is it not more frustrating if there is no error message and the application just stops working?

I think this is really important for not only good dev experience, but also good user experience.

**Comment by danrot** [comment]
This is fixed in certain places, and if we find more where something like this is happening we have to fix it there as well, but I don't see any reason to keep this issue open just in case. So I am going to close it.
