### ISSUE TITLE
Best practice: Custom element in CKEditor

### ISSUE THREAD

**Issue by lennerd** [sulu/sulu#1682]
I would like to have blockquotes in certain CKEditors based `text_editor`s. From the CKEditor perspective there are many ways to add this–e.g. plugins or styles.
But both techniques seems to not work in the current version as passing some kind of array/object structure to the aura/husky component failes.

``` xml
<property name="text" type="text_editor">
    <meta>
        <title lang="en">Text</title>
    </meta>
    <params>
        <param name="styles_set">
            <param name="name" value="Quote" />
            <param name="element" value="blockquote" />
        </param>
    </params>
</property>
```

I wonder what you are doing in such cases? Do you have any best practice?

Thanks in advance.

**Comment by danrot** [comment]
I guess this setting is just not made available in our content type so far. It would probably help to see how this is done in a pure ckeditor instance, can you maybe paste an example here?

**Comment by lennerd** [comment]
I think the problem is here, as this code should also be able to handle nested params and passing anything deeper as JSON to the attribute:

https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/text_editor.html.twig#L7-L17

I'm not sure how aura handles JSON filled parameters. Maybe this needs to be fixed on both sides.

Talking about CKEditor:

``` js
// Load from a list of definitions.
config.stylesSet = [
    { name: 'Strong Emphasis', element: 'strong' },
    { name: 'Emphasis', element: 'em' },
    ...
];
```
The `stylesSet` configuraiton is handled by husky. But as you can see an the linked snippet above, nested parameters are not passed into the component element.

Another way would be plugins:

``` js
config.extraPlugins = 'myplugin,anotherplugin';
```
This is passed as expected, but we need to add the code for the CKEditor plugin somewhere somehow. The documentation says that the plugin files need to be in the CKEditor directory inside `plugins`, which means we would have to add files to a vendor folder (SuluAdminBundle) inside a vendor folder (husky) inside a vendor folder (ckeditor). But maybe there is a way in CKEditor to register other plugin locations.

**Comment by alexander-schranz** [comment]
aura should have no problem to insert an array.
did you try the following param @lennerd :

```
<param name="styles_set" value="[{&quot;name&quot;:&quot;Strong Emphasis&quot;,&quot;element&quot;: &quot;strong&quot;},{&quot;name&quot;:&quot;Emphasis&quot;,&quot;element&quot;:&quot;em&quot;}]" />
```

**Comment by alexander-schranz** [comment]
@lennerd in the ckeditor there is also a way to add a custom config over the `customConfig` parameter maybe you can use this to add new plugins over the addExternal function, but I did not test this way. I did only found a tutorial for 3.x version but the parameter customConfig parameter still exist in 4.x so it should maybe the same way: http://ckeditor.com/forums/CKEditor-3.x/Tutorial-create-external-plugin-for-CKEDITOR

``` xml
<param name="custom_config" value="/your/path/config.js" />
```

**Comment by lennerd** [comment]
The custom config option is a very good idea. Thank you looking this up. I will come back with some experience. Maybe I can make a PR for the documentation, too.

**Comment by alexander-schranz** [comment]
currently it seems to be ckeditor a problem with underlines params.
Seems we need to prevent to convert snake_case to camelCase because ckeditor params are mixed. This will be an BC break for exist configuration (extra_allowed_content, past_from_word, ...). So we need to break our condition for the text_editor that all param names need to be in snake_case. @danrot

**Comment by lennerd** [comment]
I hadn't the time yet to test the `custom_config`. Are you sure, it's the same here? Or could that maybe be a solution for now too add a complete javascript configuration file?

**Comment by danrot** [comment]
Going to close this issue, since the CKEditor in Sulu 2.0 works different anyway.
