### ISSUE TITLE
Redirect to originally requested page after login

### ISSUE THREAD

**Issue by joemoe** [sulu/sulu#1684]
When I want to login, but do not have the right to access the page the login form is shown. After logging in I get redirected to /admin, but I want to get redirected to the page I originally requested.

**Comment by wachterjohannes** [comment]
i have tried this on the current dev-develop and for me it works ... how did you try that?

**Comment by joemoe** [comment]
i implemented a custom controller that lives that uses the admin kernel and is under security.

**Comment by danrot** [comment]
@wachterjohannes They way you have tried it works because we make use of the hash of the URL, which just has to be appended to `/admin`. TBH I didn't think about the use case @joemoe is describing here...

**Comment by joemoe** [comment]
when everything else that ships with sulu works with hashes it isn't too important.

**Comment by danrot** [comment]
That works in Sulu 2.0 :slightly_smiling_face:
