### ISSUE TITLE
List Builder usage of HYDRATE_SCALAR result

### ISSUE THREAD

**Issue by chirimoya** [sulu/sulu#1729]
Try to make use of HYDRATE_SCALAR

**Comment by danrot** [comment]
@alexander-schranz Haven't we tried that, but it doesn't work, because the types don't match if using scalar?

**Comment by alexander-schranz** [comment]
@danrot thats correct. scalar is a raw result so all fields are string so no int, floats and not sure what format the date or datetimes were.

The doctrine issue: https://github.com/doctrine/orm/issues/7447
