### ISSUE TITLE
Improvements of SEO Tab

### ISSUE THREAD

**Issue by crash0verride** [sulu/sulu#1732]
The current SEO Tab should be improved, changed with the following:
- [x] Add title for SERP Preview
- [x] Left aline SERP Preview
- [ ] Add correct titles for elements (as in code: Meta Title, Meta Description, Meta Keywords)
- [x] Add counter for Title length (55 Characters with Space recommended)
- [x] if possible change color to red if character count is 0

![seo tab](https://cloud.githubusercontent.com/assets/3469973/10879940/6b8b7e3e-8157-11e5-8d91-99d978e0bf7a.png)

**Comment by danrot** [comment]
@berndhep Do you agree? Should this be done before the 1.1 release?

**Comment by berndhep** [comment]
@danrot No, that's 1.2
