### ISSUE TITLE
template.xml block sortmode.show tag

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#1735]
Before the Sulu redesign. I could change the visible content in contentblock sortmode easily with adding a tag to those propertys i wanted to see there.

`<tag name="sulu.content.sortmode.show"/>`

Now it just shows the first 3 things:

![bildschirmfoto 2015-11-02 um 15 20 08](https://cloud.githubusercontent.com/assets/8446502/10884004/e8dd6654-8175-11e5-85c6-b9529e9b4372.png)

So in my 2nd Textblock there is a checkbox and so i get true as a preview.
Is there any possibility to solve this with a tag or is this feature gone?

**Comment by wachterjohannes** [comment]
@Quehnie i have fixed yesterday (https://github.com/sulu-io/sulu/pull/1842) that you don't see the checkbox value (: @berndhep is this enough or should we reintroduce the tags for the devs?

**Comment by danrot** [comment]
This also does not appear on Sulu 2.0, therefore going to close it.
