### ISSUE TITLE
Use MicroKernels for easier configuration

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#1757]
@weaverryan has suggested to use the new [MicroKernels feature](https://github.com/symfony/symfony/pull/15990) of Symfony 2.8 to make the configuration loading easier.

**Comment by dantleech** [comment]
This might also help with testing, as we would have less issues with configuration duplication.

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu-standard/issues/621

**Comment by webmozart** [comment]
Can this be closed in favor of that issue?

**Comment by chirimoya** [comment]
Not sure, I think they are related and don't replace each other.

**Comment by danrot** [comment]
I'd also say that the usage/supporting of micro kernels is a separate decision.

**Comment by danrot** [comment]
I think that's not a single issue anymore, we have to handle that properly anyway when we want to support Symfony flex. #3768 is probably already a start in the right direction, and then it is not in our hands anymore to tell how the kernel is created.
