### ISSUE TITLE
None parent category rows should be clickable

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1774]
You can only click on the checkbox. It would be more user friendly that the whole row is clickable to check or uncheck checkboxes of a none parent category.

<img width="818" alt="bildschirmfoto 2015-11-12 um 09 30 36" src="https://cloud.githubusercontent.com/assets/1698337/11113811/146eadda-8920-11e5-85b6-2220a08078ae.png">

**Comment by danrot** [comment]
After a discussion with @berndhep we came up with the following solutions:

* Only use the blue icon with the pencil to get into the edit form
* Single click on element only opens the children
* Double click any element to open the edit

**Comment by alexander-schranz** [comment]
this issue was more related to the category list in the content (excerpt) where is no edit mode.

**Comment by danrot** [comment]
Doesn't matter, there has still to be consistency between all these representations. And especially a single click on a line should always have the same action, and not differ based on if a category has children or not.

**Comment by alexander-schranz** [comment]
As this behaviour will not be changed in 1.x version and the 2.x has a new UI I will close this issue.
