### ISSUE TITLE
sulu_seo twig extension title, pre and/or postfix

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#1791]
Wouldn't it be good to have an option to pre or post fix the title-tag like:

Page Title | Company Name

or 

Company Name - Page Title

for constants in titles.

**Comment by wachterjohannes** [comment]
@berndhep @crash0verride what do you think?

**Comment by berndhep** [comment]
This would be a function for the webspace settings. You'd have to define a webspace title first and then define globally (for all nodes of the webspace) the pre- or postfix setting.  SEO consequences, @crash0verride ?

**Comment by danrot** [comment]
Shouldn't that be replaced by https://github.com/sulu-io/sulu/issues/2050 ? I like the suggested solution there. I'd say we can close one of these issues.

**Comment by danrot** [comment]
Closed in favour of #2050
