### ISSUE TITLE
Mysql 5.7.9 order by clause error

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#1797]
We should find a way to use mysql 5.7.9 because it is now also in brew and will update in many machines in the next time. i have only found one issue in drupal which is nearly the same.

https://www.drupal.org/node/2545480

**Comment by wachterjohannes** [comment]
to fix the version of mysql in mac run following commands:

```bash
$ brew uninstall --force mysql
$ brew tap homebrew/versions
$ brew install mysql56
```

**Comment by wachterjohannes** [comment]
if you have problems to start the server try to remove following files:

* /usr/local/var/mysql/ib_logfile0
* /usr/local/var/mysql/ib_logfile1

**Comment by alexander-schranz** [comment]
At the current project I also did build a tree like categories. I removed the group by and add 2 fieldDescriptors ('lft', 'rgt') and did then check with them if `lft + 1 === rgt` hasChildren. so no children need to join and the group by is not longer needed.

**Comment by wachterjohannes** [comment]
This would also solve the problematik with the strict mode in this bundle!

**Comment by danrot** [comment]
Which code exactly was affected here? Categories and Media? I guess for the categories it could be fixed with https://github.com/sulu/sulu/pull/2671
