### ISSUE TITLE
Display media assignment in contact/accounts after tab switching is not correct

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#1810]
When assigning media to a contact/account and switch to another tab (e.g. details) and switch back to the documents tab and opening the media-selection-overlay, the selections are not correct. 

![bildschirmfoto 2015-11-20 um 10 36 31](https://cloud.githubusercontent.com/assets/5152633/11296480/a0a7d03a-8f72-11e5-8fb1-cec192604151.png)

Also the displayed amount of selected images (see screenshot) is not correct when deleting documents directly in the list (not over the overlay).

**Comment by nnatter** [comment]
@danrot: this should be fixed with https://github.com/sulu/sulu/pull/2704

**Comment by danrot** [comment]
@turbo-ele: Can you test that behavior on develop, and see if @nnatter is right? If yes please close the issue again.

**Comment by danrot** [comment]
Have tested it once more, is really fixed.
