### ISSUE TITLE
NodeType change doesn't affect preview

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#1819]
The node type only affects the appearance of the preview initially. That means on the first load it appears if the page has the node type content, and doesn't appear on internal and external link. But if the node type changes the preview stays (if e.g. switch from content to internal) or doesn't appear (if e.g. switch from internal link to content).

**Comment by danrot** [comment]
We should make sure that this will work correctly in the 2.0 release.

**Comment by alexander-schranz** [comment]
Works as described in this issue now in 2.0. When you switch to internal or external link the Preview is not shown when switching to content type its shown immediately
