### ISSUE TITLE
Autoname behavior exception

### ISSUE THREAD

**Issue by c00n84** [sulu/sulu#1825]
When autoname behavior causes a path change an exception is thrown if the moved node has references to its children.

Steps to reproduce:
1. Create page in EN (Page 1) - published
2. Create child page in EN (Page 1.1) - published
3. Set internal Link in EN on Page 1 to Page 1.1
4. Change title in EN of Page 1 > Exception

**Comment by alexander-schranz** [comment]
cannot reproduce with the steps. so think this issue is fixed.
