### ISSUE TITLE
using require build with !text (require-text plugin)

### ISSUE THREAD

**Issue by mob8607** [sulu/sulu#1827]
This is an improvement for the build process in all bundles except the admin-bundle:

Important option for the build-process if you don't want to include the template in the built file: (build process will fail if it cannot load the file)

```
options: {
    inlineText: false,
}
```

In dev mode it's possible that the modules load longer than the default timeout of requireJS. If that's the case you can remove the timeout in the require.config by setting "waitSeconds: 0"

**Comment by danrot** [comment]
I guess we won't fix that anymore, because 2.0 is not using require anymore.
