### ISSUE TITLE
ContentType refactoring

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#1850]
To make the values of the content types more easy to read and write we should refactor the interface of the content types.
# First step

**1. Change the read/write methods**

they should look like:

``` php
public function read($value, $webspaceKey, $locale, $segmentKey) {
    // do something with the value
    return json_decode($value);
}

public function readForPreview($value, $webspaceKey, $locale, $segmentKey) {
    // do something with the value
    return $value;
}

public function write($value, $userId, $webspaceKey, $locale, $segmentKey) {
    // do something with the value
    return json_encode($value);
}
```

the values which will be returned here could be saved on the node. so we remove the dependency to phpcr-nodes and sulu properties.

**2. Mandatory resource-locator property**

Like title there should be a mandatory property `url` with the content-type `resource_locator` (only for pages).

**3. Resource-locator Content-Type**

The `resource_locator` handles the routes tree like it does before. but he doesn't write any value on the node. Because of the fact that every page has the property with the name url the url can be used everywhere.

**4. Block Content-Type**

Should return a serialized array of the component array. This will also be stored in a single node-property.

After this refactoring we can use the content types in the content-repository and use this in the navigation and smart-content. This will speed up a lot of things.
# Second step

Introduce a form generation and mapping component. There you can define an array of properties as a form. this form can be rendered outside the content bundle and used everywhere.

Additionally we should introduce a service which can convert data-arrays with the help of content-types to database-value-arrays and vice versa.

This service can then be used in the `StructureSubscriber`, `BlockContentType` and `ExcerptStructureExtension` to map values from form to database and vice versa.

@danrot @chirimoya @berndhep i think we should do at least the first step for 1.2 because we could speed up a lot of websites with that. But we should not forget that this is a big BC break.

**Comment by dantleech** [comment]
Just to add my vision here:

1. The content types should be passed either scalars or arrays which are obtained directly from the document. They should not be passed JSON strings.
2. `readForPreview` should not be neccessary - it is passed a value just as `read`, it should not do anything different.

**Comment by wachterjohannes** [comment]
+1

**Comment by chirimoya** [comment]
this should be done before #3199

**Comment by danrot** [comment]
Since there will be a bigger refactoring anyway I am closing this issue.
