### ISSUE TITLE
Media selection overlay bug when clicking on search icon

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#1876]
Reproduce:
1. Got to a content page and click on a "add media" button
2. In the overlay search for a collection 
3. click on the search-icon
4. the overlay closes and you get redirected to /admin/#

<img width="1382" alt="bildschirmfoto 2015-12-14 um 17 49 21" src="https://cloud.githubusercontent.com/assets/5152633/11787260/10ac8864-a28b-11e5-8af1-8f7001864d2d.png">

**Comment by wachterjohannes** [comment]
this also happens in the collection data-navigation

**Comment by danrot** [comment]
This seems to still happen when the user navigates starting from the dashboard (only `/admin`).
