### ISSUE TITLE
Add cache busting for Sulu translations

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#1877]
At the moment the browser cache must be cleared after editing translations which are exported to web/admin/translations/sulu.xx.json.

**Comment by danrot** [comment]
I'd suggest we extract that path from the javascript file to the HTML, so that we can use Symfony's `asset` twig method, which would enable us to use the [asset versioning feature](http://symfony.com/doc/current/reference/configuration/framework.html#ref-framework-assets-version)

**Comment by wachterjohannes** [comment]
but we should fix it for every js-file which will be loaded over require.js! we should really try to add the require cache key.

**Comment by danrot** [comment]
Is that somewhere documented?

**Comment by wachterjohannes** [comment]
i have found a stackoverflow entry about that: http://stackoverflow.com/a/8479953 but i have never tried it

**Comment by danrot** [comment]
Ok, but it would still be nice if the assets-version parameter could be used for that.

**Comment by wachterjohannes** [comment]
but then its only fixed for one case and not the rest (:
