### ISSUE TITLE
UI inconsistency: pop up for media and snippet selection

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#1881]
**Media:**
- a media item is added to the content when it is selected
- x must be clicked to close the pop up
- clicking somewhere outside of the pop up closes it and keeps the selection
  ![media-selection](https://cloud.githubusercontent.com/assets/5627878/11836367/9bb5b1f6-a3da-11e5-99b0-0594bf1b4862.png)

**Snippets:**
- a snippet is not added to the content when it is selected
- OK must be clicked to close the pop up and add the snippet
- clicking somewhere outside of the pop up closes it but does not keep the selection
  ![snippet-selection](https://cloud.githubusercontent.com/assets/5627878/11836410/df4afcfa-a3da-11e5-9fcf-87ff36c41aa2.png)

**Comment by danrot** [comment]
According to @berndhep we will introduce the ok and cancel button in the media overlay.

**Comment by danrot** [comment]
In Sulu 2.0 these two components are working similar, so this issue should be resolved.
