### ISSUE TITLE
Edit media and collections in media selection

### ISSUE THREAD

**Issue by EmiiKhaos** [sulu/sulu#1904]
As an author while editing a page and selecting images I want to be able to upload images, edit metadata, create and edit collections directly without leaving the page.

**Comment by danrot** [comment]
Uploading images is already possible, but not editing the metadata.

**Comment by alexander-schranz** [comment]
@lightglitch we use dropzone so if you have a collection open in the media selection just drop the file into it with drag and drop.

**Comment by lightglitch** [comment]
@alexander-schranz sorry it was my mistake, I didn't select a collection.

**Comment by danrot** [comment]
It is already possible to upload images, create new and edit existing collections. The only thing missing is editing the images, and we have to clarify if we want to support that, resp. how. If we support it, I would not imagine that happening in the edit form of the media itself, i.e. leaving the page form. That would be a deep link, that would also be interesting for other entities like contacts, accounts, snippets and so on.

**Comment by danrot** [comment]
Closing in favour of #5143
