### ISSUE TITLE
Piwik values validation

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#1941]
The values of the piwik analytics are not validated at the moment because the data-mapper is not able to handle objects in the data-mapper property.

it would be nice when there is the possibility to do following:

``` html
<input data-mapper-property="value.x" data-validation-required="true"/>
<input data-mapper-property="value.y" data-validation-required="false"/>
```

this should return `{value:{x: 'asdf', y: null}}` for example

**Comment by danrot** [comment]
Since we are not doing anything about the data mapper anymore I am going to close this issue.
