### ISSUE TITLE
Combine all caches to a single one

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#1942]
Following the discussion we had: https://github.com/sulu-io/sulu/pull/1233#discussion_r50228523

Combine all caches wth http://www.stashphp.com/Symfony.html and use a single service for all purposes. For the entries we could use namespaces.

**Comment by danrot** [comment]
We already switched to using the symfony cache in some places, and stashphp is not really an option anymore. Therefore going to close this issue.
