### ISSUE TITLE
Scrolling while Dragging an Element in Lists

### ISSUE THREAD

**Issue by pjeroen** [sulu/sulu#1949]
In the media list a user can drag elements for re-ordering. When dragging an element to the top or bottom of the list, the list should start scrolling up or down.

This currently works only for Chrome, not for FF, Safari or IE.
![screen shot 2016-01-25 at 13 39 48](https://cloud.githubusercontent.com/assets/513131/12551316/c36cd8b0-c369-11e5-8adb-476cafe977ed.png)

**Comment by danrot** [comment]
Looks to me like the browsers are handling this differently. After a quick online research I found some hacks and/or libraries providing that, do we really want to include something like that?

**Comment by webmozart** [comment]
@danrot How is a user supposed to achieve the desired functionality otherwise?

**Comment by danrot** [comment]
@webmozart Clicking and scrolling? Isn't that also possible on linux and windows?

**Comment by danrot** [comment]
Since this didn't come up anymore, I am going to close this issue. Clicking and scrolling at the same time also works in the new UI.
