### ISSUE TITLE
Symfony path twig extension not working with type portal routes

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1967]
If you embed your routing with `type: portal` which will create different routes for all portals. You can not embed the url in twig with `{{ path('your_route_name') }}` currently you need to do the following.

```
{{ path(request.portalUrl ~ '.your_route_name') }}
```

It would be good when sulu could handle `{{ path('your_route_name') }}` automaticely or as quick solution add a `sulu_path` twig extension.

**Comment by wachterjohannes** [comment]
we would like to get rid of the `sulu_path` extension. we think that we can include the functionality into the path http://stackoverflow.com/a/23958696

**Comment by alexander-schranz** [comment]
currently the only issue is when using another port e.g. when using `server:run`.

**Comment by alexander-schranz** [comment]
Seems not longer be an issue both the `path` and `url` returns the correct port:

```twig
{{ path('sulu_search.website_search') }}
{{ url('sulu_search.website_search') }}
```
