### ISSUE TITLE
Add update method to husky-input (datepicker)

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#1992]
I'm using the husky component "input" as a datepicker and I would like to update some datepickerOptions after the form renders. 

I can't find an update method, this would be a nice feature:
https://github.com/massiveart/husky/blob/develop/husky_components/input/main.js

**Comment by danrot** [comment]
Why do you want to change something there after the form renders? Somehow doesn't make sense to me right now.

**Comment by thomasduenser** [comment]
In my case I have two datepickers - let's assume my input fields are named **dateOne** and **dateTwo**. If I choose a date for **dateOne** I want to update the startDate (minimum date) of **dateTwo**.

The user should not have the possibility to choose a date for **dateTwo** which is in the past compared to **dateOne**.

**Comment by danrot** [comment]
I think we won't implement something like this in the old UI. If something like this comes up again, I would say we create a new issue for that.
