### ISSUE TITLE
Edit/upload contacts/accounts in contact selection

### ISSUE THREAD

**Issue by EmiiKhaos** [sulu/sulu#1996]
As an author while editing a page and selecting contact I want to be able to create contacts, edit contacts. This would improve the usability for authors.

Example use case is a standings table on a news page, where every standing is matched to a contacts entry.

**Comment by danrot** [comment]
Nice idea, but this will take some time. We can't tell you a due date to that feature.

**Comment by danrot** [comment]
Related to #1904, currently I would still imagine that to be a deep link.

**Comment by danrot** [comment]
Closing in favour of #5143
