### ISSUE TITLE
Non-legacy solution for ContentMapper::copyLocale

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#1998]
The copy locale method (`ContentMapper::copyLocale`) currently has no counterpart in the DocumentManager API(s).

This command might even be redundant when the routing auto (#1989) integration is made, as this method is mainly concerned with the ReosurceLocator.

I think it should basically be possible as follows (with the routing auto PR):

``` php
$document = // ...
$newLocale = 'de_at';
$manager->persist($document, $newLocale);
```

**Comment by danrot** [comment]
Replaced by #3227
