### ISSUE TITLE
Remove hack for PHPCR-ODM 1.2

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2013]
We upgraded (or will shortly upgrade to) PHPODM 1.3; we should remove these lines: https://github.com/sulu-io/sulu/blob/7bbdcd18d50a320ad2c7e6286138a1b8a11d7901/src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php#L44

**Comment by dantleech** [comment]
As far as I can see this issue is worked around in the PHPCR bundle, the fix is currently unreleased: 
https://github.com/doctrine/DoctrinePHPCRBundle/commit/10105dc484ea3c2707d8e7f85217b5726ce7093d

**Comment by danrot** [comment]
@dantleech The link you've posted here seems to be released in 1.3. Does this commit contain the fix?

**Comment by dantleech** [comment]
Yeah, my bad. I was looking at the branches and not the tags. We can indeed upgrade to 1.3

**Comment by patkar** [comment]
backref: #2106

**Comment by danrot** [comment]
Had to reintroduce the hack, because the behat tests were failing with the new phpcr bundle...

**Comment by dantleech** [comment]
We could either wait for https://github.com/jackalope/jackalope-doctrine-dbal/pull/323 or logout of the session / shutdown our kernel before making the web requests with Behat.

**Comment by danrot** [comment]
I would say we have no hurry in fixing this issue, so we could wait for the fix.

**Comment by alexander-schranz** [comment]
@danrot can we remove this?

**Comment by danrot** [comment]
I somehow get the feeling that this won't be fixed... Therefore going to close it. I think the comment in the code is good enough.
