### ISSUE TITLE
Drafting mode

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2028]
We have to implement a drafting mode for pages.

@chirimoya, @dantleech and me already agreed in a discussion last week that we'll have two document managers (in the beginning draft and published), and we take the same document and save it again in the second document manager (managing a different phpcr workspace, in this particular case the workspace with the published data).

There are multiple tasks to achieve, to get this working:

* synchronizing the documents between different workspaces
  * Routing nodes?
  * Set and persist the UUID of the document
* configure multiple workspaces/document managers
  * workspaces can have roles (a master workspace, one only for publishing, ...)
* command for repairing the other workspaces based on the data in the master workspace
* Access the correct workspace from the website
* User Interface
* REST API
* Create workspaces when initializing Sulu
* Enable instantiation of multiple document manager
* Publish security and mapping permissions to security contexts

**Comment by webmozart** [comment]
Is there any ticket about the underlying feature (publishing) that you could link to? From the point of view of an outsider, it's hard to tell what is happening: "We already agreed" - who, where? What about that second document manager managing a different workspace? I recommend to re-read tickets with the mindset of an outsider to find whether any kind of information is missing to make the ticket easy to understand.

**Comment by danrot** [comment]
@webmozart Updated the paragraph and added the participants of that discussion. I don't know what's unclear about the second document manager TBH. And there is no other issue about publishing, that's why I created this issue :-)

**Comment by webmozart** [comment]
Imagine somebody reads this issue who didn't participate in your face-to-face meetings. They will have a hard time figuring out what you're talking about. :) I think it's a good idea to summarize the results and decisions of face-to-face meetings when creating a ticket as a result of such a meeting.
