### ISSUE TITLE
Start writing JavaScript tests

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu#2030]
Right now, we do most (or all?) bug fixes with regards to JavaScript code without writing a test that would prevent that bug from occurring again in the future. IMO, this is quite a big problem, since we invest time into fixing a bug but have a relatively high chance of hitting the same bug again. In the long run, this is expensive and unsatisfactory for users, who may hit a bug again after it's being fixed.

I think that we should start writing tests for JavaScript code (or restructure the code in a way that can be tested) as soon as possible and reject PRs that fix a bug without a proper test case.

**Comment by danrot** [comment]
At the moment there are only tests using Behat and Selenium. This is indeed a problem, and I will have a look at this on our hackday this saturday.

**Comment by danrot** [comment]
Started with a quite easy component in #2059, I think I'll also do a harder component to test from the AdminBundle, before this should be merged. Just to make sure that the testing framework works for us.

**Comment by webmozart** [comment]
What's the status here?

**Comment by danrot** [comment]
I'd like to continue work on that on our next saturday hackday, but sadly there hasn't been one since the last time... I've already added a comment at my PR, what to do next to see if the intern framework is usable: https://github.com/sulu/sulu/pull/2059#issuecomment-207329185

**Comment by alexander-schranz** [comment]
fixed in 2.0 with Jest
