### ISSUE TITLE
Add more twig extension to retrieve parts of 'sulu_seo'

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2050]
The twig extension sulu_seo returns a string including all meta tags (title, description, keywords, alternate links, canonical tag). It should be possible to get only parts of the meta tags. Additionally the title and description should be available without html tags, e.g. the title without ```<title></title>``` because there are other meta tags which need this information (e.g. og or twitter tags).

**Comment by alexander-schranz** [comment]
As discussed with @sabinebaer the sulu_seo should not be a twig extension it should be a twig template. An Template can be easy extended and block parts can be overwritten

e.g.
``` twig
{# Set Variabes #}

{% set seoTitle = extension.seo|default(content.title) %}
{% set seoKeywords = extension.seo.keywords %}
{# ... #}

{% block title %}
    <title>{{ seoTitle }}</title>
{% endblock %}

{% block keywords %}
    {% if seoKeywords %}
        <meta name="keywords" content="{{ seoKeywords }}" />
    {% endif %}
{% endblock %}

{% block robots %}
   {# ... #}
{% endblock %}

{% block alternate %}
   {# ... #}
{% endblock %}

{# ... #}
```

a template has more flexibility to overwrite each part when extend from it


```twig
{% extends "SuluWebsiteBundle:views:seo.html.twig" %}

{% block title %}
    <title>My Company: {{ seoTitle }}</title>
{% endblock %}
```

**Comment by danrot** [comment]
The reason we have decided to use an extension is the fact that it takes care of everything (meaning internal links, shadow pages, excerpts, ...). But I also like the idea with the template, however, that's something you can implement in your projects anyway.

**Comment by alexander-schranz** [comment]
@danrot then i would create for this specific things an extension but the whole SEO as template so every tag can be overwritten easily

**Comment by wachterjohannes** [comment]
+1 for template

**Comment by webmozart** [comment]
A separate template sounds reasonable to me. Together with Twig's `embed` this should be quite flexible.
