### ISSUE TITLE
Merge parameters.yml and phpcr.yml

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu#2068]
Currently, deployment-specific parameters can be configured both in parameters.yml and in phpcr.yml (this was copied from the CMF project). However, there doesn't seem to be an obvious benefit for this separation.

In order to simplify the usage of Sulu, we should merge the two files.

**Comment by webmozart** [comment]
I would like to take care of this issue.

@chirimoya @danrot What do you think about adding a `sulu:upgrade` command that automatically performs this upgrade in projects using Sulu? We could later add more functionality to this command for making upgrades more convenient for users of Sulu.

**Comment by danrot** [comment]
I don't really know how to implement this... Where would you save the current state of the application? The phpcr migrations are creating a node for that in its tree, but I don't know how that should be handled for general tasks like this. But if you come up with a clean concept I would support that.

**Comment by webmozart** [comment]
Not sure yet. One option is to make migrations idempotent, then we can always execute all of them. However, I don't know if that works for every kind of migration. Another option is to store the version in a key of the "extra" section of composer.json (e.g. "sulu-migration-version").

**Comment by webmozart** [comment]
It might be interesting to look at https://github.com/baleen in this context.

**Comment by alexander-schranz** [comment]
fixed in sulu-minimal
