### ISSUE TITLE
Provide Doctrine migrations for upgrading to 1.3

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu#2072]
Instead of requiring the users of Sulu to execute SQL statements, I think that we should provide a Doctrine migration for upgrading to 1.2 before releasing the first RC.

As of now, IMO every PR that requires a change to the database schema should also come with a corresponding migration script.

**Comment by patkar** [comment]
:+1: for using doctrine migrations.

Additionally it should not block the user (sulu-standard) of writing own doctrine migrations. The Sulu migrations and users migrations should work together :)

**Comment by chirimoya** [comment]
We will use doctrine migrations from version 1.3.

**Comment by danrot** [comment]
After we have investigated doctrine migrations we (think we) realized that it's not the right tool for us to use. It allows only one folder to contain migration files, so we would have to put that folder into `sulu/sulu`, which means that if somebody wants to use migrations on their own it is not possible anymore.

For me it feels like Doctrine Migrations is not thought for our use case, i.e. not for the update of single bundles, but only for entire applications. So I would suggest that we keep the way we had it until now, and if somebody wants to use Doctrine migrations this can still be done (in most cases the [migrations can be autogenerated](http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#generating-migrations-automatically) anyway, so the schema:update can still be applied with --force on the development machine and generate the migrations from there).
