### ISSUE TITLE
[RFC] [Workflow] Use amending and squasing

### ISSUE THREAD

**Issue by patkar** [sulu/sulu#2073]
I know it's done easily to commit every change as a commit, but it distorts the history completely. There is no need to have the same commit directly after, like the "fix style ci". Those could be amended and force pushed on own branches.
![too much commits](https://cloud.githubusercontent.com/assets/993350/13408690/63675fa8-df2f-11e5-8fa7-a96231590a50.png)

Before finishing the Pull Request it is worth to squash commits to more meaningful commits too, like the "adjusted event propagation .."

![same commits](https://cloud.githubusercontent.com/assets/993350/13408726/98652c62-df2f-11e5-91f9-24e216205114.png)

I know this will lower hour GitHub streak and commit activity, but hey, who cares about those crank statistics?

**Comment by wachterjohannes** [comment]
your examples are really bad and should not happen but i dont like it when big changes (e.g. the whole feature) is placed in a single commit. for me it makes sense to split the PR into smaller commits. what did the others think?

**Comment by patkar** [comment]
I don't say big PRs should be a single commit, but I see those example above very often :grin:

**Comment by webmozart** [comment]
I agree. Big changes should be split into separate PRs anyway (ideally) or at least done in a set of meaningful commits. There are many problems with not properly organizing commits:

* rebasing is horrible
* bisecting (looking for commits that introduced a bug) is more difficult
* the history of a file becomes distorted and meaningless
* it's hard to tell (with git blame) who changed what when and why

**Comment by dantleech** [comment]
+1 for atomic commits.

**Comment by danrot** [comment]
Having one commit per pull request is probably a bit unrealistic... But I'd say that every single commit has to be working and the tests have to succeed. Especially the bisect feature would be very important for me.

**Comment by webmozart** [comment]
> Having one commit per pull request is probably a bit unrealistic

Not necessarily. If you restrict work on a PR to a day, you can squash everything into one commit. Only for bigger features, this doesn't make sense anymore, since the PR then actuall contains multiple features that build on top of each other. But then it could even be a good idea to split the PR into several commits and push each commit as individual PR, which greatly simplifies review.

**Comment by danrot** [comment]
We have decided to go with atomic commits now 😃 So I'll close this issue.
