### ISSUE TITLE
Add VERSION constant

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2087]
If you create a bundle and want to support multiple versions of sulu you sometimes need to check for specific versions and e.g. register other services.

**Comment by dantleech** [comment]
Rather than adding the overhead of having to maintain the contant value, we could consider making use of composer: https://github.com/Ocramius/PackageVersions

**Comment by patkar** [comment]
PackageVersions is awesome, but PHP 7 only :)

**Comment by alexander-schranz** [comment]
closing in favor of https://github.com/Ocramius/PackageVersions
