### ISSUE TITLE
Removed pages template should not crash content system

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2101]
When you delete a xml template and a page still use this template you can not access the content area anymore.

> @danrot  The best solution would be to mark the page as broken in the content tree somehow.

We should also keep in mind that it could be broken only in one language.

**Comment by danrot** [comment]
@berndhep How should we show these broken pages in the content tree?

**Comment by danrot** [comment]
The solution is to strikethrough the title and show a tooltip "Template missing" on mouse over.
