### ISSUE TITLE
Pages can't be copied or moved to the first level of the column tree

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2104]
| Q | A
| --- | ---
| Bug? | yes
| Version Used | 22579aa91105c5a844ee5a03ef656a007ae6a1f0
| New Feature? | no

#### Expected Behavior

It should be possible to copy or move pages to the first level of the content hierarchy (being the most left column in the content navigation). So there should be the column with webspaces as shown in this screenshot. (screenshot taken from the internal links content type)

![image](https://cloud.githubusercontent.com/assets/405874/13637723/2eed798e-e609-11e5-994b-ca873a5ac84b.png)

#### Actual Behavior

The expected behavior is currently not possible, because the overlay which is opened after initiating the copy or move, doesn't allow to choose the webspace as parent. (the first column from the upper screenshot is missing)

![image](https://cloud.githubusercontent.com/assets/405874/13637680/e6eefa04-e608-11e5-999d-0c196266c13c.png)

#### Steps to Reproduce

1. Open the column tree (in the navigation `webspace > content`)
2. select a page
3. Click on the gear on the bottom of the column
4. Click on "Copy page" or "Move page"

#### Possible Solutions

The overlay should also show the column with the webspaces. I assume that setting the right id in the consecutive API call will just work, if not, that has also to be fixed.

**Comment by webmozart** [comment]
:heart: this bug report

**Comment by danrot** [comment]
With the new issue template this is hopefully the default from now on :smiley:

**Comment by akira28** [comment]
Is anyone working on this one? If not, do you have any starting point, so I can try to fix it and create a PR?

**Comment by wachterjohannes** [comment]
currently we are not working on this issue but we would love to see a PR from you. you can take a look in this file https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/column/main.js#L606 and try to add the following parameter `webspace-node=true`. maybe that would be enough. but you have to try the other functionalities to not break any other of them.

**Comment by akira28** [comment]
Ok, cool.
Do you know which other functionalities make use of this overlay? ("move" is one)

**Comment by akira28** [comment]
webspace-node=true doesn't seem to work, but webspace-nodes=single is working.
There are some issues, but the main one is that I don't know how to build js dist files to simplify testing :P 
Also, seems like overlay.scss module is missing

**Comment by danrot** [comment]
@akira28 For building it you simply need to `cd` into the bundle and execute `grunt build`. In case you haven't done yet you need to execute `npm install`, to install all the dependencies. There is also a  `grunt watch` task, which will build everytime you change something.

But I think during development you don't need to build, since the original js files are loaded. At least if you are running Sulu in the dev environment.

**Comment by danrot** [comment]
Was solved by https://github.com/sulu/sulu/pull/2514
