### ISSUE TITLE
Datagrid: Select all checkbox does not work when records are added due event.

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#2109]
| Q | A
| --- | ---
| Bug? | yes
| Version Used | 1.1.10
| New Feature? | no

#### Expected Behavior

All checkboxes should be selected when clicking checkbox on top left corner (select all)

#### Actual Behavior

Top left checkbox is disabled.

#### Steps to Reproduce

1. Add elements to an empty datagrid by emiting events (record.add)
2. Try to click the select all checkbox in the top left corner. (Which will not work)

#### Possible Solutions

Datagrid is not aware of added elements by the event 'records.add'. This should be changed.

![image](https://cloud.githubusercontent.com/assets/5152633/13671169/92f82dc8-e6ce-11e5-92c0-77a8731b3ed4.png)

**Comment by danrot** [comment]
@turbo-ele Just to get this right, the top left check box is working in general, there are only problems if you some more rows using the `records.add` event, right?

**Comment by turbo-ele** [comment]
right! ;)

**Comment by nnatter** [comment]
@danrot: this should be fixed with https://github.com/massiveart/husky/pull/700

**Comment by danrot** [comment]
Yeah, remember it 😃
