### ISSUE TITLE
Hidden "Content" section

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu#2113]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Version Used | 1.1.10

#### Actual Behavior

From my understanding, Sulu is primarily a CMS. Nevertheless, the section for the actual page content is the very last one:

![image](https://cloud.githubusercontent.com/assets/176399/13675057/26bd6846-e6e0-11e5-90bb-1cb1c0217696.png)

When I used Sulu the first few times, I almost did not find that section and I still find it irritating.

#### Expected Behavior

I'd expect the icon for the page content to be the topmost one in the navigation.

**Comment by dantleech** [comment]
@chirimoya @berndhep this has been fixed now right?

**Comment by danrot** [comment]
@dantleech You are right, that has been fixed in https://github.com/sulu/sulu/pull/2196
