### ISSUE TITLE
StructureFIlingSubscriber should not depend on preceding action by AliasFilingSubscriber.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2117]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | develop |
#### Actual Behavior

Currently the StructureFilingSubscriber will use the parent node set by the AliasFIlingSubscriber as a basis for the path.
#### Expected Behavior

This is a problem because when `path` option is used, it is explicit, it will set the parent node in the persist event and other subscribers should **not** subsequently try and change the parent node. (we should also make the parentNode property immutable once it has been set.)
#### Possible Solutions

It should not depend on the preceding subscriber, and the `SnippetDocument` should not implement the `AliasFIlingSubscriber` interface.

The `StructureFilingSubscriber` should handle the entire operation (i.e. using the alias to construct the preceding part of the path and the structure type to form the later).

**NOTE**: There is a hack to work around this in the sulu-document-manager `AbstractFilingSubscriber` which should be removed when this issue is resolved.

**Comment by danrot** [comment]
This probably won't be touched before a bigger refactoring anyway, so I am going to close it.
