### ISSUE TITLE
ShadowCopyPropertiesSubscriber: Should use property encoder.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2124]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | a326675d |
#### Actual Behavior

Class uses a regular expression to determine the locale of a property:

```
preg_match('/i18n:(?P<locale>.+)-shadow-base/', $propertyName, $match);
```

It also has a dependency on the `PropertyEncoder` and does not use it.
#### Expected Behavior

It should not do that. This is a storage detail and should not be exposed beyond specific classes in the DocumentManager layer.

There is a better way to do it (I don't know what without looking closer).

/cc @wachterjohannes

**Comment by wachterjohannes** [comment]
we could add a function - to the property-encoder - to determine the locale from the property name. also the "sprintf" statements should be replaced with function calls to the encoder.

**Comment by dantleech** [comment]
then it wouldn't be a "property encoder". there is *probably* a way to do it without determining the locale from the property name.

**Comment by danrot** [comment]
This probably won't be touched before a bigger refactoring anyway, so I am going to close it.
