### ISSUE TITLE
Replacing request-analyzer by route-enhancers

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2135]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | all |
| Browser Version | none |
#### Actual Behavior

Currently the request behavior is called by a request listener.
#### Possible Solutions

We could move the whole into a route-enhancer where it could build the attributes we need step-by-step.

**Comment by dantleech** [comment]
+1 for replacing the request analyzer. the error handling it is horrible :/

**Comment by dantleech** [comment]
I think the "request analyzer" should also be capable of selecting the "portal" based on factors other than the host, e.g. from a query parameters (configurable)`. This would make testing much easier.

**Comment by danrot** [comment]
This probably won't be touched before a bigger refactoring anyway, so I am going to close it.
