### ISSUE TITLE
Replace display with display-conditions in ContentNavigationItem

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2136]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | all |
| Browser Version | all |
#### Actual Behavior

Currently you have to define in which "form" you want to display a tab with the display property. This property can contain "new" or "edit".
#### Expected Behavior

This could be replaced by the display conditions with a condition of id is null.

**Comment by alexander-schranz** [comment]
Was implemented soon after this issue was created #2099. Same exist also in 2.0 for the views.
