### ISSUE TITLE
Node Repository Refactor

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2138]
#### Actual Behavior

The [NodeRepository](https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php) has multiple issues:
- It does not use the serializer, but it uses the serializer format.
- It uses the ContentMapper, it doesn't use Documents.
- It has destructive methods (copy, order, orderBefore), not typical for a Repository pattern, and which should be done with the DocumentManager directly.
- It accepts raw request data (probably part of a bigger content issue).
- It manually creates URLs.
### Possible Solutions

The main role of the class by code volume is constructing the response for the Tree view. I suggest:
- Creating a class dedicated to this purpose, or otherwise having a way to serialize this data, preferably  using the JMS serializer (as with everything else).
- Change any thing that calls this classes destructive methods to use the DocumentManager instead.
- Handle the saving of extension data via. forms, or otherwise so that this class is not used for this purpose.
#### Steps to Reproduce

Look at the code.

**Comment by wachterjohannes** [comment]
Like we have defined in our architecture discussion i would introduce a `PageManager` which will be called from the controller a `PageRepository` which contains the different `find...` methods with the special queries and use for now the form to map data to the document. In the same refactoring i would rename the `NodeController` into `PageController` to be consistent to rest of the system

**Comment by dantleech** [comment]
Not sure about the `PageManager`, what would that do? But +1 for the rest.

**Comment by wachterjohannes** [comment]
we have agreed to introduce such a manager in all components. for the page i would say throw the node save / delete events. which should also be renamed after that.

for me the most important reason for such a manager is the extensibility for others. they could overwrite this manager and extend it with their own logic. because of that we should introduce managers everywhere.

**Comment by dantleech** [comment]
Event subscribers can already be used to act on pages / snippets etc,
why do you need a manager to do this? Also adding things "everywhere"
means more code and more matinenence.

**Comment by wachterjohannes** [comment]
but also more extensibility if we dont do that we make it even harder to extend it. how can we act with pages (if you dont want to add a document-manager subscriber)?

**Comment by dantleech** [comment]
On Thu, Mar 17, 2016 at 07:25:41AM -0700, Wachter Johannes wrote:
>    but also more extensibility if we dont do that we make it even harder to
>    extend it. how can we act with pages (if you dont want to add a
>    document-manager subscriber)?

You add a document manager subscriber, why wouldn't you want to do that?
What do you loose in extensiblity? Less code = better code = less bugs.
But lets not discuss more here :)

**Comment by danrot** [comment]
Actually we have discussed that the `DocumentManager` has the same purpose as e.g. the `ContentManager`, so there is no need for a `PageManager`. I'd say that's even some code duplication, since the `DocumentManager` already knows based on the passed `Document` what to do. A `PageManage` would probably simply wrap the `DocumentManager` without adding any real value.

@dantleech There is already a similar issue: https://github.com/sulu-io/sulu/issues/1182. I am going to  leave yours open, and close the other, since here has already been more discussion on this topic.

**Comment by wachterjohannes** [comment]
in my opinion we should provide also page_save, page_delete events (independent of document-manager) that could be done in the PageManager

**Comment by dantleech** [comment]
But what is that advantage of that over the generic document manager
events? If *we* wanted to do something to a page after it was saved,
we would use a DM event, why would the "user" do something different?

**Comment by wachterjohannes** [comment]
its easier to use because you dont have to know how you get the page, you can omit the instanceof and so on.

**Comment by danrot** [comment]
Even if we want to introduce separate events for pages (which I am not sure about), it's not an argument to introduce another manager. We also do something like this in the [ContentMapperSubscriber](https://github.com/sulu-io/sulu/blob/6b8f75c3d11f3bde694038abac56aeac961568c5/src/Sulu/Component/Content/Document/Subscriber/Compat/ContentMapperSubscriber.php#L172). This way we don't need another layer.

**Comment by danrot** [comment]
This probably won't be touched before a bigger refactoring anyway, so I am going to close it.
