### ISSUE TITLE
Behavior are coupled quite strong

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2140]
| Q | A |
| --- | --- |
| Bug? | yes (at least from develop perspektive) |
| New Feature? | no |
| Sulu Version | all |
| Browser Version | all |
#### Actual Behavior

If you create a custom document which implements the `AutonameBehavior` it automatically implements the `TitleBehavior` which implicit needs the `StructureBehavior` (but the `TitleBehavior` dont extend `StructureBehavior`). If the custom document dont need a structure you cannot use the `AutonameBehavior`
#### Expected Behavior

The `AutonameBehavior` only needs a `getTitle` function which could come from any other Behavior. Therefor it shouldn't extend the TitleBehavior which is coupled to a Subscriber.

In my (https://github.com/sulu-io/sulu/pull/1927#discussion_r56482625) case i wont implement the TitleBehavior because i have no Structure.
#### Steps to Reproduce

Create a custom document with the `AutonameBehavior`

**Comment by danrot** [comment]
This probably won't be touched before a bigger refactoring anyway, so I am going to close it.
