### ISSUE TITLE
Filtering ids in flat api conflicts with limit of listbuilder 

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#2146]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 4017651ab40e9f67fad4edf7f30923ea4af45353 |
#### Actual Behavior

When calling flat api and passing ids for filtering it conflicts with the limit parameter.
E.g.: `/admin/api/accounts?flat=true&fields=id&ids=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15` and the limit is set to 10 by default, then you only get 10 results, although you would expect all 15.
#### Expected Behavior

If i provide 15 ids i'd like to get all 15 objects as a result. An exception is if i'm explicitly set a limit (then the result should be limited)
#### Steps to Reproduce

Call the following url

```
/admin/api/accounts?flat=true&fields=id,name&ids=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
```
#### Possible Solutions

This issue is solved for accounts in https://github.com/sulu-io/sulu/pull/2143/files, but **a more centralized solution is needed**.

**Comment by danrot** [comment]
The point is that the `ListBuilder` currently doesn't handle the `ids` parameter at all, so there is no way to centralize that, expect we say that handling the IDs should be a task of the `ListBuilder`. In how many controllers is something like that used?

**Comment by danrot** [comment]
As already described the solution is not centralizable, since `ids` is not known by the `ListBuilder`. Therefore going to close this issue.
