### ISSUE TITLE
Clear cache for a single webspace

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2158]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | 8a354a4a459594a0bc5ae06f0ea3f6cddcee0ce5 |
| Browser Version | all |
#### Actual Behavior

When you click clear cache - the cache for all the webspaces will be cleared. Also this button dont work if you use varnish.
#### Expected Behavior

The cache clear should only clear the current webspace. In the navigation entry cache all the webspaces withe according permission should be cleared. Varnish should work also.
#### Steps to Reproduce

Click clear cache in the form or the navgation entry settings - cache.

**Comment by danrot** [comment]
When doing that we should also think about changing the REST call here... The current call is a GET request, which should only read, but definitely not delete something on the server.

**Comment by danrot** [comment]
Since the button has been moved, this should not be a surprise anymore.
