### ISSUE TITLE
Cache should be cleared after contact save

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2167]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.1.10 |
#### Actual Behavior

Cache has to be cleared after editing a contact that is included on a page.
#### Expected Behavior

Cache for affected parts should automatically be cleared when a contact is updated.
#### Steps to Reproduce

Change a contact that is included on a page - changes are not visible on the website without clearing the cache manually.

**Comment by danrot** [comment]
This has already been fixed :tada:
