### ISSUE TITLE
Incorrect validation of URLs

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2174]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.1.10

#### Actual Behavior
URLs inserted to fields with content type url are not validated correctly.

Example: www.example.com/ (with trailing slash)
![invalid-url](https://cloud.githubusercontent.com/assets/5627878/14012159/2db4632e-f1a4-11e5-9260-8721c59cfac0.png)

Example: 
![invalid-url-2](https://cloud.githubusercontent.com/assets/5627878/14012579/e8873954-f1a6-11e5-9b08-96968e688e24.png)

#### Expected Behavior

URLs with trailing slash and URLs with ! should be valid.

#### Possible Solutions
Improve the regular expression, see e.g. https://mathiasbynens.be/demo/url-regex. Not sure if the trailing slash problem is also related to the used regular expression as it seems to support trailing slashes.

**Comment by danrot** [comment]
@wachterjohannes The given examples are still not working for me.
