### ISSUE TITLE
CustomURL fails if language does not exist in webspace anymore

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2179]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 305f73897cd027c4b9a67df65bf6f0fd12aec543

Related to https://github.com/sulu-io/sulu/issues/2160

#### Actual Behavior

If a custom url is generated for a non-existing localizations, the following error appears:

![](https://cloud.githubusercontent.com/assets/405874/14011565/d6845ba8-f19f-11e5-94f4-4957554bd47f.png)

This problem was fixed in #2169, but somehow it still persists. Namely if a custom url exists, and the chosen localization is removed from the webspace later.

#### Expected Behavior

It should at least throw a clear exception, and not a catchable fatal error. In production it should display a 404 page (?)

#### Steps to Reproduce

1. Create a new custom url in any language
2. Remove this language from the webspace
3. Try to access the created custom url

**Comment by chirimoya** [comment]
404 in production is fine
