### ISSUE TITLE
Test cases should explicitly indicate which kernels they use.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2187]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
#### Actual Behavior

Test classes use the kernel as _found_ by either the `KERNEL_DIR` environment variable or in a pre-determined location (`Tests/Resources/app/AppKernel.php`).

This prevents different kernel configurations being effectively tested, and introduces "magic".
#### Expected Behavior

Test classes should explicitly use (or better, instantiate) the kernels that they require.

**Comment by alexander-schranz** [comment]
@chirimoya can we close this issue?

**Comment by danrot** [comment]
Shouldn't that be fixed in #4226?

**Comment by alexander-schranz** [comment]
Is fixed TestCases can now overwrite the KerneClass over the `getKernelClass` method
