### ISSUE TITLE
Translate mime-type to something readable

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2198]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | ca81e376ecf5e543b26481c00fb409c4dedbc129 |
| Browser Version | all |
#### Actual Behavior

Currently the masonry-view and edit-overlay displays the "raw" mime-type.
#### Expected Behavior

The mime-type should be translated to something readable like:
- image/jpg => JPG Image
- application/pdf => PDF Document
#### Possible Solutions

For this something similar like the file-icons service could be implemented see https://github.com/sulu/sulu/blob/b03edb75657d4141e2b294d06465896ac3c301aa/src/Sulu/Bundle/MediaBundle/Resources/public/js/services/file-icons.js#L15

**Comment by danrot** [comment]
I think that this is hard to implement in a generic way, and not really worth the hassle. Therefore going to close it.
