### ISSUE TITLE
Controllers are not tested with security

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2212]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
#### Actual Behavior

Currently all the functional tests for controllers are tested without security. If the security is enabled there is a `TestVoter`, which just grants everything.
#### Expected Behavior

For the new changes in #2207 it would have been nice to use the functional controller tests in combination with the security. That's currently not possible, because if the security is activated and another voter than the `TestVoter` is used, all the tests are failing.

**Comment by alexander-schranz** [comment]
In Sulu 2.0 since https://github.com/sulu/sulu/pull/4748/files#diff-1f0c938a55f5d3b184c32f7ea55af110 its now Possible to create security tests by using another username then `test`.
