### ISSUE TITLE
Doctrine/DriverException after creating new category

### ISSUE THREAD

**Issue by JohnPoison** [sulu/sulu#2226]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 73fceeb3748fb84201d8827e5fa77a4f9feb3bb9
| Browser Version | Firefox 45.0.1

#### Actual Behavior
Endless loading of page: Settings -> Categories after creation of new category
500 error code in ajax query:
Actual url: http://sulu.lo/admin/api/categories?sortBy=depth&sortOrder=asc&locale=en&fields=id,name&flat=true
Exception:
https://gist.github.com/JohnPoison/02be797be3d664028cc86184d49930f1

#### Expected Behavior

Categories list is loaded correctly

#### Steps to Reproduce

1. Install sulu with postgres sql
1. Go to admin area
1. Go to settings -> categories
1. Create new category
1. See endless loading of the categories list page

#### Possible Solutions

I have no idea how to solve problem yet, but if I remove flat=true, there is no exception

**Comment by wachterjohannes** [comment]
One question (: do you use postgres for your database layer? Because we have currently some problems there. Currently we recommend using MySQL to run sulu. maybe @dantleech can explain the problem more.

**Comment by wachterjohannes** [comment]
https://github.com/sulu/sulu/pull/1722

**Comment by dantleech** [comment]
Yeah some of our queries relating to the ListBuilder are incompatible with Postgres, this may be fixed in #1722.

**Comment by JohnPoison** [comment]
Sorry,  forgot to mention it,  yes I use postgres. Glad to hear it will be fixed.  I'll try MySQL for now
