### ISSUE TITLE
Include all fields in mutli-edit of media

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2230]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | 1.1.10 |
| Browser Version | All |
#### Actual Behavior

Only title, description and tags can be edited when selecting multiple assets:
![multi-edit](https://cloud.githubusercontent.com/assets/5627878/14240355/7ebc5094-fa44-11e5-94cd-415abf454dc9.png)
#### Expected Behavior

Copyright should also be editable in this overlay.

**Comment by alexander-schranz** [comment]
I have the following use case a photographer uploads a lot of images (~100) after uploading he want to set for all images he uploaded the copyright to his name.

**Comment by chirimoya** [comment]
@berndhep can you add your thoughts

**Comment by danrot** [comment]
Since this feature has been removed this is not an issue anymore :see_no_evil:
