### ISSUE TITLE
Add search to media selection

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2231]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.1.10
| Browser Version | All

#### Actual Behavior
The media selection includes only a search for collections, nor for assets.
![media-selection](https://cloud.githubusercontent.com/assets/5627878/14240644/cff891b4-fa46-11e5-8346-b1110e2a477d.png)

#### Expected Behavior

The media selection should include a search for assets.

**Comment by reflexxion** [comment]
Would be great if this can be merged in [Milestone 1.3](https://github.com/sulu/sulu/milestone/16)
