### ISSUE TITLE
Sorting pages isn't working if ghost pages are in current level

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#2239]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.1.10
| Browser Version | all

#### Actual Behavior

When trying to sort pages where at least one page on the current level doesn't exist in the current language, following error is thrown `Document has no title (title is required for auto name behavior) ... `

#### Expected Behavior

Sulu should sort the pages even though not every page on the current level is available in the current language.

#### Steps to Reproduce

This is working, because every page is available in the current language:
![bildschirmfoto 2016-04-05 um 09 11 25](https://cloud.githubusercontent.com/assets/3875917/14273959/bbd63506-fb0e-11e5-8d1b-376fcba6afa3.png)

This is not working, because (at least) one page is not available in the current language:
![bildschirmfoto 2016-04-05 um 09 11 42](https://cloud.githubusercontent.com/assets/3875917/14273972/d0e215dc-fb0e-11e5-9477-03e0d902d5a8.png)

#### Possible Solutions

If title is necessary for sorting pages, maybe the title of the "root" language (the language in which the page was created) should be used.

**Comment by danrot** [comment]
Also, in dev-develop it is currently not possible to sort pages at all, because of a JavaScript error:
![image](https://cloud.githubusercontent.com/assets/405874/14379063/7195ff3c-fd78-11e5-88fc-38345fceda29.png)
