### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2241]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

In order to support Postgres we must address the following issues:

- [ ] List builder: `SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"c1_.translation\" must appear in the GROUP BY clause or be used in an aggregate function`
- [ ] Test order expectations (postgres does not return rows in the same order as MySQL)

Other issues as test failures: https://travis-ci.org/sulu/sulu/jobs/120617459https://travis-ci.org/sulu/sulu/jobs/120617459

**Comment by danrot** [comment]
Related to https://github.com/sulu/sulu/issues/2226 and https://github.com/sulu/sulu-standard/issues/53
