### ISSUE TITLE
No preview images for SVG and EPS files

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2246]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | 1.2.0-RC4 |
#### Actual Behavior

If a EPS or SVG file is uploaded no preview image are shown: 

![image](https://cloud.githubusercontent.com/assets/405874/14315506/0174ede2-fbfe-11e5-8639-e87ab0442766.png)
#### Expected Behavior

A preview image should be shown. In addition vector graphics should probably have its own media type, since it doesn't make too much sense to calculate image formats (would somehow contradict the use case of vectory graphics), and therefore wouldn't be used with formats in twig. In that case it should not be possible to upload a new version with a bitmap graphic.
#### Steps to Reproduce
1. Navigation to media
2. Select an arbitrary collection
3. Upload a SVG or EPS image
#### Possible Solutions

Generating preview images probably doesn't make any sense in that case, since these images are vectorgraphics anyway. We should probably simply show them without any image processing.

However, it might also make sense to rasterize vector graphics, although it might be heavier to load then, depending on the image.

**Comment by chirimoya** [comment]
Be aware of performance issues regarding complex SVGs. Maybe it would make sense to generate preview images.

**Comment by alexander-schranz** [comment]
If possible I would generate a preview images.
But would also add for this images a specific `vector` thumbnail which will be saved in the public folder.

**Comment by danrot** [comment]
We could also implement rasterizing these vector graphics, but I would still introduce an own media type for them. If somebody uses the SVG directly in HTML the page would break if a non-vector graphic would be uploaded.

**Comment by alexander-schranz** [comment]
I dont see the need to an own media type. As he always need to check when output the thumbnail image if the format exists (https://github.com/sulu/sulu-standard/blob/develop/UPGRADE.md#media-preview-urls). It will not run into an 500 error. And when he want to have the vector garphic the developer need to support this in the theme by directly accessing the `vector` format.

```twig
{% if media.thumbnails['vector'] is defined %}
<img src="{{ media.thumbnails['vector'] }}"/>
{% endif %}
```

**Comment by danrot** [comment]
So when the user is uploading a new version of the file it is simply disappearing, which is also not satisfying. With the same argument we could drop the entire media types completely, saying that you always have to check whether it is a video, image, document or something else, and just do nothing in case it isn't.

**Comment by alexander-schranz** [comment]
drop media types I will interpret as a joke. but right the version upload is the problem. And when I rethink it when the developer need to access specific the `vector` thumbnail it is not much work that he will add the new media type to the pages `xml`. So I agree to create a new media type and if possible generate thumbnails (only supported by imagemagick?).

**Comment by danrot** [comment]
Well, it was not really a joke, just a provocative statement to strengthen my point 😉

**Comment by alexander-schranz** [comment]
For the versions we can say that we need a new media type how we handle it in the content type?

But I think its a little confusing for the User that he can`t choice the SVG image in the normal `image` select. 

The media types are currently not visible in the UI or? Maybe we need to add here something?

**Comment by danrot** [comment]
The type is not seen in the UI. And AFAIK it's already possible to add multiple media types. But you are right, the vector media type would have to be a subtype of the normal image media type, if we calculate rasterized graphics as described before.

**Comment by ZeeCoder** [comment]
+1 for SVG assets support.

**My use-case:**
We needed to have the ability to recolor certain images on a specific page.
The way we did it is that we require SVG to be uploaded, and we have a color field.
Then on the page some javascript inlines and recolors the SVGs.

**However we encountered two problems:**
- no previews (Which can be simply ignored)
- multiple subsequent calls to the image's `url` property causes it to sometimes return with an empty response.

**More detail on the last one:**
It seems that when the same asset is being requested through the `MediaStreamController`'s `downloadAction` method (triggered in twig by accessing the media object's `url` property), the second request simply returns a response with no content.

**Summary**
For my specific use-case, just the ability to say "use this SVG asset as-is without any kind of preprocessing" would solve my problem, but currently I can only access uploaded SVGs by using the `url` property. :/

**Comment by alexander-schranz** [comment]
@ZeeCoder the problem use the svg is that the content type is `text/html` detected by e.g. Apache but should be `image/svg+xml`. A quickfix would to implement currently your own svg controller e.g.: 

```
svg:
    path: /uploads/svg/{id}-{version}.svg
    defaults:
        _controller: "ClientWebsiteBundle:Svg:svg"
```

```php
<?php

namespace Client\Bundle\WebsiteBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Request;

class SvgController extends Controller
{
    /**
     * Returns the SVG file for the given $id.
     *
     * @param Request $request
     * @param $id
     *
     * @return BinaryFileResponse
     */
    public function svgAction(Request $request, $id)
    {
        try {
            $mediaManager = $this->get('sulu_media.media_manager');
            $media = $mediaManager->getById($id, $request->getLocale());
            $version = $media->getVersion();

            $path = $this->get('sulu_media.storage')->load(
                $media->getName(),
                $media->getVersion(),
                $media->getStorageOptions()
            );

            $cachePath = $this->cache($path, $id, $version);

            $response = new BinaryFileResponse($cachePath);
            $response->headers->set('Content-Type', 'image/svg+xml');

            return $response;
        } catch (\Exception $e) {
            throw $this->createNotFoundException('Media not found!', $e);
        }
    }

    /**
     * @param $path
     *
     * @return string
     */
    protected function cache($path, $id, $version)
    {
        $fileSystem = new Filesystem();

        $fileSystem->copy(
            $path,
            sprintf('%s/../web/uploads/svg/%s-%s.svg', $this->get('kernel')->getRootDir(), $id, $version)
        );

        return $path;
    }
}
```

and then create a twig extension which will get your svg url `/uploads/svg/{id}-{version}.svg`

**Comment by ZeeCoder** [comment]
Awesome, thanks for the detailed response, I'll try it out and come back to you as soon as I can!

**Comment by ZeeCoder** [comment]
Worked like a charm, thanks @alexander-schranz . :)

**Comment by alexander-schranz** [comment]
that sulu converts a svg to pngs the following steps are needed:

1. imagemagick need to be installed with libsvg:

```
brew install imagemagick --with-librsvg
```

2. webserver mime type detection

media mime type need to be:

```
image/svg+xml
```

if this is correct sulu will convert the svg to a png thumbnail.

**Comment by ZeeCoder** [comment]
Well it kinda works, but the last two looks broken.
It would be better just using the original SVGs instead.

<img width="286" alt="screen shot 2016-08-30 at 10 00 08" src="https://cloud.githubusercontent.com/assets/3679506/18082892/ae656fb0-6e98-11e6-9325-470ccdd9afca.png">

**Comment by alexander-schranz** [comment]
@ZeeCoder looks for me your imagemagick dont work correctly the response you get I did get before I did reinstall imagemagick with `brew install imagemagick --with-librsvg`. dont forget to clear the thumbnail cache before retrying it.
