### ISSUE TITLE
`parent` key not found in routing.yml

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2250]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2-RC4
| Browser Version | Browser name and version

#### Actual Behavior

Accessing `/admin`:

![getzner1](https://cloud.githubusercontent.com/assets/530801/14343447/f04e5846-fc98-11e5-8c01-c5b3e589a5ef.png)

#### Expected Behavior

Show the admin.

#### Steps to Reproduce

Upgrading project from 1.1 to 1.2

**Comment by dantleech** [comment]
This was "avoided" by merging the RC4 branch instead of manually upgrading, however I still do not know what the problem was. I don't think merging is a good strategy for upgrading.

**Comment by wachterjohannes** [comment]
but that have to be discussed in the issue https://github.com/sulu/sulu-standard/issues/633 .

This issue will be fixed by addind the `type: rest` to the inclusion of the `routing_api.yml` of CategoryBundle (see https://github.com/sulu/sulu-standard/blob/develop/app/config/admin/routing.yml#L56)
