### ISSUE TITLE
logout icon is a padlock

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2253]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.2.0-RC4 |
| Browser Version | Browser name and version |
#### Actual Behavior

Logout button is a padlocck

![getzner2](https://cloud.githubusercontent.com/assets/530801/14345782/dae55dd4-fca6-11e5-8f4c-8ea742db20a1.png)

This doesn't indicate to me that it is either a button or that it would log me out.
#### Expected Behavior

Would expect something like

![power off](https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRXtX0E3boESc99ICFE_tT4k3Qz3ylL6HKRAUcjmGzRzlAw8eWr)

/cc @berndhep

**Comment by alexander-schranz** [comment]
will be changed in 2.0
