### ISSUE TITLE
DocumentNotFoundException should not automatically translate to 404

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2259]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.0-RC4 |
| Browser Version | N/A |
#### Actual Behavior

Currently any uncaught `DocumentNotFoundException` gets converted to a 404.
#### Expected Behavior

It should be a 500. In _some_ cases it may mean that the "page" does not exist, but in others it means there is an invalid state and the error should be a 500.

For example, the CustomUrlBundle uses the doucment manager to find its base node, if the base node does not exist then it throws a `DocumentNotFoundException`, it gets converted to a 404 response, however is misleading:
- The resource does exist.
- 404 does not suggest that the server has a problem.
- The server is in an invalid state, it should be a 500.
#### Possible Solutions

Only turn HttpNotFoundException's into 404 responses.

**Comment by wachterjohannes** [comment]
The problem here is that we use the fos-rest bundle to translate Exception to status-code. this could not be configured by bundle this have to be configured globally. maybe we find here a better solution.

**Comment by dantleech** [comment]
If the response should be a 404 in case that a Document is not found, then the `DocumentNotFoundException` should be caught and a `HttpNotFoundException` should be thrown, and it should be given the `DocumentNotFoundException` as the previous exception (the third argument).

**Comment by danrot** [comment]
@dantleech I agree with your last comment, but it should not be translated to a 500 in my opinion. It's not the server's problem if the user passes something that does not exist, it should still be an error from the 4xx range, I'd suggest 400 (bad request), because the sent request was not valid.

**Comment by dantleech** [comment]
In the case of the CustomUrl it was the servers problem - it was missing
a "system" node (that would have been created with the
sulu:dcoument:initialize command).

But yes, an *appropriate* response should be sent.

**Comment by danrot** [comment]
This will not be fixed before a bigger refactoring, therefore going to close it.
