### ISSUE TITLE
CustomUrl: No AJAX spinner whilst saving.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2262]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

When you click save there is no indication in the UI that the save is being performed. The
case is special as this could be the only overlay in Sulu which performs a large AJAX request.

![sulu2](https://cloud.githubusercontent.com/assets/530801/14350294/7b3d3838-fcc0-11e5-8d3a-3684c6d4c1c4.png)

#### Expected Behavior

I would expect some UI state change to happen when I click "save", and maybe an AJAX spinner to appear somewhere.

#### Possible Solutions

- Animate the save button?

/cc @berndhep

**Comment by wachterjohannes** [comment]
i have talked to @berndhep that we will show a loader instead of the save button.
