### ISSUE TITLE
Collaboration warning excludes username when the collaborator is the current user.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2263]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0-RC4
| Browser Version | Browser name and version

#### Actual Behavior

If you have 2 users logged in with the same username and they are editing the same page then the "collaboration warning" ommites the username:

![user](https://cloud.githubusercontent.com/assets/530801/14350814/6c87eed4-fcc3-11e5-99cd-8769720b531b.png)

#### Expected Behavior

It should show either the users username e.g. `daniel@dantleech.com`, or have a custom message "You are currently editing this page in another session."

#### Steps to Reproduce

Login to Sulu in two separate browsers with the same username, edit the same contact in both browsers.

**Comment by danrot** [comment]
The overlay should show your own username in that case.
