### ISSUE TITLE
Content language is kept over different webspaces without fallback

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2265]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0-RC4

#### Actual Behavior

Assume you have two different webspaces with different localizations. If you are on the content tree of one webspace, switch to a language which only exists in this webspace, and change to the content tree of the other workspace, the content tree loads, but all the titles are missing:

![image](https://cloud.githubusercontent.com/assets/405874/14352055/d891cb2c-fcd2-11e5-84b0-62aa9f121e34.png)

Also the language in the URL fragment is not changing. I assume this happens because the system only handles one `contentLanguage` in the user's settings.

#### Expected Behavior

The system should navigate to a localization which is existing in the selected workspace. There are two possibilities:

1. In case the selected content language does not exist in the selected workspace fallback do another one.
2. Remember a different user setting for each webspace

#### Steps to Reproduce

1. Create a webspace with the localizations `en` and `de`
2. Create another workspace only with the localization `en`
3. Create a english page in the second webspace
4. Create a english page on the first webspace
5. Switch in the content tree of the first webspace to `de`
6. Navigate to the content tree of the second webspace

**Comment by dantleech** [comment]
Another possiblility: you could make the definition of locales global and allow them to be "activated" for the purposes of locale-switching on the website.

**Comment by danrot** [comment]
@dantleech: How should that help? Or do you suggest that all webspaces have the same localization? Because I think that's not a real option.
