### ISSUE TITLE
BC break in twig `sulu_content_path` method.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2266]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0-RC4

#### Actual Behavior

Calling `{{ sulu_contrent_path('/path/to') }}` will return the fullly qualified URL: http://foobar.com/de/path/to` previously it returned only the `/de/path/to`.

#### Expected Behavior

It should maintain the previous behavior, or we would introduce a BC break in a minor version upgrade.

#### Possible Solutions

- ?

**Comment by wachterjohannes** [comment]
that should be handled before 1.2 - at least we should write it into the UPGRADE.md to be sure the users notice this change.
