### ISSUE TITLE
Radio (single_select): cannot unselect, default is unselected + is non mandatory.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2268]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.0-RC4 |
| Browser Version | Browser name and version |
#### Actual Behavior

When using the `single_select` (radio) content type the default state is unselected.

![check1](https://cloud.githubusercontent.com/assets/530801/14376315/63668b74-fd60-11e5-9ea3-fb24174fe9c3.png)

You can consequently save the page in this state.

When you select a an option it is irreversable.

![check2](https://cloud.githubusercontent.com/assets/530801/14376334/9a894e20-fd60-11e5-82e9-d6bddbd0c99f.png)

This means that the state of the page changes irreversably once the user clicks the radio box and saves the page.
#### Expected Behavior

The form control should be able to be changed back to its initial state.
#### Steps to Reproduce
1. Create a new page containing the `single_select` content type.
2. Save the page.
3. Select an option.
4. You cannot revert the form control to its initial state.
#### Possible Solutions
- The initial control should appear unselected, but mandatory.
- A default must be provided, if not the first value should be preselected.
- There can be an button to unselect the options.

/cc @webmozart

**Comment by danrot** [comment]
Since this is the default HTML behavior I would not handle this in a different way.
