### ISSUE TITLE
Tidy up the CoreBundle

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2282]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | develop |
| Browser Version | Browser name and version |
#### Actual Behavior

Currently the CoreBundle contains lots of things which should not be there, and other things which are not sensibly configured.
- `node_names`: Defines the names of "folder" nodes in the content repository. There should be handled by the `PathSegmentRegistry` and configured in the `DocumentManagerBundle` (if they are not already).
- `types`: Defines the templates for a set of pre-configured types: `text_line`, `text_area`, etc. This should, if anything, be a dynamic array mapping templates to types. It should be in the `ContentBundle`.
- `language`: Defines the PHPCR namespace and the default language. Should be in the `DocumentManager` bundle.
- `structure`: Should be in the `ContentBundle`.
- `phpcr`: Should be in the `DocumentManagerBundle` (probably obsolete now).
- `webspace`: Should be in the `WebspaceBundle` I suppose.

**Comment by danrot** [comment]
Related to https://github.com/sulu/sulu/issues/602 ? Will close the other one, since this one is more detailed.
