### ISSUE TITLE
[RFC] CHANGELOG policy

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2283]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
#### The Problem

Curently the developer is expected to add a changelog entry for each pull request.

This means that:
- EVERY time a pull request is merged, all other pull requests become conflicted.
- Travis does not build the PR(?) branch when there is a conflcit.
#### A Solution

I propose that we adopt an atomic commit policy where by the commits are as follows:

```
#1234 [TestBundle] Fixed something

The something thing now uses the other thing in order
that something does something else.
```

or

```
<PR number> [<affected component>] <short description>

<details description>
```

The changelog can then be generated by a script _at the time of the release_:
- The first line will be the CHANGELOG entry (as per our current CHANGELOG format).
- We can include the GIT commit hash in the CHANGELOG entry.
- We exclude merge commits.

The Liip [RMT](https://github.com/liip/rmt) (release management tool) already does this, although I am not sure if we would want to adopt that tool (which does too much imo), roll our own, or find something on packagist.
#### Benefits
- Single Point of Truth for the change log.
- Will lead to improved GIT commit messages.
- Easier to cherry-pick features and therefore use multiple PRs when building large features.
- We save time - almost every PR conversation ends with "add a changlog" or/then "resolve the changelog conflict"

**Comment by wachterjohannes** [comment]
as i said i don't like the strict commitment to atomic commits. we should not force this everywhere in all situations. I can live with it but changing the contribution guidelines for every "github change" or "git feature" make it quite hard to contribute to sulu. also i am with @chirimoya when he said that the changelog file should be there. if we have a possibility to take a look at this without git it would be ok for me.

**Comment by patkar** [comment]
:-1: for automatic changelog. Would even prefer the style of keepachangelog.com which defines subsection so you can sort mentally the changes relevant to you. Changelog should be human readable, it's not a machine format ;) This means, not every PR would need a changelog entry..

To solve the conflict situation, a

    CHANGELOG.md merge=union

in the `.gitattributes` may help. This should prefer both sides of the merge to be merged without conflict

**Comment by dantleech** [comment]
@patkar the changelog would not be *automatically* merged, it would only be generated, manually, with a script. It could then subsequently be edited as required.

The generation format would be exactly the same as our current CHANGELOG.

iirc the `merge=union` approach did not work (I don't know the details, ask @danrot ).

**Comment by danrot** [comment]
Yeah, `merge=union` was causing problems, and github was still recognizing it as a conflict and didn't allow to merge it. Sometimes lines were doubled, e.g. when people felt like fixing a typo in a older changelog line.

And the changelog can still be there, but would be automatically generated at the release. However, I would not put the PR number in the commit message, if avoidable... (I can imagine that this might be necessary to put this information in the changelog).

**Comment by danrot** [comment]
And @wachterjohannes as we already discussed it is not really making it harder to contribute to Sulu, since we could still do the merge or use the new merge and squash feature of GitHub.

**Comment by dantleech** [comment]
@danrot we could get the PR number from the merge commit perhaps.

**Comment by wachterjohannes** [comment]
@danrot we will see (: we will see (:

**Comment by danrot** [comment]
@wachterjohannes Just merged the PR https://github.com/sulu/sulu-docs/pull/203 like that, couldn't be easier 😛

**Comment by danrot** [comment]
The feature is also related to https://github.com/sulu/sulu/issues/2073

**Comment by danrot** [comment]
Since we have to continue to work now, we have decided to do atomic commits now, and see how that goes. If we ditch the manual changelog entry we will decide after the next release, so long this issue is open for discussion.

**Comment by danrot** [comment]
Since we have to continue to work now, we have decided to do atomic commits now, and see how that goes. If we ditch the manual changelog entry we will decide after the next release, so long this issue is open for discussion. /cc @sulu/developer

**Comment by danrot** [comment]
Since we already started not writing a changelog in the `develop` branch, we can close this issue now.
