### ISSUE TITLE
Backend search - save information of clicked search element for tree view

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#2296]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | 1.2 (and all before) |
| Browser Version | all |
#### Actual Behavior

When searching for a page in the Sulu-Backend-Search and clicking on one of the result pages, the page will be correctly loaded.

On that loaded page there is at the top left corner a back button - pressing that back button opens the tree view of all pages but without selecting the current page. That means I don't know where the page is located inside the tree.
#### Expected Behavior

When clicking on a page outgoing from the Sulu-Backend-Search, some informations should be saved. After clicking the page and then the top left back button, the node tree should have the information which page was just selected.
#### Steps to Reproduce
1. Login to Sulu, use Search and search for a page that exists
2. Click on the search result to open the page
3. Click on the back button

**Comment by danrot** [comment]
@chirimoya My idea would be to save the user setting when the page form is opened. Then it would not matter where the user came from. If it is really that easy that would be something @ReneZumtobel could do.
