### ISSUE TITLE
404 Page not working on .aspx

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2297]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0

#### Actual Behavior

Default 404 Page is shown

#### Expected Behavior

What is the behavior you expect?

Themed 404 Page should be shown

#### Steps to Reproduce

http://sulu.io/en/test.aspx

#### Possible Solutions

Handle .aspx same way as .php

**Comment by danrot** [comment]
This is because the ending of the file is tried to be used as format. If we don't know the passed format we should probably always render html, I'll implement that today.
