### ISSUE TITLE
Show only webspace languages in language selector

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2301]
| Q | A
| --- | ---
| Bug? | not sure
| New Feature? | no
| Sulu Version | 1.2.0
| Browser Version | All

#### Actual Behavior

The languages from all webspaces and all languages which are defined in sulu.yml > sulu_core > translations (which are the languages which can be selected for the Sulu admin interface) are shown in the language selector in global areas like media and snippets.

sulu.yml:
![sulu yml](https://cloud.githubusercontent.com/assets/5627878/14556277/b526943a-02f7-11e6-85c5-e2303c5d122c.png)

webspace.xml:
![webspace](https://cloud.githubusercontent.com/assets/5627878/14556283/ba93eec2-02f7-11e6-9a53-ab11dbdea479.png)

= language selection in media/snippets:
![sulu-languages](https://cloud.githubusercontent.com/assets/5627878/14556284/c63b1318-02f7-11e6-8e1d-3981883e03b6.png)

Languages can be removed from the config which may be a solution in some cases. It is not a solution if there is no translation for the Sulu admin interface for the language selected in the webspace. I think it is quite confusing because the user may not understand why fr can be selected in the example above.

#### Expected Behavior
Show only all languages from all webspaces.

#### Possible Solutions
Maybe fixing #2300 is enough. The language would still be selectable when choosing the languages in the permissions tab of a user but at least it can be excluded from the language chooser in media/snippets.

**Comment by danrot** [comment]
I am not sure if we only want to show the languages from the webspaces here... E.g. if Sulu is used as PIM, we might also want to include the language from the PIM in this dropdown. But you are right the system language should not be used here.

I don't see #2300 being related to that.

If we really only want to use the webspace localizations we can use the `WebspaceLocalizationController` instead of the `LocalizationController`.

**Comment by chirimoya** [comment]
Remove system languages from `LocalizationController `.

**Comment by danrot** [comment]
Fixed with https://github.com/sulu/sulu/pull/2618
