### ISSUE TITLE
Add Permission support to ListBuilder

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#2310]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | all
| Browser Version | all

#### Actual Behavior

When using the ListBuilder currently there's no possibility to consider permissions - which means that all list items are displayed.

#### Expected Behavior

The ListBuilder should only show the list items that are viewable by the logged in user automatically. Furthermore it should be possible to filter / display only the list items I am able to edit. (or filter by any other permission)

**Comment by danrot** [comment]
Closed via #2312
