### ISSUE TITLE
Enlarge input field for Custom URLs

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2311]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version |  1.2.0
| Browser Version | Tested on Firefox, Chrome and Safari for Mac

#### Actual Behavior
The input field for custom URLs is very small:

![custom-url](https://cloud.githubusercontent.com/assets/5627878/14637281/9dad23aa-0630-11e6-8c24-83899e4224d5.png)

#### Expected Behavior
Fit the width of the input field to the width of the overlay.

**Comment by danrot** [comment]
Fixed in d722ef4
