### ISSUE TITLE
Page translation for page with type "internal link"

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2313]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0
| Browser Version | All

#### Actual Behavior
Adding a translation for a page with "internal  link" as page type does not work as expected:

When selecting "Create a new empty page in this language": 
- A page with type internal link is created
- The content of "Linked content" is copied and "No Title (/main/sub-1)" is shown (even if the linked page is not available in this language)
- Selecting "content" as page type and saving afterwords leads to an error ("Document has no title (title is required for auto name behavior)")

![internal-link](https://cloud.githubusercontent.com/assets/5627878/14667857/a3907bee-06e1-11e6-84af-8121a5b37120.png)

When selecting "Create a new page in this language and copy content from": 
- The content of "Linked content" is copied and "No Title (/main/sub-1)" is shown (even if the linked page is not available in this language)

#### Expected Behavior
When selecting "Create a new empty page in this language": 
- A page with type content should be created.

When selecting "Create a new page in this language and copy content from": 
- The content of "Linked content" should not be copied if the selected page is not available in the current language.

**Comment by danrot** [comment]
Partly related to https://github.com/sulu/sulu/issues/1381
