### ISSUE TITLE
[Content] ShadowCopyPropertiesSubscriber refactoring.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2328]
#### Actual Behavior

[This subscriber](https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Content/Document/Subscriber/ShadowLocaleSubscriber.php):
- uses hard-coded PHPCR namespaces and property names. 
- has the property encoder injected into it, but it is not used.
- is explicitly coupled to tags, categories and nav contexts.
#### Expected Behavior

It should at least use the property encoder and it should ideally not be coupled to tags, categories and nav contexts.

It should use a regex to determine the locale property.

**Comment by danrot** [comment]
This will not be fixed before a bigger refactoring, therefore going to close it.
