### ISSUE TITLE
[Content] Security Subscriber should use PropertyEncoder.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2329]
#### Actual Behavior

Security encoder uses hard coded PHPCR namespace prefix.
#### Expected Behavior
1. It should not used hard coded namespace prefix.
2. The document manager should be able to store nested arrays.
#### Possible Solutions
- The namespace registry should be used to retrieve the namespace via an assigned role. (the property encoder need not be used in this case).
- Ultimately the document manager could be able to store nested arrays, simplifying this logic and removing the above issue.

**Comment by danrot** [comment]
This will be part of a bigger refactoring, therefore going to close this issue.
