### ISSUE TITLE
Use template key instead of filename to create cache classes

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#233]
Currently the filename (without .xml) instead of the defined key is used to create the class name of the structure cache classes. Additionally the system crashes, if the filename without the extension (later hopefully the key) contains some characters, which are not valid in a class name (e.g. ".")

**Comment by dantleech** [comment]
Should be addressed in #685

**Comment by dantleech** [comment]
See also https://github.com/sulu-io/sulu/issues/1266#issuecomment-112920906

**Comment by danrot** [comment]
I don't think that we change that before a major refactoring, so I am going to close it.
