### ISSUE TITLE
Images - Titel / Alt Titel – SEO

### ISSUE THREAD

**Issue by StefaniePueschel** [sulu/sulu#2343]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | 1.2 |
| Browser Version |  |
#### Actual Behavior

Images: For each image iIt is just possible to add "Titel" – which is then automatically shown as Alt. For SEO it is important to be able to add "Titel" and "Alt Attribute".
#### Expected Behavior & #### Solutions

Be able to add "Titel" --> is going to be shown as Titel
Be able to add "Alt Attribute" --> is going to be shown as Alt Attribute

**Comment by You85** [comment]
+1

**Comment by alexander-schranz** [comment]
@You85 its the developers choice how he use the 2 fields title and description. I recommend normally the following way:

```
<img src="..." alt="{{ media.title }}" title="{{ media.description|default(media.title) }}">
```

alt = Title
title = description with fallback to title

**Comment by danrot** [comment]
I think @alexander-schranz approach fixes this problem.
