### ISSUE TITLE
Use WebsiteKernel for rendering Preview

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2350]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | d5cad47be5f2bd49c7f0639cd99076ed3fb99c27
| Browser Version | none

#### Actual Behavior

The preview uses the AdminKernel to render.

#### Expected Behavior

It should use the WebsiteKernel.

**Comment by chirimoya** [comment]
https://github.com/sulu/sulu/pull/2357
