### ISSUE TITLE
SearchBundle - fix SearchController query execution (array)

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#2360]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.2.1
| Browser Version | --

#### Actual Behavior

When using the Sulu Backend search, it expects an array. When the Pull Request of the MassiveSearchBundle will be merged, this is a problem because it returns an ArrayIterator. (https://github.com/massiveart/MassiveSearchBundle/pull/79)

#### Expected Behavior

To see the list of results.

#### Steps to Reproduce

Search for something in the Sulu Backend search with the data of the Pull Request linked above.

#### Possible Solutions

Change the `SearchController` line 119 and add `iterator_to_array()` like followed:

```
$adapter = new ArrayAdapter(iterator_to_array($query->execute()));
```

**Comment by wachterjohannes** [comment]
@thomasduenser could you create a PR for sulu also before we merge the linked massive-search PR. so this is not really a critical bug but should be fixed before merging massive-search.
