### ISSUE TITLE
User rights language chooser.

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#2372]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0
| Browser Version | Every Brower

#### Actual Behavior

At the moment the language dropdown grows out of content and isn't scrollable

![bildschirmfoto 2016-05-09 um 13 23 01](https://cloud.githubusercontent.com/assets/8446502/15112938/a1197c34-15f1-11e6-8c3a-50af64d247a6.png)

#### Expected Behavior

With a max-height and overflow: auto;

#### Steps to Reproduce

Add languages to webspace and try to give a user rights in all languages

#### Possible Solutions

    max-height: 315px;
    overflow: auto;

**Comment by danrot** [comment]
Giving it a fixed `max-height` doesn't seem like a good solution to me... If the screen is small enough you'll get the exact same problem again. I try to find a programmatic solution.
