### ISSUE TITLE
Show navigational context in collection navigation

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2393]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.2.0

#### Actual Behavior

Sulu doesn't show any breadcrumb or something similar for the navigation of the collections:

![image](https://cloud.githubusercontent.com/assets/405874/15218035/58c7fd10-185e-11e6-8b36-d313f311efdc.png)

#### Expected Behavior

There should be a breadcrumb or something similar, to help the user know where in the tree he is currently located. This would especially be useful if the tree is quite big.

#### Steps to Reproduce

1. Navigate to `Media`
2. See that in the navigation is no context shown

**Comment by chirimoya** [comment]
Breadcrumb as Collection-Subtile in the right content block.

**Comment by danrot** [comment]
This is done with the new media design.
