### ISSUE TITLE
Create sulu-minimal edition

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu#2406]
We'd like to create a new [sulu-minimal edition](/sulu/sulu-minimal) that will be used to bootstrap new projects in the future. This edition will only contain the bare minimum of files required to start a new project.

A few notes on the new edition:

- We'll use the Symfony 3 folder structure
- We'll remove the LiipThemeBundle by default. A new SuluThemeBundle is introduced for adding theme support to Sulu.
- We'll remove Assetic. Most projects don't use or need that library.

The folder structure will look as follows:

```
app/
  config/
    admin/
    website/
  Resources/
    templates/
      pages/
        default.xml
        homepage.xml
      snippets/
        default.xml
    views/
      templates/
        default.html.twig
    webspaces/
      example.com.xml
bin/
  adminconsole
  webconsole
src/
var/
  cache/
    admin/
    website/
  indexes/
  logs/
    admin/
    website/
  sessions/
  uploads/
  database.sqlite
```

We plan to support the creation of new projects with the `composer create-project` command:

```
$ composer create-project sulu/sulu-minimal project-dir
```

Any opinions?

**Comment by patkar** [comment]
What's the big difference to the standard edition?

**Comment by afroewis** [comment]
This is an important issue to me, since I already created my own *sulu seed project* since `sulu-standard` is a bit bloated. 

Just an idea: We could include two page templates (`start.xml` or `homepage.xml` or whatever and `default.xml`), since 99% of projects have a custom start page and define them in the webspace config as `default-template`. What do you think?

**Comment by webmozart** [comment]
@patkar The big differences to the standard edition are:

* The edition must work out of the box (e.g. no renaming of .dist files)
* The edition must not contain files that need to be deleted or largely changed when starting a project (hence "minimal")

In addition, we are planning a "Sulu Demo (Edition)" that's Sulu Minimal plus a real-world implementation with a design and various features, i.e. a showcase application that's more complete than the current Sulu Standard Edition.

@afroewis A `homepage.xml` makes a lot of sense. I added that above.
