### ISSUE TITLE
Sorting of list is working even if disabled

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#2410]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2
| Browser Version | Chrome 50.0.2661.94

#### Actual Behavior

Every column of datagrid list is sortable, even if sortable is set to false. (in fields-api)

#### Expected Behavior

Non sortable columns should not be clickable

#### Steps to Reproduce

* Go to media bundle
* Sort thumbnails
* boom 

#### Possible Solutions

Fix the bug.

**Comment by wachterjohannes** [comment]
was only a bug in media
