### ISSUE TITLE
Admin search translation keys when having multiple elasticsearch indexes

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#2411]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2

#### Actual Behavior

When having multiple sulu-instances in same elastic search environment and changing the prefix of massive_search (at_sulu and ch_sulu). The indexes of the other installation are shown in admin search (See screenshot).
The at indexes are translated as expected, but also the ch indexes are shown.

#### Expected Behavior

Only see at_sulu indexes.

![image](https://cloud.githubusercontent.com/assets/5152633/15423024/bd5bcf22-1e7b-11e6-887d-ec904a86ae9a.png)

**Comment by wachterjohannes** [comment]
fixed by https://github.com/massiveart/MassiveSearchBundle/pull/95#event-669006231
