### ISSUE TITLE
Allow DOMDocument::xinclude in templates

### ISSUE THREAD

**Issue by gisostallenberg** [sulu/sulu#2417]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | N/A
| Browser Version | N/A

#### Actual Behavior

When using [xincludes](http://php.net/manual/en/domdocument.xinclude.php) in template xml the schema validation fails

#### Expected Behavior

To be able to add xincludes or some other way to import parts of a template, so my definitions can be kept DRY.

#### Steps to Reproduce
```xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xi="http://www.w3.org/2001/XInclude"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">
    <key>default</key>

    <view>ClientWebsiteBundle:templates:default</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <meta>
        <title lang="en">Default</title>
    </meta>
    
    <xi:include href="path/to/my/shared-template-parts.xml#xpointer(/shared/properties)"/>
<!--
...
--->
</template>
```

#### Possible Solutions
[XmlLegacyLoader.php line 85](https://github.com/sulu/sulu/blob/b6ea0dc60fca1e8680ce6f2cff737217fe8c170e/src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php#L85)
```php
​
$xmlDocument = XmlUtils::loadFile($resource, function (DOMDocument $dom) use ($schemaPath) {
	$dom->xinclude();
	
	$schemaSource = file_get_contents((string) $schemaPath);
	
	return @$dom->schemaValidateSource($schemaSource);
});

**Comment by danrot** [comment]
@gisostallenberg Awesome! We didn't know that implementing it is that less work 😄 It looks like you already have a solution, can you maybe create a PR for that?

**Comment by gisostallenberg** [comment]
I will try to make a PR as soon as possible.

**Comment by gisostallenberg** [comment]
It turns out the xsd needs to be changed because xincludes adds a xml:base-attribute.
This is less easy with two namespaces (targetNamespace and xml) mixed. 

When I dynamically remove the base attribute it works though:
```php
            $dom->xinclude();

            $xpath = new \DOMXPath($dom);
            $xpath->registerNamespace('xml', 'http://www.w3.org/XML/1998/namespace');
            foreach ($xpath->query('//@xml:base') as $attr) {
                $attr->ownerElement->removeAttributeNode($attr);
            }
```
Is this acceptable?

**Comment by niels-nijens** [comment]
@gisostallenberg You're able to import XInclude XML Schema validation, as I've done here: 
https://github.com/FlexModel/FlexModel/blob/master/src/Resources/xsd/flexmodel.xsd#L4-L7

**Comment by wachterjohannes** [comment]
@gisostallenberg why cannot we define this attribute in the xsd?

**Comment by gisostallenberg** [comment]
Well, it is namespaced, so AFAIK it should be done using an import.
```xml
<xs:import namespace='http://www.w3.org/XML/1998/namespace' schemaLocation='xml.xsd'/>
```
This all works fine, but there is an issue with the namespace used in the template.xml. Therefor I keep getting:
```
[ERROR 1866] Element '{http://schemas.sulu.io/template/template}properties', attribute '{http://www.w3.org/XML/1998/namespace}base': The attribute '{http://www.w3.org/XML/1998/namespace}base' is not allowed.
```

I will look into this later, although I think the advantage of being able to use xincludes is bigger than disadvantage of removing the attributes. I can make a version where I re-attach the attributes after validation, so the document stays ok.

**Comment by alexander-schranz** [comment]
Does the included xml need not an extra xsd file for the validation?
Because their the root e.g. could be a `section`, `properties`, `params` or something else.

**Comment by wachterjohannes** [comment]
@gisostallenberg i think we have to add `<xs:any minOccurs="0" maxOccurs="unbounded"/>` to the attribute groups of this (or maybe) all xml tags. we already used this for the listbuilder-metadata.

**Comment by gisostallenberg** [comment]
@alexander-schranz No additional xsd's are needed for the included xml. The document is composed before it is validated, so it looks like a whole document. The only thing that is added is the xml:base attribute.

@wachterjohannes the following seems to work
```xml
<xs:anyAttribute namespace="http://www.w3.org/XML/1998/namespace"/>
```
I will have to look into the effects on already defined attributes in the sulu namespace when I add this anyAttribute. The drawback is this has to be added at any level (or any level at which xincludes are to be done). Maybe some kind of baseType can be defined to avoid this having to add it everywhere.

**Comment by danrot** [comment]
@gisostallenberg Does that mean it is allowed to allow every attribute? Can't we be more restrictive here? Means only allowing the `base` attribute?

**Comment by alexander-schranz** [comment]
think we need for the include file a XSD for the developers else the validation and autocomplete in the IDE will not work or can you set the parent xsd?

**Comment by niels-nijens** [comment]
`<xs:anyAttribute/>` with the namespace would only allow any attribute in that namespace and not from the Sulu namespace. Though, I think it might be better to use `<xs:attribute ref="xml:base"/>` instead.

**Comment by gisostallenberg** [comment]
@danrot It means any attribute in the namespace http://www.w3.org/XML/1998/namespace and defined in the imported xml.xsd

**Comment by gisostallenberg** [comment]
@alexander-schranz I will have to look into that, but I think it will be a large tree of xsd's. What IDE do you use to validate?

**Comment by alexander-schranz** [comment]
@gisostallenberg Intelliji / PHPStorm

**Comment by alexander-schranz** [comment]
@gisostallenberg maybe the current xsd file could also be splitted e.g. into `section`, `block`...
think the xsd files will also support to use something like includes?

**Comment by gisostallenberg** [comment]
@niels-nijens I confirmed <xs:attribute ref="xml:base"/> works fine. Still needs to be at any level though
@danrot do you prefer this or the anyAttribute (which allows specified xml:* attributes like xml:lang as well).

@alexander-schranz this is supported and I will do that.

**Comment by danrot** [comment]
@gisostallenberg That's a tricky one... Actually we also don't want anybody to set these attributes on their own, right? Regarding that argument the solution with dynamically removing that attribute before validating sounds nice, because no IDE would suggest this attribute then. However, I am aware that this solution feels a bit hacky, but are there any downsides?

If there are any downsides I would agree with @niels-nijens and allow only the `xml:base` attribute, since the others should not be set.

**Comment by gisostallenberg** [comment]
@danrot I do not see any harm in allowing all attributes from the http://www.w3.org/XML/1998/namespace -namespace, I suppose you want the xml to be validated because you want to rely on it's structure. But you are not using this namespace. In that regard you might even consider adding
```xml
<xs:anyAttribute namespace="##other"/>
```
which allows all attributes in any other namespace than the targetNamespace.

**Comment by danrot** [comment]
@gisostallenberg The crucial question for me here is what does IntelliJ suggest in this case.

**Comment by gisostallenberg** [comment]
@danrot fine, I will provide a PR with the ##other-namespace and wait for your findings.
@alexander-schranz I would like to tear apart the xsd in another PR and suggest to make an issue for that. You do not *have* to use xincludes and do not *have* to use an IDE (although I do). The first thing to accomplish is: will sulu keep working as expected with the suggested changes, that allow developers to centralize parts of their xml.
