### ISSUE TITLE
Contact datagrid infinitescroll pagination

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2421]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2
| Browser Version | all

#### Actual Behavior

The initial state of the contact-list is datagrid with infinitescroll. (maybe also in other modules)

#### Expected Behavior

The list should have dropdown pagination all the time.

#### Steps to Reproduce

Clear you user-settings and go to contact and change view to list.

**Comment by danrot** [comment]
@wachterjohannes Your steps to reproduce seem not to be enough, can you be more specific?

**Comment by wachterjohannes** [comment]
hmm there seems to be more todo ... when i tried it first it was enough but now i also don't get the error. maybe it could be something with the settings. we should keep in mind when it happens again.

**Comment by danrot** [comment]
@wachterjohannes Can you try to find out soon? I am afraid that we have a never closing ticket otherwise...

**Comment by wachterjohannes** [comment]
cannot reproduce it but i have it on my list if it happens i will reopen it with more information.
