### ISSUE TITLE
Uploading video file doesn't work

### ISSUE THREAD

**Issue by c00n84** [sulu/sulu#2422]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.2 |
| Browser Version | all |
#### Actual Behavior

If I uploaded a video file and ffmpeg/ffprobe is missing on the server, I got a misunderstood error. The error said that the file size of 1.8MB is to big. 
#### Expected Behavior

Uploading of a video file should work properly. But it will not generate a preview image of the video.
There could be a notice, which explains that a server extension is missing or something like that and that's the reason why it couldn't generate a preview image.
#### Steps to Reproduce

Upload a video file (e.g. *.m4v) in Sulu.

**Comment by alexander-schranz** [comment]
I would prefer to move the FFProbe and FFMpeg things into an own bundle `SuluVideoBundle` would be a BC Break in the Media and FormatManager construct function @sulu/core-team.

**Comment by wachterjohannes** [comment]
Extracting this into an own bundle would be nice. but i think this cannot be done before 2.0. we should think about another solution.

**Comment by danrot** [comment]
I think just moving this functionality to an own bundle would be kind of an overkill... What about defining the bundle with the ffmpeg as an optional dependency? Then we could inject it with the `on-invalid` flag, and check in the methods calling it if these services are not null.

**Comment by wachterjohannes** [comment]
that would be at least a good step. the "advantage of moving int o an own bundle would be that it would be easier to exchange.

**Comment by alexander-schranz** [comment]
the services exist at the moment when the bundle (dubtureffmpeg) is registered but the upload is failing because the binaries for ffmepg und ffprobe are not installed.
