### ISSUE TITLE
Port number not included in all URL's

### ISSUE THREAD

**Issue by cdesign** [sulu/sulu#2423]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-develop
| Browser Version | Chrome 48.0 / Safari 9.1

#### Actual Behavior

When accessing Sulu over a specific host/port, some links do not correctly contain the port number. 

For example, when loading the Homepage of a clean Sulu install, the 'SULU CMF' link and localization links ('en | de') in the upper left corner do NOT contain the port number, whereas category links in the 'Smart-Content' area at the bottom of the page DO contain the port number. (Note: you must create some categories to see this)

Examples:
'SULU CMF' url:  http://sulu/en
'en' url:  http://sulu:8917/en?categories=1

#### Expected Behavior

All URLs to Sulu content should contain the port number (if not 80 or 443??).

#### Steps to Reproduce

1) create a Host that uses a specific port number (other than 80 or 443??)
2) install a clean version of Sulu
3) add several Categories
4) load the Homepage specifying the port number (ex: 'http://sulu-standard:8917')
     - the 'SULU CMF' and localization links at top do not contain the port number
     - the Category links correctly contain the port number

#### Possible Solutions

This might be helpful: the 'SULU CMF' and localization links all call the 'sulu_content_path' twig extension (from 'master.html.twig'). The Category links are rendered using 'categories.html.twig' and call the 'sulu_category_url' twig extension. So there could be a difference there.

**Comment by cdesign** [comment]
@wachterjohannes: I wanted to let you know that I solved my problem, so I'm not sure that this is an issue.

I was building menus something like this:

`{% for item in sulu_navigation_root_tree( 'main', 2 ) %}
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ item.title }}</a>
	{% for child in item.children %}
		<li><a href="{{ sulu_content_path(child.url) }}" title="{{ child.title }}">{{ child.title }}</a>
	{% endfor %}
</li>
{% endfor %}`

But after doing some var_dumps, I realized that the call to 'sulu_content_path' is not necessary. So I eliminated the call to 'sulu_content_path' like this:

`<li><a href="{{ child.url }}" title="{{ child.title }}">{{ child.title }}</a>`

and now all of my URL's correctly contain the port number.

**Comment by wachterjohannes** [comment]
@cdesign nice solution (: yes this can work until you have only one webspace (or you dont want to link the webspaces you have). also if you put sulu into a subfolder it wont work.

**Comment by danrot** [comment]
Could this be solved by simply always adding the domain in https://github.com/sulu/sulu/blob/6320990f76863b74d4cec6b473f01bbcd403dd18/src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php#L81?

Any caveats I am forgetting about here? /cc @webmozart @wachterjohannes @chirimoya

**Comment by danrot** [comment]
Fixed in https://github.com/sulu/sulu/pull/2840
