### ISSUE TITLE
New Page all tabs are visible on language change

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2425]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.1 (demo)
| Browser Version | Opera 37.0

#### Actual Behavior

Tabs where the content manager cant do anything are visible.

#### Expected Behavior

Tabs should not be visible when create a page in another language.

#### Steps to Reproduce

1. Create a Page in DE
2. Switch to EN to create the Page in EN
3. All Tabs are visible

![newtab](https://cloud.githubusercontent.com/assets/1698337/15668472/bb34ba62-271b-11e6-9fc0-d5583b3dc609.gif)

#### Possible Solutions

Hide Tabs when create a new page.

**Comment by wachterjohannes** [comment]
this was fixed by https://github.com/sulu/sulu/pull/2405 in develop we have decided not to release it in the current 1.2 series.
