### ISSUE TITLE
Copy and move creates flat URL if parent is ghost

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2434]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

Assuming you have a similar structure to this:
![image](https://cloud.githubusercontent.com/assets/405874/15735896/5d63b9d8-289c-11e6-83d8-8f6147fc49c6.png)

If you copy `Bla` to `English` you'll end up with the URL `/bla`.

#### Expected Behavior

The URL should be `/test/bla`, because the URL generation should include all URLs from the nodes on the path to the current node, except for the ghost pages.

#### Steps to Reproduce

1. Create a page `x` in `en` and `de`
2. Create a subpage `y` only in `en`
3. Switch the language so that the page `y` is a ghost
4. Create a page `z` under `x` in `en` and `de`
5. Move or copy the page `z` under `y`
6. See that the URL in `z` in `de` is now `/z` instead of `/x/z`

**Comment by danrot** [comment]
Also affects the test case written for that, especially https://github.com/danrot/sulu/blob/193a099f0020efef1c4abf7ffee9eb06184e32ca/src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ResourceSegmentSubscriberTest.php#L435 and https://github.com/danrot/sulu/blob/193a099f0020efef1c4abf7ffee9eb06184e32ca/src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ResourceSegmentSubscriberTest.php#L298

**Comment by nnatter** [comment]
@danrot: this should be fixed with https://github.com/sulu/sulu/pull/2706

**Comment by danrot** [comment]
It is fixed, and I can't reproduce the error you have talked about.
