### ISSUE TITLE
annotations conflict

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2435]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

This line causes a conflict with annotations
https://github.com/sulu/sulu/commit/2329b9398d9e374278b8586442c668b3d2d17db6#commitcomment-17709223

**Comment by wachterjohannes** [comment]
@piratadelfuturo i will fix that today (:

**Comment by piratadelfuturo** [comment]
Thanx
