### ISSUE TITLE
First run of sulu:build dont run when db is created immediately before

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2436]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2
| Browser Version | Bash

#### Actual Behavior

In  `sulu:build` after:

```
sulu_custom_urls.initializer
          test.lo:
          [+] items path:: /cmf/test/custom-urls/items
```

it errors with:

```
[PHPCR\RepositoryException]
          You need to be logged in for this operation
```

Run the command again have no error.

#### Expected Behavior

The command should not fail.

#### Steps to Reproduce

0. clone a sulu project
1. composer install
2. choice doctrine dbal for phpcr
3. create new db
4. run `sulu:build dev`

**Comment by wachterjohannes** [comment]
The problem seems that jackalope does not login after creation of workspace.

**Comment by danrot** [comment]
Might be fixed with https://github.com/sulu/sulu/pull/2509, please close if I am right.

**Comment by alexander-schranz** [comment]
@danrot works!
