### ISSUE TITLE
sulu_content_path() misshandles external links

### ISSUE THREAD

**Issue by thgie** [sulu/sulu#2437]
| Q | A
| --- | ---
| Bug? | yes
| Sulu Version | 1.2.1

#### Actual Behavior

`sulu_content_path()` appends the external url to base url and returns that string.

#### Expected Behavior

I was told `sulu_content_path()` would handle that and just return the external url

##### twig

```twig
{% for item in links %}
    <li >
        <a href="{{ sulu_content_path(item.url, 'physio_ch', locale) }}" title="{{ item.title }}">{{ item.title }}</a>
    </li>
{% endfor %}
```

##### generated html

```html
<li >
    <a href="http://physio.lo/dehttps://www.cloudtec.ch" title="Externer Link Eins">Externer Link Eins</a>
</li>
<li >
    <a href="http://physio.lo/de/shop/boutique" title="Boutique">Boutique</a>
</li>
<li >
    <a href="http://physio.lo/de/shop" title="Shop">Shop</a>
</li>
```

#### Possible Solutions

I check for `item.nodeType` to seperate internal and external. `Type 1` is internal, `type 4` is external. That way I also can set a _blank for external.

**Comment by wachterjohannes** [comment]
seems not a problem in sulu i will talk to @thgie in slack channel about that.
