### ISSUE TITLE
Firefox: Preview is loaded twice, loader does not disappear

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2446]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 587a07e3848e2bfa2ee09ea378517737d8cc9508
| Browser Version | Firefox 46.0.1

#### Actual Behavior

Preview is loaded twice and browser tab loader does not stop loading.

![sulu-preview-twice](https://cloud.githubusercontent.com/assets/5627878/15773250/4129ad38-2976-11e6-9486-d63522b3a761.png)

#### Expected Behavior

Preview should only be loaded once and browser tab loader should stop loading.

#### Steps to Reproduce

Load any page in the Sulu admin area.

**Comment by danrot** [comment]
Cannot reproduce twice loading of preview... But can confirm that loader spins all the time...
