### ISSUE TITLE
Requestanalyzer current localization should fallback to default locale

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2449]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.3

#### Actual Behavior

When the request analyzer dont find the locale the `getCurrentLocalization` function is null and will error in the request analyzer resolver.

#### Expected Behavior

The getCurrentLocalization function should return the default Localization instead of the null. 

#### Steps to Reproduce

Easiest way to reproduce is:

1. Create a controller with a route (`/example`)  (NOT from type `portal`) 
2. Access the request analyzer and resolve it. 
3. Call `/example` the resolver will error with call `getLocalization` function on a none object

#### Possible Solutions

A. Set Default Localization as Current Localization when not found

or

B. Check in the requestAnalyzerResolver resolve function if `getCurrentLocalization` is not null before access `getLocalization` function

**Comment by wachterjohannes** [comment]
i would go with B

**Comment by alexander-schranz** [comment]
fixes by #2489
