### ISSUE TITLE
Typo in backend.en.xlf

### ISSUE THREAD

**Issue by cdesign** [sulu/sulu#2450]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.2
| Browser Version | Chrome 51.0; Safari 9.1.1

#### Actual Behavior

The smart content 'Choose Categories' panel has a dropdown choice list called 'Condition'. The first choice list value is 'Use pages that use ANY tag'. Should be '...ANY category'. This error exists in both the 'en' and 'fr' translations. 'de' is correct (I think, but I don't speak German).

#### Expected Behavior

The first choice list value should be 'Use pages that use ANY category'.

#### Steps to Reproduce

1) Default Sulu install.
2) Enable the 'Example' page type.
3) Create a page and set the type to 'Example'.
4) Select the 'References:Similar Pages' configure button.
5) In the 'Configure Similar Pages' dialog click 'Choose categories'.
6) The incorrect choice list value can be seen in the 'Condition' dropdown. 

<img width="701" alt="typo in dropdown any tag" src="https://cloud.githubusercontent.com/assets/5658799/15801939/f5a265cc-2a69-11e6-88df-879757981660.png">

#### Possible Solutions

This typo needs to be corrected in these two files:
/src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.en.xlf
/src/Sulu/Bundle/ContentBundle/Resources/translations/sulu/backend.fr.xlf

search for: id="e4b14069a8a085ede2092hf51234dh45"

**Comment by wachterjohannes** [comment]
fixed and will be released with the next hotfix release.
