### ISSUE TITLE
Incorrect button text in 'Choose data source' dialog

### ISSUE THREAD

**Issue by cdesign** [sulu/sulu#2451]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2
| Browser Version | Chrome 51.0; Safari 9.1.1

#### Actual Behavior

The smart content 'Choose data source' dialog displays incorrect button text in the what I think is supposed to be a 'Back' button:

<img width="1117" alt="incorrect button text" src="https://cloud.githubusercontent.com/assets/5658799/15801971/d23e7b88-2a6a-11e6-81f6-06a24549299d.png">
 
#### Expected Behavior

The 'en' translation should be either 'Back' or 'Cancel'. Not sure about 'fr' translation.

#### Steps to Reproduce

1) Default Sulu install.
2) Enable the 'Example' page type.
3) Create a page and set the type to 'Example'.
4) Select the 'References:Similar Pages' configure button.
5) In the 'Configure Similar Pages' dialog click 'Choose source'.
6) The incorrect button is at bottom left of the Choose source dialog.

#### Possible Solutions

There seems to be a conflict with this .xlf trans-unit-id:
id="90a3276459ba0f52ef7a41320298d5d"

The trans-unit-id in the 'de' .xlf uses a resname of '.cancel' whereas 'en' and 'fr' translations use '.back'.

![inconsistent trans unit ids](https://cloud.githubusercontent.com/assets/5658799/15802027/97db8092-2a6c-11e6-976f-ec4b8a2434ac.png)

**Comment by wachterjohannes** [comment]
fixed and will be released with the next hotfix release.
