### ISSUE TITLE
Copy page command copies multiple pages

### ISSUE THREAD

**Issue by cdesign** [sulu/sulu#2453]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2

#### Actual Behavior

The 'Copy page' command sometimes copies multiple pages. Specifically, if multiple copies of a page exist under the same parent node, when the original page is copied, that page *AND* all of its clones (under the same parent node) are copied.

This may be the same issue as: https://github.com/sulu/sulu/issues/2429

#### Expected Behavior

Obviously, only the page selected should be copied.

#### Steps to Reproduce

1) default Sulu 1.2 install
2) Create the following content hierarchy:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Section 1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Page 1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Page 2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Page 3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Section 2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Section 3

** Be sure to use the '+' button or 'Save and new' command to create the pages (not 'Copy page').

3) Select Page 2 in the content hierarchy and clone it using the 'Copy page' command (under the gear dropdown menu at bottom).

4) Rename the cloned page to 'Page 2 Copy'. Your content hierarchy should now look like this:

<img width="568" alt="content setup" src="https://cloud.githubusercontent.com/assets/5658799/15807629/7da27462-2b28-11e6-9ae8-cc5d6ea0bb2e.png">

5) Now.. Select 'Page 1' and select 'Copy page' from the gear menu. Choose 'Section 2' as the destination parent.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Sulu correctly copies Page 1 to Section 2

<img width="567" alt="copy 1 result" src="https://cloud.githubusercontent.com/assets/5658799/15808169/684b7632-2b36-11e6-8ac6-3e10c0747cc7.png">

6) Select 'Page 2' and select 'Copy page'. Choose 'Section 3' as the destination parent.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Sulu <b><u>incorrectly</u></b> copies both 'Page 2' and 'Page 2 Copy' to Section 3

<img width="569" alt="copy 2 result" src="https://cloud.githubusercontent.com/assets/5658799/15808171/776c4128-2b36-11e6-9168-c8c48dfdb10a.png">

This appears to only be an issue if the cloned page ('Page 2 Copy' in this case) exists at the same node level it's ancestor ('Page 2'). To see this, try the following:

7) Delete 'Page 2' and 'Page 2 Copy' from Section 3 (just to get an empty section).

8) Using the 'Move page' command, move 'Page 2 Copy' from Section 1 to Section 2.

9) Copy 'Page 2' from Section 1 to Section 3 (repeating step #6).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Sulu correctly copies only 'Page 2' to Section 3.

10) Now delete 'Page 2' from Section 3 (the page you just added).

11) Move 'Page 2 Copy' from Section 2 back to Section 1.

12) Copy 'Page 2' from Section 1 to Section 3 (repeating step #6 yet again).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Sulu <b>incorrectly</b> copies both 'Page 2' and 'Page 2 Copy' to Section 3

So it would appear that is only an issue when clones share the same parent node as the page they were cloned from.

Btw.. if you create additional copies of 'Page 2' (within Section 1) and again copy 'Page 2' to Section 3, all of the clones are copied (along with 'Page 2') to the new section.

**Comment by wachterjohannes** [comment]
@cdesign thanks for report this issue. i have investigated this issue today and found the problem in the implementation of `jackalope-doctrine-dbal`.

there is a bug in the line (https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L622)

```php
$query = 'SELECT * FROM phpcr_nodes WHERE path LIKE ? AND workspace_name = ?';
$stmt = $this->getConnection()->executeQuery($query, array($srcAbsPath . '%', $srcWorkspace));
```

where the nodes for the source path will be found. as you can see the LIKE is used to find also the child-nodes. but in scenario you have described the `Page 2 copy` node has the path `/section-1/page-2-1` which will also be found with this statement.

i will try to fix this query there and post the PR here.

**Comment by wachterjohannes** [comment]
the linked PR will fix this issue. i hope it will be released soon.

**Comment by wachterjohannes** [comment]
@cdesign you can update the `jackalope/jackalope-doctrine-dbal` library to 1.2.8 to fix this issue. we will also include this version in the next HOTFIX release.

**Comment by cdesign** [comment]
Awesome! Thx much. And this did solve the problem in my app.
