### ISSUE TITLE
Header bar disappears after pressing backspace in snippet

### ISSUE THREAD

**Issue by RaphaelHofer** [sulu/sulu#2457]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.1
| Browser Version | Google Chrome Version 51.0.2704.84 (64-bit)

#### Actual Behavior

header bar disappears

#### Expected Behavior

header bar is visible

#### Steps to Reproduce

1. create a snippet
2. press backspace until you are in the snippet overview (native browser - site back)
3. no header bar

**Comment by danrot** [comment]
Are you talking about this blue header bar here:
![image](https://cloud.githubusercontent.com/assets/405874/16555634/f0be4a20-41d5-11e6-84af-646f4ece4f11.png)

Because this one does not disappear when I follow your steps.
