### ISSUE TITLE
Image formats xml with no formats errors 

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2458]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.3 |
#### Actual Behavior

When you create an image-format.xml it will fail when it doesnt contain any formats.
#### Expected Behavior

Allow `formats` tag to be empty
#### Steps to Reproduce

Create the following xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<formats xmlns="http://schemas.sulu.io/media/formats"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/media/formats http://schemas.sulu.io/media/formats-1.0.xsd">
    <!-- Please add your formats here  -->
</formats>
```
#### Possible Solutions

Allow `formats` to be empty.

**Comment by danrot** [comment]
This has been fixed, there is already an [empty image-formats.xml file in sulu/skeleton](https://github.com/sulu/skeleton/blob/master/config/image-formats.xml).
