### ISSUE TITLE
sulu under subfolder, admin assets and url not generated correctly

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2462]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.2 |
#### Actual Behavior

[https://github.com/sulu/sulu/blame/develop/src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.twig](https://github.com/sulu/sulu/blame/develop/src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.twig)
,
https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/AdminBundle/Resources/public/js/login.js
and
https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/AdminBundle/Resources/public/js/login.js

These files has the asset paths or urls just written as is, this means that if I move the installation to a subfolder this breaks and doesn't show the right url.

These are the urls and assets I have came across so far I don't know if there might be some others, I am trying to override the templates that don't assign the asset path automatically.
#### Expected Behavior

Every url should be displayed to point to the right location.
#### Steps to Reproduce

Try to load sulu from any sub folder in a domain (http://domain.any/test/public_html/) being public_html the web folder.

I understand this is an unsafe practice specially if the app folder is visible but with a few tweaks the app folder could be loaded from outside the docroot, and it can install the assets and assetic dumps in any directory pointed as the web folder.
#### Possible Solutions

Possibly the twig templates should use {{ asset() }} and the .js files could load the routes in some other way, which I have no knowledge of.

**Comment by piratadelfuturo** [comment]
After editting a couple of twig templates and js it started to seem better, the twig templates can use the asset() function in twig but for the js files I think those paths need to be insterted in a better way, which I still don't know.




 

![sulu_screenshot](https://cloud.githubusercontent.com/assets/466499/15919009/bb0ced9e-2dd2-11e6-9249-f844fb10ae4f.jpg)

**Comment by danrot** [comment]
As you've already said on your own, we don't really recommend to run Sulu like this... So we won't put too much energy into this. But you could create a PR with your changes, so that we can see what you've been doing there.

**Comment by danrot** [comment]
Apart from not recommending Sulu like this, the path can now be configured using different configuration options, so I am going to close this one.
