### ISSUE TITLE
Normalize 'Asset' terminology

### ISSUE THREAD

**Issue by cdesign** [sulu/sulu#2471]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.2 |

Sulu refers to 'Assets' in three different ways:

In the sidebar area is labeled 'Assets', but when you navigate there, the page is titled 'All media' (until you choose a collection). In the Person and Organization entry forms, the tab that lets you associate Assets with the Person or Org is labelled 'Documents'.

 It would be nice to normalize this to avoid confusion.

**Comment by danrot** [comment]
@berndhep What do you think about that?

**Comment by berndhep** [comment]
@danrot Yes, we should harmonize this throughout the whole system.

**Comment by danrot** [comment]
@berndhep So it should be "Assets" everywhere?

**Comment by danrot** [comment]
Discussed with @berndhep, we should rename everything to "Media".

**Comment by danrot** [comment]
We've renamed that :-)
