### ISSUE TITLE
Menu dont open when click on snippet

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2472]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

When you click on snippet the menu keeps to be small.

#### Expected Behavior

The menu should also open to see the title of the menu not only the icon.

#### Steps to Reproduce

Click on snippet menu icon.

**Comment by danrot** [comment]
Not sure about that, what is if you want to switch between media and snippets? Then it is IMO nice that the navigation stays small... Maybe @berndhep should add his opinion on this.

**Comment by alexander-schranz** [comment]
spoke with @berndhep. we will keep this behaviour when a subnavigation have no subentries the menu stay small.
