### ISSUE TITLE
Conflict in husky.min.js

### ISSUE THREAD

**Issue by papablack** [sulu/sulu#2475]
| Bug? | yes
| Sulu Version | 354f50d4727e8fbff25fabe44bb8c56be82e5172
https://raw.githubusercontent.com/sulu/sulu/develop/src/Sulu/Bundle/AdminBundle/Resources/public/js/vendor/husky/husky.min.js

This file has unsolved GIT conflict and it fucked up the admin on my prod environment apparently :/. Dev seems to work.

**Comment by wachterjohannes** [comment]
@papablack thanks for reporting this issue. i have fixed it directly in develop.

**Comment by wachterjohannes** [comment]
i needed a second commit (: for complete documentation https://github.com/sulu/sulu/commit/02cd5241cc3a2a5aec3ef2cb6ba9599fed7c6e28

**Comment by papablack** [comment]
This CMS will eat the market with support like that ;)

**Comment by wachterjohannes** [comment]
@papablack would do you have a slack account. there you can reach us quite fast and directly. you can request one on our website http://sulu.io/en#questions
