### ISSUE TITLE
Data sent in permission tab of e.g. pages gets very big if many roles are in the system

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#2477]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.2 |
| Browser Version | any |
#### Actual Behavior

If there are more than ~ 140 roles, it doesn't work to change all of them because there's a limit in the `php.ini` file `max_input_vars`.

The request is simply too large, which truncates the data and only saves the permissions correctly for the first ~ 140 roles.
#### Expected Behavior

The permissions should be saved for all roles.
#### Steps to Reproduce

Access project with ~ 160 roles and change the permissions for one of the last roles on a page.
#### Possible Solutions

The request data which is sent should be reduced - maybe only send the data for the changed roles?

**Comment by alexander-schranz** [comment]
The `max_input_vars` is a limit for the `$_POST` and other variables. We can here not do anything if an array would be get bigger. For the `roles` in the `admin` UI this should not longer exist as we are sending the `roles` now as `json` content so it should have no inpect on the `max_input_vars` configuraition in php.
