### ISSUE TITLE
Allow certain modifications in the content tree

### ISSUE THREAD

**Issue by nicodmf** [sulu/sulu#2487]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | Specific version or SHA of a commit |
| Browser Version | Browser name and version |
#### Actual Behavior

The content are displayed in a fashion tree way and are editable only on open
#### Expected Behavior

Permit to publish and view a little preview on the tree

**Comment by danrot** [comment]
@berndhep What do you think?

**Comment by nicodmf** [comment]
I think to a popup which permit to change title, categories and other little part of an article directly on the content tree.

**Comment by berndhep** [comment]
@danrot @chirimoya We'll discuss this in the next weekly.

**Comment by danrot** [comment]
I think it makes sense to see what you are publishing first... Therefore I will close this issue, also because this feature has not been requested anymore.
