### ISSUE TITLE
Incorrect route generated by 'single_internal_link'

### ISSUE THREAD

**Issue by cdesign** [sulu/sulu#2488]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.3

#### Actual Behavior

When assigning a page to a 'single_internal_link' content type, Sulu does not always create the correct route. Sulu also does not correctly update the link path when the original page URL is changed.

#### Steps to Reproduce

1) Use default Sulu install

2) Add the following content type definition to the 'default.xml' template:

```
<property name="page_link" type="single_internal_link">
	<meta>
		<title lang="en">Page Link</title>
	</meta>
</property>
```

3) Add a default page called 'Test & Page'. The resource locator should be:

> /test-and-page

<img width="348" alt="01 create page with and in route" src="https://cloud.githubusercontent.com/assets/5658799/16180376/fa17d610-3648-11e6-8e3e-914b00f793c6.png">

4) Add a second default page and assign 'Test & Page' as the 'Page Link' (using the 'single_internal_link'). The URL is incorrect: the '-and-' has been removed:

<img width="454" alt="02 incorrect route in single_internal_link" src="https://cloud.githubusercontent.com/assets/5658799/16180377/fffad0d2-3648-11e6-8242-669b8906be91.png">

Here is an additional issue that is probably related:

1) Add a default page and name it simply 'Test Page'. The route should be:

> /test-page

2) Add a second page named 'Test Page 2' and assign 'Test Page' as the 'Page Link' (using the 'single_internal_link'). The URL should be correct. Save and go  back.

3) Edit the original 'Test Page' and change the URL to '/test-test-page' and Save.

<img width="381" alt="screen shot 2016-06-19 at 8 49 10 pm" src="https://cloud.githubusercontent.com/assets/5658799/16181364/eec694ba-365f-11e6-8e02-c33bff91c2d2.png">

4) Now go back to 'Test Page 2' and look at the 'Page Link' URL. It has not updated.

<img width="353" alt="screen shot 2016-06-19 at 8 49 35 pm" src="https://cloud.githubusercontent.com/assets/5658799/16181872/cfbca57c-3665-11e6-9e70-9b27d385f06c.png">

**Comment by wachterjohannes** [comment]
@cdesign thanks for reporting. but this is not an "issue" it is a misunderstanding. the "path" which is displayed there is not the "url" it is the page-path (generated with the title). We should display the url there.

As the result you will receive the uuid in the twig and not the path.

**Comment by danrot** [comment]
@wachterjohannes Are we really showing the path here? Then this would be clearly a bug, since the path is only used internally, and never visible in the system.

**Comment by wachterjohannes** [comment]
@danrot yes we should change that.
