### ISSUE TITLE
Slow JavaScript Performance in category tree

### ISSUE THREAD

**Issue by Jace25** [sulu/sulu#2490]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.3

#### Actual Behavior

When using lots of categories the JacaScript has to select over all category items, no matter if their parent items are collapsed or not, because at the moment the category three is rendered as flat list, and the three layout is done with some (css) indents. This causes very bad performance when collapsing or expanding some item with lots of childs.

#### Expected Behavior

No matter how many entries there are, collapsing or expanding the tree should have more performance. 

#### Steps to Reproduce

Create lots of categories and subcategories (or use some import script) and then collapse and expand the category threes and subtrees.

#### Possible Solutions

Maybe it would be better to create some nested tables so all childs are inside of a nested table below its parent item
`<table>
    <tr>
        <td id="item1">Item1</td>
    </tr>
    <tr>
         <td id="item2">Item2
               <table id="item2-childs">
                   <tr><td>Item2Child1</td></tr>
             </table>
        </td>
    </tr>
</table>`

So the JavaScript doesnt have to select all items and toggle visibility, it only has to select `#item2-childs`.

**Comment by danrot** [comment]
This should have been improved a lot by https://github.com/sulu/sulu/pull/2912. This PR only loads the top level of the categories, and only fetch the children when the parent is opened. This way a lot less element are rendered.
