### ISSUE TITLE
Choose preview text of collapsed blocks

### ISSUE THREAD

**Issue by TschannettM** [sulu/sulu#2493]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | 1.2.2 |
#### Actual Behavior

When a block is collapsed the title or preview text of that block is selected by sulu on it's own.
#### Expected Behavior

It would be good if there could be a way to influence this selection process, so that you can select on your own which field should be used as preview text.
#### Steps to Reproduce

To reproduce this behavior, simply create a block and define the important input field (which should be the preview text) in the middle or bottom part of your block (there need to be more than one input field in the according block). After collapsing the block the value of the first input block is used.
#### Possible Solutions

A possible way to solve this, could be to introduce a new Tag value
 <tag name=„sulu.preview.prioritize„ value=„up"/> and <tag name=„sulu.preview.prioritize„ value=„down“/>. With this the sulu own logic could still apply, but it would be possible to up/down vote your input fields in the sequence.

**Comment by danrot** [comment]
We already had this tag, don't remember the exact name... But yeah, that would be a nice feature, we should add it again.

**Comment by danrot** [comment]
This has alreayd been implemented again.
