### ISSUE TITLE
Double click on media will show each collection twice

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2494]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.1 (demo.sulu.io)

#### Actual Behavior

If you accidentally double click on the media icon the collections are inserted twice. 

#### Expected Behavior

Only show a collection once.

#### Steps to Reproduce

Double click on the media icon.

![media_doubleclick](https://cloud.githubusercontent.com/assets/1698337/16222364/ef347410-3797-11e6-969e-7e36b1d2c1d9.gif)

#### Possible Solutions

Empty div container before set collection.

**Comment by danrot** [comment]
Emptying the div container is not a very good solution IMO... We would still do stuff twice, which is not necessary. We should try to avoid triggering the event a second time.

**Comment by danrot** [comment]
Fixed by https://github.com/sulu/sulu/pull/2580
