### ISSUE TITLE
Add an authored field on each Sulu page

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#2499]
| New Feature? | yes
#### Actual Behavior

At the moment it is no standard to set a creation date, publishing date or processing date on a sulu webpage. In case of an website relaunch, often you need to migrate sites from an other system to a sulu website. To sort pages by smart content it would be helpful to sort pages by a date (creation, publishing or what else) 

Cases: Press releases, News, Events...
#### Expected Behavior

Set  a specific date for a page (editable date)
Sort pages by smart content > by date

**Comment by danrot** [comment]
Instead of editing the existing fields being set by the system we'd like to add an authored field, which can be set in the UI.
