### ISSUE TITLE
Request not passed in preview to controller action

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2501]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2 |
#### Actual Behavior

The website preview brakes if I rendered a custom action from a custom controller if I set the request to be passed as parameter, while in the Website context works fine.
#### Expected Behavior

Preview and Website should work similarly.
#### Steps to Reproduce

Create a custom controller and set Request as last parameter, usually the request should be passed, this is a symfony spec.

**Comment by wachterjohannes** [comment]
For preview we dont use the "normal" routing way of symfony this is a big problem of compatability with symfony 3. you have to use `$this->getRequest()` in the controller to be sure that the preview is working correctly.

**Comment by danrot** [comment]
@wachterjohannes Should be fixable before 2.0, right?

**Comment by wachterjohannes** [comment]
could be quite had but i think changing to the RouteDefaults should do it.

**Comment by danrot** [comment]
Since we are using a fake request since quite some time, I think this should be solved.
