### ISSUE TITLE
CKEditor anchor button

### ISSUE THREAD

**Issue by Jace25** [sulu/sulu#2502]
| Q | A |
| --- | --- |
| Bug? | maybe |
| New Feature? | maybe |
| Sulu Version | Sulu-Minimal |
#### Actual Behavior

The default link plugin from ckeditor should have some build in anchor functions. It seems that this functions are disabled or removed, so currently it is not possbile to set an anchor inside the text.
#### Expected Behavior

It should be possible to use the default link plugin as expected.
#### Steps to Reproduce

Create some template with a text_editor type property and set the link plugin to true:
`<param name="link" value="true"/>`
The Linkplugin is enabled (you should see some link buttons in the toolbar) but it is not possible to create an anchor with this buttons.

**Comment by wachterjohannes** [comment]
The link to the original discussion https://sulu-io.slack.com/archives/general/p1466688809000531

**Comment by Jace25** [comment]
I think the discussion starts here: https://sulu-io.slack.com/archives/general/p1466758003000638

**Comment by danrot** [comment]
@Jace25 Can you describe in more detail which functionality you are missing?

**Comment by Jace25** [comment]
The basic CKEditor has some Anchor Plugin. Here you can define some Anchors to link (http://docs.cksource.com/CKEditor_3.x/Users_Guide/Rich_Text/Links#Anchors).

We have reenabled this plugin inside of our own Bundle with
```
            // reenable Anchor element
            app.sandbox.ckeditor.addToolbarButton('links', 'Anchor');
            CKEDITOR.on( 'dialogDefinition', function( ev )
            {
                // Take the dialog name and its definition from the event
                // data.
                var dialogName = ev.data.name;
                // Check if the definition is from the dialog we're
                // interested on (the "Link" dialog).
                if (dialogName == 'link')
                {
                    // stop the event propagation, so that sulu won't remove the anchor link type
                    ev.stop();
                }
            });
```

**Comment by danrot** [comment]
Since we are using a newer version of the CKEditor now, this does not apply anymore. In case you want to make use of the new Link Plugin in Sulu 2.0 there is [some documentation for that](https://docs.sulu.io/en/2.0/cookbook/link-provider.html).
