### ISSUE TITLE
Restructure template xsd files

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2510]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | <=1.6 |
| Browser Version | none |

#### Description

The current xsd file for the templates are monolitic and should be splitted in several files by using `ximport` and namespaces. The discussion which leads into this issue has started in the PR https://github.com/sulu/sulu/pull/2482#issuecomment-229027821

**Comment by danrot** [comment]
Since we are talking more and more about using Symfony configuration, I think we won't touch this issue anymore.
