### ISSUE TITLE
sulu:build wipes assets

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2521]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

When a sulu:build dev or prod runs it wipes the assets when installing the systems collections

#### Expected Behavior

Don't wipe the assets records pls

#### Steps to Reproduce

Upload a lot of images and the run any sulu:build dev or prod command.

**Comment by danrot** [comment]
This should probably be even distributed as a hotfix...

**Comment by marcelmoosbrugger** [comment]
@danrot Isn't this issue already fixed?

**Comment by danrot** [comment]
@wachterjohannes You are totally right :)
