### ISSUE TITLE
Missing asset description after adding a new asset to a contact or organisation

### ISSUE THREAD

**Issue by christianbader** [sulu/sulu#2529]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-master
| Browser Version | Tested in Chrome and Firefox

#### Actual Behavior

See title.

#### Expected Behavior

I would like to see the appropriate asset description immediately after adding an asset to a contact or to a organisation.

#### Steps to Reproduce

-> Contacts -> People or Organisations (Detail view) -> Documents -> Add document and close dialog
Right after this action no description is available.
After a page reload or resort of the table the description is available.

**Comment by danrot** [comment]
Fixed by #2550
