### ISSUE TITLE
Block type with the name "form" is displayed incorrectly

### ISSUE THREAD

**Issue by cdesign** [sulu/sulu#2549]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.5 |
#### Actual Behavior

The 'single_select' content type is not displayed correctly in a Block,:

![single_select_in_block](https://cloud.githubusercontent.com/assets/5658799/16619650/a04df7ea-4354-11e6-9f1f-27e9fad8135c.png)

Here is the template I tested with:

[default.xml.zip](https://github.com/sulu/sulu/files/349869/default.xml.zip)

**Comment by alexander-schranz** [comment]
This issue happens only on 1.6 when its block `type` `name` is `form` so it doesn't really has something todo with the single_select

**Comment by danrot** [comment]
And it is fixed in Sulu 2.0, so I am going to close this one.
