### ISSUE TITLE
Remove PhpcrTestCase|DatabaseTestCase

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#255]
Deprecate the `PHPCRTestCase` and `DatabaseTestCase` classes and use the CMF testing component.

The idea is that you always functionally test within the context of an application.

- Lots of code is abstracted into the test bundle (not much bootstrapping)
- *Fast* fixture loading for the ORM using DoctrineFixtures
- Built in support for PHPCR
- Access to the test console.

**Comment by danrot** [comment]
These classes have already been removed, so I am closing this issue.
