### ISSUE TITLE
pages by webspace or theme

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2552]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
#### Actual Behavior

I see all the page definitions in the menu when I edit a content page, even some pages are made specifically for one kind of webspace or theme.
#### Possible Solutions

Maybe in the webspace it could be possible to define not only the default theme templates but also the available ones, so the pages and templates used only for one theme or webspace will be the only ones available to avoid loading templates with the wrong content type.

**Comment by danrot** [comment]
Currently this is solved by not implementing the template in the theme of your webspace. But I can see that this is problematic if you are using multiple webspaces with the same theme... I would personally go for a list (maybe both, white and blacklist) in the webspace config, since it is less hidden. The automatic detection to check if the template is implemented in the theme has also already confused some users...

@chirimoya WDYT?

**Comment by chirimoya** [comment]
I think the best solution would be a white and blacklist within the webspace configuration.

**Comment by ampaze** [comment]
Having the same problem. Two Webspaces that both show all templates. Not having the corresponding twig-template in the theme does not hide the template in the admin interface for me.

Wouldn't a folder named after the webspace inside the pages folder be a far simpler solution than white and blacklists?

**Comment by danrot** [comment]
@ampaze That would also be an interesting approach... The question is how often are multiple webspaces sharing templates... But if we separate the templates by webspace I would move the template configuration into the webspace folder, along with the webspace configuration file.

**Comment by ampaze** [comment]
@danrot If webspaces need to share templates, these templates could still be directly in the pages folder. This would work either way, with subfolders or if templates moved to webspace folder.

**Comment by danrot** [comment]
For now we have implemented the `excluded-templates` section of the webspace in #4861. So I consider this issue solved.
