### ISSUE TITLE
Category cant open children when click on sort by name

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2553]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2

#### Actual Behavior

Category (or any other dategrid tree) cant open children when click on sort by name

#### Expected Behavior

Should able to open children without double click when categories are sorted by a specific field.

**Comment by danrot** [comment]
When the items in the list are collapsed, and the list is sorted after the name, the list is expanded, but the arrow shows in the wrong direction:
![image](https://cloud.githubusercontent.com/assets/405874/16762187/b5c4b220-4823-11e6-971c-fd5caebb8ff1.png)

**Comment by danrot** [comment]
Sorting by name does not work anymore, but sorting by Key is still possible, and the datagrid is working as it should then, so I am closing this issue.
