### ISSUE TITLE
Can't change type of block if minOccurs and maxOccurs is set to 1

### ISSUE THREAD

**Issue by RaphaelHofer** [sulu/sulu#2560]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.3 |
| Browser Version | Chrome Version 51.0.2704.103 (64-bit) / Firefox 47.0 |
#### Actual Behavior

Dropdown disappears after selecting an other block type in a block type selection if minOccurs and maxOccurs of blocks is set to 1. Type doesn't change either.
#### Expected Behavior

Changing the block type to the selected one.
#### Steps to Reproduce
1. Create a block type selection in a template with minOccurs and maxOccurs set to 1.
2. Change the type of the block.

**Comment by danrot** [comment]
This bug doesn't appear anymore in 1.4.6
