### ISSUE TITLE
WebsiteBundle::ExceptionController loads default theme instead requested webspace theme

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2563]
| Q | A |
| --- | --- |
| Bug? | ye |
| New Feature? | no |
| Sulu Version | 1.2 |
#### Actual Behavior

If I have 2 webspaces under a same domain but under diff paths, when I go to a not found 404 page the ExceptionController will load the default activeTheme.
#### Expected Behavior

Maybe somewhere in the controller of in another service call the activeTheme should be assigned from the Webspace set on the Request.

**Comment by piratadelfuturo** [comment]
So far I just override the Exception controller with one that gets the Liip ActiveTheme class injected, but i am not sure this is the best approach:

`class ExceptionController extends BaseController{

    
    protected $requestAnalyzer;
    
    protected $parameterResolver;
    
    protected $activeTheme;
    
        public function __construct(
        \Twig_Environment $twig,
        $debug,
        ParameterResolverInterface $parameterResolver,
        RequestAnalyzerInterface $requestAnalyzer = null,
        ActiveTheme $activeTheme
    ) {
        $this->requestAnalyzer = $requestAnalyzer;
        $this->parameterResolver = $parameterResolver;
        $this->activeTheme = $activeTheme;
        parent::__construct($twig, $debug, $this->parameterResolver, $this->requestAnalyzer);

    }
    
    
    public function showAction(
        Request $request,
        FlattenException $exception,
        DebugLoggerInterface $logger = null            
    ) {
        
        if ($webspace = $this->requestAnalyzer->getWebspace()) {
            $this->activeTheme->setName($webspace->getTheme()->getKey());
        }
        
        return parent::showAction($request,$exception,$logger);
    }
    
}`

**Comment by danrot** [comment]
This doesn't happen to me on latest develop. Can you maybe check if the problem would also be solved there for you?

**Comment by danrot** [comment]
Closing due to the lack of activity.
