### ISSUE TITLE
"default-type" in block content-type not validated

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2566]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Enhancement? | yes |
| Sulu Version | all |
| Browser Version | - |
#### Actual Behavior

When defining a template, the block content type can be used, in which various block-types are defined. In the "default-type" attribute of the block, an existing block type has to be referenced. The type of the attribute however is just a simple string. When giving a string which does not correspond to an existing block type, neither Sulu nor some XSD warns about the usage. The template is accepted, but Sulu fails when opening a page which tries to use the template.
#### Expected Behavior

When the "default-type" contains a string which does not correspond to an existing block-type, either an XSD file or Sulu show notify the creator about the issue.
#### Steps to Reproduce

Create a template with a block-content type, in the "default-type" write a string which is not the name of an existing block type. Try to use the existing template in Sulu.
#### Possible Solutions

Make the names of the block-types a key and the "default-type" a key-reference in an XSD file.

**Comment by wachterjohannes** [comment]
another possible solution is to ignore a not existing default-type, use the first block-type and write a warning into the log.

**Comment by danrot** [comment]
Fixed in #4831
