### ISSUE TITLE
Provided directory "/var/data/websites/mysebsite/app/cache/website/prod/sulu/documents" does not exist

### ISSUE THREAD

**Issue by christianbader** [sulu/sulu#2567]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | dev-develop |
| Browser Version | - |
#### Actual Behavior

PHP message: PHP Fatal error:  Uncaught ProxyManager\Exception\InvalidProxyDirectoryException: Provided directory "/var/data/websites/mysebsite/app/cache/website/prod/sulu/documents" does not exist in /var/data/websites/mywebsite/vendor/ocramius/proxy-manager/src/ProxyManager/Exception/InvalidProxyDirectoryException.php:38
#### Expected Behavior

The documents directory should exist after cache setup
#### Steps to Reproduce

rm -rf app/cache/*
rm -rf app/logs/*
HTTPDUSER=`ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX app/cache app/logs uploads uploads/\* web/uploads web/uploads/\* app/data
sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX app/cache app/logs uploads uploads/\* web/uploads web/uploads/\* app/data

**Comment by alexander-schranz** [comment]
fixed #3369
