### ISSUE TITLE
No hreflangs are generated on startpages

### ISSUE THREAD

**Issue by tobias47n9e** [sulu/sulu#2568]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 79cc05811197813845d1cf3a36b3c445707ed73a
| Browser Version | All

#### Actual Behavior

On the startpage no hreflangs (e.g. `<link rel="alternate" href="http://example.domain.at/de" hreflang="de"/>`) are generated by the seo-extension.

#### Expected Behavior

Similar to the other pages one would expect an output like this:

````
<link rel="alternate" href="http://example.domain.at/de" hreflang="x-default"/>
<link rel="alternate" href="http://example.domain.at/de" hreflang="de"/>
<link rel="alternate" href="http://example.domain.at/en" hreflang="en"/>
````

#### Steps to Reproduce

Call the seo-extension on a startpage and on a content-page.

**Comment by danrot** [comment]
That should have been fixed with https://github.com/sulu/sulu/pull/2362, probably an update should be enough.

**Comment by tobias47n9e** [comment]
Thanks!
