### ISSUE TITLE
Include DocumentManager into this repository

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2571]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | --- |
| Browser Version | --- |
#### Actual Behavior

Currently the Sulu DocumentManager has its own Repo: https://github.com/sulu/sulu-document-manager
#### Expected Behavior

The DocumentManager should be in this repository, because of a better developer experience.

Also consider the discussion at https://github.com/sulu/sulu/pull/2361#discussion_r69294439 when doing this. It's saying that we should integrate some functionality like the line where this discussion started should be integrated in the `NodeHelper` of the sulu-document-manager repository.

**Comment by alexander-schranz** [comment]
This was done with sulu 2.0
