### ISSUE TITLE
priority has no effect on sulu.rlp.part

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2587]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.1 |
| Browser Version | - |
#### Actual Behavior

When using multiple sulu.rlp.parts in a template, defining priorities has no effect.
#### Expected Behavior

When using multiple sulu.rlp.parts, it should be possible to define in which order the different parts occur in the resulting resource locator.
#### Steps to Reproduce

Use a template which contains more at least two sulu.rlp parts, like e.g.:

```
<property name="title" type="text_line" mandatory="true">
     <meta>
           <title lang="de">Titel</title>
            <title lang="en">Title</title>
     </meta>
     <params>
            <param name="headline" value="true"/>
      </params>

      <tag name="sulu.rlp.part" priority="1"/>
</property>
<property name="sub_title" type="text_line">
    <meta>
        <title lang="de">Subtitle</title>
        <title lang="en">Subtitle</title>
    </meta>
    ​
    <tag name="sulu.rlp.part" priority="2"/>
</property>
```

Next, create a new page using the newly defined template. Fill out all the properties marked as "sulu.rlp.part".

**Comment by danrot** [comment]
This has been fixed in Sulu 2.0.
