### ISSUE TITLE
Preview not work errors with ini_set session module 

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2591]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | `dev-develop 13.07.2016 ( 1d2b53f9d5240a8c14b3ff52e590b602f1fc0903 )`
| PHP | 7.0.2 (brew)

#### Actual Behavior

Preview not working.

![bildschirmfoto 2016-07-13 um 18 48 03](https://cloud.githubusercontent.com/assets/1698337/16811844/92fec728-492a-11e6-8117-a75ac7150638.png)

#### Expected Behavior

Preview should work.

**Comment by wachterjohannes** [comment]
this seems to be fixed byhttps://github.com/sulu/sulu/commit/14d724e4b5896b494b5b341253bfef067fbbe65a
