### ISSUE TITLE
Preview errors on production environment web_profiler not found

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2592]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | `dev-develop 13.07.2016 ( 1d2b53f9d5240a8c14b3ff52e590b602f1fc0903 )`
| PHP | 7.0.2 (brew)

#### Actual Behavior

unexpteced config `web_profiler`

#### Expected Behavior

Preview should work.

#### Steps to Reproduce

Turn environment to prod or stage visit a page in the backend.

#### Possible Solutions

Load configs based on environment.

**Comment by wachterjohannes** [comment]
this seems to be fixed by https://github.com/sulu/sulu/commit/554c5d8b238b36beddd3a526ce4b9b730f6864b2 /cc @danrot please reopen if i am wrong.
