### ISSUE TITLE
search for image returns fixed 170x170 format

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2597]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.2.1 |
| Browser Version | - |
#### Actual Behavior

When searching for an image, for all found images just the link to the 170x170 thumbnail gets returned. Moreover the 170x170 image format is just needed for this purpose.
#### Expected Behavior

There are various choices for the expected behavior. One possibility would be to provide links to all various formats of found images, as well as a link to the original image. Furthermore the 170x170 image format could be removed.
#### Steps to Reproduce

Search for an existing image.
#### Possible Solutions

see expected behavior.

**Comment by alexander-schranz** [comment]
it would be possible to just save one format with placeholder `/uploads/media/%format%/01/1-9K1B8452.jpg?v=1` and then generate the thumbnails array  with all formats.

```
$thumbnails = [];
foreach ($this->formats as $format) {
    $thumbnails[format] = str_replace(format, '%format%', $url);
}

return $thumbnails;
```

**Comment by danrot** [comment]
Actually it would be nice to do what @alexander-schranz described here, but we should use the `UrlGenerator` from Symfony for that.

**Comment by danrot** [comment]
#802 covers somethign similar, so I am gonna close this issue.
