### ISSUE TITLE
Roles can't be deleted in the list

### ISSUE THREAD

**Issue by marcelmoosbrugger** [sulu/sulu#2627]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.7
| Browser Version | all

#### Actual Behavior

When selecting a role in the list and selecting delete from the toolbar an overlay pops up. When trying to click ok, nothing happens and a JavaScript error occurs.

#### Expected Behavior

When selecting a role from the list and clicking delete it should be possible to really submit the deletion with a click on the ok button. Afterwards the role should not be visible anymore.

Moreover as a developer I expect the behat tests to fail, if this use case is not working.

#### Steps to Reproduce

Login -> Navigate to the roles -> Select a role from the list -> Click the delete button in the toolbar -> Click the ok button on the poped up overlay

**Comment by danrot** [comment]
Fixed in https://github.com/sulu/sulu/issues/2620
