### ISSUE TITLE
No  labels appear when saving roles

### ISSUE THREAD

**Issue by marcelmoosbrugger** [sulu/sulu#2628]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.7
| Browser Version | all

#### Actual Behavior

When changing and saving or creating a role. No labels appear which notify about the successful persistence of the role.

#### Expected Behavior

When changing or creating a role a success label should appear.

#### Steps to Reproduce

Change or create a role.

**Comment by danrot** [comment]
Fixed in https://github.com/sulu/sulu/issues/2620
