### ISSUE TITLE
Set edited permissions into Config instead of reloading

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2630]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Enhancement? | yes |
| Sulu Version | 1.2.7 |
| Browser Version | Browser name and version |
#### Actual Behavior

When editing and saving a role, a warning appears that the system has to be reloaded to make the changes take effect.
#### Expected Behavior

The changes made to a role should immediately take effect after a successful response from the server.
#### Steps to Reproduce

Edit and save a role.
#### Possible Solutions

Regarding the editing roles, other components, which require a certain amount of rights, ask the "Config" component from the admin bundle via its "get" method if certain rights exist. The "Config" component also defines a "set" method. Instead of reloading the page, the "set" method of the Config could be used to make the system know about the changed role.

Even better in my opinion, would be to write a frontend security-service in the SecurityBundle, which other components can turn to, to ask if certain rights exist or not and tell the service to change rights for a role.

Regarding the rights for the text-editor, the resulting toolbar (which is returned on the save request) can be set to the text-editor via "sandbox.ckeditor.setToolbar".

**Comment by danrot** [comment]
I think this is not worth implementing. Permissions are not changed very often, and it only applies if the user editing the permissions changes a role that affects himself. Apart from that the request to the servers will already be blocked anyway.
