### ISSUE TITLE
Too much complexity in the frontend of the ContentBundle

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2637]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Enhancement? | yes |
| Sulu Version | 1.2.7 |
| Browser Version | - |
#### Actual Behavior

The frontend component `content@sulucontent` contains a lot of functionality and currently has over 1000 lines of code. It e.g. defines both the header for the edit section as well as the header for the column-tree section. Which header to render is decided via if statements. Also the layout is defined for the column-tree section and the edit section.
#### Expected Behavior

The behavior and visualization of the column-tree and the edit should be seperated. Moreover general functionality like saving, deleting and creating of nodes should be encapsulated in frontend services which can be injected in the corresponding views.
#### Steps to Reproduce

Look at the source code of `content@sulucontent`.
#### Possible Solutions

Restructure the code in the ContentBundle and tab components which come from other bundles. The frontend structure which solves the issue can be cribbed from the ContactBundle.

**Comment by danrot** [comment]
Since this entrie code is gone, I'd argue it is safe to close this issue :wink:
