### ISSUE TITLE
Tab listens on toolbar events in CategoryBundle

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2638]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Enhancement? | no |
| Sulu Version | 1.2.7 |
| Browser Version | - |
#### Actual Behavior

In the CategoryBundle the `edit` component initializes the header for the edit. However the tabs are the components which listens on the events of the toolbar and call the CRUD operations. If other tabs are added to the edit of categories this leads to duplicated code.
#### Expected Behavior

The `edit` component (the one which initializes the header and the toolbar) should be the one listening on the events of the toolbar. Moreover the CRUD operations should be encapsulated in frontend services, which can be injected in the corresponding views.
#### Steps to Reproduce

Look at the source code of the `edit` component in the CategoryBundle and its `details` tab.
#### Possible Solutions

Restructure the code in the CategoryBundle. The frontend structure which solves the issue can be cribbed from the ContactBundle.

**Comment by danrot** [comment]
Since we already have rewritten the entire JS stack I think we can close this issue.
