### ISSUE TITLE
Server responds with code 500 when changing role name to an existing one

### ISSUE THREAD

**Issue by marcelmoosbrugger** [sulu/sulu#2641]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.7
| Browser Version | -

#### Actual Behavior

When changing the name of an already existing role to a name which is already taken by another role, the server responds with a 500 code.

#### Expected Behavior

The server should respond with a 400 code.

#### Steps to Reproduce

Make sure you have an existing role in your system. Now create a new role with new name. Next change the name of the role to a name already taken by another role. Try to save the changed role.

**Comment by danrot** [comment]
The correct error code would probably be `409 CONFLICT`
