### ISSUE TITLE
Bug when deleting in "show selected" mode

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2644]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.7 |
| Browser Version | - |
#### Actual Behavior

In every datagrid: When selecting some rows and then clicking "show selected" the not selected rows get hidden as expected. However when clicking on the "delete" button in the toolbar and deleting the rows, the "show all" label above the datagrid vanishes. There is no possibility to display the rows which were hidden before the deletion.
#### Expected Behavior

Even after deleting some rows from the datagrid the "show all" label should still be there, if there are hidden rows.
#### Steps to Reproduce

The issue exists on all datagrids, but let's take the one in the CategoryBundle: Create three categories: "Cat A", "Cat B" and "Cat C". Now navigate to the category list. Select "Cat A", "Cat B" and click on the "show selected" label. Next - in the toolbar - click the delete button. The two selected categories should get deleted as expected. However there is no option to re-display the non selected and non deleted "Cat C".

**Comment by danrot** [comment]
Since we already have rewritten the entire JS stack I think we can close this issue.
