### ISSUE TITLE
Sulu navigates to contacts undesirably when clicked on navigation

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2647]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.7 |
| Browser Version | Browser name and version |
#### Actual Behavior

When on a window with a collapsed navigation and the system languages wants to be changed, its intuitive to click on the bottom section of the navigation, as the dropdown is situated there. However when clicking Sulu navigates to the contacts section, even if I have unsaved changes.
#### Expected Behavior

Sulu should not navigate to the contacts section, or at least warn me that my changes get lost.
#### Steps to Reproduce

![screen](https://cloud.githubusercontent.com/assets/1998663/17012577/dbc4e318-4f18-11e6-9b68-986b09600d45.gif)
#### Possible Solutions

I think there is an click listener in the toolbar which work perfectly when the navigation is expanded but has the undesired behavior described above when in collapsed state.

**Comment by danrot** [comment]
Since we already have rewritten the entire JS stack I think we can close this issue.
