### ISSUE TITLE
Lot of !importants in single-media-selection.scss

### ISSUE THREAD

**Issue by marcelmoosbrugger** [sulu/sulu#2650]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 17de020a5b4958dcd84f2812f9a280107acbf422
| Browser Version | -

#### Actual Behavior

The "single-media-selection.scss" contains a lot of "!important"s. This is quite confusing, as "!important" is not very common in our style files. Moreover the using "!important" makes the reuse of the affected files more difficult.

#### Expected Behavior

There should not be any "!important"s in the named file.

#### Possible Solutions

The application of the styles noted with "!important" should be enforced with the use of classes.

**Comment by nnatter** [comment]
same thing holds for "column-navigation-overlay.scss".

**Comment by danrot** [comment]
@nnatter I hope you fix this, and your previous comment is not correct anymore 😉

**Comment by nnatter** [comment]
@danrot will fix this in an additional pr :)
