### ISSUE TITLE
Old willdurand/hateoas-bundle dependencies 

### ISSUE THREAD

**Issue by markuszillig** [sulu/sulu#2651]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.2.7 |
| Browser Version |  |
#### Actual Behavior

composer.json require: willdurand/hateoas-bundle:0.3.*
#### Expected Behavior

composer.json require: willdurand/hateoas-bundle: ^1.1
#### Steps to Reproduce

![sulu](https://cloud.githubusercontent.com/assets/16701843/17024996/3fd100bc-4f5a-11e6-9df9-1fd5d3a79479.png)
#### Possible Solutions

Update willdurand/hateoas-bundle dependencies

**Comment by wachterjohannes** [comment]
@danrot can we update that for 1.3?

**Comment by danrot** [comment]
We can try, don't know if it is breaking anything.
