### ISSUE TITLE
Block components not started automatically when use outside content bundle

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2652]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | dev-develop (20-06-2016) |
#### Actual Behavior

When you use a block in your own bundle with a component e.g. media selection. The component will not be started automatically when add a new block. Also the sorting of the blocks dont work.
#### Expected Behavior

The block should start the components by itself and make the blocks sortable. 
#### Steps to Reproduce

Create your own bundle and create a block with a component that need to be started (e.g. media selection, auto complete, ...).
#### Possible Solutions

Call `Husky.start($template);` here: https://github.com/sulu/sulu/blob/1.2.6/src/Sulu/Bundle/ContentBundle/Resources/public/js/validation/types/block.js#L417

In the content area the component is started but I think this should also be handled by the block so the block can be easier used in other bundles: 

https://github.com/sulu/sulu/blob/1.2.6/src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js#L305

The logic from the sorting should be moved to the block itself so also this works automatically.

**Comment by alexander-schranz** [comment]
This is what currently need to be implemented in every form which use a block and should be part of `block.js`:

```js
bindDomEvents: function() {
    this.initSortableBlock();
}, 

bindCustomEvents: function() {
    this.sandbox.dom.on(constants.formSelector, 'form-add', function(e, propertyName, data, index) {
        var $elements = this.sandbox.dom.children(this.$find('[data-mapper-property="' + propertyName + '"]')),
            $element = (index !== undefined && $elements.length > index) ? $elements[index] : this.sandbox.dom.last($elements);

        // start new subcomponents
        this.sandbox.start($element);

        // reinit sorting
        this.initSortableBlock();
    }.bind(this));

    this.sandbox.dom.on(constants.formSelector, 'init-sortable', function(e) {
        // reinit sorting
        this.initSortableBlock();
    }.bind(this));
},

initSortableBlock: function() {
    var $sortable = this.sandbox.dom.find('.sortable', this.$el),
        sortable;

    if (!!$sortable && $sortable.length > 0) {
        this.sandbox.dom.sortable($sortable, 'destroy');
        sortable = this.sandbox.dom.sortable($sortable, {
            handle: '.move',
            forcePlaceholderSize: true
        });

        // (un)bind event listener
        this.sandbox.dom.unbind(sortable, 'sortupdate');

        sortable.bind('sortupdate', function(event) {
            this.sandbox.emit('sulu.content.changed');
        }.bind(this));
    }
},
```

**Comment by danrot** [comment]
Since we already have rewritten the entire JS stack I think we can close this issue.
