### ISSUE TITLE
Media selection broken view and add of none images

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2654]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-develop

#### Actual Behavior

 - [x] None images could not be added (js error missing check if thumbnails exist)
 - [x] All medias are shown as selected images on first open 
 - [ ] Jumping of the list because the selected are shown above make the list unuseable

#### Steps to Reproduce

![mediaselection](https://cloud.githubusercontent.com/assets/1698337/17033060/93050662-4f7c-11e6-88b1-a4eff13bedfe.gif)

**Comment by danrot** [comment]
Point 1 and 2 were fixed in #2655
