### ISSUE TITLE
Video upload fails when FFProbe is not installed

### ISSUE THREAD

**Issue by marcelmoosbrugger** [sulu/sulu#2656]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.7
| Browser Version | -

#### Actual Behavior

When I upload a video in the assets section and FFProbe is not installed, the upload fails and I get a the message "maximum filesize" reached.

#### Expected Behavior

At least the error message should be more descriptive on whats going on. Even better would be if videos could still be uploaded.

#### Steps to Reproduce

Make sure FFProbe is not installed and upload a video in the assets section.

#### Possible Solutions

In the Backend check whether or not FFProbe is available and only use it if so.

**Comment by danrot** [comment]
That's a duplicate of #2422
