### ISSUE TITLE
"Maximum filesize reached" when uploading media with no extension.

### ISSUE THREAD

**Issue by marcelmoosbrugger** [sulu/sulu#2657]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.7
| Browser Version | -

#### Actual Behavior

When uploading a media with no file extension, I get the error message "maximum file size reached".

#### Expected Behavior

Either Sulu could determine the type of the file from the file itself and not from its name, or a more descriptive error message should be shown.

#### Steps to Reproduce

Upload an image with no file extension in the assets section.

**Comment by danrot** [comment]
Tried to reproduce that with a file created with the `touch` command, and can confirm that. Actually I thought we are using the mime type for detecting the file type 😕
