### ISSUE TITLE
Internal Links on not published content

### ISSUE THREAD

**Issue by Jace25** [sulu/sulu#2660]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 79df1b3

#### Actual Behavior

We are using the internal_link block-type for setting links to other pages. It is possible to set these links on not published objects, but it is not possible to remove this links until the linked object is published:
![image](https://cloud.githubusercontent.com/assets/4090694/17051854/0a418164-4ffb-11e6-99cc-375bdab9299c.png)
There is some "remove icon" missing.

#### Expected Behavior

It should be possible to remove unpublished internal links without publish and unpublish them.

#### Steps to Reproduce

Set an internal link to some unpublished content. Later (e.g. after publishing) try to remove it. The remove icon only gets visible if the linked object is published:
unpublished:
![image](https://cloud.githubusercontent.com/assets/4090694/17051854/0a418164-4ffb-11e6-99cc-375bdab9299c.png)

published:
![image](https://cloud.githubusercontent.com/assets/4090694/17052809/56d5411a-4fff-11e6-97fc-cb63d2d9d591.png)

#### Possible Solutions

Maybe it is possible to list the items without taking care of their state. You could display the state icon (yellow, green) to indicate the current state.

**Comment by wachterjohannes** [comment]
i am not absolutely sure but this could be "only" a display issue. I think we only have to display the page and show the bubble. the id should be saved in the database.

**Comment by wachterjohannes** [comment]
i have tried this and the id will be saved. this would be quite easy to fix. @danrot @marcelmoosbrugger should we add this to milestone 1.3?

**Comment by Jace25** [comment]
@wachterjohannes yes, sorry. I forgot to add this information. All ids will be saved. As you publish the linked object it appears in the selection. So it should be only a display issue.

Thx

**Comment by marcelmoosbrugger** [comment]
I am working an this right know. This is planed for Milestone 1.3
