### ISSUE TITLE
RlpStrategy should get renamed to ResourceLocatorStrategy

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#2662]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | dev-develop (2016-07-22)

#### Actual Behavior

The base class for dealing with resource-locators is currently called RlpStrategy. 
This class should get renamed to ResourceLocatorStrategy to avoid confusion. Also abbreviations are not used in other class names.

**Comment by danrot** [comment]
Fixed with https://github.com/sulu/sulu/pull/2740
