### ISSUE TITLE
Installation improvements with user and role

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2666]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.3.0-RC1 |
#### Actual Behavior

The `prod` task will not create any user or role.
#### Expected Behavior

As a user and a role is required to access Sulu. I would just call the commands on `prod` and he can create custom role and user then. The difference to the `dev` task is that he need to input all user and role data manually.

**Comment by danrot** [comment]
I think I would not do that, because this means that the task cannot run completely on its own, but awaits user input. That is not desirable especially in a CI/CD context. If somebody wants to create this user he has to call the `sulu:security:role:create` and `sulu:security:user:create` commands.

**Comment by alexander-schranz** [comment]
@danrot not aggree with it. On the CI we could run it with no-interaction so there could the userinput be skipped and then can the default password be used.
