### ISSUE TITLE
Unpublish action should be disabled if not possible

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#2667]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | dev-develop (2016-07-25)

#### Actual Behavior

The unpublish-action in the content bundle is always clickable, regardless of wether the displayed page is published or not.

#### Expected Behavior

The unpublish-action should be clickable only if the displayed page is published.
(Similar to the save button, which is only enabled if the page was modified)

#### Steps to Reproduce

1. Open the create-page form
2. Open the edit-dropdown in the header toolbar
-> The publish-action is enabled altough the page is not created

![](https://s32.postimg.org/51orddb9f/unpub1.png)

or

1. Open any page
2. Unpublish the page
3. Open the edit-dropdown in the header toolbar
-> The publish-action is enabled altough the page is already unpublished

![](https://s32.postimg.org/ijvnpnner/unpub2.png)

**Comment by nnatter** [comment]
Also the Homepage-page hast the option "Save as draft". 
When clicked, the state of the page in the toolbar does not change, but the dropdown-items of the save-dropdown look like the page is unpublished.

**Comment by danrot** [comment]
@nnatter For the homepage this is intended. Is there also no label saying that you are editing a draft? In general once the page is published the toolbar will always say it is published, until you unpublish it again. The toolbar only says if there is any version of this page online.
