### ISSUE TITLE
Error when deleting category parent and children in list

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2672]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | dev-develop (25-07-2016) |
#### Actual Behavior

When deleting multiple categories (parent with its children) from the category list, a javascript error is thrown.
#### Expected Behavior

The selected categories should be deleted and not be visible anymore.
#### Steps to Reproduce

Navigate to the category list. The list should contain at least on parent with a child category. Select the parent first and after that the child category. Now click on the delete button in the toolbar and confirm the popup. Now an error should occur and only the child category be left in the category list. After reloading the page also the child category is gone.
#### Possible Solutions

I think the problem is that that the parent gets deleted first (which also deletes the children). After that, although the child is already deleted, a DELETE request is sent to the server.

**Comment by danrot** [comment]
Since we already have rewritten the entire JS stack I think we can close this issue.
