### ISSUE TITLE
URLs are not generated for ghost pages

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2677]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | a04d255d5ab6ea203a9c92d08b47684257b4232a
| Browser Version | ---

#### Actual Behavior

Sulu does not generate URLs for ghost pages. This is especially bad if the ghost page is the child of another page, because the URL structure is broken then.

#### Expected Behavior

URLs should also be generated for ghost pages.

#### Steps to Reproduce

1. Create a page on the second level as a child of a published page
2. Change to a language on which the parent is also published
3. Enter a title
4. See that the URL is not generated (also the parent part is missing).

**Comment by nnatter** [comment]
looks like `this.inAddMode` is false, when creating a ghost page. 
https://github.com/sulu/sulu/pull/2588/files#diff-c124d8cf9d9f11172e744e9e64c33739R71
