### ISSUE TITLE
Default locale not available in permissions

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2688]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.0-RC1

#### Actual Behavior

When e.g. your kernel default locale is `en` and you only have a webspace with `es`. Unlocalized api request e.g. `/admin/api/contacts` will error because the user have no permissions for the default locale `en`. 

#### Expected Behavior

The kernel.locale should also be available in the permissions dropdown so the user can have permission for this unlocalized entities.

**Comment by danrot** [comment]
I think that should be fixed with https://github.com/sulu/sulu/pull/2676, can you check?

**Comment by alexander-schranz** [comment]
Ok know I did only have problems with my custom controller, but could fix it by remove the fallback locale and require that JS components send always the locale.

```
$request->get(
    'locale',
    $request->getLocale() // removed this so the locale is null when no locale is sent
);
```
