### ISSUE TITLE
Allow to choose location of parameter in routes

### ISSUE THREAD

**Issue by Yoann-TYT** [sulu/sulu#2694]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | Specific version or SHA of a commit |
| Browser Version | Browser name and version |
#### Actual Behavior

For the time, I have got a route that list my products. "/catalogs". I have got a paginator enabled on this route. "/catalogs/{page}".

I want to use it with sulu because I'm interested by SEO, I18n features, and editing area text.

Is it possible, or am i forced to pass my page parameter wihtout rewriting url ? "/catalogs?page=1".

Thanks you for your response ;-)

**Comment by wachterjohannes** [comment]
@Yoann-TYT currently this is not possible. you could "fake" it with some symfony routes. but then you cannot change the route anymore.

**Comment by Yoann-TYT** [comment]
@wachterjohannes Thank you for your response ;) I'll improvise ! :)

**Comment by wachterjohannes** [comment]
@Yoann-TYT no problem (: maybe we could take a look how this could be achieved @chirimoya @danrot ?

**Comment by Yoann-TYT** [comment]
That whould be great :)

**Comment by Yoann-TYT** [comment]
Hello Daniel !

I see that you have transform the ticket to enhancement :) Nice !
But, when I choosed the page parameter to explain my problem, it was just an example :) 

I named the ticket "Resource locator and complex route" because I thought of others problems like that : 

Suggest that we have a list of house room. The list is translated in english, french, german...
According the user's locale, I'am able to get the correct list ( english / french or german ).

I want a route to show objects available by rooms.
/house/{room}/objects

But if a french man navigate on the website, I want to give him a route like that : 
/maison/{piece}/objets

Perhaps my problem is too specific, and Sulu can't help me. And the solution is to build specific controller by culture... :)

Thank you for your patience ;)

Yoann

**Comment by danrot** [comment]
Ok, got it :-) Removed the page parameter again from the issue title. But I don't really get what you want to do then... Is the route we are talking about here showing to a Sulu site? Or is that some custom logic in your own application? If yes, how do you implement Symfony logic then?

**Comment by Yoann-TYT** [comment]
Hi @danrot,
Sorry, I didn't see the notification... :-/ 
Yep, the route we are talking about here showing to a Sulu site, but needs to contain some custom logic. To put it simply, it would be great if we could associate the awesome features of Sulu ( SEO, media managment, text editing ) with some custom logic.
For now, when you are confronted to this kind of problem, you have to define your own logic on a controller, and you need to manage CMS features like translations, seo, media, in a new tab on your back-office.
I hope that my explanations are a bit clearer :)

**Comment by danrot** [comment]
You know that you can change the controller with which a page is rendered in the XML? (see https://github.com/sulu/sulu-standard/blob/develop/app/Resources/pages/default.xml.dist#L9)

Does that help in what you are trying to achieve?
