### ISSUE TITLE
ContentRouteProvider could be simplified because of Publishing feature

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2698]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.3.0-RC1
| Browser Version | ---

#### Actual Behavior

Currently the `ContentRouteProvider` class is quite complicated, and still uses the `ContentMapper`.

#### Expected Behavior

The `ContentMapper` dependency could easily be removed and replaced by the `DocumentManager`. The `DocumentManager` can easily load only published pages, because the workspace on the website only contains published pages anyway. Therefore the published ifs can be removed.

**Comment by danrot** [comment]
@chirimoya We could get rid of the `ContentMapper` dependency in the `ContentRouteProvider` if we duplicate  [the content of the `documentToStructure` method](https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Content/Mapper/ContentMapper.php#L912).

The problem we would need to do that is that we are passing a `StructureBridge` to the route and not a document, and changing this would be a way too big BC break.

**Comment by wachterjohannes** [comment]
i have already an idea of using something like the RouteDefaultProvider. where we would have to register both the structure and the document as attribute. the developer could decide then what he want to use.

**Comment by danrot** [comment]
That sounds nice, but then we still have to duplicate these lines in order to get a `StructureBridge` for this route 😉

**Comment by wachterjohannes** [comment]
@danrot thats possible (:
