### ISSUE TITLE
CSS-Style of media-selection in content-blocks

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2700]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | a916995e20ad19c35a24f610189701e9657c59b0 (around RC2)
| Browser Version | Chrome Version 51.0.2704.106 (64-bit)

#### Actual Behavior

There seems tobe an issue with the style see screenshot:

![image](https://cloud.githubusercontent.com/assets/1464615/17239091/b7b0d230-5561-11e6-8624-a3c14b0021c0.png)

#### Possible Solutions

FIX it (:

**Comment by marcelmoosbrugger** [comment]
This issue was fixed by https://github.com/sulu/sulu/pull/2683
