### ISSUE TITLE
unpublishing does not adapt resource locators of child pages

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#2707]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-develop (01-08-2016)

#### Actual Behavior

- Create a unpublished page _parent_
- Create a published page _child_ as child of the page _parent_

-> The page _child_ is now assigned to the route "/child"

- Publish the page _parent_

-> The page _child_ is now assigned to the route "/parent/child"

- Unpublish the page _parent_

-> The page _child_ is still assigned to the route "/parent/child" instead of the correct route "/child"

#### Expected Behavior

The child page should be assigned to the same route after unpublishing, as it would be, if the parent page was never published.

**Comment by nnatter** [comment]
The `adaptResourceLocators`-method of the `RlpStrategy` should implement the functionality, which is needed to adapt the resource locators of the subtree of the unpublished document in a consistent way. This method is currently private and only called by the `save`-method of the `RlpStrategy`.

**Comment by danrot** [comment]
The current behavior is the intended one. We don't want the resource locator to change too often.
