### ISSUE TITLE
publishing page produces exception when accessing unpublished child-page

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#2709]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-develop (01-08-2016)

#### Actual Behavior

1. Create an unpublished page _parent_
2. Create an unpublished page _child_ as child of the page _parent_
3. Publish the page _parent_

-> Accessing the page **/parent/child** in leads to an internal server error:
![](https://picload.org/image/rrlggpwl/getoriginallocale.png)

#### Expected Behavior

Accessing the page **/parent/child** should respond with "404 Not Found", as the child page is not published.

**Comment by danrot** [comment]
Is that something that might be fixed with #2706 ?

**Comment by nnatter** [comment]
@danrot: yes, #2706 should fix this problem.
