### ISSUE TITLE
The single internal link component is not aligned with the grid

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2711]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Enhancement? | yes |
| Sulu Version | dev-develop (2016-08-02) |
#### Actual Behavior

The single internal link component is not aligned with the grid.

![screenshot from 2016-08-02 07-37-39](https://cloud.githubusercontent.com/assets/1998663/17318142/2f478c60-5884-11e6-9f13-8cba5fbd6a19.png)
#### Expected Behavior

The UI of the component should be aligned with the grid.
#### Steps to Reproduce

See `Actual Behavior`.

**Comment by danrot** [comment]
Well, the white box is aligned with the other components...

**Comment by danrot** [comment]
Closing because there has already been a big redesign :slightly_smiling_face:
