### ISSUE TITLE
Published shadow pages in tree view are shown as in test mode

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#2719]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.6
| Browser Version |  51.0.2704.103 (64-bit)

#### Actual Behavior

In the tree view shadowpages are shown as in "test mode"
in the detail view of each page the pages are shown as published

#### Expected Behavior

Pages which are set as shadowpages and are published should be shown also in the tree-view as published pages.

**Comment by danrot** [comment]
Does not appear anymore, was maybe fixed with https://github.com/sulu/sulu/pull/2773
