### ISSUE TITLE
Organization details: parent company displays 'undefined'

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#2730]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.7 |
| Browser Version | Chrome 51.0.2704.103 (64-bit) |
#### Actual Behavior

When saving an account, and changing tabs the details tab shows 'undefined' in field parent company:

![bildschirmfoto 2016-08-03 um 09 34 39](https://cloud.githubusercontent.com/assets/5152633/17357651/296800ce-595e-11e6-80d7-0b3e3396a2dc.png)
#### Expected Behavior

No undefined
#### Steps to Reproduce
1. Open details tab of an organization
2. Change something and save
3. Change to another tab
4. Return to details tab

**Comment by danrot** [comment]
That is not happening anymore in Sulu 2.0, so I am going to close this issue.
