### ISSUE TITLE
Overwrite of html template loaded by require

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2733]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | 1.3.0-RC2 |
#### Actual Behavior

Currently the `html` templates are loaded over a relative path e.g.: `./list.html` this will not allow to overwrite this template without a modrewrite on the webserver.
#### Expected Behavior

Register the templates with require in the main component `template/sulumedia/media-selection-overlay` so the user can overwrite it in his own bundle.

**Comment by danrot** [comment]
Can you list which components are affected by that? Or is the mentioned one the only one?

**Comment by alexander-schranz** [comment]
think all `*.html` files in our bundles. 

![bildschirmfoto 2016-08-19 um 12 47 24](https://cloud.githubusercontent.com/assets/1698337/17807477/287d3062-660b-11e6-919e-75ffbb7798d9.png)

But maybe its possible to overwrite also the template when it is included relative? But dont know how this can be configured with require. Then nothing need to change we just need to document it how this can be done.

**Comment by wachterjohannes** [comment]
i would prefer to introduce a convention `template/<bundlename>/<componentname>/xyz.html` (`templates/sulucontact/contacts/skeleton.html`) this would be quite easy to document and easy to understand

**Comment by danrot** [comment]
@wachterjohannes Would you do that by registering these paths in the require config?

**Comment by wachterjohannes** [comment]
yes (:

**Comment by alexander-schranz** [comment]
Will not be changed for 1.x and not longer necessary for 2.0.
