### ISSUE TITLE
Cannot publish internal / external link

### ISSUE THREAD

**Issue by ZeeCoder** [sulu/sulu#2735]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2
| Browser Version | Chrome latest

#### Actual Behavior

When I create an internal or external link, and try to publish it, sulu reports a success, but after refreshing the page I see that it's still in "Test".
If, however I publish the content first as a regular "Content", and then change the published content to an internal link, it works as expected.

#### Expected Behavior

When I create an internal or external link, I should be able to publish it.

#### Steps to Reproduce

Create a new "Default" content.
After saving, go to settings and change the Page Type to internal link.
Fill out the Link title and linked content fields, then proceed to save.
Try publishing the content.
Refresh the page: it should show that the content is still in "Test" mode.

**Comment by marcelmoosbrugger** [comment]
Info: Publishing the internal link, according to the workflow of @ZeeCoder, works for me in the current `dev-develop`. However, the behaviour of the indicator in the toolbar is weird. It does not update when publishing the page and after a refresh its gone.

**Comment by ZeeCoder** [comment]
I encountered two more related errors:
- I couldn't unpublish an internal link, which I published the way I described in my original post under "Actual Behavior"
- When I tried to change a link's title, I got an error with the message "Error".

The only way I could specify the title of a link is to name the original content to what I want the link's label to be to begin with > publish the content > change it to be an internal link.

Is this happening to anyone else?
The problem with this workaround is that if someone wants to change the title later on, they'll encounter errors.

**Comment by marcelmoosbrugger** [comment]
Update: The page is indeed not published as the original poster described. In the backend however (e.g. in the column-navigation) it is marked as published (dev-develop 2016-08-03)

**Comment by marcelmoosbrugger** [comment]
@ZeeCoder, I could change the title of the link (at least got no error after saving).

**Comment by marcelmoosbrugger** [comment]
@ZeeCoder Is it possible, for you to test the issue on the current `dev-develop`?

**Comment by ZeeCoder** [comment]
Yes, I'll come back to you as soon as I found the time for it!

**Comment by danrot** [comment]
@ZeeCoder Since the publishing mechanism has drastically changed in develop the problems you've described are probably not occuring anymore.

However, I found two other issues: If you create an external or internal link directly from a page which has never been published, it is not deletable, because the system complains that it doesn't have a resource locator.

The second thing is that the state was not shown correctly in the toolbar, it kept the old state, resp. didn't show it at all if you directly navigate to a page.

I gonna fix these issues in a separate PR, and would consider this issue closed afterwards.

**Comment by ZeeCoder** [comment]
Thanks @danrot , that works with me 👍
