### ISSUE TITLE
[RFC] Drop support of PHP 5.5?

### ISSUE THREAD

**Issue by patkar** [sulu/sulu#2746]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | n/a
| Browser Version | n/a

#### Pros

* PHP 5.5 is end of life
* We force users to use secure version of PHP
* No problem if PHP 5.5 is dropped from Travis build matrix (as in #2744)

#### Cons

* PHP 5.5 users which want to update must update their php/systems too
* ???

#### When?

Maybe already for the upcoming 1.3 release?

**Comment by danrot** [comment]
Symfony is currently even supporting php 5.5 in 3.1, so we won't do that at the moment. We can think about this again in a few months.
