### ISSUE TITLE
[RFC] Drop support of PHP 5 for Sulu 1.4 release?

### ISSUE THREAD

**Issue by patkar** [sulu/sulu#2747]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | n/a
| Browser Version | n/a

#### Pros

* Scalar type hints
* Return values
* thus more type safety
* Better error handling with new Error type exceptions
* (Anonymous classes)
* new operators (spaceship, null coalesce)
* driving users to better performance through php 7
* usage of libraries which are php 7 only (like ocramius/package-versions)

#### Cons

* Sulu users need to update to PHP 7 too if they want still want to use sulu

#### Comparison

* TYPO3 8.x already dropped php 5 support
* Sylius may be drop php 5 support before it's first 1.0.0 release

**Comment by psren** [comment]
Should this go to 2.0 then? I think this is a huge BC break. Sylius is still not stable so that's fine.

But bumping to a major php Version in a minor release seems odd.

**Comment by danrot** [comment]
I've got the same opinion as @psren on this. Should definitely not happen before the 2.0 release, and even then we have to see how the PHP7 adoption is going.
