### ISSUE TITLE
Wrong Block behavior

### ISSUE THREAD

**Issue by Jace25** [sulu/sulu#2753]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-develop (2b06c61d6f501c80d66722dd56c6c8cc0c3fa19a)

#### Actual Behavior

I created a Block, which must not exists but if it does, there should only be one block. So i set the minOccurs=0 and the maxOccurs=1.
`
        <block name="native_add" default-type="advertisers" minOccurs="0" maxOccurs="1">
            <meta>
                <title lang="de">Native Ad</title>
            </meta>
            <types>
                <type name="advertisers">
                    <properties>
                        <property name="advertisers" type="contact">
                            <meta>
                                <title lang="en">Advertiser</title>
                                <title lang="de">Werbekunde</title>
                            </meta>
                            <params>
                                <param name="contact" value="false"/>
                                <param name="account" value="true"/>
                            </params>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
` 

If i create some content which is using this template the first thing is, that when i am using the minOccurs=0 the "Add Block" Button is disabled although there is no block added atm:
![image](https://cloud.githubusercontent.com/assets/4090694/17428615/0ec017f6-5aea-11e6-9dad-0a5c83680e83.png)

If i click the "disabled" button, it adds my block:
![image](https://cloud.githubusercontent.com/assets/4090694/17428623/216e7a0a-5aea-11e6-8dbc-edd9239f1498.png)
No the button is disabled as is should be.

If i remove the block again, the button gets active:
![image](https://cloud.githubusercontent.com/assets/4090694/17428650/41b25868-5aea-11e6-9505-15727c68bd9b.png)

But, while i was testing this behavior i noticed, that each time i remove and add the block, some form field was added to the content chooser:
First time i added the block:
![image](https://cloud.githubusercontent.com/assets/4090694/17428671/7d5d6074-5aea-11e6-936b-00080a9ca844.png)

After some removing and adding:
![image](https://cloud.githubusercontent.com/assets/4090694/17428685/a3dc70c8-5aea-11e6-8c29-12f71b452269.png)
 So it seems, that the content chooser is not cleared when removing some block. Maybe the affects other blocks to.

#### Expected Behavior

The Add-Block Button should be active if no block of this type is added. The add content overlay should be cleared if the block was removed or added again.

#### Steps to Reproduce

1. Create some Content with this block:
`
        <block name="native_add" default-type="advertisers" minOccurs="0" maxOccurs="1">
            <meta>
                <title lang="de">Native Ad</title>
            </meta>
            <types>
                <type name="advertisers">
                    <properties>
                        <property name="advertisers" type="contact">
                            <meta>
                                <title lang="en">Advertiser</title>
                                <title lang="de">Werbekunde</title>
                            </meta>
                            <params>
                                <param name="contact" value="false"/>
                                <param name="account" value="true"/>
                            </params>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
`

After loading it, you should see the disabled button (which is not really disabled)

2. Add and remove the block and look for the Form Overlay you got, when you try to add some content (contacts) to the block.

#### Possible Solutions

See above.

**Comment by marcelmoosbrugger** [comment]
@danrot I'll have a look at it.
