### ISSUE TITLE
HtmlMarkupParser misbehaving

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#2786]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 6f863a9 |

We'd like to have some previews of contents (e.g. images) inside the editor.
Developing this we found out, that there are some issues in the `HtmlMarkupParser`.

See https://regex101.com/r/iG6nO0/4 . 
There I've added some cases I think should be possible.
#### Use cases
- Previews in Editor (Like images, oembed, ...)
- Internal links on Images
- Own tags linking to something 
- ...

**Comment by Jace25** [comment]
Hi @wachterjohannes,

i am not sure, if this regex breaks something, but maybe this would fit:
```
--- a/src/Sulu/Bundle/MarkupBundle/Markup/HtmlMarkupParser.php
+++ b/src/Sulu/Bundle/MarkupBundle/Markup/HtmlMarkupParser.php
@@ -20,7 +20,8 @@ class HtmlMarkupParser implements MarkupParserInterface
 {
     const ATTRIBUTE_REGEX = '/(?<name>\b[\w-]+\b)\s*=\s*"(?<value>[^"]*)"/';
     const CONTENT_REGEX = '/(?:>(?<content>[^<]*)<)/';
-    const TAG_REGEX = '/(?<tag><%s:(?<name>[a-z]+)[^\/>]*(?:\/>|>[^<]*<\/%s:[^\/>]*>))/';
+    //const TAG_REGEX = '/(?<tag><%s:(?<name>[a-z]+)[^\/>]*(?:\/>|>[^<]*<\/%s:[^\/>]*>))/';
+    const TAG_REGEX = '/(?<tag><%s:(?<name>[a-z]+)[^>]*(?:\/>|>.*?<\/%s:[^\/>]*>))/';
```

**Comment by reflexxion** [comment]
Or with backreference to really match the same closing tag.
`(?<tag><(?<tagName>%s:(?<name>[a-z]+))[^>]*(?:\/>|>.*?<\/\k<tagName>>))`

https://regex101.com/r/iG6nO0/5


But probably it would be best to use a dom parser?

**Comment by wachterjohannes** [comment]
@reflexxion we already thought about using the dom-parser but it would be quite slow. we have done some performance checks and gets results about 10x faster with regex (this blog gets a comparable result http://blog.futtta.be/2014/05/01/php-html-parsing-performance-shootout-regex-vs-dom/) i will try your suggestions as soon as possible.

**Comment by patkar** [comment]
Would the performance penalty ever noticeable compared to secure HTML parsing with XPath?

http://stackoverflow.com/a/1732454/2084176 :trollface: 
>  Every time you attempt to parse HTML with regular expressions, the unholy child weeps the blood of virgins, and Russian hackers pwn your webapp. Parsing HTML with regex summons tainted souls into the realm of the living. HTML and regex go together like love, marriage, and ritual infanticide.

**Comment by wachterjohannes** [comment]
@patkar maybe we should rethink it but the performance boost is enormous and we should try first to improve this feature with regex. /cc @danrot @chirimoya what do you think?

**Comment by danrot** [comment]
@wachterjohannes I'd say it depends on the difference. If it is 1ms vs 10ms I would personally go with the `DomCrawler`, since it is the safer approach. If the user really feels a big difference we might have to think about it again.

**Comment by wachterjohannes** [comment]
We should discuss this with @chirimoya it was his and my decision when we implemented this feature.

**Comment by patkar** [comment]
How about an adapter on top and two implementations? One Dom parser and a
not regex one?

Johannes Wachter <notifications@github.com> schrieb am Do., 29. Sep. 2016
17:31:

**Comment by danrot** [comment]
Maintaining two solutions doesn't make any sense here to me... If something changes one of them is forgotten for sure. And I can't think that somebody wants to override the existing working one...

**Comment by wachterjohannes** [comment]
I have the same opinion here we should focus on one solution. but introducing an own service for that is maybe a good idea if there is someone who needs faster responses can override and use something else but in the core we should focus on one solution which fits most of the usecases.

**Comment by chirimoya** [comment]
ping @wachterjohannes

**Comment by wachterjohannes** [comment]
i have worked a liitle bit for that issue https://regex101.com/r/OoQ60u/2 its not perfekt but a lot better! maybe we can build on that

**Comment by reflexxion** [comment]
IMHO attributes should/must accept slashes (`/`)?!
Without that, this change won't be any better than it is now.

Think about possible use cases:

- Media in the editor 
 - `<sulu:media id="[MEDIA_ID]" />`
 - `<sulu:media id="[MEDIA_ID]">[SOME_CAPTION?!]</sulu:media>`
- Internal links in the editor 
 - `<sulu:link id="[UUID]">Link-Text</sulu:link>`
 - `<sulu:link id="[UUID]"><sulu:media id="[MEDIA_ID]" /></sulu:link>`
- Oembed (or smth like that where slashes are required) 
 - `<sulu:oembed url="[URL]" />`
- ...

**Comment by wachterjohannes** [comment]
your are totally right i will try to improve this in the near future. whats quite hard i think will be the media in the link... i cannot think how we handle this maybe with do it as long there are results in the match which would be implemented in php

**Comment by wachterjohannes** [comment]
@reflexxion i have worked yesterday at a functional version for `1.5` maybe you have time to take a look at the linked PR.
