### ISSUE TITLE
Running app/console assets:install fails

### ISSUE THREAD

**Issue by gisostallenberg** [sulu/sulu#2801]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.0
| Browser Version | n/a

#### Actual Behavior

```bash
PHP Fatal error:  Class 'Sulu\Component\HttpCache\EventSubscriber\ContentMapperSubscriber' not found in (.......)vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php on line 152
```

#### Expected Behavior

```bash
php app/console assets:install --env=prod
```
succeeding

#### Steps to Reproduce

see above

#### Possible Solutions

Fix the namespaces, setting or add a `use` statement. ContentMapperSubscriber is in namespace `Sulu\Component\Content\Document\Subscriber\Compat`.

**Comment by danrot** [comment]
It's working for me... The class you have mentioned here actually got removed. Have you cleared the cache for production?

**Comment by gisostallenberg** [comment]
You are right. It had something to do with an old clone.
