### ISSUE TITLE
Preview Bug: imageUrl get's overwriten by excerpt tab

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#2802]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
#### Actual Behavior

When setting an image in excerpt tab, the preview replaces the page's image (set with `{{ content.images }}` with the excerpts image.

Also if you open excerpt tab directly (without navigating to details tab first) the preview component is not initialized correctly. Means if you change anything, the preview is not responding.
#### Expected Behavior

The preview should send the properties in the correct twig variable (content, excerpt).
#### Steps to Reproduce
1. Open details tab
2. Open excerpt tab
3. Set an excerpt image
4. Look at page's and see the wrong image

**Comment by danrot** [comment]
This seems to be fixed in Sulu 2.0, where we refactored many parts of the preview.
