### ISSUE TITLE
Resource locator with slashes aren't editable fully after reloading

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#2819]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3

#### Actual Behavior

When entering and saving a RLP with slashes in it, it isn't editable correctly after reloading the edit dialog.

#### Expected Behavior

The whole RLP should be editable

#### Steps to Reproduce

E.g. entering `germany/berlin` in the input field, saving and reloading it will afterwards only allow to edit `berlin`

#### Possible Solutions

* Make the whole RLP editable again
* Disallow slashes

**Comment by chirimoya** [comment]
https://github.com/sulu/sulu/pull/2749

**Comment by alexander-schranz** [comment]
#1848 think in the leaf edit it should not be possible to add `/` in the url. /cc @wachterjohannes

**Comment by chirimoya** [comment]
#### Solution

* Disallow slashes

If you need the full tree editable, we will provide another resource locator strategy. See linked PR.

**Comment by wachterjohannes** [comment]
i will add this in the linked PR

**Comment by wachterjohannes** [comment]
i will create an own PR for this issue!
