### ISSUE TITLE
sulu_content_root_path() does not output the port

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu#2824]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.0
| Browser Version | Chrome 50.0.2661.102 (64-bit)

#### Actual Behavior

`sulu_content_root_path()` returns the path to the root, but without the current port number. When using the PHP built-in web server, the port is not included in the URL.

#### Expected Behavior

The returned URL should include the current port.

**Comment by webmozart** [comment]
related to #2423

**Comment by danrot** [comment]
@webmozart Could this be closed as duplicate of #2423

**Comment by danrot** [comment]
Fixed in https://github.com/sulu/sulu/pull/2840
