### ISSUE TITLE
Not possible to add new http cache handler

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2829]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.2 |
#### Actual Behavior

The compiler pass only allow internal handlers to be added to the AggregateHandler which are stored in `sulu_http_cache.handler.aggregate.handlers`. When you register your own service it can never be used, you need to overwrite the public service instead of add your own handler.
#### Solution

Instead of store the enabled handlers store the disabled and dont add them in the compilerpass.

**Comment by danrot** [comment]
This somehow contradicts with https://github.com/sulu/sulu/issues/2635. Don't know if we will fix that before the refactoring...

**Comment by danrot** [comment]
Since the AggregateHandler is gone this issue can probably be closed. @alexander-schranz Reopen if I am wrong for some reason.
