### ISSUE TITLE
Close button appearing on incorrect location

### ISSUE THREAD

**Issue by gisostallenberg** [sulu/sulu#2832]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
| Browser Version | n/a |
#### Actual Behavior

When pressing search in the assets overview a close button appears on the Add button
![image](https://cloud.githubusercontent.com/assets/11526270/17766824/3f01d498-652d-11e6-96f4-6f62b0daf6c1.png)
#### Expected Behavior

The button not appearing
![image](https://cloud.githubusercontent.com/assets/11526270/17766860/76e51ef6-652d-11e6-9784-f7b3eaa25c72.png)
#### Steps to Reproduce

Click on Assets, click on Search

**Comment by danrot** [comment]
I can't really reproduce that issue... I have tested in on the demo, when I am on the media session and click on search the navigation on your left hand side does not appear at all. And if I click the search icon (top left on your screenshots) it works as expected.

Maybe you should also tell which browser and OS you are using.

And apart from that this kind of navigation has been already removed on develop, so it won't be an issue anymore with 1.4.

**Comment by gisostallenberg** [comment]
The demo version is 1.2.1, not 1.3. I meant _Search_ from the main navigation, but in the demo version it does not reproduce either.

I'm using Google Chrome on Ubuntu.

**Comment by danrot** [comment]
Ah, ok, now I also know which search you've been talking about 😄 
Another issue is also that the light grey part of the navigation should be gone... Is that issue important for you? We have removed the entire collection navigation in 1.4, that's why I am asking.

**Comment by gisostallenberg** [comment]
For me it is fine the mark this as resolved by 1.4

**Comment by danrot** [comment]
Cool, then I will close the issue.
