### ISSUE TITLE
Content blocks do not support <info_text>

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu#2838]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3 |
#### Actual Behavior

Content blocks currently do not support the `<info_text>` element under `<meta>`. The element is simply ignored.
#### Expected Behavior

The `<info_text>` element should be rendered in the same way as in a section.

**Comment by webmozart** [comment]
Additionally, it's weird that this element is snake-case while others are camel-case (example: `<cacheLifetime>`) or hyphenated (example: `<block default-text="some-type">`).

**Comment by danrot** [comment]
No, `info_text` does currently not work at all, that's something we have to check in 2.0.

**Comment by danrot** [comment]
It does support it now :tada:
