### ISSUE TITLE
API Documentation 

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2839]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

#### Actual Behavior

No api documentation for sulu.

#### Expected Behavior

Maybe include of following bundle in admin kernel for the rest api documentation https://github.com/nelmio/NelmioApiDocBundle

**Comment by danrot** [comment]
Duplicate of https://github.com/sulu/sulu/issues/1715
