### ISSUE TITLE
Performance impact on the ContentRepository::resolveHasChildren method

### ISSUE THREAD

**Issue by nicodmf** [sulu/sulu#2844]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | master
| Browser Version | NA

#### Actual Behavior

Response for query with more than 20 or 50 nodes are too long

#### Expected Behavior

Fast query even with 1000 nodes

#### Steps to Reproduce

Add 1000 node under another node
Use the method ContentRepository::findByParentUuid(uuid...)
First phpcr query => All nodes are provided => good
1000 phpcr query => all nodes are tested independently for search possibles childs

#### Possible Solutions

To have a withChilds parameters, or a depth parameter.

#### Code

https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Content/Repository/ContentRepository.php#L636
https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Content/Repository/ContentRepository.php#L723
https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Content/Repository/ContentRepository.php#L832

**Comment by wachterjohannes** [comment]
The problem is that this will be tested foreach node. maybe we could collect them all together and query it once. The value of that boolean flag could be proxied maybe.

**Comment by danrot** [comment]
Thanks for reporting! But #2868 is actually the exact same issue, so I will close that one as a duplicate.
