### ISSUE TITLE
Double click is needed to create a page translation

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2847]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.0
| Browser Version | Tested in Firefox and Chrome

#### Actual Behavior
A double click is needed to create the page "Test" in en.
![double-click](https://cloud.githubusercontent.com/assets/5627878/17854337/13b0f81c-6872-11e6-9352-e32649b5f9b0.png)

#### Expected Behavior

A single click should be enough.

#### Steps to Reproduce

1. Create a page in "de".
2. Switch to "en" in the content tree view.
3. Try to add a translation for the page.

**Comment by wachterjohannes** [comment]
hmm the single click does something different it loads the children for a page. with a double-click you open the form. i dont think that this is a "misbehavior" @berndhep what do you think?

**Comment by berndhep** [comment]
@sabinebaer In the column navigation one click marks an item and a double click opens it. If this is confusing we could add an icon on mouseover to make it clearer. But a single click would be irritating because it does something else than in other use cases. 
@wachterjohannes @chirimoya let's discuss this

**Comment by chirimoya** [comment]
As far as I can remember, the mouse over action which displays the blue edit button got lost for this state. @sabinebaer please correct me, if I'm wrong.

**Comment by berndhep** [comment]
Yes, we would have to create a dedicated state (and button) for this case.

**Comment by berndhep** [comment]
![bildschirmfoto 2016-08-23 um 08 24 57](https://cloud.githubusercontent.com/assets/7425459/17882188/1b6ac7c4-690b-11e6-89dc-46366b37a4b8.png)
Something like this @chirimoya

**Comment by sabinebaer** [comment]
@wachterjohannes @berndhep For me it's confusing as I never use double clicks (it was more a coincidence that I tried to double click the item). A mouseover icon would be nice 👍
