### ISSUE TITLE
Call of the download url of a deleted file causes 503 Service unavailable error 

### ISSUE THREAD

**Issue by c00n84** [sulu/sulu#2854]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.7
| Browser Version | Chrome 52

#### Actual Behavior

In Google Search Console I'm getting a lot of 500 errors. The problem are media files which are deleted and not available anymore, but the links are still indexed in Google.
E.g. http://www.example.com/media/1066/download/Datasheet.pdfv=1

Log:
```
[2016-08-23 15:13:23] request.CRITICAL: Uncaught PHP Exception 
Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function 
getFiles() on a non-object" at 
/var/data/websites/www.example.com/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Controller/
MediaStreamController.php line 162 {"exception":"[object] 
(Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member 
function getFiles() on a non-object at 
/var/data/websites/www.example.com/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Controller/
MediaStreamController.php:162)"} []
```

#### Expected Behavior

I expect to get a 404 error page.

#### Steps to Reproduce

Upload a file, get the download url and delete the file. Now call the download url in the browser.

**Comment by danrot** [comment]
Fixed in #2864
