### ISSUE TITLE
Move Media to other collections / Collections limited to 10

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#2857]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Sulu Version | 1.2.3
| Browser Version | Browser name and version

#### Actual Behavior

By moving medias to other collections only the last 10 collections will be shown. But there are more sub-collections that should be shown.

#### Expected Behavior

All sub-collections should be shown and should be choosable

#### Steps to Reproduce

Try to move media to a collection with more than 10 subcollections

#### Possible Solutions

-

**Comment by danrot** [comment]
@marcelmoosbrugger Is that issue also already fixed by https://github.com/sulu/sulu/pull/2843 ?

**Comment by marcelmoosbrugger** [comment]
@danrot Yes should be fixed. However not in the 1.2 version.

**Comment by danrot** [comment]
Fixed by #2863
