### ISSUE TITLE
Resolving content in ContentRepository

### ISSUE THREAD

**Issue by janmassive** [sulu/sulu#2868]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.1.8 |
| Browser Version | - |
#### Actual Behavior

Receiving all contents in ContentRepository is really slow since the function 'resolveHasChildren' gets executed for each result. Furthermore an PHP exception is thrown if an array property is added to the mapping that can be added. (In 'Jackalope\Query\Row' -> 'getValue()' on line 166)
#### Expected Behavior

The findAll function should provide a possibility to avoid resolving children and there should be no exception be thrown in all cases.
#### Steps to Reproduce

Performance can be reproduced by executing findAll function with a big content tree. The exception is thrown if the snippet selection component is defined in template, but contains no snippets.
#### Possible Solutions

Add 'dontResolveChildren' parameter to findAll function in ContentRepository.

The exception can be avoided by rewriting the resolveProperty function in ContentRepository to: (does not execute 'Jackalope\Query\Row' -> 'getValue()' function anymore)

```
        $values = $row->getValues();

        $propertyKey = sprintf('node.%s', $name);
        if (array_key_exists($propertyKey, $values)) {
            return $values[$propertyKey];
        }

        if (null !== $shadowLocale && !in_array($name, self::$nonFallbackProperties)) {
            $locale = $shadowLocale;
        }

        $name = sprintf('%s%s', $locale, ucfirst($name));

        $propertyKey = sprintf('node.%s', $name);
        if (array_key_exists($propertyKey, $values)) {
            return $values[$propertyKey];
        }

        return null;
```

**Comment by wachterjohannes** [comment]
the `resolveHasChildren` parameter should be added in the Mapping class. the code-snippet looks good and we should introduce that in 1.4 @danrot what do you think?

**Comment by danrot** [comment]
Yeah, sounds reasonable. But I would name the method on the `Mapping` class `setResolveChildren`, to match the other method names.

**Comment by wachterjohannes** [comment]
thats correct (:

**Comment by danrot** [comment]
I guess this will be fixed differently in a bigger refactoring, therefore going to close it.
