### ISSUE TITLE
Media bug: error when uploading media anonymously as system collection

### ISSUE THREAD

**Issue by matthijsch** [sulu/sulu#2879]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3

#### Actual Behavior

When uploading media as a system collection anonymously an error occurs
`Call to a member function getId() on string {"code":1,"message":"Call to a member function getId() on string","file":"vendor/sulu/sulu/src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php","line":140} []`

#### Expected Behavior

Either it should be possible to post media as a system collection while not being logged in or an exception should be thrown

#### Steps to Reproduce

When a system collection is being retrieved anonymously like below the error occurs:
`$collection = $this->systemCollectionManager->getSystemCollection($data['systemCollectionKey']);  `

This is because on the line below the SystemCollectionManager tries to retrieve the ID of the User instance while User is a string ('Anom.')
https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php#L140

**Comment by danrot** [comment]
@alexander-schranz Is that what you've fixed in https://github.com/sulu/sulu/pull/2923 ? If so please close this issue.

**Comment by alexander-schranz** [comment]
@danrot yes this is fixed with #2923
