### ISSUE TITLE
Webspace-Key cannot contain dash or point

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2882]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3 |
| Browser Version | all |
#### Actual Behavior

If you use a dash (or point) in the webspace-key you are "Unable to edit, delete or move a content page in a new added webspace" see: https://github.com/sulu/sulu-minimal/issues/15
#### Expected Behavior

This should work or at least be validated.
#### Steps to Reproduce

Install sulu-minimal and create a new webspace with a dash in the key.
#### Possible Solutions

Validate the key and throw a meaningful exception.

**Comment by danrot** [comment]
Closed in favor of #3008 (is described in more detail, and there are no comments in this issue anyway).
