### ISSUE TITLE
HTTP-Cache warmer

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#289]
Process:
- Install https://github.com/guzzle/http
- Get sitemap
- Call all urls in sitemap over  buzz

Problems:
- Maximum run time of php

**Comment by dantleech** [comment]
You could even write a web application which crawls Sulu sites (or anyother sites which have a sitemap) - I wonder if there is one already...

**Comment by wachterjohannes** [comment]
i have found yesterday following repository which crawls a website and exract informations of it!

https://github.com/codeguy/arachnid

i think it is very useful to integrate it into a bundle and write a Symfony CacheWarmer and a Command which crawls the Website extract informations (e.g. broken links ...) write them into a log file and at the same time write all sites into the cache.

I have speaked to @danrot and i will create an own bundle for that which will be sulu independent and provides this command and cache warmer.
