### ISSUE TITLE
Small media selection text overlap button

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2894]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | dev-develop (02.09.2016) maybe also on 1.3.0 |
#### Actual Behavior

![bildschirmfoto 2016-09-02 um 10 11 03](https://cloud.githubusercontent.com/assets/1698337/18197100/c714cbfa-70f5-11e6-8ccc-f2c2c40bd7f6.png)
#### Expected Behavior

Text should not overlap the button.

**Comment by danrot** [comment]
Does not happen anymore in the new design.
