### ISSUE TITLE
Edit structure file : move files in a folder 

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu#2902]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | maybe
| Sulu Version | 1.3

Hello

I'm a newcomer to sulu
I want to move web folder according to my web hosting structure, create automatically by the control panel : 

-root folder
--private
--web

Sulu is installed in private folder, so I have to move /private/web files to /web.
I've changed composer params : 
`    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "../web",
}
,
 Assetics (sulu.yml) :
`assetic:
    write_to: "%kernel.root_dir%/../../web"`

Paths in /web (admin, website) :
`/../private/app`

#### Actual Behavior
Sulu front and back works
Assetics symlinks are good.
But Admin Translations and medias uploads are still created in private/web and private/uploads

#### Expected Behavior

Admin Translations and medias should use the /web folder as configured

#### Steps to Reproduce
Move web folder to parent, edit paths in configuration file and composer.
Upload files in backend

**Comment by alexander-schranz** [comment]
For the medias which are generated add the following to your config (`app/config/config.yml`): 

```
sulu_media:
    format_cache:
        path: %kernel.root_dir%/../../web/uploads/media
```

for the translations you need to run the following command:

```
app/console sulu:translate:export --path "../web/admin/translations"
```

@sulu/core-team the translate export should be configureable and maybe we should have one variable to change the web directory?

**Comment by rflorent** [comment]
Thanks for reply and good idea for translate export.

I've added sulu_media path to config.yml, clearing cache but no change, files uploaded still create web folder  for storing media files.

private/web/uploads/media/260x ...

Is there something I'm missing ?

**Comment by alexander-schranz** [comment]
This config should work could you pls check the `$path` here: 

https://github.com/sulu/sulu/blob/1.3.0/src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php#L53

**Comment by rflorent** [comment]
dump under dev mode show right path : 

 LocalFormatCache.php line 54
"/Users/Florent/Travail/www/sulu/www/private/app/../../web/uploads/media"

I clear the cache dev / prod

When I upload file, /private/web is create with format cache folder and file, I don't know why.
By the way, is there no other way than force SYMFONY_ENV to dev to change mode ?

thanks

**Comment by alexander-schranz** [comment]
how did you clear the cache on the website kernel using the `websiteconsole` / `webconsole`? 

You can set the `SYMFONY_ENV` in your `vhost`: http://docs.sulu.io/en/latest/cookbook/web-server/apache.html

The default is set in the `admin.php` and `website.php`.

**Comment by rflorent** [comment]
I use app/console cache:clear --env=prod

**Comment by alexander-schranz** [comment]
@rflorent app/console will only clear the admin cache use `app/webconsole cache:clear --env=prod` to clear the website cache.

**Comment by danrot** [comment]
@alexander-schranz Have you tried it out on your own? Could imagine that this is a bug on our side...

**Comment by rflorent** [comment]
Using webconsole resolve this, no more web folder created in my private folder. 
Thanks for all !
