### ISSUE TITLE
Purge of cache not working on https

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2929]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.7 |
#### Actual Behavior

When I edit my startpage https://alexanderschranz.com I need to clear the cache manually before the changes are visible is it maybe a problem with the https?
#### Expected Behavior

Should clear the cache of the startpage automatically.

**Comment by danrot** [comment]
Is this only happening on the startpage? Is the cache purged for other pages? Do you have any errors in the log?

**Comment by alexander-schranz** [comment]
Also for the subpages the cache is not cleared. See no error in the logs.

**Comment by wachterjohannes** [comment]
are you using the backend with https or http. i think the cache uses the current "host" maybe it also uses the current "scheme" (or default http)

**Comment by alexander-schranz** [comment]
all is HTTPS

**Comment by danrot** [comment]
Duplicate of https://github.com/sulu/sulu-standard/issues/791, should already be fixed.
