### ISSUE TITLE
Can't add apostrophe in meta.title of page template

### ISSUE THREAD

**Issue by reyostallenberg** [sulu/sulu#2932]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
| Browser Version | Google Chrome |
#### Actual Behavior

When I add an apostrophe (' or &amp;39; or &amp;apos;) in a meta.title of a page template as below:
![image](https://cloud.githubusercontent.com/assets/3579090/18643209/5abfa4cc-7ea4-11e6-9c7c-37a7e96cec5f.png)
I get the following error:
![image](https://cloud.githubusercontent.com/assets/3579090/18643256/98d1d12c-7ea4-11e6-8042-6c1d67c2ebe2.png)
#### Expected Behavior

That I can add an apostrophe in a title, and the title is represented in the frontend interface
#### Steps to Reproduce

See screenshot before
#### Possible Solutions

Do escaping before serialization

**Comment by wachterjohannes** [comment]
thanks for reporting this. would be quite easy to solve. @danrot should we solve this as HOTFIX or only in develop?

**Comment by reyostallenberg** [comment]
develop is okay with me
