### ISSUE TITLE
smart_content property in a snippet is not working

### ISSUE THREAD

**Issue by comemanu** [sulu/sulu#2939]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu version | 1.3.0 |
#### Actual Behavior

When trying to add a new snippet from the template, clicking on the smart_content button,
window is opening, but when trying to open the data source, nothing happens and the following error is showing in the console :
`{code: 0, message: "Call to a member function getKey() on null",…}
code
:
0
errors
:
[{message: "Call to a member function getKey() on null", code: 0,…}]
message
:
"Call to a member function getKey() on null"`

**Comment by danrot** [comment]
That issue is related to https://github.com/sulu/sulu/issues/2954

**Comment by danrot** [comment]
This seems to work now.
