### ISSUE TITLE
Sulu search should not return internal links

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#2940]
| Q | A |
| --- | --- |
| Bug? | kind of |
| New Feature? | kind of |
| Sulu Version | 1.2.7 |
#### Actual Behavior

When searching for pages in sulu search, also pages that are internal links get returned. 
#### Expected Behavior

I don't want to show internal links. It would be nice if i could query for non internal links, or at least be able to filter the results.
#### Possible Solutions

Implement a new Field `internal-link` for Document

**Comment by danrot** [comment]
@berndhep What do you think? Should a page being an internal link be returned in the search?

**Comment by danrot** [comment]
Since nobody else complained about this until now I am going to close this issue.
