### ISSUE TITLE
Data-Grid-View with wrong settings fails to render

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#2941]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3 |
#### Actual Behavior

From time to time our editors are complaining about not working data grids.
Somehow they managed to save a sort-field not existing in a specific view e.g. `mediaOrder`.
#### Expected Behavior

Hard to say; Probably don't save the setting if that `FieldDescriptor` does not exist in specific view.
#### Steps to Reproduce

I dunno how the editor did that.
##### Possible solutions

Show an message that the rendering fails due to wrong settings and adding a button to "unset" this settings.

**Comment by danrot** [comment]
I have just tried that e.g. for the thumbnail in the media section, and they are not sortable anymore. So I consider this issue solved.
