### ISSUE TITLE
Unable to initiate custom Admin service without creating Navigation for it

### ISSUE THREAD

**Issue by Edvinas9** [sulu/sulu#2943]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
| Browser Version | not applicable since it's coming from the back-end |
#### Actual Behavior

`AdminPool` is expecting custom `Admin` classes to always return an `Navigation` object when `Admin::getNavigation()` is called & crashes if it doesn't.
#### Expected Behavior

`AdminPool` should just skip `Admin` classes without `Navigation` objects when gathering all `Navigation` objects together during `AdminPool::getNavigation()` execution.
#### Steps to Reproduce

Create a custom admin class that extends `Sulu\Bundle\AdminBundle\Admin\Admin` and declare it as a service which is tagged as being `sulu.admin`. In theory, an empty `Admin` class should still "work" without breaking the whole CMS. However, when you'll try to load the CMS, you'll see that AJAX call to an API endpoint that is responsible for loading navigation started failing (API endpoint: `website.dev/admin/navigation`) and throwing this error:
`Type error: Argument 1 passed to Sulu\Bundle\AdminBundle\Navigation\Navigation::merge() must be an instance of Sulu\Bundle\AdminBundle\Navigation\Navigation, null given, called in /var/www/mysite.dev/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Admin/AdminPool.php on line 62`
#### Possible Solutions

The actual fix should probably be done in `Sulu\Bundle\AdminBundle\Navigation\Navigation::merge()` method. It should allow it's sole argument to be `null`. Aside from method header declaration, some other tweaks will also be required to be done in the source of the method.

**Comment by danrot** [comment]
Good point. I also think that it was a bad idea to put the navigation in the constructor. It should be created in a separate method.

**Comment by danrot** [comment]
That has been fixed in Sulu 2.0, because the `configureNavigationItems` function does not return anything anymore, and does not have to do anything.
