### ISSUE TITLE
Routeprovider does not support formats

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2949]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.3.0 |
#### Actual Behavior

Actually you are not able to support formats (e.g. `.rss`, `.pdf`, ...) when the entity use the route provider.
#### Expected Behavior

It should be possible to render a entity in specific formats.
#### Steps to Reproduce

Add e.g. `.rss` to your registered route.
#### Possible Solutions

The default route provider of the entity need to know which template is render and when there exist `.rss.twig` it should be able to request this format.

**Comment by wachterjohannes** [comment]
An easier and faster solution (some kind of middle step) is to return a list of supported formats from the `RouteDefaultsProvider` or configuration?

**Comment by wachterjohannes** [comment]
The current way in the page system is that the route-provider accepts all formats and the controller throw 405 exception if he cannot handle the format. There we could configure the "available" formats in the xml template of the page. for the route-bundle i would go the same way:

* accept all formats (405 handled by controller)
* afterwards (maybe the next step) make if configurable over config-tree (and xml-template for pages)

**Comment by alexander-schranz** [comment]
fixed in https://github.com/sulu/sulu/issues/3755
