### ISSUE TITLE
Input fields disappear in multiply region

### ISSUE THREAD

**Issue by RaphaelHofer** [sulu/sulu#2953]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.7
| Browser Version | Chrome Version 53.0.2785.116 (64-bit) (Every browser)

#### Actual Behavior

If you have a multiply region with min-occur set to 1 and max-occur set to 2, adding a 2nd block and switching the first one to the same type the media selection fields and the block-type dropdown disappear. 

#### Expected Behavior

Input fields keep their functionality.

#### Steps to Reproduce

See actual behavior.

#### Possible Solutions

For our use case it a solution would be to set max-occur on multiply regions to 1 with multiple block-types (we only need the dropdown for switching the input fields of the block).

![bildschirmfoto 2016-09-30 um 11 13 08](https://cloud.githubusercontent.com/assets/9111646/18986852/1c6ce924-86ff-11e6-9461-1520879da29b.png)

**Comment by danrot** [comment]
Fixed in #2955
