### ISSUE TITLE
Single Internal Link does not work in snippets

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#2954]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 883dd4999d11134fb900f5e86b4a93bd21f51d4b |
| Browser Version | --- |
#### Actual Behavior

The `single_internal_link` content type does not work correctly if used in a snippet template.

It works as long there was no selection for the `single_internal_link`, because if you click on the blue button to assign a link a request to `admin/api/nodes?tree=true&language=en&webspace-node=true` is sent.

But if a page was already assigned it tries to load the path to this page, and sending a request like `admin/api/nodes?id=3970a897-cbff-4048-9810-5331838f20b5&tree=true&language=en&webspace-node=true`. The problem here is that it tries to load the UUID and append only the webspace the page is located in.

This happens because it looks like nobody thought about using the `single_internal_link` content type, which means that a `webspace` parameter is mandatory.
#### Expected Behavior

The `single_internal_link` overlay should be working as expected.
#### Steps to Reproduce

Use the following snippet definition:

``` xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <meta>
        <title lang="de">Standard</title>
        <title lang="en">Default</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="de">Titel</title>
                <title lang="en">Title</title>
            </meta>

            <tag name="sulu.node.name"/>
        </property>

        <property name="single_internal_link" type="single_internal_link">
            <meta>
                <title lang="de">Verlinkung</title>
                <title lang="en">Link</title>
            </meta>
        </property>
    </properties>
</template>
```
1. Create a new snippet of that type
2. Assign a page to the single internal link
3. Save the snippet
4. Reload and try to assign a new snippet
#### Possible Solutions

The `webspace` parameter should not be mandatory, and instead of a boolean flag `webspace-node` we should have the `webspace-nodes` parameter as in the other actions. This way we could could include all webspaces on the top level again, load the entire path, and merge these two arrays together.

The `webspace-node` property has not too many references: https://github.com/sulu/sulu/search?utf8=%E2%9C%93&q=webspace-node

The other possibility is to build something similar in a more complicated way to keep BC.

**Comment by danrot** [comment]
@chirimoya @wachterjohannes WDYT? Should we keep BC here, or should we implement it in a clean way?

**Comment by wachterjohannes** [comment]
we should implement it in a clean way. i dont see the big advantage of the current behavior and the old data are also valid then.

**Comment by chirimoya** [comment]
ACK

**Comment by wachterjohannes** [comment]
also happens in links for ckeditor.

**Comment by rogamoore** [comment]
Workaround: Use internal_links instead. Drawback: It's not possible to limit the selection in the admin area - but you can provide a help text and only use the first link in your twig template.
