### ISSUE TITLE
Live Preview does not work on checkbox type

### ISSUE THREAD

**Issue by ReneZumtobel** [sulu/sulu#2961]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | dev-develop |
#### Actual Behavior

Live Preview does not update on checkbox content type.
#### Expected Behavior

Live Preview should update
#### Steps to Reproduce
1. Make a template with a checkbox.
2. Make a twig with live preview included for checkbox.
3. Change something -> nothing happens!

**Comment by danrot** [comment]
I have just tried the example template in the sulu-standard edition, and the checkbox preview is working there as expected. Therefore I am closing this.
