### ISSUE TITLE
Preview bug with sulu_breadcrumb / live workspace

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#2973]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.1 |
#### Actual Behavior

Preview isn't working when creating a new page as a draft and using `sulu_breadcrumb(uuid)`.

Error:

```
Type error: Argument 1 passed to Sulu\Bundle\DocumentManagerBundle\Bridge\DocumentInspector::getStructureMetadata() must implement interface Sulu\Component\Content\Document\Behavior\StructureBehavior, instance of Sulu\Component\DocumentManager\Document\UnknownDocument given, called in /Users/thomasduenser/Development/websites/ideenkanal.dev/vendor/sulu/sulu/src/Sulu/Component/Content/Mapper/ContentMapper.php on line 889
```
#### Expected Behavior

That the preview is returning the breadcrumb / is working.
#### Steps to Reproduce
1. Create a page and save it as a draft (do not publish it)
2. The template must have `sulu_breadcrumb(uuid)` in it
3. Look at the preview 
#### Possible Solutions

Seems like the preview is using the wrong workspace. Instead of using the `default` workspace, the `live` workspace is in use. There the page UUID doesn't exist.

Possible solution is to use the `live` workspace and edit the config at `src/sulu/bundle/previewbundle/resources/config/config_preview.yml`

with following lines:

```
sulu_document_manager:
    default_session: default
    live_session: live
```

furthermore it would be useful to make the preview config rewritable.

**Comment by wachterjohannes** [comment]
@danrot @chirimoya prolem is then that we see drafted data (for example in navigation/smart-content) but it would fox other problems.

**Comment by thomasduenser** [comment]
@wachterjohannes I was talking to @c00n84 yesterday and the preview is already showing the data of the current page, even if it's in the draft mode. That's why I think it's correct to see the drafted data there.

**Comment by wachterjohannes** [comment]
the current page is not the problem. you would also see the "drafted" data of another page (navigation, smart-content, ...)
