### ISSUE TITLE
Template improvement for better inheritance

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2974]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
#### Actual Behavior

Actually its hard to overwrite or extend any templates in the backend some are hardcoded `html` files which could not be overwritten or `twig` files where only the whole file could be overwritten.
#### Expected Behavior

Easy extend of exist template and make it overrideable of specific parts.
#### Possible Solutions

Here my solution for make it easier to extend the backend html.

When you render HTML you first need to create a new route:

``` xml
<!-- routing.xml -->

<route id="sulu_bundle.template.settings" path="/template/detail.html">
    <default key="_controller">FrameworkBundle:Template:template</default>
    <default key="template">SuluBundle::detail.html.twig</default>
</route>
```

``` twig
<!-- SuluBundle::detail.html.twig -->

{% extends 'SuluBundle::detail-base.html.twig' %}

{#-
 # Overwrite this template by create the file "app/Resources/SuluBundle/views/detail.html.twig"
 # which extends also from "SuluBundle::detail-base.html.twig"
-#}
```

``` twig
<!-- SuluBundle::detail-base.html.twig -->

<form id="settings-form" class="grid">
    {% block title %}
        <div class="grid-row">
            <div class="grid-col-12 form-group">
                <label for="title"><%= translations.title %></label>

                <!-- ... -->
            </div>
        </div>
    {% endblock %}

    {% block description %}
        <div class="grid-row">
            <div class="grid-col-12 form-group">
                <label for="title"><%= translations.title %></label>

                <!-- ... -->
            </div>
        </div>
    {% endblock %}

    {% block extends %}{# Add additional fields here #}{% endblock %}
</form>
```

Now if someone want to extend or overwrite the form he can do the following:

``` twig
<!-- app/Resources/SuluBundle/views/detail.html.twig -->

{% extends 'SuluBundle::detail-base.html.twig' %}

{% block description %}
    <!-- here he can overwrite the description field -->
{% endblock %}

{% block extends %}{# Add additional fields here #}{% endblock %}
```

This avoids that he need to copy the whole template and will have lesser problems when we change or extend exist templates in the core.

**Comment by wachterjohannes** [comment]
see https://github.com/sulu/SuluArticleBundle/pull/39

**Comment by alexander-schranz** [comment]
this is not longer necassery since [symfony 3.4](https://symfony.com/blog/new-in-symfony-3-4-improved-the-overriding-of-templates) as you can extend from the original file and also we have not so much twig files in 2.0
