### ISSUE TITLE
Remove query string from media formats

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2980]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
#### Actual Behavior

Sulu adds query string to images. Tools like https://tools.pingdom.com/ will rate that negative because some proxy will not cache content which have query strings.
#### Expected Behavior / Possible Solutions

We need the query string for versioning of the medias my solution would be to avoid the query string for version 1 of the media because I think the most medias on a website will not have more then 1 version.

**Comment by danrot** [comment]
Shouldn't we find a better solution for that? The suggested one does not really solve the problem, it is only being delayed. Maybe we can also use the HTTP cache as we do for the pages instead of the query string? However that would probably be not as performant as the current solution is...

**Comment by alexander-schranz** [comment]
This solution is not perfect but it would not break the folder structure. And if I look at some production db about 90% have version 1. HTTP Cache is just for the server side so it would doing nothing for the client side caching. Also pages are only cache 240s on the client and images 1month this is the version number is added. 

Other solution for this problem are internal redirects in a VHost but then the url need to be changeable to something like `/uploads/media/<format>/<folder>/<filename>.<version>.<extension>` the vhost will then  map it to a url without the `<version>` part `/uploads/media/<format>/<folder>/<filename>.<extension>`

**Comment by danrot** [comment]
All I am saying is that in a REST API that would be done via a header, and not as a query parameter. However, I don't know how this is applicable to images, since the image tags make the requests on their own 😕

**Comment by danrot** [comment]
@alexander-schranz I just checked our website with the tool you've suggested above (https://tools.pingdom.com/#5ba373a6ed000000), and I can't find anything about what you are suggesting here. There are also [other articles](https://sirv.com/help/resources/remove-query-strings-from-static-resources/) advising to keep these query parameters. Therefore I am going to close this issue.
