### ISSUE TITLE
Media selection properties in content variable in twig are resolved incorrectly

### ISSUE THREAD

**Issue by janmassive** [sulu/sulu#2984]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3 |
| Browser Version | Google Chrome 53 |
#### Actual Behavior

If properties of a media selection within the variable 'content' in a twig template want to be accessed, they are returned unresolved in the following format:

```
array:2 [▼
    "displayOption" => "top"
    "ids" => array:1 [▼
        0 => 1
    ]
]
```
#### Expected Behavior

If you have the same template within a snippet and resolve it with 'sulu_snippet_load(...)' the property 'content' contains the media in the following format:

```
array:1 [▼
      0 => Media {#2859 ▼
          #url: "/media/3/download/banner.png?v=1"
          #formats: array:18 [▶]
          #locale: "en"
          #version: null
          #additionalVersionData: array:1 [▶]
          #fileVersion: FileVersion {#2284 ▶}
          #localizedMeta: null
          #file: File {#2281 ▶}
          #entity: Media {#2278 ▶}
      }
]
```

This should also be the expected behavior when using a media selection within a page template. 
#### Steps to Reproduce

Create a page and a snippet template with a media selection in it and dump the 'content' property in a twig template.
#### Possible Solutions

---

**Comment by alexander-schranz** [comment]
seems to be fixed
