### ISSUE TITLE
Invalid namespace import

### ISSUE THREAD

**Issue by sagikazarmark** [sulu/sulu#2990]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.x |
| Browser Version | Not relevant |
#### Actual Behavior

Whenever the autoloader loads src/Sulu/Bundle/MediaBundle/Entity/Media.php a fatal error is triggered.
#### Steps to Reproduce

Autoload the class
#### Possible Solutions

Backport https://github.com/sulu/sulu/commit/3a6c999c4a8f0d5d3ff094471b2023efe856f82c to the 1.3.x release branch

**Comment by alexander-schranz** [comment]
The doctrine collection conflicts with the media collection (which is in the same folder as the media entity), because it was only used for annotation I did remove this in #2513. We could do this fix also for `1.2.x` and `1.3.x`.  /cc @wachterjohannes @chirimoya

**Comment by wachterjohannes** [comment]
@alexander-schranz will you create a HOTFIX for these two versions?

**Comment by alexander-schranz** [comment]
@wachterjohannes PR for 1.3 done for 1.2 is no one required.

**Comment by sagikazarmark** [comment]
Can we expect a hotfix release soon?

**Comment by danrot** [comment]
@sagikazarmark Seems as this have already been in the 1.3.2 release, so I am closing this issue.

**Comment by sagikazarmark** [comment]
@danrot I would say this is quite a bug which should be fixed downstream (AFAIK already done, not sure if a hotfix has been released or not).

**Comment by danrot** [comment]
@sagikazarmark According to the changelog it has been released 😉

**Comment by sagikazarmark** [comment]
Awesome, thanks.
