### ISSUE TITLE
Blameableentity will set changer as creator when creator is null

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2996]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.4.0-RC1 |
| Browser Version | Browser name and version |
#### Actual Behavior

When the creator is null and somebody change a blameable entity he will be the creator and changer keep being null.
#### Expected Behavior

Creator should keep being null and only the changer should be updated. Why it should be null is e.g. the https://github.com/sulu/SuluCommentBundle when you edit a comment the creator should keep being null.
#### Steps to Reproduce
1. Create a blameable entity with a user A.
2. Remove user A. So the entity will have Changer and Creator null.
3. Edit the entity with User B.
4. Now User B will be creator, changer is still null

**Comment by danrot** [comment]
Just tested this with a contact, and this problem does not seem to exist anymore.
