### ISSUE TITLE
Location content type mixed content error

### ISSUE THREAD

**Issue by reyostallenberg** [sulu/sulu#3003]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | dev-develop |
| Browser Version | Google Chrome Version 54.0.2840.59 (64-bit) |
#### Actual Behavior

Location content type errors in admin area as google maps is loaded insecure, see screenshot:
![screenshot from 2016-10-26 14-27-15](https://cloud.githubusercontent.com/assets/3579090/19725998/02d722ec-9b89-11e6-8267-a38f6e37c491.png)

Caused by **http** on https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/LocationBundle/Resources/public/js/map/google.js#L23
#### Expected Behavior

Load the google maps api js without errors
#### Steps to Reproduce

Host a project under https, access the admin area, add a location content-type to a page
#### Possible Solutions

Add `var gmapApiUrl = 'https://maps.google.com/maps/api/js?sensor=false';
` or `var gmapApiUrl = '//maps.google.com/maps/api/js?sensor=false';
` on https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/LocationBundle/Resources/public/js/map/google.js#L23

**Comment by danrot** [comment]
@reyostallenberg I don't see any reason not to do that :-) Can you create a PR for that?

**Comment by alexander-schranz** [comment]
as @reflexxion mention in #3029 the same is for the leaflet adapter.

**Comment by reyostallenberg** [comment]
What solution do you prefer? The one always using https or the one taking the current protocol?

**Comment by danrot** [comment]
@reyostallenberg I think there is no reason not to use HTTPS, right? So I would just use it. I think you won't get the mixed content error the other way round.

**Comment by reyostallenberg** [comment]
That's correct. I'll make a PR for both issues
