### ISSUE TITLE
Teaser not working for content pages

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3006]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.4.0-RC1 |
#### Actual Behavior

Content teaser not working when no content pages exist in teaser.
#### Expected Behavior

What is the behavior you expect?
#### Steps to Reproduce

Add pages to a teaser where no pages exist.

<img width="1162" alt="bildschirmfoto 2016-10-28 um 12 01 27" src="https://cloud.githubusercontent.com/assets/1698337/19803759/cad9ea9a-9d0a-11e6-85dc-5c76f937dbc1.png">

**Comment by wachterjohannes** [comment]
@alexander-schranz @chirimoya i cannot reproduce this issue maybe one of you can explain me in more detail.

**Comment by alexander-schranz** [comment]
The js error was fixed in https://github.com/massiveart/husky/pull/748. The other problem was for me that teaser for content pages only works when the search index is build and the page exist in the index, running the following comment did fix this problem:

```bash
bin/console massive:search:reindex
bin/webconsole massive:search:reindex
```
