### ISSUE TITLE
Husky error in url property when no url provided

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#3007]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.1 |
| Related Issues | https://github.com/massiveart/husky/issues/747 |
#### Actual Behavior

Using a property of type `url` in a structure and saving it without entering a url throws uncaught `TypeError` on next reload.
#### Expected Behavior

Simply display the field without calling the validator or preventing the field to be `null`
#### Steps to Reproduce

As described above
#### Possible Solutions
- Save an empty property value instead of null
- Validate `url` in husky before calling `.match()` on it

**Comment by danrot** [comment]
Fixed with https://github.com/massiveart/husky/issues/747

**Comment by reflexxion** [comment]
Hi @danrot,

but massiveart/husky#747 is not merged in 1.3.5 is it?

**Comment by danrot** [comment]
@reflexxion No, the fix is only in 1.4.0...

**Comment by reflexxion** [comment]
Yep, just found it myself
https://github.com/sulu/sulu/tree/1.3.5/src/Sulu/Bundle/AdminBundle/Resources/public/js/vendor/husky

**Comment by danrot** [comment]
Do you need it? Or are you planning to upgrade to 1.4 anyway?

**Comment by reflexxion** [comment]
We're planning to use 1.4 in the near feature.
But just upgraded to 1.3.5 and thought that it is fixed in there ;)
