### ISSUE TITLE
content list is empty although there should be something in there.

### ISSUE THREAD

**Issue by joemoe** [sulu/sulu#3008]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
| Browser Version | Chrome 54.0 |
| PHP | 7.0.11 |
#### Actual Behavior

Created pages are not shown in the content list.
<img width="353" alt="bildschirmfoto 2016-10-29 um 00 34 49" src="https://cloud.githubusercontent.com/assets/68620/19824527/9f773ad6-9d70-11e6-8711-15dbf31bbfa2.png">
but there are some
<img width="361" alt="bildschirmfoto 2016-10-29 um 00 34 58" src="https://cloud.githubusercontent.com/assets/68620/19824531/a687ff54-9d70-11e6-806a-2006f4799f35.png">

<img width="447" alt="bildschirmfoto 2016-10-29 um 00 43 32" src="https://cloud.githubusercontent.com/assets/68620/19824546/bfeae6aa-9d70-11e6-8018-a077f5835625.png">
#### Expected Behavior

Created pages should be shown in the list.
#### Steps to Reproduce
- I just have a basic setup. (https://github.com/digitaleinitiativen/vorarlberg.digital) which is a copy of a sulu standard project.
- I clone the repository.
- I run `composer install`
- I run `bin/adminconsole sulu:build dev`
- I login
- I create a Default page
- For a short time it shows the page in the content overview.
- Then it disappears.
- The API call /admin/api/nodes/8caa6324-dc2d-47f3-940a-52c552030a2e?webspace=vorarlberg-digital&language=de&fields=title,order,published&exclude-ghosts=false&exclude-shadows=false&&tree=true returns an empty list.
- /admin/api/nodes/8caa6324-dc2d-47f3-940a-52c552030a2e?webspace=vorarlberg-digital&language=de&fields=title,order,published&exclude-ghosts=false&exclude-shadows=false& returns something.
#### Possible Solutions

I don't know.

**Comment by danrot** [comment]
For the moment I would suspect the `-` in `vorarlberg-digital` to be the problem... But I must have a closer look at that. Probably won't make it today.

**Comment by wachterjohannes** [comment]
Seems also to be a problem if using `-` in the webspace-key.

**Comment by danrot** [comment]
That seems to be an upstream bug, seems to be related to [this issue](https://github.com/jackalope/jackalope-doctrine-dbal/issues/305).

**Comment by joemoe** [comment]
@wachterjohannes removing the `-` helped.
so for me it is fixed, as i don't really need `-` in a webspace-key.

**Comment by wachterjohannes** [comment]
@joemoe perfect (: but i think we should fix this in sulu directly.

**Comment by alexander-schranz** [comment]
related to #2882?

**Comment by wachterjohannes** [comment]
@alexander-schranz seems like this (:

**Comment by danrot** [comment]
@wachterjohannes Actually I think we should fix that in jackalope directly, if that is easily possible. I would like to avoid making our code more complicated because of a bug in another library.

**Comment by danrot** [comment]
Fixed with #3039
