### ISSUE TITLE
Little frontend colspan issue

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu#3010]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.0
| Browser Version | all browsers - window width issue

#### Actual Behavior

If you have a smaller window-size and the sulu-items positioned with colspan, than the media-element have overlaps.

#### Expected Behavior

No overlaping :)

#### Steps to Reproduce

Make two properties - as example text_editor with colspan 9 and media_selection with colspan 3.
Open sulu admin and take a look to it.

#### Possible Solutions

Only little fix with text-element on css. As example: add padding-left to text-span.
![bildschirmfoto 2016-11-02 um 13 55 37](https://cloud.githubusercontent.com/assets/8446518/19929857/cef2442a-a105-11e6-9140-248c6ead9df8.png)

**Comment by dmetzler1988** [comment]
also if you used other contents before and after colspan elements - padding is missing there and the width of elements are different :)

![bildschirmfoto 2016-11-02 um 14 12 25](https://cloud.githubusercontent.com/assets/8446518/19929992/73bc27fa-a106-11e6-9767-637c8d0abcf3.png)

**Comment by danrot** [comment]
The issue with the indentation of the article in your example will already be fixed with 1.4. For the overlapping of the text in the media selection there is already #2894. So I am closing this one as duplicate.
