### ISSUE TITLE
Overlay slides should be structured as tree

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#3013]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.*
| Browser Version | ---

#### Actual Behavior

Currently the overlay can only contain a list of slides in a linear structure. The problem with that is that if we have a structure like in the `media-edit-overlay`, where a user can jump to another slide directly. In this case it will slide over all the slides between the current and the target slide, which makes them visible for a short amount of time.

#### Expected Behavior

It should be possible to access the desired slide without sliding over another slide.

#### Steps to Reproduce

1. Navigation to a media collection
2. Click on an image
3. Click on the dropdown "Edit image" in the tab row
4. Select "Set focus point"
5. See that the slide for cropping will be visible for a short amount of time.

#### Possible Solutions

It would be nice to structure the slides in a tree structure. Then the overlay could also be used for workflows. This could look somehow like this:

```
      slide 1
     / 
root - slide 2
     \
      slide 3

```

slide 1, slide 2 and slide 3 can also have more children. The component has to be responsible for positioning the other slides correctly before sliding them into the visible part of the container, so that it doesn't have to slide over other slides.

**Comment by danrot** [comment]
@chirimoya Do we still need this? I thought this was mainly for the media overlay, which is not an overlay anymore.

**Comment by chirimoya** [comment]
we don't have slides anymore.
