### ISSUE TITLE
Warning in preview functionality

### ISSUE THREAD

**Issue by RonRademaker** [sulu/sulu#3016]
| Q | A
| --- | ---
| Bug? | perhaps
| New Feature? | unlikely
| Sulu Version | 1.3.0
| Browser Version | irrelevant

#### Actual Behavior

It gives a warning somewhere in the preview functionality (I'm seeing this in monitoring).

#### Expected Behavior

There is no warning

#### Steps to Reproduce

``` php
ron-macbook:sulu ron$ php -a
Interactive shell

php > include 'vendor/autoload.php';
php > $test = new Sulu\Component\Content\Document\Structure\PropertyValue('test', ['foo'=>'bar']);
php > $test['foo'] = 'bar';
PHP Warning:  array_merge(): Argument #1 is not an array in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90

Warning: array_merge(): Argument #1 is not an array in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90
```

#### Possible Solutions

I'm puzzled by the presence of ```array_merge``` but someone may need it to append items by setting them. If that's true, a simple test if ```$this->value[$offset]``` is an array (and initializing it to an empty array) would suffice. If the ```array_merge``` is a mistake to begin with (perhaps an incorrect way of assigning the value), it can be replace by a value assignment. 

By the way, this also disables any functionality to append new items to the value array:

``` php
php > $test['bar'] = 'bar';
PHP Notice:  Undefined index: bar in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90

Notice: Undefined index: bar in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90
PHP Warning:  array_merge(): Argument #1 is not an array in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90

Warning: array_merge(): Argument #1 is not an array in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90
```

Relevant line: https://github.com/sulu/sulu/blob/2e648cea065e1d146e580b83612b4c8729850938/src/Sulu/Component/Content/Document/Structure/PropertyValue.php#L90

**Comment by danrot** [comment]
TBH, I also don't know what this line is doing... From what I see that has been implemented by @wachterjohannes, maybe he can tell us what the thoughts behind this were.

**Comment by wachterjohannes** [comment]
@danrot @RonRademaker it was implemented for preview! i have created a PR with a fix which seems to work with preview also so maybe @danrot can review it
