### ISSUE TITLE
System Collection not able to load when created dynamically

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3026]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | `1.2.*, 1.3.*, 1.4.0`

#### Actual Behavior

I create for every entity a new system collection to store some data. Over the system collection manager it is not possible to load system collections which are not configured. 

#### Expected Behavior

It should also be possible to load system collections which are created dynamically.

#### Steps to Reproduce

Create a system collection:

```php
$this->collectionManager->save([
    'title' => 'New System Collection',
     'type' => ['id' => 2],
     'parent' => $rootCollectionId,
     'key' => $key,
     'locale' => $locale,
], null);
```

Try to load it:

```php
$this->systemCollectionManager->getSystemCollection($key)
```

#### Possible Solutions

Look into the database if a system collection with the `$key` exists.

**Comment by danrot** [comment]
When thinking about it... Why can't you configure the collections? If you allow them to be created dynamically we also can't cache them anymore...

**Comment by alexander-schranz** [comment]
@danrot if it not exists in the cache it can look for it in the DB and update the cache. The form bundle creates system collection per page based on the uuid of the page.

**Comment by danrot** [comment]
@alexander-schranz The problem with this solution is that it won't work on read-only filesystems 😕 And I think we'd like to be cloud ready. Isn't it possible to use a single system collection in the form bundle, and handle the child collections within that system collection, instead of creating one per page?

**Comment by alexander-schranz** [comment]
@danrot ok but the fallback to look into the database could be added so it is still fast for `static` system collection but can also load dynamically created system collection.

The form bundle has 2 Collection Strategies the `single` so all media is inserted in one system collection the behaviour you want and the `tree`. The tree is used by a content manager after a sweepstake with pictures ended to show all pictures with a media smart content provider by simple choice this collection.

**Comment by danrot** [comment]
@alexander-schranz I just don't get why you would need multiple system collections. Should also be possible to load the `root` collection and load the children based on its id. Would also make no difference in terms of performance as with your approach, but keep the system collection to a minimum. And we wouldn't have to include another case in the code, where we have to load collections from the database without hitting the cache.

**Comment by alexander-schranz** [comment]
@danrot just make it clear the Form Bundle use currently directly the collectionRepository and load the collection by its `key` there is no id.

But for me all collections which are created by the system are system collections and so they should be able to load over the system collection manager, else we should maybe rename in sulu 2.0 to StaticCollections /cc @chirimoya @wachterjohannes

**Comment by alexander-schranz** [comment]
As discussed the dynamic collections should be created as normal collection and loaded with the `$this->collectionRepository->findOneByKey($key)`
