### ISSUE TITLE
Use SSL Google Maps/Leaflet URL in SuluLocation

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#3029]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.1

#### Actual Behavior

Currently the google maps type in SuluLocationBundle ( https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/LocationBundle/Resources/public/js/map/google.js#L23 ) includes a non SSL variant of google maps.
When the backend is opened in https context it fails.

OSM Leaflet does the same

#### Expected Behavior

Include google maps based on current scheme

#### Steps to Reproduce

Access the backend over https and add a location property

**Comment by alexander-schranz** [comment]
duplicated with #3003

**Comment by danrot** [comment]
@alexander-schranz Please also use the duplicate label for stuff like this.
