### ISSUE TITLE
RouteManager `update` function should handle non conform URLs

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#3030]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.4.0
| Browser Version | 

#### Actual Behavior

When calling
```
$routeManager->update('/i`m a bad url~*@')
```

the url is stored as it is.
On the contrary, when calling `$routeManager->create($path)` the url is getting formatted.

#### Expected Behavior

When calling update I'd expect either
1. **an exception** to be thrown or
1. **the url to be parsed** like `/i-m-a-bad-url`

**Comment by danrot** [comment]
I would go for your second solution, so that it is working the same way as the `create` method.
