### ISSUE TITLE
No results for search when word has umlauts and is in the text_editor property

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#3036]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | all versions

#### Actual Behavior

if you enter umlauts into the text_editor it converts it into html umlauts (example. ö -> `&ouml;`)
now the "`&ouml;`" gets into the index and you can't find the word in the search.

Insprected with Luke - Lucene Index Toolbox
![bildschirmfoto 2016-11-16 um 13 47 18](https://cloud.githubusercontent.com/assets/8446502/20348029/f062ebb0-ac03-11e6-9f00-e6f05bad2e44.png)

Screenshot from Sulu Backend
![bildschirmfoto 2016-11-16 um 13 47 52](https://cloud.githubusercontent.com/assets/8446502/20348030/f27a5bae-ac03-11e6-82ed-d63d29a52c31.png)

#### Expected Behavior

Before indexing the html umlauts should be real umlauts again. (example. `&ouml;` -> ö)
so the "ö" gets into the index and we can find those words.

#### Steps to Reproduce

Add a site use text_editor property write a text with umlauts save and index. try to search for words with umlauts from the text.

#### Possible Solutions

Before indexing the html umlauts should be real umlauts again. (example. `&ouml;` -> ö)
so the "ö" gets into the index and we can find those words.

**Comment by jbfewo** [comment]
Wouldn't it be a more simple solution to set `config.entities = false ;` in CKEditor config to suppress the umlaut conversion.

**Comment by wachterjohannes** [comment]
@jbfewo at least we should give it a try.

**Comment by jbfewo** [comment]
As long it is not set as default by sulu, you could define it in your template.xml as a property param:
`<param name="entities" value="false"/>`

**Comment by wachterjohannes** [comment]
Maybe we should introduce this as a default value?

**Comment by danrot** [comment]
Fixed in #3087
