### ISSUE TITLE
Can remove content of url content type

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3045]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.1

#### Actual Behavior

Cant content remove external link (url content type). 

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

1. add a url conten type
2. create a page and add content to the url input and click save
3. try to remove the content and click save
4. refresh
5. content of the url content type is still here

#### Possible Solutions

Think null is sent to the controller and null values seem to be ignored. It should send an empty string instead.

**Comment by danrot** [comment]
Either this, or the controller handles the `null` value correctly.
