### ISSUE TITLE
fixed uncatchable exception when use sulu_content_load twig extension

### ISSUE THREAD

**Issue by trolink** [sulu/sulu#3050]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

What's in this PR?

Please check https://github.com/sulu/sulu/pull/2969, its kind a like the same issue but now its for sulu_content_load

When a page is deleted but the reference is still in a snippet, we are getting a exception. It would be nice the get null instead so we can check in Twig

Why?

You are not able to catch exceptions in twig.

Example Usage

{{  sulu_content_load(block.button_link).content.url }}

**Comment by dmetzler1988** [comment]
same issue on sulu version 1.6.5

**Comment by danrot** [comment]
#3649 should have fixed that 😃
