### ISSUE TITLE
Make "save and publish" dialog configurable

### ISSUE THREAD

**Issue by munxar** [sulu/sulu#3054]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.4.x

#### Actual Behavior

When I click "save and publish" a dialog appears to confirm my action.

#### Expected Behavior

I would love to configure that behavior to have a better UX.

#### Possible Solutions
make this dialog configurable like:

a) shows up like now
b) doesn't show up at all
c) doesn't show up, but gives me a toast in the header for e.g. 5 seconds where a could revert my action. in this case set status to unpublish.

I would give a) and c) the preference. c) would save one click per save without loosing the security.

**Comment by danrot** [comment]
@berndhep What do you think?

**Comment by berndhep** [comment]
@danrot Good idea but we should make all (sic!) dialogs customizable not only this one.

**Comment by danrot** [comment]
I don't have the feeling that we are going to implement that, therefore I am going to close this issue.
