### ISSUE TITLE
"php app/console massive:search:reindex --env=prod" Fails

### ISSUE THREAD

**Issue by placid2000** [sulu/sulu#3055]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | chrome

#### Actual Behavior

Running "php app/console massive:search:reindex --env=prod" command results on a fatal error:

provider "sulu_structure"

-- reindexing "19" instances of "Sulu\Bundle\ContentBundle\Document\HomeDocument"

  0/19 [>---------------------------]   0%
Fatal error: Call to a member function getLocalization() on null in /home/physiosw/public_html/production/vendor/sulu/sulu/src/Sulu/Component/Content/Compat/LocalizationFinder.php on line 40

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Error: Call to a member function getLocalization() on null

#### Steps to Reproduce
Run:
php app/console massive:search:purge --all
php app/console massive:search:reindex --env=prod

**Comment by wachterjohannes** [comment]
I am a bit confused of 19 home-documents! How have you configured your installation?

**Comment by placid2000** [comment]
What is a home-document? Do you mean webspaces? We have 17 of them. It's about an association having multiple unions. each with its own webspaces.

I not sure on how to answer your question. Can you be more specific?

**Comment by placid2000** [comment]
I did run redindex in verbose. This is the output:

`-- reindexing "372" instances of "Sulu\Bundle\ContentBundle\Document\PageDocument"

   0/372 [>---------------------------]   0% < 1 sec/< 1 sec 58.0 MiB[2016-12-02 08:50:51] doctrine.DEBUG: SELECT n0.path AS n0_path, n0.identifier AS n0_identifier, n0.props AS n0_props FROM phpcr_nodes n0 WHERE n0.workspace_nam                                                             e = ? AND n0.type IN ('nt:unstructured', 'rep:root') AND EXTRACTVALUE(n0.props, 'count(//sv:property[@sv:name="jcr:mixinTypes"]/sv:value[text()="sulu:page"]) > 0') LIMIT 50 OFFSET 50 ["default"]
[2016-12-02 08:50:51] doctrine.DEBUG:                SELECT * FROM phpcr_nodes               WHERE path = :path                 AND workspace_name = :workspace               ORDER BY depth, sort_order ASC {":path":"/cmf/sg_app_ph                                                             ysioswiss_ch [...]",":pathd":"/cmf/sg_app_physioswiss_ch [...]",":workspace":"default"}
[2016-12-02 08:50:51] doctrine.DEBUG: SELECT path, parent FROM phpcr_nodes WHERE parent IN (?) AND workspace_name = ? ORDER BY sort_order ASC [["/cmf/sg_app_physioswiss_ch [...]"],"default"]


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function getLocalization() on null


Exception trace:
 () at /vagrant/vendor/sulu/sulu/src/Sulu/Component/Content/Compat/LocalizationFinder.php:40
 Sulu\Component\Content\Compat\LocalizationFinder->findAvailableLocale() at /vagrant/vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/FallbackLocalizationSubscriber.php:118
 Sulu\Component\Content\Document\Subscriber\FallbackLocalizationSubscriber->getAvailableLocalization() at /vagrant/vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/FallbackLocalizationSubscriber.php:93
 Sulu\Component\Content\Document\Subscriber\FallbackLocalizationSubscriber->handleHydrate() at n/a:n/a
 call_user_func() at /vagrant/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:184
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /vagrant/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:46
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /vagrant/vendor/sulu/document-manager/lib/Collection/QueryResultCollection.php:85
 Sulu\Component\DocumentManager\Collection\QueryResultCollection->current() at /vagrant/vendor/sulu/sulu/src/Sulu/Bundle/ContentBundle/Search/Reindex/StructureProvider.php:105
 Sulu\Bundle\ContentBundle\Search\Reindex\StructureProvider->provide() at /vagrant/vendor/massive/search-bundle/Command/ReindexCommand.php:198
 Massive\Bundle\SearchBundle\Command\ReindexCommand->reindexClass() at /vagrant/vendor/massive/search-bundle/Command/ReindexCommand.php:148
 Massive\Bundle\SearchBundle\Command\ReindexCommand->execute() at /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:866
 Symfony\Component\Console\Application->doRunCommand() at /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /vagrant/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
`

**Comment by placid2000** [comment]
I have just run redindex with -vvv and got the following:

`"type":16384,"file":"/home/physiosw/public_html/production/vendor/twig/twig/lib/Twig/Template.php","line":690,"level":28928}
[2016-12-02 10:26:51] doctrine.DEBUG:                SELECT * FROM phpcr_nodes               WHERE path = :path                 AND workspace_name = :workspace               ORDER BY depth, sort_order ASC {":path":"/cmf/intranet_spitex_bern_ [...]",":pathd":"/cmf/intranet_spitex_bern_ [...]",":workspace":"default"}
[2016-12-02 10:26:51] doctrine.DEBUG: SELECT path, parent FROM phpcr_nodes WHERE parent IN (?) AND workspace_name = ? ORDER BY sort_order ASC [["/cmf/intranet_spitex_bern_ [...]"],"default"]

Fatal error: Call to a member function getLocalization() on null in /home/physiosw/public_html/production/vendor/sulu/sulu/src/Sulu/Component/Content/Compat/LocalizationFinder.php on line 40
`

This is no good because intranet_spitex_bern is no part of the project. it's another one.

**Comment by placid2000** [comment]
ok I delete the nodes in phpcr shell and some the spitex records are still remaining in phpcr_nodes table. But at least the reindex works
