### ISSUE TITLE
lang attribute on html tag not set automatically in preview mode

### ISSUE THREAD

**Issue by placid2000** [sulu/sulu#3056]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | Chrome

#### Actual Behavior

When clicking on the preview link on the top right. I get prompted to set a locale. It's about the locale that is set in the lang attribute on the <html> tag. Indeed the locale attribute gets wiped even if I hardcode it in the template.
Edit: I don't know why but it seems to work on a few homepages

#### Expected Behavior

The lang attribute should be set automatically in the preview and user should not be prompted.

#### Steps to Reproduce

Click on the preview link and check the <html> tag attributes

**Comment by danrot** [comment]
I cannot reproduce the issue... Can you think about stuff that the non-working pages got in common? How do you set this lang attribute on the html tag?

**Comment by danrot** [comment]
Closing since no further informations are given.
