### ISSUE TITLE
Emojis destroy usage of snippets

### ISSUE THREAD

**Issue by jbfewo** [sulu/sulu#3057]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | ~1.3
| Browser Version | -

#### Actual Behavior

I created a snippet which contains a 🤷 (the real utf8 emoji). This content seems to be saved to the data base but beyond this point I'm not able to use the whole snippets part of Sulu, because the emoji has been converted to �� which results in invalid json:

> Not a valid json object: 
> Request: GET http://localhost:8080/server/default/jcr:root/cmf/snippets/default/shrug.0.json 
> Response: 
> {"template":"default","i18n:de-creator":1,"jcr:uuid":"d109af2f-0c9c-49fd-976c-f6d602c610d4",":jcr:mixinTypes":"Name","jcr:mixinTypes":["sulu:snippet"],":i18n:de-published":"Date","i18n:de-published":"2016-12-02T15:17:05.000Z","i18n:de-title":"shrug",":i18n:de-created":"Date","i18n:de-created":"2016-12-02T15:17:05.000Z","i18n:de-changer":1,"i18n:de-state":2,":i18n:de-changed":"Date","i18n:de-changed":"2016-12-02T15:17:05.000Z","i18n:de-description":"<p>��</p>\n",":jcr:primaryType":"Name","jcr:primaryType":"nt:unstructured","::NodeIteratorSize":0}

If I try to reproduce this for normal contents, I got an error that it cannot be saved, but functionality isn't broken afterwards.
#### Expected Behavior

A 🤷 should be returned as a 🤷

#### Steps to Reproduce

Create a snippet with a 🤷

**Comment by danrot** [comment]
Can confirm this issue on jackalope-doctrine-dbal (looks like you are using jackrabbit, right?).

**Comment by danrot** [comment]
This is fixed with https://github.com/doctrine/DoctrinePHPCRBundle/pull/270. Therefore you also have to set the `utf8mb4` as described in http://symfony.com/doc/current/doctrine.html#configuring-the-database.
