### ISSUE TITLE
Template list not scrollable

### ISSUE THREAD

**Issue by dominikmatt** [sulu/sulu#3061]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.3.5

#### Actual Behavior
If screen height is not big enough the rest of the template-List will be hidden.

#### Expected Behavior
- Add a scrollbar to template-list
- I like to group templates like `Overview`, `Detailpages`, `Forms`, …

#### Steps to Reproduce
- Add many Templates

<img width="213" alt="bildschirmfoto 2016-12-05 um 10 07 16" src="https://cloud.githubusercontent.com/assets/3023954/20879143/a15d92da-bad2-11e6-8006-ce68e21ac769.png">

**Comment by alexander-schranz** [comment]
maybe the same as we had for the media formats we need to define a maxHeight: https://github.com/sulu/sulu/pull/2936

**Comment by danrot** [comment]
We still got he same problem in Sulu 2.0...

**Comment by danrot** [comment]
Fixed in #4929 and massiveart/husky#784
