### ISSUE TITLE
Add publisher for settings tab changelog

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3062]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.4

#### Actual Behavior

Currently don't see who publish the page or is the same as the changer?

#### Expected Behavior

The publisher and the changer could be 2 different persons and this should be listed in the settings tab changelog.

#### Possible Solutions

Save publisher and show on the settings tab.

![bildschirmfoto 2016-12-05 um 11 30 59](https://cloud.githubusercontent.com/assets/1698337/20881846/8b787460-bade-11e6-9b07-79b969ce86eb.png)

Maybe we need to add a new api endpoint that changer/publisher is not the same.

**Comment by danrot** [comment]
This will be addressed in my versioning PR. This section will change anyway:
![image](https://cloud.githubusercontent.com/assets/405874/21135144/0e4caa9e-c121-11e6-9126-efa177debac7.png)

The publisher is then also the person who created the version, since these two things are connected.
