### ISSUE TITLE
internal link page can't be set to "unpublished"

### ISSUE THREAD

**Issue by mruetzler** [sulu/sulu#3063]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.2
| Browser Version | Chrome Version 54.0.2840.98 (64-bit)

#### Actual Behavior

How does Sulu behave at the moment? 
If you choose on the internal link page "unpublish" the page changes to test mode (yellow dot).
In the structure, however, the page shows a green and yellow label. On the frontend the page stays published.

#### Expected Behavior

The internal link page should be unpublished as soon as the mode is changed to "unpublished". Also in the structure the correct label should show (yellow dot only).

#### Steps to Reproduce

See actual behavior

**Comment by danrot** [comment]
The page is not staying published on the website, I think what you are experiencing is the browser cache. But I'll have a look at the other thing with the browser cache.
