### ISSUE TITLE
Sulu Admin: Sulu version / Project version

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3064]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

#### Actual Behavior

At the moment the version is displayed in the left bottom corner. This is read out of `composer.json`.
Also theres a link to the changelog of sulu on github.

#### Expected Behavior

In my opinion it would be nice if there would be a second line for the project version and a own link to a changelog. This should then be read out of the project `composer.json`. Also the sulu version should read out from `vendor/sulu/composer.json`

**Comment by wachterjohannes** [comment]
we should extract the sulu version from composer.lock

**Comment by trickreich** [comment]
yes, also fine :)

**Comment by alexander-schranz** [comment]
@wachterjohannes would always when possible access the files inside bundle where we are sure they exist at this path in this case vendor/sulu/sulu/composer.json.

**Comment by danrot** [comment]
@alexander-schranz When doing this the value should not be hardcoded but considering the vendor-dir as in https://github.com/sulu/sulu/pull/1721. Reading from `composer.json` should be fine, but it should really not be the one in sulu-standard/sulu-minimal, since we do not advice to pull anymore, and the version number will definitely be wrong then.

**Comment by wachterjohannes** [comment]
in the file `vendor/sulu/sulu/composer.json` is no version number. we only manage our version-number in the tag name. so the only place we have the version-number is `composer.lock`

**Comment by trickreich** [comment]
@wachterjohannes @danrot This topic popped up again.

**Comment by trickreich** [comment]
@wachterjohannes @danrot @alexander-schranz 
As alex noticed in the PR: For me its also necessary to provide the option to show the app version in the backend.

**Comment by danrot** [comment]
@trickreich If the app version is more important for you, you can still override the service definition of the `AdminController` and pass the `app.config` parameter. We decided that showing two different versions is confusing for the user in most cases.
