### ISSUE TITLE
value of mailto scheme in url content type is empty after save and cache clear

### ISSUE THREAD

**Issue by RaphaelHofer** [sulu/sulu#3077]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.4
| Browser Version | Chrome Version 54.0.2840.98 (64-bit)

#### Actual Behavior

Value of `mailto` in block is empty after cache clear in settings menu and the scheme is set to ?`http://`

#### Expected Behavior

Value and scheme stays after save and cache clear.

#### Steps to Reproduce

Create a block with a block type with this property:
```
                     <properties>
                        <property name="url" type="url">
                            <meta>
                                <title lang="de">Link</title>
                                <title lang="en">Link</title>
                            </meta>

                            <params>
                                <param name="schemes" type="collection">
                                    <param name="http://"/>
                                    <param name="https://"/>
                                    <param name="mailto:"/>
                                </param>
                            </params>
                        </property>
                    </properties>
```

**Comment by danrot** [comment]
Is this a good idea at all? The email can only be sent this way, and if you want the email on its own, you have to strip the `mailto:` part away somehow... Why don't you simply use the [Email content type](http://docs.sulu.io/en/latest/reference/content-types/email.html) and add the `mailto:` in the template where you need it?

**Comment by RaphaelHofer** [comment]
i don't have to strip the mailto: part away, because we are showing icons based on the url we add like facebook, linkedin etc. and i would have to add additional logic for using the right icon. If i use it this way, i can just iterate over the array and pick the right one.

**Comment by rflorent** [comment]
In some case, we can't simply use the email content type, like when you need to add some arguments :
mailto:contact@sulu.io?subject=lorem ipsum

For example, I use a snippet with blocks. The user can add links, with the following content type per blocks :
icons type (radio)
label (text)
url 

So I use url content type with the mailto scheme because it is more flexible and I'm facing this issue.
Now, my solution is to use a text line content type instead of a url, and add the scheme manually.

**Comment by danrot** [comment]
This is now possible in Sulu 2.0 :tada:
