### ISSUE TITLE
Cannot publish page document after upgrading from 1.4.1 to 1.4.2

### ISSUE THREAD

**Issue by mechpave** [sulu/sulu#3081]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2

#### Actual Behavior

Page document cannot be published after upgrading from 1.4.1 to 1.4.2. An exception is thrown on the publish event.
An exceprion is thrown after persist method is called in Sulu\Component\Content\Types\ResourceLocator\Mapper\PhpcrMapper::save()

> [Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException]
> The option "override" does not exist. Defined options are...

#### Steps to Reproduce
Try to publish a page document:
> $document = $documentManager->create('page');
> $documentManager->publish($document, 'en');

Or publish a page in the admin panel.

**Comment by wachterjohannes** [comment]
are you sure that you also have updated the `sulu/document-manager`?

**Comment by mechpave** [comment]
That's right, id didn't update `sulu/document-manager`.
But since new version of `sulu/sulu` requires an update of another dependency, shouldn't it reflect this requirement in `composer.json`?
The thing is that I only wanted tu upgrade sulu: `composer update sulu/sulu`, so the version of `sulu/document-manager` stayed the same.

**Comment by wachterjohannes** [comment]
thats right(: we will add this constraint into the next release. Sorry for the circumstances.

**Comment by danrot** [comment]
Was fixed by #3085
