### ISSUE TITLE
Media format not purge when incorrect extension

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3086]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4, 1,3, ...

#### Actual Behavior

When you upload a media on a case sensitive file system (e.g. Ubuntu) with `.JPG` it is not purged correctly because it is saved as `.jpg` same is for `.pdf` which is not purged because it tries to purge `.pdf` file instead of `.jpg`.

#### Expected Behavior

The file with the correct extension need to be deleted on purge.

#### Steps to Reproduce

1. Upload file with `.JPG`
2. Load specific format
3. Crop specific format
4. Load specific format again the old crop is still shown.

#### Possible Solutions

`replaceExtension` is missed in `FormatManager::purge` function this needs a BC Break because the mimeType is required.

**Comment by danrot** [comment]
Fixed by #3090
