### ISSUE TITLE
Change URL of Site to one existing in history

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3089]
| Q | A
| --- | ---
| Bug? | no/yes
| New Feature? | no/yes

#### Actual Behavior

When changing the URL of a Sulu site to one which exists in history, the backend crashes and returns a 500 error.

#### Expected Behavior

To be discussed.

**Comment by danrot** [comment]
I would say the existing URL should be reused. Maybe an overlay should explain what's happening and ask for confirmation, but I think that's not necessary.

**Comment by trickreich** [comment]
But just when the existing URL was on the same page, this can also happen that the a other page had this name, or I am wrong?

**Comment by danrot** [comment]
That's what I meant 😃

**Comment by danrot** [comment]
In the mean time the API returns a 409, which is correct IMO.
