### ISSUE TITLE
Open category tree in excerpt title jumps when showing loader

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3096]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4

#### Actual Behavior

![open-category-excerpt](https://cloud.githubusercontent.com/assets/1698337/21262705/fdd58afe-c392-11e6-9664-39c1777dfcc6.gif)

#### Expected Behavior

When the loader is shown the title should stay at the same line.

#### Steps to Reproduce

Open a category tree which was not opened before in the excerpt tab.

**Comment by danrot** [comment]
Which browser are you using? This is not happening on Chrome 54.0.2840.98 for me.

**Comment by danrot** [comment]
Fixed in https://github.com/massiveart/husky/issues/759
