### ISSUE TITLE
PHPUnit 5.x

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#3105]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | since PR #3097
| Browser Version | none

#### Actual Behavior

With the changes of this PR #3097 we have some strange behaviour where the phpunit process breaks with a `Segmentation fault (core dumped)` at the end of the passing tests. This breaks the build process and turn it to red.

* https://travis-ci.org/sulu/sulu/jobs/185225440

#### Expected Behavior

The tests should run without segfault and green result (:

#### Steps to Reproduce

Create a PR and change the dependency of phpunit to a 5.x version.

**Comment by danrot** [comment]
phpunit has been updated in #3931, so closing this issue
