### ISSUE TITLE
Ckeditor special character crash page

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3106]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-develop
| MySQL Version | 5.5, 5.6 (utf8_unicode_ci)

#### Actual Behavior

When insert the following in the ckeditor on:

```
<p>&#127876;</p>
```

CKEditor transform it to when clicking back to source.

```
<p>🎄</p>
```

When saving now on 5.6 Mysql you will get an Update error. On 5.5 Mysql it inserts an incomplete xml and the page crash and can never edit again.

#### Expected Behavior

It should save the texteditor as `<p>&#127876;</p>` and not as `<p>🎄</p>`

#### Steps to Reproduce

See Actual Behavior.

#### Possible Solutions

Maybe there is any option dont convert the unicode icons to the real icons.

**Comment by jbfewo** [comment]
#3057

**Comment by danrot** [comment]
I've been thinking about this, and came to the conclusion that these emojis should actually work... I'd say even our REST API should be capable of understanding them. If the database we use has a problem with storing them, we should encode/decode the values somewhere on the server side. WDYT?

**Comment by danrot** [comment]
Short update: The UTF8-encoding of MySQL is a small subset... The encoding we need is `utf8mb4`, and I can simply set it using some DBAL configuration. That's also described in the [Symfony documentation](http://symfony.com/doc/current/doctrine.html#configuring-the-database).

However, when setting this, the PHPCR tables are the only ones not created with the `utf8mb4` charset. There seems to be some bug in jackalope I am now looking into.

**Comment by danrot** [comment]
A combination of https://github.com/jackalope/jackalope-doctrine-dbal/pull/337 and https://github.com/doctrine/DoctrinePHPCRBundle/pull/270 should fix this, but these are currently just prototypes. Will have to wait for some feedback before I can finish this.

**Comment by danrot** [comment]
Fixed upstream in doctrine/DoctrinePHPCRBundle#270, will be fixed with their next release.
