### ISSUE TITLE
Image cropping with only width set does not work

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#3114]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | Browser name and version

#### Actual Behavior
When having some image format, which should only limit the width of an image to e.g. 500 px it uses the whole height of the image.
![crop_area](https://cloud.githubusercontent.com/assets/3419968/21386252/3aa4be7c-c772-11e6-9cff-5dc11fc43855.png)

Using e.g. this image https://placeholdit.imgix.net/~text?txtsize=288&txt=3840%C3%975760&w=3840&h=5760

#### Expected Behavior
The editor should be able to crop that image to the desired width (500 px) but not be limited in height.

#### Steps to Reproduce

Define some image format with only `width` defined and open that image format in the "cropper".
That should look like the screen above

**Comment by reflexxion** [comment]
I think the only problem here is:
https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/MediaBundle/Resources/public/js/components/area-selection/main.js#L204

**Comment by danrot** [comment]
Fixed in #3138
