### ISSUE TITLE
Automation info: Permission failure

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#3117]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | e720328e2c74d945898c7239eed732d0395785c3
| Browser Version | all

#### Actual Behavior

The Automation-info calls a rest API which is secured without checking the security. Therefor the request fails if you have no permissions.

#### Expected Behavior

Don't see a failing request.

#### Steps to Reproduce

Create an automation on the page and remove the view permissions for automation.

#### Possible Solutions

Two possibilities if you have no permissions on automation:

* Dont see the info and do not do the request.
* See the info and create an unsecured api for this especially request.

**Comment by danrot** [comment]
The automation-info does not exist in this repo anymore, therefore going to close this issue.
