### ISSUE TITLE
Imagecropping while editing or creating an object wont work

### ISSUE THREAD

**Issue by Jace25** [sulu/sulu#3119]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | Chrome for Mac 55.0.2883.95 (64-bit)

#### Actual Behavior

While you are editing or creating a new page or blog entry it is possible to choose images with the media selection [contenttype](http://docs.sulu.io/en/latest/reference/content-types/media_selection.html).

It is also possible to edit this images:
![image](https://cloud.githubusercontent.com/assets/4090694/21526743/be021e54-cd26-11e6-9c28-6d51f12cd5ae.png)

But if i try to edit some of the image formats all i got is:
![image](https://cloud.githubusercontent.com/assets/4090694/21526767/e9a922c8-cd26-11e6-9c6f-959ab0a71773.png),

also some formats are marked with a warning:
![image](https://cloud.githubusercontent.com/assets/4090694/21526793/137e3e26-cd27-11e6-9634-95b8011886a6.png)

But, when i edit the same image from the media library everything works fine and also the warning is gone:
![image](https://cloud.githubusercontent.com/assets/4090694/21526805/2710da70-cd27-11e6-9574-e9bba1252784.png)

Maybe the dimension calculations when editing an image while creating new content are based on 
the wrong image(size)?
#### Expected Behavior

Editing this image should be possible, no matter from which "parent" view i try to edit it.

#### Steps to Reproduce

See actual behavior description.

**Comment by danrot** [comment]
Fixed in #3139
