### ISSUE TITLE
Sulu link tag is not generate when the title contains a slash

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu#3123]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2

#### Actual Behavior

Sulu link tag is not rendered when the title of the link contains a slash

#### Expected Behavior

It should be rendered as a link

#### Steps to Reproduce

Create a internal link in a rich editor, whit a title containing a slash

**Comment by reflexxion** [comment]
Hi @rflorent,

can you confirm, that this issue is a dup of #2786 and will be solved in #3094 ?

Regards

**Comment by wachterjohannes** [comment]
@rflorent we have refactored the markup component completely for version 1.5. This should fix your problems => could you please try your issue with the current dev-develop? we will release it in january

**Comment by wachterjohannes** [comment]
@reflexxion i would say for the given informations it is a dup of #2789 and should be fixed by the PR #3094

**Comment by wachterjohannes** [comment]
@rflorent if it is not fixed with dev-develop please reopen this issue.

**Comment by rflorent** [comment]
@wachterjohannes yes this should be fixed by the pr, thanks
