### ISSUE TITLE
Wrong default Focus-Point 

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#3124]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | yes
| Sulu Version | 1.4

#### Actual Behavior

Currently the default focus point is Top / Left.
Probably that is a bug because the "JS-Overlay" defaults on center.
So there is some inconsistency.

The `switch` in https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Focus/Focus.php#L62 and https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Focus/Focus.php#L78 will point to top and left if no `$x` / `$y` was set.
PHPs `switch` implementation uses [loose comparison](http://php.net/manual/en/types.comparisons.php#types.comparisions-loose) . So the first case for `0` will match `null` 

#### Expected Behavior

The default focus point should point to center or be configurable

#### Steps to Reproduce

Uploading some new image will crop the top / left portion of the image. 

#### Possible Solutions

The best way probably is to add some default focus point (global and / or per format).

**Comment by danrot** [comment]
@reflexxion Thanks for the detailled description. Will be fixed with #3134, and for such a small change you could as well have created a PR 😉

**Comment by reflexxion** [comment]
Indeed - Sorry! ;)

**Comment by danrot** [comment]
Fixed in #3134
