### ISSUE TITLE
Smartcontent limit 0 returns every selected page

### ISSUE THREAD

**Issue by RaphaelHofer** [sulu/sulu#3125]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2 - probably all
| Browser Version | all

#### Actual Behavior

Sulu returns all pages which are selected with the smart-content.

#### Expected Behavior

Return 0 pages.

#### Steps to Reproduce

Set the limit of any smart-content to 0.

**Comment by danrot** [comment]
I think there needs a way to return all entries, and entering 0 does not make any sense to me anyway... Therefore closing this issue.
