### ISSUE TITLE
Avoid setting HTML headline tags in text editor

### ISSUE THREAD

**Issue by janmassive** [sulu/sulu#3129]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no

#### Actual Behavior

If a user edits text within a Sulu text block, headlines can be set via the dropdown menu. This results in creating HTML tags (```<h1>```,...) around the selected text. Since most of all users do not have enough knowledge about HTML's structure, that leads to W3C invalidity.

#### Possible Solutions

The editor settings could be overwritten to add a div tag with respective classes around the selection (for example ```<div class="headline-first">...</div>```).

**Comment by alexander-schranz** [comment]
For 2.0 this is planned and for 1.0 you can disable the h1 dropdown in setting for a specific group. and add custom tags see: https://github.com/sulu/sulu-docs/issues/320

**Comment by alexander-schranz** [comment]
@chirimoya should we tag this for 2.0?

**Comment by danrot** [comment]
In 2.0 we decided not to have a `h1` by default, so this problem does not exist anymore. Creating a div tag instead of a proper heading is not really an option IMO.
