### ISSUE TITLE
Unable to create pages in other languages

### ISSUE THREAD

**Issue by mtnorthrop** [sulu/sulu#3143]
| Q | A
| --- | ---
| Bug? | Maybe?
| New Feature? | no
| Sulu Version | 1.4.4
| Browser Version | 

#### Actual Behavior

Hello, I'm trying to set up a multilingual Sulu site and I'm having trouble getting my second language working. I've set my localizations in my webspace file like this:

```
    <localizations>
        <localization language="en" default="true"/>
        <localization language="sk"/>
    </localizations>
```

I've run the `bin/websiteconsole sulu:document:initialize` command, but when I try to create a new page for the `sk` language an exception is thrown when the slug is supposed to be generated. 

The URL for this AJAX request is `http://localhost:8000/admin/api/nodes/resourcelocators/generates?language=sk&template=default&webspace=mywebspacekey` and the response I get is a 500 error with this message: `Item /cmf/mywebspacekey/routes/sk not found in workspace default`.

However, I've been able to create and edit the homepage for the `sk` language without a problem.

Does anybody have any suggestions as to what the problem might be and how I might fix it?

**Comment by alexander-schranz** [comment]
@mtnorthrop you need to create the route nodes with the `sulu:document:initialize` command its missing in the docs and only documented in the adding a new webspace. http://docs.sulu.io/en/latest/cookbook/create-new-webspace.html

**Comment by mtnorthrop** [comment]
@alexander-schranz , thanks for your response.

I've tried clearing the cache and then running `sulu:document:initialize` in both the `adminconsole` and the `websiteconsole`, but it does not seem to help.

This is the output that I get when I run the command:
```
16:09 $ bin/websiteconsole sulu:document:initialize
sulu_document_manager.initializer.workspace
  [ ] workspace: "default"
  [ ] workspace: "default_live"
sulu_document_manager.initializer.root_path_purge_initializer
  [ ] Purging workspaces
sulu_content.document_manager.content_initializer
  content namespaces:
  [ ] sulu:http://sulu.io/phpcr
  [ ] sec:http://sulu.io/phpcr/sec
  [ ] settings:http://sulu.io/phpcr/settings
  [ ] i18n:http://sulu.io/phpcr/locale
  content node types:
  [*] sulu:base
  [*] sulu:path
  [*] sulu:content
  [*] sulu:snippet
  [*] sulu:page
  [*] sulu:home
  content namespaces:
  [ ] sulu:http://sulu.io/phpcr
  [ ] sec:http://sulu.io/phpcr/sec
  [ ] settings:http://sulu.io/phpcr/settings
  [ ] i18n:http://sulu.io/phpcr/locale
  content node types:
  [*] sulu:base
  [*] sulu:path
  [*] sulu:content
  [*] sulu:snippet
  [*] sulu:page
  [*] sulu:home
sulu_core.webspace.document_manager.webspace_initializer
  [ ] homepage: /cmf/ftmaudit/contents (en)
  [ ] homepage: /cmf/ftmaudit/contents (sk)
sulu_snippet.document.snippet_initializer
  [ ] snippet path:: /cmf/snippets 
sulu_custom_urls.initializer
  FTM Audit:
  [ ] items path:: /cmf/ftmaudit/custom-urls/items 
  [ ] items path:: /cmf/ftmaudit/custom-urls/routes 

* Legend: [+] Added [*] Updated [-] Purged [ ] No change
```

I feel like I'm missing something very basic, but I'm not familiar enough with Sulu to know where to look...

**Comment by alexander-schranz** [comment]
@mtnorthrop hmm did you add the permission for the new locale. after adding a new locale you need to give your user permissions for it in the `Contact` -> `Your Contact` -> Permisson tab.

**Comment by alexander-schranz** [comment]
@mtnorthrop you can also use `bin/console doctrine:phpcr:shell` and check after running the initialize command if `cd /cmf/mywebspacekey/routes` the locales exists

**Comment by mtnorthrop** [comment]
@alexander-schranz Yes, the permissions have been added. I'm able to switch to `sk` in my webspace's Content area and click on the create button to open the Add Content form, but when I enter a title, and then click on the URL field where the slug is automatically generated for `en` pages, the Symfony debug bar shows an AJAX error caused by this exception: `Item /cmf/ftmaudit/routes/sk not found in workspace default`.

I've just checked the `doctrine:phpcr:shell` as you suggested and I only have `en` under `/cmf/ftmaudit/routes/`.

Just our of curiosity, does it make a difference whether I'm using the `adminconsole` or `websiteconsole` for these commands?

**Comment by alexander-schranz** [comment]
@mtnorthrop yes on admin it is an own workspace used. so when a page is created it is created in the admin workspace normally `default` when it is published it will copy this document from `default` to `default_live` (Publishing process). 

If you defined the locales in your portal section check if you did also add it to the top and to this portal in your webspace xml.

**Comment by mtnorthrop** [comment]
@alexander-schranz I'm not sure if my portal section is correct... This is what I have:
```
    <portals>
        <portal>
            <name>FTM Audit</name>
            <key>ftmaudit-portal</key>

            <environments>
                <environment type="prod">
                    <urls>
                        <url>{host}/{language}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url>{host}/{language}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url>{host}/{language}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
```

Am I missing a setting here?

**Comment by alexander-schranz** [comment]
@mtnorthrop no if you dont have <localization> tag inside the portal it should work correctly. Was a homepage created in the `sk` locale?

**Comment by mtnorthrop** [comment]
@alexander-schranz Yes, I have an `sk` homepage published, and it works fine when I go to `localhost:8001/sk`

**Comment by alexander-schranz** [comment]
@mtnorthrop the homepage works in the admin?  

can you try to remove `sk` node with the phpcr shell  in BOTH workspaces:

```
/cmf/<your>/routes
rm sk
save
refresh
```

 and the run `bin/adminconsole sulu:document:initialize` again.

**Comment by mtnorthrop** [comment]
@alexander-schranz 

I seem to have solved the problem. I tried running `bin/adminconsole sulu:document:initialize --purge` and this seems to have done the trick. I don't know what caused the system to get stuck with only English, but initializing the doc store using the **--purge** flag has fixed it and now everything is working fine.

Thank you again for all your time answering my questions and helping me find the solution!

**Comment by ReggieCaiShanghai** [comment]
Waring:
befor you do 
bin/adminconsole sulu:document:initialize --purge 
save you datebase!
IF bin/adminconsole sulu:document:initialize not work maybe this help:

I find the fact is that your miss the locale in you database. (for me the locale is fr). This is why there is no router find in the /cmf/ftmaudit/routes.
So what you need to do is add the locale you miss in table "phpcr_nodes" and "phpcr_nodes_references".
1. table "phpcr_nodes"
you can copy this form the other locale, but need to replace the lcoale, what I do is copy form my VM(yes, things always works in VM but not in prod ...)
As It have both default_live and default you need inset 2 for your locale
2 table "phpcr_nodes_references"
 you need to add 2(one for default_live  and the other for default) 
the source_id is the new lcoale id from phpcr_nodes 
and the target_id is the  id form phpcr_nodes  where parent="/cmf/asiaqualityfocus"
the source_property_name is "sulu:content"
Wow, I did these and it works !
Hope could help someone else have the same problem.(Still I don't know why bin/adminconsole sulu:document:initialize not work ..)
