### ISSUE TITLE
Audience targeting / Adaptive content

### ISSUE THREAD

**Issue by chirimoya** [sulu/sulu#3148]
### Proposal
It should be possible to **manage audience target groups** and the secondary content of a page or article should **adapt depending on the visitors target group**. By **secondary content** we mean all referencing or embedding content types e.g. smart-content, teaser-selection, internal-links or snippets. This content types need to be extended by a filter mechanism to accomplish the adaptive content behavior. To what extent and how a content manager needs to be able to enable or disable the adaptive content behavior needs to be defined. 

Beside the content management part of this feature there needs to be a mechanism to **determine the target group of a visitor**. Traditionally the is based on behavioral, geographic and demographic information of the visitor.

#### Behavioral targeting (interaction on the website)
 - Downloads
 - Form submits
 - Action buttons
 - Landing page (Campaign)
 - ...

#### Geographic targeting
 - Location based (IP2location)

#### Demographic targeting (only available for registered visitors)
 - Age
 - Gender
 - Education
 - Marital status
 - ...

Additionally on websites we could also take the referrer and the used device into account to determine
the target group of the visitor.

There should be some kind of rule-set management which uses the defined criterias to determine the target group of unknown visitors.

It would also be conceivable to offer the visitor a wizard to determine his target group by him self. (e.g. https://www.graubuenden.ch/de)

Recurring Users should be recognized to not lose their target group determination.

### Open questions
Can a visitor be associated with more than one target group?
Is it possible to change the target group of a visitor based on his behavior?
Are target groups organized in a tree structure?

### User Stories
- As a content manager I want to be able to manage (create, edit & delete) target groups.
- As a content manager I want to reference content (pages, snippets & articles) to one or more target groups.
- As a content manager I want to be able to configure the smart content to make use of the target group of a visitor.
- As a developer I want to have a group based http cache. One cache for each target group.
- ...

**Comment by berndhep** [comment]
Great summary, thanks @chirimoya! 

From a SEO point of view we should also discuss how much content on a page can be adaptive before we loose search engine visibility. Maybe we should talk with Jens about this.

We also need to think about the live preview in the admin. It should be possible to view the content for selected target groups while managing the page.
