### ISSUE TITLE
Content Type Default Params not in twig template

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#315]
When I create a new complexContentType. I can set an array of defaultParams in the getDefaultParams function. In the twig content type template only the params which were defined in the ContentTemplate appear.

**Comment by alexander-schranz** [comment]
@danrot only get the params which where set in the xml not this who are not set there

**Comment by danrot** [comment]
@alexander-schranz Can you explain in more detail what's wrong here?

**Comment by alexander-schranz** [comment]
When create a **complex content type** with defaultParams e.g.:

```php
    public function getDefaultParams(PropertyInterface $property = null)
    {
        return [
             'param1'  => 123,
             'param2'  => 345,
             'param3'  => 678,
        ];
    }
```

```xml
       <property name="custom" type="my_type">
            <meta>
                <title lang="de">Custom</title>
                <title lang="en">Custom</title>
            </meta>

            <params>
                <param name="param3" value="555" />
            <params>
       </property>
```

Then `params` did not contain the default values in the content type twig template: 

```twig
    {{ dump(params) }}
```

# Current Result:

```json
{
     "param3": "555"
}
```

# Expected Result:
```json
{
     "param1": "123",
     "param2": "456",
     "param3": "555"
}
```

`param1`, `param2` with values are missing.

@danrot but I'm not sure if this still exist

**Comment by alexander-schranz** [comment]
@danrot maybe the issue was on my side that I did access `property.params` instead of `params`?

**Comment by danrot** [comment]
Not sure... Can you try and close the issue if you are right about that?

**Comment by alexander-schranz** [comment]
yeah `property.params` only include the xml values and `params` also have the default values
