### ISSUE TITLE
Missing information - If somebody creates a sulu admin without choosing a language the user is not allowed to use the full backend.

### ISSUE THREAD

**Issue by uwangerin** [sulu/sulu#3152]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

If somebody creates a sulu admin without choosing a language the user is not allowed to use the full backend.
At the first sight it seems to be an error of the backend because there is no notice or warning message that choosing a language is necessary.  

#### Expected Behavior

The user is allowed to use the full backend without a selected language.

#### Steps to Reproduce

Create a new user with sulu admin permissions and do not choose a language.
The user should not be allowed to use the full backend now.

#### Possible Solutions

If it is important to choose a language, the selection should be required, and you should not be able to save your changes. Otherwise there could appear a warning message or a notice that a selection of the language is necessary for having sulu admin permissions.

**Comment by wachterjohannes** [comment]
@berndhep what do you think about that?

**Comment by danrot** [comment]
Interesting thought... however, that might not be true on your custom web application, depending how you are implementing the security part. Question is if we want to support that.

**Comment by danrot** [comment]
I've just tested it, if you do it like this now, it will only show forbidden screen if a localization is required. E.g. the contacts are working.
