### ISSUE TITLE
Update fos/rest-bundle

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#3153]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | ^1.4
| Browser Version | all

#### Actual Behavior

We currently use the configuration value `exception_handler` which will be removed with `fos/rest-bundle: ^2.0`. We have to find an alternative for that.

See PR there: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1358

**Comment by stijndm** [comment]
Hi,

I'm currently looking into the feasibility of this so we can use Sylius (requires fos/rest-bundle ^2.1) alongside Sulu. Are there any other changes to account for (https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/UPGRADING-2.0.md)?

Do you think this will require a lot of effort?

Thanks

**Comment by wachterjohannes** [comment]
we have already updated fos/rest-bundle in develop (see https://github.com/sulu/sulu/blob/develop/composer.json#L26) additionally i have also worked for a prototype to integrate sylius product bundle in the new 2.0 UI (which will be released next year) https://github.com/sulu/sulu/pull/3625 https://github.com/sulu/sulu-minimal/pull/76

**Comment by stijndm** [comment]
Wow, this sounds great!
