### ISSUE TITLE
Deleting a page which is linked with a smartcontent breaks the homepage

### ISSUE THREAD

**Issue by placid2000** [sulu/sulu#3156]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.4
| Browser Version | any

#### Actual Behavior

I have set a smartcontent block on the homepage. I set the source of the smartcontent to specific content page. Then I deleted that specific page. 

By requesting the homepage I got following error:
Item b8d3f9e6-b6dc-4b6f-a9fd-04a582a1c3ca not found in workspace default_live.

Everything worked again as I deleted the smartcontent block on the hompage. (Reseting the source of SC would probably have worked too)

#### Expected Behavior

As smartcontent was still looking for an none existing page, we might just remove its source when deleting page the SC is pointing to.

**Comment by danrot** [comment]
fixed by #3170
