### ISSUE TITLE
Wrong SEO Information for hreflang tag

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#3163]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2

#### Actual Behavior

When using the `SuluWebsiteBundle:Extension.seo.html.twig` file to display meta information for the page, the `<link rel="alternate"...` information is wrong when the page has multiple locales.

There's also printed one `<link rel="alternate"...` tag for the current language + the x-default link.

#### Expected Behavior

That the meta information is correct and no alternate tag for the current locale is defined, except the x-default link.

#### Steps to Reproduce

Use the `seo.html.twig` file:

```twig
{%- embed 'SuluWebsiteBundle:Extension:seo.html.twig' with {
        seo: extension.seo,
        content: content,
        urls: urls|default([]),
        shadowBaseLocale: shadowBaseLocale|default(''),
        defaultLocale: request.defaultLocale|default('')
    } -%}
```

#### Possible Solutions

Instead of

```twig
{%- if urls|length > 1 -%}
    {%- for locale, url in urls -%}
        {%- if defaultLocale == locale -%}
            <link rel="alternate" href="{{ sulu_content_path(url, null, locale) }}" hreflang="x-default"/>
        {%- endif -%}
        <link rel="alternate" href="{{ sulu_content_path(url, null, locale) }}" hreflang="{{ locale }}"/>
    {%- endfor -%}
{%- endif -%}
```

This could be the solution:

```twig
{%- if urls|length > 1 -%}
    {%- for locale, url in urls if locale != app.request.locale -%}
        <link rel="alternate" href="{{ sulu_content_path(url, null, locale) }}" hreflang="{{ locale }}"/>
    {%- endfor -%}
    <link rel="alternate" href="{{ sulu_content_path(urls[defaultLocale], null, defaultLocale) }}" hreflang="x-default"/>
{%- endif -%}
```

**Comment by alexander-schranz** [comment]
@thomasduenser if I read https://support.google.com/webmasters/answer/189077 I'm not sure if we should set `x-default`. But something we need to change because the sitemap has an other behaviour currently as the html twig.

**Comment by danrot** [comment]
@thomasduenser What do you mean by the meta information is not correct? are you only talking about the x-default tag?

**Comment by alexander-schranz** [comment]
@danrot currently it seems inconsistent to the sitemap.xml

when having `de` and `en` and `de` ist the default locale in the sitemap only:

```
x-default: /de
en: /en
```

ist rendered on the page itself in the meta tags it will do

```
x-default: /de
de: /de
en: /en
```

@thomasduenser it solution would remove the `de: /de` then so it is the same as the sitemap.
@thomasduenser @c00n84 did you talk with the SEOs which one is correct?

**Comment by danrot** [comment]
From what I see the information in the HTML page itself is correct. I will update the sitemap to show the same values.
