### ISSUE TITLE
Change value of checkbox toggler doesn't enable the save button

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu#3172]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.5
| Browser Version | Chrome Version 56.0.2924.76 (64-bit)

#### Actual Behavior

If you have a checkbox with type `toggler` on a page, and you only change this checkbox value in sulu admin from false to true - then no changes will be affected and the change can't be saved (because the save button is disabled).
Only if you change something in an another field the save button is enabled and the change can be saved.

#### Expected Behavior

If i change the value of this toggle button, the save button should be enabled.

#### Steps to Reproduce

Create a field with type checkbox and param type `toggler`.
Go to sulu to the page in which you have this field.
Change the value of the button from false to true.
Save button is currently disabled.

**Comment by danrot** [comment]
Just tested it, seems to be fixed now.

**Comment by dmetzler1988** [comment]
@danrot 
I test it again on sulu version 1.6.3. Same issue - but on blocks.
