### ISSUE TITLE
Blocks property for live-preview throws errors - google validator

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu#3175]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | all versions with live-preview
| Browser Version | everyone

#### Actual Behavior

If you use the live-preview of sulu and you have blocks, then the [google validator for rich-snippets](https://search.google.com/structured-data/testing-tool) throws errors for each block-element.

![bildschirmfoto 2017-02-01 um 17 04 19](https://cloud.githubusercontent.com/assets/8446518/22514714/86180a0e-e8a0-11e6-8cc6-3cd554517d5b.png)

#### Expected Behavior

This blocks shouldn't throw errors.

#### Steps to Reproduce

- Create blocks in template.
- Add live-preview properties in html.
- Test the content with rich snippet testing tool of google.

**Comment by danrot** [comment]
That issue is actually related to https://github.com/sulu/sulu-standard/issues/813. Check the comment I have written there.

**Comment by danrot** [comment]
Since this data is not necessary in Sulu 2.0 anymore I am going to close this issue.
