### ISSUE TITLE
Add robots settings for webspaces

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#3178]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | -
| Browser Version | -

#### Actual Behavior

Robots nofollow and noindex can be set for each page. It would be nice to set this for a whole webspace.

#### Expected Behavior

In webspace settings there should be checkboxes for disable indexing.

**Comment by alexander-schranz** [comment]
This was fixed by symfony over a robots-tag header: https://symfony.com/blog/new-in-symfony-4-3-automatic-search-engine-protection to avoid indexing stages. Also it can still add urls to the robots.txt file or create a custom controller for it.
