### ISSUE TITLE
Disable automation bundle by default

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#3181]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 53796a96100d7e8a9c37e524b0e01c0f06f57c0c
| Browser Version | ---

#### Actual Behavior

sulu-standard currently includes the `SuluAutomationBundle`, which makes all the UI of this bundle visible to the user. The problem is, that none of it will work, because there must at least a cronjob be setup.

Another question is why sulu-minimal is different in this regard (it doesn't load the `SuluAutomationBundle`).

#### Expected Behavior

The Automation UI should not be shown if the functionality is not working.

#### Steps to Reproduce

1. Install sulu-standard
2. Navigate to the homepage of a webspace
3. The automation tab will appear, although tasks created there will never work

#### Possible Solutions

* Extract the Automation part into an own Bundle, similar to the [SuluThemeBundle](https://github.com/sulu/SuluThemeBundle)
* Simply do not include the `SuluAutomationBundle` in the kernel as it is currently done in sulu-minimal, but leave it in the `sulu/sulu` repository.
* Add a configuration to the `SuluAutomationBundle` (my least favorite approach... Why should we load the Bundle if we don't need any of its provided functionality?)

**Comment by danrot** [comment]
@sulu/core-team WDYT?

**Comment by wachterjohannes** [comment]
i would only not load it in the sulu-standard edition. that should be enough. afterwards we can think about extracting it into an own repo

**Comment by chirimoya** [comment]
I would prefer the own bundle, but for now it's fine to disable in the kernel.

**Comment by danrot** [comment]
Of course it is enough to disable it in the kernel, but I am talking about the long-term solution here :-) And when thinking about it, if we want to extract it into an own git repository (which is also my favorite solution) we should maybe do it now, because after the release it will be a BC break...

**Comment by danrot** [comment]
This decision is actually also important for https://github.com/sulu/sulu/pull/3180#discussion_r99802337... I don't really want to put the tab for the automations into the content bundle, if that is an "external" plugin (I know, it's not that external, but still...)

**Comment by wachterjohannes** [comment]
+1 for extracting.
