### ISSUE TITLE
Missing entries in Sitemap for pages not created in default locale

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#3187]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Tested with 1.4.2 and current develop (including #743a78bdb2bf6140703df8f1583a5601daa890bc)

#### Actual Behavior

When creating a page **not** in the default locale, it won't appear in the sitemap.

#### Expected Behavior

The page should appear in the sitemap.

#### Steps to Reproduce

1. Check what you default locale is (in my example `de`)
2. Add another language to the project (in my example `en`)
3. Create and publish a page in `en` (in another locale than the default one)
4. Check the sitemap - the page isn't there.
5. To check: Save the just created page in the default locale and it will appear in the sitemap.

**Comment by danrot** [comment]
@c00n84 How should a page that doesn't exist in the x-default locale be displayed in the sitemap?
