### ISSUE TITLE
template xml, property colspan causes design bug inside of sections

### ISSUE THREAD

**Issue by oafx** [sulu/sulu#3189]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.6
| Browser Version | Firefox Dev Edition 53.0a2 (2017-02-08) (64-Bit) but should be all browsers

#### Actual Behavior

referring to issue #2276 and PR #2900 
seems only to be fixed for properties/elements that are outside of a section

```xml

        <section name="eventlocation">
            <meta>
                <title lang="de">Adresse / Veranstaltungsort</title>
                <title lang="en">Adress / Location</title>
            </meta>
            <properties>
                <property name="locationname" type="text_line"> 
                    <meta>
                        <title lang="de">Name</title>
                        <title lang="en">Name</title>
                    </meta>
                </property>
                <property name="zipcode" type="text_line" colspan="3"> 
                    <meta>
                        <title lang="de">PLZ</title>
                        <title lang="en">Zipcode</title>
                    </meta>
                </property>
                <property name="city" type="text_line" colspan="6">
                    <meta>
                        <title lang="de">Stadt</title>
                        <title lang="en">City</title>
                    </meta>
                </property>
                <property name="Street" type="text_line">
                    <meta>
                        <title lang="de">Straße / Hausnummer</title>
                        <title lang="en">Street</title>
                    </meta>
                </property>
            </properties>
        </section>

```

produces following layout:

![sulu sections design bug](https://cloud.githubusercontent.com/assets/4024755/22764988/22607252-ee6e-11e6-8634-7f3a00ebf439.PNG)

#### Expected Behavior

as discussed in the above mentioned issue/PR i would expect sulu to create new grid rows when the column maximum of 12 is reached so that these design issues don't appear.

#### Steps to Reproduce

add the section definition from above inside the default/a new template

#### Possible Solutions

Probably modify `\ContentBundle\Resources\views\Template\macros\section.html.twig` according to the changes in PR #2900 

cheers

**Comment by wachterjohannes** [comment]
we have fixed that in https://github.com/sulu/sulu/pull/3184 could you please tests this for you? if it does not fix your issue please reopen it
