### ISSUE TITLE
Snippet ghosts

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3192]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no

#### Actual Behavior

Snippet detail page: When changing the language and the snippet in the requested locale doesn't exists, the ghost will be delivered. But form doesn't show this.

#### Expected Behavior

Like in Sulu pages: Placeholder with prefix.

**Comment by danrot** [comment]
That's fixed in Sulu 2.0
