### ISSUE TITLE
Linking Media in CKEditor broken

### ISSUE THREAD

**Issue by pascalvb** [sulu/sulu#3194]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.6
| Browser Version | n/a

#### Actual Behavior

I can’t insert links to documents from the media section in a CKEditor using the default button.
The overlay selection window opens but is empty. 
JS error is aura_1: – "null is not an object (evaluating ‘this.options.types.split’)”

#### Expected Behavior

The overlay selection window opens and shows my media assets. 

#### Steps to Reproduce

* Configure a template to include a "Text editor" content type field
* Create a new page using the template
* Enter some text in the CKEditor, highlight some of it and click the "add media"-Button

#### Possible Solutions

* Seems to be related to https://github.com/sulu/sulu/pull/3162
* Maybe adding all possible types as default in "sulumedia/js/ckeditor/media-link.js" could be feasible
* Alternatively (full blown solution) provide a config param to text_editor content type with allowed media types

**Comment by danrot** [comment]
Fixed in #3195
