### ISSUE TITLE
UserManager is broken for non secured website-kernel

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#3196]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | ---
| Browser Version | ---

#### Actual Behavior

If you us the UserManager in a non secured website-kernel the userRepository is null but will be used in the whole class.

#### Expected Behavior

The UserManager should work without exceptions or throw explicit exception (not supported for example).

**Comment by danrot** [comment]
I'll fix it.
