### ISSUE TITLE
Nested Blocks

### ISSUE THREAD

**Issue by mtnorthrop** [sulu/sulu#3199]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

Would it be possible to consider adding support for nested blocks? While working with Sulu, I've run into a number of situations where this functionality would have helped greatly, and I've also seen this mentioned by others on the Slack channel a couple times.

Nested blocks would allow content managers to create layouts such as this one:

![screenshot- 2017-02-13 18-41-40](https://cloud.githubusercontent.com/assets/800546/22896251/adcc1788-f21f-11e6-90c6-3aa52d59e3f3.png)

In this example, the "Features List" would be the parent block and "features" (the paragraphs with titles and icons) in the list would be the child blocks. The content manager would be able to add however many "features" they want as child blocks of the parent. (The section title and image in this example would most likely be included as simple properties of the parent block, and not necessarily as children.)

The main goal is to make it possible to add an arbitrary number of complex content structures to a block, in the same way that it is currently possible to add an arbitrary number of blocks to a page.

(An example of this type of functionality can be found in the Neo plugin for CraftCMS:
https://github.com/benjamminf/craft-neo#allow-blocks-to-contain-children)

**Comment by danrot** [comment]
Just to be sure: This feature is not easy to build, and probably won't be build in the near future. And from what I remember @chirimoya and @berndhep consciously decided not to implement the feature that way, maybe they can elaborate here why they've decided that way in more detail.

**Comment by berndhep** [comment]
This is a topic that we have discussed multiple times and I guess this feature will come in the future. But I would not expect it before end of this year.

**Comment by mtnorthrop** [comment]
Thanks for your comments. I understand that there are a lot of technical difficulties involved in adding this feature, but maybe we can hope for it in Sulu 3.0 :-) . At least, by having this issue on GitHub, others who are interested in this feature can see that it has been discussed.

**Comment by berndhep** [comment]
I think Sulu 2 will be more realistic @mtnorthrop  ;-)

**Comment by phiko95** [comment]
Are there some custom implementations for this feature already?

**Comment by Deltachaos** [comment]
@danrot is this part of Sulu 2?

**Comment by danrot** [comment]
@Deltachaos Sadly it's not... I guess we will tackle this issue in some 2.x release.
