### ISSUE TITLE
Snippets edit form: Change language to a ghost should open copy locale overlay

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3201]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

Snippets edit form: Change language to a ghost opens the edit form with the ghost content.

#### Expected Behavior

Snippets edit form: Change language to a ghost opens copy locale overlay.

**Comment by trickreich** [comment]
Belongs a little bit to #3192

**Comment by danrot** [comment]
Is implemented in Sulu 2.0
