### ISSUE TITLE
Audience Targeting HTTP Caching

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#3208]
The responses need to be cached considering the different target groups. But the recognition of the user must work although there is a cache in front of it.

**Comment by psren** [comment]
I'm not sure if I understood this correctly.
FosHttpCacheBundle does Caching per User-Group (http://foshttpcachebundle.readthedocs.io/en/latest/features/user-context.html)

**Comment by danrot** [comment]
@psren Sry, we are using ZenHub here, so you probably don't see that this is part of a bigger issue: https://github.com/sulu/sulu/issues/3148

We had already a look at this functionality of the `FOSHttpCache`, and we are probably going to use it.

**Comment by danrot** [comment]
A question that comes to mind is how to identify users correctly. I've tested to set a cookie `user-context` with a generated UUID.
This works so far, and would allow us to have the cookie in the  `UserContextController`. Normally only the session id would be passed, but we can change it with the `session_name_prefix` option of the `UserContextSubscriber`, or we implement our own `UserContextSubscriber` and override the `cleanHashLookupRequest`.

The UUID could also be saved to the database, or even have to be saved, because otherwise we can't refer to the applied audience groups. If we in addition don't cache the response of the `userContextAction`, then every request has to hit the database, which makes the caching less efficient. Maybe we have to store these settings in a separate cache (should be configurable: files might be fine for simple installations, but won't work on clusters with read-only filesystems).
