### ISSUE TITLE
Section name with spaces generate false css class

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3213]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.0-RC
| Browser Version | Chrome 56

#### Actual Behavior

The generated class is for a section with spaces is `section-Call To Action`

#### Expected Behavior

The expected is `section-call-to-action`.

#### Steps to Reproduce

```xml
        <section name="Call To Action">
            <properties>
                <property name="books" type="text_line"/>
            </properties>
        </section>
```

#### Possible Solutions

Use something like `Urlizer` to generate the class name.

**Comment by kfrohwein** [comment]
Sadly there is no twig filter and we argued that it is probably not a wise choice to add white spaces to the property names.

So the best solution would be to add a RegEx Check to the XSD

Like:

```
    <xsd:restriction base="xsd:token">
        <xsd:pattern value="[A-Za-z]+[A-Za-z0-9_]"/>
    </xsd:restriction>
```

Still we have to check if PHPCR can use _ or - 

And it is probably a BC break.

**Comment by danrot** [comment]
Since the name is not used as css class name anymore, this is not a real problem any more.
