### ISSUE TITLE
Hint for parallel editing of a page, is not seperated in language versions

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#3218]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.7
| Browser Version |  Chrome 56

#### Actual Behavior

One person is editing the start page in German-version
One person is editing the start page in an other language version
you get the hint (yello bar on top), that two persons are working on the page 

#### Expected Behavior

no hint because you're working on different language versions

#### Steps to Reproduce
-

#### Possible Solutions
-

**Comment by danrot** [comment]
Not sure if we should implement it that way... The problem is that there could be some fields which are shared over different languages, so it would deliver a wrong feeling of safety then.

@berndhep What do you think about that?

**Comment by danrot** [comment]
We probably won't implement this, because these two content managers still could cause each other a data loss.
