### ISSUE TITLE
[ContactBundle] A contact's "position" appears as null in Twig, even when it is set

### ISSUE THREAD

**Issue by mtnorthrop** [sulu/sulu#3221]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.0-RC2

#### Actual Behavior

When I have a Contact in the Contact module with an assigned position, the contact's position is shown as `null` when I dump the Contact data in Twig.

`{{ dump(contact) }}` shows this (output abridged):
```
Contact {#3956 ▼
  #id: 2
 ...
  #position: null
...
  -id: null
}
```

`{{ dump(contact.position) }}` shows:
```
Position {#4872 ▼
  +__isInitialized__: false
  -position: null
  -id: 1
   …2
}
```

However, `{{ dump(contact.position.position) }}` seems to work:
```
"My Position"
```

**Comment by alexander-schranz** [comment]
Did have a quick look at it as I first though its a problem with the function ordering which we had some time ago in the community bundle. But it seems really only be that the `position` is not saved on the Contact entity itself like `mainEmail`. The position is only set by the `setPosition` function which is never called by doctrine. the only fix would be add something like a postLoad or for me remove the `position` property as it doesn't make sense for me when getPosition and setPosition directly access the mainAccountContact. As this is a BC Break maybe remove it in 2.0.

/cc @sulu/core-team

**Comment by wachterjohannes** [comment]
i think thats because the position is not joined when loading it! the `__isInitialized__: false` indicates that this is a proxy object from doctrine.

What i did not understand whats the problem here? have i overseen something?

**Comment by mtnorthrop** [comment]
The reason that it appear to be a problem to me is that, when you do `{{ dump(contact) }}` you get this:
```
Contact {#3956 ▼
  #id: 2
 ...
  #position: null
...
  -id: null
}
```
This result makes it look like `position` is a property that should be set, but which is null. Most of the other contact properties can be accessed by doing something like `{{ contact.firstName }}` but if you try to do `{{ contact.position }}` it doesn't work.

It's quite possible that this is actually working as intended, but in that case I guess we'd want to explain in the docs that you need to do `{{ contact.position.position }}` so that people know how to access the data.

**Comment by alexander-schranz** [comment]
I would remove the `position` property from https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/ContactBundle/Entity/Contact.php#L62-L68 and deprecate the `getCurrentPosition` and use the `getPosition`  function.
