### ISSUE TITLE
Copy locale for homepage

### ISSUE THREAD

**Issue by ollietb** [sulu/sulu#3226]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.6
| Browser Version | 

#### Actual Behavior

When I create a new locale and run `initialize` and then `copy-locale` it creates the tree with the new language, but the homepage is still the default template and when I try to copy the homepage from an existing locale using the 'Copy languages' modal in the UI, it doesn't appear to do anything

#### Expected Behavior

When copying the entire tree using the `copy-locale` command, the homepage should take on the template and content from the locale it is copy from

#### Steps to Reproduce

Add a new locale, eg en_au
```
  <localization language="en" country="us" default="true">
     <localization language="en" country="au"/>
  </localization>
  <localization language="pt" country="br"/>
```
Run initialise
```
  app/console sulu:document:initialize
```
Run copy-locale
```
  app/console sulu:content:locale-copy your_site en en_au --overwrite
```
The homepage is not the same for en_au as en and it is not possible to use the "Copy Locale" option in the UI. The other pages in the tree work as expected.

**Comment by ollietb** [comment]
Perhaps related #3127

**Comment by danrot** [comment]
@ollietb Since the PR has already been merged I assume that this issue is fixed now. Please say if I am wrong.
