### ISSUE TITLE
Search indexes "page_mywebspace_published" not known

### ISSUE THREAD

**Issue by ISC3141** [sulu/sulu#3232]
| Q | A
| --- | ---
| Bug? | no?
| New Feature? | no
| Sulu Version | 1.4.7
| Browser Version | Chrome Version 56.0.2924.87

#### Actual Behavior

When I try to do a search on the website (from the preprod VM) I have the following error : 
CRITICAL - Uncaught PHP Exception Massive\Bundle\SearchBundle\Search\Exception\SearchException: "Search indexes "page_marketplace_published" not known. Known indexes: "media", "page_marketplace", "contact", "category", "account"" at /var/www/marketplace/vendor/massive/search-bundle/Search/SearchManager.php line 331...
It works on my local, why not on the VM?

#### Expected Behavior

The index "page_mywebspace_published" for the website search should exits... Right?

#### Steps to Reproduce

I have no idea, it works on my local but not on the preprod VM...

#### Possible Solutions

None for now...

**Comment by alexander-schranz** [comment]
Did you try to purge and reindex your search:

```
bin/adminconsole massive:search:purge --all
bin/websiteconsole massive:search:purge --all
bin/adminconsole massive:search:reindex
bin/websiteconsole massive:search:reindex
```

**Comment by ISC3141** [comment]
Thanks, I forgot to purge and reindex the web part, only did on the admin...
Sorry for this issue.
