### ISSUE TITLE
Snippet list tab

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3235]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

At the moment all snippet types are displayed in same list.

#### Expected Behavior

In my opinion it would be nice if there would be a tab for each snippet type.
Same as it is implemented in the SuluArticleBundle would be nice.
Also a tab with 'All types' would be nice.

**Comment by danrot** [comment]
Closed in favour of #4278
