### ISSUE TITLE
Default snippet

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3236]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

All snippet types are displayed in the default snippet list in the webspace settings section.

#### Expected Behavior

In my opinion it would be nice if we could configure if a snippet type should be displayed in this section.

**Comment by danrot** [comment]
This is possible now with [snippet areas](https://docs.sulu.io/en/2.0/cookbook/default-snippets.html#defining-areas).
