### ISSUE TITLE
Internal Link column navigation crash with broken page

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3240]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.0-RC2
| Browser Version | Chrome 56

#### Actual Behavior

When I have a broken page in my tree:

![bildschirmfoto 2017-02-28 um 09 52 55](https://cloud.githubusercontent.com/assets/1698337/23398164/c1cf83fa-fd9b-11e6-8ad1-e491cae49431.png)

When I open another page and want to set an `Internal link` (Settings Tab) the column navigation fails with:

```
Type error: Argument 2 passed to Sulu\Component\Content\Compat\StructureManager::wrapStructure() must be an instance of 
Sulu\Component\Content\Metadata\StructureMetadata, null given, called in ~/Projects/sulu-minimal.lo/vendor/sulu/sulu/
src/Sulu/Component/Content/Mapper/ContentMapper.php on line 954
```

#### Expected Behavior

The column navigation should be shown the same way in the overlay for internal link like the main column navigation.

#### Steps to Reproduce

![internal-link](https://cloud.githubusercontent.com/assets/1698337/23398331/6b6ed514-fd9c-11e6-8716-8b7855b4b5b1.gif)

#### Possible Solutions

Seems like the same check as the main column navigation is missing in the overlay.

**Comment by danrot** [comment]
This works now also for the internal links without errors :+1: However, the page is not striked through anymore, but I would consider this a different issue.
