### ISSUE TITLE
Content Type should handle disabled, readonly, required like html standard

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3248]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

### Actual Behavior

Currently only simple content types are handling require correctly. Disabled current don't work with the form mapper and readonly is mostly not included.

### Expected Behavior

 - `required`: need to input something or choose at least one in a multi selection
 - `readonly`: The user can only see this input but not manipulate it
 - `disabled`: The different to readonly in html is that its not send to the server when the form is submitted. So the form mapper should only write disabled fields not read it.

For the input it should also check the other attributes work correctly e.g. `autofocus`: https://www.w3schools.com/tags/tag_input.asp

### Steps to Reproduce

Disabled currently works like readonly because the form mapper will still read the values.

### Possible Solutions

Every component should have the ability to be:

 - [x] Disabled
 - [ ] Readonly
 - [x] Required

**Comment by danrot** [comment]
I am not sure if `readonly` will ever be implemented, but `disabled` and `required` works now for almost all fields. Therefore going to close this issue.
