### ISSUE TITLE
Attribute 'mandatory' doesn't work for some content types.

### ISSUE THREAD

**Issue by imigo** [sulu/sulu#3249]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
1.4.7 | eaa6d9f8703370410adaf21f2fecb5c8461e750b

#### Actual Behavior

The attribute 'mandatory' doesn't do anything for (at least) the content types: single_internal_link and internal_links. 

The following validates when empty:
```<property name="teaser_box_1_url" type="single_internal_link" mandatory="true">```

#### Expected Behavior
Using the example code: is expected not to pass the validation when empty.

#### Steps to Reproduce
Add this code in a template xml file:
```
<property name="link" type="single_internal_link" mandatory="true">
  <meta>
    <title lang="en">link</title>
  </meta>
</property>
```

**Comment by danrot** [comment]
This is practically the same issue as #3161, #2901 and #2938. I am leaving the latter one open, since it is the most detailed one.
