### ISSUE TITLE
Sulu versioning disables output of creator

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3251]
| Q | A
| --- | ---
| Bug? | no/yes?
| New Feature? | no
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

When versioning is enabled the creator isn't disabled.
Is this a feature? And when yes, why?

**Comment by danrot** [comment]
Yes, this is a feature. We've decided that the information is already available in the versioning table (the one who created the first version is also the creator), and we decided to not show it once more. This might be confusing for you as a developer, but the end user will only see one of both options.
