### ISSUE TITLE
Draft has no changer

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3253]
| Q | A
| --- | ---
| Bug? | yes/no?
| New Feature? | yes/no?
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

When there's a draft without a changer, then the frontend crashes.

#### Expected Behavior

I'm not sure about that, this should be discussed, is it possible that a page exists without a changer?

**Comment by trickreich** [comment]
@wachterjohannes @danrot @alexander-schranz Please let me know what you think about this.

**Comment by alexander-schranz** [comment]
I would say yes it can have no changer as the user which created the page could have been deleted.

If pages are created or changed with Automation/TaskBundle the Task Handler should set the changer to the user which created the task to change/create the page.

**Comment by danrot** [comment]
I would also say that a changer is not totally necessary... But apart from that decision our frontend should not break if there is no changer. Even if we say that there always has to be a changer.

**Comment by wachterjohannes** [comment]
currently the frontend breaks if a draft is present without a changer.

**Comment by danrot** [comment]
That's what I am saying: It should not break if no changer is present either way.

**Comment by danrot** [comment]
Just tested it, the page can now be saved, read, and so on even if no changer is present.
