### ISSUE TITLE
VersionController Response

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3255]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5
| Browser Version | --

#### Actual Behavior

When trying to restore a version which doesn't exists, the response is 500.

#### Expected Behavior

It should be status 404.

#### Possible Solutions

We've implemented it in the SuluArticleBundle:
https://github.com/sulu/SuluArticleBundle/blob/develop/Controller/VersionController.php#L144

Maybe this could be used here also.

**Comment by trickreich** [comment]
@danrot That was the thing what I'm tried to talk about with you before.

**Comment by danrot** [comment]
Fixed in https://github.com/sulu/sulu/pull/3256
