### ISSUE TITLE
Question/Caching: Sulu performance on webhosting provider

### ISSUE THREAD

**Issue by oafx** [sulu/sulu#3257]
| Q | A
| --- | ---
| Bug? | probably not?
| New Feature? | no
| Sulu Version | 1.5.0
| Browser Version | Any Browser

#### Actual Behavior

How does Sulu behave at the moment? 

Hi, 

I'm currently struggling with the performance of Sulu (or Symfony?) in production on a webhosting plan by 1und1.de _(i know, i know, i shouldn't do that but well.. it is kind of required)._
It looks like the whenever the cache expires (40mins?) the app does a complete rebuild of the cache which results in a request that takes **30s for completion**. Which is pretty undesirable for any website.
Every following request only takes around 500ms to be completed which is more than fine but those 30s request are a deal breaker. 
On the contrary if I deploy the same app in production in a nginx/php-fpm container setup with mostly default settings the initial request takes less than 750ms to finish and the following >250ms (which is damn great imho.). I'm aware that i shouldn't use this as base for a comparision because of many reasons but i find the difference in load times way too big.

#### Expected Behavior

Since 1und1.de states that the hosting plan in use can run Drupal 8 which is afaik a Symfony based app i'd expect that it wouldn't be a problem to run Sulu on it.

Maybe I'm doing something wrong? Any ideas/suggestions/help? 
Sadly I can't use apc and only file based php opcache in this hosting plan and this doesn't seem to help.

_Also I'm sorry if this is the wrong place to asking this kind of question here in as an issue, I wasn't quite sure where to ask_

Thanks in advance

**Comment by danrot** [comment]
Just to be sure: The HTTP cache is expiring, and then the entire Symfony cache has to be rebuilt?

**Comment by oafx** [comment]
Good question. I'm not quite sure to be honest as I don't know how to debug this behavior on the webspace environment. It is the same time like cold start, like I did a rm -rf on the cache dir, so yeah i guess it rebuilds the entire cache. I was suspecting it to be in correlation with the
`<cacheLifetime type="seconds">2400</cacheLifetime>` 
as it seems to happen roughly every 40 mins but it's just a guess afterall:

``` 
[Datetime]  time_connect:time_starttransfer:time_total
[2017_03_09-11:04]   0.013:0.996:0.997
[2017_03_09-11:06]   0.029:0.079:0.079
[2017_03_09-11:08]   0.032:0.240:0.240
[2017_03_09-11:10]   0.011:26.453:26.453
[2017_03_09-11:12]   0.029:0.088:0.088
...
[2017_03_09-11:50]   0.032:0.199:0.199
[2017_03_09-11:52]   0.034:42.513:42.513
[2017_03_09-11:54]   0.029:0.112:0.112
...
[2017_03_09-12:32]   0.005:0.268:0.268
[2017_03_09-12:34]   0.013:27.213:27.213
[2017_03_09-12:36]   0.029:0.081:0.081
...
[2017_03_09-13:14]   0.029:0.082:0.082
[2017_03_09-13:16]   0.013:25.451:25.451
[2017_03_09-13:18]   0.030:0.098:0.098
...
[2017_03_09-13:56]   0.004:0.097:0.097
[2017_03_09-13:58]   0.004:26.591:26.591
[2017_03_09-14:00]   0.039:0.165:0.165
...
[2017_03_09-14:38]   0.012:0.062:0.062
[2017_03_09-14:40]   0.065:27.916:27.916
[2017_03_09-14:42]   0.014:0.166:0.166
...
[2017_03_09-15:20]   0.070:0.154:0.154
[2017_03_09-15:22]   0.004:26.178:26.178
[2017_03_09-15:24]   0.009:0.125:0.125
...
[2017_03_09-16:02]   0.014:0.134:0.134
[2017_03_09-16:04]   0.031:25.948:25.948
[2017_03_09-16:06]   0.029:0.078:0.078
...
[2017_03_09-16:44]   0.029:0.091:0.091
[2017_03_09-16:46]   0.015:26.411:26.411
[2017_03_09-16:48]   0.004:0.086:0.086

```

**Comment by danrot** [comment]
Maybe you can try to set the cache lifetime of the template to 0, and see if it is happening every time then. Or is the site already running in production? And you can't reproduce the behavior on your local machine, right?

**Comment by oafx** [comment]
i've set the lifteime of the template to 0 now and.. I don't know. 

as it happens it seems like now even if I delete the cache folder contents completely the webpage loads in about 4 secs to load at tools.pingdom.com, whatever I am doing, following loads might be a bit faster like one second but I'm not completely sure about that either.

So I figured I'd set the lifetime back to 2400 to see if it takes 30s again and.. even with an empty cache
it takes max 4 secs to load, following loads at 700ms. 

Which makes me think it's just the performance of the webshosting envrionment by 1und1.de that creates these 30s load times or in other words if I leave the lifetime at 0 and 1und1 has a bad day every request would take 30s. 

the page isn't in production yet and yeah i can't reproduce this locally but this could also be because my computer/server ressources aren't shared like they probably are at 1und1.de.

Any thoughts?

**Comment by danrot** [comment]
That's the only real explanation I have as well... Can't imagine that the cache just gets deleted, and even if it is you should probably talk to the guys from the hosting.

I could also imagine that the 30s are happening with the cache intact, since even with cache regeneration it should not take 30s... So it might really just have been a lot of load on their servers. 

Do you think we can assist you in anyway? Otherwise please close this issue.

**Comment by oafx** [comment]
No, I was just hoping that there was another explaination, hehe. Thank you @danrot
