### ISSUE TITLE
Webspace initialize with multiple portals and sub languages fails

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#3260]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Testet on 1.4.8

#### Actual Behavior

When languages are defined in a webspace, they all need to be used. so if we add something like this.
```
<localizations>
    <localization language="en" default="true"/>
    <localization language="de">
        <localization language="de" country="ch"/>
    </localization>
</localizations>
```  

And in Portal A we use  
```
<localizations>
    <localization language="en" default="true"/>
</localizations>
```

And in Portal B we use  
```
<localizations>
    <localization language="de" default="true">
        <localization language="de" country="ch"/>
    </localization>
</localizations>
```

Now if we use the `app/console sulu:document:initialize` command it fails with the error
```
[Sulu\Component\Webspace\Loader\Exception\WebspaceLocalizationNotUsedException]
The webspace definition for "microlife" has locales which are not used in any portal
```

Because de_ch is not found by the webspace validator (XmlFileLoader10.php Line 672)

#### Expected Behavior

Is that the loader also finds interleaved languages.

#### Steps to Reproduce

Use webspace and portal settings as mentioned above.

#### Possible Solutions

Temporary Solution:
Do not write interleaved languages, do it like this: (on general and portal localizations)
```
<localizations>
    <localization language="en" default="true"/>
    <localization language="de"/>
    <localization language="de" country="ch"/>
</localizations>
```

**Comment by danrot** [comment]
That's fixed in https://github.com/sulu/sulu/pull/3270, and was released with 1.4.11.
