### ISSUE TITLE
Sitemap for sub webspaces

### ISSUE THREAD

**Issue by janmassive** [sulu/sulu#3268]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.10

#### Actual Behavior

Sitemap does not contain sub webspaces that start with the same url.

#### Expected Behavior

Sitemap should contain all pages from all webspaces including sub webspaces.

#### Steps to Reproduce

Portal url of main webspace xml file:
```<url>example.com/{localization}</url>```

Portal url of a sub webspace xml file:
``` <url language="en">example.com/en/dental</url>```

#### Possible Solutions

Static fix was to override the XmlSitemapRenderer's 'renderSitemap' function to execute the provider build multiple times with the respective webspace key and to iterate over the results withing the sitemap template.

**Comment by alexander-schranz** [comment]
fixed in the sitemap refractoring in 1.6.
