### ISSUE TITLE
Possibility of Modifing column width in Column Navigation

### ISSUE THREAD

**Issue by spras** [sulu/sulu#3286]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | ?
| Browser Version | every

#### Actual Behavior

In the column navigation, column width is fixed.
It could make hard to read long page name. 

#### Expected Behavior

Possibility to configure column width, perhaps at application level or better by user preferences.

**Comment by danrot** [comment]
That's a feature that is already in discussion for the 2.0 release, don't think that we'll be able to do that before.

**Comment by spras** [comment]
Ok great ! here is an other improvement my customer related : (can be added to the 2.0 backlog ?) :
possibility to drag'n drop pages to re-order them :-)

**Comment by danrot** [comment]
We have also already been discussing this, but we don't really want to support drag&drop in the content tree... In our experience customers tend to lose pages then, because they were moved. That's why we chose the more conscious approach here.

**Comment by danrot** [comment]
The width of the columns is a bit wider now. We also cut the text from the middle, so even with long names it should be clear what is being clicked at. So I don't think we gonna add a configuration for that, because it opens the door to breaking the design, and it is a lot to maintain.
