### ISSUE TITLE
Long cache file names throw errors under windows

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3294]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.0

### Actual Behavior

Long cache file names throws error under windows:

```bash
PHP Exception Symfony\Component\Filesystem\Exception\IOException: 
"Cannot rename F:\Programs\server\wamp\www\folder\http\var\cache\admin\dev\sulu\field_descriptor\Sul10B8.tmp"
to
 "F:\Programs\server\wamp\www\folder\http\var\cache\admin\dev/sulu/field_descriptor/Sulu-Bundle-MediaBundle-Entity-Media-Sulu-Component-Rest-ListBuilder-Doctrine-FieldDescriptor-DoctrineFieldDescriptorInterface-573f30909f4bf560971e1115453c34fc.php".
```

### Expected Behavior

We should avoid long file names in cache files.

### Possible Solutions

Maybe use a hash function to avoid long file names.

**Comment by danrot** [comment]
I don't think we should use hashes here, that makes exploring and debugging the cache incredibly hard... But in the filename you've shown there is a lot of information duplicated, so we could maybe get rid of some of the information.

**Comment by danrot** [comment]
We are using now the resourcekey instead of the old representation, which is a lot shorter. Therefore this problem should be mitigated.
