### ISSUE TITLE
Block is falling behind preview in Admin

### ISSUE THREAD

**Issue by nieck** [sulu/sulu#3311]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.2
| Browser Version | Firefox 52.0.2 (but will also happen in other browsers)

#### Actual Behavior

When a block has the name "content" it uses the width of #content in the main.css file:
https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/AdminBundle/Resources/public/css/main.css#L268
This will make the block fall behind the preview.

![schermafbeelding 2017-04-14 om 12 44 53](https://cloud.githubusercontent.com/assets/26794105/25042011/049a86ca-2115-11e7-811e-f2a5f104338a.png)

#### Expected Behavior

It should not accidentally us the width of #content in the main.css file.

#### Steps to Reproduce

Create an admin page template with a block and name a block as "content"

**Comment by danrot** [comment]
We don't have any mechanisms like this anymore in Sulu 2.0, therefore this issue is solved.
