### ISSUE TITLE
Detection of available templates only works with HTML

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#3316]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | ---
| Browser Version | ---

#### Actual Behavior

Sulu detects if the template should be listed in the template dropdown by checking if the given `view` is available as `.html.twig` template in the current theme.

Just to be sure: This is the dropdown I am talking about:
![image](https://cloud.githubusercontent.com/assets/405874/25217353/d0f18508-25a6-11e7-9c37-e5751539e18a.png)

#### Expected Behavior

I have an installation where I want to use Sulu as a JSON API, so in the ideal case there is only a `.json.twig` template, and no `.html.twig`. If I do it like that, the template is not showing up in the template list anymore. IMO this is a legit use case, which should be supported.

I know that the preview might have problems with that, but I have simply turned it off.

#### Steps to Reproduce

1. Create a template
2. Only create a `.json.twig` template but no `.html.twig` template
3. The template won't be available in the dropdown

#### Possible Solutions

Configure which templates to use instead of automatically detect it. That's also a problem for beginners (they simply add a new xml file, and are wondering why it doesn't show up).

**Comment by oafx** [comment]
Quick Question: Are you saying that i can create a `.html.twig` __and__ a `.json.twig` template and sulu would know which template to serve based on the request type? I was just recently wondering about how i would expose data as an json api with sulu..

**Comment by wachterjohannes** [comment]
@oafx yes you can add you own formats as long as symfony detect the request type. But you have to provide a `html` template this is used to detect if the template is present.

**Comment by oafx** [comment]
@wachterjohannes cool stuff, will try it! thanks for the quick response

**Comment by danrot** [comment]
This was fixed in #4861
