### ISSUE TITLE
Teaser Selection loses its content when dragged and dropped

### ISSUE THREAD

**Issue by Bacis** [sulu/sulu#3318]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.0
| Browser Version | Google Chrome 57.0.2987.133

#### Actual Behavior

Sulu Teaser Selection element once repositioned with drag n drop feature with other block elements loses its content once the page was reloaded.

#### Expected Behavior

Once the element is repositioned in another place the content; title, description and image, inside the Teaser Selection element should remain the same. 

#### Steps to Reproduce

Create some block elements of any other content, for example text and Teaser Selection element, fill them in with content, save it and then reposition those blocks with drag n drop. Once you save the page and refresh it you'll see Teaser Selection element lost its content.

![teaser selection](https://cloud.githubusercontent.com/assets/9341833/25225294/311ec28c-25c1-11e7-9be3-e5db25446cab.png)

**Comment by danrot** [comment]
Closed in #3355.
