### ISSUE TITLE
Is there any way to tweak the column width in the admin panel to avoid the ellipsis in the title?

### ISSUE THREAD

**Issue by dalailomo** [sulu/sulu#3319]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.4.0
| Browser Version | -

#### Actual Behavior

In pages with long titles, an ellipsis appears in the middle of the title, making it hard to read in some situations.

![screen shot 2017-04-20 at 14 06 10](https://cloud.githubusercontent.com/assets/6674841/25232259/933dd870-25d2-11e7-8409-26383b593915.png)

#### Expected Behavior (?)

Is there any way to tweak the column width values? Thanks!

**Comment by wachterjohannes** [comment]
@dalailomo TBH currently not. there is a constant in our javascript library which cannot be overwritten from outside. @berndhep what do you think would that be a good idea to make that configurable?

**Comment by dalailomo** [comment]
@wachterjohannes thanks for the response.

Honestly it would be a very nice feature :)

**Comment by danrot** [comment]
This is a duplicate of #3286
