### ISSUE TITLE
template xml, property colspan still creates UX bugs in admin view under certain circumstances

### ISSUE THREAD

**Issue by oafx** [sulu/sulu#3341]
| Q | A
| --- | ---
| Bug? | yes (UX)
| New Feature? | no
| Sulu Version | sulu-standard 1.5.3
| Browser Version | FF 54.0a2 (2017-04-18) (64-Bit) 

#### Actual Behavior

while #3184 fixed most of the UX bugs, you still experience under certain conditions missaligned form fields when using the colspan property in the template xml.

```xml
        <section name="eventlocation">
            <meta>
                <title lang="de">Adresse / Veranstaltungsort</title>
                <title lang="en">Adress / Location</title>
            </meta>
            <properties>
                <property name="locationname" type="text_line" colspan="12"> 
                    <meta>
                        <title lang="de">Name</title>
                        <title lang="en">Name</title>
                    </meta>
                </property>
                <property name="zipcode" type="text_line" colspan="3"> 
                    <meta>
                        <title lang="de">PLZ</title>
                        <title lang="en">Zipcode</title>
                    </meta>
                </property>
                <property name="city" type="text_line" colspan="3">
                    <meta>
                        <title lang="de">Stadt</title>
                        <title lang="en">City</title>
                    </meta>
                </property>
                <property name="street" type="text_line" colspan="6">
                    <meta>
                        <title lang="de">Straße / Hausnummer</title>
                        <title lang="en">Street</title>
                    </meta>
                </property>
            </properties>
        </section>
```

![grafik](https://cloud.githubusercontent.com/assets/4024755/25860005/843a5a02-34e0-11e7-9fb6-fc738bd8b2fd.png)

#### Expected Behavior

correctly aligned form fields

#### Steps to Reproduce

add the section definition from above inside the default/a new template

#### Possible Solutions

not quite sure where to find the origin but the resulting `app.min.*.css` contains

```css 
.grid-col-6.floating:nth-child(n+3) {
    margin-top: 20px;
}
```

and it appears `:nth-child()` isn't restrictive enough to achive the expected behavior ...or in general not the way to go as even if you'd use `:nth-of-type()` there would be some strange alignments, I think..

thanks in advance
Christian

**Comment by oafx** [comment]
I just noticed that the source of the code is found in [massiveart/husky](https://github.com/massiveart/husky)  ... should i open a seperate issue there?

**Comment by danrot** [comment]
@oafx I think in here is also ok, but I am afraid we don't have a lot of time to invest in this... But if you want to create a PR that's very welcome :-)

**Comment by danrot** [comment]
(Most of) these bugs should be fixed, therefore going to close this issue.
