### ISSUE TITLE
Avoid removing all permission for content pages

### ISSUE THREAD

**Issue by janmassive** [sulu/sulu#3349]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no

#### Actual Behavior

Admin users are able to remove there own permissions for editing content pages and therefore the pages can't be reedited without resetting permissions in the database directly.

#### Expected Behavior

It shouldn't be possible to remove all permissions from pages.

**Comment by danrot** [comment]
Since this is very hard to implement, I think we won't be able to fix this. Therefore I am going to close this issue.
