### ISSUE TITLE
Images in preview are not working with absolute_url

### ISSUE THREAD

**Issue by wynny** [sulu/sulu#3380]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.5
| Browser Version | all

#### Actual Behavior

Images are not loading in preview if we use absolute_url for image-urls in our templates.

#### Expected Behavior

Images should load in preview, even if we use absolute_url.

**Comment by danrot** [comment]
Can confirm the issue, seems like the host seems to be missing in the Request we are faking for the preview. @wachterjohannes Do you think you can fix that? I guess it is not a lot of work.
