### ISSUE TITLE
Extension of symfony expression for route-generation

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#3394]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6.0-RC1
| Browser Version | none

#### Actual Behavior

Currently, a new instance of SymfonyExpression is created in the constructor of `SymfonyExpressionTokenProvider`. So no functions are available (only `object` and `translator`).

#### Expected Behavior

This ExpressionLanguage should be extensible over 
[ExpressionProviders](http://symfony.com/doc/current/components/expression_language/extending.html#using-expression-providers). These providers could be collected via a service tag and added to the ExpressionLanguage.

**Comment by danrot** [comment]
Sounds like nobody asked for that anymore :see_no_evil: And if that comes up again we can implement it. Therefore I am going to close this issue.
