### ISSUE TITLE
Massive search SearchQuery.php limit cannot be null

### ISSUE THREAD

**Issue by Bacis** [sulu/sulu#3406]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0-rc
| Browser Version | Chrome 58.0.3029.110
#### Actual Behavior

When I set up Massive Search Bundle with Elasticsearch adapter teaser selection process hangs up with 400 error: `{code: 400, message: "parsing_exception: Unknown key for a VALUE_NULL in [size].", errors: [,…]}`

Elasticsearch query:
`{\"query\":{\"query_string\":{\"query\":\"__id:\\\"de8d082c-7c41-40d4-bd9e-f3686f14cc31\\\"\"}},\"from\":0,\"size\":null}`

#### Expected Behavior
`/admin/api/teasers?ids=content;uuid&locale=locale` endpoint should return teaser json data.

`vendor/massive/search-bundle/Search/SearchQuery.php` should have the size parameter set to a value, having this value set as null throws an exception in Elasticsearch.

#### Steps to Reproduce

Set up Elasticsearch adapter and try to add a teaser element in your page.

**Comment by wachterjohannes** [comment]
fixed by https://github.com/massiveart/MassiveSearchBundle/issues/108
