### ISSUE TITLE
Symfony Flex Support

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#3412]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | ---
| Browser Version | ---

Symfony have been anounced at the end of last year, and it seems to make it a lot easier to set up projects, and would probably also help us getting rid of sulu-standard and sulu-minimal (or at least replace it with something a lot lighter).

The biggest problem we are facing is how to support multiple kernels, and it looks like there will not be a lot of thought put into this problem, since the issue for this on https://github.com/symfony/flex/issues/110 was closed pretty fast.

So we have multiple options here:

## Symfony flex will support multiple kernels in any way

Doesn't seem very likely to me at the moment.

## Hook into the symfony flex process

We somehow create our own `context.php` file which lies next to Symfony flex' `bundles.php` file. This should look something like this:

```php
<?php

return [
    'admin' => [
        'excluded_bundles' => [
            'Symfony\\Cmf\\Bundle\\RoutingBundle\\CmfRoutingBundle',
        ],
    ],
    'website' => [
        'excluded_bundles' => [
            'Sulu\\Bundle\\AdminBundle\\SuluAdminBundle',
            'Symfony\\Bundle\\SecurityBundle\\SecurityBundle',
        ],
    ],
];
```

This file would also have to be read and filter the bundles by the `Kernel`. The main problem I see here is how to fill this file. From what I've seen a bundle recipe can only copy entire files, all other options like `bundles`, which touch existing files, have a specific key in the `manifest.json` file, which we probably can't touch (except there will be some extension points I don't know about).

Otherwise this would be a manual step that has to be done after installing, which somehow contradicts the whole point of Symfony Flex (although it might still be a little easier). Apart from that we should not forget that this is not only about registering bundles, but also about loading configuration and routing files.

## Single Kernel Setup

This would probably be the approach closest to Symfony flex, according to this [comment](https://github.com/symfony/flex/issues/110#issuecomment-309833181).

We could make a single kernel setup, and avoid having a session started on the website as described in the [documentation](http://symfony.com/doc/current/session/avoid_session_start.html). I think not starting a session is one of our main reasons to have multiple kernels. A problem that would still remain is the growing size of the container. If that is a problem it would be a good idea to split it in two separate applications, and we could recommend to only do that if necessary. That would make DX a bit better, i.e. we would only have one console per application, and it cannot happen that commands have to be executed twice (at least not per application, but executing them in the other application as well might be easier to understand).

I think it should not be a big deal to support both approaches ONCE we've changed our architecture to be more modular. Then it shouldn't matter which bundle is installed in which application, since each bundle should work independently.

However, problems we would still face is that we have to move some decisions from compile time to runtime, which might be some work to do.

**Comment by wachterjohannes** [comment]
I have created a prototype which works https://github.com/wachterjohannes/sulu-skeleton its not perfect and gets a cleanup :)

To make the monolithic "core" of sulu reuse other recipes we have to replace `symfony/symfony` with `symfony/framework-bundle`, ...

In the repository, there is a PR which contains files which should be created inside the `sulu/sulu: 1.6` recipe.

**Comment by danrot** [comment]
We've got this working halfway with our own sulu/skeleton, I think that's as good as it currently gets. Therefore closing this issue.
