### ISSUE TITLE
Download-Links are broken with % in filename.

### ISSUE THREAD

**Issue by dominikmatt** [sulu/sulu#3415]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.8

#### Actual Behavior

All Image Download will Display a "400 Bad Request" error, if there is a `%` in filename.

#### Steps to Reproduce

1. Upload a image with the name `test%.png`.
2. Download or edit this image from Media-Bundle.
    - Download will display a "400 Bad Request" error
    - Image-edit is broken and does not display any image.

**Comment by danrot** [comment]
I think that should be fixed by #3431, can you check?
