### ISSUE TITLE
Proper error message when default template in webspace does not exist

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3417]
| Q | A
| --- | ---
| Bug? | no/yes
| New Feature? | no/yes
| Sulu Version | 1.6
| Browser Version | --

#### Actual Behavior

If the default template is not found the system crashes.

#### Expected Behavior

1. Is this really needed? If no template is defined, just take the first one.
2. Show error in Sulu Admin

**Comment by trickreich** [comment]
@alexander-schranz If you have more thoughts about this, just feel free to add it ;)

**Comment by alexander-schranz** [comment]
its ok for me. Important is to show an error message "Template not found ...". Making the default templates optional is also a good idea.

**Comment by danrot** [comment]
I think I would throw the exception already a lot earlier: When the template does not exist when building the cache I would already throw an exception. Similar to what we have done in #4831

**Comment by niklasnatter** [comment]
This displays the following error when using Sulu 2.2.4:
![Screenshot 2021-02-05 at 09 39 46](https://user-images.githubusercontent.com/13310795/107010014-17facd80-6796-11eb-9148-6a6afd1a8941.png)
