### ISSUE TITLE
Limit available templates

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3419]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6
| Browser Version | --

#### Actual Behavior

At the moment every template is available when creating a new template.

#### Expected Behavior

Maybe following things would be great:
* Limit available templates for children
* Limit available templates for webspaces

**Comment by trickreich** [comment]
@sulu/core-team I think we have talked about this already, but don't found a ticket for it.

**Comment by danrot** [comment]
That's the ticket: https://github.com/sulu/sulu/issues/913
