### ISSUE TITLE
Url for Media API Entity is not encoded

### ISSUE THREAD

**Issue by mob8607** [sulu/sulu#3424]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.0 
| Browser Version | Android on Honor 6X

#### Actual Behavior

Plain spaces in getUrl() method for media.

#### Expected Behavior

Encoded url from getUrl() method in media API Entity.

#### Steps to Reproduce

- Upload a file with spaces in its filename.
- Call the getUrl() method of the API entity for the MediaController. 
- Most browsers can encode the url, but it can lead to problems with several android phones.

**Comment by alexander-schranz** [comment]
Solutions: `rawurlencode` or `pathCleanup` service? 

/cc @sulu/core-team

**Comment by danrot** [comment]
Fixed in #3431
