### ISSUE TITLE
CustomUrl with Port

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3443]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.1
| Browser Version | --

#### Actual Behavior

When a custom url contains an port the BE crashes.

#### Expected Behavior

Custom urls with ports should be legit.

**Comment by danrot** [comment]
We've rebuilt everything so that the ports should not be put into the webspace configuration anyway, so this issue is not relevant anymore.
