### ISSUE TITLE
Styling issue for content type media_selection inside highlighted section of template

### ISSUE THREAD

**Issue by nwaelkens** [sulu/sulu#3456]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version |  1.6.1 / 773d626ea0f2fecaa1b36f113f9128dc0b181fa3
| Browser Version | Safari, Version 10.1.1 (12603.2.4)

#### Actual Behavior

Whenever the content type 'media_selection' is a child of `<section name="highlight">` inside an XML-template file the styling goes wrong after selecting one or more media_types (images). 
If the content type is not a child of `<section>`, all goes well. See attachement.. 

#### Expected Behavior

The media_selection field should both look the same inside or outside the `<section>` element.

#### Steps to Reproduce

Use an existing template-file and replace `<section name="highlight"> ... </section>` with this code: 
```
<section name="highlight">
    <properties>
        <property name="title" type="text_line" mandatory="true"></property>
        <property name="url" type="resource_locator" mandatory="true">
            <tag name="sulu.rlp"/>
        </property>
        <property name="image" type="media_selection">
        </property>
    </properties>
</section>

<property name="image2" type="media_selection"></property>
```

#### Possible Solutions

This is a CSS issue. All looks fine after removing the class "highlight-section" of the div-container. 
Well, offcourse the section is not hightlighted anymore now. 

The scss-line 62 or 73 in web/bundles/suluadmin/scss/modules/base.scss is partly responsible at this moment for the wrong display.
The 'problem' scss: 

```
.highlight-section {
    $imageWidth: 310px;
    $imageHeight: 270px;
    width: 100%;
    margin-top: -$contentPaddingTop;

    background: $highlightSectionBackgroundColor;
    margin-bottom: 30px;
    @include clear-float;

    .image {
        float: left;
        width: $imageWidth;
        height: $imageHeight;
        overflow: hidden;
    }

    .content {
        width: calc(100% - #{$imageWidth});
        float: left;
        padding-top: 20px;
        padding-bottom: 20px;
        @include clear-float;

        &:only-child {
            width: 100%;
        }
    }
}
```
<img width="922" alt="screen shot 2017-07-23 at 14 20 39" src="https://user-images.githubusercontent.com/737452/28503459-7a4deb82-7007-11e7-9eb3-f38754e97333.png">

**Comment by nwaelkens** [comment]
Hmm... looks like this has been reported already: https://github.com/sulu/sulu/issues/3420

**Comment by wachterjohannes** [comment]
@nwaelkens thanks for the hint. I have closed the mentioned issue because this one has more details.

**Comment by danrot** [comment]
There's also #3103, but this one is really better, so I close the other one.

**Comment by danrot** [comment]
In 2.0 the highlight section does not have a special look anymore, so the problem is solved :slightly_smiling_face:
