### ISSUE TITLE
[Security] Cross-Site Scripting

### ISSUE THREAD

**Issue by Bacis** [sulu/sulu#3476]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.1
| Browser Version | Chrome

#### Actual Behavior

It is possible to inject javascript code into text area elements and once its saved it is rendered as javascript rather than text.

#### Expected Behavior

Javascript code in text fields should have its tags stripped.

#### Steps to Reproduce

Simply type <script>alert("I shouldn't be working")</script> in a text field, save it and reload the page. There should be alert message popping on your screen.

#### Possible Solutions

Removing script tags on text elements.

![clipboard - 9 august 2017 11-05](https://user-images.githubusercontent.com/9341833/29206760-9e860c2a-7e83-11e7-9933-2181f91a2739.png)
![clipboard - 9 august 2017 11-06](https://user-images.githubusercontent.com/9341833/29206759-9e8593e4-7e83-11e7-852a-01173fb08a6d.png)
![clipboard - 9 august 2017 11-07](https://user-images.githubusercontent.com/9341833/29206758-9e858214-7e83-11e7-87e8-635ae5f9c6c0.png)

**Comment by foued611** [comment]
Cross-Site Scripting Is thereby possible

**Comment by foued611** [comment]
I can reproduce the problem, also in WYSIWYG editor

**Comment by foued611** [comment]
#3501
i think the problem is only partially solved.
the possible malicious code can still be stored in the DB.
In order to prevent the persistent XSS, the code should be cleaned up before storing and after reading data

**Comment by danrot** [comment]
Well, the WYSIWYG editor needs to store the data in HTML, because it is about editing HTML. It should also be exported that way to the twig template. Also, some people might use text areas to copy some embed codes or similar stuff. So we probably won't change that any further as in #3501.
