### ISSUE TITLE
"Resource locator" doesn't update after 'losing focus' from a date field

### ISSUE THREAD

**Issue by nwaelkens** [sulu/sulu#3481]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.1 (SF3.3.4)
| Browser Version | Safari (Version 10.1.2)

#### Actual Behavior

When using multiple rlp.parts (`<tag name="sulu.rlp.part" />`): 
The content type field 'Resource locator' does not update after losing the focus of a date field (content type: date). 

It does grab the contents of the date field though if losing focus of a text_line field.

#### Expected Behavior

The resource locator field should update when losing focus of a date field just as it does when losing focus of a text_line field. 

#### Steps to Reproduce
1. Create a new template (just the XML below should be enough)
```xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>test</key>

    <view>templates/test</view>
    <controller>SuluWebsiteBundle:Default:index</controller>

    <properties>

        <section name="highlight">
            <properties>
                <property name="title" type="text_line" mandatory="true">
                    <tag name="sulu.rlp.part"/>
                </property>

                <property name="subtitle" type="text_line">
                    <tag name="sulu.rlp.part"/>
                </property>

                <property name="startdate" type="date" mandatory="true">
                    <tag name="sulu.rlp.part" />
                </property>

                <property name="url" type="resource_locator" mandatory="true">
                    <tag name="sulu.rlp"/>
                </property>
            </properties>
        </section>

    </properties>
</template>
```
2. Create new content using this template
3. Enter data and note that I spoke the truth :-)

<img width="1000" alt="screen shot 2017-08-15 at 15 03 45" src="https://user-images.githubusercontent.com/737452/29317302-8f21a17c-81cb-11e7-8417-6f2ad1bbb183.png">

#### Possible Solutions

Probably some event trigger is missing on the fields generated by content type 'Date'.

**Comment by danrot** [comment]
fixed in #3545
