### ISSUE TITLE
Support for 2FA-Auth

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu#3482]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

Sulu currently have no 2FA support (Yubico, Google authenticator, etc.).  
How about 2FA support on login page?

**Comment by danrot** [comment]
Nice idea! But I am not sure if we want to have this in the core. @chirimoya what do you think?

**Comment by You85** [comment]
+1

**Comment by simpliste** [comment]
+1

**Comment by alexander-schranz** [comment]
@simpliste @You85 for upvoting please use github reactions and no comments!
@danrot maybe we could implement 2FA over E-Mail so third party bundles can use this interfaces to implement 2FA over other services.

**Comment by danrot** [comment]
Still not sure if we want to implement that in the core or if that should be a 3rd party bundle, since we are using external services.

**Comment by alexander-schranz** [comment]
This topic did occur again multiple times and is on my personal wish list a long time. Hope we can tackle this issue in one of our next releases Using https://github.com/scheb/2fa and the new symofony authenticator system when we upgrade to Symfony 5.4 / 6.0. Releated issue: #6513

**Comment by luca-rath** [comment]
Would rather reimplement the whole authentication process using OpenID Connect instead of just implementing 2FA, because we are way more flexible then. Someone could then just use LDAP for login with just a bit of configuration

**Comment by alexander-schranz** [comment]
LDAP Login would be great also, but 2FA and OpenID / LDAP login are for me 2 different topics.

**Comment by luca-rath** [comment]
But OIDC comes with 2FA for free, depending on the identity provider ... So time is probably better spent on OIDC

**Comment by alexander-schranz** [comment]
The problem I see with OIDC that it is not well maintained in symfony world atleast nothing I see I would currently add as a dependency to sulu. Where scheb/2fa is stable since years and well mainained.

**Comment by luca-rath** [comment]
Symfony itself shouldn't care about OIDC, the whole handling should be done in the admin frontend. So the backend would just receive an OIDC ID Token (JWT), validates it with the public key of the identity provider, check if a sulu user with the email address of the token exists and if no user exists it should create a new user with the given email address.

**Comment by chirimoya** [comment]
But you need an OpenID provider, or am I wrong? And we need to deliver a default one within Sulu.

**Comment by luca-rath** [comment]
yes exactly, but I guess it would be enough to have just a "partial" openid provider implemented in the core, so just exposing the endpoints which are really needed by the sulu admin frontend.

**Comment by alexander-schranz** [comment]
Still think this can be implemented separate as it would be an openid connect user provider, which would need to handle this. The frontend itself should not get into contact with any of this protocols, as there this complex protocols would just add security issues, and communication should be done over PHP. 

I would still not mix here SSO and 2FA, SSO is something which need more work, as it need to authenticate against an external endpoint and create or udpate our user (which is a hard requirement for sulu) with the external endpoints data. Were single sign on is just additional step and don't require the protocol.

Also SSO a very splitted thing, still lot use oauth, oauth2, there is openid connect and there is what most cms did the last year implement the ID4me protocol and ldap is still also very common.

For me I would definitly not begin to mix this things up here and implemented 2fa the most simpliest way over the scheb/2fa package which is well maintained and commonly used for this usescase.

For all of SSO I created a separate issue: https://github.com/sulu/sulu/issues/6514

**Comment by alexander-schranz** [comment]
Some research about this topic.

For API based implementation of scheb/2fa we need to follow this documentation:

 - https://symfony.com/bundles/SchebTwoFactorBundle/6.x/api.html
 
For adding support for 2fa over email the User need to be extended this way:

 - https://symfony.com/bundles/SchebTwoFactorBundle/6.x/providers/email.html
 
For adding support for 2fa over google authenticator the User need to be extended this way:

 - https://symfony.com/bundles/SchebTwoFactorBundle/6.x/providers/google.html

For adding support for 2fa over totp the User need to be extended this way:

 - https://symfony.com/bundles/SchebTwoFactorBundle/6.x/providers/totp.html
 
The extending requires a compatibility layer between sulu and scheb/2fa packages. So sulu should not require that the packages exist. Just if the are available sulu should provide the functionality out of the box. If the packages are not installed sulu will not provide 2fa in the UI. 
 
Updated implemented the compatibility layer in: https://github.com/sulu/sulu/pull/6589

**Comment by alexander-schranz** [comment]
2FA will be part of #6589 but will requires scheb/2fa to be installed and configured in the project. See docs: https://github.com/sulu/sulu-docs/pull/720
