### ISSUE TITLE
"media_selection" does not display title of medias after adding a new media.

### ISSUE THREAD

**Issue by dominikmatt** [sulu/sulu#3500]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.*, 1.6.*

#### Actual Behavior

After adding a image on a"media_selection"-field the title of already added medias are not displayed
<img width="828" alt="bildschirmfoto 2017-08-28 um 11 42 42" src="https://user-images.githubusercontent.com/3023954/29768317-13c657be-8be6-11e7-9a76-92801bd215c4.png">

#### Steps to Reproduce

- Add some medias on a "media_selection"-field.
- Save it and reload page. (Everything looks good)
- Add a media on the same "media_selection"-Field. (Now only the title of the new Media is displayed)

**Comment by alexander-schranz** [comment]
#3500
