### ISSUE TITLE
Wrong page url is returned when using "path" property in template

### ISSUE THREAD

**Issue by notsure** [sulu/sulu#3506]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3
| Browser Version | Chrome 60.0.3112.113

#### Actual Behavior

When adding a new page eg: "Press & News" the url is auto generated to "press-and-news". This works fine until you embed a smart content to your page. If this smart content has a pagination the url of the next page button of the pagination is "press-news?p=2".

#### Expected Behavior

Expected is that the url of the pagination is "press-and-news?p=2".

#### Steps to Reproduce

Add a new page template with a smart content block. Then add a new page with this template. Load sufficient subpages to the smart content so that the pagination appears. Click/View the url of the next page button.

#### Possible Solutions

The property "path" which can be used in templates rendered by the DefaultController::IndexAction should return the correct url of the page.

Page uses the the default controller of sulu website bundle:

```xml
    <controller>SuluWebsiteBundle:Default:index</controller>
```

Pagination link is currently made like this:

```twig
    <a class="pagination-item page-switch"
          href="{{ sulu_content_path(path) ~ '?p=' ~ (view.smartcontent.page + 1) }}">
    </a>
```

**Comment by alexander-schranz** [comment]
@notsure the `path` variable is the path of the PHPCR Node not the `url` of the page.
you need to use the `url` to get the current url of the page.

**Comment by notsure** [comment]
thank you!
