### ISSUE TITLE
ProxyManager File name too long

### ISSUE THREAD

**Issue by gotu** [sulu/sulu#3510]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.3
| Browser Version | Google Chrome (Ubuntu) Version 60.0.3112.113 (Official Build) (64-bit)

#### Actual Behavior

How does Sulu behave at the moment?

Using Backend, navigating to "Homepage", shows blank content area and this error message in symfony dev toolbar (when in dev env):

https://github.com/Ocramius/ProxyManager/issues/388 

#### Expected Behavior

What is the behavior you expect?

Backend to show the proper complete content management view when managing "Homepage" item.

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

Install sulu accordingly to http://docs.sulu.io/en/latest/book/getting-started.html

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.

Probably an OcramiusProxyManager issue, I posted it here: https://github.com/Ocramius/ProxyManager/issues/388

**Comment by alexander-schranz** [comment]
Hello @gotu 

this error appears with the proxy classes when you are on a crypted drive as there the filename can not be longer as a specific length. Move your project or just your cache folder outside the crypted area of your drive.

**Comment by gotu** [comment]
That makes sense, thx!
