### ISSUE TITLE
Allow mailto: and :tel links in the URL content type

### ISSUE THREAD

**Issue by thomaslarsson** [sulu/sulu#3520]
| Q | A
| --- | ---
| Bug? | no(?)
| New Feature? | yes(?)
| Sulu Version | 1.6.4
| Browser Version | Chrome 60.0.3112.113

#### Actual Behavior

Sulu currently doesn't allow URL schemes such as `:tel` or `mailto:`. The frontend validation fails. 

#### Expected Behavior

Expecting valid URL schemes such as `:tel` or `:mailto` to be allowed.

#### Steps to Reproduce

1. Add a property of the `url` content type to a template such as:
```
<property name="url" type="url">
    <meta>
        <title lang="en">URL</title>
    </meta>

    <params>
        <param name="defaults" type="collection">
            <param name="scheme" value="mailto:"/>
            <param name="specific_part" value=""/>
        </param>
        <param name="schemes" type="collection">
            <param name="mailto:"/>
            <param name="tel:"/>
            <param name="http://"/>
            <param name="https://"/>
        </param>
    </params>
</property>
```
2. Create/edit a content object of the same template. 
3. Frontend validation fails on `:tel` or `:mailto`

**Comment by wachterjohannes** [comment]
@danrot we should keep that in mind for the 2.0 release

**Comment by danrot** [comment]
This has been done in #4551
