### ISSUE TITLE
missing "previewToken"

### ISSUE THREAD

**Issue by skydiablo** [sulu/sulu#3521]
hi there!
i have installed a new plain sulu mininmal solution, like official tutorial/install guid. all works fine, except the preview function from the admin area. the given XHR-requerst ends in an error-response (but HTTP 200 ???)

the given JSON response:

> {"type":"error","exception":"Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException","code":0,"trace":[{"file":"\/var\/www\/test\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Websocket\/MessageDispatcher\/MessageHandlerContext.php","line":114,"function":"get","class":"Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag","type":"->","args":["previewtoken"]},{"file":"\/var\/www\/test\/vendor\/sulu\/sulu\/src\/Sulu\/Bundle\/PreviewBundle\/Websocket\/PreviewMessageHandler.php","line":202,"function":"get","class":"Sulu\\Component\\Websocket\\MessageDispatcher\\MessageHandlerContext","type":"->","args":["previewToken"]},{"file":"\/var\/www\/test\/vendor\/sulu\/sulu\/src\/Sulu\/Bundle\/PreviewBundle\/Websocket\/PreviewMessageHandler.php","line":87,"function":"render","class":"Sulu\\Bundle\\PreviewBundle\\Websocket\\PreviewMessageHandler","type":"->","args":[{},{"command":"render","webspaceKey":"test"}]},{"file":"\/var\/www\/test\/vendor\/sulu\/sulu\/src\/Sulu\/Bundle\/PreviewBundle\/Websocket\/PreviewMessageHandler.php","line":58,"function":"execute","class":"Sulu\\Bundle\\PreviewBundle\\Websocket\\PreviewMessageHandler","type":"->","args":[{},{"command":"render","webspaceKey":"test"}]},{"file":"\/var\/www\/test\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Websocket\/MessageDispatcher\/MessageDispatcher.php","line":63,"function":"handle","class":"Sulu\\Bundle\\PreviewBundle\\Websocket\\PreviewMessageHandler","type":"->","args":[{"resourceId":"7v030g2rds6pvc2qjr5v7mu624"},{"command":"render","webspaceKey":"test"},{}]},{"file":"\/var\/www\/test\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Websocket\/MessageDispatcher\/MessageDispatcherApp.php","line":118,"function":"dispatch","class":"Sulu\\Component\\Websocket\\MessageDispatcher\\MessageDispatcher","type":"->","args":[{"resourceId":"7v030g2rds6pvc2qjr5v7mu624"},"sulu_preview.preview",{"command":"render","webspaceKey":"test"},[],{}]},{"file":"\/var\/www\/test\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Websocket\/MessageDispatcher\/MessageDispatcherApp.php","line":59,"function":"dispatch","class":"Sulu\\Component\\Websocket\\MessageDispatcher\\MessageDispatcherApp","type":"->","args":[{"resourceId":"7v030g2rds6pvc2qjr5v7mu624"},{},{"handler":"sulu_preview.preview","message":{"command":"render","webspaceKey":"test"},"options":[]}]},{"file":"\/var\/www\/test\/vendor\/sulu\/sulu\/src\/Sulu\/Bundle\/WebsocketBundle\/Controller\/FallbackController.php","line":53,"function":"onMessage","class":"Sulu\\Component\\Websocket\\MessageDispatcher\\MessageDispatcherApp","type":"->","args":[{"resourceId":"7v030g2rds6pvc2qjr5v7mu624"},{"handler":"sulu_preview.preview","message":{"command":"render","webspaceKey":"test"},"options":[]}]},{"function":"send","class":"Sulu\\Bundle\\WebsocketBundle\\Controller\\FallbackController","type":"->","args":["admin",{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/test\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php","line":153,"function":"call_user_func_array","args":[[{},"send"],["admin",{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]]},{"file":"\/var\/www\/test\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php","line":68,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1]},{"file":"\/var\/www\/test\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Kernel.php","line":171,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/var\/www\/test\/web\/admin.php","line":40,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/var\/www\/test\/web\/app.php","line":13,"args":["\/var\/www\/test\/web\/admin.php"],"function":"require_once"}],"msg":"You have requested a non-existent parameter \"previewtoken\".","parentMsg":{"handler":"sulu_preview.preview","message":{"command":"render","webspaceKey":"test"},"options":[]}}

any suggestions ?

**Comment by wachterjohannes** [comment]
@skydiablo this exception is quite confusing - but normally the problem is the request before (where the preview will be started) where the twig throws an error. can you check that?

**Comment by skydiablo** [comment]
ok, my fault! there was an miss-configuration with theme feature...

**Comment by crevillo** [comment]
hi. i'm having the same issue. can you tell me how did you solve it? 
Thanks.

**Comment by alexander-schranz** [comment]
@crevillo do you have multiple webservers for your project?

**Comment by crevillo** [comment]
@alexander-schranz i'm developing with docker for now. i have different containers for fpm and nginx.
