### ISSUE TITLE
Texteditor field type

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3528]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | for 2.0

### Actual Behavior

The actual editor has many features which we don't need and basically want to avoid that our users throw all things into a text editor. So the current text editor is a heavy block we don't need. 

#### Texteditor functions:

- **Basic Functions**
   - Bold (`<strong>`)
   - Italic (`<em>`)
   - Underline (`<u>`)
   - Strike (`<s>`)
   - Supscript (`<sup>`)
   - Subscript (`<sub>`)
 - **Lists**
   - Ordered List (`<ol>`)
   - Unoreder List (`<ul>`)
 - **Links**  (`<a>`, `<sulu:link>`)
   - External
   - Pages
   - Assets
   - Articles
   - ...
 - **Texteditor Enter Mode** (https://docs.ckeditor.com/#!/guide/dev_enterkey)
   - Paragraph Mode (Text is wrapped in P, Enter = Paragraph, Shift Enter = Break)
   - Break Mode (Text is not wrapped in P, Enter = Break) (Used for styling titles e.g. SuluFormBundle Labels)
 - **Tables** (`<table>`): when no content type
 - **Paste from Word**
 - **Custom Elements**
   - e.g. styles (https://docs.ckeditor.com/#!/guide/dev_styles)
 - ~Headlines~ (when needed it should be added to the custom elements)
 - **Text align** (optional?)
   - Left
   - Right
   - Center
   - Block
 - **Source Mode** 
 - **Script Tags**
 - **Embeds**

**List of requested CKEditor extensions**

In the past following things were often requested.

 - colorpicker: would say the recommended way is to add Custom Elements or a Colorpicker where the colors need to be predefined: 
 - wordcount (max length)

**Comment by chirimoya** [comment]
https://github.com/ckeditor/ckeditor5/issues/592

**Comment by danrot** [comment]
Tom Vogel recommended [Slate](https://github.com/ianstormtaylor/slate) to me, built on top of React but easier to use than draft. We should probably have a look :smiley:

**Comment by danrot** [comment]
We have a text editor now with almost all the required functionality :-)
