### ISSUE TITLE
add a management system FAQ

### ISSUE THREAD

**Issue by You85** [sulu/sulu#3534]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | Yes
| Sulu Version | Latest version
| Browser Version | Chrome 60

#### Possible Solutions
it would be wise to define from the admin the questions and the answers for a page faq
Like this : https://www.powr.io/plugins/faq/standalone

**Comment by You85** [comment]
+1

**Comment by wachterjohannes** [comment]
@You85 this would be a custom module :) I don't think that we will provide a FAQ system in the core. But if you have time we would love to help you with implementing such a module.

**Comment by wachterjohannes** [comment]
I will close this issue but if you need help you can add comments here or subscribe to our slack channel where we could discuss such a new module.
