### ISSUE TITLE
premission shouldn't have

### ISSUE THREAD

**Issue by ReggieCaiShanghai** [sulu/sulu#3567]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Sulu Version | 1.6.6
| Browser Version | ALL

#### Actual Behavior

Even if you only have the live and view permission of the webspaces, the users will be able to unpubished the pages in these webspaces, but cann't publish them.

#### Expected Behavior

I think there shouldn't have this permission at all, unless you have the permission of edit

#### Steps to Reproduce

![20171016100337](https://user-images.githubusercontent.com/26782648/31598331-93e11d02-b27f-11e7-8467-730dfe373162.png)

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by danrot** [comment]
That has been fixed in Sulu 2.0
