### ISSUE TITLE
Analytics code in head and/or body

### ISSUE THREAD

**Issue by nvdbeek** [sulu/sulu#3593]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | latest

#### Actual Behavior
We use Google Analytics and Google Tag Manager only the JS code of GA and tag manager are load in our body. Is it possible to load a section in the head and other in body?

This is not only for Google but for all analytics codes.

#### Expected Behavior
For better tracking and analysis of our websites, Google recommends loading their code in the head and part of the body.

#### Steps to Reproduce
The JS code are now always loading before ending the body.

#### Possible Solutions
Possibility is to override the AppendAnalyticsListener. But it is better to give options to load in sections (head or body).

**Comment by wmschram** [comment]
+1 
Google tag manager no longer recommends loading everything in the body. It now recommends loading the <script> inside the head, and the <noscript> at the beginning of the body. 
source: https://developers.google.com/tag-manager/quickstart 

Google Analytics recommends loading everything in the head, and nothing in the body.
source: https://support.google.com/analytics/answer/1008080

**Comment by trickreich** [comment]
@sulu/core-team Any ideas when we will implement this?

**Comment by danrot** [comment]
We've discussed that internally, and we've come to the following conclusion:

* If a type like google tag manager, google analytics or something similar the type already knows where to put the code (before `</head>`, after `<body>` or before `</body>` are the options).
* For the custom type there also has to be a dropdown to select the above options.
