### ISSUE TITLE
Urls are not updated when moving content pages

### ISSUE THREAD

**Issue by notsure** [sulu/sulu#3595]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3
| Browser Version | Browser name and version

#### Actual Behavior

Lets say there are two content pages on the root level. Each of them contains multiple subpages. Now all sub items from the first content root page are moved to the root level. The url in the sulu admin view is displayed correctly but it is not updated in the front end. 

eg:

```
/foo
/foo/bar
/foo/loo
```

now `bar` and `loo` are moved to the root level but the url is still live above

#### Expected Behavior

The url should be updated 

```
/foo
/foo/bar > /bar
/foo/loo > /loo
```

#### Steps to Reproduce

Add some pages and add some sub pages and then move them into the root directory.

### Additional Feature Request

It is a pain in the ass to move multiple pages as you are only able to select one at a time and then move it with at least 3 additional clicks. So a multi selection would be nice.

**Comment by wachterjohannes** [comment]
can be fixed by clearing the HTTP-CACHE
