### ISSUE TITLE
Property type contact: fail to load contact categories.

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#3605]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Tested on 1.6.1 and 1.6.5
| Browser Version | Every browser

#### Actual Behavior

If you loop the contacts and dump their categories, it's an array with keys but empty array values if the contact have categories.

#### Expected Behavior

I expect an array of categories.

#### Steps to Reproduce

Add a property with type contact on a template.xml and add some contacts with categories in backend. Loop the contacts in frontend and dump the categories value.

#### Possible Solutions

Optimize serialization of contact data?

**Comment by trickreich** [comment]
@sulu/core-team I think there's something wrong with the serialization.. any ideas?

**Comment by wachterjohannes** [comment]
@trickreich yes looks like missing serialization context
