### ISSUE TITLE
Media interface crashes when sorted by URL column

### ISSUE THREAD

**Issue by tobias47n9e** [sulu/sulu#3617]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5, 1.6

#### Actual Behavior

Sorting by URL field breaks the Media interface.

#### Expected Behavior

URL should not be sortable.

#### Steps to Reproduce

Open Media interface. Switch to list view. Add URL field to table. Sort by URL. The user has no chance to revert back because after that all calls fail.

![grafik](https://user-images.githubusercontent.com/6953323/32775471-cca1b720-c92f-11e7-868a-b73bc91c595b.png)

#### Possible Solutions

Will send patch that disables sorting for that column.

**Comment by tobias47n9e** [comment]
Setting sortable to false does not seem to solve the issue:

    /.../vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/list-builder/Media.xml
    
    <property name="url" display="never" list:sortable="false"/>

**Comment by wachterjohannes** [comment]
@tobias47n9e you have to clear the table `se_user_settings` which contains the sorting information but for the long term the pasted snippet should work in my opinion

**Comment by danrot** [comment]
The URL is not shown anymore in the list, so this problem does not exist anymore.
