### ISSUE TITLE
Disposition type doesn't apply when downloading a media file

### ISSUE THREAD

**Issue by eugestarr** [sulu/sulu#3620]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.3
| Browser Version | Any browser

#### Actual Behavior

How does Sulu behave at the moment? 

When adding `inline` parameter to a query string of master media file keeps downloading instead of showing it in the browser.

Like: https://domain.com/media/1/download/image.png?v=1&inline=1

#### Expected Behavior

What is the behavior you expect?

According to MediaStreamController::downloadAction it should set disposition type to `inline` and allow the file to be shown in the browser.

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

1. Install Sulu 1.4.3
2. Upload media
3. Try to access a master media file by adding the `inline=1` or `inline=true` to a query string

**Comment by alexander-schranz** [comment]
@eugestarr as I can not reproduce this issue this can have some other problems:

1. the webserver overwrites the disposition type
2. the browser is configured to ignore the disposition type
3. the browser don't support disposition type for your file

Can you tell us what the returned headers are by running:

```bash
curl -XGET -I https://domain.com/media/1/download/image.png\?v\=1\&inline\=1
```
