### ISSUE TITLE
Toolbar: Collapse button/Hide text

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3621]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 2.0
| Browser Version | --

#### Actual Behavior

![image](https://user-images.githubusercontent.com/16644200/32825822-9895fc72-c9e6-11e7-8615-d4d6633aee19.png)

#### Expected Behavior

As in Sulu 1.*, just hide the text first.
Maybe also set a min-width.

**Comment by alexander-schranz** [comment]
This seems to be fixed text is hidden if screen is to small.
