### ISSUE TITLE
DocBlock for SnippetController putAction ambiguous

### ISSUE THREAD

**Issue by acrolyt** [sulu/sulu#3622]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.4 / 1.5

Just a little hint to improve the documentation

in 
https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
Line 226

The Docblock says  "Saves a new existing snippet." 
I think it's supposed to say "Saves an existing snippet"

Thats all, cheers : )

**Comment by wachterjohannes** [comment]
@acrolyt if it was that - we would be happy ;)

**Comment by danrot** [comment]
Fixed in #4916
