### ISSUE TITLE
Loading images directly from media bundle takes a long time

### ISSUE THREAD

**Issue by wmschram** [sulu/sulu#3636]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | latest

#### Actual Behavior

Showing images (SVG's in particular) on your website without _app_picture_ causes a very long loading time. I have several SVG's between 2 and 6kb. After uploading them into Sulu, i then use them on certain pages. In my Twig file i place the URL i receive through Twig as a 'background-image'. When loading that page i noticed these SVG's taking well over 200ms each to load _(between 200 and 350ms)_, even those of 2kb. The same happens when using jpg/png without _app_picture_ . I uploaded a 5kb jpg to Sulu, then used it on our page by directly requesting the link. Giving me a url like: /media/40/download these take much longer then should be excepted.

The amazingly good working _app_picture_ which i normally use for our jpg/png files, does not work with SVG's seen it will return the svg as a png file. that was the first thing i tried.

#### Expected Behavior

Showing a SVG (2 to 6kb) should not take longer then normal jpg/png files. I would except SVG's to load even faster seen the file size. 

#### Steps to Reproduce

1. Upload a svg or small jpg into Sulu (example: https://raw.githubusercontent.com/gilbarbara/logos/master/logos/airbnb.svg)
3. Use the svg/image on a page (< property name="image" type="media_selection" >).

#### Possible Solution

Make it possible to use SVG using the app_picture method, writing it into the /uploads/media folder then load them into the page. This is way faster then directly approaching a file in the media bundle.

P.s. Does the _svg_ returning as a _png_ when using _app_picture_ have something to do with: https://github.com/sulu/sulu/pull/2877/files#r78368791 ?

**Comment by alexander-schranz** [comment]
@wmschram the `url` property on medias is the download action which should not be used to embed things on the website. You should use the `media.thumbnails['format']` which will be stored in the `uploads/media` folder. To get this work correctly for SVGs imagick based on imagemagick with svg extension need to be enabled. The images need for cropping and scaling feature be converted to PNG.

If you really need original SVGs have a look at this workaround: https://github.com/sulu/sulu/issues/2246#issuecomment-236572585

**Comment by wmschram** [comment]
Ah of course, I should have known it wasn't meant to be used that way! Thanks for the workaround, a little tweak in the TwigExtension made it work just fine. Loading now takes about 15ms so that's perfect. Thanks.
