### ISSUE TITLE
shadow pages for article bundle

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#3644]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

it's not possible to generate shadow pages in articles

#### Expected Behavior

look at content area

**Comment by wachterjohannes** [comment]
@andreasganahl we already have an issue in the article-bundle :) i will close this issue in favor of this one https://github.com/sulu/SuluArticleBundle/issues/84
