### ISSUE TITLE
Invalid argument supplied for foreach() when looping through PageBridge->getChildren()

### ISSUE THREAD

**Issue by jaimybroere** [sulu/sulu#3663]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.3

#### Actual Behavior

When looping through the children of a document in a controller, the Sulu Preview throws an `Invalid argument supplied for foreach()` error.

#### Expected Behavior

The controller loops through the children and returns the childs.

#### Steps to Reproduce

This is part of the code where the issue shows up
```
 public function indexAction(StructureInterface $structure, $preview = false, $partial = false)
    {
        $pageChilds = array();
        ...
        if(is_array($structure->getChildren())) {
            foreach ($structure->getChildren() as $child) {
                array_push($pageChilds,$child->getDocument()->getResourceSegment());
            }
        }
```

#### Possible Solutions
Talked to Johannes about this and he said the document ($structure in this example) is serialized but the children are excluded.

**Comment by danrot** [comment]
Just tested, this seems to work now :tada:
