### ISSUE TITLE
Search function in article bundle 

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#3666]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

At the moment there is no fuzzy factor in the article bundle. only complete words deliver results in the search

#### Expected Behavior

please integrate a fuzzy factor for the search

**Comment by wachterjohannes** [comment]
@andreasganahl are you talking about the backend list? there we have decided to deactivate fuzzy to be more like the other lists in the admin.
