### ISSUE TITLE
WebspaceCopyCommand no smartcontent copy if no provider is set.

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#3692]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | any

#### Actual Behavior

How does Sulu behave at the moment? 

If you copy a webspace into another it check on smart_content if the provider is set and if it's content, in most projects the provider is not set because it is content as default.

#### Expected Behavior

What is the behavior you expect?

Check if provider is set and if it is content or if it's not set and uses the default provider (content).

#### Steps to Reproduce

Add two webspaces and a page with smartcontent where you add some pages. Copy into new webspace and the smartcontent will be empty.

#### Possible Solutions

Like expected behavior. check if its set or uses default provider.

**Comment by danrot** [comment]
Just tested it, works now :tada:
