### ISSUE TITLE
doctrine/orm 2.6.0 breaks composer install

### ISSUE THREAD

**Issue by PhilippSchreiber** [sulu/sulu#3697]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.11

#### Actual Behavior

composer install fails because of doctrine/orm BC break in 2.6.0

#### Expected Behavior

composer install runs

#### Steps to Reproduce

run composer install with a fresh started sulu project

#### Possible Solutions

Quickwin: fix doctrine/orm version to 2.5.* n the projects composer.json:
composer require doctrine/orm:2.5.*

**Comment by danrot** [comment]
Thanks for the issue! We've already encountered that yesterday, and there is a fix under way: #3696 

There is another PR doing the update to 2.6: #3694 
But there are too many BC breaks to justify doing that in a minor release, so we've decided to just stay on 2.5 for now.
