### ISSUE TITLE
Pass query params on a custom url

### ISSUE THREAD

**Issue by patrick-tassa** [sulu/sulu#3702]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.8

#### Actual Behavior

When using custom url, adding request parameters is not working.

#### Expected Behavior

Adding request parameters on a custom url would work.

#### Steps to Reproduce

Call a custom url in `<a href="custom_url"></a>` tag with `?param=test`, give me an error, because it don't recognize the custom url.

**Comment by wachterjohannes** [comment]
there are a few questions which come to my mind when I read this request.

1. Should this query params be matched (/test?test=1 => OK, /test?test=2 => Not OK)
2. Are they fixed? Or can they be set by the website application?
3. What should happen with this params? passed to the controller? Or even logged for tracking?

**Comment by patrick-tassa-cafpi** [comment]
1. Yes query params matches to /test?test=1
2. They be set by the website application
3. We can get them in the request param controller

**Comment by danrot** [comment]
That was fixed in #3345
