### ISSUE TITLE
Save and publish option is not deactivated when the user has no publish permisssion

### ISSUE THREAD

**Issue by jaapromijn** [sulu/sulu#3705]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | ^1.6
| Browser Version | Chromium 62.0.3202.94

#### Actual Behavior

When you create a role without publishing permissions. The CMS still shows the **Save and publish** option. Using that option will result in permission notices.
![image](https://user-images.githubusercontent.com/8127722/34523798-3f7adc32-f099-11e7-9ad4-571b8cc32a71.png)

![image](https://user-images.githubusercontent.com/8127722/34523806-4622787e-f099-11e7-81be-9c9be1e62860.png)

#### Expected Behavior

I would expect that the **Save and publish** option is disabled (like Publish).

#### Steps to Reproduce

- Create a new role: https://sulu.rocks/admin/#settings/roles/new where the Global **live** permission is deactivated.
- Create a CMS user for this role.
- Login in the CMS with this user.
- Add a new content page https://sulu.rocks/admin/#content/contents/sulu_demo/de/add/content
- The **save and publish** button will be active and using it will result in notices.

**Comment by dsuurlant** [comment]
This was also mentioned here, and hasn't been fixed afaik: https://github.com/sulu/sulu/issues/1482

**Comment by alexander-schranz** [comment]
This is fixed in 2.0 publish buttons do not longer be shown when you have no permission for it.
