### ISSUE TITLE
Customize admin environment

### ISSUE THREAD

**Issue by mvmaasakkers** [sulu/sulu#3708]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6.12

Is it possible to change/add css classes to menu items in the admin environment to customize it? I can't find a way how to and all I find is some generated templates in husky.js.

**Comment by wachterjohannes** [comment]
@mvmaasakkers there is no way to add/change the classes but you can simple reuse ours and add your css file http://docs.sulu.io/en/latest/bundles/admin/css.html?highlight=css

**Comment by danrot** [comment]
#4854 explains how that works now.
