### ISSUE TITLE
[SuluCategoryBundle] (#21) Categories visible after deleting parent node

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#371]
<a href="https://github.com/pjeroen"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/513131?v=2" /></a>
By @pjeroen *from* https://github.com/sulu-cmf/SuluCategoryBundle/issues/21

After deleting a parent node, child categories are still visible - see screenshots.

![screen shot 2014-09-02 at 13 26 44](https://cloud.githubusercontent.com/assets/513131/4117632/fa8dd414-3294-11e4-92f6-fcf10779dbf0.png)
![screen shot 2014-09-02 at 13 26 57](https://cloud.githubusercontent.com/assets/513131/4117634/ff250402-3294-11e4-9212-978590d26df5.png)

**Comment by danrot** [comment]
Small note: The child categories are deleted in the database, only the datagrid is not removing it from its own list.

**Comment by danrot** [comment]
@nnatter Can you also have a look at this?

**Comment by danrot** [comment]
Fixed with https://github.com/sulu/sulu/pull/2907 resp. 998e893
