### ISSUE TITLE
Cannot create cache file for Sulu\Component\DocumentManager\Document\UnknownDocument

### ISSUE THREAD

**Issue by fdyckhoff** [sulu/sulu#3710]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | v1.6.12
| Browser Version | -

#### Actual Behavior

Cannot create new documents, when the cache is empty. An exception is thrown when editing the homepage for the first time.

```
Uncaught PHP Exception ProxyManager\Exception\FileNotWritableException: "Could not write to path "/path/to/project/var/cache/admin/prod/sulu/proxies/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerated6ba9e6da88c639a61276f3813626e37b.php.5a568d0a08aae2.90023192": path does not exist" at /path/to/project/vendor/ocramius/proxy-manager/src/ProxyManager/Exception/FileNotWritableException.php line 60 {"exception":"[object] (ProxyManager\\Exception\\FileNotWritableException(code: 0): Could not write to path \"/path/to/project/var/cache/admin/prod/sulu/proxies/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerated6ba9e6da88c639a61276f3813626e37b.php.5a568d0a08aae2.90023192\": path does not exist at /path/to/project/vendor/ocramius/proxy-manager/src/ProxyManager/Exception/FileNotWritableException.php:60)"} []
```

#### Expected Behavior

I would expect that the file could be written. ;)

#### Steps to Reproduce

1. System: Ubuntu 16.04, PHP 7.0
2. Fresh installation of sulu-minimal (I followed the instructions of http://docs.sulu.io/en/latest/book/getting-started.html)
3. Started Server via console
4. Login as admin
5. Navigate to homepage of the newly created webspace
6. White page (no visual feedback)
7. Exception above is shown in prod.log

#### Possible Solutions

The name of the cache file is too long. I could fix the problem temporary by converting the class name with md5 in  ProxyManager\GeneratorStrategy\FileWriterGeneratorStrategy::generate

**Comment by alexander-schranz** [comment]
Hello @fdyckhoff 

are you maybe on a encrypted HDD for me it sounds like this issue: #3510
on encrypted filesystem filenames can only have a specific length. When its this issue I recommend to move the project to a none encrypted folder currently.

**Comment by fdyckhoff** [comment]
@alexander-schranz  That was indeed the problem. Thank you very much.
