### ISSUE TITLE
Webspace export has error while exporting blocks

### ISSUE THREAD

**Issue by tniebergall** [sulu/sulu#3712]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.12

#### Actual Behavior

The webspace export shows the message "ERROR: wrong data" in the block trans-unit

#### Expected Behavior

The webspace exporter should export the block values

#### Steps to Reproduce

Install sulu-demo an run "bin/console s:w:e sulu_demo.xml sulu_demo en" have a look at the block trans-unit of any page

**Comment by tniebergall** [comment]
This seems to fix the issue https://github.com/dominikmatt/sulu/blob/c5dd6c8bc3d57c425b175958b417f6f07378fc67/src/Sulu/Component/Export/Export.php

**Comment by wachterjohannes** [comment]
@tniebergall is this commit included in this pull-request https://github.com/sulu/sulu/pull/3305?

**Comment by tniebergall** [comment]
Yes

**Comment by danrot** [comment]
#3741 should fix this issue.
