### ISSUE TITLE
[CategoryBundle] Category validation type should convert ids to categories

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#372]
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot _from_ https://github.com/sulu-cmf/SuluCategoryBundle/issues/22

Currently the validation type only returns a few IDs, but it should return categories.
This would make hacks like the following obsolete: https://github.com/sulu-cmf/SuluContactBundle/blob/3a826c79edcb950d41a66a69b06cfbaeb9a442c3/Resources/public/js/components/contacts/main.js#L275

**Comment by danrot** [comment]
Not relevant in Sulu 2.0 anymore
