### ISSUE TITLE
Internal links: use internal title instead of redirect title in the content tree

### ISSUE THREAD

**Issue by ymc-siwi** [sulu/sulu#3721]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.13

#### Actual Behavior

When browsing the content tree, internal links use the title of their respective redirect target. 

#### Expected Behavior

Internal links should use their own title ("internal-title") in the nav tree. The link icon will still be visible and thus identify the node type ("link").

#### Steps to Reproduce

Create internal link in the content tree. Add subcontents to this link node. Internal link will show the title of its target in the nav tree. It will be very hard for content editors to understand why the subcontents are arranged under a node with a different name.

### Example

Imagine a content structure like this one:

Contact
Contact/Form
Contact/Contacts 
Contact/Map

Contact is an empty structure node, configured as internal link to "Form" and therefore use "Form" as its title. It will not make sense for content editors, why Form, Contacts and Map are subcontents of a node named "Form".

**Comment by DavidFeller** [comment]
Same request. I have a page with a lot of internal links that are used to build a rather complex mega menu in the frontend. Now, in the backend the parent entries inherit the title of the destination pages. For example, if I have a page called “about us” and it links to “contact”, in the backend “about us” is called “contact”, too. So when the number of pages rises, it gets quite hart for editors to understand that “about us” in the frontend is “contact” in the backend which is a link to another (sub)page that’s also called “contact”.

**Comment by wachterjohannes** [comment]
we have to discuss this topic for 2.0 /cc @berndhep @chirimoya

**Comment by danrot** [comment]
Just tested it, seems to be fixed now.

**Comment by DavidFeller** [comment]
I'm not sure it is really fixed. At least not if I understood the problem correctly in the first place. ;-). 
In a system I upgraded to 2.0.2 links in the pagetree still inherit the title of the page they point to. I'll prepare a little demo with a fresh installation. Perhaps we can discuss this on Slack.

**Comment by alexander-schranz** [comment]
Did test it seems not to be fixed.

If I create a new Page with the name `New Link` which links to `Artists` it will show `Artists` instead of `New Link` in the Page Tree.

**Comment by danrot** [comment]
Sorry, did not read carefully enough, thought this is about the navigation on the website.

However, I am not really sure if I would change this anyway. The information where the link goes to seems to be more important to me. I think that's something we should discuss internally quickly, so that we can decide if we change that behavior. /cc @sulu/core-team

**Comment by DavidFeller** [comment]
@danrot: I agree! It absolutely depends on the use case. Would it be possible to make it globally configurable..?

**Comment by nnatter** [comment]
I would expect to see the title of the link instead of the target. Otherwise, it is kind of confusing that it is even possible to set a title here. What name is displayed in a navigation?

**Comment by danrot** [comment]
@nnatter You are right, the title in the navigation is also the one from the settings tab... And since we always say the content tree also corresponds to the navigation it would probably make sense to change that...

**Comment by andrey-scada** [comment]
Hello, everyone! @danrot , any news on the progress regarding this issue?

**Comment by niklasnatter** [comment]
@andrey-scada As far as I know, there was no progress on this. I just created #5878. Unfortunately, this is a small BC break and I am not sure if we can change this before the next minor release.

**Comment by alexander-schranz** [comment]
#5878 is merged and will be part of the next release.
