### ISSUE TITLE
CoreBundle: change default value for sulu_core.content.language.default

### ISSUE THREAD

**Issue by oafx** [sulu/sulu#3722]
Hi, 

| Q | A
| --- | ---
| Bug? | maybe?
| New Feature? | no
| Sulu Version |  1.6.12

#### Actual Behavior

 _The issue is regarding my question in the sulu-io slack channel, read [more](https://sulu-io.slack.com/archives/C0430GGCV/p1516894616000055)_  

Currently, setting the parameter `locale` or the config value `framework.default_locale` doesn't influence the value of the `sulu_core.content.language.default`.

#### Expected Behavior

Following the parameter reference documentation i'd expect that setting the locale in the parameters would also apply the locale to `sulu_core.content.language.default`. 

#### Possible Solutions

@wachterjohannes propsed to set the default value to reference to `framework.default_locale`, i'd propose the parameter `locale` but basically it would be the same i guess.

thanks

**Comment by danrot** [comment]
fixed in #3735
