### ISSUE TITLE
CKEditor removes empty tags

### ISSUE THREAD

**Issue by ichdertobi** [sulu/sulu#3723]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | maybe?

#### Actual Behavior

The CKEditor removes empty tags.
For example things like icons from font-awsome 
`<i aria-hidden="true" class="fa fa-envelope-o"></i>` ,too.

How could I change this behavior?

In the configuration of CKEditor i should do something like "CKEDITOR.dtd.$removeEmpty["i"]=0" but how could I do this here?

**Comment by alexander-schranz** [comment]
Hello @ichdertobi 

You need to register your bundle as [Admin Bundle](https://blog.sulu.io/how-to-develop-a-bundle-in-the-sulu-admin-1). Then you can add the additional JS in your admin main.js file.

**Comment by ichdertobi** [comment]
What a pity =/
I was hoping there would be an option for the [text-editor](http://docs.sulu.io/en/latest/reference/content-types/text_editor.html?highlight=CKEditor) that can control this.
Okay, then I'll probably create a new component.
Thank you for your help

**Comment by alexander-schranz** [comment]
@ichdertobi if the CKEditor has a config param for that you can do this over the xml params: http://docs.sulu.io/en/latest/reference/content-types/text_editor.html#example 

But as said register your Bundle as AdminBundle and add that `CKEDITOR.dtd.$removeEmpty["i"]=0` to the main.js this is not much work.

**Comment by ichdertobi** [comment]
@alexander-schranz that was the first thing I checked at the documentation of [CKEditor Config](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html)
There isn't any option to igonre empty tags.

It is also no problem to create a bundle.
I just wanted to ask if there might be a simpler/quicker option. ;)

**Comment by alexander-schranz** [comment]
@ichdertobi you have with an own JS more possibility to change the CKEditor. Have a look at: https://github.com/sulu/sulu-docs/issues/320
