### ISSUE TITLE
ckeditor could be saved in source mode when included in blocks

### ISSUE THREAD

**Issue by tniebergall** [sulu/sulu#3727]
| Q | A
| --- | ---
| Bug? | yes
| Sulu Version | 1.6.12

#### Actual Behavior

If an attribute with ckeditor is a part of a block, the source mode validation is ignored. Therefore the next time the block is crashed.

#### Expected Behavior

The validation for the source mode should be availabel for blocks too.

#### Steps to Reproduce

Include attribute with ckeditor in a block. 
Crate a page with this block, switch to source mode in ckeditor, enter some text and save the page

**Comment by tniebergall** [comment]
@alexander-schranz

**Comment by alexander-schranz** [comment]
@tniebergall thank you for creating an issue. I think this could be related to #3161 and I will not be easy to fix in the current release.

**Comment by fdyckhoff** [comment]
+1 please fix it

I reproduced it in following scenarios:

1. create a new page with a block and save it with ckeditor in source mode
2. add a new block on an existing page and save it with ckeditor in source mode

**Comment by alexander-schranz** [comment]
@fdyckhoff maybe I have some time in the next week where I can finish #3827

**Comment by danrot** [comment]
Since in CKEditor5 there is no source mode anymore this can't be an issue anymore.
