### ISSUE TITLE
Custom suffix for SEO title

### ISSUE THREAD

**Issue by aureliusm** [sulu/sulu#3728]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6.11

#### Actual Behavior

There is no way to specify a custom suffix for SEO title for all pages like * | Company name*

#### Expected Behavior

There should be a way to specify such custom suffix so that one can preview it in the SERP preview and use it in the SEO extension on the frontend.

**Comment by aureliusm** [comment]
I think it would make sense to implement it on both admin interface and on the frontend. So that you can define such suffix in the SETTINGS of a specific webspace, because it affects all pages inside that webspace and then that suffix gets appended to all SEO titles. What do you think?

**Comment by alexander-schranz** [comment]
Hi @aureliusm 

Thank you for your feature request if you want to have fields on a webspace which are global available and changeable by the content manager you should hang into this issue: https://github.com/sulu/sulu/issues/3309.

If you just need a prefix in SEO use the following twig code:

```twig
{%- embed 'SuluWebsiteBundle:Extension:seo.html.twig' with {
    seo: extension.seo|default([]),
    content: content|default([]),
    urls: urls|default([]),
    shadowBaseLocale: shadowBaseLocale|default(),
    defaultLocale: request.defaultLocale|default('de')
} -%}
    {%- block title -%}
        {%- if seoTitle -%}
            <title>{{ seoTitle }} | Your Company</title>
        {%- endif -%}
    {%- endblock -%}
{%- endembed -%}
```

**Comment by alexander-schranz** [comment]
I will close this issue in favor of #3309 please give there a 👍  if you are interested in this webspace fields.

**Comment by aureliusm** [comment]
@alexander-schranz Hey, I checked issue #3309 and it doesn't solve the whole problem. I can already add the suffix in the template like you did in the code sample, but what is missing is the ability to add it in the SERP preview, because otherwise the client has an unclear picture of what will actually be seen by google. That's why I think that should be more "defined" as just a global webspace field.
