### ISSUE TITLE
Sitemap-Generation doesn't work if default_host isn't set

### ISSUE THREAD

**Issue by DavidFeller** [sulu/sulu#3732]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.12 & 1.6.13

#### Actual Behavior

The command ```bin/websiteconsole sulu:website:dump-sitemap``` doesn't create a sitemap.xml if ```{host}``` is used in the portals configuation without the parameter ```sulu_website.sitemap.default_host``` in app/config/config.yml.

![bildschirmfoto von 2018-02-01 16-07-36](https://user-images.githubusercontent.com/2094727/35690301-cf211fac-0775-11e8-9092-f2017350db90.png)

#### Expected Behavior

An exception should be thrown if the mentioned parameter is missing.

#### Possible Solutions
Set ```sulu_website.sitemap.default_host``` in app/config/config.yml by default

**Comment by oafx** [comment]
i suppose the exception would need to be added here: https://github.com/sulu/sulu/blob/e183f8fa94cbe0a11c6c7e73cdbc4dd3b7d0358b/src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumper.php#L103-L111 at line 107

**Comment by danrot** [comment]
fixed in #3736
