### ISSUE TITLE
admin preview goes blank on hitting the reload button

### ISSUE THREAD

**Issue by oafx** [sulu/sulu#3748]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.13
| Browser Version | latest chrome and firefox dev ed.

This issue is regarding the slack message by Jesper Veldhuizen: https://sulu-io.slack.com/archives/C0430GGCV/p1517922569000369?thread_ts=1517888349.000057&cid=C0430GGCV

#### Actual Behavior

Hitting the reload button in the preview pane results in an blank preview.

There are no network or js errors observable in the browsers devtools that indicate a failure.

#### Expected Behavior

Preview should be reloaded, displaying the content of the page

#### Steps to Reproduce

The issue is reproducable at the sulu.rocks demo. Navigate to the content editor of a page and hit the reload button for the preview. Tested at page /about with latest chrome and firefox dev ed.

/cc @danrot @wachterjohannes

**Comment by wachterjohannes** [comment]
@oafx thanks for reporting :) the linked PR should fix that!

**Comment by danrot** [comment]
fixed in #3750
