### ISSUE TITLE
Give user some feedback when they are trying to save a non valid form

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3749]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | all
| Browser Version | --

#### Actual Behavior

Save buttons are activated and they are clickable.
But when the form isn't valid, no message is shown that it has not been saved.

#### Expected Behavior

Maybe just show an error label with an message when the user hit the save button?
@berndhep @chirimoya 

#### Steps to Reproduce

Try to save a non valid page with an required field.

**Comment by alexander-schranz** [comment]
Error is shown now:

> Error - The form contains invalid values
