### ISSUE TITLE
Refactor component `Menu`

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3751]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | develop
| Browser Version | --

#### Actual Behavior

The component `Menu` is really stupid at the moment.

#### Expected Behavior

Refactor the component, look at the component `ArrowMenu`.

**Comment by danrot** [comment]
Maybe the `ArrowMenu` and `Menu` components should even be merged at one point, because the `ArrowMenu` only looks a little bit different. Or we should probably find a way to merge them :smiley:

**Comment by danrot** [comment]
I don't have the feeling that this is gonna change, therefore going to close it.
