### ISSUE TITLE
sulu_content_path returns url with wrong host

### ISSUE THREAD

**Issue by tniebergall** [sulu/sulu#3759]
| Q | A
| --- | ---
| Bug? | yes
| Sulu Version | 1.6.13

#### Actual Behavior

Within a snipped I have some links to different pages in different webspaces to build the navigation. 

In the Twig template for the navigation I’m setting the parameters f.e. like this:
url: /solution/design,
WebspaceKey: brand.

#### Expected Behavior

For my understanding it should return brand.de/{localization}/solution/design. But it returns the url with a different webspace then brand f.e. when visiting the support webspace in the frontend it returns support.de/solution/design instead.

**Comment by tniebergall** [comment]
@wachterjohannes

**Comment by danrot** [comment]
I just tested it, the solution is to use the `webspaceKey` parameter of `sulu_content_path`:

```jinja
{% for link in content.links %}
    {{ sulu_content_path(link.url, link.webspaceKey) }}
{% endfor %}
```
