### ISSUE TITLE
Use doctrineJoinDescriptor to join on self

### ISSUE THREAD

**Issue by andreLaposte** [sulu/sulu#3760]
| Q | A
| --- | ---
| Bug? | maybe
| Sulu Version | Last

Hi I'm using DoctrineFieldDescriptor for my API. I've already my "Product" entity's properties and it joins mapped in my FieldDescriptors.

Example : 
My getFieldDescriptors() function to get my Product entity & it joined entity "Offer" ids
`
protected function getFieldDescriptors()
{
return [
 'id'                      => new DoctrineFieldDescriptor(
                'id',
                'id',
                'MyNameSpace:Product',
                'id',
                []
            ),
            'offers'           => new DoctrineGroupConcatFieldDescriptor(
                new DoctrineFieldDescriptor(
                    'id',
                    'offers',
                    'MyNameSpace:Offer',
                    'offers',
                    $offerJoin
                ),
                'offers'
            ),
            'label'                    => new DoctrineFieldDescriptor(
                'label',
                'label',
                'MyNameSpace:Product',
                'label',
                []
            ),
[...]
}
`

However my "Product" entity have a join on itself by a join property "parent".
`
    /**
     * @ORM\ManyToOne(targetEntity="NameSpaceTo\Product",
     *     inversedBy="children", cascade={"persist"})
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     */
    private $parent; 
`

My question :
How can I join in function getFieldDescriptors() my Product entity to its "parent".

I'v try this : 

`'parent' => new DoctrineFieldDescriptor(
                    'id',
                    'parent',
                    'MyNameSpace:Product',
                    'parent',
                    'MyNameSpace:Product'
                ),
`
And it doesn't work...

**Comment by wachterjohannes** [comment]
@andreLaposte thanks for reporting this issue. have you any exception message? Or why do you know that it does not work?

**Comment by andreLaposte** [comment]
The message varies according to my tests.

Did you ever have done a join on the same entity ? If yes how did you do ?

**Comment by wachterjohannes** [comment]
actually we have see https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php#L239

**Comment by andreLaposte** [comment]
Nice it works well, thanks a lot !
