### ISSUE TITLE
Image cropping feature gives error if used without any custom image formats

### ISSUE THREAD

**Issue by nwaelkens** [sulu/sulu#3783]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.12 (but not a new problem)

#### Actual Behavior
Without defining any custom image formats in `image-formats.xml` cropping an images gives the error `Crop not possible The original image is too small`. 

#### Expected Behavior
It should crop, or give feedback like 'create custom image format first'. 

#### Steps to Reproduce
1. remove any custom images formats you have by deleting `image-formats.xml`
2. clear cache admin-kernel
3. goto >admin>media and edit an image
4. click at 'edit image' on 'crop'. 
The error is visible in a yellow beam:
<img width="870" alt="screen shot 2018-02-20 at 11 35 58" src="https://user-images.githubusercontent.com/737452/36419665-dc899fcc-1632-11e8-9b63-11ed63f3c7b9.png">

#### Possible Solutions
Quick fix: Mention this in docs (installation guide > setup at least 1 custom image format)

**Comment by wachterjohannes** [comment]
@nwaelkens will be fixed in 2.0

**Comment by alexander-schranz** [comment]
This is fixed in 2.0
