### ISSUE TITLE
Can't scroll to bottom of the language dropdown in media overlay

### ISSUE THREAD

**Issue by wynny** [sulu/sulu#3786]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.3
| Browser Version | Chrome 64.0.3282.167 (Official Build) (64-bit)

#### Actual Behavior

If the language dropdown is higher than the overlay you cant scroll to the bottom.

#### Expected Behavior

Scrolling to the bottom of the dropdown, even if there is a huge list of languages.

#### Steps to Reproduce

![screen shot 2018-02-19 at 16 34 27](https://user-images.githubusercontent.com/1161909/36432798-5e7aa756-165b-11e8-8561-571f16ce4414.png)

#### Possible Solutions

add css:

.edit-media-overlay .language-changer .husky-select-list {
    max-height: 200px;
}

**Comment by danrot** [comment]
Since there is no language dropdown in the overlay anymore this is no issue anymore.
