### ISSUE TITLE
Changing a snippets template leads to an exception when asinged to webspace

### ISSUE THREAD

**Issue by tniebergall** [sulu/sulu#3808]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.13

#### Actual Behavior

When I create a snipped with a custom template and asinged it to a webspace in the settings > snipped tab everything is fine.
When I change the template of the asinged snipped and the change to the webspace settings > snipped tab nothing appears and the log shows the following error.

`[2018-02-28 10:20:41] request.CRITICAL: Uncaught PHP Exception Sulu\Bundle\SnippetBundle\Snippet\WrongSnippetTypeException: "Wrong snippet type were detected (actual: "navigation_footer_group", expected: "navigation_footer")." at [web-root]/vendor/sulu/sulu/src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php line 114 {"exception":"[object] (Sulu\\Bundle\\SnippetBundle\\Snippet\\WrongSnippetTypeException(code: 0): Wrong snippet type were detected (actual: \"navigation_footer_group\", expected: \"navigation_footer\"). at [web-root]/vendor/sulu/sulu/src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php:114)"} []
`

#### Expected Behavior

And error message in the backend and the possibility to correct the template

**Comment by alexander-schranz** [comment]
fixed in 1.6.17
