### ISSUE TITLE
[ContactBundle] (#125) Move BankAccounts-handling from Abstract to AccountsController

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#383]
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot _from_ https://github.com/sulu-cmf/SuluContactBundle/issues/125

**Comment by alexander-schranz** [comment]
The logic seems to be in AbstractContactManager now and as both Contact and Accounts has this logic it seems for me the right place at current state.
