### ISSUE TITLE
Form for custom urls broken after the url was edited

### ISSUE THREAD

**Issue by fdyckhoff** [sulu/sulu#3838]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | v1.6.14
| Browser Version | Firefox and Chromium 

#### Actual Behavior

After a custom url is edited the Url is saved with an additional `/`. When I open the edit form after this, the form is broken and I cannot save any changes. I need to remove the custom url and create it again.

#### Expected Behavior

The custom url is not saved with an additional `/` and the form doesn't break.

#### Steps to Reproduce

1. Create a new Custom Url /foo to redirect to page "Bar". The custom url is displayed in the list as `example.org/foo`
2. Edit the redirect without any changes and save it
3. Now the custom url is displayed as `example.org//foo` (double `/`)
4. Opening the edit form results in JS Type Error. The form is broken and cannot be edited.

JS Error in Browser Console:
```
TypeError: this.customUrls[a] is undefined
```

![sulu-error-custom-url-redirect-form-after-edit](https://user-images.githubusercontent.com/14044108/37311986-a323b552-2649-11e8-9c6d-cce6081a10d9.png)

#### Possible Solutions

-

**Comment by danrot** [comment]
Fixed in https://github.com/massiveart/husky/pull/780
