### ISSUE TITLE
Add authored date to elasticsearch index

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu#3840]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6.15
| Browser Version | Browser name and version

#### Actual Behavior

Currently the authored date is missing in elasticsearch index.

#### Expected Behavior

The authored date should be available in elasticsearch index.

#### Steps to Reproduce

Take a look to elasticsearch index. The authored date of a page is missing.

#### Possible Solutions

Need to be added in `StructureProvider.php` in `sulu/sulu/src/Sulu/Bundle/ContentBundle/Search/Metadata/`.

**Comment by danrot** [comment]
Fixed in #3846
