### ISSUE TITLE
Field value will be overwritten when changing the template

### ISSUE THREAD

**Issue by tniebergall** [sulu/sulu#3853]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.15
| Browser Version | irelevant

#### Actual Behavior

When the attribute multilingual="false" of a property is set and you change the template of a language version the field value wont be loaded into the template and the save process will overwrite the value with an empty one, because it is shared over all languages.

#### Expected Behavior

The value f.e. image should be loaded when changing the template. 

#### Steps to Reproduce

Create a page with a template and create some translations. Change one language to a template which includes a property with the attribute multilingual="false", input some value and save the page. Go to another language change the templates to the one from before, the non multilingual content wont be loaded, save the page and the content is gone.

#### Possible Solutions

Load the value when changing the template or stop overwriting when the template changes and the field value is empty

**Comment by wachterjohannes** [comment]
there are 3 paces which have to be changed to fix this error:

* Add a `structure` parameter to `NodeController` and pass this to the `DocumentManager`
* Use this structure option in the `StructureSubscriber` https://github.com/sulu/sulu/blob/master/src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php#L186 to set a different `structureType`
* in the javascript component `sulucontent/conent/form` reload the data with the selected `structureType` (`template`) and use this to call `setFormData` to the form https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js#L372

**Comment by trickreich** [comment]
@tniebergall It's planned to implement this next week.

**Comment by tniebergall** [comment]
That would be perfect :-)

**Comment by alexander-schranz** [comment]
fixed in #3876
