### ISSUE TITLE
[ContactBundle] (#119) Correct REST API endpoints

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#386]
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot _from_ https://github.com/sulu-cmf/SuluContactBundle/issues/119

The REST endpoint `api/account/categories` should be something like `api/account-categories`, since there is no ID in the first version, which means it cannot be considered as sub resource.

**Comment by danrot** [comment]
This api does not seem to exist anymore.
