### ISSUE TITLE
Snippet Areas Cache Invalidation

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3869]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

No cache invalidation is triggered when a default snippet is changed.

#### Expected Behavior

That's the question..
When a default snippet is changed, it should be possible to invalidate the cache.
But what can/should happen when a snippet is set new?

**Comment by trickreich** [comment]
@alexander-schranz @wachterjohannes Maybe you have some more information to add here.

**Comment by alexander-schranz** [comment]
@sulu/core-team when we set the tag (e.g. `snippet-area-<webspaceKey>-<snippetAreaKey>`) always when `load` function of the manager is called. It can always be invalidated also when no snippet is rendered. Else this tag should be added to the reference store in the content type and in the twig extension.

**Comment by alexander-schranz** [comment]
@Prokyonn implemented tag based cache invalidation for 2.6
