### ISSUE TITLE
Texteditor Change from Sorted list to unsorted list builts <div>

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#3875]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version |1.6.16
| Browser Version | Every

#### Actual Behavior

Texteditor: first mark a textline as sorted list and then remark. you can see in editor-mode, that the text no is marked with <div>

**Comment by danrot** [comment]
Doesn't seem to happen with the new version of the CKEditor anymore.
