### ISSUE TITLE
Title of assigned pages in InternalLinks FieldType is not consistent

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#3877]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | ---
| Browser Version | ---

#### Actual Behavior

If you open a page with an `internal_links` content type included, the behavior is a little bit strange when the homepage of a webspace is entered. Directly after adding it it will have the name of the webspace shown in the listing, and after saving and reloading it will have the actual title assigned in the Homepage (by default "Homepage").

#### Expected Behavior

The behavior should be consistent if the page is assigned already or is being newly assigned.

#### Steps to Reproduce

1. Open a page with an internal link field type
2. Click the plus button to open the overlay
3. Add the homepage shown in the overlay with the webspace name
4. Click confirm
5. The homepage is now listed in the field type using the name of the webspace
6. Save the page
7. Reload the page
8. After loading the items for the field type you'll see that the name of the homepage is now whatever title it has ("Homepage" if you haven't changed it since the initialization of Sulu)

#### Possible Solutions

The problem is that the API returns the title differently in both requests (once it is "/admin/api/pages?locale=en&ids=44c991c1-044e-40e9-bbd0-03fc25035ce3,6ec0fbd4-abef-4de5-a7c1-9299aacb67a7,92615b87-3ae7-4fb8-b635-0e0f50faf5a4&page=1&flat=true" and the other time it is "/admin/api/pages?locale=en&flat=true". Passing the `ids` seem to change this behavior. I think we have to be consistent in both cases.

**Comment by niklasnatter** [comment]
Fixed by #5878
