### ISSUE TITLE
Export data from form to csv

### ISSUE THREAD

**Issue by gauquier** [sulu/sulu#3882]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6

#### Actual Behavior

When you export data to csv the Multiline Textfield data comes in different cells. Each row from the Multiline Textfield comes in a separate cell. The enclosure is now ^@ instead of ".

#### Expected Behavior

The enclosure must be " instead of ^@.

#### Steps to Reproduce

<img width="1258" alt="screen shot 2018-03-29 at 15 23 48" src="https://user-images.githubusercontent.com/22136028/38092493-ac132b08-3368-11e8-80a2-0a1cba72170c.png">

<img width="564" alt="screen shot 2018-03-29 at 14 39 19" src="https://user-images.githubusercontent.com/22136028/38092528-c91e08da-3368-11e8-8582-c02ecd9d51e8.png">

**Comment by alexander-schranz** [comment]
Can not longer reproduce this issue. So I think this is fixed.
