### ISSUE TITLE
No internal link redirection for second localization

### ISSUE THREAD

**Issue by lan-acti** [sulu/sulu#3883]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.16.16
| Browser Version | Chrome, Firefox 

Hello,
 
I’ve developed a website based on Sulu (version 1.6.16). The site is currently available in French only and I would like need to add English as another available language.
I’ve followed the documentation to add another « Localization » : http://docs.sulu.io/en/latest/book/localization.html. 
Below is the code from my Webspace file :
 
```
<localizations>
    <localization language="fr" default="true"/>
    <localization language="en"/>
</localizations>
```

And also :
```
<portals>
    <portal>
        <name>*****.com</name>
        <key>*****</key>
        <environments>
            <environment type="prod">
                <urls>
                    <url>{host}/{localization}</url>
                </urls>
            </environment>
            <environment type="stage">
                <urls>
                    <url>{host}/{localization}</url>
                </urls>
            </environment>
            <environment type="dev">
                <urls>
                    <url >{host}/{localization}</url>
                </urls>
            </environment>
        </environments>
    </portal>
</portals>
```
then I launched the command: `php bin/adminconsole sulu:document:initialize`
 

Following this action, in the back-office, I can add French and English content without issue.
On the front office, in French, when I display an internal link, the link is `href = '/my-page`.
When I click on it, I am redirected to `/fr/my-page`, and my page is displayed in French. When I test the same thing in English, I still have a link marked `href =" /my-page"` but when I click on it, the redirection is not done, I have instead  a 404 error because it doesn’t find the page `/my-page` (it should redirect me to /en/my-page).
 
Here is how I dispaly an internal link in twig :
```
{% set slider_linkbutton = sulu_content_load(slider.slider_linkbutton) %}
<a href="{{ slider_linkbutton.content.url }}">cliquez ici</a>
```

I tried many times, emptying the caches, leaving an empty database, and so on. I also ran the `php bin / adminconsole sulu: content: resource-locator: maintain` command but I didn’t  get any change.
 
Could you help me ?
Thank you.

**Comment by alexander-schranz** [comment]
Hello lan-acti,

you are missing the [sulu_content_path](http://docs.sulu.io/en/latest/reference/twig-extensions/functions/sulu_content_path.html) twig extension: 

```
{{ sulu_content_path(slider_linkbutton.content.url) }}
```

This will add the correct url prefix based on your webspace configuration. So everytime when you render a sulu url you need to call this twig extension currently on that url.

See also the [Navigation Example](http://docs.sulu.io/en/1.2/book/creating-a-basic-website/creating-a-twig-template.html#navigation).

**Comment by lan-acti** [comment]
Hello @alexander-schranz, 

Thank you for your help. 
I had indeed forgotten to use this function. 
Now everything works fine. 

Thanks again,
