### ISSUE TITLE
[ContactBundle] (#97) adapt tests for import

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#389]
<a href="https://github.com/turbo-ele"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/5152633?v=2" /></a>
By @turbo-ele *from* https://github.com/sulu-cmf/SuluContactBundle/issues/97

the import is extended continiously. the test files should be adapted as well

**Comment by danrot** [comment]
The import has been moved to the ContactExtensionBundle, so that has no validity anymore.
