### ISSUE TITLE
[ContactBundle] (#96) validate the conversions from account in the API

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#390]
<a href="https://github.com/michaelzangerle"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1465587?v=2" /></a>
By @michaelzangerle _from_ https://github.com/sulu-cmf/SuluContactBundle/issues/96

https://github.com/sulu-cmf/SuluContactBundle/pull/93/files#diff-1f341b23820a13aa8bc76c73691430a0R119

" i think a request like /accounts/[account id]/convertto/[type id] with a validation would be fine"

**Comment by danrot** [comment]
Doesn't sound like this still exists in Sulu 2.0
