### ISSUE TITLE
Remove hardcoded `/admin` from whole frontend

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3904]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0
| Browser Version | --

#### Actual Behavior

On some places the url to the backend is hardcoded in the frontend application.

#### Expected Behavior

Everything should be dynamically created. It should be possible to change the `/admin` prefix in the admin.

**Comment by danrot** [comment]
Fixed in #4007
