### ISSUE TITLE
[ContactBundle] (#86) Navigating contact list through form

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#392]
<a href="https://github.com/turbo-ele"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/5152633?v=2" /></a>
By @turbo-ele _from_ https://github.com/sulu-cmf/SuluContactBundle/issues/86

when in contact form, it would be nice to be able to navigate through contacts that have been shown before in list overview. (next, back button in header)

**Comment by danrot** [comment]
Related to https://github.com/sulu-cmf/sulu-standard/issues/159 /cc @berndhep

**Comment by berndhep** [comment]
@danrot We've added a solution for that to the Backlog. It's not a 1.0 feature.

**Comment by danrot** [comment]
I don't think that this is coming, as I can't remember it was requested again. Therefore going to close it.
