### ISSUE TITLE
FieldDescriptors XML changes need a hard cache clear

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3944]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | all
| Browser Version | --

#### Actual Behavior

After changing a field descriptor, the developer needs to hard clear the cache.

#### Expected Behavior

In non production env no cache clear should be needed.
Also StructureMetadata etc. should be generated correctly.

**Comment by danrot** [comment]
Just tested, no hard cache clear was necessary after changing the field descriptors.
