### ISSUE TITLE
User with view only role, can delete drafts

### ISSUE THREAD

**Issue by wmschram** [sulu/sulu#3948]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Sulu Version | 1.6.10
| Browser Version | Chrome 66

#### Actual Behavior

When i login as a user with only 'view' rights, that user is able to delete a draft.
Example: user logs in while having only the role 'viewer'. That person opens a concept page (draft). That user then receives a yellow warning that he/she is viewing a draft. The user can then click on the button 'delete draft'. The draft is now deleted. 

#### Expected Behavior

The user should receive a permission error the moment he/she tries to delete the draft.

#### Steps to Reproduce

Create a new user role and on each setting select only "view" and nothing else. Save the user role.
Create a new user and give this user the just newly create user role. Make sure you don't give it any other roles as well!
Login as this new user, and try to delete a draft.

**Comment by danrot** [comment]
@wmschram Thanks for reporting! #3949 should deal with that.

**Comment by danrot** [comment]
fixed in #3949
