### ISSUE TITLE
[ContactBundle] (#77) import: trim data

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#396]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes *from* https://github.com/sulu-cmf/SuluContactBundle/issues/77

to find in some imported names with a ending space!

**Comment by danrot** [comment]
Import has been moved to the SuluContactExtensionBundle, and is not in this repository anymore.
