### ISSUE TITLE
Template switching not working correctly when having different block types between templates

### ISSUE THREAD

**Issue by StaffNowa** [sulu/sulu#3961]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.18

#### Actual Behavior

1. I created a couple of XML pages in app/Resources/pages/*.xml with different block types between templates.
2. I opened the current page of webspace that was already in use own page template and already have blocks.
3. For example I am trying to change Internal page to Example page (XML).

#### Expected Behavior

What is the behavior you expect?
The system does not change page template, but throw exception "The block type "image_big" has not been registered. Known block types are: [editor, editor_image]"

#### Steps to Reproduce

1. I created a couple of XML pages in app/Resources/pages/*.xml with different block types between templates.
2. I opened the current page of webspace that was already in use own page template and already have blocks.
3. For example I am trying to change Internal page to Example page (XML).

**Comment by alexander-schranz** [comment]
Example:

<details>
<summary>Template A</summary>

```xml
        <block name="blocks" default-type="hello">
            <types>
                <type name="hello">
                    <properties>
                        <property name="test" type="text_line">
                            <meta>
                                <title lang="de">Hello</title>
                            </meta>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
```
</details>


<details>
<summary>Template B</summary>

```xml
        <block name="blocks" default-type="info">
            <types>
                <type name="info">
                    <properties>
                        <property name="test" type="text_line">
                            <meta>
                                <title lang="de">Info</title>
                            </meta>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
```
</details>

1. Save Page with Template A which includes block hello
2. Try to switch to Template B -> will crash with `The block type "hello" has not been registered. Known block types are: [info]`

**Comment by alexander-schranz** [comment]
This issues seems to exist before but was only thrown when saving: #3429.
The block was rendered as default type but the type was not replaced. The content manager had here the possibility to delete the corrupt block but if you had many blocks it would not be possible for him to find which one was the corrupt one.
