### ISSUE TITLE
Rename checkbox field type to toggler

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#3992]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | ---
| Browser Version | ---

#### Actual Behavior

We currently have a `checkbox` field type, which can be displayed either as a toggler or a checkbox.

#### Expected Behavior

We have defined that this content type should always be displayed as a toggler. So the content type should be renamed to `toggler` instead of `checkbox`, and the `type` option in the XML should not exist anymore. This will improve the consistency of our forms.

#### Steps to Reproduce

1. Add a template with a `checkbox` field
2. Open a page with that template and see that the `checkbox` field is displayed as checkbox instead as toggler.

#### Possible Solutions

Rename both the `checkbox` field and content type to `toggler` and remove the `type` option from it.

**Comment by alexander-schranz** [comment]
As we didn't change this I will close this one.
