### ISSUE TITLE
Replace all urls in preview should be avoided

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3996]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6

#### Actual Behavior

The current implementation of replace urls in preview crashes instagram embeds and content manager can not longer test if the links works.

#### Expected Behavior

Should not crash instagram embeds and links should be render normal.

#### Steps to Reproduce

Try to click a url in the preview.

#### Possible Solutions

1. Only replace {host} with the current default host (replace `http://{host}` with nothing so it will be linked to current domain (because websocket has no current domain to used as replace))
2. Add `target="_blank"` instead of replace all urls with `#` (optional)

**Comment by danrot** [comment]
@alexander-schranz Wasn't that already fixed in #4027? Please reopen if I am wrong.
