### ISSUE TITLE
Change article typ

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#4010]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes, perhaps
| Sulu Version | 1.6
| Browser Version | doesn't depand

#### Actual Behavior

If you are using differtent types in the article modul and you create an article in a wrong type it is not possible to move the article in to another typ.

#### Expected Behavior

would be nice, to change the article typ in case you have created it wrong

**Comment by alexander-schranz** [comment]
This issue does not belongs to sulu core. It belongs to the [SuluArticleBundle](https://github.com/sulu/SuluArticleBundle): 

In the article bundle a similar issue can be found  here: https://github.com/sulu/SuluArticleBundle/issues/280
