### ISSUE TITLE
Remove .html.twig from webspace templates definitions

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4012]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | for 2.0

#### Actual Behavior

Actually it is not possible to get for example the search page as json or another format. Also I can't create custom error pages for .xml, ...

#### Expected Behavior

It should possible to create search and error pages in any request format.

#### Steps to Reproduce

Try to create a `search.json.twig` file. And access the search page.

#### Possible Solutions

```xml
    <templates>
        <template type="search">search</template>
        <template type="error">error</template>
    </templates>
```

```php
$webspace->getTemplate('error') . '.' . $request->getRequestFormat() . '.twig';
```

**Comment by danrot** [comment]
This has been implemented.
