### ISSUE TITLE
Save issue with organizations without setting longitude/latitude

### ISSUE THREAD

**Issue by RaphaelHofer** [sulu/sulu#4015]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.18
| Browser Version | ~

#### Actual Behavior

If you are using mysql version 5.7 and want to add an address to an organization without longitude and latitude Sulu throws an error in the network log:
```
An exception occurred while executing 'UPDATE co_addresses SET latitude = ?, longitude = ? WHERE id = ?' with params ["", "", 2]:SQLSTATE[01000]: Warning: 1265 Data truncated for column 'latitude' at row 1
```

#### Expected Behavior

Possibility to add an address without longitude and latitude.

#### Steps to Reproduce

Use Mysql version 5.7:
Steps to reproduce see actual behavior.

#### Possible Solutions

On first view MySQL 5.7 doesn't convert empty strings to null, probably a conversion of empty strings to a null value would fix it.

**Comment by alexander-schranz** [comment]
@RaphaelHofer fixed in #3950 which was released with 1.6.19
