### ISSUE TITLE
Saving a snippet in a new language conflicts

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4016]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.6 (show conflict overlay), 1.6.18 (loading forever, ...)

#### Actual Behavior

When you switch inside a snippet to a not exist language it will load the data from the other language and will conflict when save it in the new language.

#### Expected Behavior

Should not conflict as the snippet was never saved in that language. Also when a conflict appears on 1.6.18 the confict overlay is not shown.

#### Steps to Reproduce

1. Save a snippet in EN
2. Switch language to DE
2a. (will not show copy language overly or something else)
2b. (will load content of EN which should not happen)
3. Save snippet
3a. Save request will save with conflict
3b. Under 1.6.18 conflict overlay is not shown.

**Comment by danrot** [comment]
Closed in #4018
