### ISSUE TITLE
Can't modify "creation-date" of entries (Safari)

### ISSUE THREAD

**Issue by pascalMartilotti** [sulu/sulu#4019]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.16
| Browser Version | Safari 11.1 (13605.1.33.1.2)

#### Actual Behavior

It is not possible to modify the date of creation of an entry/post. (publication, event, announcements)
Safari doesn't display the creation date/time when editing an entry in the sulu admin-page, it only shows "NaN.NaN.0NaN NaN:NaN". In the edit-modal however, only the timepicker is not working and shows "NaN:NaN". The datepicker is fine and the date is displayed correctly as well. However it is not possible to save the entry because JavaScript is crashing.

- This issue only occurs with Safari

#### Expected Behavior

The entry (event, publication, announcement) can be modified. 
Date and time is displayed in the admin-page and edit-modal.

#### Steps to Reproduce

0) use Safari and log in as administrator
1) Go to Content
2) edit a single Entry (publication for example)
3) Go To the "Settings"-Tab
-- on the bottom of the page, you can see the first error regarding "NaN" when you take a look at the changelog --
4) Click the edit-symbol in the Changelog
--  in the edit-modal you can see the "NaN" on the right side at the timepicker --
5) Click OK and try to save the Entry

**Comment by alexander-schranz** [comment]
Think the problem has todo with the changes in the PR where the time was added to the authored field maybe this line errors on safari: https://github.com/sulu/sulu/pull/3626/files#diff-fb30f8d7e8a35ad25793218867efb57bR155
