### ISSUE TITLE
urls variable return different result for static routes and content pages

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4061]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | <= 1.6, dev-develop
| Browser Version | All

#### Actual Behavior

`urls` Variable result for content pages:

```json
[
    'de' => '/page',
    'en' => '/page',
]
``` 

`urls` Variable result for static routes:

```json
[
    'de' => '/de/static',
    'en' => '/en/static',
]
```

As a language switcher uses `sulu_content_path` this ends up in `/de/de/static`

#### Expected Behavior

The template attributes resolver should only return end path for static routes:

```json
[
    'de' => '/static',
    'en' => '/static',
]
```

#### Steps to Reproduce

1. Webspace with {localization} in its path:

2. Render a static type: portal route with:

```php
return $this->render(
    $view,
    $this->get('sulu_website.resolver.template_attribute')->resolve([]),
    $response
);
```

3. Implement the language switcher the same way you would do it for content pages:

```twig
{% for locale, url in urls %}
    {{ sulu_content_path(url, null, locale) }}
{% endfor %}
```

#### Possible Solutions

The error is in https://github.com/sulu/sulu/blob/6e5dbca08a8c10ec33643d521b8f2e977458ed57/src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php#L122-L153 that should return only the last part of the route: `/static` without language prefix and domain to be equal to the current urls variable for content pages.

**Comment by danrot** [comment]
@alexander-schranz Isn't that the same issue as #4118 ?

**Comment by alexander-schranz** [comment]
Fixed that static routes now return a full absolute url since #4571
