### ISSUE TITLE
Live preview not always updated

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4075]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.21, Sulu 2.0-pre-alpha1

#### Actual Behavior

Live preview not always updated.

#### Expected Behavior

Live preview should be updated always when changing things.

#### Steps to Reproduce

- [x] **Add or remove single internal link**

When a single internal link is changed live preview is not updated

- [x] **Images not updated (maybe only when render with twig extension)**

1. Use `get_image` from [MassiveTwigExtension](https://github.com/massiveart/web-twig/blob/master/docs/image.md) to render an image the image is not updated.

- [x] **Add new block**

1. When add a new block the live preview is not updated

- [x] **Add text to not yet render field**

2. If the field is not yet render the preview seems not be updated

**Comment by wachterjohannes** [comment]
will be fixed by #3592
