### ISSUE TITLE
Moving block with text editor will initialise text editor and still show the textarea

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4089]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | <= 1.6.21
| Browser Version | Tested on Opera 54

#### Actual Behavior

When you move a block with a texteditor in it the texteditor is initialise but the textarea ist still there:

![bildschirmfoto 2018-08-02 um 10 45 33](https://user-images.githubusercontent.com/1698337/43573086-391d8918-9641-11e8-880d-b40881a9d9c6.png)
 

#### Expected Behavior

The texteditor should not been getting initialised when moving a block.

#### Steps to Reproduce

Move a block with a not initialised texteditor. 

#### Possible Solutions

1. Solution: Texteditor should not been initialised
2. Solution: Textarea should also be removed when initialise over block move.

**Comment by niklasnatter** [comment]
I am going to close this as Sulu 1.6 receives critical fixes only and this is not a problem on Sulu 2.0 anymore. Hope that is okay for you 🙂
