### ISSUE TITLE
 Unknown function "preload" in "SuluAdminBundle:Admin:main.html.twig"

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#4091]
| Q | A
| --- | ---
| Bug? | yes
| Sulu Version | 676388dc8a737d9936b27872c6d7ede7be7064e0

#### Steps to Reproduce
We use a VM and in my composer.json `"sulu/sulu": "^2.0@dev",` is used.
Just did a fresh install 3 times and it fails.

#### Possible Solutions
alexander did write on slack to do:

`framework:
    web_link: ~`

**Comment by alexander-schranz** [comment]
We should preconfigure it in the AdminBundle to enable web_link or check if web_link is available.

**Comment by danrot** [comment]
Hm... From what I know Symfony realizes on its own if the server supports HTTP2 pushes, and acts accordingly. Is there any reason somebody might want to deactivate that? If not I would say we use a `PrependExtension` to set that.

**Comment by alexander-schranz** [comment]
Symfony itself just set the `Link` header and browsers ignore that if the server don't provide content over http2 so the only thing why you want disable it if you don't want that the [WebLinkResponseListener](https://github.com/symfony/symfony/blob/da3845668f362ec1a13baa5b252072f4ad210aa7/src/Symfony/Component/WebLink/EventListener/AddLinkHeaderListener.php) is called maybe for minimal performance reasons?

But I also think we don't have a big performance improvement on that little page which only assets is a css and js, where no other assets block requests so for me it would also be ok just remove the `preload` functions there so we don't have a web_link dependency.

**Comment by danrot** [comment]
I think I would still leave it. The [specification](https://www.w3.org/TR/preload/) sounds like it is more than just an early fetch:

> For example, the application can use the preload keyword to initiate early, high-priority, and non-render-blocking fetch of a CSS resource that can then be applied by the application at appropriate time.

AFAIK it also is able to send the request quite a bit earlier, because the document does not have to be parsed first. And `rel="preload"` AFAIK only works with links, but not with script tags, that's why the WebLink component is required.

I'd say we add this setting using a `PrependExtension`.

**Comment by danrot** [comment]
I just had a look, and I have seen that the `web-link` component is enabled by default... So this only does not work if somebody sets this `enabled` flag to false manually. And if this is done in the YML config, then a `PrependExtension` also doesn't help... And I haven't found an easy solution to check if the method exists :confused: `defined` seems only to work with variables, not with functions.

**Comment by alexander-schranz** [comment]
@danrot it not always enabled it depends if using fullstack symfony or not: https://github.com/symfony/symfony/blob/f50e17fa4edd6216f7fe5b908f04e64ba1d19a9e/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L955

**Comment by danrot** [comment]
Interesting... So a `PrependExtension` would stil make sense, but could also be overridden. However, I think if somebody overrides that value it is their fault :see_no_evil: I am quickly making a PR.
