### ISSUE TITLE
Setting Ip Address in URL Content Type not possible

### ISSUE THREAD

**Issue by M0TT3P** [sulu/sulu#4096]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.21
| Browser Version | Google Chrome Version 68.0.3440.84 (Offizieller Build) (64-Bit)

#### Actual Behavior

The input gets a red border.
Saving the snippet is not possible.

#### Expected Behavior

Saving should be possible

#### Steps to Reproduce

Go to snippets->add snippet->
title: test
description:text
url: http://10.100.0.1:8080/weblogin.htm

**Comment by alexander-schranz** [comment]
Hello @M0TT3P,

can you add your snippet.xml definitions?

**Comment by M0TT3P** [comment]
`<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <meta>
        <title lang="en">Default</title>
        <title lang="de">Standard</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

            <tag name="sulu.node.name"/>
        </property>

        <property name="description" type="text_editor">
            <meta>
                <title lang="en">Description</title>
                <title lang="de">Beschreibung</title>
            </meta>
        </property>

        <property name="url" type="url">
            <meta>
                <title lang="en">Url</title>
                <title lang="de">Url</title>
            </meta>

            <params>
                <param name="schemes" type="collection">
                    <param name="http://"/>
                    <param name="https://"/>
                </param>
            </params>
        </property>

        <property name="images" type="media_selection">
            <meta>
                <title lang="de">Bild</title>
                <title lang="en">Image</title>
            </meta>

            <params>
                <param name="types" value="image"/>
                <param name="formats" type="collection">
                    <param name="240x160" />
                </param>
            </params>
        </property>
    </properties>
</template>
`

**Comment by alexander-schranz** [comment]
@M0TT3P ok seems just todo with the URL Content type. Until this bug is fixed you can just use the `text_line` and later when this works you can change it back to `url`.

**Comment by alexander-schranz** [comment]
The bug seems to be in this regex in husky: https://github.com/massiveart/husky/blob/5b4cceb14179fa26c347e371530cd05b8c77026f/husky_services/url-validator.js#L15 
It seems not allowing private IP addresses which should really be changed.

**Comment by danrot** [comment]
Works in Sulu 2.0.
