### ISSUE TITLE
Multiple Webspace Ordering in Admin Backend

### ISSUE THREAD

**Issue by Rowanism** [sulu/sulu#4099]
Q | A
------------ | -------------
Bug? | no
New Feature? | no
Sulu Version | <= 1.6.13
Browser Version | All

#### Actual Behavior

Sorting multiple webspaces in the admin panel is only possible through the following methods:
- Prepending numbers to webspace filenames `0-name.xml`, `1-name.xml`, `2-name.xml` etc.
- Prepending letters to webspace keys `A_name`, `B_name`, `C_name`

#### Possible Solutions

- Provide documentation for either method in the official docs
- Introducing a numerical sortindex tag for webspaces
- Providing a sorting feature for webspaces like for pages

**Comment by danrot** [comment]
@Rowanism We currently don't have a high priority on this feature, but if you are willing to create a PR on your own, we might merge it. However, before you start we would have to define first how the XML structure should look like.

**Comment by niklasnatter** [comment]
Since https://github.com/sulu/sulu/pull/5532, webspaces are sorted by the webspace name per default 🙂
