### ISSUE TITLE
301 Redirect urls with trailing slash and query parameters

### ISSUE THREAD

**Issue by simpliste** [sulu/sulu#4103]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.21
| Browser Version | Chrome Version 68.0.3440.106

#### Actual Behavior

Urls ending with a slash are redirected to urls without a slash. For example the url https://sulu.rocks/en/contact/ is redirected with 301 to https://sulu.rocks/en/contact. 

When the url that ends with a slash has query parameters so https://sulu.rocks/en/contact/?source=google it is also redirected with a 301 to https://sulu.rocks/en/contact without the query parameters.

#### Expected Behavior

I expect urls ending with a slash to be redirected to urls without a slash but the query parameters should me maintained. 

For example https://sulu.rocks/en/contact/?source=google should be redirected with a 301 to https://sulu.rocks/en/contact?source=google

#### Steps to Reproduce

See: https://sulu.rocks/en/contact/?source=google

**Comment by trickreich** [comment]
@simpliste Sadly we have currently no resources to fix this. Maybe you can create a PR and fix it?
Or you can fix it with nginx/apache rewrite rules for now?

**Comment by simpliste** [comment]
@trickreich We fixed it with a nginx rewrite for now. When i have time i will look into it and create a pr. 

For people running into the same problem, you can fix it by changing the nginx configuration [provided](http://docs.sulu.io/en/latest/cookbook/web-server/nginx.html) by sulu with the following changes:
`
location / {
	# Urls ending with a slash and get parameters are redirected to urls without a trailing slash and get parameters are lost
	rewrite ^/(.*)/$ /$1 redirect;
        index website.php;
        try_files $uri @rewritewebsite;
    }
`

Keep in mind that that the /admin/ url actually ends with a slash so you can not add it for all locations, because this will result in a redirect loop for /admin/. So put the rewrite in the location block specified above.

**Comment by debreczeniandras** [comment]
@chirimoya @wachterjohannes I also ran into the issue, and already fixed it locally.
Can I open a PR or somebody already started working on it?

**Comment by wachterjohannes** [comment]
@debreczeniandras of course - you can simply open a pull-request and we will review it. if there are problems we can guide you to the necessary parts of the system

**Comment by debreczeniandras** [comment]
The hotfix PR is now ready. Can somebody review it?
Should I open another pull request for the 1.5 branch?

**Comment by danrot** [comment]
@debreczeniandras I already commented that in your PR: Please only open a PR against the 1.5 branch, we well merge that back to master and develop on our own when we do the release anyway :-)

**Comment by danrot** [comment]
Fixed in #4207
