### ISSUE TITLE
Remove analytics-key attribute from webspace url

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4117]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 2.0.0-alpha1

#### Actual Behavior

Currently there exist the `<url analytics-key="test">` in the webspace configuration. This was some time ago replaced with analytics tab on the Webspace settings.

#### Expected Behavior

We should remove the analytics configuration from the websapce as it is recommended using the analytics tab instead.

#### Possible Solutions

Remove the attribute from the xml xsd and from the webspace/portal url object and also remove from the `request.analyticsKey` in twig.

**Comment by danrot** [comment]
Seems like these properties have been deleted :slightly_smiling_face:
