### ISSUE TITLE
A symfony portal route contains the resource-locator-prefix in the urls array 

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#4118]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | at least ^1.5
| Browser Version | none

#### Actual Behavior

Sulu generates the `urls` array for custom Routes in `TemplateAttributeResolver` with the resource-locator-prefix. 

#### Expected Behavior

The resource-locator-prefix should not be generated there to be consistent with pages.

#### Steps to Reproduce

create a webspace with prefix `/{localization}` and dump the routes on a custom route.

```twig
{%- for locale, url in urls -%}
    <a href="{{ sulu_content_path(url, null, locale) }}">
        {{- locale -}}
    </a>
{% endfor %}
```

#### Possible Solutions

The problem is that the schema of the route contains this prefix - so the router generates it with this prefix. So currently I have no idea how to solve this.

**Comment by alexander-schranz** [comment]
https://github.com/sulu/sulu/blob/fe6eb5441913b0102ee932c191fc409ac91245af/src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php#L137-139

Replace this with: 

```php
if (isset($routeParams['prefix'])) {
    $routeParams['prefix'] = '';
}
```

would fix the generated urls

**Comment by alexander-schranz** [comment]
duplicated issue: #4061
