### ISSUE TITLE
Deep Link from teaser selection to actual item.

### ISSUE THREAD

**Issue by luca-rath** [sulu/sulu#4127]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6.19
| Browser Version | Google Chrome 68.0.3440.106

#### Expected Behavior

There should be links in the teaser selection to the selected items.

#### Steps to Reproduce

- Add teaser selection to template
- Select some entities in admin surface

**Comment by danrot** [comment]
What links are you talking about? Do you want to get to the form of the linked element if you click it in the teaser element? Can you maybe add a screenshot, to make absolutely sure we are on the same page?

**Comment by luca-rath** [comment]
I would like to have a button in each element in a teaser selection which leads me to the details page / edit page of that element.
![bildschirmfoto 2018-09-14 um 09 34 00](https://user-images.githubusercontent.com/5758674/45536317-698b1200-b801-11e8-8979-7ae579926fde.png)
This could be e.g. such an icon or something like that.
