### ISSUE TITLE
Return full phpcr path instead of relative to webspace node

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4128]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | for 2.0

#### Actual Behavior

Actually the `path` in twig return the relative path to the webspace node. This mostly make the problem that the `path` is mistaken as `url`.

#### Expected Behavior

If we return the full phpcr path this will not longer be mistaken as url and the developer can better work with the phpcr path.

**Comment by danrot** [comment]
Do we have any places where we use the path? IMO we should actually get rid of this value, since it serves no real purpose (at least none I know of), and it couples us more to PHPCR than necessary.
