### ISSUE TITLE
Users can't change their own contact without being able to change all of the contacts

### ISSUE THREAD

**Issue by cdellamonica** [sulu/sulu#4131]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6.21
| Browser Version | any

#### Actual Behavior

Users without rights on "Contacts > people" don't have access to their own contact and can't change their password. In a corporate environnement it represents a security threat.

#### Expected Behavior

One should be able to edit his contact and change his password without being a contacts admin.

#### Steps to Reproduce

Login with a user that does not have a role with the permission "Contacts > people" checked in. Click on the username  in the menu.

#### Possible Solutions

There could be an additional permission "contact > self" that could enable access only to your own contact.

**Comment by danrot** [comment]
That's something we plan to add in a 2.x release. Are you planning to upgrade anyway? Or do you really need that feature in the 1.x series?

**Comment by cdellamonica** [comment]
Hello Dan, it's good to know the feature is planned for 2.x. We are planning to upgrade, although it might be a long work as we are hosting 50+ sites on the platform. Right now, we ask our staff to change their password using the "I forgot my password" feature.

**Comment by danrot** [comment]
This feature has been implemented in #4615 :tada:

**Comment by cdellamonica** [comment]
Awesome ! Thanks 🥳
