### ISSUE TITLE
ResourceTabs view uses all router attributes on navigate

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#4138]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Alpha 2.0
| Browser Version | --

#### Actual Behavior

Currently the `ResourceTabs` view is using all available router attributes.
https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js#L60

This can cause in heavy exception, for example with two datagrids when the `sortColumn` parameter is set.

#### Expected Behavior

To be discussed. Maybe throw away all GET parameter?

**Comment by danrot** [comment]
While thinking of it... When we would fix #4139 this issue wouldn't be so bad anymore, right? Adding some configuration makes things more complicated, and people probably forget it anyway. But maybe there are other problems regarding the `ResourceTab` navigation in other situations, which are not solved that easily...

**Comment by danrot** [comment]
We have added the `RouterAttributesToBlacklist` option in order to allow to filter attributes that might make problems.
