### ISSUE TITLE
Datagrid crashes when `sortColumn` is not available

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#4139]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

When opening a link with `sortColumn=abc` and the column `abc` doesn't exists, the request made by the datagrid crashes and therefore the whole frontend crashes as well. 

#### Expected Behavior

I think the datagrid could remove the parameter if the column does not exist, because it should know of all columns.

Somewhere here:
https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js#L103

https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js#L106

**Comment by danrot** [comment]
The datagrid does not crash anymore, therefore going to close that issue.
