### ISSUE TITLE
Disabled cache environment are hardcoded

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4141]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 2.0.0-alpha-3

#### Actual Behavior

Currently the environments where the cache is disabled are hardcoded see: https://github.com/sulu/sulu/blob/80c99e5ee1fe4645246ecfda06cc6da45a4e09e0/src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php#L117-L120

#### Expected Behavior

We should use `canBeDisabled` configuration and use PrependConfigurationExtension instead with `kernel.debug` as default or better provide a default based on the env to don't crash the old behaviour.

**Comment by nnatter** [comment]
I think this should be fixed via #5303?

**Comment by alexander-schranz** [comment]
@nnatter yes this is fixed.
