### ISSUE TITLE
Default property values per template

### ISSUE THREAD

**Issue by aubryfr** [sulu/sulu#4165]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | `1.6.20`
| Browser Version | Any

#### Actual Behavior

No feature at the moment, as confirmed by @trickreich (see [Slack thread](https://sulu-io.slack.com/archives/C0430GGCV/p1536159313000100) )

#### Expected Behavior

I would like to be able to define default settings for a certain type of page.

For example, if I have a "Landing Page" template, I would like to define that the "Hide in sitemap" option under "SEO" will be checked by default (currently is unchecked).

#### Steps to Reproduce

N/A

#### Possible Solutions

I haven't thought about it.

**Comment by alexander-schranz** [comment]
related to #1133 not sure if we should keep both issues? /cc @danrot

**Comment by danrot** [comment]
Yeah, that's definitely exactly the same, so we can close this as duplicate... @aubryfr You are welcome to give the other issue a thumbs up :-)
