### ISSUE TITLE
Search snippets by template type

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#4171]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

I can search snippets only by name

#### Desired Behavior

Something like the Article bundle does for the various article types. Tabs, full text search, anything is better than nothing :)

**Comment by alexander-schranz** [comment]
same as #3235 please give an upvote there
