### ISSUE TITLE
[ContentBundle] Naming conflict = type (shadow, ghost) and type (page, snippet)

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#418]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes _from_ https://github.com/sulu-cmf/SuluContentBundle/issues/271

https://github.com/sulu-cmf/SuluContentBundle/commit/64fa2957e75635969b925b39e7e42195e749e2a2

**Comment by danrot** [comment]
I think we have discussed multiple times in the mean time that type is something that has always to be considered in its context... Therefore going to close this one.

And if we do something about it, it will be probably in 3.0 anyway, which will be a bigger refactoring anyway.
