### ISSUE TITLE
[ContentBundle] Extract 'excerpt' to config or at least to a constant

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#419]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes _from_ https://github.com/sulu-cmf/SuluContentBundle/issues/266

https://github.com/sulu-cmf/SuluContentBundle/pull/265#discussion_r19087559

**Comment by danrot** [comment]
Sounds to me like having the excerpt in a separate XML file is the solution to this, so I guess this is not relevant anymore.
