### ISSUE TITLE
Regenerate resource locator slug based on new page title

### ISSUE THREAD

**Issue by DavidFeller** [sulu/sulu#4221]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6x
| Browser Version | all

#### Actual Behavior

When you copy a page from one language to another and change the page's title afterwards, the resource locator/slug has to be changed/set manually. 

#### Expected Behavior

There should be a way to (re)generate the slug based on the new title to prevent users from trying to e.g. type in a slug with special characters or umlauts.

#### Steps to Reproduce

Add a new page, give it a title in one language (the slug ist generated automatically) and save/publish the page. Copy the page to another language/locale, change the page's title.

#### Possible Solutions

Add an event listener that (re)generates the page's slug whenever the title field is changed. Perhaps there could be a parameter in the config to enable/disable this feature.

**Comment by danrot** [comment]
We definitely don't want to update the title always - that would generate too many URLs, and might cause other pages to get worse URLs with a number appended... But a regenerate button or something like that could be an idea to solve this...Would have to talk to our designers first about where to place it :-)
