### ISSUE TITLE
Load data for select FieldType using a Symfony service

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#424]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes _from_ https://github.com/sulu-cmf/SuluContentBundle/issues/222

Configurable over:
- service with interface (called from twig with webspace and locale)
- nesting params (property params)

**Comment by danrot** [comment]
Already implemented checkbox and radio groups, which can simply be filled by data in the xml template. Still missing:
* selects
* load data from services

**Comment by tniebergall** [comment]
Are there any updates for this content type?

**Comment by wachterjohannes** [comment]
@tniebergall TBH not really :) there is a part implementation for checkbox and radios but for select there is currently no solution

**Comment by danrot** [comment]
This has been implemented in the mean time :slightly_smiling_face:
