### ISSUE TITLE
Move edit icons to the right of item listing tables.

### ISSUE THREAD

**Issue by ADmad** [sulu/sulu#4244]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | maybe
| Sulu Version | 2.0.0-alpha4

#### Actual Behavior

Currently when you hover over a row, the pencil icon to edit record in shown on left hand side of the row.

Since it's common to have action icons/links on the right hand side I always find myself moving the cursor to the right side by muscle memory and then having to move cursor to left side to click the icon.

#### Expected Behavior

Personally I prefer having action links on right hand side.

#### Possible Solutions

1. Move the action icons to right hand side by default
2. Allow the positioning of action icons to be configurable.

**Comment by danrot** [comment]
Do you have any resources to back up that claim? I've seen a lot of tables where these icons are on the left side, and having it on the right side would have two major drawbacks for me:

1. The navigation is on the left side, so when you navigate to a table, and then want to go to a form, you have a very short distance from your cursor to these action buttons. If you put it on the right side, you always have to move your cursor across the entire screen.
2. Having the actions on the left has the advantage that the most important column - the first one - is the closest one to the buttons. If the buttons are on the right, there is a huge whitespace first, and then the next column is the date or something, which is bad at showing what the current row holds.

So I don't see us moving these actions to the right. However, a solution that might also work for you, is to enable double clicks on the row. Then you could get to the form from any position on the row. That would mean the `dblclick` callback would have to be used in our `Table` component and our [`TableAdapter` for the `Datagrid`](https://github.com/sulu/sulu/blob/d05ae70/src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js#L36) would have to call the `onItemClick` callback then.

We've planned to do that anyway, but if you are willing to create a PR for that it would be very welcome :slightly_smiling_face:

**Comment by ADmad** [comment]
I guess enough examples can be provided for both cases. For e.g Drupal has action links on right side while Wordpress shows them below the item title in 1st column on left side.

I don't have any arguments against the reasons you have provided for keeping them on left side. 
I concede it boils down to personal preference and what an individual is more accustomed to, hence closing the issue :slightly_smiling_face:
