### ISSUE TITLE
[ContentBundle] Include "more link text" to smart content config

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#426]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes _from_ https://github.com/sulu-cmf/SuluContentBundle/issues/202

**Comment by danrot** [comment]
This text has to be added to the excerpt already, so I think it doesn't make any sense anymore to put it in the smart content config as well.
