### ISSUE TITLE
Twig sulu_categories throws exception if category with parent key does not exist

### ISSUE THREAD

**Issue by AndreasA** [sulu/sulu#4270]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-develop (59812040b20170d5000b79a734d84670d3994202)
| Browser Version | Chrome 70

#### Actual Behavior

When using sulu_categories with a parent key that does not exist then the thrown exception is passed on to the frontend. Normally the searched for parentKey does exist but if it does not, it shouldn't break the whole frontend.

#### Expected Behavior

If the parent key is not found then it should just return an empty array.

#### Steps to Reproduce

{% sulu_categories(app.request.locale, 'missing-category-key') 

#### Possible Solutions

Catch the exception CategoryKeyNotFoundException and return an empty array instead.

**Comment by danrot** [comment]
Usually we are a bit careful with hiding errors like this, because it makes it hard to find real bugs in your application. However, in this case I think I would do it like you've suggested, because this would also break the page if the content manager deletes the category with the given key, am I right?

**Comment by AndreasA** [comment]
I agree, that one shouldn't hide errors but that is exactly the case that if hte parent category does not yet exist, it results in an exception for the whole page which isn't nice as that component is loaded everywhere :)

**Comment by AndreasA** [comment]
PR created: https://github.com/sulu/sulu/pull/6379/files

**Comment by alexander-schranz** [comment]
This was fixed in #6379 we decided to not log an error or throw exception as we are currently not doing this in other twig extension loading something.
