### ISSUE TITLE
CacheClearer path is hardcoded

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4292]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

The path to the cache clearer is hardcoded see https://github.com/sulu/sulu/blob/7e9fccd605f6ccd2d7053b94a701c2b15f5274f5/src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php#L86.

#### Expected Behavior

The path should not be hardcoded.

#### Steps to Reproduce

Changing cache directory and try to clear the cache.

#### Possible Solutions

A. Not a perfect solution use current cache directory from kernel and replace last occurrence of `/admin/` with `/website/`. 
B. Move http cache directory outside the kernel cache directory e.g. `var/httpcache` which path is used in both kernels. Path could/should also be configurable.

**Comment by danrot** [comment]
Shouldn't that be solved now? The cache clearer clears the `common` folder now: https://github.com/sulu/sulu/blob/ccae9ca/src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php#L86
Please reopen if you have meant something different.
