### ISSUE TITLE
Media: Upload file size exceed: No error message and nothing happens

### ISSUE THREAD

**Issue by AndreasA** [sulu/sulu#4297]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0-dev 930731896827d00fdc21d884327dc84256868c94
| Browser Version | Chrome 70

#### Actual Behavior

When uploading an image that is over the upload file size (be it PHP or nginx POST size or anything else like that), the upload fails but the user isn't notified about it at all.

#### Expected Behavior

Inform the user about the issue (maybe even include the current limit if possible)

#### Steps to Reproduce

Set upload size (e.g. nginx POST size) to 1 MB and upload an image with 2 MB

**Comment by comixtrip** [comment]
@AndreasA: Do you think something like that would help in your case? (See PR)

**Comment by AndreasA** [comment]
It looks good from just the code perspective. Will have to verify functionality, of course :)

**Comment by AndreasA** [comment]
Will try to test it later this week.

**Comment by niklasnatter** [comment]
Thanks a lot for reporting! This was fixed in https://github.com/sulu/sulu/pull/5553
