### ISSUE TITLE
Migration text editor values from Sulu 1.x

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#4302]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6.x. and 2.0.0
| Browser Version | ---

#### Actual Behavior

The new UI might break in certain situations if it is used with data from older installations.

A list of currently known issues:
- [x] media_selection field type (currently requires an `ids` property in Sulu 2.0, since it will wail otherwise)?
- [ ] text editor (ckeditor5 and ckeditor4 are not completely compatible)

#### Expected Behavior

We either have to be fault tolerant enough or provide migrations to update the old values. This decision might also be different from case to case, and I think we don't necessarily have to say that it has to work one way for all the occurrences.

**Comment by alexander-schranz** [comment]
As nobody ever complained about the ckeditor4 html not fully compatible with new ckeditor5 I will close this issue. If somebody does stumble over such a things they would need to create a plugin for ckeditor5 or use builtin plugins or configuration options of ckeditor for it. End it also possible that they create there own text editor.
