### ISSUE TITLE
SuluRouteBundle RouteProvider should redirect when a path without prefix is provided

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#4324]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | all
| Browser Version | --

#### Actual Behavior

Currently a route is accessible with and without prefix. 

#### Expected Behavior

A redirect should happen when no prefix is provided.

#### Steps to Reproduce

Without prefix: https://sulu.rocks/blog/drop-big-beats
With prefix: https://sulu.rocks/en/blog/drop-big-beats

https://sulu.rocks/blog/drop-big-beats should redirect to https://sulu.rocks/en/blog/drop-big-beats

**Comment by trickreich** [comment]
@sulu/core-team In my opinion this is a critical bug and should be fixed in Sulu 1.6.

**Comment by alexander-schranz** [comment]
fixed in #4672
