### ISSUE TITLE
Sulu throws error, when opening internal links content type, if corrupted sites are in the project

### ISSUE THREAD

**Issue by marcostastny** [sulu/sulu#4326]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.1

#### Actual Behavior

When you have corrupted sites in the backend of your project, and you want to add internal links, it will throw the following error:
`Call to a member function hasTag() on null`

Called by:
`vendor/sulu/sulu/src/Sulu/Component/Content/Repository/ContentRepository.php`
Happens at line: 795

#### Expected Behavior

It shouldn't break, would be nice to just not display the corrupted sites.

#### Steps to Reproduce

Add a corrupted site, by adding site and then removing template xml, afterwards internal links won't work.

**Comment by danrot** [comment]
I think this bug has already been fixed. I've tried the steps as you have said, and then the pages using that template is displayed stroke through:
![screenshot from 2018-12-18 18-28-20](https://user-images.githubusercontent.com/405874/50171473-d6c3ad00-02f2-11e9-8315-5d38d677f9e1.png)

And it is still selected in the `internal_links` field type of another page, and also the overlay with the column navigation is working (although it is not stroke through there...).
![screenshot from 2018-12-18 18-29-42](https://user-images.githubusercontent.com/405874/50171538-ff4ba700-02f2-11e9-8b74-e5353bc38fdf.png)

For this reason I am going to close this issue. Please tell us if you have more information, that can help reproducing the error, if an upgrade to the latest version does not help.
