### ISSUE TITLE
Cache clear for preview not working anymore

### ISSUE THREAD

**Issue by fdyckhoff** [sulu/sulu#4369]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.0-alpha4
| Browser Version | -

#### Actual Behavior

The Cache-Clear command does not clear the preview cache anymore.
Only the base cache clear command of Symfony is executed.

#### Expected Behavior

The preview cache should be cleared when the admin cache is refreshed

#### Steps to Reproduce

Install sulu-minimal project and execute `php bin/adminconsole cache:clear`

**Comment by fdyckhoff** [comment]
I checked the develop branch just now. It does not work there either.

1. View a page preview in the backend
2. Compare timestamps of `var/cache/admin` and `var/cache/preview`
3. Clear cache via `adminconsole`
4. Compare timestamps again

Only `var/cache/admin` was refreshed.

**Comment by danrot** [comment]
Fixed in #5204
