### ISSUE TITLE
User contact permissions crashes when too many webspace and roles are defined

### ISSUE THREAD

**Issue by cdellamonica** [sulu/sulu#4371]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6
| Browser Version | Any

#### Actual Behavior

Our project has 50+ webspaces and as much roles so our users can manage only their webspace's content.

In the user admin panel, if I want to change the roles of a user, the request to /admin/api/users generates a 70Mb Json in my dev environnement and crashes in production.

#### Expected Behavior

The page loads quickly and I can manage my users.

#### Steps to Reproduce

Create 50+ webspaces and roles, edit a user's permissions.

#### Possible Solutions

Load less information to list the roles and permissions.

**Comment by danrot** [comment]
Are you saying that the form for the roles is doing fine, while only the contact form is not working correctly?
Because then the number of webspace probably wouldn't mattter, but only the number of roles. Could you double check?

How does the request fail? Is it maybe the same error as in https://github.com/sulu/sulu/issues/2477?

**Comment by cdellamonica** [comment]
Hello Daniel,

I think both problems are related. Webspaces increase the issue because each webspace create 4 new permissions ( webspace, default-snippets, analytics, custom-urls ). So I have currently 931 records in the se_permissions table. The admin/api/users Json returns Roles * Permissions * Language records, which becomes quite a lot in my case !
The request fails as it times out, because it seems like the backend does a SQL request for each Role/Permission/Language 

I think the contact form does not need the detail of all the permissions to work as it's not displaying them. It just needs the roles list. That would greatly decrease the complexity.
 
I hope my comment makes sense :)

**Comment by danrot** [comment]
Ah, I see, I wasn't aware that the `permission` field is rendered as well... Removing that should be a quite easy fix which already should improve the response. I won't have time to fix it today, but I'll ask others from the team, and otherwise I'll fix it next week.

**Comment by cdellamonica** [comment]
awesome ! Thanks :)

**Comment by danrot** [comment]
@cdellamonica Can you copy over the two lines from [this file from my PR](https://github.com/sulu/sulu/pull/4376/files#diff-87867051cbf0ddc1f92a5fa5ab4c3532) and tell if that makes your problem go away?

**Comment by cdellamonica** [comment]
@danrot, This fix works, although I think you should apply the "fullRole" group to the $settings attribute too.
Thanks !

**Comment by danrot** [comment]
@cdellamonica Since this actually is a BC break, I would like to avoid changing more than necessary. If the settings don't make any problems, I'd leave them there. The fix will be included in the next release, so I am going to close this issue. Thanks for noticing!
