### ISSUE TITLE
FieldDescriptors not longer usable in website context

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4399]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.0-dev (2018-01-29)
| Browser Version | -

#### Actual Behavior

Since changes in the datagrid (https://github.com/sulu/sulu/pull/4361) you can not longer use fielddescriptor in website api's. We used it also on the website api's to create list responses.

#### Expected Behavior

It should still be possible to create list based on field descriptors also in website context.

**Comment by Ctecmobility** [comment]
Hi guys, 
Any news on how to implement this in the website context, while it's not fixed yet?
Could I be of any help to get this fixed?
Thanks in advance

**Comment by danrot** [comment]
Going to close this issue in favour of #4946.
