### ISSUE TITLE
Cannot build assets anymore (terser webpack plugin breaks)

### ISSUE THREAD

**Issue by fdyckhoff** [sulu/sulu#4409]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | develop + 2.0.0-alpha4
| Browser Version | -

#### Actual Behavior

Building assets fails (because Terser v3.16.0 breaks terser-webpack-plugin) 

see https://github.com/webpack-contrib/terser-webpack-plugin/issues/66

> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! @ build: `webpack --mode production`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the @ build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

[2019-02-03T21_28_35_721Z-debug.log](https://github.com/sulu/sulu/files/2826021/2019-02-03T21_28_35_721Z-debug.log)

#### Expected Behavior

That it builds the assets without error

#### Steps to Reproduce

1. Clean install of develop branch
2. npm install (node v11.9.0 (npm v6.5.0))
3. npm run build

#### Possible Solutions

Add a fixed terser version to your package.json.

```
npm install terser@3.14.1 --save-dev
```

Thanks @rhoffmann for finding the issue and (temporary) fix

**Comment by danrot** [comment]
The upstream issue was solved, so that should be working again.
