### ISSUE TITLE
Strange umlaut values rendered in Firefox

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4413]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6.24
| Browser Version | Firefox 65

#### Actual Behavior

If you paste texts from PDF is sometimes happens that umlauts are pasted as strange characters which will be displayed on e.g. Firefox like this (depending on the font family e.g.: Open Sans):

![bildschirmfoto 2019-02-05 um 13 51 39](https://user-images.githubusercontent.com/1698337/52274525-41858200-294d-11e9-945b-942f169453ea.png)

#### Expected Behavior

This double character umlauts should be replaced with normal umlauts values in the PasteFromWord function.

ü => ü
ä => ä
ö => ö

#### Steps to Reproduce

Copy  this text:

> üäö 

into the Editor

#### Possible Solutions

Replace the character with normal umlaut values.

**Comment by danrot** [comment]
I have just tried that again in Firefox 76.0 (Sulu 1.6 and 2.0), and it does not seem to occur anymore. So I am going to close this issue.

**Comment by alexander-schranz** [comment]
Can confirm the "fake" umlauts are now render correctly in firefox.
