### ISSUE TITLE
Language copy of pages does ignore source template

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4422]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.21
| Browser Version | - 

#### Actual Behavior

Currently if you copy a language from A to B and B has another template as A the template of B is not switched and so not all data is saved.

#### Expected Behavior

If you copy a language from A to B it should also change the template.

#### Steps to Reproduce

1. Create a new Page with Template `homepage` in Language `DE`
2. Create a new Languagevariant in `EN` with template `default`
3. Copy Languagevariant from DE -> EN the template is not changed.

**Comment by danrot** [comment]
Is it possible, that this bug does not exist anymore in Sulu 2.0? :thinking:

**Comment by alexander-schranz** [comment]
@danrot I would say that there is something like `$destDocument->setStructureType($document->getStrucureType());` in the `ContentMapper` missing but its really strange there is no change in 2.0 I could find and there it seems to work 🙈

**Comment by danrot** [comment]
Weird... so it works in Sulu 2.0 for you too? Maybe we should just fix it the way you've suggested for Sulu 1.6.

**Comment by alexander-schranz** [comment]
@danrot yes did also work in 2.0 for me too.  Created a PR for 1.6: #5240.

**Comment by danrot** [comment]
Fixed in #5240
