### ISSUE TITLE
Unable to edit snippets

### ISSUE THREAD

**Issue by HadGS** [sulu/sulu#4441]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | actual develop
| Browser Version | Firefox 63

#### Actual Behavior

Create snippets with template which is not first in select of templates. When try to edit this snippet, template selected in select of templates is first, not the correct one with which snippet was created.

#### Expected Behavior

Being able to edit snippets with respect to chosen template within snippet create.

#### Steps to Reproduce

Create two or more snippets templates and create snippet with template which is not first in select of templates. Save it and try to edit this snippet.

**Comment by HadGS** [comment]
Still persist in actual develop.
![bug](https://user-images.githubusercontent.com/40547189/54343081-491c0300-463e-11e9-940d-b96c08a7565d.gif)

When additionally the first snippet has also blocks with some different fields, it blanks screen with some console error.

**Comment by danrot** [comment]
@HadGS Thanks for reporting! This should be fixed by now in the latest develop.

**Comment by HadGS** [comment]
@danrot Yes, it works.
