### ISSUE TITLE
Webspace: Custom Url Tab crashes when url creator gets deleted.

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#4447]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no

#### Actual Behavior

If you delete a user, who added a custom URL in the webspace, the custom url tab won't work anymore because of the failed user load.

#### Expected Behavior

Show "deleted user" or empty column in the custom url list.

#### Steps to Reproduce

Create a user, add a custom url and delete the user. Now try to open the custom url list.

#### Possible Solutions

Show another value in the column.

**Comment by alexander-schranz** [comment]
fixed in #4644
