### ISSUE TITLE
Image is scaled with fixed width and fixed height when mode="inset" is defined in scale.

### ISSUE THREAD

**Issue by hans77cz** [sulu/sulu#4449]
| Q                  | A
| ------------------ | ---
| Bug fix?           | yes
| New feature?       | no
| BC breaks?         | no

#### Actual Behavior
Image is scaled with fixed width and fixed height when mode="inset" is defined in scale.

#### Expected Behavior
Image is scaled with max width and max height when mode="inset" is defined in scale. According to exapmple listed in http://docs.sulu.io/en/latest/book/image-formats.html

#### Steps to Reproduce
Define image format with mode="inset" in image-formats.xml and generate image thumbnail.

```
<format key="small">
    <meta>
        <title lang="en">Small</title>
    </meta>
    <scale x="343" y="343" mode="inset"/>
</format>
```
Original Image

![f-type_original](https://user-images.githubusercontent.com/15885709/52993364-35e98f00-3414-11e9-9f65-e074ad2f96a9.jpg)

[BUG] Image is scaled with fixed width and fixed height

![f-type_bug](https://user-images.githubusercontent.com/15885709/52993362-3550f880-3414-11e9-814b-061122e12637.jpg)

[FIX] Image is scaled with max width and max height

![f-type_fix](https://user-images.githubusercontent.com/15885709/52993363-35e98f00-3414-11e9-84f3-e101555e5c16.jpg)

#### How to fix
Change `ImageInterface::THUMBNAIL_INSET` to `'inset'` that comes from $format array on line 130.

https://github.com/sulu/sulu/blob/e1e0fb0b244afec3b577003af0d625ab603f8fa6/src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php#L130

**Comment by alexander-schranz** [comment]
@hans77cz seems like there was an undocumented change in the imagine library we use for scaling. Will have a look at it, you can currently downgrade to imagine/imagine to 0.7.1 delete the generated thumbnail.
