### ISSUE TITLE
[MediaBundle] media-selection component request

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#445]
<a href="https://github.com/michaelzangerle"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1465587?v=2" /></a>
By @michaelzangerle _from_ https://github.com/sulu-cmf/SuluMediaBundle/issues/101
### Added params

The media-selection component adds a fields parameter (to fetch the medias in a collection) but this param has no effect. Example: 

```
http://sulu.lo/admin/api/media?collection=1&fields=id,thumbnails,title
```

**Comment by danrot** [comment]
Does not happen anymore in Sulu 2.0
