### ISSUE TITLE
Twig variable extension is an empty array only in backend preview

### ISSUE THREAD

**Issue by D37R4C7** [sulu/sulu#4455]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | f73d3c92253ad88b711ae780656f027a529d6dca
| Browser Version | Chrome

#### Actual Behavior
Call extension.excerpt in Frontend is working just fine, but throws an error in backend preview.

`{% if extension.excerpt.something %}`

> Key "excerpt" does not exist as the array is empty.

#### Expected Behavior

Should work in Frontend and in Preview

**Comment by alexander-schranz** [comment]
@D37R4C7 thanks for the issue. As a workaround you can use:

```twig
{% if extension.excerpt.something|default %}

{% endif %}
```

/cc @wachterjohannes its seems like the [template attributes](https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php#L83) service is not used in the preview

**Comment by wachterjohannes** [comment]
@D37R4C7 are you using the dev-develop branch?

**Comment by D37R4C7** [comment]
> @D37R4C7 are you using the dev-develop branch?

Yes, I do.
