### ISSUE TITLE
Do not load image on page if related media entity was deleted

### ISSUE THREAD

**Issue by HadGS** [sulu/sulu#4463]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.0-alpha5

#### Actual Behavior

When try to visit page with included media via SingleMediaSelection and that media was deleted, showing that page throws MediaNotFoundException.

#### Expected Behavior

Try to show page with deleted media should load without that media.

#### Steps to Reproduce

Upload image file to Media section, then in website create page with single media selection and publish it. Then delete Media. Then visit that page with deleted media.

#### Possible Solutions

In SingleMediaSelection in getContentData method instead of directly return result of mediaManager, wrap it in try-catch block.
``try {
    $entity = $this->mediaManager->getById($data['id'], $property->getStructure()->getLanguageCode());
} catch (MediaNotFoundException $e) {
    return null;
}
return $entity;``

**Comment by alexander-schranz** [comment]
@HadGS sounds good. Do you want to create a PR for this?

**Comment by HadGS** [comment]
I can try.
