### ISSUE TITLE
Unable to delete images

### ISSUE THREAD

**Issue by D37R4C7** [sulu/sulu#4472]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | b2ff2ba6fc1d3c734302b380a1f198b565a7ac51
| Browser Version | Browser name and version

#### Actual Behavior

When deleting an image in the media section, I get this error.

```
Warning: strpos(): Empty needle

in /vendor/massive/search-bundle/Search/Decorator/PrefixDecorator.php (line 63)
```

**Comment by alexander-schranz** [comment]
Seems to have todo with the default value in the skeleton:

https://github.com/sulu/sulu-minimal/pull/160/files#diff-fd5f052de140f80b411859e9cf21d34d

which should not be empty. You can set it to `massive` until we fixed it.
