### ISSUE TITLE
CacheClearer service is not public

### ISSUE THREAD

**Issue by DjangoFR** [sulu/sulu#4475]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.x-dev b2ff2ba

#### Actual Behavior

There is an error if you clean media chache:

**_The "sulu_media.format_cache_clearer" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead._**

#### Expected Behavior

Cleaning media caches without error. ;)

#### Steps to Reproduce

execute `bin/websiteconsole sulu:media:format:cache:clear`

#### Possible Solutions

https://github.com/sulu/sulu/blob/fd4546ccc8a6a3ef74e124067c2e95a1340d3ec3/src/Sulu/Bundle/MediaBundle/Resources/config/services.xml#L48

`<service id="sulu_media.format_cache_clearer" class="%sulu_media.format_cache_clearer.class%" public="true"/>
`

**Comment by alexander-schranz** [comment]
@DjangoFR Thanks for the issue:

Did work on removing all `ContainerAwareCommand` and replace them with normal `Command` and dependency injection in https://github.com/sulu/sulu/pull/4445 but is not yet finished.

Currently you can just remove the folder manually instead of using the command.
