### ISSUE TITLE
New field descriptor not shown when user settings exists

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4479]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | sulu-2.0-alpha5
| Browser Version | -

#### Actual Behavior

When you add a new field Descriptor and a user have saved field descriptors in the user settings the new field descriptor is not shown up. 

#### Expected Behavior

The field descriptors should be merged. A new one should be added old should removed from the user settings.

#### Steps to Reproduce

Change field descriptor in a list so the field descriptor are persisted to the database.
Add a new field descriptor. The new field descriptor will not be shown up.

#### Possible Solutions

Merge saved field descriptor settings and default field descriptor settings so new are added and old are removed.

**Comment by nnatter** [comment]
Fixed via #5267
