### ISSUE TITLE
Incorrect convertion of URLS in some languages (ex. NL)

### ISSUE THREAD

**Issue by tacoor** [sulu/sulu#4496]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | 2.0.0-alpha5
| Sulu Version | 
| Browser Version | -

#### Actual Behavior

When editing the titel of the page, sulu converts the url to match the new page. De url still contains unvalid characters

#### Expected Behavior

De url is normally converted in a way that is it valid

#### Steps to Reproduce

Change the language to dutch (NL) and edit a new page.
Type in a page title that contains special characters  for example ':'

**Comment by danrot** [comment]
Should be fixed in #4512. Thanks for reporting!
