### ISSUE TITLE
Copy/Paste from MS Word 2019

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#4497]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.21
| Browser Version | Chrome 73

#### Actual Behavior

I'm using the copy/paste from MS word function in Sulu texteditor. In word I'm using Office 2019. By using the function a separate text-line will be inserted. Please take a look on the example:

```
<p>&nbsp;</p>

<p>Über einen Aushang am Schwarzen Brett verabredeten sich Rodelfans aus allen Abteilungen des ...</p>

<p>&nbsp;</p>
```

#### Expected Behavior

The ```<p>&nbsp;</p>``` at the beginning and at the end should be eliminated

#### Steps to Reproduce

Copy Paste Text from Word 2019 by using the function "copy paste from MS Word. Please take care and be shure not copieng some empty text lines with you.

#### Possible Solutions
...

**Comment by alexander-schranz** [comment]
@andreasganahl thank you for creating an issue. The issue seems to be related to #4280 so I will close this one. You can subscribe it there to stay up2date.
