### ISSUE TITLE
Call to a member function getProperty () on null New content specific lang

### ISSUE THREAD

**Issue by kevinhuron** [sulu/sulu#4498]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Sulu Version | 1.6.25
| Browser Version | Chrome last version

Sorry for the inconvenience...

I tried to search but did not find ...

When I'm in the "content" part and I'm in FR language I can create and edit pages,
on the other hand as soon as I want to translate the page in EN, I wish to copy it from the FR but when redirecting for the edition of this page I have this error:

`Call to a member function getProperty () on null`

The profiler display me the error, it from here : 
`$item['title'] = $parentDocument->getStructure()->getProperty('title')->getValue();`
File : **vendor/sulu/sulu/src/Sulu/Bundle/ContentBundle/Serializer/Subscriber/StructureSubscriber.php**

it happens on any template page

I'm stressed because I have to do a deployment for the end of the week ...

My Webspace conf : 
vernet.xml

> <?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.1.xsd">

    
    <name>Hôtel Vernet</name>
    
    <key>vernet</key>
    
    <theme>vernet</theme>
    
    <localizations>
        <localization language="fr" default="true"/>
        <localization language="en"/>
    </localizations>

    <default-templates>
        <default-template type="page">hotelHomePage</default-template>
        <default-template type="home">hotelHomePage</default-template>
    </default-templates>

    <templates>
        <template type="search">search.html.twig</template>
        <template type="error">error/default.html.twig</template>
        <template type="error-404">error/404.html.twig</template>
    </templates>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="fr">Navigation principale</title>
                    <title lang="en">Main Navigation</title>
                </meta>
            </context>
            <context key="foot">
                <meta>
                    <title lang="fr">Navigation de pied de page</title>
                    <title lang="en">Footer navigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>Hôtel Vernet</name>
            <key>vernet</key>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="fr">www.hotelvernet-paris.fr</url>
                        <url language="en">www.hotelvernet-paris.com</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url>testv3.vernet.bsignaturehotels.com/{localization}</url>
                        
                        
                    </urls>
                    
                        
                        
                        
                    
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="fr">vernet-v3-fr.localhost</url>
                        <url language="en">vernet-v3-en.localhost</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>

an example of a page template : 

> <?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:xi="http://www.w3.org/2001/XInclude"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    
    <key>legal-notice</key>

    <view>BsHotelsWebsitesBundle:templates:pages/legal-notice</view>
    <controller>BsHotelsWebsitesBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <meta>
        <title lang="en">Legal notice page</title>
        <title lang="fr">Page de mentions légales</title>
    </meta>
    <properties>
        
        <xi:include href="../includes/highlight.xml"
                    xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:section)"/>

        
        
        <xi:include href="../includes/header-background.xml"
                    xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:section)"/>

        
        
        <xi:include href="../includes/resa-block.xml"
                    xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:section)"/>

        
        
        <xi:include href="../includes/call-to-scroll.xml"
                    xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:section)"/>

        <section name="Options">
            <properties>
                <property name="legal_notice_title" type="text_line">
                    <meta>
                        <title lang="en">Title</title>
                        <title lang="fr">Titre</title>
                    </meta>
                </property>
                <property name="legal_notice_content" type="text_editor">
                    <meta>
                        <title lang="en">Content legal notice</title>
                        <title lang="fr">Contenu mentions légales</title>
                    </meta>
                </property>
            </properties>
        </section>

    </properties>

</template>

The page is created, but I can't edit it, I got this error every times...

Thanks for the help :)

**Comment by alexander-schranz** [comment]
Hello @kevinhuron

did you try to test if it works on a clean new database? You can do this by running `bin/console sulu:build dev --destroy` ATTENTION this will delete all exist data (pages, ...), but would help if you could test if its a problem based on the your XML's or on exist data in your current Database.

If you add languages later you should before editing or add any new page run the sulu:document:init command as [documented](http://docs.sulu.io/en/latest/book/localization.html). Else if you forgot that need to delete EN properties from the startpage node and rerun the command or create the necassary root commands yourself.

**Comment by kevinhuron** [comment]
Hi @alexander-schranz 

The command `bin/console sulu:build dev --destroy` Fix my issue

Really sorry for the inconvenience and thank you very much for your quick help

**Comment by alexander-schranz** [comment]
@kevinhuron we are happy if we could help you. Feel free to join our slack channel https://sulu.io/en#questions
