### ISSUE TITLE
[WebsiteBundle] dispatch an event after cache clear

### ISSUE THREAD

**Issue by debreczeniandras** [sulu/sulu#4503]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6.25
| Browser Version | irrelevant

#### Actual Behavior

When cache clear is called from the backoffice, a `DELETE /admin/website/cache`  request issued which clears the http cache.

#### Expected Behavior

I would like to have an event dispatched at this state, so I can hook an own cache clear listener that performs more tasks related to cache clearing. 
For example purging all caches from a CDN. 

#### Background

The production site is behind Cloudflare in our case. A normal cache clear removing the HTTP Cache is not enough, so we need to call the purge api.

#### Possible Solutions

Dispatch a dedicated cache clear event in this method:

https://github.com/sulu/sulu/blob/ae060d1b1403f789653cff5c2478da5154a6b04a/src/Sulu/Bundle/WebsiteBundle/Controller/CacheController.php#L29-L38

**Comment by wachterjohannes** [comment]
@debreczeniandras this is a good idea - for now you could overwrite the service `sulu_website.http_cache.clearer`  and add you custom logic. But i think it would be a good idea to create a PR for this - sounds like an easy pick and would make this easier

**Comment by danrot** [comment]
That's definitely something worth adding. But I guess we should agree on a event name before you start :slightly_smiling_face: How about "sulu_website.cache_clear"?

**Comment by debreczeniandras** [comment]
To be more precise, I opted for 'sulu_website.cache.post_clear'. Check the PR to see more.

**Comment by alexander-schranz** [comment]
fixed in #4504
