### ISSUE TITLE
updated assets are not taken by SULU

### ISSUE THREAD

**Issue by kevinhuron** [sulu/sulu#4505]
Hi ! Sorry for the inconvenience

I developed a bundle for my SULU project.
Of course I had to create foms, lists and new routes. Any PHP side is ok. For the front I created my modules in Resources / public / js / main.js for routes and Resources / public / js / components for my forms and lists.

When I'm in the dev environment, everything is updated, and everything works perfectly.

But when I push to pull on a server in Stage or prod environment, SULU displays the new tabs and modules, but no action is possible because it has not updated the assets but SULU does not take this bet up to date and I do not understand why
When I check the sources, they are well updated ...

I clear the project cache, clear the browser cache ...
Re build the assets via assets: install

But nothing...

I do not know what to do...

Can you help me please ?

Thank you

**Comment by alexander-schranz** [comment]
Hello @kevinhuron,

please use the Issue template when creating new issues!

For the stage and prod environment you need to create (recommended minified) javascripts into the dist folder e.g.:

https://github.com/sulu/SuluCommunityBundle/tree/1.0.1/Resources/public

You can do this by copy the [package.json](https://github.com/sulu/SuluCommunityBundle/blob/master/package.json) and [Gruntfile.js](https://github.com/sulu/SuluCommunityBundle/blob/master/Gruntfile.js) into your bundle change the Gruntfile.js (BUNDLE_NAME) and run `npm run build`

**Comment by alexander-schranz** [comment]
@kevinhuron also have a look at:

 - https://github.com/sulu/examplenewsbundle

And the sulu 1.6 blog series:

 - https://blog.sulu.io/how-to-develop-a-bundle-in-the-sulu-admin-1
 - https://blog.sulu.io/how-to-develop-a-bundle-in-the-sulu-admin-2
 - https://blog.sulu.io/how-to-develop-a-bundle-in-the-sulu-admin-3
 - https://blog.sulu.io/how-to-develop-a-bundle-in-the-sulu-admin-4
 - https://blog.sulu.io/how-to-develop-a-bundle-in-the-sulu-admin-5

**Comment by wachterjohannes** [comment]
@kevinhuron you can find the neccesary changes to generate dist file here https://github.com/sulu/ExampleNewsBundle/pull/6/commits/0b631e319a67c058339675a735423a7044068054

after this run `grunt build` and commit this changes in your bundle

**Comment by kevinhuron** [comment]
Hi!

Thank you very much for your answers

I understand now, I followed your instructions and everything work fine

Thank you for your help and your time and sorry the issues templates...
