### ISSUE TITLE
[MediaBundle] Single Media select

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#451]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes _from_ https://github.com/sulu-cmf/SuluMediaBundle/issues/64

needed for excerpt icon

**Comment by kriswillis** [comment]
This would be useful :+1:

I find that most of the time I only want to select a single image for inclusion in an area of a template.

**Comment by alexander-schranz** [comment]
I did talk with @c00n84 about this maybe a good solution would be to add a limit parameter to multi select content types like media and internal link. What you think @danrot

**Comment by danrot** [comment]
I think when we have been talking also with @wachterjohannes we said that it would have advantages if we use two separate content types. It would e.g. be useful if there is also no array returned if it is just a single image, which means that the data is a bit different, and just changing a parameter should not break the entire system. According to @berndhep the visualization should be also different. For these reasons I would prefer two different content types, although they can share a lot of code.

**Comment by lennerd** [comment]
:+1: whats the status here?

**Comment by danrot** [comment]
@lennerd Sadly the priority of this task was not high enough to be handled so far...

**Comment by lennerd** [comment]
If you have some information about adding custom property components I could try to make a PR for this. :wink:

**Comment by danrot** [comment]
AFAIC we have no documentation for creating an own content type until now, @joemoe correct me if I am wrong.

Basically you have to register a service using the `sulu.content.type`, and create a twig template, whose content will be rendered for later via aura.

This is a very simple description, probably somebody should invest some time and create a more detailed description in the documentation.

**Comment by joemoe** [comment]
got the hint. on my to document list, which means you get a ticket @danrot  :)

**Comment by trickreich** [comment]
Push!

Would be nice
