### ISSUE TITLE
Check namings before final release

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#4514]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 2.0.0
| Browser Version | ---

We have came up with some new names, which should be discussed before the Sulu 2.0 release, because once released we have to stick with them for a while.

The list below is not complete, but includes some names that are inconsistent resp. not very optimal:

- `apiOptions` vs `options` (the same thing used with different names in different components)
- All the options for `RouteBuilders` describing mappings like `routerAttributesToFormStore` (might be renamed to something without `FormStore` like `routerAttributesToFormOptions` and `routerAttributeToListOptions`, etc., since backend developers might not be familiar with the term `Store`)

**Comment by alexander-schranz** [comment]
Release is done and we refractor it to FormRequest see #4774
