### ISSUE TITLE
RouteBundle does not redirect to language prefix

### ISSUE THREAD

**Issue by dominikmatt** [sulu/sulu#4533]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.26
| Browser Version | ~

#### Actual Behavior

The RouteBundle does not redirect to the language prefix.

#### Expected Behavior

- RouteBundle should redirect a route with the correct language prefix.

#### Steps to Reproduce

**Setup**
- `de` must be the default language in this example
- Install the ArticleBundle and create a article-page
- Create a content-page

**Case 1** RouteBundle with ArticleBundle
RouteBundle should redirect a route with the correct language prefix.
e.g.: We call `example.com/article/test` (Article Page) now there should be a redirect to the correct language (`example.com/de/article/test`) or 404 page should be shown.

**Case 2** Sulu Content
- Call a `en`-url (Content Page) without language prefix ---> Now you got a 404 Error page
- Call a `de`-url (Content Page) without language prefix ---> Now you will be redirected to the url with the language prefix

#### Possible Solutions

-

**Comment by alexander-schranz** [comment]
fixed in #4672
