### ISSUE TITLE
CustomUrl with redirect behavior always redirects to HTTP schema

### ISSUE THREAD

**Issue by debreczeniandras** [sulu/sulu#4537]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6
| Browser Version | irrelevant

#### Actual Behavior

Creating a Custom Url with Redirect behavior always redirects to 'http' schema.

#### Expected Behavior

Custom Url with redirect behavior should respect the current request schema.

#### Steps to Reproduce

Create a new Custom Url, and apply the Redirect. Observe that the generated redirect url is always 'http' schema.

#### Possible Solutions

Schema is not passed as 6th argument here:

https://github.com/sulu/sulu/blob/b8bdb0185b1e2f1e81fd560cab1b6ee012bfce36/src/Sulu/Component/CustomUrl/Routing/Enhancers/RedirectEnhancer.php#L48-L53

We need to add the current schema when calling `WebspaceManager::finUrlByResourceLocator' method.

**Comment by alexander-schranz** [comment]
@debreczeniandras thank you for your issue. it seems like there is `$request->getHost(), $request->getScheme()` missing at the `findUrlByResourceLocator` call. Can you create a pull request on the `release/1.5` branch of sulu/sulu?

**Comment by alexander-schranz** [comment]
fixed with #4538
