### ISSUE TITLE
Cache Clear Button only clears cache for current admin-domain

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#4544]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | ^1.5
| Browser Version | ---

#### Actual Behavior

When you clear the cache the service `sulu_website.http_cache.clearer` uses the request domain to clear the whole cache. If you have multiple domains in your system the others can only be cleared by changing the URL.

#### Expected Behavior

All the domains should be invalidated.

#### Steps to Reproduce

Introduce mutliple webspaces with different domains`test1.sulu.io`and `test2.sulu.io`.

#### Possible Solutions

The cache-clearer should use the WebspaceManager to find all the available domains and use the request domain only if the `{url}` placeholder is used.

**Comment by niklasnatter** [comment]
Fixed in https://github.com/sulu/sulu/pull/5848
