### ISSUE TITLE
File Download not working if "@" is in filename.

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#4560]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.26

#### Actual Behavior

It's not possible to download images from the Sulu Backend (Medias) if the filename of the image has been uploaded with the "@" character. E.g. `file@2x.png`.

`domain.lo/media/1/download/file%402x.png?v=1`
500 returned with message `http://domain.lo/media/3/download/400x400_test001%402x.jpeg?v=1`.

#### Expected Behavior

The download of the image should work.

#### Steps to Reproduce

Upload an image to the media area that contains an "@" in it's filename.

**Comment by alexander-schranz** [comment]
@thomasduenser thank you for report this should be fixed with #4512
