### ISSUE TITLE
Unpublished page not show in teaser selection

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4563]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6.26
| Browser Version | -

#### Actual Behavior

Unpublished page not shown in teaser selection after being selected.

#### Expected Behavior

An unpublished page should also be shown in the teaser selection after being selected.

#### Steps to Reproduce

1. Create a teaser selection. 
2. Add a unpublished page to it
3. Page will not be shown in the list

#### Possible Solutions

ContentTeaserProvider should in case of Admin not go on the published index it should go on the unpublished index.

**Comment by danrot** [comment]
For me the page is listed, but the title in the teaser selection is missing.

**Comment by niklasnatter** [comment]
Fixed by #5716
