### ISSUE TITLE
RFC: Provide a more performant alternative to sulu_content_load

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4576]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | for 2.0
| Browser Version | -

#### Actual Behavior

If you have only a uuid of a page because e.g. custom entities or currently in single_page_selection in many cases `sulu_content_load` is used to get to the url. This is basically leaks in performance as `sulu_content_load` resolve all its content types so many data is loaded which is basically not needed.

You can use currently the `sulu:link` (now `sulu-link`) tag to avoid the sulu_content_load but if you need to url in another case then a tag e.g. form tag given it to a js component there is currently not alternative to sulu_content_load. 

#### Expected Behavior

We should provide a better twig extension which force you to define which fields should really be loaded / resolved by this twig extension.

#### Possible Solutions

In most cases only the url is needed so something like should be ok:

```php
sulu_page_load_url(uuid)
sulu_page_load_url(uuid, 'en') // optional locale
```

but in some cases you maybe need a little bit more information:

```php
sulu_page_load(uuid, ['title', 'url', 'excerptTitle' => 'excerpt.title'])
sulu_page_load(uuid, ['title', 'url', 'excerptTitle' => 'excerpt.title'], 'en')  // optional locale
```

Another way could also be going over the teaser provider which provides a [teaser](https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/PageBundle/Teaser/Teaser.php) object:

```php
sulu_load_teaser('page', uuid)
sulu_load_teaser('page', uuid, locale) // optional locale
```

Also a way could be go over the link provider which is used for the sulu-link tag to get its data which provides a title and url [information](https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/MarkupBundle/Markup/Link/LinkItem.php):

```php
sulu_load_link('page', uuid)
sulu_load_link('page', uuid, locale) // optional locale
```

**Comment by niklasnatter** [comment]
I think this was fixed be https://github.com/sulu/sulu/pull/5820. Please feel free to reopen if that is not the case 🙂

**Comment by alexander-schranz** [comment]
Is fine for me!
