### ISSUE TITLE
[MediaBundle] Pass all values from request and let the MediaManager decide what to use

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#458]
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot _from_ https://github.com/sulu-cmf/SuluMediaBundle/issues/33

See https://github.com/sulu-cmf/SuluMediaBundle/pull/21#discussion-diff-15024028R453, https://github.com/sulu-cmf/SuluMediaBundle/pull/21#discussion-diff-15158537R198 and
https://github.com/sulu-cmf/SuluMediaBundle/pull/21#discussion-diff-15158600R261

**Comment by alexander-schranz** [comment]
This seems to be the current behaviour since a longer time.
