### ISSUE TITLE
Save old Template data

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#46]
Should we save old template data?
these two posibilities:
- clear all node properties within change template
- store data for each template in a own node

**Comment by dantleech** [comment]
I think this will be handled with versioning.

Shall we close this?

**Comment by wachterjohannes** [comment]
what did you think @danrot @chirimoya

**Comment by danrot** [comment]
I don't think we should close this, it is not really related to the refactoring, and I am not sure if this should be solved by versioning, makes the handling quite tough I guess.

**Comment by danrot** [comment]
The solution for this issue would be to show the "mixed" data when switching to another template in the new form. Then the user is aware of the fact that overrides some data.

**Comment by danrot** [comment]
The Versioning feature described in #2067 might help here, because every template switch could create a new version. Then the non-used properties could be simply deleted.

**Comment by danrot** [comment]
@chirimoya Didn't you say we can close this issue now, because the current solution is good enough for you?

**Comment by chirimoya** [comment]
yes
