### ISSUE TITLE
[MediaBundle] Add image crop function for different aspect ratios

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#460]
<a href="https://github.com/alexander-schranz"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1698337?v=2" /></a>
By @alexander-schranz *from* https://github.com/sulu-cmf/SuluMediaBundle/issues/12

When their are image formats 40:30, 60:45, 80:60 and 1680:1050
he can set for 4:3 and 16:10 a specific image section

**Comment by danrot** [comment]
@marcelmoosbrugger That's probably what you are currently working on.

**Comment by marcelmoosbrugger** [comment]
Yes, kind of.

**Comment by danrot** [comment]
Then please don't forget to add it this issue as fixed to your PR 😉
