### ISSUE TITLE
Add migration for permissions for upgrading from 1.6 to 2.0

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#4608]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.0-alpha6
| Browser Version | All

#### Actual Behavior

The assignments of permissions for webspace settings to roles are missing after upgrading from Sulu 1.6 to Sulu 2.0.

#### Expected Behavior

The permissions assigned to a role do not change during the upgrade.

#### Steps to Reproduce

Create a new role in Sulu 1.6 with webspace setting permissions and upgrade to Sulu 2.0. The webspace setting permissions are not added correctly.

<img width="1397" alt="permissions" src="https://user-images.githubusercontent.com/5627878/60015693-5e182180-9684-11e9-8307-f6ec91905fef.png">

#### Possible Solutions

The permission context has changed (e.g. from `sulu.webspace_settings.xxxx.analytics` to `sulu.webspaces.xxx.analytics`. Add a migration to fix this.

**Comment by alexander-schranz** [comment]
Fixed in https://github.com/sulu/sulu-docs/pull/649 and https://github.com/sulu/sulu/pull/6060
