### ISSUE TITLE
[SecurityBundle] User in Permission tab should be fetched in model

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#461]
<a href="https://github.com/mob8607"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1636945?v=2" /></a>
By @mob8607 _from_ https://github.com/sulu-cmf/SuluSecurityBundle/issues/89

JavaScript user model should have functionality to fetch a user by contactId (Permissions)

**Comment by danrot** [comment]
With the complete JS rewrite this is obsolete.
