### ISSUE TITLE
Deleting a page breaks the "webspaces" view

### ISSUE THREAD

**Issue by ctmarc** [sulu/sulu#4618]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | sulu-minimal / dev-develop
| Browser Version | All Webbrowsers

#### Actual Behavior

When deleting a page from the webspace `mywebspace`, the `se_user_settings` table still shows the deleted PHPCR ID in `sulu_admin.list_store.pages.webspace_overview_mywebspace-prod.active` for the active user ID.

The Webspaces view will stop loading because of a 404 error on: `/admin/api/pages?exclude-ghosts=false&exclude-shadows=false&locale=en&webspace=mywebspace-prod&expandedIds=832b1249-6539-461d-8a90-be9ca0d53e37&fields=title%2Cpublished%2Cid&flat=true`

Replacing the value in the `se_user_settings` table or in the URL by a valid node ID fixes the problem.

#### Expected Behavior

The setting `sulu_admin.list_store.pages.webspace_overview_mywebspace-prod.active` should be updated in `se_user_settings` when a node is deleted from the sitemap.

#### Steps to Reproduce

- Login to Sulu Backend
- Go to "Webspaces" and delete any child page
- Reload the browser / the "Webspaces" view

**Comment by danrot** [comment]
This has already been fixed in #4550.
