### ISSUE TITLE
Add file import list toolbar action

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4621]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | for 2.0.0
| Browser Version | -

#### Actual Behavior

Currently there is no list toolbarAction for an import from data from a file.

#### Expected Behavior

Add a import listToolbarAction which can be used to import data from a file e.g. `csv`.
Any files should be able to be choicen and the controller should handle if it supports the import format by return a 400 status code if not supported (not sure maybe 406 or 415 is good)

This can then be used in `SuluRedirectBundle` to import by csv file.

**Comment by niklasnatter** [comment]
Should be fixed by https://github.com/sulu/sulu/pull/5767 🙂
