### ISSUE TITLE
Form mandatory validation should work within block

### ISSUE THREAD

**Issue by markusmoosbrugger** [sulu/sulu#4629]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0
| Browser Version | -

#### Actual Behavior

Form mandatory validation doesn't work within a block element.

#### Expected Behavior

Form validation should also work within a block element. The validation does work if the mandatory property is located in a normal form outside the block.

#### Steps to Reproduce

Add a block which contains at least one mandatory property and save the form afterwards in the browser.

```
<block name="receivers" default-type="to">
    <types>
        <type name="to">
            <properties>
                <property name="email" type="email" colspan="6" mandatory="true"/>     
            </properties>
        </type>
    </types>
</block>
```

**Comment by danrot** [comment]
Fixed in #4889.
