### ISSUE TITLE
Sulu Massive Search config not working with ES 6

### ISSUE THREAD

**Issue by kleinkoerkamp** [sulu/sulu#4663]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.0-RC1
| Browser Version | Browser name and version

#### Actual Behavior

`bin/console massive:search:reindex` is resulting in 
`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Reje  
  cting mapping update to [test_sulu_massive_page-nl-i18n] a  
  s the final mapping would have more than 1 type: [Sulu_Bundle_PageBundle_Do  
  cument_HomeDocument, Sulu_Bundle_SnippetBundle_Document_SnippetDocument]"}]  
  ,"type":"illegal_argument_exception","reason":"Rejecting mapping update to   
  [test_sulu_massive_page-nl-i18n] as the final mapping woul  
  d have more than 1 type: [Sulu_Bundle_PageBundle_Document_HomeDocument, Sul  
  u_Bundle_SnippetBundle_Document_SnippetDocument]"},"status":400} `

#### Expected Behavior

Working reindex

#### Steps to Reproduce

* Elasticsearch 6.7
* Configure massive search to use Elasticsearch adapter
* Adding some pages, including homepage
* Run `bin/console massive:search:reindex`

#### Possible Solutions

-

**Comment by alexander-schranz** [comment]
With the new [MassiveSearchBundle 2.1.0](https://github.com/massiveart/MassiveSearchBundle/releases/tag/2.1.0) this error should not longer happen.

Its needed to provide the Elasticsearch Version:

```yaml
massive_search:
    adapter: elastic
    adapters:
        elastic:
            version: 6.8
            hosts: ['%env(ELASTICSEARCH_HOST)%']
```

@kleinkoerkamp Thank you for your and investigating into this issue.
