### ISSUE TITLE
Remove symfony/force-lowest

### ISSUE THREAD

**Issue by dsuurlant** [sulu/sulu#4664]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 2.0.0-RC1, develop
| Browser Version | n/a

#### Actual Behavior

Currently, version 2.0.0-RC1 and develop require the package `symfony/lowest-version`. However, that package has been abandoned and replaced by a setting in `symfony/flex`.

#### Expected Behavior

For all Symfony-related packages in the most recent Sulu version to be active and generate no Composer warnings.

#### Steps to Reproduce

In my case, I set up a project using `sulu/sulu-minimal` and the warning about https://github.com/symfony/force-lowest came up.

#### Possible Solutions

Remove `symfony/lowest-version` from the `sulu/sulu` requirements. Developers can configure their own Symfony installation by adding `extra.symfony.require` to the composer.json file.

**Comment by danrot** [comment]
I am not totally sure if that will work correctly for `sulu/sulu`. The thing is that we also [testing with the lowest package versions installed](https://github.com/sulu/sulu/blob/fe56ab0/.travis.yml#L36), to see if we have the correct dependencies pinned. But feel free to try to remove this package in a PR, and we'll see if the tests still work as expected.

**Comment by alexander-schranz** [comment]
symfony/remove-lowest was removed in #4756
