### ISSUE TITLE
Error when building image with same hash and name

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4728]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | -
| Browser Version | -

#### Actual Behavior

The `npm run build` ends in a strange error when the same image exist twice in a sulu installation:

Multiple assets emit to the same filename /build/admin/images/checkerBackground.559cbe83770ee9374e8f48407bd4c616.gif

#### Expected Behavior

An image should not error when bundle A and bundle B has the same image in its repository.

#### Steps to Reproduce

When you have 2 bundles which has the same image currently like the `checkerBackground.gif` the build will crash:

```
npm run build
```

#### Possible Solutions

**1. Do not build images and fonts**

Not building fonts and images over webpack and just throw them into the bundles public folder and load them from there, this would also keep every project repositories smaller, atleast >=2.7mb.

**2. Find options to force overwrite**

Maybe there is an option to omit this error and just build it.

**Comment by alexander-schranz** [comment]
@danrot the error seems not longer exist did we change here something?

**Comment by danrot** [comment]
I didn't change anything...
