### ISSUE TITLE
[TagBundle] datagrid: include tab key in workprocess of editable list

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#473]
<a href="https://github.com/michaelzangerle"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1465587?v=2" /></a>
By @michaelzangerle _from_ https://github.com/sulu-cmf/SuluTagBundle/issues/25

daniel mentioned: I think it would also be nice to be able to step to the next field with tabulator, which just creates a new tag at the moment. Maybe you can decide if the tab press should create a new tab or jump to the next field based on the content of the editable span (empty -> jump to next field, not empty -> create new tab)

**Comment by danrot** [comment]
Since there is no inline editing currently this feature got obsolete.
