### ISSUE TITLE
HttpCache on Stage environment crashes when downloading a media the second time.

### ISSUE THREAD

**Issue by rs2487** [sulu/sulu#4737]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0-RC1
| Browser Version | -

#### Actual Behavior

When Sulu is used in Staging environment, there is an error when downloading  a media with original media url a second time. First time when download a media. it works. When the Response is cached the second request on the same url returns an error.

`The Response content must be a string or object implementing __toString(), "boolean" given.`

I had to comment out the line 54 in the index.php of sulu minimals public folder.

#### Expected Behavior

Media downloads are not cached an can be downloaded more then one time.

#### Steps to Reproduce

- Upload Media.
- Open Media.
- Goto History.
- Click on a Version.
- Reload the Download.

#### Possible Solutions

?

**Comment by alexander-schranz** [comment]
Can not reproduce it. So I think its fixed with upgrading the the newer version of symfony http cache implementation fixed. Let us know if it still happens somewhere.
