### ISSUE TITLE
Single select default value with visibleCondition

### ISSUE THREAD

**Issue by martinlagler** [sulu/sulu#4784]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

When there is a single_select property with a default_value and another property with a visibleCondition depending on that single_selects default value, the property is only visible after the select is changed and not by the default value.

#### Expected Behavior

The property with the visibleCondition should be display immediately and not only after the select is changed

#### Steps to Reproduce

```xml
<property name="providerAlias" type="single_select" colspan="6">
            <meta>
                <title>Provider</title>
            </meta>

            <params>
                <param name="default_value" value="facebook"/>

                <param name="values" type="collection">
                    <param name="facebook">
                        <meta>
                            <title>Facebook</title>
                        </meta>
                    </param>

                    <param name="twitter">
                        <meta>
                            <title>Twitter</title>
                        </meta>
                    </param>
            </params>
</property>

<property name="appId" type="text_line" visibleCondition="providerAlias == 'facebook'">
    <meta>
        <title>AppId</title>
    </meta>
</property>
```

**Comment by alexander-schranz** [comment]
I did test this and this seems to work now. Think this was fixed by @Prokyonn in #5576
