### ISSUE TITLE
A section at the top of a page XML results in too much space.

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#4786]
I add a < section > element to capsule title and url. This results in too much space. Seems that the tab bar has some weird displaced <div> elemet that pushes everything down. And maybe the section should have less space above.

![sulu_too_much_space](https://user-images.githubusercontent.com/245385/66135802-bf904a80-e5fa-11e9-9a2d-6a794842da7c.png)

**Comment by danrot** [comment]
Fixed in #5618
