### ISSUE TITLE
Create a Account Selection Content Type

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4806]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | for 2.0
| Browser Version | -

#### Actual Behavior

Currently there exist no `account_selection` content type.

#### Expected Behavior

There should exist a `account_selection` content type.

#### Possible Solutions

**1. Create a AccountSelection Content Type similiar to.**

Here it can have a look at the [SingleContactSelection](https://github.com/sulu/sulu/blob/release/2.0/src/Sulu/Bundle/ContactBundle/Content/Types/SingleContactSelection.php) or [ContactAccountSelection](https://github.com/sulu/sulu/blob/release/2.0/src/Sulu/Bundle/ContactBundle/Content/Types/ContactAccountSelection.php)

**2. Register the selection field type:**

Register a selection field type here: https://github.com/sulu/sulu/blob/release/2.0/src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php#L149

Have here a look at [SnippetSuluExtension](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php#L59-L76)

**3. Write a basic Unit Test for the AccountSelection**

Create a Unit Test for it

Have a look at [SingleAccountSelectionTest](https://github.com/sulu/sulu/blob/release/2.0/src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleAccountSelectionTest.php)

**Comment by nnatter** [comment]
Fixed via #5383
