### ISSUE TITLE
Can't edit single_page_selection after deleting selected page

### ISSUE THREAD

**Issue by DavidFeller** [sulu/sulu#4808]
| Q | A
| --- | ---
| Bug? | unsure
| New Feature? | no
| Sulu Version | 2.0.0-RC2

@alexander-schranz asked me to create this issue.

#### Actual Behavior

After Upgrading from 1.6.x to 2.0.0-RC2 (in multiple steps) a content element of type single_page_selection can't be edited in the admin section (screenshot attached).  

<img width="946" alt="Bildschirmfoto 2019-10-09 um 08 47 30" src="https://user-images.githubusercontent.com/2094727/66575286-f8d63680-eb75-11e9-96e1-8a89407d3323.png">

Chrome dev tools show the following error message:

```Entity with the type "" and the id "384061b3-d76b-42fa-9618-168251d3507c" not found.```

#### Expected Behavior

There should be a way to a) delete the selection if the destination page isn't available/doesn't exist anymore or b) the user should be able to select another page. 

#### Steps to Reproduce

Not 100% sure since the sulu instance was upgraded in multiple steps following the develop branch and all beta releases. So far I wasn't able to reproduce this in any other instance, but I created a backup of the whole system to do further testing.

#### Possible Solutions

Rebuilding the admin js using npm or running `sulu:content:resource-locator:maintain` did not solve this.

**Comment by danrot** [comment]
Just reproduced it, it is actually quite simple: If the page you have linked got deleted this error happens... Will have a look at it.

**Comment by danrot** [comment]
Fixed in #4830
