### ISSUE TITLE
SuluFormBundle with Sulu 2.0.0

### ISSUE THREAD

**Issue by lilithmagenta** [sulu/sulu#4820]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 2.0
| Browser Version | Browser name and version

Hello,
I would like to know if it was possible to use SuluFormBundle with Sulu 2.0.0.
I'm trying to set up a search form like on version 1.6. *
but apparently it is not possible.
Is there an alternative, or at the moment it is better to create your own form?

Thank you for your clarification

**Comment by alexander-schranz** [comment]
@lilithmagenta the SuluFormBundle is still under development for 2.0 ([Roadmap (https://github.com/sulu/SuluFormBundle/issues/190)]).

But at current state you should be possible to install it by using
> `composer require sulu/sulu-form-bunde:dev-develop`

See also the current dev-develop docs: https://github.com/sulu/SuluFormBundle/blob/develop/Resources/doc/index.md for installation 

If you have any errors feel free to create an issue in the [FormBundle Repository](https://github.com/sulu/SuluFormBundle/issues/190)

**Comment by lilithmagenta** [comment]
Oh yeah !!! you make my day with this comment 😃 
I'm really happy to learn this because I started to really appreciate Sulu
Thank you @alexander-schranz
