### ISSUE TITLE
Can't install SuluArticleBundle since upgrade 2.0.0

### ISSUE THREAD

**Issue by lucas-gymex** [sulu/sulu#4826]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 2.0.0

Hello,

I am finalizing a project using Sulu 2.0.0. I will need SuluArticleBundle, but when I do:
`composer require sulu/article-bundle`
an error occurs, I can not install it with my version of Sulu.
Is there a dev version that could be used or is it impossible?

Thank you in advance for your answers

**Comment by alexander-schranz** [comment]
@lucas-gymex the SuluArticleBundle is still under development for 2.0. All bundles which are compatible with 2.0 will get a 2.0 tag the following are currently on the roadmap:

 - SuluArticleBundle
 - SuluFormBundle
 - SuluCommunityBundle
 - SuluCommentBundle
 - SuluAutomationBundle
 - SuluRedirectBundle

 For the article bundle you can track the following https://github.com/sulu/SuluArticleBundle/pull/396. There will still be changes after it but you can install on `dev-develop` when its installed.

**Comment by lucas-gymex** [comment]
Oh ok, I was asking because I thought it would have been possible to install this bundle as SuluFormBundle, but thanks for the answer 😄

**Comment by nnatter** [comment]
I think this should be resolved now, right?
