### ISSUE TITLE
TypeError when retrieving previews from file versions

### ISSUE THREAD

**Issue by markdehaan** [sulu/sulu#4827]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0
| Related issues/PRs | #4024 #4828 

#### Actual Behavior

A TypeError is generated when calling CollectionController->cgetAction in Media from within a collection.

#### Expected Behavior

Return correct response instead of throwing a TypeError

#### Steps to Reproduce

In Sulu Admin:

- go to All Media
- choose a collection
- upload an image

Then you'll notice the failing XHR request in the Symfony debug toolbar

![image](https://user-images.githubusercontent.com/427608/67022120-01dc8000-f101-11e9-87e3-3be875739bd8.png)

#### Possible Solutions

Remove storageOptions parameter in call to FormatManager->getFormats() in CollectionManager. This parameter was removed in issue #4024 but probably forgotten to remove in the call from the CollectionManager. I've made a pull request #4828 to fix the issue.

**Comment by danrot** [comment]
Fixed in #4828
