### ISSUE TITLE
No changelog information if a page's author has been deleted

### ISSUE THREAD

**Issue by DavidFeller** [sulu/sulu#4845]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | >= 2.0.0
| Browser Version | Any

#### Actual Behavior

If the author (user account) of a page is deleted the changelog information throw 404 errors and are not updated when another user changes and saves that page.

#### Expected Behavior

If the author doesn't exist anymore the author and changelog fields should be cleared (and/or editable) and they should be updated when another user changes the page.

#### Steps to Reproduce

1. Create a new page as e.g. user "admin"
2. Create a second user that has identical permissions
3. Login as the new user and delete the user admin in contacts
4. Edit the page that was created by admin and check  "Author" and "Changelog"

![Bildschirmfoto vom 2019-10-22 20-36-57](https://user-images.githubusercontent.com/2094727/67368816-442a1500-f578-11e9-9ec7-313aea596ed8.png)

**Comment by danrot** [comment]
Fixed in #4849
