### ISSUE TITLE
Sulu 2 admin filters

### ISSUE THREAD

**Issue by lightglitch** [sulu/sulu#4855]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 2.0

Support filters components in the admin datagrids.

**Comment by nnatter** [comment]
What kind of filters would you expect? How would you propose to configure them?

**Comment by lightglitch** [comment]
In terms of configuration I see something like the form xml configuration file, but for filters. Filters are just an extra form that filters the datagrid results. 

I just don't know for sure how would be handle by the entity admin api.

You can see some ideas from [react admin demo](https://marmelab.com/react-admin-demo/)

**Comment by lightglitch** [comment]
Solving the frontend and having a interface in the backend that receives the filter parameter would be already nice. 

To make it total generic you would need to implement operators: equals/different, in/not in, great than, etc that are converted to a query like you do in findCategories in the CategoryBundle for parent filter and sort.

**Comment by danrot** [comment]
This would indeed be a nice feature, but it will certainly take some time to implement. Can't promise you until when we will have something like this.
