### ISSUE TITLE
Toolbar text_editor configuration

### ISSUE THREAD

**Issue by lightglitch** [sulu/sulu#4860]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 2

It's possible configure the cktoolbar on the type text_editor?
Because I can't find anything in the documentation http://docs.sulu.io/en/2.0/reference/content-types/text_editor.html

thx

**Comment by alexander-schranz** [comment]
@lightglitch there is a CKEditor config and plugin registry which you can import at:

https://github.com/sulu/skeleton/blob/2.0.1/assets/admin/index.js#L20

and use the following way:

https://github.com/sulu/sulu/blob/87fdd3500d5999548acc07ca4b4df9842a9956f4/src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/README.md

**Comment by lightglitch** [comment]
Thx, I will try it.

**Comment by danrot** [comment]
It should definitely go into the docs, but this is another issue :slightly_smiling_face: Going to close this issue, as what you are asking for is working. You can still ask questions on the closed issue as well.
