### ISSUE TITLE
Creating own Sitemap provider breaks admin interface.

### ISSUE THREAD

**Issue by HadGS** [sulu/sulu#4865]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.1
| Browser Version | irrelevant

#### Actual Behavior

If is registered own sitemap provider, admin interface fails with:
`Warning: Invalid argument supplied for foreach()`
`In ResolveInstanceofConditionalsPass.php line 121`
Issue is with this line of code
https://github.com/sulu/sulu/blob/d7b430ceaabdc3f221ff795124b01fe6db036912/src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php#L110

#### Expected Behavior

Creating own Sitemap providers does not break admin.

#### Steps to Reproduce

Create new Sitemap Provider via https://docs.sulu.io/en/2.0/cookbook/sitemap-provider.html and try to access admin interface.

#### Possible Solutions

Line of code mentioned above change either to `->setTags(['sulu.sitemap.provider' => []]);` or `->addTag('sulu.sitemap.provider');`

**Comment by HadGS** [comment]
No, `undefined method named "setTag" of class "Symfony\Component\DependencyInjection\ChildDefinition"`

**Comment by alexander-schranz** [comment]
Fixed in #4871
