### ISSUE TITLE
SULU 2.0.1 - Add additional informations for a given webspace

### ISSUE THREAD

**Issue by kevinhuron** [sulu/sulu#4870]
| Q | A
| --- | ---
| Bug? | no?
| New Feature? | no
| Sulu Version | 2.0.1
| Browser Version | Chrome Version 78.0.3904.87

### Actual Behavior
... ?
### Expected Behavior

Hi !

How can I reproduce something like this SULU 1.6.X screen _(My business websites)_ : 
_Add additional informations for a given webspace directly with a custom form_
![Capture d’écran 2019-11-05 à 10 40 24](https://user-images.githubusercontent.com/8026215/68197094-ed7dfb80-ffb9-11e9-83b1-18b48e3592a7.png)

**With SULU 2.X ?**

------

I Have checked the @danrot PR in sulu-doc for extends admin, but it explain how we can create **a list** of something in the **left navigation** but not **only a form _(or a list of something)_** in **the webspace tabs view**.

_I have tried something based and the Custom URLs but I'm blocked here... :_ 
![Capture d’écran 2019-11-05 à 10 31 58](https://user-images.githubusercontent.com/8026215/68197653-e60b2200-ffba-11e9-9bd0-18ac444e25de.png)

_Because when I clicked on this surrounded tab I get a blank page with this error :_  
`The view "Form" needs a resourceStore to work properly.Did you maybe forget to make this view a child of a "ResourceTabs" view?`

-----
**Thanks by advance for your helps**

**Comment by alexander-schranz** [comment]
Hello @kevinhuron ,

the resourceKey is the resource you register in the admin configuration e.g.:

https://github.com/sulu/sulu-docs/pull/459/files#diff-51220c2246d8674ff46eff2dd7e41652R280

After you did configure your resource you can set it as resourceKey for that Form. 

The parent of your view need to be `->setParent(PageAdmin::WEBSPACE_TABS_VIEW)`.

If you have still problem show some code.

**Comment by kevinhuron** [comment]
@alexander-schranz , 
Thanks for your answer.

If you can help me to find where I did wrong, that will great :)

here, some code : 
**My Entity:** 
![Capture d’écran 2019-11-05 à 11 46 37](https://user-images.githubusercontent.com/8026215/68201485-27530000-ffc2-11e9-839a-91a6d1ea8a3e.png)

**My Configuration in** `/config/packages/sulu_admin.yaml`
![Capture d’écran 2019-11-05 à 11 46 52](https://user-images.githubusercontent.com/8026215/68201542-3fc31a80-ffc2-11e9-97c4-b1e97d3a5ed8.png)

My Form:
![Capture d’écran 2019-11-05 à 11 47 03](https://user-images.githubusercontent.com/8026215/68201572-4ce00980-ffc2-11e9-9af5-07ad331024f8.png)

**My AdminConfig in** `/Admin/...Admin.php`
![Capture d’écran 2019-11-05 à 11 47 46](https://user-images.githubusercontent.com/8026215/68201636-6b460500-ffc2-11e9-9ea9-d748eac9e682.png)

I Hope these screens of Code will help...

**Comment by alexander-schranz** [comment]
@kevinhuron do you see any error in the Network Tab? And did you try to clear the `var/cache` folder after you configure it?

**Comment by kevinhuron** [comment]
@alexander-schranz , Yes I tried to clear cache (I also remove the `var/cache` folder) and nothing change...

I have zero error when I come on the Page tab on the webspace view, excepted when I click on my custom tab I got a blank page with this error in the Console : 
`The view "Form" needs a resourceStore to work properly.Did you maybe forget to make this view a child of a "ResourceTabs" view?`

**Comment by alexander-schranz** [comment]
@kevinhuron I think this is a real error in our Form.js. The following lines:

https://github.com/sulu/sulu/blob/d7b430ceaabdc3f221ff795124b01fe6db036912/src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js#L93-L98

Should be inside this else:

https://github.com/sulu/sulu/blob/d7b430ceaabdc3f221ff795124b01fe6db036912/src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js#L121-L123

Can you test if this works for you then?

**Comment by kevinhuron** [comment]
@alexander-schranz , Sorry for my ignorance but How can I test it ? I can't modify `vendor/` content....
_My projet is come from_ `sulu/skeleton`

**Comment by alexander-schranz** [comment]
@kevinhuron to test it you can modify the file in your vendor and do a `npm install && npm run build` in the your projects `assets/admin`.

**Comment by kevinhuron** [comment]
@alexander-schranz , I moved lines and I get this error : 
Cannot set property 'resourceKey' of undefined
In line 58 in Form.js

Indeed the `resourceStore` is undefined...
However The `resourceKey` get the right key

**Comment by niklasnatter** [comment]
I think this is included in #3309 and therefore going to close this. Feel free to open a new issue if you disagree 🙂
