### ISSUE TITLE
Notice: Undefined offset: 2

### ISSUE THREAD

**Issue by axzx** [sulu/sulu#4877]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.1

#### Actual Behavior

How does Sulu behave at the moment? 
![obraz](https://user-images.githubusercontent.com/1436016/68468573-94f86980-0218-11ea-8173-193405172cb8.png)

#### Expected Behavior

correct preview

#### Steps to Reproduce

Probably in data structure is something wrong, but I don't know how check it.

**Comment by alexander-schranz** [comment]
@axzx for the preview its currently necassary to have a block named `content` to have in your template: https://github.com/sulu/skeleton/blob/master/templates/base.html.twig#L46

**Comment by axzx** [comment]
@alexander-schranz thanks
I changed it and it works fine now
