### ISSUE TITLE
Some images cannot be converted but no error messages.

### ISSUE THREAD

**Issue by vladimirdjuricic** [sulu/sulu#4879]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.1
| Browser Version | Chromium 78.0.3904.70 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

#### Actual Behavior

1. Randomly selected JPG is uploaded but not rendered to other format/size per any request

#### Expected Behavior

Image should be converted from uploaded image format/size to other format/size.

When this error would occur, error message should be displayed since it confuses the developer and user otherwise.

Also, when URL of a to-be-converted image is directly accessed, no error is displayed. Instead 404 is returned (e.g: http://somesite.local/uploads/media/sulu-400x400-inset/08/48-IMG_20160716_165446.png?v=1-0)

#### Steps to Reproduce

Scenario 1. 
Try couple of random jpg images or use one from the attachment.
This is the output of linux's **file** command for the example "bad" image:

`# file /tmp/CCB_icon_logo.jpg`

`/tmp/CCB_icon_logo.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CS6 (Windows), datetime=2019:05:22 23:42:16], baseline, precision 8, 1024x1024, frames 3
`
Images for testing:
![Hasselblad00091](https://user-images.githubusercontent.com/56277044/68509328-f9471780-0270-11ea-8469-1dac11a376a8.jpg)

![CCB_icon_logo](https://user-images.githubusercontent.com/56277044/68509375-11b73200-0271-11ea-8043-17f48c5aedca.jpg)

**Comment by vladimirdjuricic** [comment]
Either to provide better error message or to use different error type and handle it differently.

https://github.com/sulu/sulu/blob/d7b430ceaabdc3f221ff795124b01fe6db036912/src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php#L169

I had thoughts that these images should be rejected on an upload process, but on a second thought these images are basically valid (generally speaking), so I am not sure anymore.

**Comment by danrot** [comment]
I have just tested to upload your image, and the system rendered other formats without any problems... Can you check in the Symfony Logs what kind of error messages you find?

And I think you are also right about the error code... I think in the below code snippet we should change it to a 400.

https://github.com/sulu/sulu/blob/d7b430ceaabdc3f221ff795124b01fe6db036912/src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php#L169-L175

@alexander-schranz Or do you know about any reason for using 404 here?

**Comment by vladimirdjuricic** [comment]
@danrot I am using custom docker container for php. I've found that this is not working once gd is installed alongside with imagemagick (gd used by default by sulu). It confused me since direct call to non-converted image returned 404. 

Anyway, maybe I should alter the description of this issue to contain the updated  "Steps to reproduce" section?

**Comment by vladimirdjuricic** [comment]
@danrot Update: Now I have both **gd** and **imagemagick** installed and all works. But, once I disable **imagemagick** in php.ini file this issue appears. So, I guess only update to code should be to set it to 500 (due to valid client image) or maybe 415?

**Comment by alexander-schranz** [comment]
@vladimirdjuricic sulu use Imagick if Imagick extension is enabled.
https://github.com/sulu/sulu/blob/8b8c674c5f9254ceab0014095387c11ee004a603/src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php#L258

When you disable imagick you also need to rebuild the cache (`bin/websiteconsole cache:clear`) else it will still try to use imagick.

You can force also a specific adapter by configure it e.g.:

```
sulu_media:
    adapter: gd # imagick
```

**Comment by vladimirdjuricic** [comment]
@alexander-schranz thx for the info. I noticed it that **composer install/update** made complaints about imagemagick missing to go away once the imagemagick would be disabled. Now I know why. Thanks!

**Comment by danrot** [comment]
@vladimirdjuricic So everything works now, and we can close this issue?

**Comment by vladimirdjuricic** [comment]
Not sure if you'd update http status code? If not, I will close it.

**Comment by danrot** [comment]
Ah, right... @alexander-schranz What do you think about the status code? Any reason it is not 400 or something else than 404 at this spot:

https://github.com/sulu/sulu/blob/d7b430ceaabdc3f221ff795124b01fe6db036912/src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php#L169-L174

**Comment by alexander-schranz** [comment]
@danrot depends on the exception there are multiple mediaexceptions thrown in the image convertion and all are mostly that the media not exist except the following which should be converted to 500 error and we should add the prevous exception to it:

https://github.com/sulu/sulu/blob/8b8c674c5f9254ceab0014095387c11ee004a603/src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php#L161

**Comment by alexander-schranz** [comment]
I would also change the behavour and throw a `new HttpException` with previous exception at: 

https://github.com/sulu/sulu/blob/d7b430ceaabdc3f221ff795124b01fe6db036912/src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php#L169-L174

so under development a nice stack trace is shown.

**Comment by vladimirdjuricic** [comment]
@alexander-schranz correct. Status code should follow the real reason behind it.

**Comment by danrot** [comment]
@alexander-schranz I have e.g. also foun da `GhostScriptNotFoundException`, `FilenameAlreadyExistsException` or a `FormatOptionsMissingParameterException`, whereby all of them don't feel like 404 is the correct error code.

**Comment by alexander-schranz** [comment]
@danrot GhostScript we totally forget to disable by default in 2.x. Currently ghostscript is enabled always and so I would only change that exception code if we make ghostscript disabled by default.
The other two exception I are not Exception of functions calls in the image convertion. But maybe we should handle every exception Individual in the FormatManager.

**Comment by danrot** [comment]
Even if we change the default of GhostScript, we should still handle the case that it is activated but not installed. But even then you could argue that the image has not been found, because it could not be converted. So when thinking about it now, I would say we could also leave it as it is. While I generally like the idea of throwing a proper exception instead of just logging something, we should be careful. Because since #4886 we know that people rely on the behavior as it is.

**Comment by danrot** [comment]
I think for the moment we will leave the error code as it is, so I am going to close this issue.
