### ISSUE TITLE
Sulu 2.0 ck editor should support code editing

### ISSUE THREAD

**Issue by almare** [sulu/sulu#4881]
| Q | A
| --- | ---
| Bug? | Maybe
| New Feature? | no
| Sulu Version | 2.0
| Browser Version | Browser name and version

#### Actual Behavior

At the moment it is impossible to use source code editing inside ckeditor. The button is missing.

#### Expected Behavior

The ckeditor should support source editing to add for example classes or edit html directly.

#### Possible Solutions

Add source code editing plugin to ck editor.

**Comment by alexander-schranz** [comment]
@almare hello. We are sorry but the CKEditor 5 does not longer support editing its source code see e.g.: https://stackoverflow.com/questions/47729450/ckeditor-5-how-to-insert-some-html-aka-wheres-the-source-mode.
You can add custom plugins and custom configurations over our registries see: https://github.com/sulu/sulu/blob/2.0.0/src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/README.md
Not sure whats currently the way for a styleset dropdown.

**Comment by almare** [comment]
Thank you, I didn't know that.

**Comment by alexander-schranz** [comment]
@almare I created an issue on the Ckeditor5 repository side as I'm currently not sure how to build a styleset dropdown in ckeditor 5. Issue can be found here: https://github.com/ckeditor/ckeditor5/issues/5723. You can subscribe it if you want.
I will close this issue as its currently nothing we can fix in sulu.
