### ISSUE TITLE
Support request: Cookie consents recommendation

### ISSUE THREAD

**Issue by almare** [sulu/sulu#4887]
Is there a cookie consents recommendation for sulu 2.0? I tried this bundle connectholland/cookie-consent-bundle but I can't get it work. So is there any advice? Thank you for any hints.

**Comment by alexander-schranz** [comment]
@almare we don't force anything in the frontend and I can not give any recommendation here, I personally only needed to handle cookies in the frontend currently so I only used JS libraries and no twig or php cookie libraries.

**Comment by almare** [comment]
Thank you for your answer. My question was indeed regarding only the frontend part.
