### ISSUE TITLE
[WebsiteBundle] Remove cache clear button when Cache handling is good enough

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#489]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes _from_ https://github.com/sulu-cmf/SuluWebsiteBundle/issues/52

Commit https://github.com/sulu-cmf/SuluWebsiteBundle/commit/63cf6a65d635030943a42e62861218a6e37fd62a and https://github.com/sulu-cmf/sulu-standard/commit/e7e2878a311cbff4a9b2a362158723b2e5c95fcf

**Comment by alexander-schranz** [comment]
I think we will always need the possibility to manually clear a cache. Systems like Drupal provide this also.
