### ISSUE TITLE
Problem when deploying in production - AudienceTargetingBundle

### ISSUE THREAD

**Issue by zazz-will** [sulu/sulu#4891]
| Q | A
| --- | ---
| Sulu Version | 2.0.1

Hello,

I'm putting my site in production, and I have a problem when I put my .env.local file in prod mode

I get the following error : `Fatal error: Uncaught Error: Class 'App\AudienceTargetingCacheListener' not found in C:\wamp64\www\my-project\src\Kernel.php:47 Stack trace: #0 C:\wamp64\www\my-project\public\index.php(54): App\Kernel->getHttpCache() #1 {main} thrown in C:\wamp64\www\my-project\src\Kernel.php on line 47

the code is as follows:
`       <?php

        namespace App;

        /*
        * This file is part of Sulu.
        *
        * (c) Sulu GmbH
        *
        * This source file is subject to the MIT license that is bundled
        * with this source code in the file LICENSE.
        */

        use FOS\HttpCache\SymfonyCache\HttpCacheProvider;
        use Sulu\Bundle\HttpCacheBundle\Cache\SuluHttpCache;
        use Sulu\Component\HttpKernel\SuluKernel;
        use Symfony\Component\Config\Loader\LoaderInterface;
        use Symfony\Component\DependencyInjection\ContainerBuilder;
        use Symfony\Component\HttpKernel\HttpKernelInterface;

        class Kernel extends SuluKernel implements HttpCacheProvider
        {
            /**
             * @var HttpKernelInterface|null
             */
            private $httpCache;

            public function __construct(string $environment, bool $debug, string $suluContext = self::CONTEXT_ADMIN)
            {
                parent::__construct($environment, $debug, $suluContext);
            }

            protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader)
            {
                // Feel free to remove the "container.autowiring.strict_mode" parameter
                // if you are using symfony/dependency-injection 4.0+ as it's the default behavior
                $container->setParameter('container.autowiring.strict_mode', true);
                $container->setParameter('container.dumper.inline_class_loader', true);

                parent::configureContainer($container, $loader);
            }

            public function getHttpCache()
            {
                if (!$this->httpCache) {
                    $this->httpCache = new SuluHttpCache($this);
                    $this->httpCache->addSubscriber(new AudienceTargetingCacheListener());
                }

                return $this->httpCache;
            }
        }
`

would anyone have an idea of ​​where the worry is coming from, please? in dev mode everything works perfectly, but not in prod

Thank you for your answers

**Comment by alexander-schranz** [comment]
If you open the class. Your IDE should tell you that `AudienceTargetingCacheListener` does not exist you shoud import it from the correct namespace.

```php
use Sulu\Bundle\AudienceTargetingBundle\EventListener\AudienceTargetingCacheListener;
```

**Comment by danrot** [comment]
I assume that the solution of @alexander-schranz is working, therefore going to close this issue.
