### ISSUE TITLE
[BUG] Unable to save a category for a page

### ISSUE THREAD

**Issue by Alainvdz99** [sulu/sulu#4903]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0
| Browser Version | Chrome  

#### Actual Behavior

Its now possible to create and save an category but when you select a catergory on a page, it doesnt save the category.

#### Expected Behavior

Thats you save the categories on the page so i can use specific pages in my smart content.

What is the behavior you expect?

#### Steps to Reproduce
category select: 
```
  <property name="categories" type="category_selection">
            <meta>
                <title lang="en">Category Selection</title>
                <title lang="nl">Categorie selectie</title>
            </meta>
        </property>
```

**Comment by danrot** [comment]
I fixed that a while ago, but couldn't find the PR anymore... However, I just tested it to be sure, and the categories are saved now :slightly_smiling_face:
