### ISSUE TITLE
[WebsiteBundle] Do not redirect partial matches

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#491]
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot _from_ https://github.com/sulu-cmf/SuluWebsiteBundle/issues/28

Partial Matches should not be redirected, but displayed in the default localization instead. Therefore accessing the default language using the language placeholder in the URL should not be possible.

**Comment by danrot** [comment]
@crash0verride This issue is quite old, and I am not sure how this should be solved anymore...

If the default language of a website is english, should the page www.example.org show the english version, and www.example.org/en should not be existent, or should www.example.org redirect to www.example.org/en ?

**Comment by lennerd** [comment]
:+1: for redirect.

I ran into this configuration problem myself:

``` xml
<environments>
    <environment type="prod">
        <urls>
            <url>www.example.org/{localization}</url>
            <url language="en">www.example.org</url>
        </urls>
    </environment>
</environments>
```

This will make www.example.org/en and other localizations for example www.example.org/de available as normal routes. I think the english page was also avialable under www.example.org.
I expected to have a redirect from www.example.org/en to www.example.org  and no redirect for www.example.org/de.

**Comment by alexander-schranz** [comment]
Think this issue can be closed, we are doing a redirect of a partial match if no route exist for the current url and if a target page exist. The language is provided by default locale provider (http://docs.sulu.io/en/2.0/cookbook/change-default-locale-provider.html)
