### ISSUE TITLE
Page tree gets cleared after clicking on different pages before first request is finished

### ISSUE THREAD

**Issue by luca-rath** [sulu/sulu#4912]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.2
| Browser Version | Chrome latest

#### Actual Behavior

The webspace page tree gets cleared completely.

#### Expected Behavior

The page tree shows the contents of the last clicked page.

#### Steps to Reproduce

Go to webspaces, click on any child page of the homepage and then on a different page immediately after the first click.
If your second click is on a page with children, all children except the first one get displayed.

**Comment by luca-rath** [comment]
ping @danrot

**Comment by cirykpopeye** [comment]
I can confirm it's a bug, I've had it a few times already.

**Comment by danrot** [comment]
Fixed in #5010
