### ISSUE TITLE
[WebsiteBundle] Mark the active site in the navigation

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#492]
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot *from* https://github.com/sulu-cmf/SuluWebsiteBundle/issues/27

The data passed to the twig templates for the navigation should also mark the active page

**Comment by alexander-schranz** [comment]
I add here the twig code we currently use to check if a page is active. Its not a pretty solution but it works

``` twig
{% if uuid is defined %}
    {% set sulu_breadcrumb = sulu_breadcrumb(uuid) %}
{% endif %}
{% for navigationItem in navigationItems %}
    {% set selectedClass = '' %}
    {% if sulu_breadcrumb is defined %}
        {% for breadcrumbItem in sulu_breadcrumb %}
            {% if (navigationItem.uuid == breadcrumbItem.uuid) %}
                {% set selectedClass = 'active' %}
            {% endif %}
        {% endfor %}
    {% endif %}
    {# .... #}
{% endfor %}
```

**Comment by wachterjohannes** [comment]
@chirimoya i think we should add this to release 1.0 this solutions seems for me very slow and "hacky" ... /cc @danrot @berndhep
