### ISSUE TITLE
add extra view over all navigations in a webspace

### ISSUE THREAD

**Issue by remdan** [sulu/sulu#4921]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 2.*
| Browser Version | any

#### Actual Behavior

Every page can be set to a navigation through the 'Settings' tab. The label/name from that navigation-link is automatically the title from that page.
![Screen Shot 2019-11-28 at 14 05 55](https://user-images.githubusercontent.com/5031692/69809223-97cbf600-11e9-11ea-8d8f-c05646d241ba.png)

And your navigation items are in the same order as your pages in the admin.
That can be very tricky If a page is in multiple navigation context and you want to have it in another place in another context. You need to do for every navigation a Internal-Page etc.

![Screen Shot 2019-11-28 at 14 22 21](https://user-images.githubusercontent.com/5031692/69809838-ddd58980-11ea-11ea-8bb0-8e5499f5f5fe.png)

#### Expected Behavior

It would be nice if there is an overview of all defined menus in a webspace and then you can set the order and the link-name for every single navigation. So it should be definitely a different order as your pages in the admin!
Maybe more in the future there you can also put an icon to every point or some other details...

#### Possible Solutions

Add a 'Navigations' tab and show a extra view where you can delete, add and order your navigations. Also give different translated link-names.

![Screen Shot 2019-11-28 at 14 32 36](https://user-images.githubusercontent.com/5031692/69810622-9ea83800-11ec-11ea-87b6-dfcb5420c074.png)

**Comment by danrot** [comment]
In our opinion having just one tree instead of multiple ones is a lot easier for the content manager to handle. Therefore we don't plan to support something like this in the core. However, @kfrohwein is also a big advocate of this feature. Maybe you can join forces and build your own Bundle introducing a functionality like this.
