### ISSUE TITLE
Smart content bug when removing its source page

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/sulu#4931]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.2
| Browser Version | any

#### Actual Behavior

When removing the source page of the smart content, the loader animation keeps loading. I can open the filter but I'm unable to click to change the source. 
I now have to fix it using PHPCR.

#### Expected Behavior

That I would be able to change the source after deleting the other one.

#### Steps to Reproduce

- Add a page with smart content type on it. 
- Select a page as source of the smart content. 
- Remove that page without disconnecting it from the smart content. 
- Go back to the page with smart content -> loading forever animation

#### Possible Solutions

Might have to catch the uncaught promise error. ( Not sure )

![schermafbeelding_2019-12-05_om_13 25 11](https://user-images.githubusercontent.com/17956647/70236916-33b7ad80-1766-11ea-96c3-76e6a5658244.png)

**Comment by nnatter** [comment]
Should be fixed with #4941 🙂
