### ISSUE TITLE
Image cropping with to large image format.

### ISSUE THREAD

**Issue by martinlagler** [sulu/sulu#4936]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-release/2.0
| Browser Version | Browser name and version

#### Actual Behavior

When a image format has higher resolutions then the image itself the cropping doesn't work properly. In the example below it's not possible to move the image focus to the bottom of the image.

#### Expected Behavior

Working cropping.
![Bildschirmfoto 2019-12-09 um 09 26 04](https://user-images.githubusercontent.com/24388840/70419591-06207c00-1a66-11ea-8f4d-0efbc9d8b91c.png)

**Comment by danrot** [comment]
That is fixed in #5197
