### ISSUE TITLE
Filters are not taken into account during export csv lists

### ISSUE THREAD

**Issue by etidimjav** [sulu/sulu#4943]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.29

#### Actual Behavior

During lists csv export, filters are not taken into account.

#### Expected Behavior

When a filter is selected the export should take it into account.

#### Steps to Reproduce

Set up filters and csv export function for a list of items.
https://docs.sulu.io/en/1.6/cookbook/integrating-custom-filters.html

**Comment by danrot** [comment]
While testing I have realized that also stuff like sorting and searching is not taken into account...

**Comment by etidimjav** [comment]
An "inelegant" method to do that, is to pass to session the filter id and when request for csv export is launched, we can set filter id query parameter from the session.

**Comment by danrot** [comment]
I don't see any reason to do that, because we should have all the information to do that in place.

**Comment by etidimjav** [comment]
Yes I'm agree with that but with my skills and my time, it's working. But I know it's not the solution.

**Comment by danrot** [comment]
In [this line] the URL for the REST API is created, I think this is the place that needs some fixing.
