### ISSUE TITLE
Hide a block on the website

### ISSUE THREAD

**Issue by GillesKnockaert** [sulu/sulu#4964]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | any
| Browser Version | any

#### Actual Behavior

If you wan't to hide a block for a period of time, you need to remove the block and then add it again when you need it again.

#### Expected Behavior

possibility to temporary disable a block instead of deleting.

#### Possible Solutions

next to the icons to minimize a block or to remove a block add a striped through 'eye' icon. When clicked make visually clear that the block is not visible for the user on the front end. This can be done on several ways for example a color indication, givo the block a bit opacity,.... . Also change the icon to an icon that isn't striped through.

when clicked on the icon again, reverse the state to visable.

**Comment by alexander-schranz** [comment]
@GillesKnockaert thank you for your request. I think this would be an interesting feature and think @chirimoya is planning to make the blocks in future more controlable by the content manager.

**Comment by manuxi** [comment]
To archive this, add a checkbox to each block and check the state in the corresponding template.
Fast implemented with includes in xml, extends in twig.
