### ISSUE TITLE
Improve Headless CMS support

### ISSUE THREAD

**Issue by gisostallenberg** [sulu/sulu#4986]
# Problem description
At the moment Sulu does not really have an API to support responses when used as Headless CMS. The default solution is to add `templates/pages/default.json.twig` with the following in it
```yaml
{{ content|json_encode|raw }}
```

This solution lacks some feautures:
* Sometimes we want more data to be added, just as is done while writing twig.
* The navigation is not available at a good endpoint
* We need to write twig and use `raw` to make it work, while there are way better ways to output json
* The url displayed in the response is not ajusted to the fact we are using the API
* Internal links are not parsed

# Proposed solution
* Agree on an (Open API?) spec for the output
* Add a default json endpoint for the (nested) navigation
* Passing the expected (Sulu\Component\Content\Compat\Structure?) output throught a service or event to be able to adjust it based on the project's needs. Add a reference to the navigation endpoint in each document
* Skip Twig for outputting
* Fix all url's in the output to reflect the fact an API is used and parse internal links

**Comment by gisostallenberg** [comment]
We might even remove the .json extension by checking the accept-headers...

**Comment by wachterjohannes** [comment]
@gisostallenberg we have published the WIP bundle https://github.com/sulu/SuluHeadlessBundle

**Comment by wachterjohannes** [comment]
i will close this issue in favor of issues in the newly created repository
