### ISSUE TITLE
Go to website link in admin panel

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/sulu#4988]
# Problem description

There's no way for our customer to go directly to their website from the admin panel

# Proposed solution

Add a button with target="_blank" in the top nav bar, there's enough room for it I think.

![Schermafbeelding 2020-01-17 om 15 33 09](https://user-images.githubusercontent.com/17956647/72620073-e3c02f00-393e-11ea-808a-457d045ea8b1.png)

**Comment by danrot** [comment]
There is a similar issue: #4350. Therefore going to close this one as duplicate.
