### ISSUE TITLE
toolbar-dropdown-menu runs out the screen

### ISSUE THREAD

**Issue by TheCadien** [sulu/sulu#4996]
| Q | A
| --- | ---
| Bug | Yes
| Sulu Version | Every Version

# Actual Behavior

If in the "toolbar-dropdown-menu" are too many Items , it will run out of the screen area. (For example the List with Snippet Templates.)

# Expected Behavior

I think a Scrollbar sounds like an nice solution.

# Steps to Reproduce

Create a lot of Snippet Templates (I think 20+ are enough ) and take a look at the Admin Backend at "admin/#snippet/snippets/de/add"

# Possible Solutions

We fix it heavy simple with an max Hight to get a scroll bar.
`<style>.husky-toolbar .toolbar-dropdown-menu { max-height: 500px; }</style> `

**Comment by danrot** [comment]
I have actually fixed this in https://github.com/massiveart/husky/pull/784 already... Can you double check if you are running the latest version of Sulu 1.6?

**Comment by TheCadien** [comment]
Ah my mistake. We implemented our fix at the beginning of december and had to open a bug issue since then.

**Comment by danrot** [comment]
Don't worry :slightly_smiling_face: But then I am going to close this issue.
