### ISSUE TITLE
System Collections should not be able to be edit / removed

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5005]
| Q | A
| --- | ---
| Sulu Version | 2.0.3
| Browser Version | All

# Actual Behavior

Currently in the UI the following Buttons are shown:

 - Move Collection
 - Edit Collection
 - Delete Collection
 - Add new Collection

all this should not be possible for a System Collection. Most of that will throw currently an Api error (unless delete which should really not be possible for system collections).

# Expected Behavior

The buttons should not be available for system collections and we should show system collection with another Icon maybe a lock icon.

# Steps to Reproduce

Try to add collections inside a system collection the api will error. 

# Possible Solutions

Disable or hide the buttons by the condition that the collection is from type system.

**Comment by danrot** [comment]
Fixed in #5018
