### ISSUE TITLE
Smart Content elements list not loading in admin

### ISSUE THREAD

**Issue by alexandrin-rus** [sulu/sulu#5006]
Hello, 

When selecting the content using a smart_content filter, if we add `<param name="properties" type="collection">` the admin cannot load the preview list. However even though the list in the admin area does not load the actual content page and preview work and are displaying the elements correctly.

 If I remove the properties configuration, the list with the selected elements loads but I loose access to the properties I am interested in.

I noticed is that this also happens in the sulu.rocks demo when editing the Artists Overview template. 

![sulu-smart-content-not-loading](https://user-images.githubusercontent.com/1786146/72999374-f9829800-3e07-11ea-82cc-9b4505b4f39d.JPG)

The request that breaks is: 

/admin/api/items?provider=pages&excluded=87a8e806-97c7-4cf7-aab8-dd0298ed89d3&locale=en&params=%7B%22properties%22%3A%7B%22name%22%3A%22properties%22,%22value%22%3A%5B%7B%22name%22%3A%22title%22,%22value%22%3A%22title%22,%22title%22%3Anull,%22placeholder%22%3Anull,%22infoText%22%3Anull%7D,%7B%22name%22%3A%22headerImage%22,%22value%22%3A%22headerImage%22,%22title%22%3Anull,%22placeholder%22%3Anull,%22infoText%22%3Anull%7D,%7B%22name%22%3A%22url%22,%22value%22%3A%22url%22,%22title%22%3Anull,%22placeholder%22%3Anull,%22infoText%22%3Anull%7D%5D,%22title%22%3Anull,%22placeholder%22%3Anull,%22infoText%22%3Anull%7D%7D&dataSource=87a8e806-97c7-4cf7-aab8-dd0298ed89d3&sortBy=published&sortMethod=asc

The error received is Call to a member function getName() on array in vendor\sulu\sulu\src\Sulu\Component\Content\SmartContent\QueryBuilder.php:216

# Expected Behavior

Preview list should load in the admin area as well.

**Comment by nnatter** [comment]
Thanks for reporting this! I think this should be fixed with #4978 🙂 Unfortunatelly, the fix is not released yet.

**Comment by alexandrin-rus** [comment]
Good to hear. Thank you!

**Comment by danrot** [comment]
@alexandrin-rus Since this is already fixed I am going to close this issue. Would be awesome if you could double-check if the latest `release/2.0` branch is working as expected for you. In case it doesn't we will reopen this issue.

**Comment by alexandrin-rus** [comment]
Just checked the release/2.0, everything seems to work as expected now. Thank you!
