### ISSUE TITLE
UI Display Bug in Admin View - Smart Content

### ISSUE THREAD

**Issue by thgie** [sulu/sulu#5009]
| Sulu 2.0.3 |
| Browser independent | Tested on recent version of Chrome, FF and Safari

Smart Content list doesn't adjust to available width.

![SharedScreenshot](https://user-images.githubusercontent.com/731681/73167132-92126400-40f7-11ea-8f63-baac0c6c172a.jpg)

**Comment by chirimoya** [comment]
@danrot please have a look.

**Comment by danrot** [comment]
Fixed in #5015
