### ISSUE TITLE
{host} is not correctly replaced in the preview

### ISSUE THREAD

**Issue by eekes** [sulu/sulu#5020]
| Q | A
| --- | ---
| Sulu Version | 2.0.3
| Browser Version | Chrome 79.0.3945.130

# Actual Behavior

The {host} part is not correctly replaced in the preview.

# Expected Behavior

It should replace the current host

# Steps to Reproduce

Displaying the preview in /admin 🙂

**Comment by danrot** [comment]
Fixed in #5024
