### ISSUE TITLE
Add request variable to DefaultController indexAction

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#503]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes _from_ https://github.com/sulu-cmf/SuluWebsiteBundle/issues/42

**Comment by danrot** [comment]
Instead of adding this variable we can now use the `WebsiteController`, which does not have any default actions at all. If the developer wishes, he can add this request variable in his own Controller.
