### ISSUE TITLE
Empty snippet list after deleting one snippet XML declaration if snippet content exists

### ISSUE THREAD

**Issue by partikule** [sulu/sulu#5030]
| Q | A
| --- | ---
| Sulu Version | 2.1.*@dev

# Actual Behavior

500 error on Snippet List after removing one snippet XML declaration file if content already exists for this snippet in DB.

# Expected Behavior

The list of the other existing snippet are displayed

# Steps to Reproduce

1. Create one snippet XML file
2. Create content for this snippet
3. Rename / Delete the snippet XML file
4. Try to get the Snippets List on the backend : admin/#/snippets

# Possible Solutions

Do the same than what is done for pages.

**Comment by TheCadien** [comment]
i think we talk from the same error :P 

https://github.com/sulu/sulu/issues/4958

**Comment by danrot** [comment]
Oh, right, my bad, I asked @partikule to create that issue :grimacing: I am sorry, but at least you know now which issue you can follow to keep track of that :blush
