### ISSUE TITLE
Sulu admin build download not work when using different line break

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5031]
| Q | A
| --- | ---
| Sulu Version | 2.0.3
| Browser Version | -

# Actual Behavior

If your projects use a different line break the `sulu:admin:download-build` the hash check will fail and you can not download the file.

# Expected Behavior

It should transform the project line breaks to our used line break

# Steps to Reproduce

Change linebreaks of assets/admin files and then try `sulu:admin:download-build`

# Possible Solutions

Replace all linebreaks and spaces (if the proejct have different indention) before generating a hash over the files.

Also I would add a `--force` command to skip this hash test.

**Comment by danrot** [comment]
It would be nice if somebody with a windows machine could implement this, because otherwise this is pretty hard to test :confused:

**Comment by danrot** [comment]
Fixed in #5033
