### ISSUE TITLE
Allow to upload media in root collection

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5038]
| Q | A
| --- | ---
| Sulu Version | 2.0.3
| Browser Version | .

# Actual Behavior

Currently if you open the media module you can not upload files directly there you need first choice a collection.

# Expected Behavior

You should be able to upload files always then a overlay should be shown with a single collection selection.

# Steps to Reproduce

1. Try to upload a file without choosing  a collection

# Possible Solutions

Show overlay with single collection selection (should exist as used inside the media smart content provider).

**Comment by nnatter** [comment]
As a quickfix, we could display a warning/tooltip if the user hovers the disabled `Upload` toolbar action or tries to drag-and-drop something 🙂

**Comment by alexander-schranz** [comment]
We did got a design for this. The upload should be possible but when the media is dropped and no collection is selected the following overlay should appear to select the correct collection:

![All Media - Choose Location](https://user-images.githubusercontent.com/1698337/111486823-1a0e5f80-8738-11eb-881d-f6d9d13355b7.png)

**Comment by alexander-schranz** [comment]
This is fixed by #6052 and will be part of the 2.3 release.
