### ISSUE TITLE
Error when deleting a media item with crops defined

### ISSUE THREAD

**Issue by TimGroenenberg** [sulu/sulu#5044]
| Q | A
| --- | ---
| Sulu Version | 2.0.3
| Browser Version | Chrome Version 79.0.3945.130

# Actual Behavior

When trying to delete a media item which has crops defined the following error is thrown:
`A new entity was found through the relationship 'Sulu\Bundle\MediaBundle\Entity\FormatOptions#fileVersion' that was not configured to cascade persist operations for entity: Sulu\Bundle\MediaBundle\Entity\FileVersion@000000001fede5db0000000068902c50`

# Expected Behavior

Expected behaviour is that media items with crops are allowed to be deleted and the defined crops are also deleted.

# Steps to Reproduce

- Upload an image in the media manager
- Edit an image and click on the "Define crops" button
- Edit one of the crops and save it
- Try to delete the image

**Comment by danrot** [comment]
Fixed in #5046
