### ISSUE TITLE
Category Medias do not save their order.

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#5073]
| Q | A
| --- | ---
| Sulu Version | Is a Sulu 1.6 and 2.x issue

# Actual Behavior

Since you can add medias to categories, the category translation and the medias are connected n:m in the database but there is no media order saved in that table and so it just load them by id order (lowest first)

# Expected Behavior

If i order the medias inside a category it should stay ordered 

# Steps to Reproduce

Create a Category and upload 2 medias, try to order them.

# Possible Solutions

Add one more column to category_translation_media_interface table named like "order" or "position" to keep them in order.

**Comment by danrot** [comment]
Has been fixed in #5107
