### ISSUE TITLE
The chosen language should persist if the backend view changes

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5080]
# Problem description

If I enter the sulu.rocks backoffice and klick on "webspaces" the default language will be "en". If I change that to "de", click on a content, edit and save the content and use the "go back" button it will stay "de". But if I click on webspaces again or click for example on "snippets" the language will be reset to "en" without any further notification.

# Proposed solution

Keep the language for everything until the user actively changes it. Or at least give the content manager a noticeable warning that the default language is used.

**Comment by alexander-schranz** [comment]
Currently I think every view has its own user settings for its content language. And if you click on a menu item the locale is loaded from the user setting and the back button does load it from the current view.

I think from content manager perspective the best case would be have both a global user setting for the content language which will save the last choosen locale and fallback to the view specific language if that view doesn't have the specified globale locale in it.

**Comment by chirimoya** [comment]
@danrot can you have a look. Cloud it be that the behaviour change from 1.6 to 2.0?

**Comment by man-andy** [comment]
We also have this issue. It is really annoying, because the user is now adding articles, media, snippets in the wrong locale

**Comment by alexander-schranz** [comment]
@chirimoya I tested the behaviour before and it was inconsistent. The language switch on pages and snippets where shared, but Medias and Categories had there own language. I think it would make sense that it would affect all views if I switch the content language.

**Comment by man-andy** [comment]
@alexander-schranz It is also happening in the article bundle.
The CMS is pretty unusable at this point. The user is constantly adding articles to the wrong webspace now.

I see this as a critical bug.

**Comment by kfrohwein** [comment]
Honestly I second that this is rather critical for the usability. In every presentation I have to tell people now "oh please beware that you won't enter content in a different language then you expect.". Don't know how the other 2.0 users can stand this but maybe most aren't using multilingual features.

**Comment by danrot** [comment]
Fixed in #5101
