### ISSUE TITLE
Preview not refreshed completely on language change

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5084]
| Q | A
| --- | ---
| Sulu Version | 2.0.4
| Browser Version | -

# Actual Behavior

Preview not refreshed on language change

# Expected Behavior

When switching the language of a page or other content with preview, the preview should reload the whole site in the new selected language.

# Steps to Reproduce

1. Open https://sulu.rocks/admin/#/webspaces/demo/pages/en/5eab85ce-7a3b-4e71-a3ad-203bd5002144/details
2. Switch language
3. Only things inside content block are refreshed not the menu outside or header

**Comment by niklasnatter** [comment]
I can reproduce the problem by adding a translation to my template. The translation will not be updated in the preview when switching the locale:

```twig
{{ 'sulu_website.cache_clear'|trans([], 'admin') }}
```

It looks like the locale that is sent to the server by the `PreviewStore` is not updated when switching the locale in the administration interface.

**Comment by alexander-schranz** [comment]
This issue was fixed by #5924 at current state we can only fix this in the new 2.3 release.
