### ISSUE TITLE
Blocked file types and max file size are never set

### ISSUE THREAD

**Issue by tvwijgerden** [sulu/sulu#5090]
| Q | A
| --- | ---
| Sulu Version | 1.6.x & 2.0.x
| Browser Version | -

# Actual Behavior

Setting the `sulu_media.format_manager.blocked_file_types` and `sulu_media.upload.max_filesize` configuration has no effect.

# Expected Behavior

Setting the `sulu_media.format_manager.blocked_file_types` configuration should block the configured file types.

Setting the`sulu_media.upload.max_filesize` configuration should limit the file size to the configured max file size

# Steps to Reproduce

Add `application/pdf` to the `blocked_file_types` configuration and upload a pdf file.

# Possible Solutions

The `FileValidator` class contains a `setBlockedMimeTypes` method and a `setMaxFileSize` method. These methods are never called, so max file size and blocked mime types are never set.

A possible solution would be calling these methods in the `SuluMediaExtension` and passing the correct configuration option for both methods. 

If you want to see this changed I can make a PR for it. If I want to make the changes for both version 1.6 and 2.0, should I make two PR's or how would I do that?

**Comment by danrot** [comment]
@tvwijgerden Since this bug also appears in Sulu 1.6, you should make the change in the `release/1.6` branch. We will take care of merging the changes to 2.0 afterwards. In general you should always fix a bug in the oldest supported version (currently 1.6), in which the bug appears.

**Comment by danrot** [comment]
Fixed in #5096
