### ISSUE TITLE
[HttpCache] Impossible to debug in dev mode

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#5104]
| Q | A
| --- | ---
| Sulu Version | 2.0
| Browser Version | -

# Actual Behavior

Actually is impossible to debug varnish configuration in development because this:
https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php#L114

# Expected Behavior

That function should return true in specific cases. 

# Steps to Reproduce

Configure Varnish in dev mode and test response

# Possible Solutions

Maybe in debug section add another option or always if debug is enabled because is confusing.

**Comment by alexander-schranz** [comment]
Thank you for creating an issue. As mention in #4141 we should introduce a flag instead in the SuluHttpCache Configuration.

**Comment by plozmun** [comment]
I didn't see that there was an open issue, so closing this :)

Thank you @alexander-schranz !!
