### ISSUE TITLE
Smart content medie doesn't sort by title

### ISSUE THREAD

**Issue by thgie** [sulu/sulu#5139]
| Bug? | yes
| Sulu Version | 2.0.4
| Browser Version | Chrome 80.0.3987.149

#### Actual Behavior

Smart content with _provider_ media doesn't sort by title. Changing direction has no effect.

#### Expected Behavior

Should sort :)

**Comment by thgie** [comment]
Thank you for the hint :) Will move the report over there.

**Comment by danrot** [comment]
Duplicate of #5142
