### ISSUE TITLE
Add position to category medias for pgsql

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5146]
| Q | A
| --- | ---
| Sulu Version | 2.0.5

The SQL in your UPGRADE.md is MySQL only.
If I do doctrine:schema:update the SQL is not usable.

```sql
CREATE SEQUENCE ca_category_translation_medias_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     DROP INDEX "primary";
     ALTER TABLE ca_category_translation_medias ADD id INT NOT NULL;
     ALTER TABLE ca_category_translation_medias ADD position INT DEFAULT 0 NOT NULL;
     ALTER TABLE ca_category_translation_medias ADD PRIMARY KEY (id);
```

* DROP INDEX "primary"; wont work because the index in unknows.
* ALTER TABLE ca_category_translation_medias ADD id INT NOT NULL; won't work because the col is NOT NULL but is missing a default.
* ALTER TABLE ca_category_translation_medias ADD PRIMARY KEY (id); won't work because the PK wasn't removed before.

**Comment by alexander-schranz** [comment]
@kfrohwein sadly I'm not familiar with postgresql and have currently not running but if I google about adding the autoincrement I think it should be something like this for the id:

```
ALTER TABLE ca_category_translation_medias ADD id INT NOT NULL DEFAULT nextval('ca_category_translation_medias');
```

Did you found a SQL which is working for postgresql you can share?

**Comment by kfrohwein** [comment]
I am not sure if my PK sequence now works.

I believe this is the Doctrine issue:
https://stackoverflow.com/questions/6076180/doctrine2-doesnt-set-sequence-to-default-for-id-column-postgres

**Comment by kfrohwein** [comment]
I believe we are not even using that table because we don't use categories at all...

**Comment by alexander-schranz** [comment]
@kfrohwein ok then its really a doctrine issue. Could thought that it could make problems if there are exist entries in the table, but if there are no entries and doctrine still can not upgrade the schema then its really strange issue. From my side I think something like:

```
CREATE SEQUENCE ca_category_translation_medias_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     ALTER TABLE ca_category_translation_medias ADD id INT NOT NULL DEFAULT nextval('ca_category_translation_medias');
     ALTER TABLE ca_category_translation_medias ADD position INT DEFAULT 0 NOT NULL;
     ALTER TABLE ca_category_translation_medias ADD PRIMARY KEY (id);
```

should work but thats untested maybe somebody with a installed postgresql could test this /cc @chirimoya. 

For deployment or any database upgrade I can recommend using doctrine migration bundle. There you can then also edit the SQL which are generated and you are sure which SQL is executed when deploy the project. The good thing is that the database migration can also be tested in the CI I used the following for this: https://gist.github.com/alexander-schranz/e7ab61e7edbcb0c3b46baf6b92921c0f. Which is really simple it just test if migration up and down works without throwing errors. 

In a project I had also problems the doctrine:schema:update did not rename something instead drop a column on another machine, which could end in losing data, so if you keep with this use `dump-sql` and check the SQL before run it with `force` on your production server.

**Comment by danrot** [comment]
I think this is an upstream bug in Doctrine... So maybe you should create an issue there. Since there is nothing we can really do about this command not working, I am going to close this issue.

**Comment by kfrohwein** [comment]
Final note: As the table was empty in my case anyways it was easier to just delete the table and do a doctrine:schema:update. That works.
