### ISSUE TITLE
Image Cropping: Minimal Size Area not draggable

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5155]
| Q | A
| --- | ---
| Sulu Version | 2.0.6
| Browser Version | Chrome, Ubuntu, Version 80.0.3987.149 (Official Build) (64-bit)

# Actual Behavior

If you want to crop an image that is smaller then the minimum crop size you can only double click to maximize the cropping area in the center. Then maybe you can drag it to the top of the image but that is more like a flicker. You can't drag it where you want it.

# Expected Behavior

I say it's okay that you can't make the area smaller because it is already too small. Still it would be nice to drag the area as you like and avoid flickering. I guess the JS is using some too large numbers and messes up the calculation.

# Steps to Reproduce

Take a small image and set an image style like:

```
    <format key="hero-swiper-xl">
        <meta>
            <title lang="en">Hero Swiper XL</title>
            <title lang="de">Hero Swiper XL</title>
        </meta>

        <scale x="2560" y="853" mode="outbound"/>
    </format>
```

**Comment by danrot** [comment]
Fixed in #5197
