### ISSUE TITLE
Teasers don't have a Webspace Key

### ISSUE THREAD

**Issue by marcostastny** [sulu/sulu#5156]
# Problem description

Currently the Content Type does not send the Webspace Key of the Item. This is according to Documentation. Sadly therefore its not possible to simply call `{{ sulu_content_path(teaser.url, teaser.webspaceKey) }}` and therefore Teasers in different Webspaces will always link to the current Webspace.

# Proposed solution

As Described by Alex there are multiple Solutions for how to fix this Problem. You could generate the full URL already in the Teaser Provider, or add a field WebspaceKey which will be null on Articles and filled on pages. I would prefer the latter, because we could then programmatically check which webspace this is and add for example custom styling.

Additionally it also would be possible to enhance the documentation, by documenting this behaviour and adding the following Workaround as a Solution to this Problem.

# Workaround

There is a workaround for this problem, by simply using `sulu:link` instead of the `sulu_content_path` function.

`<sulu:link href="{{ teaser.id }}"></sulu:link>`

**Comment by alexander-schranz** [comment]
Think the best solution would be to generate the whole url in the TeaserProvider itself and still provide the webspaceKey as teaser.attribute.

**Comment by marcostastny** [comment]
We just ran into a problem with the `sulu:link` way will break with an Error, when using it to display articles. `Call to a member function getLocalization() on null at "/vendor/sulu/sulu/src/Sulu/Component/Content/Compat/LocalizationFinder.php:40"` Therefore something like the following will be needed:
```twig
{% set element = teaserItem.type == 'content' ? 'sulu:link href="' ~ teaserItem.id ~ '"' : 'a href="' ~ sulu_content_path(teaserItem.url) ~ '"' %}
{% set endElement = teaserItem.type == 'content' ? 'sulu:link' : 'a' %}

<{{ element|raw }}></{{ endElement }}>
```

**Comment by danrot** [comment]
@alexander-schranz The attributes of a provider is just a simple array anyway, and could easily contain context-specific options, right? Then it would also be ok for me to add a `webspaceKey` there.

**Comment by danrot** [comment]
In #5264 I've added the `webspaceKey` as teaser attribute. Can we consider this issue solve because of that?

**Comment by alexander-schranz** [comment]
@danrot think thats currently the best solution without any bc break gonna close it.
