### ISSUE TITLE
Max / Min Length Config for text_line and text_editor

### ISSUE THREAD

**Issue by TheCadien** [sulu/sulu#5158]
Problem description

Our customer would like to have a individually config for some backend properties with the content types "text_line" or "text_editor". 
He would like to set a maxi number of characters and i think that makes sense. 

# Proposed solution

i think some heavy simple config like that, would do the job perfectly 

```xml
<property name="title" type="text_line">
    <meta>
        <title lang="en">Title</title>
    </meta>
    <params>
        <param name="max_length" value="255"/>
       <param name="min_length" value="20"/>
    </params>
</property>
```

**Comment by danrot** [comment]
There is already #2938, wich is a similar issue... Therefore I am going to close this issue as duplicate. Can you maybe add your suggestion in #2938, so that we discuss which option to choose?

**Comment by danrot** [comment]
Oh, sorry about that, it's not the same issue, just similar :see_no_evil: The question still is if we should use the `minOccurs` and `maxOccurs` options for that, or introduce separate ones as you suggested. Questionable is if `minOccurs` and `maxOccurs` should only be used for blocks, or if their meaning is dependant on the context. This decision would still affect #2938 as well.

**Comment by alexander-schranz** [comment]
I would go with `params` like in the Proposed solution. I find `minOccurs` and `maxOccurs` strange for a string length.

**Comment by nnatter** [comment]
I tend to agree with @alexander-schranz on this. Using a param feels more appropriate to me 🙂

**Comment by danrot** [comment]
Ultimately that would mean for me that we should remove these attributes completely and move them to params as well. Currently according to the XSD they can be passed to every property, but if we implement it like that, they'll never have an effect.

**Comment by nnatter** [comment]
> Ultimately that would mean for me that we should remove these attributes completely and move them to params as well. Currently according to the XSD they can be passed to every property, but if we implement it like that, they'll never have an effect.

Personally, I think that would be the better solution than using them in different types with different consequences. 🙂

**Comment by niklasnatter** [comment]
Thanks for creating this issue! This was solved in https://github.com/sulu/sulu/pull/5672
