### ISSUE TITLE
Single Media Select will run endless 404 requests

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5177]
| Q | A
| --- | ---
| Sulu Version | 2.0.4 - 2.0.6
| Browser Version | Chrome Latest

# Actual Behavior

![Screenshot from 2020-04-04 14-09-17](https://user-images.githubusercontent.com/245385/78450325-17793e00-767e-11ea-82ce-9df11e5f9b53.png)

# Expected Behavior

Just do nothing after the first request.

# Steps to Reproduce

- I go to sulu.rocks
- Upload an image
- Use that in a new default content
- Go to the media manager and delete the image
- re open the content

# Possible Solutions

Response with something that the JS knows there is no image or just stop requests of this element if the response was 404. Maybe retry a few times but please don't hammer the server.

**Comment by nnatter** [comment]
Thanks for reporting! Should be fixed in #5183
