### ISSUE TITLE
Copy content and dynamic url generator broken

### ISSUE THREAD

**Issue by FarouHub** [sulu/sulu#5220]
| Q | A
| --- | ---
| Sulu Version | 2.0

# Actual Behavior

When you try to copy content from a page from a language  to a new language, the admin api throw a error like 

```
ErrorException: Warning: grapheme_strpos(): grapheme_strpos: 
Offset not contained in string
```
exemple: create an english page from a existing french page

Dynamic url generator (generate the url after typing the title a new page creation)

Bug due to the merge #5057 

# Expected Behavior

Copy content from the existing page (FR) to the new (EN, DE)

# Steps to Reproduce

Just try to copy a page.

# Possible Solutions

In the PathCleanup.php file, need to check the empty string part after the explode

```
foreach ($parts as $i => $part) {
    if($part !== ''){
        $slug = $this->slugger->slug($part, '-', $languageCode);
        $slug = $slug->lower();
        if (0 === $i || $i + 1 === $totalParts || !$slug->isEmpty()) {
            $newParts[] = $slug->toString();
        }
    }
}
```

**Comment by danrot** [comment]
I can't reproduce this bug :thinking: What version of PHP are you using? Maybe the behavior of this `grapheme_strpos` function changed in some version?

**Comment by FarouHub** [comment]
PHP 7.2.27 (cli) (built: Jan 24 2020 03:49:45) ( NTS )

**Comment by FarouHub** [comment]
I try with another php version and it is working fine.

> PHP 7.3.14 (cli) (built: Jan 24 2020 03:06:50) ( NTS )

**Comment by danrot** [comment]
Our tests run seem to run against PHP 7.2.29, see e.g. https://travis-ci.org/github/sulu/sulu/jobs/675418605. Do you have that version available as well? Maybe it is a PHP bug, that has been solved in the mean time...

**Comment by FarouHub** [comment]
Bug is due to the php version
