### ISSUE TITLE
Add more social networks to contact details

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#5224]
# Problem description

It is quite common to set social networks links in the footer. Ideally these links should be configurable under "Contacts" > "Organizations" and not hardcoded. But some of them are missing, like Youtube or LinkedIn. Also some kind of phone like "Whatsapp" or "Telegram".

# Proposed solution

Add the possibility of adding those fields in configuration. Maybe that option already exists?

**Comment by alexander-schranz** [comment]
@plozmun They are stored in the database so its easy to add them also in your project. But still think it would make sense to add others like LinkedIn to sulu core. They are here https://github.com/sulu/sulu/blob/03906293121f4c246dc5cacf03e03fe46ce9962e/src/Sulu/Bundle/ContactBundle/DataFixtures/ORM/LoadDefaultTypes.php#L117-L130

@chirimoya which do you think make sense to add here?

**Comment by plozmun** [comment]
Oh! Great, thank you @alexander-schranz

**Comment by danrot** [comment]
I think linkedin an youtube/vimeo would make sense.  But it is questionable to me if I would call stuff like Whatsapp, Telegram and the like a social network.
