### ISSUE TITLE
Page table does not display indicator for draft pages

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#5225]
| Q | A
| --- | ---
| Sulu Version | 2.0.6

# Actual Behavior

When I change the display mode of my page list to `tree_table`, I no longer see any indicators about the status of my pages. This makes it hard to see which pages are published at the moment.

![current behaviour](https://i.imgur.com/LvNJvAh.gif)

# Expected Behavior

The `tree_table` adapter should display the same indicators as the `column_list` adapter.

# Steps to Reproduce

1. Create a new page
2. Save the page as draft only
3. Navigate to the page list
4. Switch the display mode of the list to `tree_table`

**Comment by danrot** [comment]
Fixed in #5348
