### ISSUE TITLE
External and internal links in CKEditor get deleted in table

### ISSUE THREAD

**Issue by mtcool112** [sulu/sulu#5250]
| Q | A
| --- | ---
| Sulu Version | 2.0.4
| Browser Version | Chrome Version 69.0.3497.81 (Official Build) (64-bit)

# Actual Behavior

When I create a block with a textfield and add a table with a link inside, everything goes right and I can save it.
Only when I re-open the same block it doesn't add the link to the text, so when I save it the link is gone.

# Expected Behavior

If you re-open the textblock the link inside the table should still be available

# Steps to Reproduce

1. Add a block with a text_field.
2. Create a table with items.
3. Make one of the items a Link.
4. Save the page.
5. Re-open the same block (the link(s) will be gone)
6. Change something inside the block. 
7. Save the page again.

**Comment by danrot** [comment]
I have just tested it, and the behavior is exactly the same when the text editor is used outside of a block...

**Comment by nnatter** [comment]
Tried to debug this a bit. Looks like the link is only deleted if it is the first elemen in the cell of the table 🤔

**Comment by danrot** [comment]
fixed in #5592
