### ISSUE TITLE
Error if API data is not formatted correctly for content type "media_selection

### ISSUE THREAD

**Issue by MagisterSiltar** [sulu/sulu#5253]
| Q | A
| --- | ---
| Sulu Version | Sulu (2.0.4)
| Browser Version | Firefox 75.0 (64-Bit)

# Actual Behavior

If you create a Content Type "media_selection" with the name "documents" for a custom entity form in the Sulu Admin area, this leads to a Javascript Error as soon as you try to assign a media file.

<img width="1055" alt="Bildschirmfoto 2020-04-22 um 10 47 12" src="https://user-images.githubusercontent.com/8614830/79961215-ab247a00-8486-11ea-9ec0-dcea941e23be.png">

# Expected Behavior

Either you get an error message that "documents" is not allowed as name or the selection of media files works normally.

# Steps to Reproduce

`
        <property name="documents" type="media_selection">
            <meta>
                <title>Documents</title>
            </meta>

            <params>
                <param name="types" value="image,video"/>
                <param name="displayOptions" type="collection">
                    <param name="leftTop" value="true"/>
                    <param name="top" value="true"/>
                    <param name="rightTop" value="true"/>
                    <param name="left" value="true"/>
                    <param name="middle" value="false"/>
                    <param name="right" value="true"/>
                    <param name="leftBottom" value="true"/>
                    <param name="bottom" value="true"/>
                    <param name="rightBottom" value="true"/>
                </param>
                <param name="defaultDisplayOption" value="left"/>
            </params>
        </property>
    </properties>
`

# Possible Solutions
Hint: If you change the type to single_media_selection, everything works fine.

**Comment by alexander-schranz** [comment]
Does the error happens only on an exist entity or when selecting the media_selection inside a add form which is not saved yet?

If it happens only an exist entity only it basically should be something wrong with your api. 

The media selection expect from your api something like:

```
{
    "ids": [1,2],
    "displayOption": "left"
}
```

If the api maybe still return the format of the single media selection `{"id": 1, "displayOption": "left"}` it could fail when the js try to set the ids after you select them.

**Comment by MagisterSiltar** [comment]
Hello Alex

You're right, the problem seems to be the data. I added the field afterwards and the array is probably configured incorrectly. "documents:	[]" Maybe it would be useful to add a more understandable exception?

Thanks for your help.

**Comment by MagisterSiltar** [comment]
Hello Alex

You're right, the problem seems to be the data. I added the field afterwards and the array is probably configured incorrectly. "documents:	[]" Maybe it would be useful to add a more understandable exception?

Thanks for your help.

**Comment by nnatter** [comment]
I think throwing a descriptive error in the `media_selection` and `single_media_selection` would be a good idea! I remember that this problem popped up in the Slack channel too.

**Comment by alexander-schranz** [comment]
@nnatter maybe there should be no error or just a warning as I could think the same would maybe happen in pages if you switch in a template from `single_media_selection` to `media_selection`.

**Comment by nnatter** [comment]
@alexander-schranz Just checked this - it does not happen with pages because the `MediaSelectionContentType` does handle this case 🙂 
https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php#L73

**Comment by danrot** [comment]
What should happen when switching between content types that can't really be translated is still a question that we have not answered :see_no_evil: I thought there is an issue about that as well, and I wanted to link it, but I can't find it :confused:

**Comment by danrot** [comment]
Okay, it was #46, and we closed it, because we were discussing this for years :see_no_evil:

**Comment by alexander-schranz** [comment]
Oh for pages it does work as the content type itself does return the correct format. So its only a problem for own api's which just return the json directly from the database or forget serialize it false.

**Comment by danrot** [comment]
Fixed in #5256
