### ISSUE TITLE
Webspace export doesn't work

### ISSUE THREAD

**Issue by amb-jarek** [sulu/sulu#5265]
| Q | A
| --- | ---
| Sulu Version | 2.0.6
| Browser Version | not important
| Symfony/*, (symfony/twig-bundle) | 4.4.7
| twig/twig | 2.12.5

# Actual Behavior

I'm trying to copy data from one env to another. But when I execute 
```
./bin/websiteconsole  sulu:webspace:export myexportfile mywebspace en
```
I'm getting following error
```
In Export.php line 239:

  Attempted to call an undefined method named "exists" of class "Twig\Environment".
```
I checked it using `websiteconsole`, `adminconsole` and `console`. Everytime result is the same.
Snippets export also doesn't work.
# Expected Behavior

Export should work or if supplied parameters are wrong I should get proper error message

# Steps to Reproduce

Described above

# Possible Solutions

No idea

**Comment by alexander-schranz** [comment]
@amb-jarek Thank you for creating this issue this was fixed in #5191 and will be available in the next release.

**Comment by amb-jarek** [comment]
@alexander-schranz thank you for so fast response. When do you guys plan to release new version?

**Comment by alexander-schranz** [comment]
@amb-jarek we hope to do a release in the next days.
