### ISSUE TITLE
Wrong title of internal links returned by breadcrumb extension

### ISSUE THREAD

**Issue by DavidFeller** [sulu/sulu#5276]
| Q | A
| --- | ---
| Sulu Version | 2.1-RC1

# Actual Behavior
The twig extension `sulu_breadcrumbs` returns the linked content's title instead of the given title of an internal link.

# Expected Behavior
If an internal link has a "Link Title" (screenshot attached), this title should be returned by the twig extension.

![sulu_breadcrumbs](https://user-images.githubusercontent.com/2094727/81177150-8102aa00-8fa6-11ea-8014-b7b979a238df.jpg)

**Comment by nnatter** [comment]
Thanks for reporting! Might be useful to tackle this together with #3721

**Comment by alexander-schranz** [comment]
This was fixed by #5879
