### ISSUE TITLE
Set internal link in text_editor throws exception

### ISSUE THREAD

**Issue by manuxi** [sulu/sulu#5286]
| Q | A
| --- | ---
| Sulu Version | 2.1.0-RC1
| Browser Version | Chrome 81.0.4044.138

# Actual Behavior

When I link an existing page in the text_editor and save this page I see console errors (500, same Notices as described further down). After saving the page with the internal link is broken, I'm not able to load it correctly. Reported: "Notice: Undefined index: href" in vendor\sulu\sulu\src\Sulu\Bundle\MarkupBundle\Markup\LinkTag.php (line 111). 

Since I could not edit, open or even delete the page in the admin area I had to delete the page manually from the database.

# Expected Behavior

Link is working.

# Steps to Reproduce

see above.
I remember this has been working before 2.1.0-RC1; but since I recreated the blocks I have no old internal link to test. To update to 2.1.0-RC1 (from 2.0) I changed the version in composer.json and made an update.

**Comment by alexander-schranz** [comment]
@manuxi composer update alone will not update your projects admin JS build. You will need to update it or rebuild it [see update docs](https://docs.sulu.io/en/2.0/upgrades/upgrade-2.0.html). Can you check if the error does also occur after you updated the build.

**Comment by manuxi** [comment]
Ok, I've tried this. At the end, it was not successfull. 

I'm using 2.1.0-RC1. When I ran npm install / npm run build the package.json got some old versions and the text editor disappeared. 

"@ckeditor/ckeditor5-theme-lark": "^14.0.0",	=> skeleton is ^18.0.0
"file-loader": "^4.2.0",						=> ^6.0.0
"mini-css-extract-plugin": "^0.8.0",			=> ^0.9.0
"postcss-hexrgba": "^1.0.0",					=> ^2.0.0
"raw-loader": "^3.1.0",						=> ^4.0.0

Entering "php bin/console sulu:admin:download-build" gave me only the message:

'The files in the local "\assets\admin\" folder do not match the ones in the remote repository "https://raw.githubusercontent.com/sulu/skeleton/2.1.0-RC1".
Either bundles with custom JavaScript have been added, which means it has to be done manually with NPM, or the files in your repository are outdated and have to be copied from the remote repository.'

So I deleted the node_modules and package.lock and updated the package.json from the skeleton repo. Another "php bin/console sulu:admin:download-build" fixed the missing editor issue.

I added a test block with an internal link again, but am getting the same error again :(

**Comment by manuxi** [comment]
Ok, it may be my fault by clicking too fast...? 
Try this to reproduce it (backup your db before trying this!):
Mark a string in the editor, click on internal link (page), select a page. In the next overlay an indicator appears as long as the page isn't updated in the field "link URL". If you click on confirm while the indicator is shown respectively the "link URL" is not set, you'll be in trouble.

**Comment by danrot** [comment]
Fixed in #5289
