### ISSUE TITLE
Upload into system folder not possible, no message

### ISSUE THREAD

**Issue by mavimedia** [sulu/sulu#5292]
| Q | A
| --- | ---
| Sulu Version | 2.1.0-RC1
| Browser Version | Chrome 81 (Mac)

# Actual Behavior

Uploading images into system folder is not possible. There is no information.
Nothing happens. It seems like an error.

# Expected Behavior

Upload buttons could be disabled and/or a message could appear, that upload into system folder is not possible.

**Comment by danrot** [comment]
This has been fixed in #5279 already. This is already part of 2.0.7 and will also be included in the next RC.
