### ISSUE TITLE
Admin UI bug on 403 response

### ISSUE THREAD

**Issue by antonstsk** [sulu/sulu#5296]
| Q | A
| --- | ---
| Sulu Version | 2.0.7

Admin UI not reacting to the 403 response when user doesn't have permissions to edit content on certain tabs.

**Actual Behavior**
It does remove the possibility to access prohibited sections but does not lock the permissions tab on page edit.
(Permissions tab on screenshoot but also happens to settings tab with change log section)

![image](https://user-images.githubusercontent.com/33395021/82139899-d7d07500-982b-11ea-8cea-8b9a99041006.png)

**Expected Behavior**
Same as everywhere remove that tab if user not allowed to edit permissions or at least put a lock icon instead of loader circle.
Example:

![image](https://user-images.githubusercontent.com/33395021/82140011-c045bc00-982c-11ea-8659-3dcd08eb63a1.png)

**Steps to Reproduce**
1. Create two users  and two roles (admin, user).
2. Using a user with admin role revoke the possibility to administrate some admin sections (Contacts, Global, Security & Settings).
3. Edit any page and access to the "permissions" tab.

**Comment by nnatter** [comment]
Hey, thanks for reporting! What is the reason for closing it?

**Comment by antonstsk** [comment]
> Hey, thanks for reporting! What is the reason for closing it?

That's because in guys from slack told me how to do it right :)
But still I guess this error remains if you do it like I did.

**Comment by nnatter** [comment]
Oh alright. Then what is the right way to do this? 🙂 
I am afraid i did not see that message in Slack. Would be nice to document to solution here in case someone else has the same issue.

**Comment by antonstsk** [comment]
> Oh alright. Then what is the right way to do this? 🙂
> I am afraid i did not see that message in Slack. Would be nice to document to solution here in case someone else has the same issue.

Yes, sorry, here it is:
![image](https://user-images.githubusercontent.com/33395021/82297733-5c99cb00-99b3-11ea-9f2b-4a770522a158.png)
