### ISSUE TITLE
Paste into resourceLocator field does not filter out special characters

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5301]
| Q | A
| --- | ---
| Sulu Version | 2.0.6
| Browser Version | -

# Actual Behavior

When you example copy `/example/thank-you` or something like `Hello World /// Test` into the url field it will add that directly without filtering special characters out.

# Expected Behavior

As you can not type `/` or other characters you should also not be able to paste this characters into the url field.

# Steps to Reproduce

![paste-url-with-slash](https://user-images.githubusercontent.com/1698337/82315808-2ae12e00-99cc-11ea-9615-266e0598960b.gif)

# Possible Solutions

Filter out special characters also when pasted.

**Comment by danrot** [comment]
Good catch! It is also questionable what happens if you type an umlaut in the URL field. Should nothing happen? Or should e.g. "ä" automatically be replaced by "ae"?

**Comment by alexander-schranz** [comment]
@danrot thats a good question. I thought we are allowing `äöü` but currently it seems to end in a ResourceLocatorNotValidException atelast in language `en` and `de`.

**Comment by kfrohwein** [comment]
In our case the string was "ResourceLocator '/20200714-reise-zum-nordkap–bis-zum-ende-elektrisch' is not valid" maybe it failed because of the leading slash.

**Comment by danrot** [comment]
Fixed in #5591
