### ISSUE TITLE
Default snippet selection overlay ignores snippet type

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#5311]
| Q | A
| --- | ---
| Sulu Version | 2.0.7

# Actual Behavior

When I want to select the default snippet for a specific type/area, the overlay contains all snippets regardless of their type. When I select a snippet of the wrong type, the administration interface crashes.

![current behaviour](https://i.imgur.com/eP8EMRX.gif)

# Expected Behavior

The overlay should only contain snippets that are allowed for the type/area.

**Comment by danrot** [comment]
Fixed in #5313
