### ISSUE TITLE
ErrorController Exceptions issues

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#5314]
| Q | A
| --- | ---
| Sulu Version | RC1
| Browser Version | All

# Actual Behavior

There are some errors in the new ErrorController :

- Some exceptions doesn't have [getStatusCode method ](https://github.com/sulu/sulu/blob/2cee553e46edd222e798a50a43f27618481a9481/src/Sulu/Bundle/WebsiteBundle/Controller/ErrorController.php#L64) Ex: MissingParameterException
- If format doesn't exists `Twig\Error\LoaderError `is launched

# Expected Behavior

Capture all errors and show correctly the template defined or default

# Steps to Reproduce

Set APP_ENV=prod and try some urls: 

/test.jpg
/test.php
/.env 

# Possible Solutions

- Change 
```$code = $exception->getStatusCode();``` by ```$code = $flattenException->getStatusCode();```
- Check if the template exists before render 
```
        // render the default twig error template when no webspace template found or template doesn't exists
        if (!$errorTemplate || !$this->twig->getLoader()->exists($errorTemplate)) {
            return $this->symfonyErrorController->__invoke($exception);
        }
````

**Comment by alexander-schranz** [comment]
Thank you for report. You are correct this should be `$flattenException->getStatusCode()`. Do you want to create a PR?

**Comment by plozmun** [comment]
Yes, of course. And the other one? Do you think we have to check if the template exists? Maybe in ```getErrorTemplate``` method?

**Comment by alexander-schranz** [comment]
If the template does not exist its false configured in the webspace and should error. So I there definitely an error should happen.

**Comment by plozmun** [comment]
No but for example if `error-404` template is configured in webspace but `error/error-404.xml.twig` doesn't exists in templates folder it fails because is never checked .

https://github.com/sulu/sulu/blob/2.1.0-RC1/src/Sulu/Component/Webspace/Webspace.php#L468

This returns error/error-404.xml.twig and later is render directly. https://github.com/sulu/sulu/blob/2.1.0-RC1/src/Sulu/Bundle/WebsiteBundle/Controller/ErrorController.php#L74

**Comment by alexander-schranz** [comment]
Okay I understand the check should be then in the `getErrorTemplate` template method and return null if the template does not exist.

**Comment by plozmun** [comment]
Done in #5315

**Comment by alexander-schranz** [comment]
#5315 is merged
