### ISSUE TITLE
Image search field not working for single_media_selection

### ISSUE THREAD

**Issue by martinlagler** [sulu/sulu#5320]
| Q | A
| --- | ---
| Sulu Version | 2.1.0-RC1

# Actual Behavior

How does Sulu behave at the moment? 
`bin/websiteconsole massive:search:reinde`
![image](https://user-images.githubusercontent.com/24388840/83636908-03cb5480-a5a7-11ea-9e6f-b1ff7636fb8f.png)

# Expected Behavior

Use the id of the `single_media_selections` instead of the ids.

# Steps to Reproduce

Add `<tag name="sulu.search.field" role="image" index="false" />` to a `single_media_selection` and run `bin/websiteconsole massive:search:reinde`

**Comment by danrot** [comment]
Fixed in #5354
