### ISSUE TITLE
Api not return error messages on prod

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5336]
| Q | A
| --- | ---
| Sulu Version | effects currently all versions
| Browser Version | -

# Actual Behavior

Api not return error messages on production.

# Expected Behavior

The api should return the error messages on production.

# Steps to Reproduce

1. Disable debug

```env
APP_DEBUG=0
```

2. Login on sulu

3. Visit e.g.: https://sulu.rocks/admin/api/media/1

# Possible Solutions

That under prod/stage the correct error message e.g.: [MissingArgumentException](https://github.com/sulu/sulu/blob/release/2.1/src/Sulu/Component/Rest/Exception/MissingArgumentException.php) we would need to add this exception to the fos_rest messages mapping, else fos rest will just return the status code text [see logic here](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3d8501dbdfa48811ef942f5f93c358c80d5ad8eb/Serializer/Normalizer/AbstractExceptionNormalizer.php#L54-L60).

**Comment by danrot** [comment]
Wondering why they have chosen to implement it this way... I could imagine that they consider this a possible security vulnerability. Especially in your example the following string would be shown to the requester:

```
Missing parameter locale in Sulu\\Bundle\\MediaBundle\\Controller\\MediaController
```

This would allow to infer that Sulu and therefore PHP is used, delivering valuable information to potential attackers. This is only one example, I could easily imagine, that other exceptions would even contain more information about the underlying system.

Actually the person calling this API would probably not even really be interested in what controller was called, but only what they were doing wrong. Therefore I think that in the above case a message like this would be sufficient:

```
Missing parameter locale
```

Furthermore I would suggest checking all subclasses of `RestException`, make sure their messages don't include any sensitive information, and add them to the `fos_rest.exception.messages` configuration.

**Comment by niklasnatter** [comment]
As described in https://github.com/sulu/sulu/issues/5312#issuecomment-777291327, implementing the `TranslationErrorMessageExceptionInterface` will add a translated error message to the response. Every other exception will lead to a generic error message such as `"message": "Bad Request"`. This is done by the `FlattenExceptionNormalizer` of the FOSRestBundle:
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/8779ceebf715d1c60bd10286fce9d32ed03c484a/Serializer/Normalizer/FlattenExceptionNormalizer.php#L49-L53
