### ISSUE TITLE
Splitting template information into sections

### ISSUE THREAD

**Issue by antonstsk** [sulu/sulu#5344]
# Problem description
Can't split admin data into blocks.

# Proposed solution
Would've been cool to have a way to create arrays of data. Using sections or specific names with slashes or dots.

![image](https://user-images.githubusercontent.com/33395021/84520908-8a351400-acd4-11ea-9ab5-6c852d120bb3.png)

**Comment by nnatter** [comment]
The `page_excerpt` form already uses names like `ext/excerpt/title` to send objects (in this case a `ext` object that contains a `excerpt` object) to the server when saving the form. I think it would be nice if we could use this syntax for page templates too 🙂

**Comment by alexander-schranz** [comment]
This is similar to #5063 so I will close this one. Feel free to add your thoughts there. I think it should not be so much work to implement this we just need to discuss it how we save it in PHPCR.
