### ISSUE TITLE
Deprecating security groups

### ISSUE THREAD

**Issue by NeuralClone** [sulu/sulu#5349]
| Q | A
| --- | ---
| Sulu Version | 2.0.8
| Bug? | Unclear
| Browser Version | Doesn't appear to matter

# Actual Behavior

Groups in the SecurityBundle lack a UI to manage them in the admin panel.

# Steps to Reproduce

Use the instructions found in the [Getting Started guide](https://docs.sulu.io/en/2.0/book/getting-started.html) in the Sulu documentation and create a user with permissions to view, add, edit, and delete roles, groups, and users.

# Additional Information

I've been looking through the current Sulu documentation and I've run into a bit of trouble with user groups. In the [SecurityBundle documentation](https://docs.sulu.io/en/2.0/bundles/security.html), it says:

> In addition to that a user can have some roles and groups assigned, whereby a group can consist of multiple other groups and roles.

And then the feature isn't elaborated upon. The concept of groups being assigned roles is fairly self-explanatory but as far as I've been able to tell, there is absolutely no trace of groups in the admin panel except when editing permissions for a specific role.

I'm using the default configuration found in [sulu/skeleton](https://github.com/sulu/skeleton). I've looked through the source code and I've found the code that handles user groups. Even the appropriate Doctrine model exists. The actual database tables have also been automatically created.

But how are groups actually used and/or enabled? I've double checked the permissions for my admin user and the user has the ability to view, add, edit, and delete groups along with roles and users. Yet I can't actually create groups through the admin panel and there isn't a console command that handles that. They don't appear in the demo on the Sulu website either.

![Security](https://user-images.githubusercontent.com/678221/84695868-880fc700-af19-11ea-8b67-36da0e63b909.png)

Are user groups supposed to be a feature that's functional by default or are they something we're supposed to manually add to the admin panel if we want to use them? Are there settings somewhere that let us enable and/or configure them?

It's very unclear how groups are intended to be used without additional information. I feel like I'm missing something really obvious.

**Comment by alexander-schranz** [comment]
@NeuralClone Thank you for your report. 
I'm not sure if there where some projects using the groups but in the core I think they are not implemented and have no effect atleast in the current versions, so here definitly the Documentaiton is missleading and should be adopted. Do you have any usecase for groups? Can you provide some information what you want to handle over groups and can not be greated with the current roles?

/cc @sulu/core-team

**Comment by NeuralClone** [comment]
Hi @alexander-schranz,

Thanks for your response and for clarifying some of my questions about groups in Sulu. That's more or less what I suspected based on the code I looked at but it's good to have confirmation.

It's absolutely true that the current user roles should be able to get the job done in most cases. In fact, I really like the system already in place. It's easy to use and very flexible. If you combine that system with Symfony's role hierarchy, it covers most cases I can think of. It's one of the factors that led me to start integrating Sulu into a project.

As far as groups and roles go, I'm thinking more about situations where there are a lot of users with many different roles. When you have a small number of users, directly editing their roles is rather straightforward. But if you scale up the number of users, it starts becoming a bit cumbersome to edit the roles of each user and make sure everyone has the right permissions.

Assigning roles based on the group someone is added to becomes far more appealing under those kind of conditions. I also fully realize that that particular use case probably isn't the norm for most developers using Sulu.

**Comment by alexander-schranz** [comment]
@NeuralClone I could think that `Users` Tab on the `Role` Detail view could make sense. So you have a better overview of which user have a specific Role in such big systems.

**Comment by danrot** [comment]
Groups are partly implemented, so I think if you would create the required database entries on your own, the security check would work as expected. I think we have to decide if we want to support groups ultimately, or if we say that the system gets too complicated then from a UX perspective.

If we say we don't want to implement the UI for that, we should probably get rid of the entire code handling this, resp. at least deprecate all of it and delete it in the next major release.

But for that decision we definitely need the opinion of @chirimoya.

**Comment by NeuralClone** [comment]
Thanks, guys. This has definitely given me some stuff to think about and whether I want to devote much time to groups.

The simplest solution is certainly to just deal with user roles. That approach is straightforward and easy to understand and use. On the other hand, the existing code for groups does a lot of the heavy lifting for a possible UI implementation and could add some flexibility in situations with a lot of users. But I absolutely agree that groups complicate things. So I think a strong case can be made for and against groups.

Regardless of what ends up being decided, I really appreciate that this is being discussed and considered. :+1:

**Comment by chirimoya** [comment]
@NeuralClone thanks for raising the topic. I think we made the topic too big initially. I would say that we should deprecate groups. If we need some kind of hierarchy in future, we could even introduce that for roles, but currently I don't see the added value of groups compared to the added complexity.

**Comment by niklasnatter** [comment]
Thanks for bringing this up! We have deprecated the functionality in #5912
