### ISSUE TITLE
Contact Account Selection only returns ID of position

### ISSUE THREAD

**Issue by marcostastny** [sulu/sulu#5358]
# Problem description

The contact account Selection new to Sulu 2 only returns the ID of a Job Position. Currently there seems to be no Solution for getting the Job Position of a Contact within the Contact Account Selection. As a quick Solution you are able to load the whole contact with the sulu_resolve_contact Twig extension and then check the AccountContact relation. There is also the possibility to write a user defined twig extension which loads contact positions over the Repository.

# Proposed solution

Either enhance the Serialization of the contact to also include the position (preferably like in sulu 1.6 where you could use contact.position.position, as this would mean no rewriting of code is needed in update cases) or provide a twig extension which loads the position of contact by the given id.

**Comment by alexander-schranz** [comment]
This is related to following PR #4895

**Comment by danrot** [comment]
Fixed in #5380
