### ISSUE TITLE
False Webspace loaded when having no permission

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5359]
| Q | A
| --- | ---
| Sulu Version | 2.1.0-RC1
| Browser Version | Browser name and version

# Actual Behavior

False Webspace loaded when not having no permission.

# Expected Behavior

The webspace which I have permissions for should be loaded

# Steps to Reproduce

1. Create a installation with 2 Webspace
2. Go to User Roles and give Permission only to second webspace (base.sulu.io, sulu.io (have permisson for this) )
3. Remove maybe exist user settings
> DELETE FROM se_user_settings WHERE settingsKey = 'sulu_page.webspace_tabs.webspace';
3. Reload Page so new Permission and user settings loaded
4. Click on Webspaces

![Screenshot_2020-06-23 SULU](https://user-images.githubusercontent.com/1698337/85401091-bdd82f80-b559-11ea-9ed3-f1e99562b1e9.png)

Now you will see the false webspace. As I have no permissions there I can't do anything.

# Possible Solutions

Load the first webspace which I have permission for instead of the first webspace which is available.

**Comment by danrot** [comment]
This shouldn't be too hard to implement. In the following line we are currently taking the first webspace available; I guess that's the cause of the issue:

https://github.com/sulu/sulu/blob/6793028c2aa0340c85cfe03560c54b73f4a2274f/src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php#L109

We would have to adjust that in a way, that the `securityChecker` is used. It should look similar to the `hasPermission` call in `PageAdmin::hasSomeWebspacePermissions` method, just with the minor difference that not all webspaces are checked:

https://github.com/sulu/sulu/blob/6793028c2aa0340c85cfe03560c54b73f4a2274f/src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php#L405-L419
