### ISSUE TITLE
Links inside the text editor do not respect http port

### ISSUE THREAD

**Issue by thenetexperts** [sulu/sulu#5364]
| Q | A
| --- | ---
| Sulu Version | 2.1.0
| Browser Version | N/A

# Actual Behavior

I am running sulu via local php server on port 9090.
A link created inside a text field is rendered without the port. For example it renders `https://127.0.0.1/en/test`

# Expected Behavior

The link should be rendered as `https://127.0.0.1:9090/en/test`

# Steps to Reproduce

- Bootstrap a fresh sulu 2.1.0
- Create a new page
- Add a textfield and add a link inside the textfield (an internal link)

# Possible Solutions

Somewhere the port information is lost and needs to be added.

**Comment by nnatter** [comment]
The `ContentPathTwigExtension` solves this with the following lines:
https://github.com/sulu/sulu/blob/2be30ce7561911b243884ae27e86907899fa2639/src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php#L86-L91

I guess we need to add something similar to the `PageLinkProvider` and the `PagesSitemapProvider`.

**Comment by nnatter** [comment]
Should be fixed via #5374
