### ISSUE TITLE
Automatically adding of noopener to target _blank links in ckeditor

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5368]
# Problem description

Its recommended that `target="_blank"` links should set `rel="noopener"` so the target page can not access the JS context of the opener page. Mostly you read about using rel="noopener noreferrer" but noreferrer has no inpact of the security and would only have negative inpact on google analytics so its by google recommended to set only rel="noopener".

# Proposed solution

Following steps are needed:

- sulu:link with target=_blank should have automatically a noopener added `HTMLMarkupListener`.
- external links inside the ckeditor should get automatically noopener see [Link](https://ckeditor.com/docs/ckeditor5/latest/features/link.html) configuration

**Comment by danrot** [comment]
Since I guess that this should always be set, no matter where the link was set, I would suggest to implement that in `sulu:link`.

**Comment by alexander-schranz** [comment]
@danrot sorry that was no OR in the Proposed solution that was a AND. For sulu:link its not so important as it is a internal link, important it is for external links in the ckeditor which are set as `<a href` and are not effected currently by the MarkupListener.

**Comment by alexander-schranz** [comment]
As never requested and as analysed for my SEO workshop this issue does not longer exist and was patched in modern browsers that `noopener` is default and so the target page does not have access to it.
