### ISSUE TITLE
Allow multiple config folder for page or Snippet

### ISSUE THREAD

**Issue by TheCadien** [sulu/sulu#5370]
# Problem description

I would like to get more structure in the configuration folder.

At the moment it is possible to adjust the folder paths, but apparently it is not possible to add several folders, for example for snippets or pages.

# Proposed solution

In my imagination, a configuration for this could look like this

`
sulu_core:
    webspace:
        config_dir: "%kernel.root_dir%/Resources/webspaces"
    content:
        structure:
            default_type:
                snippet: "default"
            paths:
                homepage:
                    path: "%kernel.root_dir%/Resources/templates/pages"
                    type: "home"
                page:
                    path: "%kernel.root_dir%/Resources/templates/pages"
                    type: "page"
                pages_blog:
                    path: "%kernel.root_dir%/Resources/templates/pages/blog"
                    type: "page"
                snippet_folde_one:
                    path: "%kernel.root_dir%/Resources/templates/snippets/folder_one/"
                    type: "snippet`
                snippet_folde_two:
                    path: "%kernel.root_dir%/Resources/templates/snippets/folder_two/"
                    type: "snippet`

**Comment by alexander-schranz** [comment]
@TheCadien its possible the key ist just to override the exist paths. If you use a unique key you can add additional folders:

```yaml
custom_pages:
    path: "%kernel.project_dir/...."
    type: Page
```

**Comment by TheCadien** [comment]
oh nice :D ! 
I think thats i need ! Tanks
