### ISSUE TITLE
Event weights for removing PHPCR nodes can result in the wrong order

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5376]
| Q | A
| --- | ---
| Sulu Version | 2.1.0

# Actual Behavior

The default installation runs fine. Still our installation for some reason gives a different order after a PHP krsort()

# Expected Behavior

Fixed order of events

# Steps to Reproduce

Sorry I can not really reproduce the behaviour still:

Vanilla Sulu does:

1. StructureRemoveSubscriber 550
2. CustomUrlSubscriber 550
3. ContentMapperSubscriber (PreRemove) 500
4. RemoveSubscriber 500

My Sulu intance does:

1. CustomUrlSubscriber 550
2. StructureRemoveSubscriber 550
3. RemoveSubscriber 500
4. ContentMapperSubscriber (PreRemove) 500

If the RemoveSubscriber is run before the ContentMapperSubscriber the PHPCR node gets status 4 which means it is deleted. The content mapper checks the webspace then getPath which will result in an PHPCR Exception that the node is deleted in jackalope/jackalope/src/Jackalope/Item.php:685.

# Possible Solutions

Reoder the events a bit. I provide a patch soon and we can discuss the weights to use.

**Comment by nnatter** [comment]
Fixed by #5378
