### ISSUE TITLE
Category selection overlay not scrollable

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/sulu#5377]
| Q | A
| --- | ---
| Sulu Version | 2.1
| Browser Version | Chrome

# Actual Behavior

When many categories and opening the smart content filter for categories, and when you expand all of the subcategories suddenly the cross to exit the overlay is not available anymore (until your close all).

![Schermafbeelding 2020-06-30 om 14 47 20](https://user-images.githubusercontent.com/17956647/86127712-a3193400-bae0-11ea-83e0-bc907a5bce22.png)

# Expected Behavior

Maybe a scroll behaviour that the list of categories is limited height

# Steps to Reproduce

Add many categories, open a smart content filter and browse through categories

# Possible Solutions

Scroll functionality with max-height (like in fragment?)

**Comment by danrot** [comment]
Fixed in #5402

**Comment by danrot** [comment]
@cirykpopeye Thanks for reporting!
