### ISSUE TITLE
Add the option to open link in a new page

### ISSUE THREAD

**Issue by GillesKnockaert** [sulu/sulu#5382]
# Problem description
I wanted an external link in my main navigation.

# A clear description of what the problem is.
I added a page then added it to the menu and in the settings tab I selected External link as page type. This works perfectly except the link takes me away from the site so this should open in a '_blank' window. this way they won't leave my site completely.

# Proposed solution
Add a dropdown with possible options or just a checkbox to open in a new tab. Or maybe by default open 'external link' page types in a new window. not needed for 'internal link' page types.

# A clear description of what you want to be implemented.
As stated above.

**Comment by alexander-schranz** [comment]
If you want to link all external links with target="_blank" you can do it in the twig template this way:

```twig
            {% for item in sulu_navigation_root_flat('main', 1) %}
                {% set itemUrl = sulu_content_path(item.url) %}
                <a href="{{ itemUrl }}" title="{{ item.title }}"
                   {% if item.nodeType == 4 %}target="_blank" rel="noopener"{% endif %}{# add target blank to target page #}
                   class="navbar__item{{ app.request.uri starts with itemUrl ? ' navbar__item--active' : '' }}">
                    {{ item.title|upper }}
                </a>
            {% endfor %}
```

**Comment by GillesKnockaert** [comment]
true but wouldn't it be nice if you could set it in the backend? or that it's acting like this by default I don't know why else you would select external link.

**Comment by alexander-schranz** [comment]
@GillesKnockaert maybe it depends on the situation but if the developer don't take it into account when creating the `<a href` link it will do nothing and then its strange to have that option.

**Comment by nnatter** [comment]
As far as I understand this, the developer is free to add a `target="_blank"` when rendering the link in the twig template. The snippet provided by @alexander-schranz shows, how to add that to all navigation items that are external links.

I dont think Sulu can adjust anything here, because the rendering of the link happens in the twig template inside of the project. Therefore I am going to close this. Fee free to reopen the issue, if i misunderstood something 🙂
