### ISSUE TITLE
when pasting a string with a '/' in the resource locator it changes the first part of the resource locater.

### ISSUE THREAD

**Issue by GillesKnockaert** [sulu/sulu#5384]
| Q | A
| --- | ---
| Sulu Version | Specific version or SHA of a commit --> 2.1.0
| Browser Version | Browser name and version -> latest chrome version

# Actual Behavior

If you paste a string with a '/' in the resource locater, it copies everything before the '/' to the part of the resource locator that you can't change. By doing this the resource locator is not valid and it is impossible to save the page (if that part contains spaces or special chars).

![image](https://user-images.githubusercontent.com/7395323/86241098-9f4de600-bba2-11ea-92cf-187c197792fb.png)

# Expected Behavior

give an error to the user that the input contains invalid chars.

# Steps to Reproduce

copy a string with a '/' in it in the resource locator field.

# Possible Solutions

it's not possible to type a '/' in there but you can paste a '/' there, i would expect sulu not to change the part of the resourcelocator that you can't change but just show that the field is invalid. So don't move the text.

**Comment by alexander-schranz** [comment]
@GillesKnockaert thank you for reporting this issue. There is an similar issue for this here: #5301. So I will close this one. Feel free to add your thoughts there.
