### ISSUE TITLE
block won't open after you copy a page to another language

### ISSUE THREAD

**Issue by GillesKnockaert** [sulu/sulu#5386]
| Q | A
| --- | ---
| Sulu Version | 2.1.0
| Browser Version | Latest Chrome version

# Actual Behavior

I have a block with just a text field, when I create the page in another language I can't open that block until I refresh the page.

# Expected Behavior

The block should just open ;)

# Steps to Reproduce
i added a page with a block on. saved the page and then selected another language. I get prompted to copy the content from another language, i chose to do so. 
But when I then try to open the block, it won't open, it just does nothing.

when i refresh the browser page, it works again.

**Comment by nnatter** [comment]
Hey, thanks for reporting! I just tested this with `2.2.0` and it looks like it is fixed there. Feel free to reopen the issue if the problem still occurs for you 🙂
