### ISSUE TITLE
After changing page template property values (select) the old values are stuck on the saved pages

### ISSUE THREAD

**Issue by timkoopmans50** [sulu/sulu#5388]
| Q | A
| --- | ---
| Sulu Version | 2.1
| Browser Version | *all

# Actual Behavior

I have event pages as declared in config/templates/pages/event.xml : 
        <property name="somepropname" type="select">
            <meta>
                <title lang="en">Something</title>
            </meta>

            <params>
                <param name="values" type="expression" value="service('app.list').getValues()" />
            </params>
        </property>

lets say getValues return A B and C. We now create an event page and select A, B and C. 
Now we change the return values of getValues to 1, 2 and 3. We go back to our event page, select 1, 2 and 3. A,B and C are not visible in the select. After saving, the headless bundle returns A,B,C,1,2,3 instead of just 1,2,3

# Expected Behavior
After saving a page, values that are no longer in the property select should be removed

# Steps to Reproduce

Described under "actual behavior".

**Comment by danrot** [comment]
Fixed in #5397.
