### ISSUE TITLE
when adding a location on a map with a lat or long of 0 you can't save it

### ISSUE THREAD

**Issue by GillesKnockaert** [sulu/sulu#5389]
| Q | A
| --- | ---
| Sulu Version | 2.1.0
| Browser Version | latest Chrome

# Actual Behavior
You can't save a location on a map when the lat or long is 0.

# Expected Behavior
you should be able to add a location with 0 in one or both of these fields.

# Steps to Reproduce
type a '0' in the lat or location field

# Possible Solutions
the location lat 0 long 0 is also a locations so pick that as default and just allow a 0 in the fields.

**Comment by nnatter** [comment]
Thanks for reporting!
