### ISSUE TITLE
Focuspoint selection is not responsive

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5390]
| Q | A
| --- | ---
| Sulu Version | 2.1.0
| Browser Version | Crome, Ubuntu, Version 83.0.4103.116 (Official Build) (64-bit)

# Actual Behavior

Really a minor thing but I just wanted to tell:

![focuspoint](https://user-images.githubusercontent.com/245385/86476009-00fa8580-bd46-11ea-8d14-6832365f8d4f.gif)

If you change the screensize while setting the focuspoint the selected image will resize but not the focuspoint selectors.

# Expected Behavior

Everything rezises

# Steps to Reproduce

Just try to change the focus point and rezise the screen

**Comment by nnatter** [comment]
This will hopefully be fixed by #5400 - thanks for reporting!

**Comment by danrot** [comment]
Was fixed in #5431 

@nnatter @alexander-schranz Just a friendly reminder, to remember closing issues, if you have fixed them :wink:
