### ISSUE TITLE
Preview image for PDF with dots in the filename is regenerated on each pageload of media-list

### ISSUE THREAD

**Issue by kjueni** [sulu/sulu#5394]
| Q | A
| --- | ---
| Sulu Version | 2.1.0
| Browser Version | -

# Actual Behavior

When a file is uploaded and it has dots (.) in its filename (e.g. my.cool.file.pdf), the filename for the preview image results in my.cool.jpg (Media list). Because it's saved correctly (my.cool.file.jpg) on the filesystem, the preview-file is not found when the media list is rendered and the preview is always regenerated.

# Expected Behavior

The filename of the preview urls should be my.cool.file.jpg

# Steps to Reproduce

Upload a pdf with dots in its filename, e.g. my.cool.file.pdf and check the media list where this file should be displayed --> preview is generated on each load.

# Possible Solutions
As far as I could reproduce, pathinfo is called two times in the process, once at the beginning (filename becomes my.cool.file) and once before getMediaUrl is called in the replaceExtension method (filename becomes my.cool)
```
public function getFormats($id, $fileName, $version, $subVersion, $mimeType)
{
        // filename before pathinfo: my.cool.file.pdf
        $fileName = \pathinfo($fileName)['filename'];
        // filename after pathinfo: my.cool.file
        $formats = [];

        $extensions = $this->converter->getSupportedOutputImageFormats($mimeType);

        if (empty($extensions)) {
            return [];
        }

        $originalExtension = $extensions[0];
        foreach ($this->formats as $format) {
            foreach ($extensions as $extension) {
                $formatUrl = $this->formatCache->getMediaUrl(
                    $id,
                    // Because there is another pathinfo call in replaceExtension, filename becomes my.cool and then my.cool.jpg
                    $this->replaceExtension($fileName, $extension),
                    $format['key'],
                    $version,
                    $subVersion
                );

                if ($extension === $originalExtension) {
                    $formats[$format['key']] = $formatUrl;
                }

                $formats[$format['key'] . '.' . $extension] = $formatUrl;
            }
        }

        return $formats;
}
```

**Comment by niklasnatter** [comment]
Thanks a lot for reporting! This should hopefully be fixed in #5768
