### ISSUE TITLE
FormatOptions entity uses INT to store crop values but could receive FLOATS

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5409]
| Q | A
| --- | ---
| sulu version | 2.1.0

# Actual Behavior

Sulu supplies FLOATS to the DB and MySQL will auto cast those to INT.

# Expected Behavior

Just save INTs to the DB

# Steps to Reproduce

Use PGSQL and try to save an copped image. It will crash on ->flush().

# Possible Solutions

Postgrsql doesn't auto cast and throws an error.  So somewhere the data should be casted to INT

**Comment by kfrohwein** [comment]
Maybe this is a browser issue then. But for some reason the backoffice JS now provides floats and not ints. And there is no casting in the code.

**Comment by kfrohwein** [comment]
I reopen this as I want to provide a different patch :)

**Comment by alexander-schranz** [comment]
Fixed in #5418
