### ISSUE TITLE
Collection pagination disabled on media selection

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu#5411]
| Q | A
| --- | ---
| Sulu Version | 2.1.0
| Browser | FF

# Actual Behavior

From a widget media selection, the collection pagination is not enabled. Prev and next button aren't enabled. If you just click on the page number field and outside, the pagination is reloaded and the next button is enabled.

# Expected Behavior

Navigate with the collection pagination

# Steps to Reproduce

Have a page template with a media selection widget.
Have more than 10 collection.
Click on the widget to select media, try to go to the next 10 collections

**Comment by danrot** [comment]
Fixed in #5584
