### ISSUE TITLE
Make entries of disabled media_selection scrollable

### ISSUE THREAD

**Issue by luca-rath** [sulu/sulu#5413]
| Q | A
| --- | ---
| Sulu Version | 2.1
| Browser Version | Browser name and version

# Actual Behavior

The media list has a max height of `225px`. If there are too many medias selected in a disabled `media_selected`, the media list cannot be scrolled.

# Expected Behavior

Scrolling should work in disabled `media_selections`.

# Steps to Reproduce

~~~xml
<property name="medias" type="media_selection" disabledCondition="true">
    <meta>
        <title>app.medias</title>
    </meta>
</property>
~~~

**Comment by danrot** [comment]
Fixed in #5416
