### ISSUE TITLE
Would be nice to see a message when a file is too large for uploading.

### ISSUE THREAD

**Issue by jordygroote** [sulu/sulu#5417]
# Problem description

When a file is larger than upload_max_file_size it gives 400 and does nothing, no message or anything.
Would be nice to see an error message on the top of the CMS so you know what's going on.

# Proposed solution
DIsplay error message

![Schermafbeelding 2020-07-16 om 13 32 22](https://user-images.githubusercontent.com/8653367/87667015-f2f72c80-c769-11ea-9798-da177e0e4710.png)

**Comment by nnatter** [comment]
After #5553 was merged, there should be a general error message when this happens. Would still be nice to show a more specific message in this case 🙂

**Comment by niklasnatter** [comment]
Thanks a lot for reporting! Should be fixed by #5797
