### ISSUE TITLE
Mandatory field not working correctly.

### ISSUE THREAD

**Issue by GillesKnockaert** [sulu/sulu#5426]
| Q | A
| --- | ---
| Sulu Version | Specific version or SHA of a commit
Sulu 2.1

| Browser Version | Browser name and version
Latest version of Chrome

# Actual Behavior

A mandatory field is mandatory when you create the page. But when you go back to the page you can just remove the value of the mandatory field so it is empty and save it.

# Expected Behavior

A mandatory field should always have a value.

# Steps to Reproduce

Create a temlpate with a mandatory field on it let's say a single media select. then when you create a page using that template, you need to add a image or you can't save it. So when you saved the page, go back to the page and remove the image. now you can save the page but the mandatory field is empty???

# Possible Solutions

Make sure that mandatory fields always have a value else you can't save them.

**Comment by alexander-schranz** [comment]
@GillesKnockaert currently mandatory fields only working for simple fields which are saved as empty string. Field Types like selection which use array or objects be saved are currently not possible to be mandatory as current limitation of the json schema which is not type specific. We hope we can in future provide here something to fix this problems.

**Comment by danrot** [comment]
This has been for the mentioned media selection in #5640. Thanks for reporting!
