### ISSUE TITLE
PDF upload: The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by sbutlersloss** [sulu/sulu#5431]
| Q | A
| --- | ---
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

# Actual Behavior

We uploaded a pdf to our site, the link was working fine for a few days and now has stopped working. The message we receive is

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.  "

The link that was being used is: https://econ4future.org/media/4/download/Beyond%20Economics-As-Usual.pdf?v=2&inline=1

# Expected Behavior

-

# Steps to Reproduce

-

# Possible Solutions

-

**Comment by alexander-schranz** [comment]
Please check the logs under `var/log` folder and other logs like your *webserver*  or *php-fpm*  logs to get a correct error message.

**Comment by alexander-schranz** [comment]
Close because of due inactivity, feel free to provide more information or [join our slack](https://sulu.io/services-and-support#chat).
