### ISSUE TITLE
Cropping window not resizing when selecting a different(and changed) image format

### ISSUE THREAD

**Issue by roykoper** [sulu/sulu#5445]
| Q | A
| --- | ---
| Sulu Version | 2.0.7
| Browser Version | Google Chrome

# Actual Behavior

How does Sulu behave at the moment? 

When changing the format for an image which already has a crop defined, the cropping window does not get changed properly. 

# Expected Behavior

What is the behavior you expect?

For the cropping window to change when selecting different image formats.

# Steps to Reproduce

1. Create a crop for an image
2. Change the image format's width/height to a different value
3. Select the image format when cropping
4. Observe that the crop window has not changed according to the new format's width/height

**Comment by roykoper** [comment]
I tested this on version 2.1.1 and it still occurs.

**Comment by alexander-schranz** [comment]
@roykoper can you show a screencast what you are doing. And did you after the update download the latest sulu build using `bin/adminconsole sulu:admin:download-build`?

**Comment by alexander-schranz** [comment]
Okay @nnatter showed me what you meant.

@roykoper Thats currently the case that if you change the format in the `xml` that you need also remove the exist generate images for this format in the `public/uploads/media/<format>` directory and remove exist crop coordinates from the format options table or create a database migration for this crops. This is nothing what sulu will handle for you if you change the xml.

I personally recommend that the image format key should represent the format it its best way example keys should be: `200x`, `x100`, `300x150`, `80x50-inset`. See the sulu-demo [image-formats.xml](https://github.com/sulu/sulu-demo/blob/master/config/image-formats.xml). This avoids problems like you have.

**Comment by nnatter** [comment]
As @alexander-schranz already mentioned - if you change an existing image format, you will need to migrate your application (remove cached crops and migrate/truncate the `me_format_options` table. 

From my perspective, the current behaviour is not wrong. If you change an existing format, Sulu will still display the crop that is used on the website in the crop overlay. The ratio of the crop will be corrected to the new image format as soon as you modify the crop.
