### ISSUE TITLE
Problem saving pages when there is an uppercase letter in the URL field.

### ISSUE THREAD

**Issue by jordygroote** [sulu/sulu#5462]
# Actual Behavior

When there is a capital letter in the URL. We get a red error in the top of the CMS and can't save the page.
With no logic error message or hint on what to do.

# Expected Behavior

It saves the page or displays usefull error.

# Steps to Reproduce

See this video:

https://www.loom.com/share/080c6f426d5c4425b2785e1931ba164b

# Possible Solutions

Automaticly convert uppercase letters to lowercase letters.

Or

Display a usefull error message saying something like:
"There is a uppercase letter in your URl structure please change this to lowercase letter."

**Comment by danrot** [comment]
Fixed in #5591
