### ISSUE TITLE
SVG is not be chopped

### ISSUE THREAD

**Issue by ThiKool** [sulu/sulu#5466]
| Q | A
| --- | ---
| Sulu Version | 2.1.1
| Browser Version | Doesnt matter

# Actual Behavior

I've tried to embed some new .svg Images, but the cannot be cropped:
`Crop coordinates must start at minimum 0, 0 position from top left corner, crop height and width must be positive integers and must not exceed the current image borders`

Example SVG is attached!
[graduates.zip](https://github.com/sulu/sulu/files/5135564/graduates.zip)

I've defined it at image-formates.xml:

```
<format key="careerBannerImage">
    <meta>
        <title lang="en">Career banner image</title>
        <title lang="de">Karrierebanner-Bild</title>
    </meta>
    <scale x="195" y="222"/>
</format>
```

In twig:

```
{% set image = sulu_resolve_media(element.image.id, app.request.locale) %}
<img src="{{ image.formats['careerBannerImage'] }}"
```

**Comment by nnatter** [comment]
Hey,
thanks for reporting! does this issue still occur on `2.2.0`?

**Comment by ThiKool** [comment]
It was a problem with my SVG file. Can be closed
