### ISSUE TITLE
No URL generated for internal links from different webspaces

### ISSUE THREAD

**Issue by jaimybroere** [sulu/sulu#5467]
| Q | A
| --- | ---
| Sulu Version | 1.6.35
| Browser Version | All browsers

# Actual Behavior

When adding internal links in a texteditor, url's for pages on a different webspace are not generated correctly. The `<a>` tag is rendered without an `href` for these pages. Url's for pages on the same webspace _are_ generated correctly.

# Expected Behavior

The links to pages on different webspaces should be rendered with an href.

# Steps to Reproduce

1. Create a field with a texteditor type
2. In the texteditor field, add an internal Sulu link to a page on a different webspace
3. The link is rendered without an `href` 

# Possible Solutions

As discussed in Slack, this seems to be a bug in the `findUrlByResourceLocator` method called here
https://github.com/sulu/sulu/blob/f8a39a228ca763607ba7e9743f3af7b3397be51f/src/Sulu/Bundle/ContentBundle/Markup/Link/PageLinkProvider.php#L111

When `$domain` is set to `null` the url is generated correctly.

**Comment by alexander-schranz** [comment]
There is currently 2 possible solutions:

Adding the following logic to the:

**Solution A**

Copy the logic from the [ContentPathTwigExtension](https://github.com/sulu/sulu/blob/6793028c2aa0340c85cfe03560c54b73f4a2274f/src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php#L71-L75). Into the PageLinkProvider e.g.:

```php
    protected function getLinkItem(Content $content, $locale, $scheme, $domain = null)
    {
        $published = !empty($content->getPropertyWithDefault('published'));
        if ($domain && !$this->webspaceManager->findWebspaceByKey($webspaceKey)->hasDomain($domain, $this->environment, $locale)) {
            $domain = null;
        }

        $url = $this->webspaceManager->findUrlByResourceLocator(
            $content->getUrl(),
            $this->environment,
            $locale,
            $content->getWebspaceKey(),
            $domain,
            $scheme
        );

        return new LinkItem($content->getId(), $content->getPropertyWithDefault('title'), $url, $published);
    }
```


**Solution B**

We move this handling into the WebspaceManager so nobody need to handle it itselfs. 

I think this can be done by changing the following part:

https://github.com/sulu/sulu/blob/6793028c2aa0340c85cfe03560c54b73f4a2274f/src/Sulu/Component/Webspace/Manager/WebspaceManager.php#L249-L255

To:

```php
            if ($sameLocalization && $sameWebspace) {
                if ($portalInformation->isMain()) {
                    \array_unshift($urls, $url);
                } elseif ($this->isFromDomain($url, $domain)) {
                    \array_unshift($urls, $url);
                } else {
                    $urls[] = $url;
                }
            }
```

/cc @sulu/core-team what do you think?

**Comment by alexander-schranz** [comment]
This bug seems to be introduced in `1.6.34` in #5328 /cc @wachterjohannes

**Comment by wachterjohannes** [comment]
as we fixed the latest bug in the webspace manager - i would also fix it there

**Comment by danrot** [comment]
I would also go for the `WebspaceManager`, it should not required to do this in multiple places.

**Comment by nnatter** [comment]
Should hopefully be fixed by. #5471. Thanks for reporting!
