### ISSUE TITLE
cache:clear not sufficient to see new templates

### ISSUE THREAD

**Issue by jacekwilczynski** [sulu/sulu#5481]
| Q | A
| --- | ---
| Sulu Version | 2.1.2
| Browser Version | back-end issue but Chrome Version 84.0.4147.135 (Official Build) (64-bit)

# Actual Behavior

A newly added page template is not visible in the admin after running `bin/adminconsole cache:clear`. Cache must be cleared the hard way (`rm -rf var/cache/*`).

# Expected Behavior

A newly added page template is visible in the admin after running `bin/adminconsole cache:clear`.

# Steps to Reproduce

1. Set up a new project using the Sulu Skeleton:
1.1. run `composer create-project sulu/skeleton example && cd example`
1.2. connect a database
1.3. run `bin/adminconsole sulu:build dev -n`
2. Go to the `/admin` URL and log in as "admin" with password "admin".
3. Create a new page template:
3.1. Copy `/config/templates/pages/default.xml` as `another.xml` and modify:
&nbsp;&nbsp;&nbsp;&nbsp;3.1.1. `<key>another</key>`
&nbsp;&nbsp;&nbsp;&nbsp;3.1.2. `<view>pages/another</view>`
&nbsp;&nbsp;&nbsp;&nbsp;3.1.3. `<meta><title>Another</title></meta>`
3.2. Copy `/templates/pages/default.html.twig` as `another.html.twig`.
4. Run `bin/adminconsole cache:clear`.
5. In the admin panel, go to Webspaces and create a new page.
6. Try to choose "Another" as the new page's template (not possible).

**Comment by alexander-schranz** [comment]
This seems related to the following issue #5309 think webspaces and template structures are cached the same way.

**Comment by jacekwilczynski** [comment]
Ooops, then sorry, feel free to close my ticket.

**Comment by alexander-schranz** [comment]
@jacekwilczynski  issue is still okay. I just linked it so if somebody have a look at the other issue with webspaces they could also have a look at this one with templates.

**Comment by danrot** [comment]
Fixed in #5510
