### ISSUE TITLE
Support request: How to access video path in twig

### ISSUE THREAD

**Issue by almare** [sulu/sulu#5491]
I have a problem getting the video path url in twig. Currently I am not able to load the video. I started debugging and I see the Media Entity in the {{ dump(block.background_media) }} part

`
Sulu\Bundle\MediaBundle\Api\Media {#7826 ▼
  #url: "/media/226/download/test-video.mp4?v=1"
  #formats: []
  #locale: "de"
  #version: null
  #additionalVersionData: array:1 [▶]
  #fileVersion: Sulu\Bundle\MediaBundle\Entity\FileVersion {#11420 ▶}
  #localizedMeta: null
  #file: Sulu\Bundle\MediaBundle\Entity\File {#11417 ▶}
  #entity: Sulu\Bundle\MediaBundle\Entity\Media {#11322 ▶}
}
`

But i am not able to access one of the properties. I tried to get the path by the function sulu_get_media_url(block.background_media) but this thows the following error.

`Argument 1 passed to Sulu\Bundle\MediaBundle\Twig\DispositionTypeTwigExtension::getMediaUrl() must be an instance of Sulu\Bundle\MediaBundle\Api\Media, null given, called in /home/almare/Webserver/omnoto.com/omnoto/var/cache/website/dev/twig/7a/7a32900915550bd17624d603035fc37e0d6a5e9c407bfba852cebdbdc1b3b89d.php on line 83`

As I can see is in the twig dump command the object of type  Sulu\Bundle\MediaBundle\Api\Media.
I tried to google some documentations regarding the embedding of videos, but here is a lack of documentation. All I found is about enabling ffmpeg and ffprobe.

I also tried different things but all without success. Most of them stopped with the error like this.

`Impossible to access an attribute ("url") on a null variable.`

How is it intended to get the video path? Any suggestions are welcome. Thank you

**Comment by almare** [comment]
Thank you for your fast response.

This is my configuration:.
```                                
<property name="background_media" type="single_media_selection" colspan="3">
    <meta>
        <title lang="en">Background media</title>
        <title lang="de">Hintergrund Medien</title>
    </meta>
    <params>
        <param name="types" value="image,video"/>
    </params>
</property>
```

I found my problem.. I renamed the property from backgroundimage to background_media. This was probably to much changes at once. Anyway, it worked as intended... once again. Is it possible to rename the property type or is it generally a dumb idea?

**Comment by alexander-schranz** [comment]
@almare if you don't want to lose any data you would need to create a phpcr migration from the old to the new name.

I'm closing this issue as it seems to be fixed.
