### ISSUE TITLE
Sulu Security Feature: Error 403 on every page when logged in

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#5496]
| Q | A
| --- | ---
| Sulu Version | 96096d163f29679215845f3877fa67da33f377ef

# Actual Behavior

When browsing the website as "anonymous" user you can reach every site, but when logged in you'll get an error 403 even if the website security is not even enabled on this page.

# Expected Behavior

1. Every logged in user at least has the same rights as an "anonymous" user.
2. If website security is not enabled it should not block views from logged in users.

# Steps to Reproduce

install sulu and create a user, which can log in.
Login and try to visit some created pages.

**Comment by Quehnie** [comment]
oh and i forgot to mention, if you save the "permissions" tab it does not save any changes.

**Comment by alexander-schranz** [comment]
@Quehnie currently you need to give the user role access to the webspace which they are allowed to access in your webspace configured system also access to the media to see and download them is needed. If using the `SuluCommunityBundle` this is normally done when by the `sulu:community:init` command when creating the role for that systems.

**Comment by Quehnie** [comment]
@alexander-schranz okay so if i add a new webspace after that i have to do in on my own. but the "permissions" tab still does not save it if i disable website permissions.

**Comment by alexander-schranz** [comment]
> okay so if i add a new webspace after that i have to do in on my own

If the new webspace has an own security system and not have the same system as the webspace itself yes you need to edit the roles if you want they have access to it, but mostly you then have additional role else you would use the same system.

**Comment by Quehnie** [comment]
@alexander-schranz in my projects both webspaces use the Website system but in the security_website.yaml you have to add multiple webspace keys?

**Comment by alexander-schranz** [comment]
Think #5504 and #5503 should fix your issues.

**Comment by Quehnie** [comment]
Thanks everything works fine now :)

**Comment by alexander-schranz** [comment]
@Quehnie Thx for the feedback!
