### ISSUE TITLE
sulu:security:init does not add anonymous access for new webspaces

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#5499]
| Q | A
| --- | ---
| Sulu Version | 74d39b37aa536d76dbc8adb7fd5a44653fd95998

# Actual Behavior

When you already updated sulu and initialized the security. When adding new webspaces anonymous users wont be able to access those pages because the wont have the role permissions. when executing sulu:security:init again it wont add those permissions.

# Expected Behavior

Add anonymous permissions for new webspaces or add toggler to the role overview to show the anonymous role and edit their permission.

# Steps to Reproduce

init security add new webspace and init security again there wont be any access.

# Temporary Solution
Add the same permissions for the new webspace like the old one in se_permissions for the anonymous role.

**Comment by alexander-schranz** [comment]
@Quehnie provided a fix for this in #5504.
