### ISSUE TITLE
Inconsistency with data_path_to_auto_complete and request_parameters in SingleSelection field type

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#5507]
| Q | A
| --- | ---
| Sulu Version | since 9f0233fc3fd1917697370645e55e2887ba2d57dc
| Browser Version | ---

# Actual Behavior

The `SingleSelection` field type has two params. One is called `data_path_to_auto_complete`, which allows to read data using a json pointer from the form and append that information in the query string, and the other is `request_parameters` enabling to statically define some parameters to be appended in the query string in the XML template.

Both of these params are collections, but the problem is that the meaning of the `name` and the `value` of the child parameters is switched. So if you want to have a query string like `?test1=value1&test2=title_of_page` you would have to define it in this way:

```xml
        <property name="single_account_selection" type="single_account_selection">
            <params>
                <param name="data_path_to_auto_complete" type="collection">
                    <param name="title" value="test2" />
                </param>
                <param name="request_parameters" type="collection">
                    <param name="test1" value="value1" />
                </param>
            </params>
        </property>
```

This is very confusing, because in the `request_parameters` case the `name` is used for the name of the query parameter, whereby in the `data_path_to_auto_complete` case the `value` is used as the query parameter name.

The reason for implementing it this way in the `data_path_to_auto_complete` case is that the `name` of the param is currently a mandatory field, but the value is not. Therefore the `name` was chosen to be the default for the path in that case to allow a shortcut like this:

```xml
                <param name="data_path_to_auto_complete" type="collection">
                    <param name="title" />
                </param>
```

Then the `title` query parameter is filled with the value of the current title field. However, it could also be handled the other way round, this is just what makes this a little bit more complicated.

This problem was introduced in #5506, but it was not possible to solve in a different way. The only other solution would have been to switch the meaning of the `value` and `name` parameters for the `request_parameters` just in this case, which would also make it inconsistent with all the other occurences of `request_parameters`.

# Expected Behavior

The only important thing is that the name of the query parameter is determined in a consistent way. I would personally prefer to use the `name` as the name of the parameter and the `value` as the value passed to that query parameter (I think that makes a lot more sense than the other way round).

```xml
        <property name="single_account_selection" type="single_account_selection">
            <params>
                <param name="data_path_to_auto_complete" type="collection">
                    <param name="test2" value="title" />
                </param>
                <param name="request_parameters" type="collection">
                    <param name="test1" value="value1" />
                </param>
            </params>
        </property>
```

Mind that we also talked about making the `name` attribute of the `param` tag an optional field, that would also solve some confusions in other parts of the system, where only one of both is needed, and that now has to be the `name`.

# Steps to Reproduce

Use the first XML file posted above, and see that it works. But the XML configuration itself is confusing.

# Possible Solutions

Switch the meaning of `name` and `value` in the [`SingleSelection` field type](https://github.com/sulu/sulu/blob/9f0233fc3fd1917697370645e55e2887ba2d57dc/src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js#L399-L409), but remember that this is a breaking change.

**Comment by nnatter** [comment]
I think the `SingleSelection` field type already supports a `resource_store_properties_to_request` param that uses the desired configuration. Maybe we can just deprecate the `data_path_to_auto_complete` param?

**Comment by danrot** [comment]
Yeah, if I am not completely mistaken (just had a look at the code, didn't test it), the `resource_store_properties_to_request` param also uses the `name` and `value` of the param correctly... So maybe just deprecating it would really be the solution to this.

**Comment by danrot** [comment]
Going to close this, just don't forget to remove all the deprecation created in #5586 before releasing 3.0 :slightly_smiling_face:
