### ISSUE TITLE
Additional webspaces falling back to first webspace hostname in page localizations

### ISSUE THREAD

**Issue by thenetexperts** [sulu/sulu#5515]
| Q | A
| --- | ---
| Sulu Version | 2.2@dev
| Browser Version | -

# Actual Behavior

The hostname of the `localizations` of a page are wrong for every webspace except the first one.

# Expected Behavior

This hostname of the `localizations` of a page just be the ones defined in the webspace config.

# Steps to Reproduce

Use latest master branch, create two webspaces using different portal url's. Create a page in the second webspace, check the output of the localizations array.

# Possible Solutions

@alexander-schranz mentioned:
There no webspaceKey is given and it seems like webspaceManager doesn’t handle that correct instead it just use the first portal here: https://github.com/sulu/sulu/blob/795feac9867b7df89a391a532a7554ba15447e34/src/Sulu/Component/Webspace/Manager/WebspaceManager.php#L219

This check is false. If webspaceKey is null it should use the current webspace not the first one.

And in https://github.com/sulu/sulu/blob/795feac9867b7df89a391a532a7554ba15447e34/src/Sulu/Bundle/WebsiteBundle/Resolver/ParameterResolver.php#L109 the call `webspaceManager->findUrlByResourceLocator` is using the above mentioned function.

**Comment by nnatter** [comment]
Thanks for reporting! Should be fixed by #5521
