### ISSUE TITLE
Error handling frontend of media library

### ISSUE THREAD

**Issue by jordygroote** [sulu/sulu#5540]
# Problem description

I’ve extended the `MediaManager.php `. When i throw a:
```
throw new MediaException('Blocked file type', MediaException::EXCEPTION_CODE_BLOCKED_FILE_TYPE);
```
In the `save()` function, no error is triggered in the CMS.

It just glitches and the user has no clue what happened.

# Proposed solution

Ability to display a red error bar in the media library after throwing an error from a controller.
Underneath answer by @nnatter 

> it looks like there is no error handling at all implemented in the frontend at the moment. at least, we need to adjust the MediaUploadStore, the MultiMediaDropzone, the MediaCollection and the MediaOverview

**Comment by danrot** [comment]
Fixed in #5554
