### ISSUE TITLE
Webspace export and import with block in block

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#5541]
| Q | A
| --- | ---
| Sulu Version | d945d9c1967bba13fac217d7ebf2ca19fefd605d

# Actual Behavior

When exporting a webspace even block in block elements are in the xliff file. When importing those blocks are missing.

# Expected Behavior

Also import block in block elements.

# Steps to Reproduce

Site XML with block in block, export an reimport webspace into another language.

**Comment by niklasnatter** [comment]
Should hopefully be fixed by #5659. Thanks for reporting!
