### ISSUE TITLE
Translated pages do not use translated parent pages in path prefix

### ISSUE THREAD

**Issue by thenetexperts** [sulu/sulu#5548]
| Q | A
| --- | ---
| Sulu Version | 2.1.2
| Browser Version | Firefox

# Actual Behavior

The Resourcelocator of the newly created child page is using either the path prefix of the (copied from) page or removes the path prefix completely.

# Expected Behavior

The Resourcelocator should reflect the path prefix from the parent in the same language

# Steps to Reproduce

1. Create a new page in the default language (DE) named "Deutsche Seite", save.
2. Switch to english language (EN) and allow copy of the (DE) locale
3. Rename this english page to "English Page", save.
4. Switch back to default language (DE)
5. Create a new child page below "Deutsche Seite" and name it "Deutsche Unterseite" (The Resourcelocator will be correct)
6. Switch to english language (EN) and allow copy of the (DE) locale
7. Rename the english page to "English Subpage".

You will now see the ResourceLocator will keep the name "deutsche-seite". If you click in the Article Textfield the prefix might even vanish, leaving the english child page with no path prefix (of the parent).

**Comment by nnatter** [comment]
This should hopefully be fixed by #5558 and #5573 🙂
