### ISSUE TITLE
Second log out throws JS error

### ISSUE THREAD

**Issue by ThiKool** [sulu/sulu#5565]
| Q | A
| --- | ---
| Sulu Version 2.1.1

# Actual Behavior

Log out page loads infinitly after second log out. JS error thrown:
`Uncaught (in promise) Error: The key "route" has already been used for another field`

# Steps to Reproduce

Log in into admin panel
Log out
Log in again
Log out

**Comment by nnatter** [comment]
Thanks for reporting! Should be fixed by #5562

**Comment by ThiKool** [comment]
I'm now on Sulu 2.2.1 with the same issue!

**Comment by nnatter** [comment]
@ThiKool Have you updated the JavaScript build while upgrading your application as described in the [upgrading guide](https://docs.sulu.io/en/2.2/upgrades/upgrade-2.x.html)?

**Comment by ThiKool** [comment]
Sorry I forgot to upgrade the JS build. Now everything is fine!
