### ISSUE TITLE
While updating an entity the resource_store_properties_to_request param is not working in SingleSelection

### ISSUE THREAD

**Issue by sanhofman** [sulu/sulu#5577]
| Q | A
| --- | ---
| Sulu Version | 2.1.3

# Actual Behavior

The `resource_store_properties_to_request` param in combination with Single Selection and Selection is working properly on entity creation. And on entity update while altering the parent field, the dependant field values are properly updated (filtered) while using selection. But this is not yet the case for single_selection. After altering the parent field, the dependant field values are not updated on latest release.

But this is the case on dev-master?

# Expected Behavior

While altering the parent field, the dependant field values should always be updated.

# Steps to Reproduce

**Used code**

```
<section name="companySection">
    <properties>
      <property name="companyId" type="single_select" mandatory="true" colspan="6">
     <meta>
           <title>app.company</title>
     </meta>
     <params>
            <param name="values" type="expression" value="service('app.admin_manager').getCompanies()"/>
    </params>
    </property>
    <property name="contact" type="single_contact_selection" visibleCondition="companyId != null" mandatory="true" colspan="6">
    <meta>
          <title>app.account</title>
    </meta>
     <params>
         <param name="resource_store_properties_to_request" type="collection">
             <param name="companyId" value="companyId" />
         </param>
     </params>
   </property>
  </properties>
</section>
```

**On creation: values properly filtered according to parent**

<img width="1680" alt="Screenshot 2020-10-29 at 11 11 09" src="https://user-images.githubusercontent.com/17701731/97554797-93025a00-19d7-11eb-8db4-69444a5b3468.png">

**On update: values not filtered after changing parent**

<img width="1679" alt="Screenshot 2020-10-29 at 11 10 39" src="https://user-images.githubusercontent.com/17701731/97554837-a4e3fd00-19d7-11eb-9bc7-2eecd8906cf7.png">

**Comment by nnatter** [comment]
the `resource_store_properties_to_request` param is not supported on `2.1.3`. The parameter was added with `2.2.0 -RC1`: https://github.com/sulu/sulu/releases/tag/2.2.0-RC1

Can you test if it is working on `2.2.0 -RC1`?

**Comment by sanhofman** [comment]
Yes, you're right.

Working on `2.2.0-RC1`. I expected it to be in `2.1.3` already, my bad and  thanks for fast reply!

**Comment by nnatter** [comment]
Alright, thats good.
Dont worry - its quite hard to get an overview of the supported params because we havent found a good place to document these things yet 😕
