### ISSUE TITLE
Add resolveConflict parameter to createOrUpdateByAttributes method of RouteManager

### ISSUE THREAD

**Issue by mgwestwerk** [sulu/sulu#5579]
# Problem description

When using the createOrUpdateByAttributes function of the RouteManager there is no option to check for conficting routes. If a conflict exists it cannot be resolved afterwards as the function already persists the route.

This problem can for example occur when using the ContentBundle (https://github.com/sulu/SuluContentBundle/blob/4d62683790248bda95fa243ad34b59078c79a2a2/Content/Application/ContentDataMapper/DataMapper/RoutableDataMapper.php#L168)

# Proposed solution

Add a parameter analogous to the create and update functions.

**Comment by nnatter** [comment]
Thanks for reporting! Sounds like a useful thing to do 🙂 
Would you like to create a PR for this?

**Comment by mgwestwerk** [comment]
I can do that. I am conflicted with regard to one question:
Do I set the default value of the parameter to...

- `false` to make sure every existing call has the exact same behavior like before or
- `true` to make it consistend with the create and update method?

**Comment by nnatter** [comment]
While it would be nice to be consistent with the other methods, it is a BC break to set the parameter to `true` per default 😕 
So I think we need to go with `false` here. Also, we need to add a hint about the changed signature to the `UPGRADE.md`.

**Comment by mgwestwerk** [comment]
Just one more thought regarding the default behavior question:
In case of a conflict the method as it is returns an already persisted route object with duplicate path which inevitably results in an exception during the next flush. Therefore I think an argument can be made that the previous result in case of a conflict is invalid and does not have to be maintained. Alternatively it could be the same as for the other methods which is in case of a conflict either resolve it or throw an exception.

**Comment by nnatter** [comment]
Thats right.. I think it would be okay for me to use `true` as default value. But we need to describe that the parameter needs to be set to `false` to retain the old behaviour in the `UPGRADE.md`. 🙂
