### ISSUE TITLE
Check of Email uniquness in UserManager::processEmail should be case insensitiv

### ISSUE THREAD

**Issue by rs2487** [sulu/sulu#5596]
| Q | A
| --- | ---
| Sulu Version | 2.1.1

# Actual Behavior

Sulu throws an exception when updating a user which email address only changed by different upper or lower case of character. 

# Expected Behavior

The comparison should be case insensitive. 

# Possible Solutions

Use strcasecmp here: https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php#L684

**Comment by nnatter** [comment]
Hey, thanks for reporting. This sounds like a useful thing to do 🙂 Would you like to create a pull request?

**Comment by luca-rath** [comment]
Fixed by #6170, will be released as 2.2.12 and 2.3.2
