### ISSUE TITLE
Add subscript / superscript in CKEditor

### ISSUE THREAD

**Issue by C-burr** [sulu/sulu#5602]
# Problem description

I want to be able to type subscript and superscript in the text editor, without having to copy the desired character from somewhere else.

# Proposed solution

As far as i know, CkEditor already supports subscript and supscript, it just has to be enabled for sulu text editors.

**Comment by alexander-schranz** [comment]
I think it just need to be added to the toolbar and maybe 2 icons are needed.

https://github.com/sulu/sulu/blob/87fdd3500d5999548acc07ca4b4df9842a9956f4/src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/CKEditor5.js#L87

The toolbar names are here.

https://ckeditor.com/docs/ckeditor5/latest/features/basic-styles.html#available-text-styles

**Comment by nnatter** [comment]
Thanks for reporting! Should be fixed in #5609 🙂
