### ISSUE TITLE
Refresh url button adds `-1` suffix to url if parts haven't changed

### ISSUE THREAD

**Issue by luca-rath** [sulu/sulu#5603]
| Q | A
| --- | ---
| Sulu Version | 2.2.1
| Browser Version | Brave latest

# Actual Behavior

![Bildschirmvideo-aufnehmen-2020-10-30-um-12 07 18](https://user-images.githubusercontent.com/5758674/98235638-619f0680-1f62-11eb-83db-4a6d4c9f51d3.gif)

# Expected Behavior

If the refreshed url would be the same as the current url, a `-1` suffix should not be added to the url

# Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

# Possible Solutions

Always send `id` (if available) as property of `parts` to the `ResourceLocatorController::postAction`, then the `ResourceLocatorStrategy` can check, if the found url belongs to the current page

**Comment by nnatter** [comment]
When fixing this, we should also have a look at https://github.com/sulu/sulu/issues/5363

**Comment by nnatter** [comment]
When fixing this, we should alos have a look at https://github.com/sulu/sulu/issues/5363

**Comment by luca-rath** [comment]
fixed with #5604
