### ISSUE TITLE
Filter breaks admin screen

### ISSUE THREAD

**Issue by timkoopmans50** [sulu/sulu#5611]
| Q | A
| --- | ---
| Sulu Version 2.X |
any browser

# Actual Behavior
1- go to https://sulu.rocks/admin/#/accounts/1/documents
2-add a filter on "type" , "audio" for example. 
3-click on the "people" tab
4-you will end up on a white screen due to a promise error, as it will attempt to apply an impossible filter on a screen. Additional problem: because the filter is saved for the user in the se_user_settings table, as a result the screen will break again and again. If you happen to have a custom admin screen with 2 tabs and the second tab breaks your primary, you will never be able to restore the problem without DB access. 

# Expected Behavior
filter should be supplied on sub-tab not on primary tab

**Comment by nnatter** [comment]
Thanks for reporting! Closing this as a duplicate of #5612
