### ISSUE TITLE
Sulu admin UI is not working correctly when changing page then navigating to other page

### ISSUE THREAD

**Issue by jordygroote** [sulu/sulu#5621]
| Q | A
| --- | ---
| Sulu Version | 2.2.1
| Browser Version | Chrome

# Actual Behavior

UI sort of crashes when navigating to other view without saving the page

# Expected Behavior

Render the other view

# Steps to Reproduce

See .gif included

![sulu-admin-ui-crash](https://user-images.githubusercontent.com/8653367/98836881-87387e00-2442-11eb-9a2e-d6d1986805b5.gif)

**Comment by nnatter** [comment]
Should be fixed in #5626. Thanks for reporting @jordygroote!
