### ISSUE TITLE
page_selection does not show yellow "test-mode" marker

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#5632]
| Q | A
| --- | ---
| Sulu Version | 2.2.1

# Actual Behavior

The page_selection only shows in the overlay which pages are unpublished,
but this yellow indicator is missing in the selected pages list.

# Expected Behavior

Also add yellow indicators to the selected pages list.

# Steps to Reproduce

Save page, unpublish the page and select it in a page_selection.

**Comment by danrot** [comment]
fixed in #5634
