### ISSUE TITLE
teaser_selection does not work with secured pages

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#5633]
| Q | A
| --- | ---
| Sulu Version | 2.2.1

# Actual Behavior

When selecting a secured pages in the teaser_selection does not show title, description or anything at all.

# Expected Behavior

The selection is shown in the sulu and checked in the website controller if available for this user.

# Steps to Reproduce

Website security on pages, teaser_selection and select those.

**Comment by alexander-schranz** [comment]
This is duplicated to #4066 so I will close this one. Please add your additional informs there.
