### ISSUE TITLE
Form fields being deleted after you save the form twice

### ISSUE THREAD

**Issue by jordygroote** [sulu/sulu#5641]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Form Bundle Version | ^2.0
| Sulu Version | 2.2.1
| Browser Version | Chrome

I setup a new sulu skeleton. And successfully reproduced.

#### Actual Behavior

After you add a field, save the form once. Then without refreshing save it again the field get deleted.

#### Expected Behavior

Save the form

#### Steps to Reproduce

.gif included

![video_form (1)](https://user-images.githubusercontent.com/8653367/98791308-29397580-2405-11eb-950f-281e7ff2076a.gif)

**Comment by nnatter** [comment]
Thanks for reporting! Should hopefully be fixed in #5642.
