### ISSUE TITLE
Allow to set anchor hash when using <sulu-link /> tag

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#5661]
# Problem description

The `<sulu-link />` tag allows to create a link to another page by its uuid inside of a twig template. Unfortunately, it is not possible to set the `hash` of such a link.

# Proposed solution

When using the default anchor tag, the hash of a link is just appended to the value of the `href` attribute. For example: 
```html
<a href="https://docs.sulu.io/en/2.0/book/getting-started.html#webspaces">Webspaces</a>
```

Therefore, it would be nice to support something like 
```html
<sulu-link href="123-123-123#hash-value">Link Text</sulu-link>
```

**Comment by niklasnatter** [comment]
Fixed in https://github.com/sulu/sulu/pull/6090
