### ISSUE TITLE
Allow to set anchor hash for internal link in text editor

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#5662]
# Problem description

When creating a link to another page in the text editor, it is not possible to set the `hash` of the link.

![Screenshot 2020-11-26 at 18 00 37](https://user-images.githubusercontent.com/13310795/100377311-52ffb880-3011-11eb-9ffa-ed64bc79bbb0.png)

# Proposed solution

I think it would be nice to add an additional input for setting the `hash` of the link in the overlay visible in the screenshot above.

# Related Issues
- https://github.com/sulu/sulu/issues/5661
- https://github.com/sulu/sulu/issues/3440

**Comment by alexander-schranz** [comment]
Think this is create I would go for the syntax like the following in the `<sulu-link href="754c610c-0b50-4d94-90bc-a598bf8e61c8#myanchor" ...>` so its similar to how normal link is.

**Comment by niklasnatter** [comment]
Fixed in https://github.com/sulu/sulu/pull/6090
