### ISSUE TITLE
Sulu 2.2.2 Assets/Media Admin crashes

### ISSUE THREAD

**Issue by ymc-thzi** [sulu/sulu#5674]
Since updating to Sulu 2.2.2 the Assets/Media Section in the admin crashes after it loads. It is just a blank screen with some js errors caused by some mbox.js usage. All other sections are OK.
(Happens in all browsers)

![Bildschirmfoto 2020-12-01 um 11 30 41](https://user-images.githubusercontent.com/1804472/100733198-1f84ab80-33ce-11eb-8170-0dc425988f81.png)

**Comment by nnatter** [comment]
Is it possible that you have not updated the build of the administration interface when upgrading you application?
You can do that by using the `bin/console sulu:admin:update-build` command:
https://docs.sulu.io/en/2.2/upgrades/upgrade-2.x.html

**Comment by ymc-thzi** [comment]
YES, that's it 😃 
Thanks a lot for the awesome response time and the fix
