### ISSUE TITLE
Allow to configure route generation for custom entities consistent to pages

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#5676]
### Basics

There are two basic strategies when it comes to route generation at the moment.

#### Strategy 1: Live generation in Form based on `sulu.rlp.part` tag (used for pages)

In this strategy, properties that have a `sulu.rlp.part` tag are sent to the server via AJAX request when the form is edited. The value of the route is updated directly in the form, even without saving. On save, the already generated route-path is included in the data that sent to the API. This strategy is used for pages. 

#### Strategy 2: Generation based on entity (used for articles)

In this strategy, the route field in the form is updated only after save. When saving the form, the respective entity is persisted and the route bundle is used for generating the route-path for the persisted entity. The route bundle will generate the route-path by evaluating the configured route schema with the persisted entity. In contrast to strategy 1, this strategy allows to include the id of the entity in the route. Unfortunately, this strategy has considerable worse UX (see for example https://github.com/sulu/SuluArticleBundle/issues/514).

### Current Solution

When implementing a custom entity, I would like to use live generation for the route of the entity because it has better UX. 

This is already possible by the following steps:

1. Add a `sulu.rlp.part` tag to a property in the form of the entity. Now, if this property is changed, the ResourceLocator field-type will send an AJAX to the `RouteController::postAction`. The `RouteController` will generate the route-path by evaluating the configured route schema with the parts that were sent to the controller.

2. Because the `RouteController` will evaluate the configured route schema with the parts sent to the controller, we can now use a route schema like this:

```yml
sulu_route:
    mappings:
        App\Entity\Event:
            generator: schema
            options:
                route_schema: '/events/{object["title"]}-{object["subtitle"]}'
            resource_key: events
```

#### ~~Problem 1: Need explicitly include all parts in the configured route schema~~ 

~~When generating the route-path for a page. The parts that are tagged with `sulu.rlp.part` are sorted by their priority and concatenated using `-` between parts. I cannot easily mimic this behaviour for a custom entity without explicitly including all parts in the route schema.~~

Solved by #5675

#### Problem 2: Error when route schema is evaluated with entity 

Depending on how the custom entity is implemented, there might be parts of the system that will try to evaluate the route schema using the entity (not with the `parts` array like the `RouteController`). For example, this can happen when using the `bin/console sulu:route:update` command. 
In these cases, the generation will fail because the route schema (`'/events/{object["title"]}'`) expects that `object` is an array.

**Comment by niklasnatter** [comment]
Fixed by #5675
