### ISSUE TITLE
Browser crashes on input of faulty, complex URL in URL Field within backend

### ISSUE THREAD

**Issue by saphrus** [sulu/sulu#5681]
| Q | A
| --- | ---
| Sulu Version | 2.1.5
| Browser Version | Chrome 87.0.4280.88 / Firefox 83.0

# Actual Behavior

When you enter a complex, faulty URL (e.g. `https://secret-secret-secret-secret-secret.secret-secret.com/de/publicservicedetail?q=elterngeld beantragen&id=8969217&organisationid=208445263` (the space character between "elterngeld" and "beantragen" being the fault)) in an URL input field within the backend, your browser crashes.

# Expected Behavior

no browser crashes

# Steps to Reproduce

- Log into the backend
- Have an URL input field
- Enter a faulty, complex URL (e.g. `https://secret-secret-secret-secret-secret.secret-secret.com/de/publicservicedetail?q=elterngeld beantragen&id=8969217&organisationid=208445263`)

# Possible Solutions

You can quick check the the behaviour here https://regexr.com/5hisv
Since this seems to be no sulu-specific bug, but a browser issue, I see only 2 options:
- optimize/simplify the Regex to work around the faulty JavaScript RegEx implementation
- Fix the JavaScript RegEx implementation

**Comment by alexander-schranz** [comment]
I personally would remove the regex as today there with kind of things like applinks e.g. `myapp://` or other things I don't really see why we should add any validation. Also I think the regex does not support IPv6 which would also be more complicated as see for example the [Symfony Url Validator](https://github.com/symfony/symfony/blob/31ee43a8c67897a2f61782060965f5c8a81f58a2/src/Symfony/Component/Validator/Constraints/UrlValidator.php#L24-L40). 

The browser `<input type="url">` itself a valid url is all which has a [urlscheme://restofurl](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url) the schema does only support there only `a-z` and `-`, the url can have any character with our select for schema I really don't see any need to validate the url as in our case the urlscheme is dropdown and can not be input false and the rest should support any characters.

**Comment by luca-rath** [comment]
Since we've added the possibility to define json-schema per field type recently, we could use that for validation. The `uri` format is even included in the spec (https://json-schema.org/understanding-json-schema/reference/string.html#resource-identifiers)

**Comment by luca-rath** [comment]
But this functionality has been introduced in the current `master` and the bug already existed in `2.1`, so validation would be completely missing in `2.1` and `2.2` versions, if we just remove the regex validation

**Comment by alexander-schranz** [comment]
@luca-rath I think with the select for the schemas we definitly have enough validation without adding some regex or json validation. I think currently the regex validation does harm more then its useful don't see any need as doing more as a normal browser currently validates for the url input type, also urls are mostly copied and not inputted manually.

As an example [🏹.to](https://🏹.to) is a invalid RFC Uri but browsers convert it to correct RFC url. So I really see from content management view here no need to add more validation. Datamanagement is a different where I maybe want to have RFC uris or things like that, but from content management it will harm us more when a content manager copies a url which will then not be valid as when he itself input a false url.

**Comment by luca-rath** [comment]
![image](https://user-images.githubusercontent.com/5758674/107635761-f903ac00-6c6b-11eb-9a71-fb421f62b59e.png)
![image](https://user-images.githubusercontent.com/5758674/107635789-0751c800-6c6c-11eb-96ed-afc5cadd8b31.png)
![image](https://user-images.githubusercontent.com/5758674/107636223-9a8afd80-6c6c-11eb-9a62-250179081813.png)

This is the behaviour, if we add json-schema's `uri` format to url properties. Pasting `https://secret-secret-secret-secret-secret.secret-secret.com/de/publicservicedetail?q=elterngeld beantragen&id=8969217&organisationid=208445263 ` does not crash the admin, it just fails with the same error message as in the image.

The alternative is not validating the input at all, as @alexander-schranz suggested.

/cc @sulu/core-team what do you think?

**Comment by luca-rath** [comment]
https://json-schema.org/understanding-json-schema/reference/string.html#resource-identifiers The `uri` format is documented here

**Comment by niklasnatter** [comment]
Thanks for testing! I would trust the [JSON schema `uri` (or `iri`) format](https://json-schema.org/understanding-json-schema/reference/string.html#resource-identifiers). These formats implement an RFC and its one thing less to think about for us 🙂

**Comment by luca-rath** [comment]
unfortunately `iri` is not supported by our ajv version (6.x) out of the box, see https://github.com/ajv-validator/ajv/blob/master/docs/validation.md#formats ... But there is a separate plugin https://github.com/luzlab/ajv-formats-draft2019 which adds support for it. Though I'm not sure about adding that

**Comment by luca-rath** [comment]
But I should mention that this community plugin is mentioned in the `README.md` of https://github.com/ajv-validator/ajv-formats#formats

**Comment by luca-rath** [comment]
![image](https://user-images.githubusercontent.com/5758674/107639642-6d8d1980-6c71-11eb-852d-098229c50e2f.png)
![image](https://user-images.githubusercontent.com/5758674/107639786-a88f4d00-6c71-11eb-91af-879bf4c0e888.png)

Using the `iri` format of that plugin, both of these urls pass the validation. But it's hardly possible to find any input which does not pass validation with the `iri` format

**Comment by luca-rath** [comment]
![image](https://user-images.githubusercontent.com/5758674/107640137-1e93b400-6c72-11eb-9428-72f0fa9a186c.png)

Okay, unfortunately this valid input doesn't pass using that plugin's `iri` implementation ... So I would say we should use ajv's `uri` implementation

**Comment by niklasnatter** [comment]
> So I would say we should use ajv's `uri` implementation

Sounds good to me 🙂 
We can still change this to a less strict validation if it turns out that the `uri` format causes problems.

**Comment by alexander-schranz** [comment]
As mention above I personally would remove the validation completely as mention above this could be also be app links which have there own formats. I think this validation will hurt us more then actually it will improve any UX.

**Comment by niklasnatter** [comment]
Dont have a very strong opinion, removing the validation is okay for me too. Just want to be able to close this issue as solved 😉

**Comment by niklasnatter** [comment]
Thanks for reporting! Fixed in #5812
