### ISSUE TITLE
Add media `single_collection_selection` field type

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5694]
| Q | A
| --- | ---
| Sulu Version | for `2.x`
| Browser Version | -

# Actual Behavior

Currently there is no field type or content types for media collections.

# Expected Behavior

In some cases it would be great to have a `single_collection_selection` field type or also a `collection_selection`. Example the sulu form bundle could use it to make it possible to set the target collection for uploaded media (could be restricted collection).

Other use cases should be a media overview on the website with very special filters for tags or categories or custom fields, where the developer want to make the query itself and can not use the smart content feature for it.

# Possible Solutions

Register selection types for the collection resource. And maybe also provide a content type for it which returns the api/collection using the collection manager service.

**Comment by alexandersch** [comment]
We would really like to see this feature. Could you maybe point us on the right direction in how to implement this or what your thoughts are about this?

**Comment by alexander-schranz** [comment]
@alexandersch a "Field Type" itself should not be much work. As the endpoint exist it just need something like the following configure in the `SuluMediaExtension`:

https://github.com/sulu/sulu/blob/b74039fb7acf16ed69d7e7e74dc83174a5a195ce/src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php#L167-L190

The content type here is more need to be discussed. As in this case it should not return any medias (for this the media smart content provider is there). Return the collection entity would need to be discussed, but if you don't need the `single_collection_selection` in pages the register of the field type would be enough and something we could currently do without any problem.

Can you provide some information about your use case and where do you want to use the field type? Always good to get feedback from the community :)

**Comment by alexandersch** [comment]
We would actually need it in a custom entity admin screen. So the field type would then suffice. 

But we actually do need the full list of media from a collection in our frontend though to show download links. So your suggestion of using the smart content media provider is probably the solution we would go for in our use case. I am not entirely sure if the headless bundle resolves the media for smart content already though. 

I was thinking that, maybe in a headless situation, you would need the collection information and not the media object in that collection. So I would probably resolve the media list in a content resolver anyway.

**Comment by alexander-schranz** [comment]
@alexandersch the media smart content provider exist in the headless bundle. Here is the current list of implemented content types in the headless bundle: https://github.com/sulu/SuluHeadlessBundle/issues/3

**Comment by niklasnatter** [comment]
Thanks for creating the issue! Should be fixed in #6219 🥳
