### ISSUE TITLE
The "localizations" entry is not always available in the templates

### ISSUE THREAD

**Issue by danakil** [sulu/sulu#5697]
| Q | A
| --- | ---
| Sulu Version | 2.2.2
| Browser Version | Firefox Linux

# Actual Behavior

Sulu should provide a "localizations" variable in each templates.
It does not provide it for templates rendered from custom controller, instead there is a "urls" variable which seems deprecated.

# Expected Behavior

The "localizations" variable should be available in all the templates.

# Steps to Reproduce

Configure a sulu with at least 2 locales. The "localizations" variable is available in the default base template.
Create a custom controller and render a custom template which extends the base template. There is only an "urls" variable available.
My custom controller is based on:
https://github.com/sulu/sulu-workshop/blob/master/src/Controller/Website/EventWebsiteController.php

# Possible Solutions

Seems confirmed by users niklas and alex in Slack.
Comment from "niklas": "it looks like the TemplateAttributeResolver was not updated when deprecating the urls variable"

**Comment by nnatter** [comment]
Should hopefully be fixed by #5698
