### ISSUE TITLE
Return absolute URLs when resolving sulu-link tags

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#5702]
| Q | A
| --- | ---
| Sulu Version | 2.1.2
| Browser Version | N/A

# Actual Behavior

Media added to a text area by using the `sulu-media` tag are replaced with relative urls in emails and therefore can not be loaded in the email.

# Expected Behavior

`sulu-media` tags should be replaced with absolute urls.

# Steps to Reproduce

We are using the `SuluFormBundle` and want to use the `sulu-media` tag inside the success email text. However, I guess the easiest way to reproduce it is using the `sulu-media` tag in any text area and then inspect the resolved url - the url is always relative.

# Possible Solutions

As discussed with @alexander-schranz the `MarkupParser` that is used by the [SwiftMailerListener](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/MarkupBundle/Listener/SwiftMailerListener.php) to replace the urls in emails should return absolute URLs.

**Comment by nnatter** [comment]
I think you are talking about the `sulu-link` tag with the `media` provider (eg `<sulu-link href="123" provider="media" />`), right?

Is there a usecase where `sulu-link` tag should be resolved to a relative link? If not, I think we could adjust the `LinkTag` to solve this for all providers? @sulu/core-team

**Comment by luca-rath** [comment]
The only usecase I could think of would be the headless bundle to allow following the link without actually refreshing the page. But I don't know if there is even a resolver for the `sulu-link` tag in the headless bundle yet

**Comment by nnatter** [comment]
> The only usecase I could think of would be the headless bundle to allow following the link without actually refreshing the page. But I don't know if there is even a resolver for the `sulu-link` tag in the headless bundle yet

When using the included JS setup, the `interceptAnchorClick` util in the `SuluHeadlessBundle` should already work with absolute URLs 🙂 
https://github.com/sulu/SuluHeadlessBundle/blob/1ba404d1c12383c0ac49072f5775707bcad03e14/Resources/js-website/src/utils/interceptAnchorClick.js#L39-L48

**Comment by luca-rath** [comment]
okay, then it's fine 👍

**Comment by alexander-schranz** [comment]
@nnatter I think it does not harm creating absolute always urls. The best way to implement this for all providers would be https://github.com/sulu/sulu/blob/7ca6a5e0d22d69c69d45f39ca52a156e75d2adfc/src/Sulu/Bundle/MarkupBundle/Markup/LinkTag.php#L55 using the `urlHelper` by symfony for [absolute_url](https://github.com/symfony/symfony/blob/494ef421c554a78b38c6779c4b7deb9a20d89923/src/Symfony/Bridge/Twig/Extension/HttpFoundationExtension.php#L53) which handles correct if you have no absolute domain.

@luca-rath this is handled by the headless js implementation correctly to check if the url is the correct domain. Also we are talking here about `media` urls for download the media, for pages and articles the link provider always return absolute urls.

**Comment by cedric-gunz** [comment]
@nnatter @alexander-schranz 

Are you planning to fix this in the near future? 

Best regards,
Cedy

**Comment by niklasnatter** [comment]
Would have been nice to get a contribution here 🙂  Just created #5834 for this.

**Comment by niklasnatter** [comment]
Thanks for reporting! Fixed in #5834
