### ISSUE TITLE
[SymfonyInsight] Your project gitignore file should not contain user-specific files 2

### ISSUE THREAD

**Issue by StaffNowa** [sulu/sulu#5724]
# Problem description
Your project gitignore file should not contain user-specific files 2

# Proposed solution
I think better set up a global .gitignore file
```
touch ~/.gitignore
git config --global core.excludesfile ~/.gitignore
```

**Comment by alexander-schranz** [comment]
@StaffNowa Thank you for report. I think with `user-specific` files you talk about `/.idea` and `.DS_Store`. Where I personal agree that this should be the case. We did add this file to make contributions as easy as possible to sulu. If we do not add them they are maybe accidentally commitet by contributors and we need then always ask them to remove them or do it ourself. I think this files do not hurt in the `.gitignore` file and in a project created over the skeleton the `.gitignore` can always be edited. Or do you have a case where this hurts? Or make your setup process more difficult?

**Comment by StaffNowa** [comment]
For me ok :+1: like we have now :-1: Just checked Symfony Insight report :)

**Comment by alexander-schranz** [comment]
@StaffNowa oh thx for sharing the result. I will close this one as I see currently not advantage for removing them.
