### ISSUE TITLE
symfony/http-foundation 5.2 => 6.0

### ISSUE THREAD

**Issue by StaffNowa** [sulu/sulu#5726]
# Problem description

```
The constant Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_ALL is deprecated but you use it
@deprecated since Symfony 5.2, use either "HEADER_X_FORWARDED_FOR | HEADER_X_FORWARDED_HOST | HEADER_X_FORWARDED_PORT | HEADER_X_FORWARDED_PROTO" or "HEADER_X_FORWARDED_AWS_ELB" or "HEADER_X_FORWARDED_TRAEFIK" constants instead.
In file public/index.php on line 40.
```

# Proposed solution

Possible solution change Request::HEADER_X_FORWARDED_ALL into Request::HEADER_X_FORWARDED_FOR

**Comment by alexander-schranz** [comment]
@StaffNowa currently we support a range from 4.4 to 5.x. This means that we will have Symfony Deprecations which were introduce after 4.4. This deprecations will not be changed until we will cancel the support for 4.4 which I think will not happen before we support Symfony 5.4 LTS / 6.0 is released. Still thank you for report. So we can change this only when it is supported that way also in the 4.4 Version. Can you test this and create a PR for it in sulu/sulu and sulu/skeleton repository 2.1 branch?

**Comment by StaffNowa** [comment]
@alexander-schranz ok I will check it ;)

**Comment by alexander-schranz** [comment]
@StaffNowa as the skeleton always is installed with the newest version of symfony/symfony in the `sulu/skeleton` repository we can use the new [index.php](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.1/public/index.php)

**Comment by niklasnatter** [comment]
Thanks for reporting! Should be fixed by https://github.com/sulu/sulu/pull/5729 🎉
