### ISSUE TITLE
Custom form "Page block settings" for page template

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu#5727]
Hello,

I try to set a custom form block setting as described in [https://docs.sulu.io/en/2.2/reference/content-types/block.html#extending-block-settings](url) with settings_form_key, for some blocks in my page template.
My custom form settings is not loaded, still have the default form "page_block_settings.xml"
My blocks params :

```
<block name="content_sections" default-type="section" minOccurs="0">
                    <meta>
                        <title lang="fr">Sections</title>
                    </meta>
                    <params>
                        <param name="add_button_text">
                            <meta>
                                <title lang="fr">Ajouter une section</title>
                            </meta>
                        </param>
                        <param name="settings_form_key" value="page_section_settings"/>
                    </params>
                    ...
```
                    
My setting form in config/forms/page_section_settings.xml :

```
<?xml version="1.0" ?>
<form xmlns="http://schemas.sulu.io/template/template"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/form-1.0.xsd"
>
    <key>page_section_settings</key>
    <properties>
        <section name="section_settings">
            <properties>
            ...
```
            
It would be great to have different settings per blocks tag <block>. 
I my case, I use nested blocks as sections and columns and it makes sense to have specifics settings for each block tag (not type).

Thanks

**Comment by alexander-schranz** [comment]
@rflorent thx for report. Can it be that the following part does always override your param: https://github.com/sulu/sulu/blob/60901bf750bc324816e7231fac76d1d35d87e9e1/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php#L184-L187 Then this would be a bug which should be fixed there.

**Comment by rflorent** [comment]
@alexander-schranz thanks, that's right, this part override my params. If I comment out, my custom setting form is loaded but the "page_block_setting" param is lost (hide block).

How can I do to keep the hide block setting with my custom settings ? put it on my custom form ?

**Comment by alexander-schranz** [comment]
@rflorent I think we need to check if no other value was set by using `!array_key_exists('settings_form_key', $itemMetadata->getOptions())` in the if statement. Do you want to create a PR for this for the 2.2 branch?

**Comment by alexander-schranz** [comment]
Fixed in https://github.com/sulu/sulu/pull/6171
