### ISSUE TITLE
Sulu Media Ghostscript Path can't handle env values

### ISSUE THREAD

**Issue by friemt** [sulu/sulu#5730]
| Q | A
| --- | ---
| Sulu Version | 2.2.2
| Browser Version | all

# Actual Behavior

```
sulu_media:
    ghost_script:
        path: ...
```

- `path: '/usr/local/bin/gs/'` does work
- `path: '%env(GHOSTSCRIPT_BINARY)%'` does not work
- `path: '%env(resolve:GHOSTSCRIPT_BINARY)%'` does not work
- `path: '%ghost_script_path%'` does not work

# Expected Behavior

```
sulu_media:
    ghost_script:
        path: ...
```

- `path: '/usr/local/bin/gs/'` does work
- `path: '%env(GHOSTSCRIPT_BINARY)%'` does work
- `path: '%env(resolve:GHOSTSCRIPT_BINARY)%'` does work
- `path: '%ghost_script_path%'` does work

# Steps to Reproduce

- Checkout & install Sulu. 
- Add a `sulu_media.ghost_script.path` from above.
- Try to upload a PDF to any collection.

**Comment by niklasnatter** [comment]
Thanks a lot for reporting! Should be fixed in the next release by https://github.com/sulu/sulu/pull/5740
