### ISSUE TITLE
Backend javascript media queries on key pressed

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu#5743]
| Q | A
| --- | ---
| 2.2.3 |
| 7.3 | 
| MariaDB | 
| Firefox 84.0.2 | 

# Actual Behavior

On backend's xml template page form, after selecting a media (field block), every key pressed on a text field, or a action on a field will call a media request.  Overload and slowness make the backend unusable.

# Expected Behavior

No useless request

# Steps to Reproduce

Open web debug tools, add ou edit a xml template page, select a media and edit other fields. 
Tested on firefox and chrome, on local project and sulu demo online.

# Possible Solutions
![bug-mystique-3](https://user-images.githubusercontent.com/8590540/104214128-5e7b3780-5437-11eb-9ba6-2adcac1641e9.jpeg)

**Comment by alexander-schranz** [comment]
@rflorent Thx for report could be that we did introduce here a bug in #5576

/cc @nnatter @Prokyonn maybe we forget to add somewhere to add a `key` property and instead of reuse a component it create a new instance of it and do a new request.

**Comment by niklasnatter** [comment]
Thanks for reporting! Should be fixed in the next release by #5745
