### ISSUE TITLE
How to add a custom ToolbarAction

### ISSUE THREAD

**Issue by ymc-thzi** [sulu/sulu#5746]
I simply want to add a button to the list view in the admin. I found this in the docs 

> ... there is a formToolbarActionRegistry and a listToolbarActionRegistry extension point that allow to register custom toolbar actions...

I have no idea how to start this. There is not one single example on the whole internet where and how to add an action. 😄
First of all, is it to do in JS or PHP?
Where and how can I set a custom ToolbarAction?

I tried almost everything setting ToolbarActions in the yml config files because of this doc entry somewhere 
> ...The actions that are displayed in the toolbar can be configured using the route's options...

Please help me, how this is concrete meant to be work.

**Comment by luca-rath** [comment]
There is an example how to do this 😉 See https://github.com/sulu/sulu-demo/pull/81

**Comment by niklasnatter** [comment]
Depending on where you want to add a toolbar action, the following example pull requests should be helpful:
- https://github.com/sulu/sulu-demo/pull/81
- https://github.com/sulu/sulu-demo/pull/82

**Comment by ymc-thzi** [comment]
cool, thanks for the hints

**Comment by niklasnatter** [comment]
The [Sulu Demo repository](https://github.com/sulu/sulu-demo/pulls?q=is%3Aopen+is%3Apr+label%3AExample) contains multiple pull requests that demonstrate how to extend different parts of the administration interface. The examples include adding custom toolbar-actions, content-types, list-field-transformers, list-item-actions and completely new views. 

As the administration interface is a Javascript application built with React, these things are mostly implemented as React components and need to be added to the respective Javascript registries to allow for using them in your application. The built-in views, services and components of the administration interface application are documented in the [Sulu Javascript Docs](https://jsdocs.sulu.io/). 

To make these resources easier to discover, we recently added links to them to the first paragraphs of the [Extend Admin UI chapter of the Sulu documentation](https://docs.sulu.io/en/2.2/book/extend-admin.html).

I am closing this as solved. Feel free to open a new issue if you encounter any problems 🙂
