### ISSUE TITLE
Position on admin UI

### ISSUE THREAD

**Issue by ehibes** [sulu/sulu#5770]
# Problem description

Hi everybody, 
I made a custom entity in my Sulu project and generate an Admin UI list view. 
Is there a way to make this list "orderable", I mean to change position of entities ?

**Comment by niklasnatter** [comment]
Thanks for reporting. I think this is a duplicate of https://github.com/sulu/sulu/issues/5371 - please upvote/add your thoughts there. Feel free to create a new issue if I am mistaken 🙂
