### ISSUE TITLE
Teaser Selection does not show secured pages.

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#5785]
| Q | A
| --- | ---
| Sulu Version | 2.2.2

# Actual Behavior

When pages are secured with the website roles and you select them in a teaser selection they wont load any of the page details and in result also not shown on the page even when logged in. I know that it is not that easy because the teaser_selection is saved in the index and not like the other fields.

# Expected Behavior

Also secured pages should be selectable in the teaser_selection

# Steps to Reproduce

Secure some pages with website roles and try to add them to a teaser_selection

**Comment by alexander-schranz** [comment]
Think this is similar to #4066. I think as know website permissions are also handled over the permission tab we really need to have a look at this or maybe refractor the `TeaserSelection` to work with PHPCR query instead of index.

**Comment by niklasnatter** [comment]
Think this would be a good opportunity to refactor the `PageTeaserProvider` to use PHPCR instead of the search index. I feel like using the search index there regularly causes problems and makes things hard to understand and extend.

**Comment by niklasnatter** [comment]
Should be fixed in #5842. Thanks a lot for reporting!
