### ISSUE TITLE
Link Provider Proposal

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#5790]
# Problem description

Currently there is a lot of usecases where the content manager should decide if he want to create a **Internal Link**  or a **External Link**. Currently there is no content type to handle both. 

# Proposed solution

We should create a content type which would implement our Link Providers and also make it possible to create also external links.

So we have a select with example:

 - External
 - Page
 - Article
 - Media
 
 When External is clicked an overlay with where url field:
 
<img width="497" alt="Bildschirmfoto 2021-02-03 um 11 07 31" src="https://user-images.githubusercontent.com/1698337/106731700-10a9b780-6610-11eb-819b-f5a52604be1c.png">

For Pages a Overlay with a Single Page Selection:

<img width="500" alt="Bildschirmfoto 2021-02-03 um 11 08 19" src="https://user-images.githubusercontent.com/1698337/106731753-2c14c280-6610-11eb-8333-b85d72b33ce3.png">

The field should be saved in the following way:

For External Link:

```js
{
     "type": "external",
     "value": "https://sulu.io",
}
```

For Page:
 
 ```js
{
     "type": "external",
     "value": "6af41b72-3947-4326-a1b0-ee21c056bd43",
}
```

For Article:
 
 ```js
{
     "type": "external",
     "value": "6af41b72-3947-4326-a1b0-ee21c056bd43",
}
```

For Media:
 
 ```js
{
     "type": "external",
     "value": 1,
}
```

The content type could also have the possibility to add a `target` but this should be activate able so example:

```js
{
     "type": "<type>",
     "value": "<typeid>",
     "target": "_blank",
}
```

Additional it could also be possible that we the title could be changed we have mostly the use case here:

```js
{
     "type": "<type>",
     "value": "<typeid>",
     "target": "_blank",
     "title": "My Custom Title",
}
```

This could be activated by:

```xml
<property name="link" type="link_provider"><!-- maybe just call it `link` -->
       <params>
                <param name="target" value="true" />
                <param name="title" value="true" />
       </param>
</property>
```

And would look like this in the overlay:

<img width="499" alt="Bildschirmfoto 2021-02-03 um 11 14 40" src="https://user-images.githubusercontent.com/1698337/106732479-076d1a80-6611-11eb-8c32-8a33f3940ee5.png">

Its important that its only activate able because the target and title should not be here when the developer does not handle it.

### Note

instead of `type`  we could be use `provider` and instead of `value` we could use `href` so we are similar to the `<sulu-link />` Tag which will also use this LinkProvider services. We should also keep in mind that there could also be a additional `anchor` field in future for this link providers not sure if this will be `<sulu-link href="<id>#my-anchor"/>` or `<sulu-link href="<id>" anchor="my-anchor" />`. 

### Resolving of this Field Type as Content Type

The resolved object should look like the following:

```js
{
     "type": "page",
     "link": "http://sulu.io/my-page",
     "title": "My Title",
     "target": "_blank",
}
```

```js
{
     "type": "external",
     "link": "http://sulu.io/my-page",
     "title": "My Title",
     "target": "_blank",
}
```

To avoid confusing between `link` and `value` in case of external link I would not output the value to the resolved.

**Comment by niklasnatter** [comment]
This was fixed implemented in #6134 and will be included in the upcoming Sulu 2.4 release 🎉 
We plan to publish the first stable Sulu 2.4 release in the end of 2021.
