### ISSUE TITLE
Tags are limited to 10 in the tag selection content type

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#5828]
| Q | A
| --- | ---
| Sulu Version | 2.1.2
| PHP Version | 7.4.9
| DB Version | 5.7.31
| Browser Version | Any browser

# Actual Behavior

Only 10 tags are loaded in a tag selection in the Sulu admin area.

# Expected Behavior

Either there is something like a pagination for tags or the limit of tags that are loaded for a tag selection should be configurable in the xml.

# Steps to Reproduce

1. Add 11 tags to a tag selection in Sulu.
2. Save (all 11 tags will be saved).
3. Reload the page.
4. Only 10 tags will be displayed in the tag selection.
5. If you save the page, those 10 tags will be saved, the 11th is missing afterwards.

**Comment by luca-rath** [comment]
Thank you for reporting this bug! Fixed in #5830
