### ISSUE TITLE
Double-clicking sorting-number inputs navigates to the edit view

### ISSUE THREAD

**Issue by sanderquirynen** [sulu/sulu#5838]
| Q | A
| --- | ---
| Sulu Version | 2.2.4
| Browser Version | Multiple browsers
# Actual Behavior

When you go to a sorting view in a webspace and double-click one of the number fields, you get redirected to the page, instead of selecting the value inside the input field (the default behaviour of input fields).

# Expected Behavior

Just select the value inside the input.

# Steps to Reproduce

1. https://sulu.rocks/admin/#/webspaces/demo
2. Webspaces
3. Click 'order'
![image](https://user-images.githubusercontent.com/5577225/108845500-cc418400-75dd-11eb-8e96-04252b10ef32.png)
4. Double click one of the inputs
![image](https://user-images.githubusercontent.com/5577225/108845592-e8452580-75dd-11eb-9bbe-5d776db410ee.png)

**Comment by alexander-schranz** [comment]
Can confirm this and as I know @chirimoya did also mention it once, we should definitely in sort mode disable the click listeners as double click is mostly use to mark all numbers inside input and I aslong as it is in edit mode of the order you should not be possible to do in this column something else or navigate to a item.

**Comment by niklasnatter** [comment]
Thanks for reporting! Should be fixed in #5838
