### ISSUE TITLE
Number-Types not visible in collapsed block preview

### ISSUE THREAD

**Issue by HellFirePvP** [sulu/sulu#5860]
| Q | A
| --- | ---
| Sulu Version | 2.2.4
| PHP Version | 7.4.15
| DB Version | Postgres 12.2
| Browser Version | Google Chrome 89.0.4389.82

# Actual Behavior

In the collapsed block view, a number-type property does not show its value, even if the tag "sulu.block_preview" is added to it.

# Expected Behavior

The number-type property should show its value in the collapsed view.

# Steps to Reproduce

- Create a Block element which contains a number-type property
- Add the tag "sulu.block_preview" to that property
- Collapse the element and check the collapsed view

# Possible Solutions

As far as 'niklas' in the Sulu slack channel mentioned:
> i think the StringBlockPreviewTransformer does not handle numbers at the moment indeed. can you please create an issue for this?

**Comment by luca-rath** [comment]
Fixed by #5861
