### ISSUE TITLE
Block settings are applying in all blocks

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#5868]
| Q | A
| --- | ---
| Sulu Version | >= 2.2.4 
| PHP Version | -
| DB Version | - 
| Browser Version | Checked on Chrome Versión 88.0.4324.192 

# Actual Behavior

If some setting is applied in a block when you open block settings in another block same settings is applied ( not saved if you don't push apply )

# Steps to Reproduce

- Go to sulu.rocks , edit a block settings and check "Don't display on public website" 
- Edit settings in next block and the check is marked

**Comment by niklasnatter** [comment]
Can confirm that this is a bug - thanks for reporting!
We should probably reset the data of the `blockSettingsFormStore` before opening (or after closing) the overlay here:
https://github.com/sulu/sulu/blob/aa692e8255750d21f5a287a420304c544c2a8619/src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js#L383-L395

**Comment by niklasnatter** [comment]
Thanks for reporting! Should be fixed by #5882
