### ISSUE TITLE
Preview of articles not working with global variables defined in the templates

### ISSUE THREAD

**Issue by tstauer** [sulu/sulu#5874]
| Q | A
| --- | ---
| Sulu Version | 2.2.5
| PHP Version | 7.3.24
| DB Version | MySQL 5.7.35
| Browser Version | Firefox 78.8.0esr
| massive/web-twig-extensions | v1.5.0
| symfony/twig-bridge | v5.2.3
| symfony/twig-bundle | v5.2.4
| twig/twig | v2.14.3

# Actual Behavior

We are getting the message "500 Internal Server Error" instead of the preview of an article.

# Expected Behavior

We want to see the preview of the article we are looking at in the Sulu backend.

# Steps to Reproduce

Define some global variable outside of blocks in a twig template and rely on that variable in the block named "content".
```
{% set breadcrumbsLevel = 1 %}

{% block content %}
    {{ dump(breadcrumbsLevel|default('variable not set')) }}
{% endblock %}
{% block someotherblock %}
    {{ dump(breadcrumbsLevel|default('variable not set')) }}
{% endblock %}
```

This is the output:
```
"variable not set"

1
```

We see the variable is output in "someotherblock" but missing in "content".

# Possible Solutions
I find the idea to only render the content block for the preview is great and it seems straight forward. However it looks like the global variable of the template is lost in this change. Tried to find out when this was introduced but couldn't find out which version it was released to

This is where I'd suggest to not use "Sulu\Bundle\PreviewBundle\Preview\Preview::renderPartial" and to render the entire template and cutting the content out of the previewContentReplacer in "src/Sulu/Bundle/WebsiteBundle/Resources/views/Preview/preview.html.twig", like before the change.

As alternative it should be noted in the upgrade documentation to Sulu 2.

**Comment by alexander-schranz** [comment]
This is a limitation of the preview and this has nothing todo with sulu 2.0 this limitation does also exist in 1.6 the error is just more visible in 2.0 as most devs didn't read the error message in the logs.

If you open your 1.6 sulu you will see some like this also there in the response of the preview:

>  message | Object { code: 9903, message: "Variable  \"test\" does not exist.  (/Sulu/sulu-article.lo/app/Resources/views/templates/default.html.twig  line 17)", type: "Sulu\\Bundle\\PreviewBundle\\Preview\\Exception\\TwigException" }
-- | --

So here was no breaking changes just DX improvement that the error is shown, and so the live refresh is not longer working correctly.
