### ISSUE TITLE
Trying to edit a page without language permission

### ISSUE THREAD

**Issue by paul-staedtler** [sulu/sulu#5884]
| Q | A
| --- | ---
| Sulu Version | 2.2.3
| PHP Version | 7.4.15

# Actual Behavior

When trying to edit a page without the permission for the corresponding language it will show a infinite "loading" screen and throws an exception in the background: 

`Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException:
Permission "view" in localization "de" for object with id "cef8e1b9-0219-4505-9d87-bd01273843c1" and of type "Sulu\Component\Content\Document\Behavior\SecurityBehavior" not granted`

It already doesn't show the edit Button anymore if you don't have the permission for the language but you can simply double click on the page and it will "open" anyway.

This doesn't happen when opening the page first in a language the user has permission to and then switching to a not permitted one with the language switch at the top right. Then it will show you access denied and you can simply switch back again. Even though this is also a bit weird because it still shows one the delete button which can be used but will throw an exception in the background. Similar to the issue i created a few days back #5876

# Expected Behavior

It shouldn't be possible to open the pages by double clicking on them if the user doesn't have the permission for the language.
Just like the button for editing is already not shown anymore.

# Steps to Reproduce

I have created a role which has all permissions for a web space so it can create and edit pages in it but didn't give the user which i assigned the role to the permission for all languages.
So now when trying to edit any page in a language the users doesn't have permission to do so (by simply double clicking the page instead of the edit button which is not visible) he gets an irritating response.

**Comment by niklasnatter** [comment]
Thanks a lot for reporting! Should be fixed in #5885
