### ISSUE TITLE
Requesting ContactBundle\Entity\Account::getAccountAddresses() through Doctrine triggers incorrect return  value

### ISSUE THREAD

**Issue by wimulkeman** [sulu/sulu#5897]
| Q | A
| --- | ---
| Sulu Version | 2.2.5
| PHP Version | 7.2.20
| DB Version | 5.7.32-35
| Browser Version | - (issue on command line)

# Actual Behavior

When running the command `bin/console massive:search:reindex` the following error is thrown when indexing the accounts:

```
provider "doctrine_orm"

-- reindexing "8" instances of "Sulu\Bundle\ContactBundle\Entity\Account"
 0/8 [>---------------------------]   0%

In Account.php line 325:
  Return value of Sulu\Bundle\ContactBundle\Entity\Account::getAccountAddresses() must implement interface Doctrine\Common\Collections\Collection, null returned

massive:search:reindex [--batch-size BATCH-SIZE] [--provider PROVIDER]
```

This issue is given on `getAccountAddresses`, `getPhones` and `getEmails`.

# Expected Behavior

The expected behavior is that the account can be called through Doctrine ORM when no address, phonenumber or e-mail is provided for the account.

# Steps to Reproduce

1. Create a new account in admin under Contacts > Persons without an address or e-mail
2. Run `bin/console massive:search:reindex`

# Possible Solutions

The properties like `accountAddresses` are populated `new ArrayCollection()` which satisfies the required return value. The issue is that Doctrine skips the construct part because it uses reflection to fill the Entity properties. Therefore the property stays null.

The code anticipates this as can be seen in https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/ContactBundle/Entity/Account.php#L534 where the code checks for a possible null occurrence.

Locally I fixed it by altering the [AccountInterface](https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/ContactBundle/Entity/AccountInterface.php) and [Account entity](https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/ContactBundle/Entity/Account.php) to return `?Collection` instead of `Collection` for the functions [getAccountAddresses](https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/ContactBundle/Entity/Account.php#L521), [getPhones](https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/ContactBundle/Entity/Account.php#L323) and [getEmails](https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/ContactBundle/Entity/Account.php#L342)

**Comment by alexander-schranz** [comment]
Thank you for report.

I think we can not change the interface here from BC promise but I think we could return an empty array collection e.g.:

```php
return $this->accountAddresses ?: new ArrayCollection();
```

Do you want to create a PR for this on the `2.1` branch?

**Comment by wimulkeman** [comment]
That would indeed fix it. I will create a PR for it

**Comment by wimulkeman** [comment]
@alexander-schranz Should I set the update for all the methods which expect to return a Collection?

- getUrls
- getPhones
- getEmails
- getNotes
- getChildren
- getFaxes
- getSocialMediaProfiles
- getBankAccounts
- getTags
- getAccountContacts
- getAccountAddresses
- getMedias
- getCategories

The properties called by these methods are filled in the constructor.

**Comment by alexander-schranz** [comment]
Rethinking this here is maybe just something false with the loading mechanism because Doctrine should initialize it with a PersistentCollection or Lazy Collection and we should not have the need to handle this in our code.

**Comment by alexander-schranz** [comment]
@wimulkeman I tried to reproduce it. I created an `Account` without any address in a normal sulu/skeleton and it did work without any problems. Can you try if it works for you with a normal `sulu/skeleton` installation. Maybe the bug is inside a change of your project.

**Comment by niklasnatter** [comment]
As far as i understand, doctrine should initialize these properties based on the mapping for the entity if the entity is loaded from the database. The initialization in the constructor is only needed if a new entity is created somewhere in the code: https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/association-mapping.html#initializing-collections

Have you overwritten any entities or changed the mapping for existing entities in your project?

**Comment by wimulkeman** [comment]
@alexander-schranz @nnatter I checked it with the `sulu/skeleton` and `sulu/sulu` repos. In both cases it works. As a test I also coupled the database of the project where it failed and it also works on the specified project database.

I see that in the project the account entity is overwritten but the new Entity is not used in Massive Search. The Doctrine configuration has also been changed under `packages` but only to include the entities under `src/`. There seems to be a mix of annotations (in the project) and xml files (in Sulu) for the same entity. Maybe that messes some things up. That will need to be investigated in the project.

Based on that I would say the issue is indeed in the project itself en therefore I will close this issue. Thanks for your feedback.

**Comment by niklasnatter** [comment]
@wimulkeman Thanks for investigating! There is an article in the documentation about how to overwrite an entity, maybe you can check if the project is configured like described:
https://docs.sulu.io/en/2.2/cookbook/extend-entities.html

I could imagine that overwriting an entity can mess things up here. Please feel free open a new issue if you can reproduce the problem by overwriting an entity as described in the docs! 🙂

**Comment by niklasnatter** [comment]
Okay I tried this in on of our projects and I suspect that the `massive/search-bundle` package is not compatible with overwritten entities 😕  
Would you test if you can confirm this and create a new issue if you can?

**Comment by wimulkeman** [comment]
@nnatter Thanks for checking. I will give it a try in the project and let you know the results.

**Comment by wimulkeman** [comment]
@nnatter The configuration for overwriting the Account entity in the project is equal to the one descripted on at https://docs.sulu.io/en/2.2/cookbook/extend-entities.html. I will try to find a reason why `massive/search-bundle` is not using the new model and if this causes the conflict.

Would you like to have a new issue for that in this repo `sulu/sulu` because the overwrite is done through a custom Sulu part or should it be placed under `massive/search-bundle`? If I can find the cause I could be more precise where the fault would be.

**Comment by niklasnatter** [comment]
> I will try to find a reason why massive/search-bundle is not using the new model and if this causes the conflict.

I think the `massive/search-bundle` is using an invalid mapping because of the hardcoded class in the `massive-search-mapping`:
https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/ContactBundle/Resources/config/massive-search/Account.xml#L3

I guess we need to use the interface in the `massive-search-mapping` and somehow adjust the `massive/search-bundle` to resolve the target entity for the interface. Unfortunately I dont have time to have a deeper look at this at the moment 😕 

> Would you like to have a new issue for that in this repo sulu/sulu because the overwrite is done through a custom Sulu part or should it be placed under massive/search-bundle?

Would prefer to create it in the `sulu/sulu` repository for visibility. The `massive/search-bundle` repo is not very active and is basically maintained by the Sulu team anyway 🙈 

Thanks a lot for your effort!
