### ISSUE TITLE
Collapsable sections in the backend

### ISSUE THREAD

**Issue by GillesKnockaert** [sulu/sulu#5899]
# Problem description
When adding blocks to in the backend that page can become quite long, for this you can collapse blocks so that they are compact which is very nice. but sometimes this just won't cut it. to create structure here you can add sections.

# Proposed solution
also make sections collapsable
We often have blocks that you don't need to change a lot since they affect the way the page is displayed on the frontend. Let's say we have a section called page settings. here we add some stuff like some toggles, ability to add a background image,....

Once we have this all set up we don't need to acces this anymore (well not often at least). So here it would be nice if we could collapse this section so that it takes less place in the backend.

**Comment by niklasnatter** [comment]
Thanks for writing this up! I am going to close this because there is an existing issue for such a feature (#5094). 
Please upvote the existing issue and feel free to add additional thoughts there 🙂
