### ISSUE TITLE
Blank page on list index custom entity after insert

### ISSUE THREAD

**Issue by Romaixn** [sulu/sulu#5925]
| Q | A
| --- | ---
| Sulu Version | 2.2.6
| PHP Version | 7.4.3
| DB Version | postgres 13
| Browser Version | Chrome 89.0

Hello, after check out the code at https://github.com/sulu/sulu-demo/tree/example/custom-entity , I tried to reproduce.

This work but when I save an entity, I have a blank page on list view. (without sidebar, etc)

Did I miss something to have this problem?

**Comment by niklasnatter** [comment]
Hey,
do you see any errors or failed requests in the development tools of your browser?

**Comment by Romaixn** [comment]
Thanks to your response on Slack, I've solved the problem! It came from a "checkbox" field that is not available in the listing.
