### ISSUE TITLE
ContentRepository: Only fetching needed properties to increase Sulu performance

### ISSUE THREAD

**Issue by d3vpunk** [sulu/sulu#5935]
# ContentRepository::resolvePermissions is fetching unused properties

Hi everyone :slightly_smiling_face: We are currently working on several performance fixes, starting with one of our biggest sites with the awesome Sulu 2 :+1: 

On many pages we have now already implemented cache for the navigation and it has some effect - it works well.
But we looked further and noticed that much time is spent in specific methods. We did several Blackfire tests and we noticed that calling the `ContentRepository::findByUuids` takes quite a long time (see screenshot, prod mode).

We looked further and we noticed two things: One has to do with query cache could be used to increase the performance.
See: https://github.com/doctrine/DoctrinePHPCRBundle/pull/359 

The other is about the handling of the **result permissions**:

You can see in the screenshot that this method is constantly called:

![result_permission_time](https://user-images.githubusercontent.com/1311487/114567694-c5490080-9c73-11eb-953a-445a4b6e4c21.png)

The `ContentRepository::getNode` method fetches the complete node with often about 200-800 properties. And in our case: Only a few or none are left over in the end. ( `sec:*` filter ) 

.. to find in this method: https://github.com/sulu/sulu/blob/c0e3b0b4d64d82111618a48de374e10265f3fb89/src/Sulu/Component/Content/Repository/ContentRepository.php#L455

![permission_code](https://user-images.githubusercontent.com/1311487/114568245-41dbdf00-9c74-11eb-8be1-895968f85d1c.png)
![stack_properties](https://user-images.githubusercontent.com/1311487/114568248-42747580-9c74-11eb-9b5f-67325c09a875.png)

# Possible solution 1: Make it possible to only fetch needed properties

If we could somehow have the possibility to fetch only the properties that are needed in the first place, we would have a performance boost. So with an early return (`[]`) in this function our code **runs 20%-30% faster**. 

# Possible solution 2: Configuration option to disable permissions in website mode

Somehow disable permissions at all (in website mode). I guess on many projects the most pages are anonymous anyway - without firewall involved - so granular checks on permission aren't needed.

Idea: Is a configuration where you can disable permissions completely in that situations useful? Like `permission_enabled: true`
Of course this flag should be enabled by default - but when desired - permissions could be disabled in frontend.

**Comment by niklasnatter** [comment]
Thanks a lot for writing this up and providing all the relevant information! 

The problem should hopefully be fixed in the next release by #6089 🙂

**Comment by d3vpunk** [comment]
@nnatter  @alexander-schranz  You are amazing. Thank you very much!

**Comment by alexander-schranz** [comment]
Beside the profiled performance issue here, we could also improve the performance when using jackalope-doctrine-dbal adapter: https://github.com/jackalope/jackalope-doctrine-dbal/pull/381. Also older sulu versions will benifit from it as it is released with jackalope/jackalope-doctrine-dbal 1.7.0.
