### ISSUE TITLE
CKEditor heading dropdown cut off

### ISSUE THREAD

**Issue by tstauer** [sulu/sulu#5938]
| Q | A
| --- | ---
| Sulu Version | 2.2.7
| PHP Version |7.3.24
| DB Version | MySQL 5.7.30
| Browser Version | Firefox 78.9.0esr (64-Bit)

# Actual Behavior

Sulu cuts off the dropdown for heading options at the end of a block

# Expected Behavior

The dropdown is fully displayed or a scrollbar within the dropdown allows to scroll to all entries.

# Steps to Reproduce

Configure a block with a ckeditor in a template and let the block end directly after the ckeditor.
The demo sulu.rocks has a picture choice after the ckeditor so the issue can not be reproduced there.
<img width="391" alt="cutmenu" src="https://user-images.githubusercontent.com/48862892/115020270-a38d8a80-9eba-11eb-8407-62094c40024f.png">

This is a template to reproduce the observed behaviour.
[test.xml.zip](https://github.com/sulu/sulu/files/6324732/test.xml.zip)

This issue may be related to https://github.com/sulu/sulu/pull/5744.

**Comment by alexander-schranz** [comment]
Thx for reporting this issue. I hope that we maybe can fix it on ckeditor directly to avoid issues like this in future. https://github.com/ckeditor/ckeditor5/issues/9499. Else there seems currently be a `overflow-y: hidden` on the default `grid` element which was added here: https://github.com/sulu/sulu/commit/96096d163f29679215845f3877fa67da33f377ef I think we should remove that and make sure that the  `ghost dialog` has no side effects when we are doing it as it seems it was added in that PR.

**Comment by niklasnatter** [comment]
Should be fixed in #6054 - thanks for reporting! 🙂
