### ISSUE TITLE
Resource title of domain event is not localized

### ISSUE THREAD

**Issue by luca-rath** [sulu/sulu#5940]
| Q | A
| --- | ---
| Sulu Version | 2.3

# Actual Behavior

The resource title of a `DomainEvent` is not localized. This will probably be a problem for `removed` events as soon as there should be an audit log showing entity deletions, because then the actual entity is not available anymore to retrieve the title in the correct language.

# Possible Solutions

All available translations of the resource title could be saved on the `DomainEvent`'s event context.

**Comment by alexander-schranz** [comment]
Saving all locales would also mean that we would need to load the entity in all locales, which is a lot of overfetching, specially for big sites like some of our community member did have with +50, +60 localizations. So I would not save the title in all available localizations.

If we display it in the UI and it did happen in another locale we could show beside the title the locale example as indicator that the title is shown in that locale:

> Thomas Schedler did remove the "測試" (zh) page.

And if it was removed in the same locale the current user is shown it could just be:

> Thomas Schedler did remove the "Test" page.

I think that would be fine.

**Comment by luca-rath** [comment]
So this means, that the`resourceLocale` has to be saved on any domain event, even for `removed` events, but this is kind of strange, because if there is a domain event of type `removed` and with locale `en`, one could think, that this resource has only been removed for locale `en` instead of deleted completely. So I would suggest adding a new field `metaLocale` or `resourceTitleLocale` or something similar. /cc @nnatter

**Comment by alexander-schranz** [comment]
@luca-rath would not add a additional locale here just to display it. A event which removes the locale would be named differently and will not be the same event, so I don't think that this will be confusing.

**Comment by luca-rath** [comment]
In a short call with @sulu/core-team we decided to add an additional locale field, which saves the locale of every localized information in that event (`resourceTitle` and maybe some other localized information in `eventContext`), but we haven't come up with a proper name yet. My suggestion would be `metaLocale`.

* I think `resourceTitleLocale` would be too specific, because it's possible, that the event context contains localized information such as a description.
* The problem with `eventLocale` is, that it's not really clear what's the difference between `resourceLocale` (the already existing locale) and that new `eventLocale`.
* Also there was the suggestion of `contextLocale`, but I'm also not a big fan of that, because IMO this is less self descriptive.

**Comment by alexander-schranz** [comment]
As a reference here the current fields on the EventRecord: https://github.com/sulu/sulu/blob/7833cdced3878fe25303c0f93c99daeba1e5e6b8/src/Sulu/Bundle/EventLogBundle/Resources/config/doctrine/EventRecord.orm.xml#L10-L26

Also not sure about it. I think in all cases the problem is what is the difference between this 2 locales. Maybe the current `resourceLocale` should be renamed to `eventLocale` and use something like `resourceContextLocale`. Still I think its hard to know which locale is for which aslong as we would not be too specific like resoucreTitleLocale. 

Also a question could be, do we need `resourceTitle` on the `EventRecord` itself, a solution could be that we move both the `title` and this `locale` to the `eventContext`, then its also more clear how its connected.

**Comment by luca-rath** [comment]
Since **every** domain event should have a resource title, i don't think we should move that into the event context. From my understanding, the event context contains *additional information* about the event or the resource

**Comment by alexander-schranz** [comment]
> Since every domain event should have a resource title

Also when we still have on PHP level a `getResourceTitle` method we could still save it as a part of the `eventContext` with the `locale`. Just thinking out loud which alternatives we have here to avoid confusion with 2 locales.

**Comment by niklasnatter** [comment]
The `eventContext` provides additional information that is relevant for a specific event. If that event has no `resourceLocale`, it concerns all translations of the entity (eg. moved/deleted). I am not sure if there is a lot of localized information that is relevant in the context of such an event.

What would be an example where the `eventContext` contains localized information but the `resourceLocale` is not set? 🤔 

If this is not a common thing, i would go for the simple way and store a `resourceTitleLocale` that has a fallbacks to the `resourceLocale`.

**Comment by alexander-schranz** [comment]
> What would be an example where the eventContext contains localized information but the resourceLocale is not set? 🤔

Thats true.

I think I would then go with `resourceTitleLocale`, I think this is currently the only naming which make it not confusing when we have 2 locales on the event record.

**Comment by luca-rath** [comment]
`resourceTitleLocale` is fine for me 👍

**Comment by luca-rath** [comment]
@nnatter @alexander-schranz implemented in #5945
