### ISSUE TITLE
Media folders missing from the "move image" targets

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5975]
| Q | A
| --- | ---
| Sulu Version | 2.2.7
| PHP Version | 7.4
| DB Version | Pgsql
| Browser Version | Latest Chrome

# Actual Behavior

You want to move a media item but the folder is missing in the selection

![image](https://user-images.githubusercontent.com/245385/116682765-f6813a80-a9ae-11eb-8921-08fae839cd24.png)

![image](https://user-images.githubusercontent.com/245385/116682780-faad5800-a9ae-11eb-94c1-ae32c503619a.png)

# Expected Behavior

All folders I can see in the media over view are selectable if I want to move an media item.

# Steps to Reproduce

Add more then 10 folders and try to move an image to those above 10. There should be some missing.

# Possible Solutions

Probably increase or remove the limit from the PHP code.

**Comment by alexander-schranz** [comment]
Thx for creating this issue, I could reproduce it on the sulu rocks demo. Not sure but could also be a problem in the Media Smart Content Provider in the collection selection.

**Comment by niklasnatter** [comment]
Thanks for reporting! Should be fixed with #5987 🙂
