### ISSUE TITLE
Enable pagination in admin page tree

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#6019]
# Problem description

We have a site with a lot of pages with multiple languages ( 22 in total ) and there is a bad performance in admin due to all pages are loaded ( more than 30 seconds sometimes ) 

# Proposed solution

Add a "Load more" in each tree to enhance performance, 20 items should be enough.

**Comment by wachterjohannes** [comment]
@plozmun which version of sulu do you use?

**Comment by plozmun** [comment]
> @plozmun which version of sulu do you use?

2.2.7

I know it's complicated because there are many fields in the node and a lot of children. It was a simple project at the beginning but the client wanted more and more pages 😅

**Comment by wachterjohannes** [comment]
@plozmun this is not a solution to the actual problem - but have you thought about the article bundle for some sections of your page?

**Comment by plozmun** [comment]
> @plozmun this is not a solution to the actual problem - but have you thought about the article bundle for some sections of your page?

Yes, I thought about it but I didn't know where the client is going to create the pages 😞

**Comment by plozmun** [comment]
@wachterjohannes Is it possible to migrate pages to articles?

**Comment by wachterjohannes** [comment]
@plozmun not out of the box :) but it would be quite easy to do that in a command

But we have another issue with performance which could be your problem too. Can you maybe comment out the code of the following function?

https://github.com/sulu/sulu/blob/d2f8f5c866af8ace7ba39b0b8fa5c2fba7bf3413/src/Sulu/Component/Content/Repository/ContentRepository.php#L455

**Comment by plozmun** [comment]
> @plozmun not out of the box :) but it would be quite easy to do that in a command
> 
> But we have another issue with performance which could be your problem too. Can you maybe comment out the code of the following function?
> 
> https://github.com/sulu/sulu/blob/d2f8f5c866af8ace7ba39b0b8fa5c2fba7bf3413/src/Sulu/Component/Content/Repository/ContentRepository.php#L455

Yes, I have overwritten that method to return an empty array and it improves performance.

**Comment by alexander-schranz** [comment]
@plozmun could then be similar to the following issue: https://github.com/sulu/sulu/issues/5935. We had this on our roadmap.

**Comment by plozmun** [comment]
Yes! Close this issue then to reduce noise. Thanks!

**Comment by alexander-schranz** [comment]
@plozmun Thx would be great if you subscribe the other issue and to test the performance in your case when we fix the issue.

**Comment by plozmun** [comment]
> @plozmun Thx would be great if you subscribe the other issue and to test the performance in your case when we fix the issue.

Done!
