### ISSUE TITLE
X-Default handling in meta and sitemap

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6027]
| Q | A
| --- | ---
| Sulu Version | 2.x 
| PHP Version | 
| DB Version | 
| Browser Version | 

# Actual Behavior

Currently the x-default doesn't work:

 - when the webspace configure url per locale (x-default is from language to language different)
 - when the default language does not exist the `x-default` should not be returned
 - to be discussed x-default should never be set as it is a international landingpage

# Expected Behavior

Correctly handling of x-default handling in meta and sitemap.

**Comment by plozmun** [comment]
Hi @alexander-schranz! 

In a recent project we have changed the ParameterResolver behavior to add a new parameter to localizations 
```php
            if (\array_key_exists($locale, $pageUrls)) {
                $url = $this->webspaceManager->findUrlByResourceLocator($pageUrls[$locale], null, $locale);
                $alternate = true;
            } else {
                $url = $this->webspaceManager->findUrlByResourceLocator('/', null, $locale);
                $alternate = false;
            }

            $localizations[$locale] = [
                'locale' => $locale,
                'url' => $url,
                'country' => $country,
                'alternate' => $alternate
            ];
```
Later in seo.html.twig 
```twig
    {%- if localizations|length > 1 -%}
        {% if defaultLocale and localizations[defaultLocale].alternate == true %}
            <link rel="alternate" href="{{ localizations[defaultLocale].url }}" hreflang="x-default"/>
        {% else %}
            <link rel="alternate" href="{{ localizations[app.request.locale].url }}" hreflang="x-default"/>
        {% endif %}
        {%- for localization in localizations -%}
            {%- if localization.alternate -%}
                <link rel="alternate" href="{{ localization.url }}" hreflang="{{ localization.locale|replace({'_': '-'}) }}"/>
            {%- endif -%}
        {%- endfor -%}
    {%- endif -%}
```

- If alternate exists it's added. 
- If default locale exists , it's added like x-default 

WDYT?

**Comment by alexander-schranz** [comment]
@plozmun Yes the `alternate` flag is something I also had in mind. In twig we maybe need to check if `alternate` is not defined it should handle like `alternate: true` for backward compatibility. The `x-default` is something we are currently waiting for feedback from our partners seo experts.

The `localizations` need also be adjusted then in the `TemplateAttributeResolver` which is used by other bundles controller: https://github.com/sulu/sulu/blob/98ad36fb9c7f401816a52138d88a75d68a3dee5a/src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php#L99

**Comment by alexander-schranz** [comment]
This is now fixed by following following pull requests and will be part of the next releases:

 - #6071
 - #6072
 - #6073
 - sulu/SuluArticleBundle#568
