### ISSUE TITLE
Add media properties to media admin

### ISSUE THREAD

**Issue by alexandersch** [sulu/sulu#6033]
# Problem description

The custom media properties are not visible in the media admin screen.

# Proposed solution

Something like a read only representation of the properties somewhere on the media admin screen.

**Comment by alexander-schranz** [comment]
The custom properties contains currently none content information but I think in some cases it would make sense to show them to the content manager. Example properties data are `width`, `height` for videos and images. Another example is saving `exif` data in the properties https://docs.sulu.io/en/latest/bundles/media/properties-provider.html#create-custom-properties-provider, this could be a  `camera_model` or `latitude/longitude` data of a image or video. But properties are at the end a whole `json` object and could contain objects not only simple text fields. 

I'm at current state not sure how we could find a general way to display all properties at current state I think you could give a try to `extend` the `media_details.xml` in your project with:

```xml
<?xml version="1.0" ?>
<form xmlns="http://schemas.sulu.io/template/template"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/form-1.0.xsd"
>
    <key>media_details</key>

    <properties>
       <section name="media_properties" colspan="12">
            <properties>
                <property name="properties/my_custom_property" type="text_line" disabledCondition="true">
                    <meta>
                        <title>sulu_admin.title</title>
                    </meta>
                </property>
            </properties>
        </section>
    </properties>
</form>
```

Maybe at current state this would be enough to display the property you want to show.

**Comment by alexandersch** [comment]
![image](https://user-images.githubusercontent.com/3180083/118004220-8e850980-b349-11eb-8caf-b9f301508850.png)
Seems to be working. Of course, more complex data would be difficult this way. But this will suffice for now!
