### ISSUE TITLE
Error displaying dropdown for header in ckeditor

### ISSUE THREAD

**Issue by rmatt-dev** [sulu/sulu#6051]
| Q | A
| --- | ---
| Sulu Version | 2.2.4
| PHP Version | 
| DB Version | 
| Browser Version | 

# Actual Behavior

The error is related to overflow-y for the dropdown header. It happens, if there's not enough space between the dropdown button and the bottom of the window.
![image](https://user-images.githubusercontent.com/84366300/118589247-4c702380-b7a0-11eb-9b41-aa69d0ed63fe.png)

If I turn off overflow-y: hidden for the selected element, everything is fine.
![image (1)](https://user-images.githubusercontent.com/84366300/118589323-70336980-b7a0-11eb-90e5-8920f60445aa.png)

# Expected Behavior
The drop-down list will show correctly.

**Comment by alexander-schranz** [comment]
Thx for reporting the issue. This is similar to #5938 I will have a look at it as it seems ckeditor did not responded to: https://github.com/ckeditor/ckeditor5/issues/9499

**Comment by niklasnatter** [comment]
Thanks a lot for reporting! Should be fixed in #6054
