### ISSUE TITLE
Display "add block" button between existing blocks

### ISSUE THREAD

**Issue by ymc-thzi** [sulu/sulu#6103]
Sometimes it is hard to find the right position via drag and drop for a newly added block especially if you had a lot of blocks and had to scroll while dragging.
Is the "add block" button configurable in some way (besides the new 2.3 attribs collapsable and movable)?

<img width="631" alt="Bildschirmfoto 2021-06-10 um 10 08 04" src="https://user-images.githubusercontent.com/1804472/121489854-c75de000-c9d4-11eb-86d4-c03bd7d372f0.png">

**Comment by alexander-schranz** [comment]
@ymc-thzi Thank you for creating this issue. The add button is currently not configurable, but we have in discussion that on `hover` between the blocks and also I think on the top in the grey area the button should appear automatically so a block can also be added between or at the top fast.

**Comment by niklasnatter** [comment]
This could be tackled together with https://github.com/sulu/sulu/issues/5836
