### ISSUE TITLE
Wrong exception when lang is configured on database but not in sulu_core

### ISSUE THREAD

**Issue by ehibes** [sulu/sulu#6106]
| Q | A
| --- | ---
| Sulu Version | 2.3
| PHP Version | 7.4
| DB Version | MariaDB
| Browser Version | Chrome

# Actual Behavior

Context : trying to update a 2.2 project to 2.3 project. When I update the database part, Sulu throws an exception : 
``` There is no Metadata available for the type "form" with the key "snippet". ```
This is because a lang is set on updated database (fr in my case), but currently not configured on sulu_core.

# Expected Behavior

**The app should not crash, or a better exception should be thrown.**

# Steps to Reproduce

Sulu 2.2 project with alternative lang configured in `sulu_core`. 
Make a 2.3 fresh install, link the 2.2 database, update it.

# Possible Solutions

Update `sulu_admin.yml` file, adding missing locale on `sulu_core` part. 
The exception is not thrown anymore.

**Comment by alexander-schranz** [comment]
@ehibes Thank you for creating this issue. We decided to add here a fallback to the default locale. It can be tested here #6108
