### ISSUE TITLE
Update shadow pages correctly in smartcontent

### ISSUE THREAD

**Issue by popoplanter** [sulu/sulu#6126]
| Q | A
| --- | ---
| Sulu Version | 1.6.40 
| PHP Version | 7.4
| DB Version | mysql 5.7 
| Browser Version | all 

# Actual Behavior

- Shadow pages are still counted in the pagination when created from a page that is in draft mode, therefore a wrong hasNextPage result will occur.

- When changing the title of a page, the shadow page does not update the information in the smart content and the sorting in the smart content gets messed up. For example: a page starts with the Letter A and a shadow page for it is created. Then the page title is changed to Letter Z. The shadow page shows the new name in the smart content but sorts by the old name (when sorting form A-Z appears on top but should be on the bottom).

# Expected Behavior

- hasNextPage should return true even if there are shadow pages that have not explicitly been saved on their own to update the published state.

- Shadow pages should update their title for sorting in smartcontent when their original page is changed.

**Comment by niklasnatter** [comment]
Thanks for creating this issue! I dont fully understand the following yet:

> Shadow pages are still counted in the pagination when created from a page that is in draft mode, therefore a wrong hasNextPage result will occur.

This is a scenario where the shadow locale itself is published but the target locale is not, right? In this case, the `hasNextPage` acts like the shadow page is included in the result but the result itself does not include it?

**Comment by niklasnatter** [comment]
@C-burr I remember that we talked about this but I am not sure if we found a solution. Is this still a problem? 🤔

**Comment by popoplanter** [comment]
@nnatter i dont think we found a solution for it, i just saved the affected shadow pages to fix the issue. But this problem could occur again

**Comment by niklasnatter** [comment]
I am going to close this as we cannot really do anything about it without being able to reproduce it. Please feel free to create a new issue if you can reproduce the problem!
