### ISSUE TITLE
Unable to navigate to other pages after deleting all entries of one page in a list (e.g. snippets)

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#6140]
| Q | A
| --- | ---
| Sulu Version | 2.3.1
| PHP Version | 7.4.16
| DB Version | 5.7.32
| Browser Version | Chrome 91.0.4472.114

# Actual Behavior

After deleting all items of a page in a list view (e.g. snippets) the pagination navigation is not shown any more:

<img width="1245" alt="snippets-deleted" src="https://user-images.githubusercontent.com/5627878/124275603-0c43e500-db43-11eb-924e-203c79b067aa.png">

The pagination navigation is shown again after a refresh of the page:

<img width="1247" alt="snippets-reload" src="https://user-images.githubusercontent.com/5627878/124275700-30072b00-db43-11eb-8508-073b3055f621.png">

# Expected Behavior

The pagination toolbar should be shown after deleting all items of a page. It would be nice if not only the toolbar is shown but if remaining items from another page would be shown. E.g. if I delete all items from page 1 I want to see all items of page 2 afterwards.

# Steps to Reproduce

1. Create 11 snippets.
2. Use the checkbox in the table header of the list to select all 10 items of the first page.
3. Delete the snippets.
4. The pagination navigation ist not visible any more and also the remaining 1 snippet is not shown.

**Comment by remdan** [comment]
It also happens in the media list.

My expected behavior: After delete items, it should refill the items per page and update the pagination... not only after deleting all items one time...

**Comment by niklasnatter** [comment]
Thanks for reporting! Should be fixed in #6168 and will be included in the upcoming 2.2.12 and 2.3.2 release 🙂
