### ISSUE TITLE
Page template is not refreshed when switching locales in the Sulu admin

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#6145]
| Q | A
| --- | ---
| Sulu Version | 2.3.1
| PHP Version | 7.4.16
| DB Version | MySQL 5.7.32
| Browser Version | 91.0.4472.114

# Actual Behavior

The page template is not refreshed after switching locales when editing a page in the Sulu admin. This leads also to a strange behavior, where the content saved in blocks is not refreshed correctly when switching the locale.

# Expected Behavior

The page template and all contents should be refreshed correctly when switching locales on pages in the Sulu admin.

# Steps to Reproduce

1. Create a new page in the Sulu admin for `en` with template `Default`.
2. Switch to `de` on this page and select `Yes` when you are asked to choose the language.
3. Change the template for `de` from `Default` to `Overview` and save the page.
4. Switch back to `en` on this page. The selected template is still `Overview` although it should be `Default` for `en`.

Note: Reloading the page solves the problem.

**Comment by alexander-schranz** [comment]
I test it and it seems like this issues does also exist in older versions (2.2.2 and 2.2.11) so atleast it has not todo with our latest refractorings in the ResourceFormStore, still this issue should be fixed, that the correct template metadata data is used.

**Comment by niklasnatter** [comment]
Thanks for reporting! Should be fixed in #6168 and will be included in the upcoming 2.2.12 and 2.3.2 release 🙂
