### ISSUE TITLE
Pressing enter does not work when switching pages in lists (e.g. snippets)

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#6148]
| Q | A
| --- | ---
| Sulu Version | 2.3.1
| PHP Version | 7.4.16
| DB Version | MySQL 5.7.32
| Browser Version | 91.0.4472.114

# Actual Behavior

Pressing enter in the input field for the page number in the pagination navigation for lists does not change the page. The page is changed after clicking somewhere outside the input field.

<img width="278" alt="pagination" src="https://user-images.githubusercontent.com/5627878/124949913-436a3880-e012-11eb-8741-42b31ef440bf.png">

# Expected Behavior

The page should also be changed when enter is hit.

# Steps to Reproduce

1. Go to a list with 11 items (e.g. snippets).
2. Change the page number in the input field to 2 and hit enter - nothing happens.
3. Clicking outside the input or leaving the field in any other way (e.g. with tab) will change the page.

**Comment by luca-rath** [comment]
Fixed by #6167, will be released as 2.2.12 and 2.3.2
