### ISSUE TITLE
media items reload per page after batch delete

### ISSUE THREAD

**Issue by remdan** [sulu/sulu#6154]
| Q | A
| --- | ---
| Sulu Version | 2.3.1
| PHP Version | 7.4.16
| DB Version | MySQL 5.7.35
| Browser Version | Firefox 89.0.2

# Actual Behavior
I'm in a media folder with more than 100 items.
It shows me 10 items per page on default.
If I select one or more items and delete them, then there is no reload like a refill until the page maximum is reached.
Also, if I select and delete all, in my example all 10 items, pagination disappears! So I have to do a page reload.

# Expected Behavior

After the batch delete, it should also refill the items per page and update the pagination.
Maybe a site reload is easier!? what happen on a error with the message...

# Steps to Reproduce

![Bildschirmfoto 2021-07-15 um 18 43 28](https://user-images.githubusercontent.com/5031692/125825781-c5c70d5e-b39f-4ed4-81cf-e2c39f03454f.png)

**Comment by alexander-schranz** [comment]
@remdan Seems like for its the same issue as described here: https://github.com/sulu/sulu/issues/6140 or do I understand it not correctly?

**Comment by remdan** [comment]
> @remdan Seems like for its the same issue as described here: #6140 or do I understand it not correctly?

Yes, looks like this behavior exist in every list!

**Comment by alexander-schranz** [comment]
I will close then this issue in favor of #6140 to avoid here duplicated issues, please subscribe #6140 and add there maybe additional information if you want.
