### ISSUE TITLE
xi:include fails inside recursive xi:include

### ISSUE THREAD

**Issue by R3dLantern** [sulu/sulu#6173]
| Q                  | A
| ------------- | ---
| Sulu version | 2.3.1
| PHP version | 8.0.9
| DB version | MySQL 10.4.12-MariaDB
| Browser | Google Chrome 64-bit 92.0.4515.107

XML schema validation fails if the `xi:include` structure is too complex.
When using a recursive inclusion, e.g.
```xml
<properties xmlns="http://schemas.sulu.io/template/template"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xi="http://www.w3.org/2001/XInclude"
            xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/properties-1.0.xsd">
  <block name="foo">
    <types>
      <type name="primary">
         <properties>
             <property name="foo"/>
         </properties>
      </type>
      <type name="secondary">
         <properties>
           <xi:include xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)
                                 xpointer(//sulu:block[@name='foo']/sulu:properties/*)"/>
         </properties>
       </type>
     </types>
  </block>
</properties
```
an underlying `xi:include` will not be resolved:
```xml
<properties xmlns="http://schemas.sulu.io/template/template"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xi="http://www.w3.org/2001/XInclude"
            xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/properties-1.0.xsd">
  <block name="foo">
    <types>
      <type name="primary">
         <properties>
             <xi:include href="./somewhere/else.xml"
                         xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)
                                   xpointer(//sulu:property[@name='foo'])"/>
         </properties>
      </type>
      <type name="secondary">
         <properties>
           <xi:include xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)
                                 xpointer(//sulu:block[@name='foo']/sulu:properties/*)"/>
         </properties>
       </type>
     </types>
  </block>
</properties
```
which in turn throws a validation exception in `XmlUtils::parse`:
```
[ERROR 1871] Element '{http://www.w3.org/2001/XInclude}include': This element is not expected. (in /path/to/base/file.xml - line ???, column 0)
```

Is this a problem with Sulu?

**Comment by alexander-schranz** [comment]
Hello @scarcloud,

I don't think you can xi:include recursively this would end in an endless loop. But you can xinclude inside an xinclude.

See as example the demo:

 - https://github.com/sulu/sulu-demo/blob/master/config/templates/pages/homepage.xml#L80-L81
 - https://github.com/sulu/sulu-demo/blob/38b3cecf8efa919aa38f92c9a243d3fe75a6bf69/config/templates/includes/blocks.xml#L16
 
 But you still need to avoid to create a loop.

**Comment by alexander-schranz** [comment]
Because on inactivity I will close this issue. For completness I add here links to the official xinclude docs as this methods are provided by PHP directly and are not sulu specific:

 - PHP Docs: https://www.php.net/manual/de/domdocument.xinclude.php
 - Xinclude Specification: https://www.w3.org/TR/xinclude/
