### ISSUE TITLE
Settings tab of pages does not work (due to JS error)

### ISSUE THREAD

**Issue by wimvds** [sulu/sulu#6179]
| Q | A
| --- | ---
| Sulu Version | 2.2.12 & 2.3.2
| PHP Version | 7.4.22
| DB Version | MySQL 5.7.33 
| Browser Version | Firefox 91.0

# Actual Behavior

The Settings tab of pages does not work. In the JS console we see a the following error :
`Uncaught (in promise) Error: The "page_settings" configuration does not support types, but a type of "default" was given`
(in metadataStore.js:79:18)

# Expected Behavior

A working settings tab ;p

# Steps to Reproduce

You can check the issue on the current demo site, as it seems to be affecting Sulu 2.3.2 as well :
https://sulu.rocks/admin/#/webspaces/demo/pages/en/522bdd49-5cbe-4108-ba2c-d0fa80c6bf62/settings

# Possible Solutions

We downgraded to Sulu 2.2.11 for now, as the issue does not seem to appear there.

**Comment by alexander-schranz** [comment]
Thank you for reporting. I tested it and I can reproduce it, it seems like it have todo with the changes in https://github.com/sulu/sulu/pull/6169. We will have a look at it.

**Comment by niklasnatter** [comment]
Thanks for reporting! I am sorry to say that this is a bug in the new version indeed. For the moment, downgrading to `2.2.11` and updating the administration build with the `bin/adminconsole sulu:admin:update-build` command should make the error disappear.

We are working on a fix and I hope that we can release a new version without the problem soon! 🙂

**Comment by alexander-schranz** [comment]
This is fixed in #6180 and released in [2.2.13](https://github.com/sulu/sulu/releases/tag/2.2.13) and [2.3.3](https://github.com/sulu/sulu/releases/tag/2.3.3).
