### ISSUE TITLE
The "page_excerpt" configuration does not support types, but a type of "default" was given

### ISSUE THREAD

**Issue by almare** [sulu/sulu#6181]
| Q | A
| --- | ---
| Sulu Version | 2.3.2
| PHP Version | 8.04
| DB Version | MARIADB 10.3.31
| Browser Version | Firefox 91

# Actual Behavior
After updating to latest Sulu version incl. the following Bundles (Article, Form, Automatation, SuluMegamenu, Theme,Redirect) I receive this error if I try to open the excerpt, seo or settings page of each page and article. I had also custom config/forms/(page_block_settings.xml, ...) I removed them completely during my tests, but without success.

` Uncaught (in promise) Error: The "page_excerpt" configuration does not support types, but a type of "default" was given`
or
`Uncaught (in promise) Error: The "page_seo" configuration does not support types, but a type of "default" was given`

I have also custom pages like my home page. In this case the error looks like this.

` Uncaught (in promise) Error: The "page_excerpt" configuration does not support types, but a type of "homepage" was given`

At the moment I just see the loading indicator and I am not able to edit my articles and pages anymore.

# Expected Behavior

Sulu should open again the seo, settings and excerpt forms.

# Steps to Reproduce
Due to the customizations like different bundles which the most people using it's hard to find out if a bundle is causing this behaviour. 

# Possible Solutions
Hopefully you got an idea what is causing this error for fixing or a deeper test to find a solution

**Comment by alexander-schranz** [comment]
@almare Thank you for reporting, this issue is similar to #6179. We are already working on a fix: #6180. Will close this in favor of #6179

**Comment by almare** [comment]
Oh, sorry! I didn't see that issue. Thx
