### ISSUE TITLE
after live,image not upload mime type error

### ISSUE THREAD

**Issue by dilipom13** [sulu/sulu#6202]
| Q | A
| --- | ---
| Sulu Version | 
| PHP Version | 
| DB Version | 
| Browser Version | 

# Actual Behavior

# Expected Behavior

# Steps to Reproduce

# Possible Solutions

**Comment by dilipom13** [comment]
Hello Sir,

https://prnt.sc/1qtg47a

**error** : **Unable to guess the MIME type as no guessers are available (have you enabled the php_fileinfo extension?).**

I face above error, I add the 'extension = fileinfo' and 'extension=php_fileinfo.dll' in php.ini (in cPanel).
but can't resolve this error, please help me.

**Comment by niklasnatter** [comment]
Are you sure that the `php_fileinfo` extension is enabled? What is the output of `phpinfo()`?
https://www.php.net/manual/de/function.phpinfo.php

**Comment by dilipom13** [comment]
> Are you sure that the `php_fileinfo` extension is enabled? What is the output of `phpinfo()`?
> https://www.php.net/manual/de/function.phpinfo.php

this issue is fixed.
yes you write php_fileinfo was not enabled, but now it's working fine.

Thank you @nnatter

**Comment by niklasnatter** [comment]
Alright - thats good to hear! 🙂
