### ISSUE TITLE
The requested URL was not found on this server.

### ISSUE THREAD

**Issue by dilipom13** [sulu/sulu#6204]
| Q | A
| --- | ---
| Sulu Version | 
| PHP Version | 
| DB Version | 
| Browser Version | 

# Actual Behavior

# Expected Behavior

# Steps to Reproduce

# Possible Solutions

**Comment by niklasnatter** [comment]
Please fill out issue template when creating a new issue. Unfortunately, we are not able to help you with this amount of information.

**Comment by dilipom13** [comment]
> Please fill out issue template when creating a new issue. Unfortunately, we are not able to help you with this amount of information.

my issue is , i have uploaded one demo project in cPanel (upload in subfolder).
it's working fine in localhost.
 project url : - **https://xxx/projects/my-lara-project/**
      
when i click on delete the record, popup will open, after i click on 'yes' link, delete is not working and redirect on bellow url:
     
     https://xxx/categories/11

    how can i manage ? i have no idea. because i am new in lavarel.
i change my self in .env file. confing/app.php file. but can't solve it.

please guide me.

**Comment by wachterjohannes** [comment]
@dilipom13 are you sure you are in the right repository? Seems you have a problem with laravel? sulu is a projekt which is built ontop of symfony and not ontop of laravel :) if i am wrong feel free to add more informations :)
