### ISSUE TITLE
PageController should handle `types` request param in list action

### ISSUE THREAD

**Issue by luca-rath** [sulu/sulu#6235]
# Problem description

The `PageController::cgetAction()` should take the `types` request param into account to allow defining types in `page_selection` and `single_page_selection` properties

# Proposed solution

Implement similar to `SnippetController::cgetAction()`

**Comment by niklasnatter** [comment]
I feel like the tree structure of the page tree makes it hard to implement this in a intuitive manner. For example, there might be a parent page of the wrong type that has child pages with the correct type. In this case, we still need to display the parent page (even if it has the wrong type) to let the user navigate to the child pages.

I think the more intuitive solution for restricting the selection to specific templates is to use the `item_disabled_condition` param:
```xml
<property name="page_selection" type="page_selection">
    <params>
        <param name="item_disabled_condition" value="template != 'expected-template-key'"/>
    </params>
</property>
```

**Comment by luca-rath** [comment]
you're right, seems to be a good solutions 👍
