### ISSUE TITLE
Wrong localization for location selection de lat/lang

### ISSUE THREAD

**Issue by Skullfox** [sulu/sulu#6237]
| Q | A
| --- | ---
| Sulu Version | 2.0.0+

# Actual Behavior

Wrong Lat/Lang translation in Location Bundle for DE.

# Expected Behavior

Correct translation

# Steps to Reproduce

Insert Lat/Lang in DE based on input title ->  wrong location 

# Possible Solutions

Fix localization lat lang for DE
`/src/Sulu/Bundle/LocationBundle/Resources/translations/admin.de.json`
```
    "sulu_location.latitude": "Breitengrad",
    "sulu_location.longitude": "Längengrad"
```

**Comment by Prokyonn** [comment]
Fixed by https://github.com/sulu/sulu/pull/6244, released as 2.2.15 and 2.3.5
