### ISSUE TITLE
Performance issue in the admin media area

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#6238]
| Q | A
| --- | ---
| Sulu Version | 2.3.1
| PHP Version | 7.4.22
| DB Version | 5.7.32
| Browser Version | All

# Actual Behavior

Loading the media area in the Sulu admin is really slow since our last update to Sulu 2.3.1 in a project with ~14.000 files. According to the profiler the request to `/admin/api/media?page=1&locale=de&fields=thumbnails,type,name,size,mimeType,title,id&limit=10&flat=true` results in at least one really slow query:

![profiler](https://user-images.githubusercontent.com/5627878/134192541-89f61389-25d6-40de-8d2f-0ad379a2c623.png)

Running the following query takes approx. 25 seconds:

```
SELECT m0_.id AS id_0, m0_.created AS created_1 
FROM me_media m0_ 
LEFT JOIN me_collections m1_ ON m0_.idCollections = m1_.id 
LEFT JOIN se_access_controls s2_ ON (s2_.entityClass = 'Sulu\\Bundle\\MediaBundle\\Entity\\Collection' AND CAST(s2_.entityId AS char) = CAST(m1_.id AS char) AND s2_.idRoles IN (SELECT s3_.id FROM se_roles s3_ WHERE s3_.securitySystem = 'Sulu')) 
LEFT JOIN se_roles s4_ ON s2_.idRoles = s4_.id 
WHERE ((s2_.permissions & 64) = 64 OR s2_.permissions IS NULL) AND (s4_.id IN (1, 2) OR s4_.id IS NULL) 
ORDER BY created_1 DESC 
LIMIT 10;
```

After a hint from @alexander-schranz I added a new column with type integer to the table `su_access_controls` and added the `entity_id` casted to an integer to it (`UPDATE se_access_controls SET entityIdInt = CAST(entityId AS SIGNED);`). Running the query from above again without the casts and with the new column `entityIdInt` the query takes ~10 seconds. After adding an index to the new column the result is available in only a few milliseconds.

This does maybe not only affect the media area but also other parts of Sulu.

**Comment by niklasnatter** [comment]
Thanks for reporting! This should be fixed in #6250
