### ISSUE TITLE
Long webspaces dropdown flows out of screen and is not scrollable

### ISSUE THREAD

**Issue by arwinstratingws** [sulu/sulu#6257]
| Q | A
| --- | ---
| Sulu Version | 2.3
| PHP Version | 8.0.10
| DB Version | MySQL 5.7.35
| Browser Version | Chrome 93.0.4577.82

# Actual Behavior

When alot of webspaces are present, the webspace selection dropdown in the admin portal overflows the viewport and is not scrollable when this happens. This results in not being able to select the webspaces in the list that are rendered outside of the viewport.

# Expected Behavior

When the list of webspaces is longer/higher than the screen height it is expected that the dropdown list becomes scrollable so that the user is still able to select all webspaces.

# Steps to Reproduce

View the admin portal on a small screen size or fill enough webspaces for the dropdown to overflow the viewport.

# Possible Solutions

The webspaces dropdown should have a fixed max-height in order for the overflow styling to take effect. Either this or the parent of the popover needs to have a height set so the popover can have a relative height to the parent set (e.g. 80%).

The component in question is the ArrowMenu which is used by the WebspaceSelect component within the AdminBundle.

**Comment by alexander-schranz** [comment]
@arwinstratingws Thanks for the report. This should really not happen and a max height should be there with scrollbars.
How many webspace do you have? We currently have a design also that there will be a search box to search for specific webspace but it is not yet implemented.

**Comment by arwinstratingws** [comment]
@alexander-schranz Thanks for the quick response! 

We currently have 26 webspaces which is enough for this issue to occur on smaller screens. 

The new design idea of including a search box sounds like a good addition to larger lists, even when scrollable :)

**Comment by niklasnatter** [comment]
Thanks for reporting this! Could you create a pull request for limiting the height of the dropdown?

**Comment by alexander-schranz** [comment]
This is fixed by #6276. Thx for report.
