### ISSUE TITLE
Get Snippet uuid from Snippet Content Type 

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#626]
In some cases you need the uuid from a snippet to send it to a controller. Currently you only get the snippet content.

**Comment by danrot** [comment]
Doesn't `snippet.uuid` work?

**Comment by danrot** [comment]
And it should also be in the `view`-variable

**Comment by alexander-schranz** [comment]
`content.snippet` only returns me the fields in the snippet:

![bildschirmfoto 2015-02-16 um 10 54 18](https://cloud.githubusercontent.com/assets/1698337/6209881/7aac5298-b5ca-11e4-8166-ecb6b35086d5.png)

`view.snippet` only the view-variables of the fields in the snippet:
![bildschirmfoto 2015-02-16 um 10 54 41](https://cloud.githubusercontent.com/assets/1698337/6209895/95f300ba-b5ca-11e4-9e24-3788c9e3f9f5.png)

currently no uuid is returned

**Comment by danrot** [comment]
Ok, so the `view`-variable contains the wrong values. `view.snippet` should IMHO just contain the snippet ids

**Comment by alexander-schranz** [comment]
i think you only need to add the `view.snippet[0].uuid` the others e.g. like `view.snippet[0].main_image.displayOption` you also need.

**Comment by thomasduenser** [comment]
I've just had the same problem, would be nice to have this possibilityin a future version.

**Comment by danrot** [comment]
Ah, that issue also just came up in a project from @janmassive, the fix would be quite easy (the `getViewData` of the `SnippetContent` is exactly the same as `getContentData`, which is obviously wrong).

**Comment by wachterjohannes** [comment]
hmm for me the resulting structure should be:

```
content.snippets[].view[property-name] // should contain the view data of the property
content.snippets[].content[property-name] // should contain the content data of the property

view.snippets // should contain the uuids of selected snippets
```

This would be a BC-Break but necessary otherwise we lose a lot of informations.

/cc @berndhep should we fix that for 1.1 or later?

**Comment by berndhep** [comment]
@wachterjohannes 1.2

**Comment by danrot** [comment]
I think that's a huge bc break, and not really developer friendly to use...

what about something like this:

```
content.snippets[uuid].property-name
view.snippets[uuid].property-name
```

I guess people are looping over values anyway, and do not directly access them using the indexes (except when cross-referencing from `content` to `view`). So I think we could make use of the indexes.

**Comment by wachterjohannes** [comment]
but there i see another problem: if you are only want to access the first item (because there is no single select) then i think you would use `[0]` that wouldn't work then and it would be not that easy to get the first element ...

**Comment by danrot** [comment]
There is still the `first` filter in twig, which IMO should be preferred for this purpose, since it also works with different data structures, and probably also handles the empty case.

**Comment by wachterjohannes** [comment]
hmm ok that sounds good ... but i would prefer the "bigger" structure because its consistent ...

**Comment by danrot** [comment]
Having another `view` and `content` variables in the `content` variable is worse for me, since the entire splitting on the root level doesn't make any sense for me. That's why the second approach is even more consistent for me.

**Comment by alexander-schranz** [comment]
@danrot closing this issue as the snippet uuid is available under `view.snippets[0].uuid`

**Comment by lubomirfiala** [comment]
I would like to reopen this issue. The uuid of snippet is available under view, but if you have a lot of nested blocks, it is very unpractical (and possibly dangerous) to search for it.

**Comment by alexander-schranz** [comment]
@lubomirfiala dont think we will change in the block structure much so I really recommend always give content and view to your twig files never just content, things like displayOptions are also stored there for smart contents media selections.

See sulu demo how to handle it:

https://github.com/sulu/sulu-demo/blob/8a66e447ecb2729afd99d702c0d31409e8d1dbf7/templates/includes/blocks.html.twig#L7
