### ISSUE TITLE
Saving pages with snippets in blocks fails

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#6272]
| Q | A
| --- | ---
| Sulu Version | 2.3.5
| PHP Version | 8.0
| DB Version | Mysql 
| Browser Version | All

# Actual Behavior

Saving pages with snippets in blocks fails. It's seems that recently changes in StructureProvider cause this error:

```
        In FieldEvaluator.php line 64:
                                                                                   
          [TypeError]                                                              
          get_class(): Argument #1 ($object) must be of type object, string given  
                                                                                   
        
        Exception trace:
          at /vendor/massive/search-bundle/Search/Metadata/FieldEvaluator.php:64
         Massive\Bundle\SearchBundle\Search\Metadata\FieldEvaluator->getValue() at /vendor/massive/search-bundle/Search/ObjectToDocumentConverter.php:166
         Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter->populateDocument() at /vendor/massive/search-bundle/Search/ObjectToDocumentConverter.php:177
         Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter->populateDocument() at /vendor/massive/search-bundle/Search/ObjectToDocumentConverter.php:177
         Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter->populateDocument() at /vendor/massive/search-bundle/Search/ObjectToDocumentConverter.php:113
         Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter->objectToDocument() at /vendor/massive/search-bundle/Search/SearchManager.php:167
         Massive\Bundle\SearchBundle\Search\SearchManager->index() at /vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Search/EventSubscriber/StructureSubscriber.php:108
         Sulu\Bundle\PageBundle\Search\EventSubscriber\StructureSubscriber->indexDocument() at /vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Search/EventSubscriber/StructureSubscriber.php:60
         Sulu\Bundle\PageBundle\Search\EventSubscriber\StructureSubscriber->indexPersistedDocument() at /vendor/symfony/event-dispatcher/EventDispatcher.php:230
         Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /vendor/symfony/event-dispatcher/EventDispatcher.php:59
         Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /vendor/sulu/sulu/src/Sulu/Component/DocumentManager/DocumentManager.php:58
```

# Steps to Reproduce

Create nested blocks with references to snippets, and try to save

# Possible Solutions

I have changed this line and  it's solve the error but i don't know if this is correct https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/PageBundle/Search/Metadata/StructureProvider.php#L317 to 
```
 $componentProperty->getName() . '_'
```

**Comment by niklasnatter** [comment]
Hey, thanks for reaching out!
I tried to reproduce the error, but was not able to yet. Could you provide a page template to reproduce the problem?

**Comment by plozmun** [comment]
Hi @nnatter . I've created a small reproducer from sulu demo. It's strange because only occurs when 2 blocks are envolved.

You have to create 11M an 4M blocks to see the error.

This is the branch https://github.com/plozmun/sulu-demo/tree/structure-provider-reproducer

**Comment by niklasnatter** [comment]
Thank you - I was able to reproduce the error! The problem in your case is that your `04M-testimonial` type has a `items` property with the type `snippet_selection` and the `11M-numbers` type has a `items` property that is a nested block.
This causes an error because the data of the `snippet_selection` is treated as "nested block data" when indexing the page.
I have created a new issue that explains the problem: https://github.com/sulu/sulu/issues/6277

Unfortunately, I am not sure how to properly fix this yet. I think this will need some additional logic for handling different block types, but the `MassiveSearchBundle` does not support anything like this as far as i know 😕  
As a workaround, you can rename one of your properties to prevent the problem at the moment.

**Comment by plozmun** [comment]
Thanks @nnatter . I had tried that solution but the problem is that this site is in production already 😞  . I don't know if exists any solution to migrate that content.

**Comment by niklasnatter** [comment]
I think you should be able to migrate the data using a PHPCR migration: https://docs.sulu.io/en/2.3/cookbook/migrate-content-data.html
I am aware that this is a bit of work when dealing with nested blocks, but I cant think of another workaround at the moment. I am sorry for the inconveniences 😕

**Comment by niklasnatter** [comment]
@plozmun We came up with a fix that can be implemented in the next Sulu release and would solve the problem in your case (see #6281). I think I would recommend to keep the project on `2.3.4` until we are able to release `2.3.6` 🙂

**Comment by plozmun** [comment]
Yeah! It works 

I've been researching the same thing but I haven't been able to solve it. 😅
