### ISSUE TITLE
Search controller does not have localizations

### ISSUE THREAD

**Issue by speex404** [sulu/sulu#6274]
| Q | A
| --- | ---
| Sulu Version | 2.3.1 / 2.3.2 / 2.3.5
| PHP Version | 8.0.9
| DB Version | MySQL 8.0.23 
| Browser Version | 93.0.45 

# Actual Behavior

If you dump the variables you get a localizations array, containing links to the current page in all languages. This can be used e.g. for a language switcher.
However, on the search page the urls of the array are just pointing to the start page.

# Expected Behavior

The localizations array should be accessible on the search page, containing at least the locale and url for each item (locale).

# Steps to Reproduce

Setup a clean sulu project.
Add different localizations to some pages in the admin backend
Add `{{ dump() }}` to the base.html.twig file
Open some of the frontend pages and check the localizations array
Open the search page and check the localizations array

**Comment by niklasnatter** [comment]
Thank you for reaching out!

As far as I know, the url in the `localizations` variable does not include query parameters at the moment. 
Would you expect the variable to contain the query parameters on the search page?
Should they also be included on other pages?

**Comment by speex404** [comment]
Yes, I would expect that the locale URL is used and the parameter is simply left as it is.

So that i can e.g. search for an article, change the language and then get results for my search term in the appropriate language.

**Comment by niklasnatter** [comment]
I have created a pull request to pass the correct `localizations` attribute to the twig template: https://github.com/sulu/sulu/pull/6283

The pull request will not add the query parameters to the urls in the `localizations` attribute. I think the behaviour should be consistent with the `localizations` attribute for pages which does not contain query parameters too. If you want to add the query parameters in your language switcher, you can use `app.request.queryString` to access the current query parameters in your twig template 🙂

**Comment by niklasnatter** [comment]
Fixed in #6283
