### ISSUE TITLE
Disable Default Security Checker

### ISSUE THREAD

**Issue by RSalo** [sulu/sulu#6314]
| Q | A
| --- | ---
| Sulu Version | 2.3.6 
| PHP Version | ~ 
| DB Version | ~ 
| Browser Version | ~ 

# Actual Behavior

`  The service "sulu_admin.admin_pool" has a dependency on a non-existent service "sulu_security.security_checker". Did you mean this: "sulu_security.security_context_voter"?`

# Expected Behavior

Should load Symfony Authorization Checker without exception.

# Steps to Reproduce

```
sulu_security:
  checker: false
```

# Possible Solutions

SecurityChecker should use AuthorizationCheckerInterface with isGranted method to be compatible with Symfony security checker when it's disabled.

**Comment by alexander-schranz** [comment]
Thank you for creating an issue. Services which use the `sulu_security.security_checker` requires that the `checker: false` else they should be avoided to be registered. In the future the checker will always be available when SecurityBundle is there. This is currently an option which is part of the current 2 Kernel Setup which we are working to get rid of. The security checker itself is different to the AuthorizationCheckerInterface and so it is its own Interface.
If you have a service like a `Admin` class you can currently mark it with sulu.context admin so its not loaded in the website context:

```yaml
services:
    App\Admin\:
        resource: '../src/Admin'
        tags: [{name: 'sulu.context', context: 'admin'}]
```

If this does not work for you let us know more about your use case and problem you did get into it to better understand which type of service you are trying to create with the security checker and where it makes problems.

**Comment by RSalo** [comment]
Thanks a lot! There is no problem for me to redefine new services with my needs. Just found out strange checker behavior and created an issue. Close this one if similar exists already.

**Comment by alexander-schranz** [comment]
In which type of services are you currently using the checker?

**Comment by RSalo** [comment]
ACL and voters tree wherein use decision which depends on inner voter constant. If I correctly understand the question.

**Comment by alexander-schranz** [comment]
If the voter is only admin specific you can as above register it only in the admin context with `sulu.context` tag. You can also inject the security checker optionally with:

```php
?SecurityCheckerInterface $securityChecker = null
```

And then go with:

```php
if (!$this->securitChecker) {
     return self::ACCESS_ABSTAIN;
}
```

Still as said above its more because of the 2 Kernel Setup that the `checker: true|false` option exist and we work to get rid of the 2 Kernel Setup so in future the security checker should be available always when the SecurityBundle is registered.

Thx for your response and provide an example where you use it.

**Comment by RSalo** [comment]
Yeap, I did something like that. Thanks again. That was very informative!

**Comment by alexander-schranz** [comment]
Thx for your responses and feedback. I will close this issue and hope with getting rid of the 2 Kernel Setup we will get ride of this kind of problems. If you have still any problems feel free to add a comment here, create a new issue or use our [slack channel](https://sulu.io/services-and-support#chat) to ask further questions.

**Comment by lesmyrmidons** [comment]
Hello !
I upgrade a project sulu 2.5 to 2.6 and I get the same error message, except that on this project I didn't add an extension to the admin.

What you said above about changing the context doesn't work because I don't have a folder `../src/Admin`.

How can I solve the problem?

**Comment by alexander-schranz** [comment]
@lesmyrmidons you sure that you run into same issue with the security checker? Sure its not another configuration service in your case?

**Comment by lesmyrmidons** [comment]
Yes, I just apply a config in composer.json on skeleton sulu of upgrade version Sulu and Symfony.
After run comand `composer update`

At one time, a cache:clear, return this error :
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 116:
                                                                                                                                                                               
  The service "sulu_admin.admin_pool" has a dependency on a non-existent service "sulu_security.security_checker". Did you mean this: "sulu_security.security_context_voter"?
```
to delete the previous messages, I added  this config :
```
sulu_security:
   checker: true
 ```
 Now I have this message :
 ```
 The service "sulu_admin.admin_pool" has a dependency on a non-existent service "sulu_reference.reference_list_view_builder_factory".
 ```

The bundle added:
- SuluFormBundle

**Comment by alexander-schranz** [comment]
@lesmyrmidons Go to your [config/bundles.php](https://github.com/sulu/skeleton/blob/db28153f8f9a334f5199c5e23eb39af35ceafd2a/config/bundles.php#L16)

And update it like you see in the skeleton:

```diff
-    Sulu\Bundle\AdminBundle\SuluAdminBundle::class => ['all' => true, 'admin' => true],
+    Sulu\Bundle\AdminBundle\SuluAdminBundle::class => ['all' => true],
```

When running into such issues sometimes good to check the skeleton files directly: https://github.com/sulu/skeleton. It contains all changes including the one for latest Symfony versions to support.

**Comment by lesmyrmidons** [comment]
Yes, I've already changed this configuration as well as all the yaml config.

**Comment by alexander-schranz** [comment]
Then its strange did you follow all steps of the `UPGRADE.md` file? https://github.com/sulu/sulu/blob/2.6/UPGRADE.md#new-required-bundle 

if that still doesn't work please try to create a reproducable repository based on the `sulu/skeleton`.

**Comment by lesmyrmidons** [comment]
Oh ! My bad, I missed the change to CmfRoutingBundle and SuluReferenceBundle.
It's good now

**Comment by nickvanderzwet** [comment]
If you still run into this problem, a solutions might be to add https://github.com/sulu/skeleton/blob/2.6/config/packages/sulu_security.yaml into your project
