### ISSUE TITLE
Admin Texteditor Parameters from 1.6 don't work in Sulu 2.x

### ISSUE THREAD

**Issue by ampaze** [sulu/sulu#6346]
| Q | A
| --- | ---
| Sulu Version | 2.x

# Actual Behavior

With

```xml
<property name="html" type="text_editor">
    <meta>
        <title lang="de">HTML</title>
    </meta>
    <params>
        <param name="table" value="false"/>
        <param name="paste_from_word" value="true" />
    </params>
    <tag name="sulu.search.field"/>
</property>
```

the parameters are ignored or don't work.

While they are no longer mentioned in the documentation (compare [1.6](https://docs.sulu.io/en/1.6/reference/content-types/text_editor.html) and [2.3](https://docs.sulu.io/en/2.3/reference/content-types/text_editor.html)); there is also no mentioned what happened to them or what to do when upgrading.

https://docs.sulu.io/en/2.3/upgrades/upgrade-1.6-2.0.html
https://github.com/sulu/sulu/blob/2.x/UPGRADE.md

# Expected Behavior

How can the CKEditor Toolbar be modified? How to disabled the table button? What happened to `paste_from_word`?

**Comment by alexander-schranz** [comment]
This plugins for table and for paste_from_word are in Sulu 2.0 enabled always enabled and can not longer be disabled. The CKEditor 5 works different to the 4, if you want to modify it have a look at the https://jsdocs.sulu.io or example [demo pull request](https://github.com/sulu/sulu-demo/pull/77). We normally recommend to stay with the default editor and not modify it, as a normal sulu installation should not have the need for building a custom JS adminb uild. If you want to add something to the UPGRADE.md file feel free to create a Pull Request to add something there.
Provide different ckeditor settings are discussed in the following issue: https://github.com/sulu/sulu/issues/5214 feel free to add your thoughts there, will close this issue to have that at a single point.
