### ISSUE TITLE
Add option to select 'inline' for a media internal link on pages.

### ISSUE THREAD

**Issue by j1v37u2k3y** [sulu/sulu#6368]
# Problem description

When selecting a media asset for internal link would like to add to have an option to add 'inline' to the url.

Right now the work around for me is to grab the url from the media and append `&inline=1` and make the link an external one.

# Proposed solution

so the url parameters would be this appended:

`?v=1&inline=1`

**Comment by alexander-schranz** [comment]
Hello @j1v37u2k3y,

If you want to have always images or pdfs be inlined you can configure this in the sulu_media configuration this way:

```yaml
sulu_media:
    disposition_type:
        default: "attachment"
        mime_types_inline: ["application/pdf", "image/jpeg"]
```

If you want todo that only on a specific media by adding the `&inline=1` paragraph the [`sulu_get_media_url`](https://docs.sulu.io/en/2.3/reference/twig-extensions/functions/sulu_get_media_url.html) can be used for this:

```twig
<a href="{{ sulu_get_media_url(media, 'inline') }}>
    {{ media.title }}
</a>
```

This solution only works for `media` selection or smart content providers. Inside the text editor its currently not possible that the content manager can select if its inline or attachment (force download). But think that would be interesting feature. I think a dropdown in the overlay with Default, Inline, Attachment would be good. But currently not sure how we can implement this in the MarkupBundle as this is media specific and pages/articles dont has yet that case. I hope atleast the `disposition_type` config can at currently be enough for you to handle this for your current project.

**Comment by j1v37u2k3y** [comment]
@alexander-schranz What file does this config go into?

**Comment by alexander-schranz** [comment]
@j1v37u2k3y You can put that config into a new `config/packages/sulu_media.yaml` file.

**Comment by j1v37u2k3y** [comment]
@alexander-schranz thank you so much worked like a charm.. forgot to clear:cache.
