### ISSUE TITLE
sulu-link will not work when page is a redirect page

### ISSUE THREAD

**Issue by simsationX** [sulu/sulu#6369]
| Q | A
| --- | ---
| Sulu Version | 2.3.7
| PHP Version | PHP 8.0.11
| DB Version | 
| Browser Version | 

# Actual Behavior

If you use `<sulu-link></sulu-link>` (https://docs.sulu.io/en/2.3/bundles/markup/link.html) and the target page is a redirect, the link will not be resolved correctly.

Problem is: If a template is using `single_page_selection`  (https://docs.sulu.io/en/2.3/reference/content-types/single_page_selection.html) and the content manager uses a page of type redirect as the target page, the link won't work. According to the docs, you should use `<sulu-link>` as a tag for `single_page_selection`. But this works only with normal pages not redirect pages.

# Expected Behavior

The redirect page would resolve correctly.

# Steps to Reproduce

- Log in to sulu admin

- Create new page

- Go to “Settings“ of this subpage

- Change page type from “content” to “internal redirect”

- Select random redirect target 

- Click on “Save & publish”

- Go to another Page

- Add a content block and add an internal link or a button with an internal link and use your subpage (redirect) as your target 

- Go and visit the parent page on the frontend

- Click on the link

- The link will lead to the root no to the redirect

# Possible Solutions

The reason is that  in `resolveInternalLinkContent` in `ContentRepository` the url property of the `content` object stays empty and won't be resolved. For normal pages it would work, but not for redirect pages.

See PR

**Comment by alexander-schranz** [comment]
This is the behaviour for all relative current urls. You need to use always the [sulu_content_path](https://docs.sulu.io/en/2.3/reference/twig-extensions/functions/sulu_content_path.html) twig extension to get the full url of the page. At current state we can not change this behaviour as it would be a bc break we could think about this in 3.0 to change the behaviour.

**Comment by simsationX** [comment]
@alexander-schranz Sorry my bug description was misleading. The problem is much more a general issue. I have updated the bug description. Could you have a look again?

**Comment by alexander-schranz** [comment]
@ymc-sise This still appears on the 2.3.7? This is something I thought should be fixed in #6263 by @nnatter.

Can you check if all works expected if you first `Save & Publish` the page **before** changing it to a redirect type of internal link?

**Comment by simsationX** [comment]
@alexander-schranz I have checked it again and I saved & published the page first before changing to a redirect page as internal link.

Unfortunately no, `<sulu-link>` will not resolve the link. Please check it yourself.

**Comment by niklasnatter** [comment]
Fixed in #6484. Thanks for reporting!
