### ISSUE TITLE
Add title field to link content type

### ISSUE THREAD

**Issue by remdan** [sulu/sulu#6372]
# Problem description

Befor the link type exist i create my links in this way:

```
<property name="link" type="single_page_selection" mandatory="true">
    <meta>
        <title lang="en">Button (Link)</title>
    </meta>
</property>
<property name="link_name" type="text_line" mandatory="true">
    <meta>
        <title lang="en">Button (Name)</title>
    </meta>
</property>
<property name="link_title" type="text_area" mandatory="true">
    <meta>
        <title lang="en">Button (Title-Attribut)</title>
    </meta>
</property>
```

```
{% set target = sulu_content_load(content.link) %}
<a href="{{ sulu_content_path(target.content.url) }}" title="{{ content.link_title }}">{{ content.link_name }}</a>
```

# Proposed solution

I would like to have only one type for creating an html link.

```
<property name="link" type="link">
    <meta>
        <title lang="en">Link</title>
    </meta>
    <params>
        <param name="name" type="text_line" mandatory="true"/>
        <param name="title" type="text_line" mandatory="true"/>
        <param name="enable_target" value="true"/>
        <param name="enable_anchor" value="true"/>
        <param name="types" type="collection">
            <param name="page"/>
            <param name="external"/>
            <param name="media"/>
        </param>
    </params>
</property>
```

`<a href="{{ content.link }}" target="{{ content.link.target }}" title="{{ content.link.title }}">{{ content.link.name }}</a>
`

**Comment by alexander-schranz** [comment]
@remdan Thank you for your feedback:

I don't think we will add here any dynamic content types. But I think it would make sense to add also the `Alternate Title` to the overlay so its similar to the current implementation of the Internal Links in the `text_editor` content types:

<img width="518" alt="Bildschirmfoto 2021-11-25 um 11 41 48" src="https://user-images.githubusercontent.com/1698337/143426891-4ce748d0-344f-4aea-8be7-95e1af21cf30.png">

For the Content (name you called it) I'm not sure I personally don't see it in the overlay, I would see it side by side to the link from UI/UX perspective as it faster accessible and content manager don't need to open the overlay to change that text. So something like this would then be my proposal:

<img width="612" alt="Bildschirmfoto 2021-11-25 um 11 48 32" src="https://user-images.githubusercontent.com/1698337/143427860-45c109f7-75ea-4e8f-bee0-dd913487ae94.png">

But something similar could also be build by using following template structure:

```xml
<property name="link" type="link" colspan="6">
    <meta>
        <title lang="en">Link</title>
    </meta>
</property>

<property name="link_text" type="text_line" colspan="6">
    <meta>
        <title lang="en">Link Text</title>
    </meta>
</property>
```

<img width="623" alt="Bildschirmfoto 2021-11-25 um 11 51 27" src="https://user-images.githubusercontent.com/1698337/143428266-9e4ed962-0bc2-4b5e-b873-1eb2e06d9cf3.png">

The advantage so would only be that the content/title would then be under `content.link.title`.

**Comment by remdan** [comment]
@alexander-schranz Thank you for your new example "side by side to the link" I would find that okay.

yet another thought, in combination with blocks:
```
<block name="blocks" default-type="default">
    <meta>
        <title lang="en">Blocks</title>
    </meta>
    <types>
        <type name="default">
            <meta>
                <title lang="en">My default Block</title>
            </meta>
            <properties>
                <property name="link" type="link" colspan="6">
                    <meta>
                        <title lang="en">Link</title>
                    </meta>
                    <params>
                        <param name="enable_target" value="true"/>
                        <param name="enable_anchor" value="true"/>
                        <param name="types" type="collection">
                            <param name="page"/>
                        </param>
                    </params>
                </property>
                <property name="link_text" type="text_line" colspan="6">
                    <meta>
                        <title lang="en">Link Text</title>
                    </meta>
                </property>
            </properties>
        </type>
    </types>
</block>
```

```
{% for block in content.blocks %}
<a href="{{ block.link }}" target="{{ view.blocks[loop.index0].link.target|default('') }}" title="{{ view.blocks[loop.index0].link.title|default('') }}">{{ dump(block.link_text) }}</a>
{% endfor %}
```

`{{ dump(view.blocks) }}`
![Bildschirmfoto 2021-11-29 um 11 46 07](https://user-images.githubusercontent.com/5031692/143854247-653e847e-6501-40a9-988c-f8c4a933d016.png)

the workaround over the view needs a separated handling, it's possible, but I am not so excited...

**Comment by alexander-schranz** [comment]
Thx for report. We decided not to make the link content type flexible, but add the possibility to add a title like its done in the ckeditor. The title is in the `view` variable as we also have the other data there. Make sure you use something like the following when working with blocks:

```twig
{% for block in content.blocks %}
     {% include 'includes/blocks/' ~ block.type ~ '.html.twig' with {
        content: block,
        view: view.blocks[loop.index0],
     } only %}
{% endfor %}
```

See also the demo:

https://github.com/sulu/sulu-demo/blob/12fef890049a282533579ea3381ab7a9a5ebf119/templates/includes/blocks.html.twig#L3-L10
