### ISSUE TITLE
{host} wildcard in webspace configuration not working with audience targeting

### ISSUE THREAD

**Issue by adepretis** [sulu/sulu#6407]
| Q | A
| --- | ---
| Sulu Version | 2.3.7
| PHP Version | 8.0.13
| DB Version | Percona 5.7.35-38
| Browser Version | irrelevant
| Cache | Varnish configured according to https://docs.sulu.io/en/2.3/bundles/audience_targeting.html
| Reverse Proxy | HAProxy

# Actual Behavior

When defining catch-all hosts in the webspace configuration the audience targeting functionality isn't able to detect it.

```
    <portals>
        <portal>
            <name>my-webspace</name>
            <key>my-webspace</key>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="de">{host}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url language="de">{host}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="de">{host}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
```

With active audience targeting you get `UrlMatchNotFoundException There exists no portal for the URL "_sulu_target_group"` in the end. It only works when adding an explicit hostname or `localhost` - this is also related to #6406

Fun fact: if you got it to work once and the client has all the audience targeting cookies, it works.

# Expected Behavior

It should work exactly like without the audience targeting in place and the `{host}` wildcard should be recognized.
 
# Steps to Reproduce

- Setup Varnish
- Setup HAProxy (optional, for SSL termination)
- Setup Audience Targeting
- Setup Webspace with `{host}` wildcard in portal environment urls
- Access http(s)://my.example.domain

# Possible Solutions

No idea

**Comment by adepretis** [comment]
Update: this is definitively related to #6406 

If this change is in place, the `{host}` wildcard matching also works again.

**Comment by mamazu** [comment]
The PR that was linked was merged. If this still isn't fixed please reopen this issue.
