### ISSUE TITLE
Query parameters in <sulu-link> tag

### ISSUE THREAD

**Issue by exastion** [sulu/sulu#6418]
# The `<sulu-link>` tag only supports anchors

Currently the `<sulu-link>` tag only allows anchors using `#` in the `href` attribute. IMHO it should be possible to also add query parameters using a `?` here.

# Proposed solution

~~A workaround is to use an empty anchor followed by the query parameters: `123-123-123-123#?query=parameter`.~~

EDIT: I did not check if the resulting link actually works. This is not the case, as no new request is send to the server if the page is the same.

After taking a look at the code, it doesn't seem to be to difficult to add the possibility to support query parameters directly and I would be willing to create a pull request.

**Comment by alexander-schranz** [comment]
Sorry for the late response. This definitly is something which can be added. I think currently the string is splitted by `#` hre: https://github.com/sulu/sulu/blob/ee6e61de48f20d1514e4f2bf9fc49401a5882000/src/Sulu/Bundle/MarkupBundle/Markup/LinkTag.php#L218-L219

The `$hrefParts[0]` should also be splitted by `?` then a `query` could additional be returend and when query is not null it should be added above before:

https://github.com/sulu/sulu/blob/ee6e61de48f20d1514e4f2bf9fc49401a5882000/src/Sulu/Bundle/MarkupBundle/Markup/LinkTag.php#L80-L82

to the url. If you want to give it a try I'm happy to review it.

**Comment by exastion** [comment]
I created a pull request implementing the feature.
The parsing is strict about the order of the query parameters and the anchor, following the [RFC](https://www.rfc-editor.org/rfc/rfc3986#section-4.1).
I'm not sure about what should happen if the order is not right, should this be ignored and be put in the right order or should it fail?
Or wouldn't it be easier to not include anchor nor query parameters in `href` but use separate properties i.e.: `anchor` and `query`.
I guess this would make the code less complex.

**Comment by alexander-schranz** [comment]
@exastion will comment on the Pull Request about your question.
