### ISSUE TITLE
Add possibility for defaults for Url Content Type

### ISSUE THREAD

**Issue by remdan** [sulu/sulu#6433]
# Problem description
It's not possible in the moment to set defaults like the "Url" type.
# Proposed solution

```
<params>
    <param name="defaults" type="collection">
        <param name="target" value="_parent"/>
        <param name="scheme" value="http://"/>
        <param name="specific_part" value="www.google.at"/>
    </param>

    <param name="schemes" type="collection">
        <param name="http://"/>
        <param name="https://"/>
    </param>
</params>
```

**Comment by alexander-schranz** [comment]
@remdan Thank you for report. This is duplicated to #6373 please add your thoughts there and subscribe that issue.

**Comment by alexander-schranz** [comment]
Oh sorry the title did confuse me. You did talk about the `Url` content type.

**Comment by remdan** [comment]
you are right, is duplicated to #6373 I did't found that ticket at that time...
