### ISSUE TITLE
Sorting of snippets by type is not working

### ISSUE THREAD

**Issue by jesperveldhuizen** [sulu/sulu#6443]
| Q | A
| --- | ---
| Sulu Version | latest version (tried it out on sulu.rocks)

# Actual Behavior

The sorting of snippets in the SULU admin ui is not working. Snippets are not sorted by type. Sorting by title is working though.

# Expected Behavior

Sorting of the snippets by type is working correctly.

# Steps to Reproduce

Go to: https://sulu.rocks/admin/#/snippets/de?sortColumn=title&sortOrder=asc

Add some random snippets and try sorting by type.

**Comment by niklasnatter** [comment]
I think we already have an open issue for this (https://github.com/sulu/sulu/issues/6207), therefore I am closing this in favour of the older one. Still thanks for your time!
