### ISSUE TITLE
Add support for avif image formats

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6476]
# Problem description

Beside webp there is a new image format on the horizont the avif format. It would be great to add this format also.

Tweet by Ikea changing 21% less traffic on images:

https://twitter.com/robinwhittleton/status/1486013791670353922

# Proposed solution

On sulu side it is more straight forward:

 - [x] Adjust the ImagineImageConverter avif format
     - [x] https://github.com/sulu/sulu/blob/c0e3b0b4d64d82111618a48de374e10265f3fb89/src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php#L129-L142
 - [x] Adjust the SuluMediaExtension avif_quality
     - [x] https://github.com/sulu/sulu/blob/a6f8287d7e0cd30be591bbe54f48883c6de5c7ff/src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php#L257

**Testing checklist**

The support has been added to `imagine`: https://github.com/php-imagine/Imagine
We should test if it work like expected for us.

 - [x] GD Adapter (https://php.watch/versions/8.1/gd-avif) seems to be implemented
   - [x] avif_quality support
 - [x] Imagick Adapter should already be supported but need to be checked
   - [x] avif_quality support
 - [x] VIPS Adapter seems to be implemented
   - [x] avif_quality support

**Comment by alexander-schranz** [comment]
Reseved for [VincentA](https://twitter.com/vinceAmstoutz/status/1590404420613046272).

**Comment by vinceAmstoutz** [comment]
@alexander-schranz Before I start in the next few days, I need, please, a confirmation on this part:
> The support need also be added to imagine: https://github.com/php-imagine/Imagine

Correct me if I'm wrong, you mean I should add support for AVIF images in the `php-imagine/Imagine` repository in addition?

**Comment by chirimoya** [comment]
It looks like `Imagine` has already added the support for AVIF ... https://github.com/php-imagine/Imagine/issues/742 /cc @alexander-schranz correct me, if I'm wrong.

**Comment by vinceAmstoutz** [comment]
> It looks like `Imagine` has already added the support for AVIF ... [php-imagine/Imagine#742](https://github.com/php-imagine/Imagine/issues/742) /cc @alexander-schranz correct me, if I'm wrong.

Well seen, since version 1.3 apparently: https://github.com/php-imagine/Imagine/releases/tag/1.3.0.

So for this point there is nothing to do @alexander-schranz?

**Comment by alexander-schranz** [comment]
@vinceAmstoutz Welcome nice to see you here :)

> Correct me if I'm wrong, you mean I should add support for AVIF images in the php-imagine/Imagine repository in addition?

So the task here is that Sulu Code need to be updated that avif is supported in the linked files:

 - [ ] Adjust the ImagineImageConverter avif format
     - [ ] https://github.com/sulu/sulu/blob/c0e3b0b4d64d82111618a48de374e10265f3fb89/src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php#L129-L142
 - [ ] Adjust the SuluMediaExtension avif_quality
     - [ ] https://github.com/sulu/sulu/blob/a6f8287d7e0cd30be591bbe54f48883c6de5c7ff/src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php#L257
     
The `Imagine` checkbox list is just there that we don't forget to test if the `avif_quality` parameters is working like expected but can ignore by you.

**Comment by vinceAmstoutz** [comment]
Thanks for your welcoming 🙂
Perfect!

**Comment by alexander-schranz** [comment]
@vinceAmstoutz if you need any help to start let me know. But definitely no stress here take your time. And if you have questions always feel free to ping me.

**Comment by alexander-schranz** [comment]
Implemented by @vinceAmstoutz in #6910 🎉 Part of upcoming 2.6
