### ISSUE TITLE
single_page_selection returns uuid for unpublished page instead of null or empty

### ISSUE THREAD

**Issue by martinlagler** [sulu/sulu#6489]
| Q | A
| --- | ---
| Sulu Version | 2.3
| PHP Version | 7.4
| DB Version |  MySQL 5.7 

# Actual Behavior

`single_page_selection` returns uuid for unpublished pages.

# Expected Behavior

Unpublished pages should be null, as the link will not be generated correctly

# Steps to Reproduce

`single_page_selection` 

and

```
<sulu-link href="{{ item.link }}" class="button">
    <span>
        Link
    </span>
</sulu-link>
```

**Comment by alexander-schranz** [comment]
@martinlagler currently the single page selection does not know if the page does exist or not as it does not load anything. The MarkupListener should in that case remove sulu-link tag and so it should not longer be a link. As a workaround you currently could use `sulu_content_load(item.link, {'title': 'title', 'url': 'url'})`. Its very important to add the properties to it else it will end in performance issue.
Also with 2.4 we added a new content type called link which would be better suited for your usecase: https://docs.sulu.io/en/2.4/reference/content-types/link.html.

**Comment by alexander-schranz** [comment]
I will close the issue as it is related to https://github.com/sulu/sulu/issues/545 which is about that the single page selection only returns the uuid.
