### ISSUE TITLE
Search: Do not create a new Elasticsearch index field for every field in a Sulu XML template

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#6501]
# Problem description

A new field is created in the index for every field in the Sulu XML template if the Sulu search is used with the Elasticsearch adapter. This could lead to a huge amount of fields, above all when using the `sulu.search.field` tag for fields in block in block structures. Elasticsearch limits the number of fields by default to 1000 - so it could happen that the content manager adds one new block and is then running into an error when saving the page as the following Elasticsearch exception is thrown: `Limit of total fields [1000] has been exceeded`.

# Proposed solution

Best solution would be a new attribute in the `sulu.search.field` which gives the developer the possibility to choose if the content of this field should just be taken into account for searching or if it is really needed as a separate field that could be retrieved from the index (similar to the `Unstored` field type in Zend Lucene).

**Comment by thomasduenser** [comment]
We ran into this problem for two projects in the last few weeks and therefore I would love to see an implementation of the proposed solution.

**Comment by alexander-schranz** [comment]
fixed in #6868
