### ISSUE TITLE
Make media usages visible for content managers

### ISSUE THREAD

**Issue by spackmat** [sulu/sulu#6507]
# Problem description

Hi, I'm in the deep evaluation phase of Sulu for a project and played around with uploaded media. Maybe I'm missing something, but I expected to have the possibility to show the related pages/content-elements of a media entity inside the media manager. Like "this image is used in..." From my experience that information is crucial for content managers to avoid the media chaos that constantly grows with every uploaded media element.

For some background: We have several content-situations, where the media is directly owned by the entity or page and should at best not be shown in the media manager at all (like the PDF files of job descriptions). That seems to be not possible in an easy way with Sulu, so we must manage this media via the media manager, right? To do that, our content managers need a way to see to what content an uploaded file belongs to, so they can decide if they can safely delete it or use it elsewhere.

# Proposed solution

It would be cool if the relations of media elements are made visible to content editors, at least for internal relations (pages/content-elements/users), but even better for all relations, especially to own entities (like my job offers).

Also cool would be a possibility to configure uploaded media to be privately owned by their relation so that they are not shown in the media manager at all or maybe in a special collection and prevented to be used elsewhere and be deleted/unpublished together with their parent (and also inheriting their access rights). I neither found a way to do that in Sulu directly, but at least have an idea about how to implement that in part for my custom entities. Is there any documentation about handling files of custom entities without involving the media manager, I missed somewhere?

**Comment by alexander-schranz** [comment]
Hello @spackmat there is currently no reference store where we know which media is used where. It would require to save this somewhere as `content` itself is saved unstructured and so it is not a relation on the database itself. So there is no way from ORM point of view to find out which media is used where.

There where some discussion already about it how to achieve this if a Global Reference store/repository should be included into the new `ContentBundle` or if it is part of the media bundle to provide a `MediaReference` store/repository and save its relation. Both solutions has it's advantages and disadvantages. We can currently not give a timeline when something like this will be implemented but it is something which was already in discussion to provide in future. Think it is good to have now also an issue here for it, which can be used as a discussion point and get other peoples opinion on this topic.

For `privately owned` media you should go with a system collection. See https://docs.sulu.io/en/2.4/cookbook/system-collections.html This are special collections which can configured and are as example used for contact avatars and account logos. And then in your custom entities form you can use the special single_media_upload type see example for contact: https://github.com/sulu/sulu/blob/245c5fd5c45fdcffffc65cd99c3ef3e7a9e9ed22/src/Sulu/Bundle/ContactBundle/Resources/config/forms/contact_details.xml#L11-L26. Hint this is a field type only and can not be used inside pages / articles / snippets or content entities.

Independent from this feature I always recommend to predefine the collection structure with all your content managers to have a good structuring where which media are put.

**Comment by spackmat** [comment]
Hey, thank you for your time. I am quite surprised that neither the content repository has fast query-methods for that one-direction-relations between media and referencing content (like NoSQL-Databases provide), nor that the system keeps track of those references in any way.

For my current project needs that is quite a showstopper as we come from the very painful origin of an unkind SharePoint-based implementation of a big website where our dozens of low trained content editors (public services employees) upload their files everywhere and after some years nobody is able to tell if a file lying around somewhere can be renamed, replaced or deleted safely, nor if it even should be publicly available anymore. That the SharePoint-search indexes PDF files and make all those outdated files findable does not make it better. So one of the top points for my evaluation is the handling of files in relation to the content.

In that project (and most of my other projects in the past), having uploaded media not privately owned by content/pages is the exceptional case. The standard case is: An editor authors a notice on the black board or a job offer or an article or a content page and uploads files and images that are never and also should never be used anywhere else. And, even more important: They should vanish with their parents, when they are unpublished/deleted. I'm not sure if using a system collection meets those requirements, even if I could use it inside pages / articles / snippets or content entities.

So from that evaluation point of view I cannot recommend Sulu for our upcoming usecases for now internally, which is a pity as so often I had that "finally!" feeling while evaluating the system.

I had also found the system collections, that, at least in part, solve some of my problems. Question on this: The documentation of the media select fields does not mention a way to restrict the upload to specific collections or (even better) system collections. Why not? Then I could create a collection taxonomy and force my content editors to not splat their files anywhere around. And I didn't find the `single_media_upload`, because it is not documented at all, so thanks for that hint.

Other question related to my custom entities: Is it possible to use the Sulu admin for them, but making them handle their uploaded files on their own way? The `single_media_upload` only uploads to a configurable collection, when I've understood that correctly. I just need an upload field and the controller can handle the storage part as it does with a standard Symfony Form or an AJAX-version of it.

**Comment by alexander-schranz** [comment]
I try to answer all your questions hope I don't forget one:

> I am quite surprised that neither the content repository has fast query-methods for that one-direction-relations between media and referencing content (like NoSQL-Databases provide)

In sulu only content is stored in PHPCR. Media itself are stored in a normal relational database. That is why there exist no reference on database level between page and media. If you want manually create an endpoint to show media references you would need to check the `templates` structure and then load all pages and check if a media is inside them. Specially blocks / nested blocks make it hard to query this kind of things. 

> I had also found the system collections, that, at least in part, solve some of my problems. Question on this: The documentation of the media select fields does not mention a way to restrict the upload to specific collections.

No there is currently no way to restrict the media selection as I remember. The only way would be to restrict them by system collection key as you normally don't want to hardcode any IDs in your code, but that is not implemented yet and would be a another issue. The only way a user sees not all collection are using permissions you can tell which role which collection can see via the Permission overlay when you open a collection. 

> The single_media_upload only uploads to a configurable collection, when I've understood that correctly.

Yes a single_media_upload will upload that specific file into that collection. The main difference to a single media selection is first that you can not choose where it is uploaded and second if you drop a new file to the exist media it will create a "New Version" of the exist media and not create a new Media in that case. So it normally used for one-to-one relation between an object and a media.

> I just need an upload field and the controller can handle the storage part as it does with a standard Symfony Form or an AJAX-version of it.

If you want to create an own field type to upload things into a custom directory you need to write the JS implementation for it. Have a look at the sulu demo examples here: https://github.com/sulu/sulu-demo/pull/79. But if you don't create then a media entity you will not be able to use all media features or have a global media management.

I think if you want a privately owned media for an object best is that you go with a `single_media_upload` into a system collection. And then you can create a Event Listener which will also remove the media when the object is removed. This way the content manager don't can or need to select a collection and you make sure that media are removed when not in use anymore.

**Comment by alexander-schranz** [comment]
Closing this as implemented in 2.6
