### ISSUE TITLE
documentManager->removeLocale not working

### ISSUE THREAD

**Issue by ymc-thzi** [sulu/sulu#6510]
| Q | A
| --- | ---
| Sulu Version | 2.4.1
| PHP Version | 8.1.3

# Actual Behavior

`$this->documentManager->removeLocale($document, $localeToRemove);`
throws an Exception:
`Call to a member function format() on null at /var/www/sulu/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Trash/PageTrashItemHandler.php:112`

# Expected Behavior

documentManagers removeLocale method works without failing

# Steps to Reproduce

$this->documentManager->removeLocale($someDocument, 'en');

**Comment by alexander-schranz** [comment]
@ymc-thzi thx for report. Looks for me that your page does not have created date which is really strange as that should be always the case: https://github.com/sulu/sulu/blob/855897b99a873ba115edf8b4e71a082ae9fae1de/src/Sulu/Bundle/PageBundle/Trash/PageTrashItemHandler.php#L112

Can it be that you try to delete a document which was not yet persisted to the database?

I tested it on my installation `Delete current localization` did work without any problems there.

**Comment by ymc-thzi** [comment]
Thanks for the answer. So I will check whats wrong with my documents...
Will report the solution here if I will find anything.

**Comment by simsationX** [comment]
@alexander-schranz We have 4 languages, de, fr, it, en. But not each document has all 4 locale variants. So for some documents we have de, fr, it, en, for some we have only de, fr, it, for some we have de, it, en.

Now for certain conditions we want to clean up a locale. So in that case want to delete all documents in en. For that we iterate through:

```
$query = 'SELECT * FROM [nt:unstructured] WHERE (([jcr:mixinTypes] = "sulu:article") OR ([jcr:mixinTypes] = "sulu:page"))';
        $documents = $this->documentManager->createQuery($query)->execute();

        foreach ($documents as $document) {
            if ($document instanceof UnknownDocument) {
                continue;
            }
            
            $this->documentManager->removeLocale($document, $localeToRemove);
        }
```

Unfortunately we don't have a "en" version for each document. But we assume that your removeLocale function should handle this in the PageTrashItemHandler in 

`$localizedPage = $this->documentManager->find($page->getUuid(), $locale);`

But if I var_dump $localizedPage then I have:

```
(Sulu\Bundle\PageBundle\Document\PageDocument)#15175 (30) {
  ["nodeName":protected]=>
  string(18) "politik-verwaltung"
  ["created":protected]=>
  NULL
  ["changed":protected]=>
  NULL
  ["creator":protected]=>
  int(10)
  ["changer":protected]=>
  ```
  
  So should we take care of checking that the locale variant exists for documents before removing it?

**Comment by alexander-schranz** [comment]
Seems like you are loading the document in the ghost locale which you should not be done when you want to delete / remove it.

Normally you need to load a document with the `load_ghost_content` => `false` flag else you get the document in its ghost locale: https://github.com/sulu/sulu/blob/855897b99a873ba115edf8b4e71a082ae9fae1de/src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php#L156-L158

Else you could also check if a `i18n-<your-locale>:created` property exists before calling removeLocale. But the `removeLocale` method is not be build that you call it with `ghostDocument` normally. So I don't think we will change here something.

**Comment by simsationX** [comment]
Thank you for the reply.

I understand. Checking for the property seems to be good solution. :+1:
