### ISSUE TITLE
Dropping Support for PHP 7.4, 7.3 and 7.2

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6515]
# Problem description

Currently Sulu 2.x supports the range of PHP 7.2 to 8.1. Symfony 6 requires atleast PHP 8.0 where they will drop 8.0 support in 6.1 and go there with PHP 8.1.

As symfony 6 make heavy usage of Union Types which is only supported with PHP 8 it can make things hard to provide support also for PHP 7.4 and old version. Specially return types like here make the things hard: https://github.com/symfony/symfony/blob/64215ea63e585670352fae17e82b6393d1617e96/src/Symfony/Component/Serializer/Serializer.php#L157

# Proposed solution

Drop support for PHP 7.4 and lower in favor of supporting Symfony 6 and newer.

PHP 7.4 is already in security support only and will not longer get any updates in november: https://www.php.net/supported-versions.php

Related: 

 - #6513
 - https://github.com/sulu/sulu/issues/6556

**Comment by sabinebaer** [comment]
For me it would be ok to drop PHP <=7.4 support as we should upgrade our projects to PHP 8 anyway at some time during this year. If there are any major bugs that really impact us or our customers it would be great if you could release the corresponding bugfix not only for the newest Sulu version but also for an older version that still supports PHP < 8.0.

**Comment by alexander-schranz** [comment]
If there is a urgent bugfix required we definitely open for our [partners](https://sulu.io/partner/find-a-partner) to backport it back in this case to the previous 2.4.x version which would then support PHP 7.4. Also when that version is not longer in the supported range. So maybe in this case 2.4 will maintained a little bit [longer then usually](https://sulu.io/direction).

Thx for your feedback.
