### ISSUE TITLE
_target not working in content type "link"

### ISSUE THREAD

**Issue by Mouradrhl** [sulu/sulu#6546]
| Q | A
| --- | ---
| Sulu Version | 2.4 
| PHP Version | 8 
| DB Version |  Postgresql 12
| Browser Version | Chrome last

# Actual Behavior
Param "enable_target" not working for content type "link"

# Expected Behavior
target="_blank" must be enabled

# Steps to Reproduce
- In template xml add a content type link with :  `<params><param name="enable_target" value="true"/></params>`
- In admin interface select target of the link : "_blank"
- Click the link, the linked document must open in a new tab.

# Possible Solutions

**Comment by alexander-schranz** [comment]
The `html` is generated by your twig template and you need in the twig template keep the set `_target` in mind. See the documentation about it here: https://docs.sulu.io/en/2.4/reference/content-types/link.html#complex-twig

**Comment by alexander-schranz** [comment]
Closing this as it seems to be solved.
