### ISSUE TITLE
Add Support for Symfony 6

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6556]
# Problem description

Add Support for Symfony 6.

# Proposed solution

Upgrade dependencies and sulu core to be compatible to Symfony 5.4 / 6.0.

 - #6515
 
# External Dependencies Symfony 6 Support

The following packages need to be updated first before symfony 6 compatibility can be added:

 - [x] [massive/search-bundle](https://github.com/massiveart/MassiveSearchBundle)
   - [x] https://github.com/massiveart/MassiveSearchBundle/pull/167
 - [x] [massive/build-bundle](https://github.com/massiveart/MassiveBuildBundle)
   - [x] https://github.com/massiveart/MassiveBuildBundle/pull/23
 - [x] [handcraftedinthealps/rest-routing-bundle](https://github.com/handcraftedinthealps/RestRoutingBundle)
   - [x] https://github.com/handcraftedinthealps/RestRoutingBundle/pull/18
   - [x] https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2368
 - [x] [jackalope/jackalope](https://github.com/jackalope/jackalope)
    - [x] https://github.com/jackalope/jackalope/pull/369
 - [x] [jackalope/jackalope/jackalope-doctrine-dbal](https://github.com/jackalope/jackalope-doctrine-dbal)
 - [x] [jackalope/jackalope-jackrabbit](https://github.com/jackalope/jackalope-jackrabbit)
    - [x] https://github.com/jackalope/jackalope-jackrabbit/pull/168
    - [x] https://github.com/jackalope/jackalope-jackrabbit/pull/169
 - [x] [phpcr/phpcr-shell](https://github.com/phpcr/phpcr-shell)
   - [x] https://github.com/jackalope/jackalope/pull/372
   - [x] https://github.com/phpcr/phpcr-utils/pull/207
   - [x] https://github.com/jackalope/jackalope-jackrabbit/pull/170 
   - [x] https://github.com/phpcr/phpcr-shell/pull/210
 - [x] [friendsofsymfony/http-cache-bundle](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle)
    - [x] https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/573
 - [x] [phpcr/phpcr-migrations](https://github.com/phpcr/phpcr-migrations)
    - [x] https://github.com/phpcr/phpcr-migrations/pull/14
 - [x] [dantleech/phpcr-migrations-bundle](https://github.com/dantleech/phpcr-migrations-bundle)
    - [x] https://github.com/dantleech/phpcr-migrations-bundle/pull/17
    - [x] https://github.com/dantleech/phpcr-migrations-bundle/pull/18
 - [x] doctrine/cache
    - [x] https://github.com/doctrine/cache/pull/398
 
# Sulu Support
 
 - [x] Upgrade PHPFFmpeg to 1.0
   - [x] https://github.com/sulu/sulu/pull/6548
 - [x] Drop Support for PHP 7.3 and Symfony 5.3 and lower
   - [x] #6515
   - [x] #6513
   - [x] https://github.com/sulu/sulu/pull/6553
 - [x] Replace swiftmailer with Symfony Mailer
   - [x] https://github.com/sulu/sulu/pull/6549 
   - [x] https://github.com/sulu/skeleton/pull/164
 - [x] Upgrade FOSJSRoutingBundle
   - [x] https://github.com/sulu/sulu/pull/6551
   - [x] https://github.com/sulu/skeleton/pull/165
 - [x] Ugrade toflar/psr6-symfony-http-cache-store
   - [x] https://github.com/sulu/sulu/pull/6552
 - [x] Replace antishov/doctrine-extensions-bundle with stof/doctrine-extensions-bundle
   - [x] https://github.com/sulu/sulu/pull/6564
 - [x] Code Upgrades
   - [x] https://github.com/sulu/sulu/pull/6555
   - [x] https://github.com/sulu/sulu/pull/6554
   - [x] https://github.com/sulu/sulu/pull/6557
   - [x] https://github.com/sulu/sulu/pull/6561
   - [x] https://github.com/sulu/sulu/pull/6562
   - [x] https://github.com/sulu/sulu/pull/6567
   - [x] https://github.com/sulu/sulu/pull/6568
   - [x] https://github.com/sulu/sulu/pull/6569
   - [x] https://github.com/sulu/sulu/pull/6571
   - [x] https://github.com/sulu/sulu/pull/6573
   - [x] https://github.com/sulu/sulu/pull/6574
   - [x] https://github.com/sulu/sulu/pull/6575
   - [x] https://github.com/sulu/sulu/pull/6576
   - [x] https://github.com/sulu/sulu/pull/6577
   - [x] https://github.com/sulu/sulu/pull/6578
   - [x] https://github.com/sulu/sulu/pull/6579
   - [x] https://github.com/sulu/sulu/pull/6580
   - [x] https://github.com/sulu/sulu/pull/6581
   - [x] https://github.com/sulu/sulu/pull/6582
   - [x] https://github.com/sulu/sulu/pull/6583
   - [x] https://github.com/sulu/sulu/pull/6584
   - [x] https://github.com/sulu/sulu/pull/6585
   - [x] https://github.com/sulu/sulu/pull/6586
   - [x] https://github.com/sulu/sulu/pull/6587
   - [x] https://github.com/sulu/sulu/pull/6601
   - [x] https://github.com/sulu/sulu/pull/6603
   - [x] https://github.com/sulu/sulu/pull/6604
   - [x] https://github.com/sulu/sulu/pull/6625
   - [x] https://github.com/sulu/sulu/pull/6626
   - [x] https://github.com/sulu/sulu/pull/6651
   - [x] https://github.com/sulu/skeleton/pull/170
 - [x] Ugrade Symfony Core packages, Cmf Routing, FosHttpCache, ...
   - [x] https://github.com/sulu/sulu/pull/6563
   - [x] https://github.com/sulu/skeleton/pull/173
 - [x] Remove getRootDir (optional)
   - [x] sulu/sulu Preview https://github.com/sulu/sulu/pull/6652
   - [x] ~~massive bundles~~ nothing found
 - [x] Upgrade security firewall (PUBLIC_ACCESS, authenticator, ...)
   - [x] sulu/sulu
   - [x] skeleton

**Comment by alexander-schranz** [comment]
Merged and alreay party of Sulu 2.5.0-alpha1: https://github.com/sulu/sulu/releases/tag/2.5.0-alpha1

**Comment by StaffNowa** [comment]
Good job :)

**Comment by alexander-schranz** [comment]
@StaffNowa Thx. Even could use your work from the [security.encoder_factory => security.password_hasher_factory](https://github.com/sulu/sulu/pull/6562/commits) pull request in mine :)
