### ISSUE TITLE
Dropping Support for npm 6 in favor of npm 8.8

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6566]
# Problem description

We were still stuck on npm 6 but with the release of npm 8.8 there is a new flag which allows us the install the dependencies the way which make it again possible to build them again.

**Advantages** to switch to npm 8.8:

 - User need to update instead of downgrade npm on latest node and node lts versions (npm i -g npm)
 - Long term it would be better to switch to npm 8.8 and keep sulu compatible with newer versions of npm and node
 
**Disadvantages** to switch to npm 8.8:

 - npm 8.8 does not longer create symlink for local packages which make it harder to develop sulu itself or custom bundles with custom js (workaround maybe possible over postinstall)
 - there is no way to support npm 6 and npm 8.8 so update is required
 - users need to switch between npm 6 and npm 8.8 for when developing different sulu projects

# Proposed solution

Discuss if we want to go on npm 8.8 with sulu 2.5 or if we wait with this change until 3.0.

Related issues:
 
 - https://github.com/sulu/skeleton/issues/88
 - https://github.com/webpack/webpack/issues/13572#issuecomment-923736472
 - https://github.com/npm/cli/issues/2339#issuecomment-1111228605

**Comment by mamazu** [comment]
It's merged into 2.6
