### ISSUE TITLE
Contact | Security Issues

### ISSUE THREAD

**Issue by ghost** [sulu/sulu#6608]
Dear Sulu contributors,

I've tried to contact you through the email found in your security policy, but got no response.
Please get back to me at: [vulnerability@whitesourcesoftware.com](mailto:vulnerability@whitesourcesoftware.com) or [miriam.iomin@whitesourcesoftware.com](mailto:miriam.iomin@whitesourcesoftware.com)
It's about security issues found in your project.

Thanks,
Miriam

**Comment by alexander-schranz** [comment]
Hello Miriam,

Thank you for reaching out for us. And really sorry for the late response, the emails were broken in my Mail Client (Apple Mail and Gmail).
It did filter it out and attachments were not even accessible. Not sure why Gmail behave this way.
Another maintainer also getting the emails did now forward me the files.
I will check them and answer you per email.

Already thank you for your contribution to sulu.

Best Regards,
Alex

**Comment by ghost** [comment]
@alexander-schranz Hey didn't get any email from you :( Is there any update regarding this?
Thanks in advance :)

**Comment by alexander-schranz** [comment]
Hello @wsmi22,

You should got an email to `miriam.iomin@whitesourcesoftware.com` at 18. May and an invitation to the security advisory. I can try to resend you the invitation.

**Comment by ghost** [comment]
@alexander-schranz I see it now thank you!
