### ISSUE TITLE
Extending a standard entity (e.g. Sulu User) causes Doctrine to not spot it when generating proxies

### ISSUE THREAD

**Issue by AdamReece-WebBox** [sulu/sulu#6611]
| Q | A
| --- | ---
| Sulu Version | 2.2.19
| PHP Version | 8.0.18
| DB Version | MySQL 5.7.38

We are currently extending Sulu's standard User entity as per documentation here:
https://docs.sulu.io/en/2.2/cookbook/extend-entities.html
Our extended class is at `App\Entity\User` and pretty much works exactly as expected.

# Actual Behaviour

Unfortunately this has a side effect in Doctrine whereby the proxy class for `Sulu\Bundle\SecurityBundle\Entity\User` is not generated in Symfony's cache, which is necessary because some add-on bundles (such as the community bundle) make direct reference to the class. (File `__CG__SuluBundleSecurityBundleEntityUser.php` will be missing.)

This only applies to production environment because `doctrine.orm.auto_generate_proxy_classes` is `false`. In development and testing environments the proxy class is generated on demand as this setting is `true` for those.

This applies to both "admin" and "website" cache realms.

I accept this may be an upstream issue with Symfony's Doctrine bundle, or Doctrine itself, but there should be mention of this in Sulu's documentation as a "gotcha".

# Expected Behaviour

Doctrine proxy file `__CG__SuluBundleSecurityBundleEntityUser.php` should be generated 

# Steps to Reproduce

1. Extend a standard non-abstract Sulu entity, e.g. `Sulu\Bundle\SecurityBundle\Entity\User` as `App\Entity\User`.
2. Deploy (or reconfigure) to production without debugging enabled.
3. Run `bin/websiteconsole cache:warmup --env=prod --no-debug` just to give yourself every possible chance.

At this point you'll notice that `./var/cache/website/prod/doctrine/orm/Proxies` is missing file `__CG__SuluBundleSecurityBundleEntityUser.php`, and your application will crash as a result.

# Possible Solutions

Changing `doctrine.orm.auto_generate_proxy_classes` to `true` in the production Doctrine config would work but that would have negative performance impact.

**Comment by alexander-schranz** [comment]
Hello @AdamReece-WebBox,

The class `Sulu\Bundle\SecurityBundle\Entity\User` should not exist from Doctrine point of view. 

The error you are running into is mostly that some custom entity or third party entity is not referencing the user correctly and uses `Sulu\Bundle\SecurityBundle\Entity\User` in a ORM mapping.

It is important that ORM mapping is always done based on the Interface not the Class. As example here: https://github.com/sulu/sulu/blob/c298925a6815803b5f94ca80be3ffce1c939615f/src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/UserRole.orm.xml#L12.

So search for appearance of `Sulu\Bundle\SecurityBundle\Entity\User` in your and third party ORM mappinggs and replace them with `"Sulu\Component\Security\Authentication\UserInterface`. The interface will be mapped via target resolve listener to your [configured entity](https://docs.sulu.io/en/2.2/cookbook/extend-entities.html#configuration) then correctly and the error should be gone.

**Comment by AdamReece-WebBox** [comment]
Very interesting !

The majority of our entities did reference our own `App\Entity\User` but I did find two that referenced Sulu's User.
That, and a couple of other functional changes to take in Sulu's user interface instead of Sulu's user entity, seems to have done the trick.

A tell tale sign was a HTTP 500 when signing in (via the community bundle) in production mode, which no longer happens.
We'll try out our application further and see if this is a working solution.

Thank you kindly @alexander-schranz 

--

Update: We've done a few `cache:clear` calls as a result of deploying to both staging, and all seems to be working well. We've since done a live deployment and had no complaints so far. Thanks again Alex!

**Comment by alexander-schranz** [comment]
Thx for the feedback, good to hear that it all works now.
