### ISSUE TITLE
Collections and Media permissions are coupled

### ISSUE THREAD

**Issue by R3dLantern** [sulu/sulu#6612]
| Q | A
| --- | ---
| Sulu Version | 2.4.2
| PHP Version | 8.1.5
| DB Version | MariaDB 10.4.12
| Browser Version |  Google Chrome 101.0.4951.64 (64-bit)

# Actual Behavior

When applying user role permissions for the Media section, both Collection and Media entity permissions are shown in a single line:

![image](https://user-images.githubusercontent.com/8995716/168840490-d09db9e2-606c-4b72-a869-c3326afc8a80.png)

While design implies the possibility of assigning varying permissions for both entities, it's technically not the case. Applying any permission for one entity will apply the same permission to the other.

# Expected Behavior

Not sure here. UI design says it should be possible to set varying permissions, but the Media overview implies that this is an ignored edge case. I nevertheless report it as a bug for now.

# Steps to Reproduce

Try applying user role permissions for `Media.collections`.

**Comment by alexander-schranz** [comment]
I'm not sure how this is happening. Sulu itself does not have media permissions. Permissions for media are controlled only over collections. So the demo only displays the collections:

<img width="1250" alt="Bildschirmfoto 2022-05-17 um 17 54 27" src="https://user-images.githubusercontent.com/1698337/168855217-3d997c04-0af2-434e-825a-0495db87d7c1.png">

Did you extend MediaAdmin with your own MediaAdmin and accidently provided more permissions. Or did you want to add some new permissions. In that case it is required that you use another key then the exist one. So the following key should not be used for your new permissions: https://github.com/sulu/sulu/blob/c298925a6815803b5f94ca80be3ffce1c939615f/src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php#L187

Still media are not developed to have there own permissions. They always should be controlled over collection permissions and only that permisisons are kept in mind for selection and smart contents on website content types.

**Comment by R3dLantern** [comment]
After some research I discovered there was a problem in my custom Admin class, hence the doubled permission buttons. Fixing it returned the view to the state you've screenshotted.

> Still media are not developed to have there own permissions. They always should be controlled over collection permissions and only that permisisons are kept in mind for selection and smart contents on website content types.

I see. In that case, I will close this.
