### ISSUE TITLE
SingleSelection field only changes its type when the name of the field updates

### ISSUE THREAD

**Issue by j-mahlke** [sulu/sulu#6613]
| Q | A
| --- | ---
| Sulu Version | 2.3.11
| PHP Version | 8.1
| Browser Version | Chrome 101

# Actual Behavior

When a field in a block changes its type from single_something_selection to single_other_selection without changing the name of the field, the overlay list shows the list of the last entity (in the example above, single_other_selection would list entities of type something)

# Expected Behavior

when the block type changes the type of a field without changing the name, it should also affect the type of entities in single-selection lists

# Steps to Reproduce

use this page-template:
note, that the name of the field is always "item", no matter what type of entity_selection
`
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <view>pages/default</view>
    <controller>Sulu\Bundle\WebsiteBundle\Controller\DefaultController::indexAction</controller>
    <cacheLifetime>604800</cacheLifetime>

    <meta>
        <title lang="en">Default</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
            </meta>
            <params>
                <param name="headline" value="true"/>
            </params>

            <tag name="sulu.rlp.part"/>
        </property>

        <property name="url" type="resource_locator" mandatory="true">
            <meta>
                <title lang="en">Resourcelocator</title>
            </meta>

            <tag name="sulu.rlp"/>
        </property>

        <block name="content" minOccurs="0">
            <meta>
                <title lang="de">Inhalt</title>
            </meta>

            <params>
                <param name="add_button_text">
                    <meta>
                        <title lang="en">Add feature</title>
                    </meta>
                </param>
            </params>

            <types>
                <type name="contact">
                    <meta>
                        <title lang="en">Contacts</title>
                    </meta>

                    <properties>
                        <property name="item" type="single_contact_selection">
                            <meta>
                                <title lang="en">Contacts</title>
                            </meta>
                        </property>
                    </properties>
                </type>
                <type name="snippet">
                    <meta>
                        <title lang="en">Snippet</title>
                    </meta>

                    <properties>
                        <property name="item" type="single_snippet_selection">
                            <meta>
                                <title lang="en">Snippet</title>
                            </meta>
                        </property>
                    </properties>
                </type>
                <type name="entity_a">
                    <meta>
                        <title lang="en">Entity A</title>
                    </meta>

                    <properties>
                        <property name="item" type="single_entity_a_selection">
                            <meta>
                                <title lang="en">Entity A</title>
                            </meta>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
    </properties>
</template>

`

**Comment by alexander-schranz** [comment]
Hello @jmahlkeXTAIN, thx for reporting,

Currently it is expected that as example a text_line will tried to be migrated into a text_area when switching templates or block types and so on. We currently have no mechanism implemented to avoid this kind of migrations for selections. So when switching from contact to account selection it will still try to load thing by the id provided before. I'm not sure if this will be changed soon, so at current state I recommend you to name your properties differently if you don't want that behaviour.

Still the admin ui should never crash if you request something which does not exist. It should just try to load the entity if not it should stay empty. Does the UI crash in your case? If yes that should definitly not happening and could be related to #6610 issue.

**Comment by j-mahlke** [comment]
Hi @alexander-schranz ,
thanks for your fast answer.
As changing the names in the whole project is a huge amount of work for us, we'd like to try to fix that ourselfes and create a PullRequest on that.
Do you have any advice on where to start?

**Comment by alexander-schranz** [comment]
Can I ask you how the issue behave in your case? If you switch the type the request to the endpoint should be send with the previous id and if it does not exist it should return a 404 and so it should not make any problems and the admin should work like expected.

Or do you run into another issue that the Admin JS crashes because of some weird behaviour?

**Comment by j-mahlke** [comment]
If I switch the type from single_A_selection to single_B_selection, the overlay with the title single_B_selection.title shows the list of A entities. 
Instead, it should replace the List with a list of B entities. it uses the old resource-key and therefor also accesses the old entity api endpoint / old route.
If you save the page and reload the page before selecting an item in the list, you then get the correct list, as the field already has its correct type on page loading.

no problem with crashes here.

**Comment by j-mahlke** [comment]
This is the example page template from the reproduce section.
On Page loading, the single_contact_selection is loaded because it is the first type in the block-types config.
Then, I change the type to Entity_A, and click on the selection field to select an Entity of type A.
Instead of seeing the list of A's, I still see the list of contacts

<img width="876" alt="Bildschirmfoto 2022-05-19 um 11 50 57" src="https://user-images.githubusercontent.com/87640962/169265767-ca6be3c5-7e37-494f-8ed6-6d50c5ee43e3.png">

**Comment by alexander-schranz** [comment]
Ohhh I understand, seems like there is something not rerendered. Can you check if the issues is only with block types or if it is also outside of blocks when example switching the template?
I could think that there is maybe some issue with mobx here and nested objects, which we already had on some other cases as mobx can not always detect changes int hat objects 🤔

**Comment by j-mahlke** [comment]
I can't reproduce the problem when switching templates, so looks like this only applies to blocks.

**Comment by j-mahlke** [comment]
project/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js gets the old ListStore in Props

**Comment by alexander-schranz** [comment]
Quick look at the code there could be a quickfix via a `key`:  There are currently two solutions I see:

**A:**

I could think that adding here a key property: https://github.com/sulu/sulu/blob/c298925a6815803b5f94ca80be3ffce1c939615f/src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js#L202

Something like `key={name + '_' + type}` could maybe work. I hope that the type is here `contact_selection` and not just `selection`.

**B:**

Another place where already a key is set but the type not included could be here: https://github.com/sulu/sulu/blob/c298925a6815803b5f94ca80be3ffce1c939615f/src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js#L70

`key={schemaKey + '_' + schemaField.type}`

@jmahlkeXTAIN Could you give it a try? If one or both works to fix the issue?

/cc @niklasnatter what do you think? What the correct place here is?

**Comment by j-mahlke** [comment]
option A works <3
key is 'item_single_contact_selection'
I'm creating a PR for that

**Comment by niklasnatter** [comment]
Thanks for reporting! This was fixed in #6620
