### ISSUE TITLE
MediaAdmin is only included for PermissionTypes::EDIT, not PermissionTypes::VIEW

### ISSUE THREAD

**Issue by YetiCGN** [sulu/sulu#6617]
| Q | A
| --- | ---
| Sulu Version | 2.4.2
| PHP Version | 8.1.5
| DB Version | doesn't matter
| Browser Version | all browsers affected

# Actual Behavior

The Media admin view is not included in the sidebar and the routing if only "view" and "add" privileges are configured for `sulu.media.collections`. However, if the user has the media view open and the privileges are revoked in the meantime, the interface is reasonably usable: They can upload new files and browse which files exist, but not change or delete files.

# Expected Behavior

When `PermissionTypes::VIEW` is granted for `sulu.media.collections`, show MediaAdmin in navigation sidebar and include routes in admin routing.

# Steps to Reproduce

1. Assign a role to a user that has media create, view and edit privileges.
2. Open admin interface with that user, navigate to media view.
3. Revoke edit privilege for that role.
4. Keep on navigating as the unprivileged user with reloading the admin interface and the media view will still work, but without editing privileges.
5. Reload admin interface and the navigation item will be gone and deeplinks will not work anymore because of router configuration.

# Possible Solutions

See upcoming one-line PR ^^

**Comment by alexander-schranz** [comment]
@YetiCGN This was a decision made some time ago that all items in the Navigation Bar need to have atleast `Edit` permissions. The problem what is here is that I want to give someone as least permission as possible. But e.g. "view" permission as Sulu is API driven is required for any "Selection" Field Types so even if I say they only are allowed to Edit "Snippets" they still need "View" Permission for all selections they can use. So we decided a Navigation Item is only show for users which have actually "Edit" Permission for that area.

**Comment by YetiCGN** [comment]
Okay, I see. I guess we will include it as a Composer patch for our application then.

**Comment by alexander-schranz** [comment]
We know it is not the ideal solution for all, but currently did fit in the most use cases. When discussion the problem we had also discussed if there should be additional permission type just for navigation item but we decided against that to have 2 different types of read permissions.
