### ISSUE TITLE
Deleting referenced tag fails

### ISSUE THREAD

**Issue by ymc-siwi** [sulu/sulu#6627]
Deleting referenced tag fails

| Q | A
| --- | ---
| Sulu Version | 2.4.2
| PHP Version | 8.1.3
| DB Version | MySQL 5.7.36
| Browser Version | Chrome 100.0.4896.127

# Actual Behavior

- If tags are used in contacts (reference in table co_contact_tags) or accounts (reference in table co_account_tags), they cannot be deleted via backend interface (Settings -> Tags -> delete referenced tag)
- Deletion fails with an unspecific error message

# Expected Behavior

- Deleting a tag will also delete related references to contacts and accounts
- Deleting a contact will also delete related references to tags (entries in table co_contact_tags)
- Deleting an account will also delete related references to tags (entries in table co_account_tags)

# Steps to Reproduce

- Log into admin using a user that has sufficient rights to manage tags, contacts and organizations
- Open tag list view (/admin/#/tags)
- Add and save new tag
- Edit a contact, add the new tag, save contact
- Open tag list view (/admin/#/tags) again, try to delete tag
- Deletion will fail with error message ```An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`blk_sulu`.`co_contact_tags`, CONSTRAINT `FK_4CB525501C41CAB8` FOREIGN KEY (`idTags`) REFERENCES `ta_tags` (`id`))```
- The same will happen for organizations (table and index name in error message will of course vary).

# Possible Solutions

- Workaround for the time being: delete all references in contacts and accounts manually before deleting a tag
- Enable cascading between tags (table ta_tags) and tables co_contact_tags/co_account_tags
- Pull request currently in preparation.

**Comment by alexander-schranz** [comment]
@ymc-siwi Thx for creating this issue. Looks like here is a on-delete cascade missing:

https://github.com/sulu/sulu/blob/6069d05f8efae4ad89c428adf4113dc326a0bf74/src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Contact.orm.xml#L182-L194

This should be added to all many-to-many relations on contacts and accounts seems like it is missed in other cases also.

As an example here it is correct:

https://github.com/sulu/sulu/blob/6069d05f8efae4ad89c428adf4113dc326a0bf74/src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml#L70-L79

Do you want to create a Pull Request for it updating the on-delete cascade?

**Comment by ymc-siwi** [comment]
@alexander-schranz Sure, PR already in preparation ;-) Thanks for looking into the issue!

**Comment by niklasnatter** [comment]
I think this should be fixed in #6628. Thanks a lot!
