### ISSUE TITLE
 http://schemas.sulu.io/template/template-1.1.xsd unavailable

### ISSUE THREAD

**Issue by simontol** [sulu/sulu#6653]
| Q | A
| --- | ---
| Sulu Version | 2.4.2
| PHP Version | 8.1.6
| DB Version | 5.7.37
| Browser Version | N/A

# Actual Behavior
Upgraded from Sulu 1.x a month ago and migrated some page types with the following header:
```
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">
```
The upgrade process went fine and all worked well.
Today I found that the http://schemas.sulu.io/template/template-1.1.xsd file has become unavailable.
I've tried to switch to http://schemas.sulu.io/template/template-1.0.xsd but some tags are not valid such as:
`<xi:include`

# Expected Behavior
Was the 1.1.xsd file been removed intentionally?
I'm expecting to be able to reach the 1.1 file to keep backward compatibility.

# Possible Solutions
Please put http://schemas.sulu.io/template/template-1.1.xsd file on the server.

Thanks.

**Comment by alexander-schranz** [comment]
Thx for report. Looks like something wrong here with the schema deployment, that there are not all version available. 

/cc @wachterjohannes can you check this not sure how this is currently deployed.

As a workaround you can also reference to your local file in the vendor directory:

Depending where your file is, it something like:

```xml
xsi:noNamespaceSchemaLocation="../../../vendor/sulu/sulu/src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd"
```

Similar phpunit is doing: https://github.com/sulu/skeleton/blob/2.5/phpunit.xml.dist#L5

**Comment by simontol** [comment]
Hi @alexander-schranz ,
thank you for your reply.
Unfortunately there is no `template-1.1.xsd` file in the schema directory. 
Can't find it in the codebase.

**Comment by wachterjohannes** [comment]
@simontol i have taken a look at that - do you have any idea in which version of sulu the `template-1.1.xsd` was available? seems to me that there were never an official release with this XSD. Also on the server we never deployed that intentionally. /cc @alexander-schranz

**Comment by simontol** [comment]
Hi @wachterjohannes,
our team inherited the Sulu project from another team.
We've upgraded the project from 1.6 to 2.4.
The xsd link started giving error at the start of this month.
I suppose that the file was removed from the server on June 8th.
![immagine](https://user-images.githubusercontent.com/32391/175973659-b97cc03c-a04a-4d97-9eaf-06ac8cb7454c.png)

I dug into the git history and found that the reference to the `1.1` file was added on December 2017.

**Comment by alexander-schranz** [comment]
I think you are save to change that templates all to `template-1.0.xsd` I could not find a reference to the `1.1` file in one of old skeletons or standard version and the current version of skeleton still uses 1.0. I think we did falsly versionate it sometimes ago and it was never adjusted correctly. So at current state I think we will keep go with the `1.0` file and you just need adjust your references from 1.1 to 1.0 in your project.

**Comment by wachterjohannes** [comment]
@simontol i can only approve what @alexander-schranz said - just change back to 1.0 version. i have no chance to find any reference to the 1.1 version and also in the deployment there was no version 1.1

I will close this issue but if you have problems with it after changing to version 1.0 - feel free to open a new issue
