### ISSUE TITLE
Media upload from root collection provokes permission error

### ISSUE THREAD

**Issue by R3dLantern** [sulu/sulu#6662]
| Q | A
| --- | ---
| Sulu Version | 2.4.3
| PHP Version | 8.1.7
| DB Version | MariaDB 10.4.12
| Browser Version | Google Chrome 102.0.5005.115 (64-bit)

# Actual Behavior

When in Media overview ("root collection"): You can trigger the upload process and then proceed to select a collection you are not permitted to reach for the new upload. The result is a HTTP 403 response, however the error message is generic and does not provide any information on what exactly went wrong.

# Expected Behavior

It should not be possible to select a restricted collection for a new Media upload. The best case would be that restricted collections are not up for selection in the overlay column list.

# Steps to Reproduce

1. Create a collection and enable custom permissions for it.
2. Log in as a user that is not permitted to access the new collection, and go to the Media overview.
3. Initiate an upload process. You should see the collection you have no access to (albeit it with the "shield" icon).
4. Select the collection as the upload target and confirm.

# Possible Solutions

* When fetching the collection list via API, the system should already consider filtering out restricted collections, albeit it with the caveat that child collections without restriction would fall victim to such filtering.
* The UI could be visually and funcationally enhanced by preventing selection of restricted collections and indicate the restriction, e.g. via icons or distinct coloring.

**Comment by alexander-schranz** [comment]
Thx for reporting. This is fixed via #6666 and will be part of the next release.
