### ISSUE TITLE
Admin backend crashes when setting localStorage with non JSON values

### ISSUE THREAD

**Issue by tstauer** [sulu/sulu#6724]
| Q | A
| --- | ---
| Sulu Version | 2.5.0
| PHP Version | 8.0.20
| DB Version | mysql  Ver 14.14 Distrib 5.7.38
| Browser Version | Firefox 91.11.0esr (64-Bit)
# Actual Behavior

The admin backend crashes in the file clipboard.js when trying Json.parse on the localStorage content.
Action buttons like saving in the backend are not working due to the JavaScript error.

The error got introduced in this pull request when clipboard.js was added to Sulu 2.5.0:

#6630 

https://github.com/sulu/sulu/pull/6630/files#diff-0fa7c85ac2df4f8b0c29998cd6c4f2d148d0704a5c712b986a683eb71528e070

# Expected Behavior

Sulu must not crash.

# Steps to Reproduce

1. Login to the Sulu backend
1. Open a page with the preview activated
1. No error yet
1. Add some JavaScript to the page content
    1.  `localStorage.setItem('HelloWorld', 'Test');
`1. Reload the page
1. A JavaScript error is thrown
    1. ` Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    storageEventListener clipboard.js:15
    updateStorageEventListener clipboard.js:18
    observe clipboard.js:47
    e BlockCollection.js:60`

Please note that executing the following in the browser console after load does not throw an error:
`localStorage.setItem('HelloWorld', 'Test');`

# Possible Solutions

Put a try..catch around the JSON.parse.
https://stackoverflow.com/a/4467327

Or use a check if the string is valid json before performing JSON.parse
https://stackoverflow.com/a/3710226

**Comment by alexander-schranz** [comment]
Fixed in #6749 and will be part of the next release. @tstauer Thx for report!
