### ISSUE TITLE
ImageMap in admin not works if you use custom admin path

### ISSUE THREAD

**Issue by lucacolombo4** [sulu/sulu#6728]
| Q | A
| --- | ---
| Sulu Version | 2.4.3
| PHP Version | 8.0.16
| DB Version |  MariaDB 10.7
| Browser Version | Chrome 103

# Actual Behavior

If you use a custom admin path the ImageMap content type not shows image in the admin interface due to the wrong url to the image.

# Expected Behavior

ImageMap works with custom admin path

# Steps to Reproduce

1 - change admin path following sulu-demo example: https://github.com/sulu/sulu-demo/pull/60
2 - loading an image file in the ImageMap content type, the image cannot be loaded
3 - i noticed that in the file ImageMap/ImageRenderer.js there is the admin path with the default "admin" url:  
 https://github.com/sulu/sulu/blob/2.4.3/src/Sulu/Bundle/MediaBundle/Resources/js/containers/ImageMap/ImageRenderer.js#L52

**Comment by alexander-schranz** [comment]
@lucacolombo4 good catch 👍 . This should definitly use the fos js routing library to generate the url.

Do you want to create a PR for this for the 2.4 branch: You can find an example here: https://github.com/sulu/sulu/blob/08863981d9e607dd1432db68eec2dac710732f74/src/Sulu/Bundle/AdminBundle/Resources/js/stores/metadataStore/metadataStore.js#L30 and you find the route name here: https://github.com/sulu/sulu/blob/95d8c67f5df770b649b7706623c618034746778a/src/Sulu/Bundle/MediaBundle/Resources/config/routing.yml#L1

**Comment by lucacolombo4** [comment]
Thank you Alex, i followed your indications and it works.
You have to modify also this file: [vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php](https://github.com/sulu/sulu/blob/5755c551dcd69a91f6ef05f7148408f49b849b87/src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php#L108)
adding 'sulu_media.redirect' to 'routes_to_expose'

**Comment by alexander-schranz** [comment]
fixed in #6729
