### ISSUE TITLE
Make return arrow direct back to page editing when renewing image

### ISSUE THREAD

**Issue by marek5816** [sulu/sulu#6787]
# Problem description

When I am editing page and I click on image, because I need to update it with newer version, every time I click on back arrow, it return me to media not the page that I am editing.

# Proposed solution

It would be nice if it redirect user back to page editing, because every time I need to make unnecessary clicks to get back to editing, if user would like to work more with media page, he can simply make just one click on sidebar

**Comment by alexander-schranz** [comment]
@marek5816 The arrow button in the Sulu UI will at current state always navigate to the "overview" or the defined parent route of that view.
At current state the easiest way to get back to the page you did come from by just click your Browsers "Back Button", which will navigate you back to the page you did come from.
