### ISSUE TITLE
Readme mentions wrong versions for requirements

### ISSUE THREAD

**Issue by friemt** [sulu/sulu#6796]
| Q | A
| --- | ---
| Sulu Version | 2.5
| PHP Version | NA
| DB Version | NA
| Browser Version | NA

# Actual Behavior

`README.md` on `sulu/sulu` and `sulu/skeleton` lists the wrong requirements despite the `composer.json` dependencies being set to `"php": "^8.0 || ^8.1"` and `"symfony/framework-bundle": "^5.4 || ^6.0"`.

Sulu requires a PHP version higher or equal to 7.2 and is compatible with every Symfony version starting from 4.3.

# Expected Behavior

Sulu requires a PHP version higher or equal to 8.0 and is compatible with every Symfony version starting from 5.4.

# Steps to Reproduce

# Possible Solutions

**Comment by alexander-schranz** [comment]
We are currently still supporting Symfony 4.4 and and PHP 7.2 in Sulu 2.4, which is actively maintained. You can install it via `composer create-project sulu/skeleton:"2.4.*"`. But if you start a new project we recommend the usage of PHP 8.1 and Sulu 2.5 as Sulu 2.4 end of life is end of year. See our [Direction](https://sulu.io/direction) about our Release Cycle.

**Comment by friemt** [comment]
Okay, shouldn't the readme of version 2.5 list the actual requirements for version 2.5? Am I missing something?

**Comment by alexander-schranz** [comment]
@friemt I decided to keep it when releasing 2.5 as it is more a "Landingpage README", until we really drop support for it because Symfony 4.4 is also still a supported LTS version. There are currently also still discussion if we support 2.4 longer then other minor releases, because of such things.

**Comment by friemt** [comment]
Ok, thanks for the clarification.
