### ISSUE TITLE
add categories and tags to link type

### ISSUE THREAD

**Issue by remdan** [sulu/sulu#6798]
# Problem description

It is currently not possible to generate a link that also refers to a corresponding category or tag... for example you have a link in a footer that points to a site with a [SmartContent](https://docs.sulu.io/en/2.5/reference/content-types/smart_content.html).

Yes, it's possible by query, but you have to know the id from the category...
![](https://user-images.githubusercontent.com/5031692/185155295-096f9673-1d59-4ed9-8061-c3365b77c374.png)

```
<property name="link" type="link">
    <meta>
        <title lang="de">Link</title>
    </meta>
    <params>
        <param name="enable_anchor" value="true"/>
        <param name="enable_query" value="true"/>
        <param name="enable_attributes" value="true"/>
        <param name="types" type="collection">
            <param name="page"/>
        </param>
    </params>
</property>
```

For Editors it's not that nice, I think there should be a workaround by [Category selection](https://docs.sulu.io/en/2.5/reference/content-types/category_selection.html#category-selection) field...

# Proposed solution

`<param name="enable_categories" value="true"/>`
Should take a default like from SmartContent: "Defines the categories key to be used in the website query string. This comma separated list of category ids will be combined (AND) with the selected tags from the backend. Default: categories"

or defined:
`<param name="enable_categories" value="my_ parameter_ key"/>`

```
<property name="link" type="link">
    <meta>
        <title lang="de">Link</title>
    </meta>
    <params>
        <param name="enable_anchor" value="true"/>
        <param name="enable_query" value="true"/>
        <param name="enable_attributes" value="true"/>
        <param name="enable_categories" value="c"/>
        <param name="enable_tags" value="t"/>
        <param name="types" type="collection">
            <param name="page"/>
        </param>
    </params>
</property>
```

**Comment by alexander-schranz** [comment]
I don't think we will add such a features to the `link` content type. As the focus on the link content type is creating a link like `<sulu-link>` and `<a href>` not more. What makes maybe in your case more sense is using the `teaser_selection` which is extendable by overwriting such services. Currently there is no `single_teaser_selection` but maybe that would make to make this easier in future. 

If I see your example with types filter: 

```xml
<param name="types" type="collection">
    <param name="page"/>
</param>
```

You should more go with a `single_page_selection` or `page_selection`. If you want to link to a page and nothing else. The `link` is more created as above for simple usecase but with advantages of linking to everything what have an url which comes with such limitations that you only have access what is required to render a link.

**Comment by remdan** [comment]
thanks for your feedback... now I understand the background and usecase of the two types better.

**Comment by remdan** [comment]
teaser_selection is not a option in the moment I think... the direction of progress is not yet completely clear to me, is in a state of upheaval ([many open tickets](https://github.com/sulu/sulu/issues?q=is%3Aissue+is%3Aopen+teaser)).
