### ISSUE TITLE
Temporarily disable preview in admin

### ISSUE THREAD

**Issue by oprichnik** [sulu/sulu#6806]
# Problem description

When in a page with a lot of content, the preview is refreshing every time i'm typing something on the keyboard.

This makes impossible writing something smoothly because of excessive lags.

# Proposed solution

- Automatic sensor disabling preview when typing on the keyboard
- Setting to disable temporarily the automatic preview refresh

**Comment by alexander-schranz** [comment]
That sounds strange there is already some debouncing active which should avoid to many requests and refreshing. Current debounce rate is hardcoded to 250ms: https://github.com/sulu/sulu/blob/e8a62f408dd15e1b89b9bfff63dda2d89cc3597e/src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js#L26.
What could also be the reason for the `lags` is custom JS which maybe leaks memory everytime the website is refreshes. So maybe try to check if the lags also appear when you have no JS on your website. Else not sure if @wachterjohannes have maybe any input to this.

**Comment by oprichnik** [comment]
I updated to the last version of Sulu and this is working as expected by now.
