### ISSUE TITLE
Incompatibility with gedmo/doctrine-extensions 3.7.0

### ISSUE THREAD

**Issue by llefort001** [sulu/sulu#6808]
| Q | A
| --- | ---
| Sulu Version | Tested with 2.4.2, 2.4.5
| PHP Version | 8.0.22
| DB Version | mariadb-10.3.34
| Browser Version | Chrome 105.0.5195.52

# Actual Behavior

Error 500 : 
`Uncaught Exception: An exception has been thrown during the rendering of a template ("Tree object class: App\Entity\Category must have tree metadata at this point")`

Happens after extending sulu Category entity like in ths example : https://github.com/sulu/sulu-demo/pull/92.
Then calling  `sulu_categories(app.request.locale, 'services') ` in one of the app templates.

After cache:clear, app loads correctly 1 time. Each subsequent load leads to the error.

**Only happens if APP_DEBUG = 0**

# Expected Behavior

App loads correctly categories each time.

# Steps to Reproduce

`composer create-project sulu/skeleton 2.4`
`composer require gedmo/doctrine-extensions 3.7.0`
Add `sulu_categories(app.request.locale, 'services') ` in `your base.html.twig` (no need to have existing categories)
Set `APP_ENV=prod APP_DEBUG=0` in your `.env.local`
`bin/console cache:clear`
Reload your homepage -> Supposed to work 1 time
Reload your homepage -> Error 500 -> Check var/log/website/prod.log

# Possible Solutions
Using another doctrine-extensions version resolves the problem (kinda hard to find out this solution and why it works)
Tested with : 
`composer require gedmo/doctrine-extensions 3.5.0`
`composer require gedmo/doctrine-extensions 3.6.0`
`composer require gedmo/doctrine-extensions 3.8.0`

**Comment by alexander-schranz** [comment]
@llefort001 Thx for report as it seems to work on the latest 3.8 version we should just add a conflict to `3.7` to the conflict section of your `composer.json`: https://github.com/sulu/sulu/blob/2.4/composer.json#L143

Do you want to create a pull request for the 2.4 branch adding this conflict?

**Comment by alexander-schranz** [comment]
fixed in #6810
