### ISSUE TITLE
App Secret is stored visible in .env file

### ISSUE THREAD

**Issue by manibi** [sulu/sulu#6822]
| Q | A
| --- | ---
| Sulu Version | 
| PHP Version | 
| DB Version | 
| Browser Version | 

# Actual Behavior
The value of APP_SECRET is visible in the .env file and can easily be found with dorking.

# Expected Behavior
No openly visible variable values in .env file

# Steps to Reproduce
Look into https://github.com/sulu/sulu/blob/2.5/.env row 3

# Possible Solutions
Remove visible variable values from .env file and use encryption.

**Comment by luca-rath** [comment]
This repository is never used in production directly. Instead, a new project is created using the `sulu/skeleton` repository, which does not have a `APP_SECRET` set and a new `APP_SECRET` is generated automatically when creating the project and written to the `.env.local` file. The `.gitignore` file contains `.env.local`, therefore that secret is never being pushed
