### ISSUE TITLE
Translation bug in preview (snippets and smart content)

### ISSUE THREAD

**Issue by wimvds** [sulu/sulu#6831]
| Q | A
| --- | ---
| Sulu Version | 2.4+
| PHP Version | 7.4.30
| DB Version | MySQL 5.7.39
| Browser Version | Chrome 105.0.5195.125 / Firefox 105.0.1

# Actual Behavior

When you edit a page in the admin and toggle the language via the dropdown in the edit window, the snippets and smart content in the preview will keep the original language you opened the page in, instead of switching to the new language you selected.

# Expected Behavior

All snippets and smart content should be shown in the correct language.

# Steps to Reproduce

Go to the admin on sulu.rocks and edit the blog page with `en` selected as the language. Then toggle the language to `de`via the dropdown. You'll see that the content in the preview window is updated, but the article teasers (smart content) will still be in English instead of German.

![translation-issue](https://user-images.githubusercontent.com/777114/192971336-f646c91d-788b-49fb-bdf4-15057b25fca5.gif)

# Possible Solutions

This seems to be due to the fact that the /admin/preview/start call is only executed on the initial page load, so content will be cached for that locale, and subsequent update calls will not touch the snippets and smart content. Because when you toggle the language only the /admin/preview/update call is executed, and this will load the cached data from the previously selected locale. You can test this by reloading the edit page in the browser (using the browser "Reload this page" button), then everything will be ok again because the /admin/preview/start call will be triggered.

Not sure what the best fix is here, but based on what I described above a quick fix seems to be to call the previewStore.start(); method in JS whenever the language is toggled in the UI.

**Comment by niklasnatter** [comment]
Thanks for reporting! This should be fixed in #6861
