### ISSUE TITLE
Anonymous roles always granted access to media when webspace security system is defined

### ISSUE THREAD

**Issue by NeuralClone** [sulu/sulu#6833]
| Q | A
| --- | ---
| Sulu Version | 2.3 or higher
| Symfony | 5.3 or higher
| PHP Version | 7.2 or higher
| DB Version | N/A
| Browser Version | N/A

# Actual Behavior

If there's a security system configured for a webspace and the anonymous role for that system is denied access to a media collection, access is still always granted if a user knows the download routes for the files in the collection.

# Expected Behavior

Access should be denied to a media file if an anonymous role doesn't have the view permission.

# Steps to Reproduce

(**Edit:** As per the discussion below, I've created a repository to reproduce this issue [here](https://github.com/NeuralClone/sulu-skeleton/tree/reproducer/anonymous-role-media-download).)

1. Create a new project using `sulu/skeleton` as outlined in the [Getting Started](https://docs.sulu.io/en/latest/book/getting-started.html) guide.
2. Add a security system to the example webspace:

```xml
<security permission-check="true">
    <system>Website</system>
</security>
```

3. Enable user context caching as [described here](https://docs.sulu.io/en/2.5/cookbook/user-context-caching.html).
4. Create a new media collection, activate the above security system for it, and deny access to the anonymous role.
5. Upload a media file to the new collection.
6. Create a download link for the newly uploaded media in a template:

```twig
{% set media = sulu_resolve_media(1, app.request.locale) %}
{% set url = sulu_get_media_url(media, 'attachment') %}

<a href="{{ url }}">Download</a>
```
7. Download the file without logging in.

# Additional Information

The problem seems to occur in the `SecurityChecker` service, Specifically, the first `if` statement:

https://github.com/sulu/sulu/blob/54a06ae9662d4944d51ebfcebafa07bbd68982fd/src/Sulu/Component/Security/Authorization/SecurityChecker.php#L40-L46

Anonymous roles are always granted access to media files regardless of permissions in Symfony 5.3 or later due the token always being `null`. This is fine when a security system isn't defined.

But it's problematic if you've configured one, want to deny media access to anonymous roles, and you're using a version of Symfony that doesn't create anonymous tokens.

# Possible Solutions

I've created a temporary workaround for this by overriding the `SecurityChecker` service and removing the anonymous check. This forces `isGranted()` to be called and access is correctly denied when appropriate.

I don't know if this is the best fix. I needed a quick way to prevent access to media collections while working out a more general solution and this seemed to break the least amount of stuff without knowing all of the inner workings of Sulu.

**Comment by alexander-schranz** [comment]
Did you setup a complete security system? Because justpermission-check is not enough to make this work.

Can you check the following documentation: https://docs.sulu.io/en/2.5/cookbook/user-context-caching.html

And if possible create a reproducable repository if it does not work for you.

**Comment by NeuralClone** [comment]
I also enabled user context caching as described in the documentation and somehow forgot to include it above. Sorry about that. I'll edit my post to include that step.

And sure, I can do that.

**Comment by NeuralClone** [comment]
I've created a repository that reproduces this particular issue and shows the exact changes I made after creating a sulu/skeleton project:

https://github.com/NeuralClone/sulu-skeleton/tree/reproducer/anonymous-role-media-download

I wanted to get this up and running quickly so my fixtures are loosely based on the fixtures in [sulu/sulu-demo](https://github.com/sulu/sulu-demo).

The steps to reproduce this issue after cloning the above repository and installing packages are:

1. Configure the database and run the `sulu:build` command:

`php bin/adminconsole sulu:build dev`

2. You can either manually set the permissions on the automatically created collection in the admin panel or just run this after the above command:

`php bin/adminconsole doctrine:fixtures:load --group=security --append`

3. Visit the homepage and click the download link without logging in.

Please let me know if any additional information is required or if anything needs to be changed/updated to help make this easier. I don't think I've missed anything but if I have, apologies in advance.

**Comment by alexander-schranz** [comment]
Can you try out if it is releated to #6825

**Comment by NeuralClone** [comment]
Sure, I can look into that.

**Comment by niklasnatter** [comment]
Hey, thanks a lot for setting up and providing the repository for reproducing this!

As you have already noticed, the problem here is that the behaviour of the symfony security bundle changed. In previous versions, Symfony returned an `AnonymousToken` for unauthenticated users. This was changed  in the authenticator-based security model (https://github.com/symfony/symfony/pull/42423) which was first introduced in 5.1: https://symfony.com.ua/doc/current/security/experimental_authenticators.html 
As far as I understand, the new model was opt-in until Symfony 6.0, so that is why this issue did not pop up until now.

I will check if these changes affect other parts of the system too and hopefully open a pull request to fix the issues!

**Comment by NeuralClone** [comment]
> Hey, thanks a lot for setting up and providing the repository for reproducing this!
> 
> As you have already noticed, the problem here is that the behaviour of the symfony security bundle changed. In previous versions, Symfony returned an `AnonymousToken` for unauthenticated users. This was changed in the authenticator-based security model ([symfony/symfony#42423](https://github.com/symfony/symfony/pull/42423)) which was first introduced in 5.1: https://symfony.com.ua/doc/current/security/experimental_authenticators.html As far as I understand, the new model was opt-in until Symfony 6.0, so that is why this issue did not pop up until now.
> 
> I will check if these changes affect other parts of the system too and hopefully open a pull request to fix the issues!

You're welcome! I had intended to take another look at things this weekend as mentioned above but I ran out of time.

I really appreciate the prompt responses, assistance, and all the hard work everyone has put into this project. It's saved me a ton of time.

**Comment by alexander-schranz** [comment]
@NeuralClone I merged both security checker related pull requests so it is easier for you to test you can run:

```
composer require sulu/sulu:"~2.5.1@dev"
```

To install the current dev version into your project. Please let us know if this did fix your issue.

**Comment by niklasnatter** [comment]
> I really appreciate the prompt responses, assistance, and all the hard work everyone has put into this project. It's saved me a ton of time.

Thats great to hear - thank you! 🙂

**Comment by niklasnatter** [comment]
Fixed in #6837

**Comment by NeuralClone** [comment]
> @NeuralClone I merged both security checker related pull requests so it is easier for you to test you can run:
> 
> ```
> composer require sulu/sulu:"~2.5.1@dev"
> ```
> 
> To install the current dev version into your project. Please let us know if this did fix your issue.

Thank you! Both fixes seem to have solved the issues I was having.

**Comment by alexander-schranz** [comment]
Thx for the feedback.
