### ISSUE TITLE
Add a way to create scopes for grouped parameters similiar to sections

### ISSUE THREAD

**Issue by stollr** [sulu/sulu#6860]
# Problem description

I am creating my first website with Sulu. I like the division between the structure (templates) and the content (twig). When it comes to structure the admin area *sections* are a nice way to separate different areas of a page.
But I am missing a way to not only separate those areas in the admin UI, but also to separate the properties from different sections when accessing them in the template.

Let me give you an example. Let's say our page template looks like this:
```xml
<properties>
    <section name="a">
        <properties>
            <property name="title" type="text_line"/>
            <property name="text" type="text_area"/>
        </properties>
    </section>
    <section name="b">
        <properties>
            <property name="title" type="text_line"/>
            <property name="text" type="text_area"/>
            <property name="image" type="single_media_selection"/>
        </properties>
    </section>
</properties>
```
And this is the twig template
```twig
<div class="a-wrapper">
    <h2>{{ content.a.title }}</h2> <!-- "content.a.title" instead of "content.title" -->
    <p class="text-center">{{ content.a.text }}</p>
</div>
<div class="b-wrapper">
    <h2>{{ content.b.title }}</h2> <!-- "content.b.title" instead of "content.title" -->
    <div class="d-flex">
        <img src="{{ content.b.image.formats['500x'] }}">
        <p class="text-left">{{ content.b.text }}</p>
    </div>
</div>
```    
I hope you see what I mean. I want to access the properties of different sections by separate property paths in the twig template. One advantage is that I can reuse property names. The other is a more clear separation in the twig template, too.

# Proposed solution

One solution would be to add a new attribute to the `<section>` element to get a new scope in the twig template. For example `<section own-scope="true">`.

The other solution would be to create a new element. Maybe simply `<scope>` or `<group>`. The new element should separate the properties in the admin UI the same way as sections already do.

What do you think? Or maybe there is already a way to achieve that (I know blocks, but this is not what I need in this case)?

**Comment by alexander-schranz** [comment]
@naitsirch Thx for creating this feature request. There is already an issue for it here https://github.com/sulu/sulu/issues/5063. So please add your additional thoughts there so we don't have here duplicated issues.

**Comment by stollr** [comment]
Thx for the hint. I have overlooked that issue.

**Comment by alexander-schranz** [comment]
No problem you are welcome!
