### ISSUE TITLE
JS error on article edit page of SULU demo

### ISSUE THREAD

**Issue by glen-rhodes** [sulu/sulu#6865]
| Q | A
| --- | ---
| Sulu Version | demo
| PHP Version | demo
| DB Version | demo
| Browser Version | Firefox 106.0.1

# Actual Behavior

When I click "edit" on an article in the article list of the admin section of SULU demo, I get a blank page with this error in me JS console:
TypeError: this.webspaceOptions[0] is undefined.

# Expected Behavior

I expected to see an article edit page.

# Steps to Reproduce

Click on the pen icon in the article list in the admin section of SULU demo : https://sulu.rocks/admin/#/articles/en/article.

**Comment by alexander-schranz** [comment]
@glen-rhodes I can not reproduce it. I can just click on any article and the article edit view is loaded like expected, no JS error. Maybe just somebody tried to change or messed around with the demo data. The demo is reseted in a specified interval and so it maybe is why the error is currently not longer there.

If you have similar issue on a local project let us know how to reproduce it.

**Comment by niklasnatter** [comment]
This sounds like somebody was messing with the permissions of the demo application while you were using it. As @alexander-schranz already set, the demo application is resetted periodically, so the error is not reproducible anymore. Still thanks for reporting! 🙂
