### ISSUE TITLE
sulu_content_load causes exception "Warning: Array to string conversion".

### ISSUE THREAD

**Issue by Impergator** [sulu/sulu#6870]
| Q | A
| --- | ---
| Sulu Version | 2.4.1
| PHP Version | 8.1
| DB Version | mariadbd  Ver 10.6.9-MariaDB for Linux on x86_64 (MariaDB Server)
| Browser Version | Google Chrome 105.0.5195.125 (Official Build) (64-bit)

# Actual Behavior

When ever I call the twig function `sulu_content_load(<myPageId>)` I get the following error

![image](https://user-images.githubusercontent.com/59212513/198560483-056e470f-bde6-4f6b-882a-3ea3e61780db.png)
![image](https://user-images.githubusercontent.com/59212513/198560645-9e209227-1d2b-4d4c-8af9-21f0823afe60.png)

The QueryBuilder tries to contatenate the $sortBy array with a string which php 8 doesn't seem to allow.
![image](https://user-images.githubusercontent.com/59212513/198561075-8f86fd0d-1d90-459e-86fd-99189bc5d71d.png)

# Expected Behavior

I expect to get the sulu page returned by the twig function instead of throwing the error described above.

# Steps to Reproduce

Just make an empty sulu project with the versions specified above. Create some pages and try to load a page by its id with sulu_content_load(<id>). The same bug appears with snippets as well.

# Possible Solutions

When I remove the marked code in the SmartContent\QueryBuilder then the rest works fine, so maybe just convert the array before concatenating or removing the code if it's not needed at all.
![image](https://user-images.githubusercontent.com/59212513/198570934-0b189737-07f1-4d24-b5f1-ea69bb3c119c.png)

**Comment by alexander-schranz** [comment]
@Impergator is this maybe an older project which was updated to a newer version. The sortBy was changed some time ago and phpcr migration where added. Can you check if this happens also for a new page? And check if all your phpcr migrations are run:

```bash
bin/console phpcr:migrations:migrate
```

PS: `sulu_content_load` should always used with `properties` parameter else you will run into performance issues: https://docs.sulu.io/en/2.5/reference/twig-extensions/functions/sulu_content_load.html

**Comment by Impergator** [comment]
@alexander-schranz You are right, this is an older project that was updated. I've tested your recommendations and the error only appears when I reference an old page. When I reference a new page it works perfectly. I tried `bin/console phpcr:migrations:migrate` to upgrade the old pages, but the migrations are already on the newest version. Is there something else I need to upgrade?

**Comment by alexander-schranz** [comment]
This is the migration which should handle this: https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202005250917.php

Maybe you can try to rerun this one only or debug why it does not work for your page.

**Comment by Impergator** [comment]
Ok, I upgraded the sulu version to 2.5, reverted the phpcr migration scripts and reran them. Now it also works with the old pages. Thank you very much.
