### ISSUE TITLE
Upload icon have overlay path

### ISSUE THREAD

**Issue by Jupi007** [sulu/sulu#6873]
The down arrow of the `upload` icon got overlay path, and it looks weird.

**Actual:**

![Capture d’écran du 2022-10-30 19-38-38](https://user-images.githubusercontent.com/36476595/198895783-94dd8894-9aa9-4af2-b077-793fe5e3ecb5.png)

https://github.com/sulu/sulu/blob/5c1717cbc50f279e9035cdc7a673c50dc2e18c09/src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg?short_path=7d478d8#L158

**Expected:**

![Capture d’écran du 2022-10-30 19-38-47](https://user-images.githubusercontent.com/36476595/198895782-197d93ba-769d-4431-bc16-63b0c7afe27e.png)

```svg
<glyph unicode="&#xe994;" glyph-name="upload" d="M512-96c-17.673 0-32 14.327-32 32v344.742l-90.74-80.66c-13.21-11.74-33.436-10.55-45.178 2.658-11.742 13.21-10.55 33.436 2.658 45.178l144 128c12.124 10.777 30.396 10.777 42.52 0l144-128c13.209-11.741 14.398-31.969 2.656-45.178-11.742-13.209-31.969-14.4-45.178-2.658L544 280.738V-64c0-17.673-14.327-32-32-32zM224 224C94.327 224 32 286.327 32 384c0 48.897 13.49 105.924 41.373 147.75 33.957 50.936 85.831 75.947 152.215 67.475C240.59 779.257 360.218 864 512.789 864c151.942 0 208.09-48.76 248.11-192.88C895.48 661.482 992 573.645 992 448c0-153.273-80.082-224-192-224-17.673 0-32 14.327-32 32 0 17.673 14.327 32 32 32 78.22 0 128 43.965 128 160 0 95.122-77.642 160-192 160-14.684 0-27.483 9.993-31.045 24.238C670.875 768.561 639.532 800 512.79 800 381.802 800 288 727.5 288 560c0-21.436-20.664-36.81-41.195-30.65-58.505 17.552-95.312 4.2-120.178-33.1C106.644 466.276 96 421.285 96 384c0-62.327 33.673-96 128-96 17.673 0 32-14.327 32-32 0-17.673-14.327-32-32-32z" />
```

I'd like to do a PR, but I have no idea of your build process for this file.

**Edit:** using Sulu 2.5

**Comment by alexander-schranz** [comment]
@Jupi007 Hello 👋 ,

we are using `icomoon`. Easiest way to update the `icomoon` icons is to download the current `selection.json`: https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/selection.json

Dragging the `selection.json` into [Icomoon app](https://icomoon.io/app/#/select) should use all our preconfigured settings again. (If you already used Icomoon I mostly do this in a private/incognito window to not mixup things with other project).

And then you should be able to replace the icon there. And download the pack again which can be unzipped into the same directory again.

**Comment by Jupi007** [comment]
Hi @alexander-schranz 👋
Okay, thanks :)
I will do this a bit later today.

**Comment by Jupi007** [comment]
A small question: `2.4` and `2.5` icon files are different from each other, should I do a PR for each?

**Comment by alexander-schranz** [comment]
@Jupi007 In this edge case it would be great. Normally we would solve the merge conflict when merging 2.4 -> 2.5 but we would in this case also need to regenerate the icomoon selection.json via the web app as the `selection.json` is not very "git friendly". So a PR for both branches in this edge case would make it easier for us so I can cherry pick the files of your 2.5 PR when merging 2.4 -> 2.5.

But I'm also fine to fix it only on 2.5 as it is just a small visual bug, which does not effect the functionality of Sulu so it isnt that important to be released also for 2.4. So it is up to you if you want to target 2.4 and 2.5 or only 2.5.

**Comment by Jupi007** [comment]
Okay, I'll do two PRs so :)
It is not a big deal for me to do it.

**Comment by Jupi007** [comment]
I'm doing a review of the full icon font, and some other icon are affected:

![image](https://user-images.githubusercontent.com/36476595/198981182-f0ad8cf2-f183-432e-823d-67437b5e1fe3.png)
![image](https://user-images.githubusercontent.com/36476595/198981210-0b7793d9-637b-4799-83a7-a8fec964fb81.png)
![image](https://user-images.githubusercontent.com/36476595/198981235-962005f1-14c7-4219-ad8c-1c84e223ba10.png)
![image](https://user-images.githubusercontent.com/36476595/198981368-c9d59638-44d4-43b9-ac48-8d9d4f8cb57b.png)
![Capture d’écran du 2022-10-31 10-56-10](https://user-images.githubusercontent.com/36476595/198981535-d31441d0-5bd3-424c-a192-fcd788b25413.png)
![Capture d’écran du 2022-10-31 10-56-04](https://user-images.githubusercontent.com/36476595/198981546-76808856-66c9-485a-98ae-1be9633b69dc.png)
![image](https://user-images.githubusercontent.com/36476595/198981739-95276cf8-7a38-4d62-90ed-17f0534571dc.png)

If it is okay for you, may I fix all of them?

**Comment by alexander-schranz** [comment]
@Jupi007 sure that is great 👍 . Thank you for working on this issue :)

**Comment by alexander-schranz** [comment]
Thank you. 👍 Icons are updated:

 - https://jsdocs.sulu.io/2.4/#icon
 - https://jsdocs.sulu.io/2.5/#icon
