### ISSUE TITLE
contact_selection content type produce infinite loading animation

### ISSUE THREAD

**Issue by tommysonsylverstone** [sulu/sulu#6874]
| Q | A
| --- | ---
| Sulu Version | 2.4.5
| PHP Version | 7.4.30
| DB Version | MySql 8.0.30 (Ubuntu 20.04)
| Browser Version | Chrome 106.0.5249.119

# Actual Behavior

In my sulu admin, the `contact_selection` will work fine the first time, but as soon as I'm quitting and coming back to my form, the content type doesn't show the contacts I've entered previously anymore and it's showing an infinite loading animation.
The fonctionnalities by clicking the icon are still here, but the previously selected contacts aren't checked on the list anymore, despite the datas being saved as it should.

Video example
https://www.youtube.com/watch?v=7ZN02E7QJlc

# Expected Behavior

The contacts are shown correctly and managable even after coming back to the form.

# Steps to Reproduce

1 - Configure a `contact_selection` content type in your config file
2 - insert 1 or more contacts
3 - reload your page/go back and come back to your form

# Tested stuff
- Tried the same with `account_selection` content type, but the bug isn't procuded.
- This happens both on articles and pages form

**Comment by alexander-schranz** [comment]
@tommysonsylverstone Thank you for reporting. Does this also happen if you add a `contact_selection` to a page template.

A infinite loading normally happens when a backend error is happening. Can you open your browsers dev tools and check the requests to the `/admin/api/contacts` there should be failing request. The error of that request would be very interesting. If there is no error the response still would be interesting. It could also be that there is an error in the selection itself so a JS error should then appear in the browser dev tools can you check also that one?

Would be nice if you could check if the error does also appear when just create a new `sulu/skeleton` and add there a contact_selection. So we are sure it is not related to anything in your project.

**Comment by tommysonsylverstone** [comment]
@alexander-schranz After checking the admin `profiler`, it seems very likely that the error is produced by something I did previously in my project. Here's the deal:
- I've followed [this pull request](https://github.com/sulu/sulu-demo/pull/91) to add another tab/data to a contact. In my case, it was a simple text field `text_editor`.
- In my profiler, I've got the following error
`[Semantical Error] line 0, col 1219 near 'App_Entity_Contact__class.freeText': Error: 'App_Entity_Contact__class' is not defined.`
`freeText` is the name of my `text_editor` content type.

So that means I've probably skipped a step or the `contact_selection` doesn't like when the original `Contact` class is extended ?

**Comment by alexander-schranz** [comment]
@tommysonsylverstone if you are in a custom tab. That is mostly a hint that your API does not return the `contacts` in the way the frontend expect it. So you need to have a look at your serializer configuration and methods which are serialzing.

The return of your JSON api should look like:

```json
{
    "contacts": [1, 2]
}
```

Mostly the error is that you are serialzing the `getContacts()` or whatever you named the property and that returns not only the IDs. So create a `getContactIds` method and serialize that method and not the `getContacts` or `contacts` property.

**Comment by alexander-schranz** [comment]
@tommysonsylverstone the error on overwriting sounds like there is something not correclty configured. Check again the configuration here: https://docs.sulu.io/en/2.5/cookbook/extend-entities.html specially the `sulu_contact` configuration.

And also check that nobody reference the `old` class. That should not be used in any `metadata` like list or entity orm metadata. Instead use the new class or the interface like here: https://github.com/sulu/sulu/blob/5c1717cbc50f279e9035cdc7a673c50dc2e18c09/src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Account.orm.xml#L61

**Comment by tommysonsylverstone** [comment]
My `sulu_contact.yaml` config is like this:
```
sulu_contact:
    objects:
        contact:
            model: App\Entity\Contact
            repository: Sulu\Bundle\ContactBundle\Entity\ContactRepository
```
As for the overriding of doctrine orm xml files, I don't know how to proceed. Also I'm trying to apply those changes to the `Contact` entity only, do I have to change anything about my `Account` entity to make it work too ?

**Comment by alexander-schranz** [comment]
@tommysonsylverstone no you don't need todo anything on core entities.

You only need to change maybe your own entities or any none sulu core bundles which have a relation to `Contact` entity.

So example if you are using a Third Party bundle which has a relation to `Contact` instead of `ContactInterface` it would be needed to fix that in the Third Party Bundle.

Also make sure that your doctrine metadata cache is cleared. There is some metadata clear command available under `bin/console list`.

**Comment by tommysonsylverstone** [comment]
I've tried running `bin/console doctrine:cache:clear-metadata`, one try with just this, another try with `bin/adminconsole cache:clear`, both didn't solved the issue. I also don't have any third party bundle that uses the `Contact` entity outside my own `App` .

I've also noticed something about the api url it's trying to getting to:
`http://localhost:8000/admin/api/contacts?flat=true&ids=2%2C3%2C6&locale=fr&page=1`
is the `%2C3%2C6` part normal ? I've looked up google on url encoding and it seems to translate as `>^` .
Also would you like I copy paste the doctrine query that's blocking the process?

**Comment by alexander-schranz** [comment]
How does the response of your API looks like? Where your `contact_selection` is used?

**Comment by tommysonsylverstone** [comment]
The API response looks like this:
```
{code: 0,…}
code
: 
0
errors
: 
[,…]
0
: 
"Doctrine\\ORM\\Query\\QueryException: SELECT SuluMediaBundle_Media.id AS avatar, CONCAT(App_Entity_Contact.firstName, CONCAT(' ', App_Entity_Contact.lastName)) AS fullName, App_Entity_Contact.firstName AS firstName, App_Entity_Contact.lastName AS lastName, App_Entity_Contact.mainEmail AS mainEmail, Sulu_Bundle_ContactBundle_Entity_Account.name AS account, SuluContactBundle_Address.city AS city, SuluContactBundle_Address.zip AS zip, SuluContactBundle_Address.street AS street, SuluContactBundle_Address.number AS number, CONCAT(SuluContactBundle_Address.street, CONCAT(' ', SuluContactBundle_Address.number)) AS addressLine, SuluContactBundle_Address.state AS state, SuluContactBundle_Address.countryCode AS countryCode, App_Entity_Contact.mainPhone AS mainPhone, App_Entity_Contact.id AS id, App_Entity_Contact.mainFax AS mainFax, App_Entity_Contact.mainUrl AS mainUrl, App_Entity_Contact.created AS created, App_Entity_Contact.changed AS changed, App_Entity_Contact.birthday AS birthday, SuluContactBundle_ContactTitle.title AS title, App_Entity_Contact.salutation AS salutation, App_Entity_Contact.formOfAddress AS formOfAddress, SuluContactBundle_Position.position AS position, App_Entity_User.username AS user, App_Entity_User.locked AS userLocked, App_Entity_Contact__class.freeText AS freeText FROM App\\Entity\\Contact App_Entity_Contact LEFT JOIN App_Entity_Contact.avatar SuluMediaBundle_Media LEFT JOIN App_Entity_Contact.accountContacts SuluContactBundle_AccountContact WITH SuluContactBundle_AccountContact.main = true LEFT JOIN SuluContactBundle_AccountContact.account Sulu_Bundle_ContactBundle_Entity_Account LEFT JOIN App_Entity_Contact.contactAddresses SuluContactBundle_ContactAddress WITH SuluContactBundle_ContactAddress.main = TRUE LEFT JOIN SuluContactBundle_ContactAddress.address SuluContactBundle_Address LEFT JOIN App_Entity_Contact.title SuluContactBundle_ContactTitle LEFT JOIN SuluContactBundle_AccountContact.position SuluContactBundle_Position LEFT JOIN App\\Entity\\User App_Entity_User WITH App_Entity_User.contact = App_Entity_Contact.id WHERE App_Entity_Contact.id IN (:ids) ORDER BY App_Entity_Contact.id ASC in /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:21\nStack trace:\n#0 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(546): Doctrine\\ORM\\Query\\QueryException::dqlError()\n#1 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(652): Doctrine\\ORM\\Query\\Parser->semanticalError()\n#2 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(312): Doctrine\\ORM\\Query\\Parser->processDeferredIdentificationVariables()\n#3 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(408): Doctrine\\ORM\\Query\\Parser->getAST()\n#4 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(274): Doctrine\\ORM\\Query\\Parser->parse()\n#5 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(286): Doctrine\\ORM\\Query->parse()\n#6 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\\ORM\\Query->_doExecute()\n#7 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\\ORM\\AbstractQuery->executeIgnoreQueryCache()\n#8 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(890): Doctrine\\ORM\\AbstractQuery->execute()\n#9 /var/www/pqn-a/project/vendor/sulu/sulu/src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php(282): Doctrine\\ORM\\AbstractQuery->getArrayResult()\n#10 /var/www/pqn-a/project/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Controller/ContactController.php(337): Sulu\\Component\\Rest\\ListBuilder\\Doctrine\\DoctrineListBuilder->execute()\n#11 /var/www/pqn-a/project/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Controller/ContactController.php(315): Sulu\\Bundle\\ContactBundle\\Controller\\ContactController->prepareListResponse()\n#12 /var/www/pqn-a/project/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Controller/ContactController.php(260): Sulu\\Bundle\\ContactBundle\\Controller\\ContactController->getList()\n#13 /var/www/pqn-a/project/vendor/symfony/http-kernel/HttpKernel.php(152): Sulu\\Bundle\\ContactBundle\\Controller\\ContactController->cgetAction()\n#14 /var/www/pqn-a/project/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#15 /var/www/pqn-a/project/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#16 /var/www/pqn-a/project/public/index.php(66): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#17 {main}\n\nNext Doctrine\\ORM\\Query\\QueryException: [Semantical Error] line 0, col 1219 near 'App_Entity_Contact__class.freeText': Error: 'App_Entity_Contact__class' is not defined. in /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43\nStack trace:\n#0 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(546): Doctrine\\ORM\\Query\\QueryException::semanticalError()\n#1 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(652): Doctrine\\ORM\\Query\\Parser->semanticalError()\n#2 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(312): Doctrine\\ORM\\Query\\Parser->processDeferredIdentificationVariables()\n#3 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(408): Doctrine\\ORM\\Query\\Parser->getAST()\n#4 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(274): Doctrine\\ORM\\Query\\Parser->parse()\n#5 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(286): Doctrine\\ORM\\Query->parse()\n#6 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\\ORM\\Query->_doExecute()\n#7 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\\ORM\\AbstractQuery->executeIgnoreQueryCache()\n#8 /var/www/pqn-a/project/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(890): Doctrine\\ORM\\AbstractQuery->execute()\n#9 /var/www/pqn-a/project/vendor/sulu/sulu/src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php(282): Doctrine\\ORM\\AbstractQuery->getArrayResult()\n#10 /var/www/pqn-a/project/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Controller/ContactController.php(337): Sulu\\Component\\Rest\\ListBuilder\\Doctrine\\DoctrineListBuilder->execute()\n#11 /var/www/pqn-a/project/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Controller/ContactController.php(315): Sulu\\Bundle\\ContactBundle\\Controller\\ContactController->prepareListResponse()\n#12 /var/www/pqn-a/project/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Controller/ContactController.php(260): Sulu\\Bundle\\ContactBundle\\Controller\\ContactController->getList()\n#13 /var/www/pqn-a/project/vendor/symfony/http-kernel/HttpKernel.php(152): Sulu\\Bundle\\ContactBundle\\Controller\\ContactController->cgetAction()\n#14 /var/www/pqn-a/project/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#15 /var/www/pqn-a/project/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#16 /var/www/pqn-a/project/public/index.php(66): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#17 {main}"
message
: 
"[Semantical Error] line 0, col 1219 near 'App_Entity_Contact__class.freeText': Error: 'App_Entity_Contact__class' is not defined."
```

My `contact_selection` is used in my articles.xml config file.

**Comment by alexander-schranz** [comment]
@tommysonsylverstone I don't mean that API I mean the API of your resources which returns the data for the `contact_selection`.

**Comment by alexander-schranz** [comment]
But also in the list response there is an error which is related to your project code.

Looks like you extended the `contacts.xml` and did configure there something wrong that produces: `App_Entity_Contact__class.freeText AS freeText` instead of `App_Entity_Contact.freeText AS freeText`:

Maybe you did not use the correct string or variable in your custom list xml: https://github.com/sulu/sulu/blob/5c1717cbc50f279e9035cdc7a673c50dc2e18c09/src/Sulu/Bundle/ContactBundle/Resources/config/lists/contacts.xml#L196

**Comment by tommysonsylverstone** [comment]
> 

That was it !

My field configuration was like that:
```
<property name="freeText" translation="Texte libre">
    <field-name>freeText</field-name>
    <entity-name>App\Entity\Contact::class</entity-name>
</property>
```
when you just have to declare your Entity without the `::class` at the end.

Many thanks @alexander-schranz !

**Comment by alexander-schranz** [comment]
Yeah you can not use `App\Entity\Contact::class` here only `%parameters%` or real FCQN no `::class`.

But good if it only was that.
