### ISSUE TITLE
Add emoji support for url slugger

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6882]
# Problem description

Currently emojis are just removed and not replaced by the name when slugging a title with emoji for it. It would be nice to slug them also.

# Proposed solution

In Symfony 6.2 a new `withEmoji`: https://symfony.com/blog/new-in-symfony-6-2-better-emoji-support

For bc reasons it would require something like following that we run not into any error with Symfony 6.1 or lower:

```php
if (method_exists($slugger, 'withEmoji') {
    $slugger->withEmoji();
}
```

The class doing the slug can be found here: https://github.com/sulu/sulu/blob/2.5/src/Sulu/Component/PHPCR/PathCleanup.php and the slugger service definition here: https://github.com/sulu/sulu/blob/08863981d9e607dd1432db68eec2dac710732f74/src/Sulu/Bundle/CoreBundle/Resources/config/content.xml#L36

<br/>
<br/>

> **Note**
> This issue was specially created for beginners as it is a easy to implement. So it is perfectly for beginners and first time contributors. Experienced contributors should let this open for beginners.

**Comment by nozarashi20** [comment]
Hi @alexander-schranz , I can tackle this one

**Comment by alexander-schranz** [comment]
@nozarashi20 sure, pull request welcome :)
