### ISSUE TITLE
Default avatar got bad contrast

### ISSUE THREAD

**Issue by Jupi007** [sulu/sulu#6884]
| Q | A
| --- | ---
| Sulu Version | 2.5 and 2.4 (not tested but same code)

# Actual Behavior

The default user avatar got very bad contrast: the icon almost blend in its background.

![Capture d’écran du 2022-11-02 19-57-45](https://user-images.githubusercontent.com/36476595/199594379-de2b05e9-f67b-4538-a867-4c670fa32802.png)

# Possible Solutions

Something like this would be better imo:

![image](https://user-images.githubusercontent.com/36476595/199595464-48761036-5a6d-4692-8a32-b48a98b6bd41.png)

**Comment by alexander-schranz** [comment]
@Jupi007 aslong as we don't add additional blue I'm fine with it. If the blue does not yet exist and this variant we need to discuss it with the style guide.

**Comment by Jupi007** [comment]
What I propose is to use some kind of transparent white.

**Comment by alexander-schranz** [comment]
@Jupi007 would not introduce a new color currently, isn't there something which already matches? Else I need to recheck the things with the existing styleguide and designer.

**Comment by Jupi007** [comment]
Oh okay, I understand.
Let me check if I can find some color which fit in your palette.

**Comment by Jupi007** [comment]
What do you think of this:

![Capture d’écran du 2022-11-09 14-26-17](https://user-images.githubusercontent.com/36476595/200842573-98c70eb2-706e-49c0-9520-f88d26d0697e.png)

I used:

```scss
color: $alto;
background-color: $mirage;
```

**Comment by alexander-schranz** [comment]
Looks fine for me 👍

**Comment by Jupi007** [comment]
Great!
Let me do a PR so.

**Comment by alexander-schranz** [comment]
Fixed in #6902
