### ISSUE TITLE
[RFC] Adding admin resource URLs to FOSJsRouter automatically

### ISSUE THREAD

**Issue by stollr** [sulu/sulu#6886]
# Problem description

I wanted to extend the admin UI with a custom entity and followed the [docs](https://docs.sulu.io/en/latest/book/extend-admin.html). But when I tried to open the list view in the browser I got the following javascript error:

> "[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@111]' Error: The route "app.api_association.index" does not exist."

After some debugging I found out that the route of the action was removed in `FOS\JsRoutingBundle\Extractor\ExposedRoutesExtractor::getRoutes()` because there was no matching regex pattern for my route. In Sulu's AdminBundle the general pattern `(.+\.)?c?get_.*` [is added](https://github.com/sulu/sulu/blob/c89235ae5db54e4c3b4a0c790370ec2ccbf78667/src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php#L106) to the extension config `fos_js_routing.routes_to_expose`.

But if you do not name your routes the same way as it is done in the documentation, you will get the error mentioned above.

# Proposed solution

Imho it would be better to take the URLs that are already configured by the developer and expose them automatically instead of forcing the developer to follow a convention (which is not documented anywhere). As far as I understand we may take the routes defined in `sulu_admin.resources.*.routes.*` and add them as routes to be exposed to the FOSJsRouting configuration.

What do you think? If you like this idea I'll create a PR.

**Comment by alexander-schranz** [comment]
It definitely make sense for me to expose all routes which are configured as resource routes as they are used by the admin JS. 

Think creating a compilerpass and adding the addition routes same way as here: https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/DependencyInjection/FOSJsRoutingExtension.php#L48-L50 should do the job.

**Comment by niklasnatter** [comment]
Using the configuration to determine what to expose is a great idea! 🙂

**Comment by alexander-schranz** [comment]
Thank you for implementing this 🎉  will be part of the upcoming 2.6 release :)
