### ISSUE TITLE
Longer help texts lead to overflow and overlapping content

### ISSUE THREAD

**Issue by FlorianBoe** [sulu/sulu#6939]
| Q | A
| --- | ---
| Sulu Version | 2.5.4
| PHP Version |
| DB Version |
| Browser Version |

# Actual Behavior

Defined info texts created in the configuration with info_text are limited to a maximum height. Longer help texts lead to overflow and overlapping content.

# Expected Behavior

The description-label should adapt in height to the respective content.

# Steps to Reproduce

Simply define a long text as info_text.

<img width="576" alt="Bildschirm­foto 2022-12-14 um 16 14 30" src="https://user-images.githubusercontent.com/663702/207635277-bb03742e-5af2-4ac8-863f-92c1a31f5169.png">

# Possible Solutions

If a minimum is necessary for the description-label, this should be defined as min-height.

<img width="169" alt="Bildschirm­foto 2022-12-14 um 16 20 01" src="https://user-images.githubusercontent.com/663702/207635521-e05df7e7-d6ae-47ec-8a46-42e18455ae7f.png">

**Comment by alexander-schranz** [comment]
@FlorianBoe I'm fine to switch this to `min-height` we shoud just test the different case when there are `colspan="6"` used on the properties to define side by side properties. Do you want to create a pull request for this?

**Comment by FlorianBoe** [comment]
I am happy to make a pull request for this change. You are right that specifying `colspan="6"` leads to problems, because not all elements have the same height anymore and the multi-column layout is solved by floats.

<img width="890" alt="Bildschirm­foto 2022-12-14 um 21 44 07" src="https://user-images.githubusercontent.com/663702/207710436-b606d7c0-cec1-4b37-b8e0-9c0935430bf6.png">

**Comment by alexander-schranz** [comment]
@FlorianBoe floating is the expected behaviour currently for the grid as required for some special layouts. As nothing is overlapping its currently fine.

The second row can in this case just wrapped inside a section colspan 12 to avoid the floating there. So its fine.
