### ISSUE TITLE
Restore trash item without security context fails

### ISSUE THREAD

**Issue by Jupi007** [sulu/sulu#6969]
| Q | A
| --- | ---
| Sulu Version | 2.5.5
| PHP Version | 8.1.11

# Actual Behavior

Trying to restore a trash item without a security context always fails at security check.
I can provide a minimal reproduction repository is needed.

# Expected Behavior

The item should be allowed to be restored, even if the security context is null.

# Possible Solutions

In `TrashItemController.php`, the security check should be conditionally call, only if the item security context is not null:

https://github.com/sulu/sulu/blob/0c564eb9b8df8a163dc6a4381c710b003f80641a/src/Sulu/Bundle/TrashBundle/UserInterface/Controller/Admin/TrashItemController.php#L290-L298

```php
        if (null !== $trashItem->getResourceSecurityContext()) {
            $this->securityChecker->checkPermission(
                // ...
            );
        }
```

**Comment by Jupi007** [comment]
Maybe the best solution would rather be to handle a null `securityContext` in sulu `SecurityChecker`:

https://github.com/sulu/sulu/blob/0fccd621763eaedef3653ba307f1494fc12b1c99/src/Sulu/Component/Security/Authorization/SecurityChecker.php#L43-L46

```php
if (!$subject || ($subject instanceof SecurityCondition && null == $subject->getSecurityContext())) {
    // if there is no subject or no security context, the operation is allowed, since we have nothing to check against
    return true;
}
```

**Comment by Jupi007** [comment]
I created a minimal reproducing repo based on sulu-skeleton: https://github.com/Jupi007/sulu-issue-6969

**Comment by mamazu** [comment]
Fixed by the merge request.
