### ISSUE TITLE
Localization '/sl' landing page redirection to '/en'

### ISSUE THREAD

**Issue by Kami0n** [sulu/sulu#6972]
| Q | A
| --- | ---
| Sulu Version | 2.5.5
| PHP Version | 8.2.0
| DB Version | MySQL 
| Browser Version | 10.4.27-MariaDB 

# Actual Behavior

Hello, I'm trying to set up a multilingual Sulu site and I'm having trouble getting one of my languages working. I've set my localizations in my webspace file like this:

```
<localizations>
    <localization language="en" default="true" />
    <localization language="sl" />
    <localization language="it" />
</localizations>
```

I've run the `php bin/adminconsole sulu:document:initialize --purge` command, but when I try to go to link `/sl` it redirects (301) me to `/en` .
`/it` works as expected. 
If I try to change from `sl` to `si` it also works as expected.
I also tried `de`, `sk`, `si` and all of them work as expected.

My portals code:
```
<environment type="dev">
    <urls>
        <url>{host}/{localization}</url>
    </urls>
</environment>
```

`sl` is a ISO 639-1 language code for Slovenian language.

# Expected Behavior

Every language should have its own landing page. No redirections to other languages.

**Comment by alexander-schranz** [comment]
Mostly this happens if your browser has an old 301 cached. So check your browsers caches or try woth different browser. Else check the /_profiler to check which controller creates the redirect.

**Comment by Kami0n** [comment]
Thank you. It was a browser cache issue.
