### ISSUE TITLE
Migrate deprecations to symfony/deprecation-contracts

### ISSUE THREAD

**Issue by YetiCGN** [sulu/sulu#6977]
# Problem description

While Symfony now uses a central function `trigger_deprecation` from the package `symfony/deprecation-contracts` which can be overriden to do nothing in production, Sulu triggers `E_USER_DEPRECATED` itself in several places. This makes silencing deprecation INFO messages hard.

# Proposed solution

Require `symfony/deprecation-contracts` and refactor all occurences of `@\trigger_error(\sprintf('The "%s" method is deprecated on "%s" use "..." instead.', __METHOD__, __CLASS__), \E_USER_DEPRECATED);` to use `trigger_deprecation()`.

**Comment by alexander-schranz** [comment]
As this is the new way in Symfony we should switch to that one.

Added `Easy Pick` here as it seems like a straight forward task, if you want todo it let us know here via a comment if you start.

**Comment by YetiCGN** [comment]
Okay, I'm on it.
