### ISSUE TITLE
Unable to initialize a new Webspace

### ISSUE THREAD

**Issue by juagarc4** [sulu/sulu#6987]
# Problem description
After creating a  new webspace in the configuration, that is, the corresponding xml file in the directory webspaces, I have to run the command `php bin/adminconsole sulu:document:initialize`

It is fine if you can access to the server an execute the command. It is even possible if you control the deployment process and know when exactly the site is available, but what about the case in which you don't have any access to the server or to the deployment process? How can I execute the command to enable the new webspace?

Thanks in advance
Regards

**Comment by alexander-schranz** [comment]
@juagarc4 There is currently no way todo this. Sulu is build for enterprise websites which we expect have access to the servers, currently there is no way to use Sulu without having possibility to add CLI commands to your deploy process.

Already Sulu requires to run `bin/console sulu:build ...` to setup Sulu once on the server. So SSH Connection and access to run php commands is a minimum requirement for running Sulu. We are also not focused on changing this currently, as Sulu is heavily build on top of Symfony which already requires to rebuild the container cache via its `bin/console cache:clear` command on every deploy.

Even if you don't have direct SSH connection to the server, your deployement process should have possiblity to run additional commands as already the `bin/console cache:clear`. We normally recommand for basic project to use [`deployer`](https://sulu.io/blog/deploy-sulu-with-deployer), which is really easy to setup and provides a save green/blue deployment process.
