### ISSUE TITLE
PHPUnit 10 Upgrade

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6988]
# Problem description

We can Upgrade Sulu 2.5 to PHPUnit 10 as Sulu 2.5 already requires atleat PHP 8.1.

# Proposed solution

Upgrade to PHPUnit 10 with `rector`:

 - https://getrector.com/blog/how-to-upgrade-to-phpunit-10-in-diffs
 - https://phpunit.de/announcements/phpunit-10.html

**Comment by mamazu** [comment]
In the current version of the `composer.json` in the 2.5 branch 8.0 is still allowed.

**Comment by alexander-schranz** [comment]
@mamazu good catch. Then maybe target 2.6 😄

**Comment by mamazu** [comment]
Currently this isn't possible. The `phpspec/prophecy` package doesn't yet support phpunit 10, I just checked.

**Comment by alexander-schranz** [comment]
For preparing maybe we could test out the current PHPUnit 10 branch/pull request of prophecy to give maybe prophecy already feedback if it works with PHPUnit 10 or not.

What already could be targetted are the deprecations like:

 - assertObjectHasAttribute() is deprecated and will be removed in PHPUnit 10.
 - Expecting E_WARNING and E_USER_WARNING is deprecated and will no longer be possible in PHPUnit 10.
 
Currently we can test PHPUnit 10 with:

```
    "require-dev": {
        "phpspec/prophecy": "^1.18@dev",
        "phpspec/prophecy-phpunit": "^2.1@dev",
        "phpunit/phpunit": "^10.2"
    }
```

**Comment by alexander-schranz** [comment]
@TheCadien said he will tackle this :)
