### ISSUE TITLE
Content Security Policy (CSP) for SULU

### ISSUE THREAD

**Issue by domaingood** [sulu/sulu#7000]
Up-to-date with the latest [CSP Level 3 Working Draft](https://www.w3.org/TR/CSP/)
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Policy is automatically optimized to remove duplicate directives and reduce header length
Policy Violation logging integrations:

Automatically adds 'unsafe-inline' to individual requests when necessary for core libraries ([core/ckeditor]
Dispatches an event to allow other modules to alter policies for each request
The included Content Security Policy Extras module provides additional security hardening by altering core services.

**Comment by alexander-schranz** [comment]
Hello @domaingood,
 
Im not understanding correctly what you proposal target is. What you directly want to change in sulu, or what sulu should provide. Can you expose it more?

Maybe #6533 is something which targets the same?

**Comment by jaydul09** [comment]
yes i want same as https://github.com/sulu/sulu/issues/6533

**Comment by alexander-schranz** [comment]
Then closing this in favor of #6533 to avoid duplications.
