### ISSUE TITLE
Fix test-workflow state badge in README files

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#7010]
| Q | A
| --- | ---
| Sulu Version | 
| PHP Version | 
| DB Version | 
| Browser Version | 

# Actual Behavior

![Bildschirmfoto 2023-02-15 um 14 07 57](https://user-images.githubusercontent.com/1698337/219035989-4cf6bee3-a491-44bb-8670-78784a612806.png)

# Expected Behavior

Badge should be outputted correctly. For this the READMEs need to beupdated see: [https://github.com/badges/shields/issues/8671](https://github.com/badges/shields/issues/8671)

 - [x] sulu/skeleton
 - [x] sulu/sulu
 - [x] sulu/SuluFormBundle
 - [x] sulu/SuluCommunityBundle
 - [x] sulu/SuluCommentBundle
 - [x] sulu/SuluRedirectBundle
 - [ ] sulu/SuluContentBundle
 - [x] sulu/SuluArticleBUndle
 - [x] sulu/SuluHeadlessBundle
 - [x] sulu/SuluSyliusConsumerBundle
 - [x] sulu/SuluSyliusProducerPlugin
 - [x] sulu/SuluAutomationBundle
 - [x] sulu/messenger

**Comment by alexander-schranz** [comment]
@mamazu one thing was missing in the list: https://github.com/sulu/messenger/ do you want tackle that also :)

**Comment by mamazu** [comment]
@alexander-schranz Sure: sulu/messenger#5

**Comment by alexander-schranz** [comment]
@mamazu Thank you!
