### ISSUE TITLE
CannotEvaluateTokenException throw exception with array $entity

### ISSUE THREAD

**Issue by Jupi007** [sulu/sulu#7013]
| Q | A
| --- | ---
| Sulu Version | 2.4 and 2.5
| PHP Version | Unrelated
| DB Version | Unrelated
| Browser Version | Unrelated

# Actual Behavior

The `Sulu\Bundle\RouteBundle\Generator\SymfonyExpressionTokenProvider::provide()` method can handle a non-object `$entity` parameter, and it is correctly managed in the method:

https://github.com/sulu/sulu/blob/0d92f0a3e837809333077fcedc2bd43f2752d7e2/src/Sulu/Bundle/RouteBundle/Generator/SymfonyExpressionTokenProvider.php#L59-L63

If something went wrong during the expression language evaluation, a `CannotEvaluateTokenException` is throw, but its constructor can only handle object `$entity`, cause to `\get_class($entity)`:

https://github.com/sulu/sulu/blob/0d92f0a3e837809333077fcedc2bd43f2752d7e2/src/Sulu/Bundle/RouteBundle/Generator/CannotEvaluateTokenException.php#L34-L38

With php versions from 8.0, this throw a `TypeError`.

# Expected Behavior

The `CannotEvaluateTokenException` should be instantiated without problem.

# Steps to Reproduce

By define a sulu `route_schema` with a custom entity, and by trying to use an inexistent property.

# Possible Solutions

Check if `$entity` is an object before call `get_class()`, and call `gettype()` if false:

```diff
    parent::__construct(
-       \sprintf('Cannot evaluate token "%s" for entity with type "%s"', $token, \get_class($entity)),
+       \sprintf('Cannot evaluate token "%s" for entity with type "%s"', $token, \is_object($entity) ? \get_class($entity) : \gettype($entity)),
        0,
        $previous
    );
```

**Comment by mamazu** [comment]
Fixed in the attached merge request.
