### ISSUE TITLE
Adding translations as shown in the documentation cause Invalid type for path "sulu_core.locales.translations". Expected "scalar", but got "array".

### ISSUE THREAD

**Issue by Nape** [sulu/sulu#7033]
| Q | A
| --- | ---
| Sulu Version | 2.4.11
| PHP Version | 7.4.12
| DB Version | MySQL 5.7.35)

# Actual Behavior
```


In ScalarNode.php line 36:
                                                                                               
  Invalid type for path "sulu_core.locales.translations". Expected "scalar", but got "array".  

```
**Adding this in config/packages/sulu_core.yaml**
sulu_core:
    locales:
        en: English
        fr: French
    translations:
        - en
        - fr

As mention in the documentation cause : Invalid type for path "sulu_core.locales.translations". Expected "scalar", but got "array". 

[https://docs.sulu.io/en/2.4/book/getting-started.html](https://docs.sulu.io/en/2.4/book/getting-started.html)

# Expected Behavior

```

Language: en
------------

 ! [NOTE] Download skipped because Sulu includes a translation for the language "en" per default.                       


Language: fr
------------

Starting download for the "sulu/sulu" project in "fr"
Extract ZIP archive...

 ----------- -------------- 
  Package     Translations  
 ----------- -------------- 
  sulu/sulu   738           
 ----------- -------------- 

Writing language fr into translations folder


```

# Possible Solutions

sulu_core:
    locales:
        en: English
        fr: French
-----OMIT THIS PART---
    translations:
        - en
        - fr
-----OMIT THIS PART---

**Comment by mamazu** [comment]
Works in the latest version 2.5.13
