### ISSUE TITLE
Element '{http://gediminasm.org/schemas/orm/doctrine-extensions-mapping}tree-left': No matching global element declaration available, but demanded by the strict wildcard.

### ISSUE THREAD

**Issue by yivi** [sulu/sulu#7057]
| Q | A
| --- | ---
| Sulu Version | 2.5.8
| PHP Version | 8.1.17
| DB Version | 15.2

Brand-new Sulu installation, just created with `composer create-project sulu/skeleton my-project`.

When running `bin/adminconsole sulu:build dev` I get libXML validation errors:

```
In MappingException.php line 1005:

  libxml error: Element '{http://gediminasm.org/schemas/orm/doctrine-extensions-mapping}tree-left': No matching global element declaration available, but demanded by the strict wildcard.
   in /Users/yivi/Projects/personal/weblog-sulu/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Collection.orm.xml at line 13
  libxml error: Element '{http://gediminasm.org/schemas/orm/doctrine-extensions-mapping}tree-right': No matching global element declaration available, but demanded by the strict wildcard.
   in /Users/yivi/Projects/personal/weblog-sulu/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Collection.orm.xml at line 16
  libxml error: Element '{http://gediminasm.org/schemas/orm/doctrine-extensions-mapping}tree-level': No matching global element declaration available, but demanded by the strict wildcard.
   in /Users/yivi/Projects/personal/weblog-sulu/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Collection.orm.xml at line 19
  libxml error: Element '{http://gediminasm.org/schemas/orm/doctrine-extensions-mapping}tree-parent': No matching global element declaration available, but demanded by the strict wildcard.
   in /Users/yivi/Projects/personal/weblog-sulu/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Collection.orm.xml at line 52
  libxml error: Element '{http://gediminasm.org/schemas/orm/doctrine-extensions-mapping}tree': No matching global element declaration available, but demanded by the strict wildcard.
   in /Users/yivi/Projects/personal/weblog-sulu/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Collection.orm.xml at line 55

```

<img width="1243" alt="imagen" src="https://user-images.githubusercontent.com/1815039/231537185-d4f375ef-03b7-48f8-9325-67869b6681fd.png">

I have made no modifications besides adding these lines to `config/packages/sulu_admin.yaml`:

```yaml
sulu_core:
    locales:
        en: English
        es: Castellano
    translations:
        - en
        - es
```

**Comment by rommelfreddy** [comment]
can confirm. same issue without changing anything

**Comment by chirimoya** [comment]
Looks like it's related to https://github.com/doctrine/DoctrineBundle/issues/1643

Try to add the following to your `composer.json`:

```
    "conflict": {
        "doctrine/orm": "2.14.2"
     }
```

and run `composer update doctrine/orm` which should downgrade your `doctrine/orm` package to `2.14.1`

**Comment by yivi** [comment]
You are right. I was (slowly and painstakingly) reaching that same conclusion, although I hadn't found that issue yet.

Might be worth releasing a patch version with the `conflict` rule in it?

Thanks for the help.

**Comment by MemoICT** [comment]
Same here.

Using `composer create-project sulu/skeleton <project> --no-install` and adding conflict in the composer.json worked for me

**Comment by alexander-schranz** [comment]
Thx for the reports. For current state @sulu will conflicting the incompatible `doctrine/orm` version. Two new versions are tagged [2.4.13](https://github.com/sulu/sulu/releases/tag/2.4.13) / [2.5.9](https://github.com/sulu/sulu/releases/tag/2.5.9) adding the conflict.

For future update of the issue please subscribe the `doctrine/orm` issue [here](https://github.com/doctrine/DoctrineBundle/issues/1643).
