### ISSUE TITLE
Multiple relations between custom entities showing incorrect values.

### ISSUE THREAD

**Issue by stemod** [sulu/sulu#7073]
| Q | A
| --- | ---
| Sulu Version | tested on 2.5.8 and 2.5.9
| PHP Version | 8.1.x
| DB Version | MySQL 8.0

# Actual Behavior

When adding a custom entity that has a relation to another entity multiple times the list view displays incorrect values (only the last one is correct).

# Expected Behavior

Show the correct value.

# Steps to Reproduce

Create two entties: (e.g.)
Domain (id, account, ownerHandle, adminHandle, techHandle, zoneHandle)
DomainHandle (id, companyName)

Now create a domains.xml list view which displays the field companyName of every handle.
Only the value of the last handle defined in the XML will be displayed for all handles.

**Comment by alexander-schranz** [comment]
If you join the same entity multiple times you need to replace `entity-name` with an alias:

```xml
    <joins name="adminHandle" ref="adminHandle">
        <join>
            <entity-name>adminHandle</entity-name> <!-- not class name here -->
            <field-name>App\Entity\Domain.adminHandle</field-name>
        </join>
    </joins>
    <joins name="techHandle" ref="techHandle">
        <join>
            <entity-name>techHandle</entity-name> <!-- not class name here -->
            <field-name>App\Entity\Domain.techHandle</field-name>
        </join>
    </joins>
```

And in the property tag also use the alias instead of the class name. The `entity-name` is here little bit confusing more see it as a doctrine query builder where that field is the `alias`.
