### ISSUE TITLE
VIEW permissions for User Roles are not working like expected

### ISSUE THREAD

**Issue by stefliekens** [sulu/sulu#7088]
| Q | A
| --- | ---
| Sulu Version | 2.5.x 
| PHP Version | 8.1

# Actual Behavior

When using the User Roles for Sulu features like snippets, contacts, categories, tags, ... I can choose to enable only the VIEW permission. 
<img width="876" alt="image" src="https://github.com/sulu/sulu/assets/3245491/bce6783a-307e-4735-b2a2-b404944e1dcf">

After logging in with an admin user with the related user role, I cannot see the related navigation items or access the list views/pages. Now those navigation items and list views require the EDIT permission.  

The same behavior you can see in the ArticleBundle and FormBundle.

# Expected Behavior

As an admin user with only VIEW-permissions I should see:
- the corresponding navigation item
- the list view/page without add or delete buttons
- an edit or view action to open the form without a save button (see screenshot below)
![image](https://github.com/sulu/sulu/assets/3245491/2ddd655d-6363-4043-87b2-400eb9c1ecdc)

# Steps to Reproduce

- Create a new User Role
- Enable only VIEW permission for Setting > categories
- Create an new admin account (Contact > People) and assign the new created User Role
- Login with the admin account
- You will see there is no "Settings > Categories" navigation item in the sidebar

**Comment by mamazu** [comment]
Fixed in the merged merge request.
