### ISSUE TITLE
Translation break page editing - contentBlock

### ISSUE THREAD

**Issue by marek5816** [sulu/sulu#7090]
| Q | A
| --- | ---
| Sulu Version | 2.5.4
| PHP Version | 8.1.16
| DB Version | MarianDB
| Browser Version | Firefox

# Actual Behavior

When I am using custom translation, when I open page editing where is **contentBlock**, sulu give weird error `Missing parameter token in Sulu\Bundle\PreviewBundle\UserInterface\Controller\PreviewController` 

# Steps to Reproduce

1. Use translation [admin.sk.zip](https://github.com/sulu/sulu/files/11678520/admin.sk.zip)
2. Create contentBlock
```
        <block name="specifications" default-type="contentBlock">
            <meta>
                <title lang="en">Specifikacie</title>
            </meta>

            <params>
                <param name="add_button_text">
                    <meta>
                        <title lang="en">Pridat polozku</title>
                    </meta>
                </param>
            </params>

            <types>
                <type name="contentBlock">
                    <meta>
                        <title lang="en">Polozka</title>
                    </meta>

                    <properties>
                        <property name="title" type="text_line" colspan="3">
                            <meta>
                                <title lang="en">Nazov</title>
                            </meta>
                        </property>

                        <property name="text" type="text_line" colspan="3">
                            <meta>
                                <title lang="en">Popis</title>
                            </meta>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
```
3. Open page editing

**Comment by alexander-schranz** [comment]
Thx for creating an issue,

Do you know which specific translation key does result in the error or does the error also appear when you create a empty `admin.sk.json` with just `{}` in it?

Another quesiton what is the Language of the Page you are editing and what is the System Language of the user you are logged in? (Profil System Language)

**Comment by marek5816** [comment]
`Do you know which specific translation key does result in the error or does the error also appear when you create a empty admin.sk.json with just {} in it?`
EDIT - Yes, I created empty translation, the error is same. (so sulu is maybe trying to access missing translation?)
There is not any information about what translation make this error, because the error message does say anything about translation

`Another quesiton what is the Language of the Page you are editing and what is the System Language of the user you are logged in? (Profil System Language)`
Page language is set to EN, system language is set for this translation what I provided so SK

**Comment by alexander-schranz** [comment]
Loading of the `.json` format is not part of sulu this is directly handled by symfony translation component and so we can not optimize here any error message if the file is invalid.

If you want to switch your system language to `sk` you can configure it like here: https://docs.sulu.io/en/2.5/book/getting-started.html. If you want to translate the whole interface we can add also SK to crowdin where our community works on the translations: https://sulu.crowdin.com/sulusulu  

I will close the issue as we can not optimize here something as symfony loads the translation files.
