### ISSUE TITLE
Contact selection is reordering entries by id 

### ISSUE THREAD

**Issue by thomas-peter-juweliere** [sulu/sulu#7094]
| Q | A
| --- | ---
| Sulu Version | 2.5.9
| PHP Version | 8.2
| DB Version | MySQL 5.7.39
| Browser Version | Chrome 114.0.5735.90

# Actual Behavior
When I open a block with a contact selection. All entries are automatically sorted by ID and the saved sorting is overwritten.

# Expected Behavior
The list keeps the saved order when opened.

# Steps to Reproduce
Create a block with a contact selection. Add some contacts. Sort them manually. Save the block, reload the admin and edit it again.

![sorting-error](https://github.com/sulu/sulu/assets/117661087/bd258183-ee70-49ab-ae8c-fc8bd7305190)

**Comment by alexander-schranz** [comment]
Hello @thomas-peter-juweliere,

I can not reproduce your issue. The contacts are sorted in my case like they are ordered in the selection, undependingly if they are in a block or not:

![order-contacts](https://github.com/sulu/sulu/assets/1698337/cbaea98a-f973-47f2-9c34-4796f6b8380d)

The sorting is happening  here: https://github.com/sulu/sulu/blob/5006f0bccfaf4a4f41ba3275e687263b4636e58b/src/Sulu/Bundle/ContactBundle/Content/Types/ContactSelection.php#L56-L58

Maybe your project did overwrite the `contact_selection` content type and so is returning here something else and does not keep the ordering of the ids in mind?

**Comment by thomas-peter-juweliere** [comment]
Many thanks for your response.

The problem does not exist in a fresh installation of Sulu.
