### ISSUE TITLE
Upgrade to Symfony 6.3 results in error when loading JMS serializer annotations

### ISSUE THREAD

**Issue by stefliekens** [sulu/sulu#7095]
| Q | A
| --- | ---
| Sulu Version | 2.5.9
| Symfony Version | 6.3
| PHP Version | 8.1
| doctrine/annotations | 1.14.2
| jms/serializer |  3.22.0

# Actual Behavior

After upgrading to Symfony 6.3 and Sulu 2.5.9, the admin is not accessible because the /admin/config route results in 500 error with message `The annotation ... in property ... was never imported. Did you maybe forget to add a "use" statement for this annotation?`
![image](https://github.com/sulu/sulu/assets/3245491/87c6ee42-69ff-45a1-8b41-584f602d0f31)

# Expected Behavior

The admin should load as usual. 

# Steps to Reproduce

Upgrade the Sulu demo project to the latest Sulu and Symfony 6.3 version.

# Possible Solutions

For now I've added the line below in the `public/index.php` file:
```
Doctrine\Common\Annotations\AnnotationRegistry::registerLoader('class_exists');
```

After some research and debugging I saw Symfony removed this `class_exists` loader:

[version 6.2.11](https://github.com/symfony/symfony/blob/v6.2.11/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1637) <=> [version 6.3.0](https://github.com/symfony/symfony/blob/v6.3.0/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1718)

**Comment by chirimoya** [comment]
Adding some context: https://github.com/symfony/symfony/issues/50617 & https://github.com/symfony/symfony/pull/48725 /cc @alexander-schranz

**Comment by alexander-schranz** [comment]
This should now be fixed with: https://github.com/handcraftedinthealps/ElasticsearchBundle/releases/tag/5.4.1:

```bash
composer update handcraftedinthealps/ElasticsearchBundle
```

**Comment by stefliekens** [comment]
Upgrading `sulu/article-bundle` together with the `handcraftedinthealps/elasticsearchbundle` worked for me. 

Thanks @alexander-schranz !
