### ISSUE TITLE
SearchIndex Crashed - no rebuild

### ISSUE THREAD

**Issue by remdan** [sulu/sulu#7113]
| Q | A
| --- | ---
| Sulu Version | 2.5.9
| PHP Version | 8.1

# Actual Behavior

When uploading several files at the same time, the server was overloaded and maybe something crashed here after at the search index? Now no new files can be uploaded and no existing ones can be deleted!

<img width="1436" alt="Bildschirmfoto 2023-07-03 um 15 31 36" src="https://github.com/sulu/sulu/assets/5031692/d778385f-d476-4764-b3e2-c0983b59ced6">

<img width="1419" alt="Bildschirmfoto 2023-07-03 um 15 43 46" src="https://github.com/sulu/sulu/assets/5031692/43ca94bc-0f2b-4a7f-834b-59788d9ddc9a">

`{code: 0, message: "Internal Server Error"}`

# Expected Behavior

# Steps to Reproduce

# Possible Solutions

**Comment by alexander-schranz** [comment]
Zendsearch sometimes can be get corrupt.

A `bin/console massive:search:purge` and `bin/console massive:search:reindex` can be solve this issue. For the website the same commands can be used `bin/websiteconsole massie:search:purge` and `bin/websiteconsole massive:search:reindex`.

Sometimes a job doing `bin/console massive:search:optimize` can avoid this kind of issues as the index don't get to much fragmented.
