### ISSUE TITLE
Media of "link" content type returns old file version (MediaLinkProvider)

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#7119]
| Q | A
| --- | ---
| Sulu Version | 2.5.9
| PHP Version | 8.1.20
| DB Version | 8.0.31

# Actual Behavior

When using the [`link` content type](https://docs.sulu.io/en/2.5/reference/content-types/link.html) to select a **media**, the stored URL contains the latest file version at that time.

When uploading a new file version (of the linked media), the page still has the old version in the download URL, e.g: `?v=1`, although the newest version is 2.

# Expected Behavior

The url of the `link` content type should return the media URL of the latest file version.

# Steps to Reproduce

Add a link content type to a page.
```xml
<property name="link" type="link">
    <meta>
        <title lang="en">Link</title>
        <title lang="de">Link</title>
    </meta>

    <params>
        <param name="enable_target" value="true"/>
        <param name="enable_title" value="true"/>
        <param name="types" type="collection">
            <param name="page"/>
            <param name="external"/>
            <param name="media"/>
        </param>
    </params>
</property>
```

Select a **media** and print the the link `{{ dump(content.link) }}`.

Then, upload a new version of the selected media and dump the link again. It still shows the link with `?v=1` then.

**Comment by alexander-schranz** [comment]
fixed in #7164
