### ISSUE TITLE
Snippet areas - not possible to use translation keys

### ISSUE THREAD

**Issue by rogamoore** [sulu/sulu#7120]
| Q | A
| --- | ---
| Sulu Version | 2.5.9
| PHP Version | 8.2

# Actual Behavior

When trying to use Symfony translation keys in the XML snippet, specifically for area meta titles, they are not being translated.

# Expected Behavior

The Symfony translation keys should be correctly translated when used in the XML snippet for area meta titles.

# Steps to Reproduce

The issue can be reproduced by using a Symfony translation key in the XML snippet for an area meta title. Here is an example:

```xml
    <areas>
        <area key="top">
            <meta>
                <title>some.translation.key</title>
            </meta>
        </area>
    </areas>
```

The problem seems to be in the `getArea` function in [SnippetAreaCompilerPass.php](https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/SnippetBundle/DependencyInjection/Compiler/SnippetAreaCompilerPass.php). This issue is similar to the one addressed in [PR #6682](https://github.com/sulu/sulu/pull/6682).

# Possible Solutions

I can offer to open a PR to address this issue, but we need to decide where to put the translation logic.

**Comment by alexander-schranz** [comment]
I'm not sure if we can access the translator inside a compilerpass 🤔 normally we should have not even access any services in compilerpasses but yeah we didn't know better at that state 🙈. Feel free to give it a try.
