### ISSUE TITLE
Progressive Web Apps (PWA) for SULU CMS

### ISSUE THREAD

**Issue by tawhidafridi** [sulu/sulu#7124]
Service worker implementation (offline-ready, add to homescreen)
Server side rendering (indexable by Google and other search engines)
Native multi-site support
Native multi-language support
Support for SULU content elements
Built in support for SULU CMS

**Comment by alexander-schranz** [comment]
Hello @tawhidafridi,

please us the Issue Template for your requests. Also I'm not sure what you are missing. Sulu has a strict seperation content from presentation, this allows you build your website the way you want it and you can use technology you want even per default PHP -> Twig I think all of your points are already fullfilled.

> Native multi-language support

Every webspace already can have one or multiple languages: https://docs.sulu.io/en/2.5/book/localization.html

> Native multi-site support

You can create more then one webspace to have support for multi sites. https://docs.sulu.io/en/2.5/cookbook/create-new-webspace.html

> Support for SULU content elements

You can structure your content elements you want: https://docs.sulu.io/en/2.5/book/templates.html. For dynamic content elements have specially look at `Blocks`: https://docs.sulu.io/en/2.5/book/templates.html#content-blocks

> Server side rendering

Per default Sulu is used via PHP and Twig which is server side rendered and so indexed by default. https://docs.sulu.io/en/2.5/book/twig.html. You even can use Sulu Headless via it JSON API and use so technoligy like NextJS, Remix, Angular, ... or what ever technoligy your frontend team prefers. Per default and the most common way is stay with Symfony Twig template engines.

> Service worker implementation 

Over Sulu strict seperation content from presentation the JavaScript is all in your hands. You easily can provide a `manifest.webmanifest` for your website.

**Comment by alexander-schranz** [comment]
I don't think that we will add any built in support as rendering of the whole side is in the devs hands who create projects and such implementation are different based on the framework they use (Twig, Remix, Angular, React, ...) So I will currently close this issue. If you are open you can create a example pull request for the sulu demo or sulu docs cookboosk pull request which we can show such example how to create such things.

https://github.com/sulu/sulu-demo/pulls
