### ISSUE TITLE
$viewCollection is empty in custom Admin class

### ISSUE THREAD

**Issue by sanchobor** [sulu/sulu#7136]
Sulu Version - 2.5.
PHP Version - 8.1 

# Actual Behavior

I'm adding tabs to Sulu’s Admin page following this [doc page](https://docs.sulu.io/en/2.5/cookbook/add-admin-tabs.html) and then I wanted to hide some of the predefined tabs (Seo, Excerpt and Settings) based on the PermissionType of the user, but I can not get the $viewcollection - is empty when called in my custom Admin class (following [this answer](https://stackoverflow.com/questions/68438768/excerpt-and-taxonomies-on-sulu-admin)): 

`public function configureViews(ViewCollection $viewCollection): void
{
    if ($viewCollection->has('sulu_page.page_edit_form.excerpt')) {
        $viewCollection->get('sulu_page.page_edit_form.excerpt')
            ->setTabCondition(false);
    }
}`

Any help would be appreciated :)

**Comment by mamazu** [comment]
Hey, have you verified that they are run in the correct order? It sounds like your priority is still a little off.

**Comment by alexander-schranz** [comment]
As there was no response and I think it is a priority issue @mamazu mention I close this issue.
