### ISSUE TITLE
[MarkupBundle] preg_match_all(): Argument #2 ($subject) must be of type string, array given

### ISSUE THREAD

**Issue by shochdoerfer** [sulu/sulu#7140]
| Q | A
| --- | ---
| Sulu Version | 2.5.8
| PHP Version | PHP 8.1

# Actual Behavior

An admin user tries to delete a page but the deletion process fails with the following error in the logs:
```
[2023-08-17T21:24:44.183109+02:00] php.CRITICAL: Uncaught Error: preg_match_all(): Argument #2 ($subject) must be of type string, array given {"exception":"[object] (TypeError(code: 0): preg_match_all(): Argument #2 ($subject) must be of type string, array given at /var/www/vendor/sulu/sulu/src/Sulu/Bundle/MarkupBundle/Markup/HtmlTagExtractor.php:40)"} []
```

# Expected Behavior

Page deletion should work.

# Steps to Reproduce

Since the deletion of other pages works fine, I assume something is odd with that specific page. So it's not a general bug in Sulu. Still, it should be fixed somehow to allow "defect" pages to be deleted.

# Possible Solutions

My current "quick fix" works as follows:

1. In `Sulu\Bundle\MarkupBundle\Markup\HtmlTagExtractor::count()` I added the following check:
```
if (!is_string($html)) {
    return 0;
}
```

2. In `Sulu\Bundle\MarkupBundle\Markup\HtmlTagExtractor::extract()` I added the following check:
```
if (!is_string($html)) {
    return [];
}
```

After applying the patch, the page deletion for the specific page is working again. If you feel the patch outlined above makes sense, let me know and I prepare a PR.

**Comment by alexander-schranz** [comment]
It strange that in general the deletion does call the Markup HtmlTagExtractor here 🤔 . Can you show the whole Stack trace of the error? And also what `$html` variable does contain in this case?

**Comment by shochdoerfer** [comment]
The $html variable contains the following:
```
array(1) {
  [0]=>
  string(0) ""
}
```

The full stack trace looks like this:
```
TypeError:
preg_match_all(): Argument #2 ($subject) must be of type string, array given

  at vendor/sulu/sulu/src/Sulu/Bundle/MarkupBundle/Markup/HtmlTagExtractor.php:44
  at preg_match_all('/<sulu-[a-z]+/', array(''), null)
     (vendor/sulu/sulu/src/Sulu/Bundle/MarkupBundle/Markup/HtmlTagExtractor.php:44)
  at Sulu\Bundle\MarkupBundle\Markup\HtmlTagExtractor->count(array(''))
     (vendor/sulu/sulu/src/Sulu/Bundle/MarkupBundle/Markup/DelegatingTagExtractor.php:36)
  at Sulu\Bundle\MarkupBundle\Markup\DelegatingTagExtractor->count(array(''))
     (vendor/sulu/sulu/src/Sulu/Bundle/MarkupBundle/Markup/HtmlMarkupParser.php:56)
  at Sulu\Bundle\MarkupBundle\Markup\HtmlMarkupParser->validate(array(''), 'de')
     (vendor/sulu/sulu/src/Sulu/Component/Content/Types/TextEditor.php:83)
  at Sulu\Component\Content\Types\TextEditor->validate(array(''), 'de')
     (vendor/sulu/sulu/src/Sulu/Component/Content/Types/TextEditor.php:48)
  at Sulu\Component\Content\Types\TextEditor->read(object(Node), object(BlockPropertyWrapper), 'customer', 'de', null)
     (vendor/sulu/sulu/src/Sulu/Component/Content/Types/BlockContentType.php:147)
  at Sulu\Component\Content\Types\BlockContentType->read(object(Node), object(BlockPropertyWrapper), 'customer', 'de', null)
     (vendor/sulu/sulu/src/Sulu/Component/Content/Types/BlockContentType.php:147)
  at Sulu\Component\Content\Types\BlockContentType->read(object(Node), object(TranslatedProperty), 'customer', 'de', null)
     (vendor/sulu/sulu/src/Sulu/Component/Content/Document/Structure/ManagedStructure.php:123)
  at Sulu\Component\Content\Document\Structure\ManagedStructure->getProperty('content_blocks')
     (vendor/sulu/sulu/src/Sulu/Component/Content/Document/Structure/ManagedStructure.php:172)
  at Sulu\Component\Content\Document\Structure\ManagedStructure->toArray()
     (vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Trash/PageTrashItemHandler.php:116)
  at Sulu\Bundle\PageBundle\Trash\PageTrashItemHandler->store(object(PageDocument), array())
     (vendor/sulu/sulu/src/Sulu/Bundle/TrashBundle/Application/TrashManager/TrashManager.php:77)
  at Sulu\Bundle\TrashBundle\Application\TrashManager\TrashManager->store('pages', object(PageDocument))
     (vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/EventListener/PageTrashSubscriber.php:75)
  at Sulu\Bundle\PageBundle\EventListener\PageTrashSubscriber->storePageToTrash(object(RemoveEvent), 'sulu_document_manager.remove', object(EventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:270)
  at Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(object(RemoveEvent), 'sulu_document_manager.remove', object(EventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure), object(Closure)), 'sulu_document_manager.remove', object(RemoveEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RemoveEvent), 'sulu_document_manager.remove')
     (vendor/sulu/sulu/src/Sulu/Component/DocumentManager/DocumentManager.php:67)
  at Sulu\Component\DocumentManager\DocumentManager->remove(object(PageDocument))
     (vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Controller/PageController.php:432)
  at Sulu\Bundle\PageBundle\Controller\PageController->Sulu\Bundle\PageBundle\Controller\{closure}('5a161b30-1fcf-411c-930a-af4b98f26eeb')
     (vendor/sulu/sulu/src/Sulu/Component/Rest/RestControllerTrait.php:146)
  at Sulu\Component\Rest\AbstractRestController->responseDelete('5a161b30-1fcf-411c-930a-af4b98f26eeb', object(Closure))
     (vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Controller/PageController.php:438)
  at Sulu\Bundle\PageBundle\Controller\PageController->deleteAction(object(Request), '5a161b30-1fcf-411c-930a-af4b98f26eeb')
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:66)         
```

I agree, it might not be ideal to fix it in this method, but I was not sure where else to fix it. And at least for my case, I need a quick fix ;)

Maybe it also makes sense to add a string typehint to both the count() and extract() methods to make it clearer what you can pass. Obviously this would not fix this error but make things a bit more clearer.

**Comment by shochdoerfer** [comment]
And interestingly, when I try to delete the "defect" page from trash, that works even without my changes. So it is just the regular deletion process that is affected.

**Comment by DanielRuf** [comment]
I can see where the issue stems from:

>   at Sulu\Component\Content\Document\Structure\ManagedStructure->getProperty('content_blocks')

content_blocks is a "block" which contains sub blocks. Probably not really related to our logic in the service:

![grafik](https://github.com/sulu/sulu/assets/827205/437ad610-b4db-4163-9bc4-1a4d5851c8b1)

`content_blocks` is defined like this:

```
        <block name="content_blocks" minOccurs="0">
            <!-- @see https://docs.sulu.io/en/2.2/reference/content-types/block.html -->

            <meta>
                <title lang="en">Blocks</title>
                <title lang="de">Blöcke</title>
            </meta>

            <types>
            <!-- @see https://docs.sulu.io/en/2.2/book/templates.html#including-other-templates -->

                <xi:include href="../includes/blocks/iframe.xml" xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)"/>

                <xi:include href="../includes/blocks/image.xml" xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)" />

                <xi:include href="../includes/blocks/media.xml" xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)" />

                <xi:include href="../includes/blocks/wysiwyg.xml" xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)" />

                <xi:include href="../includes/blocks/two_columns.xml" xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)"/>

                <xi:include href="../includes/blocks/three_columns.xml" xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)"/>

            </types>
        </block>
```

Not sure if helpful.

**Comment by alexander-schranz** [comment]
Looks for me the interesting part is here: https://github.com/sulu/sulu/blob/a68e0de1ffbe3321dc6bc66ff3bbea0be5571ee5/src/Sulu/Component/Content/Types/TextEditor.php#L48 that you are getting here a `$value`.

Does save and publish the page itself work?

Was the templated changed programmatically? What sometimes can make problem is a field is named inside a `block` the same way like another field in another `block type` but have there another `type` used.

**Comment by shochdoerfer** [comment]
@alexander-schranz we can't do anything with the page. Accessing it also fails. That's why the customer wanted to delete it and start over :)

**Comment by alexander-schranz** [comment]
What is the error on accessing it? Also would look at the `phpcr-node` itself via the `doctrine:phpcr:shell`.

**Comment by DanielRuf** [comment]
@alexander-schranz I remember now. the website was using en and de as languages before. At this time the page was probably created and so it existed in two language variants.

Then the customer wanted to have only de as language. So we deleted it from the language configuration.

The issue probably only exists for pages that existed in both or the original en language and when the deletion process is started, the might arise.

Edit: `content_blocks` was introduced after the language was deleted, which was much later.

**Comment by alexander-schranz** [comment]
I think you need to identify (via phpcr shell) the `TextEditor` field inside your `content_blocks` which is running into the exception and returns here an array instead of an excpected string field:

https://github.com/sulu/sulu/blob/a68e0de1ffbe3321dc6bc66ff3bbea0be5571ee5/src/Sulu/Component/Content/Types/TextEditor.php#L48

**Comment by shochdoerfer** [comment]
@alexander-schranz given this seems to be project specific issue, I guess we can close the issue. Still, do you think a PR to catch (or ignore) the problem in the HtmlTagExtractor or elsewhere makes sense?

**Comment by alexander-schranz** [comment]
I think some validation here: https://github.com/sulu/sulu/blob/a68e0de1ffbe3321dc6bc66ff3bbea0be5571ee5/src/Sulu/Component/Content/Types/TextEditor.php#L48 would not hurt. Mostly to ignore runtime error silently log an error or just convert to null or empty string. Still would be interesting how you did run into that error that a text editor field has a `array` field.

Is any other field named the same way as the text editor field?

**Comment by DanielRuf** [comment]
@alexander-schranz I have a feeling that it was caused by this logic shown in the screenshot:

![grafik](https://github.com/sulu/sulu/assets/827205/9a7fda8d-eb7c-403e-9a34-1754dcc5fe31)

I guess we will have to test to see, if it works now.

**Comment by alexander-schranz** [comment]
Don't see how this should be releated how the Document is rendered on the Website. It need to be more when a document is modified not when it is rendered. As said most common case would be if you have a field in your templates which has the same name but another type. But for that case you first need to find out which `text_editor` field is effect by the bug and then check what other fields exist with the same name. Another error could by if the `type` was changed in the past without adding phpcr migrations for it to the project.

**Comment by DanielRuf** [comment]
Good to know, thanks @alexander-schranz.

I guess we will find the cause when we check this the next time, when it happens again.

Unrelated to the reported issue, can you share details on this?

> adding phpcr migrations for it to the project

Not sure where this is documented in the Sulu docs. But we had the need to change types a few times during development and then I had to manually remove the phpcr node via terminal. But I was not aware of the (probably simple?) solution for xml / phpcr migrations.

**Comment by alexander-schranz** [comment]
> Not sure where this is documented in the Sulu docs. But we had the need to change types a few times during development and then I had to manually remove the phpcr node via terminal. But I was not aware of the (probably simple?) solution for xml / phpcr migrations.

If you do:

```diff
-<property name="text" "some_selection" />
+<property name="text" "text_editor" />
```

The data is stored as array `[1,2,3]` and to make sure text editor field now always get `string` you would need remove the existing properties or set to empty string or migrate them to the expected values example:

https://docs.sulu.io/en/2.5/cookbook/migrate-content-data.html

Sure migrations are only required to be created when you did deploy before something and content manager were able to create fields with some_selection. For development just some type changing during developing a template you normally don't create migrations as long as the template field was never deployed to prod.

**Comment by DanielRuf** [comment]
Thanks for the link and details. Seems like this is something that might come handy in the future. I thought there was an easier way like the `doctrine:migrations:diff` command. Not sure if this works with Sulu and the xml configs or if I see this in a too simple and naive way.

Besides that, the biggest challenge is still to establish some common understanding in the team for phpcr and the terminal commands to work with the nodes - instead of reverting the local development database to its initial state (happened in some cases at the beginning when there was not much knowledge about the relevant commands).

We'll keep you updated when we find out more regarding our issue and how we solved it in the end (maybe we really needed a migration there).

**Comment by alexander-schranz** [comment]
See PHPCR storage like a unstructured JSON field in doctrine. If you change the representation of that data you need to write a migration but migrations:diff doesn't help you in that case you need to write it your own knowing how it was structured before and how it is structured now.

What sure should change in Sulu to check in case of `TextEditor` if the `$value` is a string and only then call the method. That way you would not run into this error again.

```diff
         $value = $node->getPropertyValueWithDefault($property->getName(), $this->defaultValue);
-         $property->setValue($this->validate($value, $languageCode));
+         $property->setValue(\is_string($value) ? $this->validate($value, $languageCode) : null);

         return $value;
```

**Comment by alexander-schranz** [comment]
@shochdoerfer if you want you can tackle a Merge Request with the suggestion in: https://github.com/sulu/sulu/issues/7140#issuecomment-1685795306 for 2.4

**Comment by shochdoerfer** [comment]
@alexander-schranz thx! Will do. Will add this to my (long) todo-list ;)

Kudos for your insights & help. Very much appreciated. Next time when our paths cross, the drinks are on me.
