### ISSUE TITLE
Link content type inside a block not translated when a page is copied to a new localization

### ISSUE THREAD

**Issue by dev-newvisibility** [sulu/sulu#7159]
| Q | A
| --- | ---
| Sulu Version | 2.5.9
| PHP Version | 8.1
| DB Version | MariaDB 10.7
| Browser Version | Chrome 116

# Actual Behavior

When a block that has a [link](https://docs.sulu.io/en/2.5/reference/content-types/link.html) in its properties is copied to a new localization, the link retains its original locale. So in the frontend, the link will always point to the page in the original localization.

# Expected Behavior

The rendered link should always match the current locale.

# Steps to Reproduce
- Configure a webspace with multiple localizations.
- Configure a page template with at least one block property, which in turn has a property of type [link](https://docs.sulu.io/en/2.5/reference/content-types/link.html) (tested with page provider).
- Go to the admin and fill in the link.
- Save the page and copy the localization to another localization.
- Go to the frontend. The latter localization will show a link pointing to the wrong localization.

# Possible Solutions
We have seen that the link content type persists in PHPCR the locale info:

```json
{"provider":"page","target":null,"anchor":null,"query":null,"href":"57b0fda8-5736-4701-a6c1-8791e5d16c33","title":null,"rel":null,"locale":"en"}
```

A possible solution could be not to persist the locale info and use the current one when rendering a template.

**Comment by alexander-schranz** [comment]
The saved `locale` does not longer has any effects since `2.5.10`: https://github.com/sulu/sulu/commit/b2c773167c922302662fb405faf5c7d1cd9aee82

Are you sure you are on `2.5.10`?

**Comment by dev-newvisibility** [comment]
Hi,
sorry, my mistake, I confirm that we are still on v2.5.9.

Thank you.

**Comment by alexander-schranz** [comment]
Then the update should fix your issue, let us know if it does.

**Comment by dev-newvisibility** [comment]
Hi,
Just tried it with v2.5.10. It works great.
