### ISSUE TITLE
Trying to report a vulnerability 

### ISSUE THREAD

**Issue by PH03N1XSP** [sulu/sulu#7165]
Hello, I am reporting a vulnerability in Sulu, and I have sent the email and everything, but you do not respond, I wrote to you about ten days ago, and yesterday again but nothing

This is the email security@sulu.io

**Comment by PH03N1XSP** [comment]
You have the technical details and everything about the vulnerability in the email [for obvious reasons I did not put them here]

**Comment by alexander-schranz** [comment]
Closing this, answered the issue in the email. Thx for reporting.
