### ISSUE TITLE
Property "block" -> choosen type not active

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#717]
Property "block" -> when I have multiple types and I want to see what type one block instance has, it isn't marked as active.

![bildschirmfoto 2015-01-15 um 11 28 18](https://cloud.githubusercontent.com/assets/3875917/5755912/221a1608-9caa-11e4-8303-70209d7c5fe0.png)

**Comment by wachterjohannes** [comment]
@berndhep where should we place the type of a block?

**Comment by wachterjohannes** [comment]
make dropdown markable with a little arrow infront of the selected item and instead of the wheel place the selected value!

**Comment by danrot** [comment]
We already have that in the template list, I guess it should not be too much work too change here as well, or is it?

**Comment by wachterjohannes** [comment]
no it is not to hard (=

**Comment by alexander-schranz** [comment]
This was fixed a long time ago when the Block in I think 1.2 were redesigned.
