### ISSUE TITLE
Disabled/invisible mandatory property still mandatory

### ISSUE THREAD

**Issue by manuxi** [sulu/sulu#7193]
| Q | A
| --- | ---
| Sulu Version | 2.5.10
| PHP Version | 8.13
| DB Version | MySQL 5.7.32
| Browser Version | Chrome

# Actual Behavior

Not sure whether this is as bug, feature request or as designed. I'd like to report that to discuss. I'm trying to have less block elements in my newer Sulu projects. Therefor I'm using more config options where I sometimes hide sections or disable properties. If I disable a property (or more confusing, hide it) and it's mandatory, it can't be saved, since the mandatory property isn't filled out.

# Expected Behavior

When disabling a property I'd suggest to make it not mandatory anymore.

# Steps to Reproduce

Set a prop to mandatory and disable it with a condition.

# Possible Solutions
Hidden or disabled properties should not be mandatory.

**Comment by alexander-schranz** [comment]
Hello @manuxi, There already exists an issue about this. Read more about it here: #4609
