### ISSUE TITLE
Filtering lists by selection is buggy

### ISSUE THREAD

**Issue by veewee** [sulu/sulu#7195]
| Q | A
| --- | ---
| Sulu Version | 2.5.9
| PHP Version | 8.1.17
| DB Version | Postgres 14.5
| Browser Version | Firefox, chrome, safari, ...

# Actual Behavior

* Go to https://sulu.rocks/admin/#/contacts?filter.accountId%5B0%5D=1
* Clear account filter + press OK
* Refresh page
* You'll notice that "all" possible values of the selection filter for accountId selection get reactivated.
   * (On that page, there is only 1 possible value for the selection filter - but if there are more: all get activated)

https://github.com/sulu/sulu/assets/1618158/21c76621-593a-48d1-a67c-82351aa01939

The same problem exists for our custom filter implementations as suggested in https://github.com/sulu/sulu/issues/7162. In there, it becomes visible during filtering and is therefore more problematic than after a refresh. Nevertheless, it is a bug that needs to be dealt with at its core.

# Expected Behavior

The selection filter keeps track of the last selected value(s). If no values were selected, the filter gets removed.

# Steps to Reproduce

See "Actual Behavior"

**Comment by alexander-schranz** [comment]
Hello @veewee,

I think this is related that all our `User Settings` are __delayed__ to avoid spamming the server. So if you are editing filters and **directly refresh** the new filtes are not yet saved and you will get your old state. But if you wait ~2-3 seconds the filters are correctly updated also on the server and the filter is then correctly removed. For us it is unexpected that a user change a filter and directly refreshes.

Can you confirm that if you wait before refreshing some seconds this issue does not appear?

**Comment by veewee** [comment]
@alexander-schranz 

I don't think the user settings are causing this issue.
I've made a new screen recording that might give you a better idea of what is going on:


https://github.com/sulu/sulu/assets/1618158/52838093-d8d8-466f-b5a8-7e77b3507c4e

As you can see:

* I wait until the user settings are applied
* Then I refresh
* Then of a sudden the autocomplete contains all possible values when clicking it open again.

The excpectation there would be that only the selected value is present in that autocomplete.

**Comment by stefliekens** [comment]
@alexander-schranz, you can close this issues. We didn't consider the `ids` request query parameter in our related controllers. We reworked them by using `\Sulu\Component\Rest\RestHelperInterface::initializeListBuilder` which does take the IDs into account in the doctrine/db query. 

cc @veewee
