### ISSUE TITLE
SnippetResolver caching snippets by UUID, not by locale

### ISSUE THREAD

**Issue by shinyvision** [sulu/sulu#7201]
| Q | A
| --- | ---
| Sulu Version | 2.5.10
| PHP Version | 8.2.12
| DB Version | MySQL 5.7.38
| Browser Version | Brave 1.60.114

# Actual Behavior

When loading the same snippet in different locales, it returns the same snippet in the first locale that was requested.

# Expected Behavior

When loading the same snippet in different locales, we want the first request to return the snippet in the first requested locale, and the second one in the other locale.

# Steps to Reproduce

Try the following:

```php
<?php

declare(strict_types=1);

namespace App\Sulu\Settings;

use Sulu\Bundle\SnippetBundle\Twig\SnippetAreaTwigExtension;

#[Autoconfigure(
    bind: ['$snippetAreaTwigExtension' => '@sulu_snippet.twig.area_snippet'],
)]
class SettingsProvider
{
    public function __construct(
        private readonly SnippetAreaTwigExtension $snippetAreaTwigExtension,
    ) {
    }

    public function getSettings(): ?array
    {
        $settings = $this->snippetAreaTwigExtension->loadByArea('settings', 'mysite', 'en');
        $settings2 = $this->snippetAreaTwigExtension->loadByArea('settings', 'mysite', 'de');

        dump($settings); // English
        dump($settings2); // English, should be German
    }
}
```

# Possible Solutions

The SnippetResolver has a $snippetCache, this caches snippets by UUID. If you add the locale to the index, this should fix the problem.

**Comment by mamazu** [comment]
Thanks for reporting. It has been fixed with the attached merge request and will be in the next 2.4 version.
