### ISSUE TITLE
Incompatibility with Symfony 6.4 because of renderBlock method in WebsiteController

### ISSUE THREAD

**Issue by stollr** [sulu/sulu#7215]
| Q | A
| --- | ---
| Sulu Version | 2.5.10
| PHP Version | irrelevant
| DB Version | irrelevant
| Browser Version | irrelevant

# Actual Behavior

When doing a `composer update` and Symfony package versions are not limited to `< 6.4` in the root composer.json Composer will install the new Symfony 6.4 version, which will lead to the following error:

> Declaration of Sulu\Bundle\WebsiteBundle\Controller\WebsiteController::renderBlock($template, $block, $attributes = []) must be compatible with Symfony\Bundle\FrameworkBundle\Controller\AbstractController::renderBlock(string $view, string $block, array $parameters = [], ?Symfony\Component\HttpFoundation\Response $response = null): Symfony\Component\HttpFoundation\Response in /srv/htdocs/myproject/vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php on line 125

# Expected Behavior

No error during composer update.

# Steps to Reproduce

Execute `composer update` in a Sulu 2.5.10 project.

# Possible Solutions

Either Symfony 6.3 won't be upgraded to 6.4 (by adding a conflict constraint) or Sulu's renderBlock method has to be adjusted.

**Comment by stollr** [comment]
Oh, I just found https://github.com/sulu/sulu/commit/1fc46655a4a14afbb2600b6524ff63153d5fd4e1. So it is already fixed in 2.5 branch, but next patch version has not been released, yet.

When are you planning to release it?

**Comment by alexander-schranz** [comment]
Thx for reporting, we are working on creating a release soonish.

**Comment by alexander-schranz** [comment]
closing as fixed in #7148
