### ISSUE TITLE
Exceptions in ResettingController:sendEmailAction

### ISSUE THREAD

**Issue by eekes** [sulu/sulu#7243]
| Q | A
| --- | ---
| Sulu Version | 2.5.11 (but any version I think)
| PHP Version | 8.1
| DB Version | MySQL 5.7

# Actual Behavior

If something goes wrong when using the password reset form, a 204 is returned.

# Expected Behavior

An exception should be throw

# Steps to Reproduce

In ResettingController::sendEmailAction, all exceptions are ignored. I've had a couple of issues such as token send limit exceptions or Postmark exceptions, but I had to manually edit this file in production to be able to figure out what was going on.

Is there a specific reason why all exceptions are ignored?

# Possible Solutions

Just throw the exceptions?

**Comment by mamazu** [comment]
Just as an update. The reason why this is not implemented is that this is could be used as a Security vulnerability.

[GHSA-wfm4-pq59-wg6r](https://github.com/sulu/sulu/security/advisories/GHSA-wfm4-pq59-wg6r)
