### ISSUE TITLE
Authored date for shadow pages not used in smart content sorting.

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#7252]
| Q | A
| --- | ---
| Sulu Version | 2.5.9

# Actual Behavior

First you create a page in EN and then create a language variant DE, which points as a shadow page on EN.
Now you have to set an authored date on the EN language. In DE the new authored date will be shown in sulu but in phpcr the DE language still has the old date. This causes an issue when sorting by authored date in a smart content in language IT.

# Expected Behavior

Also use the EN language as authored date when a shadow page is given.

# Steps to Reproduce

See behavior.

# Possible Solutions

As fast solution you can just save the DE version again so the shown date also saves into the phpcr.

**Comment by alexander-schranz** [comment]
@Quehnie Thx for the report, I think this issue should be resolved in #7310, #7343, #7351 and should be part of the latest Sulu releases.
