### ISSUE TITLE
doctrine/orm 2.18.0 causing exception with old file versions

### ISSUE THREAD

**Issue by popoplanter** [sulu/sulu#7269]
| Q | A
| --- | ---
| Sulu Version | 2.5.12 
| PHP Version |  8.1 
| DB Version | mysql 8.0.27 
| Browser Version | all 

# Actual Behavior

When updating to doctrine/orm 2.18.0 an exception occurs on Medias with multiple file versions:

`The given entity of type 'Sulu\Bundle\TagBundle\Entity\Tag' (Sulu\Bundle\TagBundle\Entity\Tag@1553) has no identity/no id values set. It cannot be added to the identity map.`

# Steps to Reproduce

Update to doctine/orm 2.18.0

# Possible Solutions

This can be avoided by defining a conflict entry in composer.json to enforce an older version but this should not be the solution to the problem as newer doctrine/orm versions should be supported

```
    "conflict": {
        "doctrine/orm": ">= 2.16.0"
    },
```

**Comment by alexander-schranz** [comment]
Look like this is related to https://github.com/doctrine/orm/issues/11100.

Not sure yet where we may call `addSelect` twice 🤔

**Comment by Prokyonn** [comment]
https://github.com/doctrine/orm/pull/11194 would fix the issue, but unfortunately it is still not merged

**Comment by alexander-schranz** [comment]
This should be fixed in https://github.com/doctrine/orm/pull/11194 (doctrine/orm 2.19.6)
