### ISSUE TITLE
Issues with admin JS build after update to 2.5.12

### ISSUE THREAD

**Issue by fnagel** [sulu/sulu#7274]
| Q | A
| --- | ---
| Sulu Version | 2.5.12
| PHP Version | 8.1.26
| DB Version | 
| Browser Version | Firefox 122.0

# Actual Behavior

Build crashes (see logs below)

# Expected Behavior

Build should work without error messages.

Admin UI works afaics, only the view with my custom toolbar crashes:
`Error: There is no toolbar item with key "app.url" registered! Registered keys: sulu_admin.add, sulu_admin.delete, sulu_admin.export, sulu_admin.move, sulu_admin.upload, sulu_contact.add_contact, sulu_contact.add_media, sulu_contact.delete_media`

# Steps to Reproduce

Update from 2.5.10 to 2.5.12 and run the admin JS build.

# Logs

Console output after `php bin/console sulu:admin:update-build`:

```
Build administration interface assets
-------------------------------------


> sulu-skeleton@ build /var/www/html/assets/admin
> webpack --mode production

   1331 modules

ERROR in build/admin/main.d6b8c63a211c486a01c1.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at /var/www/html/assets/admin/node_modules/webpack/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/var/www/html/assets/admin/node_modules/webpack/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/var/www/html/assets/admin/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/var/www/html/assets/admin/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sulu-skeleton@ build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sulu-skeleton@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/.npm/_logs/2024-02-09T15_49_23_882Z-debug.log
```

The log file contains:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.18
3 info using node@v18.17.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle sulu-skeleton@~prebuild: sulu-skeleton@
6 info lifecycle sulu-skeleton@~build: sulu-skeleton@
7 verbose lifecycle sulu-skeleton@~build: unsafe-perm in lifecycle true
8 verbose lifecycle sulu-skeleton@~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/assets/admin/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle sulu-skeleton@~build: CWD: /var/www/html/assets/admin
10 silly lifecycle sulu-skeleton@~build: Args: [ '-c', 'webpack --mode production' ]
11 silly lifecycle sulu-skeleton@~build: Returned: code: 1  signal: null
12 info lifecycle sulu-skeleton@~build: Failed to exec build script
13 verbose stack Error: sulu-skeleton@ build: `webpack --mode production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:514:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:514:28)
13 verbose stack     at maybeClose (node:internal/child_process:1091:16)
13 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
14 verbose pkgid sulu-skeleton@
15 verbose cwd /var/www/html/assets/admin
16 verbose Linux 5.15.90.1-microsoft-standard-WSL2
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v18.17.1
19 verbose npm  v6.14.18
20 error code ELIFECYCLE
21 error errno 1
22 error sulu-skeleton@ build: `webpack --mode production`
22 error Exit status 1
23 error Failed at the sulu-skeleton@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by alexander-schranz** [comment]
@fnagel Did you try to build the admin via docker like here: https://docs.sulu.io/en/2.5/cookbook/build-admin-frontend.html#solution-2-build-manually-with-docker

Else the `app.url` isn't part of the core. So it more sounds like an issue that your custom javascript is not compiled correctly. Customization are normally in the https://github.com/sulu/skeleton/blob/2.5/assets/admin/app.js. Maybe you accidently said `yes` to replace that file. You should say there `no` if it contains required customizations.

**Comment by fnagel** [comment]
@alexander-schranz I'm using a Docker image for the application, so everything runs and builds in a Docker container. But not in the way you've linked above. Building the admin JS was no problem before updating.

Yes, `app.url` is a custom toolbar component I'm using and it worked without issues in v2.5.10. I assume the browser console error is due to the the broken build. 

When reading the error logs, I think it has something to do with `terser-webpack-plugin` and the node hash functionality. Google has some results like this: https://stackoverflow.com/questions/73144960/error-error0308010cdigital-envelope-routinesunsupported-at-new-hash-nodei

Looks like the SSL in my container is not compatible with all those outdated packages. Using `export NODE_OPTIONS=--openssl-legacy-provider` in the CLI before building fixes this. Taken from https://sebhastian.com/error-0308010c-digital-envelope-routines-unsupported/

**Comment by alexander-schranz** [comment]
Which node version are you using to build? We currently testing Sulu against 14 and 16 because of requirement to npm 6. Some package upgrades will come with Sulu 2.6 and alternative to npm@6 will be experimental support for [`bun`](https://bun.sh) as at current state the only package manager which behaves with local packages like remote packages like `npm@6` was doing.

**Comment by fnagel** [comment]
I'm downgrading my "standard" PHP Docker container to use node v18.17.1 with npm v6.14.18. with this command `npm install -g npm@6`, but that will not work forever as the dependencies for the website build need newer versions.
