### ISSUE TITLE
Viewer admin user can not access to admin webspace

### ISSUE THREAD

**Issue by niji-ahubert** [sulu/sulu#7302]
| Q | A
| --- | ---
| 2.5.10 | 
| 8.2.10 | 
| 8.1.0 | 
| Firefox Release 123.0 or Chrome Version 122.0.6261.96 | 

# Actual Behavior

I've created a reader user, this user can access webspace only in view mode.
My user can not access to webspace

# Expected Behavior

I want to access webspace and content in view mode

# Steps to Reproduce

- create a reader role with only view access
- create a user and assign reader role
- test to access webspace ( you can not)

# Possible Solutions

in  Sulu\Bundle\PageBundle\Admin\PageAdmin function hasSomeWebspacePermission() you only accept user with PermissionTypes::EDIT
so my reader user can not access to webspace

`

    private function hasSomeWebspacePermission(): bool
    {
        foreach ($this->webspaceManager->getWebspaceCollection()->getWebspaces() as $webspace) {

            $hasWebspacePermission = $this->securityChecker->hasPermission(
                self::getPageSecurityContext($webspace->getKey()),
                PermissionTypes::EDIT
            );

            if ($hasWebspacePermission) {
                return true;
            }
        }
        return false;
    }

`

**Comment by alexander-schranz** [comment]
@niji-ahubert Thx for creating the issue. This as a little bit more complicated our API is based also on the permissions and in the past we decided that the `View` permissions give you only access to use `Selections` and to navigate to a entity you atleast require `Edit` permissions.

That way we could make it possible that example somebody could edit a whole Entity with Relations to Page, Article, .. without have access to the webspace article itself. We are sure the permission is not the best one.

As there is already a similar issue I will close this one to keep discussion at one place: https://github.com/sulu/sulu/issues/4867
