### ISSUE TITLE
Old media versions throw 404 error

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#7319]
| Q | A
| --- | ---
| Sulu Version | 2.5.12 introduced mostly with #7259

# Actual Behavior

If an old media version gets requested the MediaStreamController throws a 404 Error.

# Expected Behavior

src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php Line 257  
Should use getMediaById so we get all Versions and not only the current one.

# Steps to Reproduce

Upload 2 File Versions.

# Possible Solutions

src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php Line 257  
Should use getMediaById so we get all Versions and not only the current one.

**Comment by alexander-schranz** [comment]
I think the issue is here https://github.com/sulu/sulu/pull/7259/files#r1625969195
@Quehnie or @harunbuljubasic do you want to create a pull request for it?

**Comment by alexander-schranz** [comment]
fixed in #7480
