### ISSUE TITLE
Error in media->insights->references if media is referenced with article

### ISSUE THREAD

**Issue by hual7** [sulu/sulu#7346]
| Q | A
| --- | ---
| Sulu Version | 2.6.0-RC1
| SuluArticleBundle | 2.6.x-dev
| PHP Version | 8.3
| DB Version | MariaDB 10.5.23
| Browser Version | Chrome latest

# Actual Behavior

If a media is referenced to an article, I'll get the following JS error with and a blank browser window
<img width="882" alt="Bildschirmfoto 2024-04-05 um 15 59 28" src="https://github.com/sulu/sulu/assets/89628357/39ab2664-c0e7-483e-b80f-c3ce1993fc79">

# Expected Behavior

The list of referenced Pages, Snippets and Articles

# Steps to Reproduce

Update to the latest 2.6-dev-versions, add image to article and try to view the referenced resource @ media insights.

**Comment by Prokyonn** [comment]
Should be fixed with https://github.com/sulu/sulu/pull/7350
