### ISSUE TITLE
Extensions are not updated inside the preview

### ISSUE THREAD

**Issue by Olivier127** [sulu/sulu#7348]
| Q | A
| --- | ---
| Sulu Version | 2.5.14
| PHP Version | 8.2.7
| DB Version | MySQL 8.3
| Browser Version | Chrome, Edge, Firefox

# Actual Behavior

Hello, I noticed  that when I update the "excerpt and taxonomy" section, these modifications no longer reflect in the preview (I have to refresh the page with F5 or exit and come back to it).
In my template, I use the title, description, and image area for the cover image as well as the title of a page. 

example with a fresh install with sulu 2.5.14 (and 2.6.0-RC1, no others sulu bundle (article, form etc.)

I set an image 

![image](https://github.com/sulu/sulu/assets/70262207/abb3c0f6-c704-4bcb-a176-d95e3e11c819)

the preview don't update the extension

same thing with title or description

![image (1)](https://github.com/sulu/sulu/assets/70262207/266480c9-7e1b-4b70-9a5e-46d91887de7a)
![image (2)](https://github.com/sulu/sulu/assets/70262207/89173bdc-514b-4cd8-a63f-21a8ad64682e)

but, even if the preview does not update the extension array, the front can access of the values
![image (3)](https://github.com/sulu/sulu/assets/70262207/a3b4489c-9b44-4e1d-88e5-f2e6ad10aeac)

The SEO array inside extension doesnt be updated
![image](https://github.com/sulu/sulu/assets/70262207/f33aa75f-5fa9-4e66-a3d2-b5ed0fa2a959)

I must do a F5 Brower refresh to update sulu and have the right data each time.

# Expected Behavior

Preview extension array updated each time

# Steps to Reproduce

Install a fresh install 2.5.14,
put dump inside default.html.twig

Go to the excerpt and taxonomy section on a page et set some data inside.
You will see inside the dump that que extension array doesnt contain any data

# Possible Solutions

**Comment by mamazu** [comment]
Fixed in the attached merge request.

**Comment by Olivier127** [comment]
@mamazu same issue inside ArticleBundle (ArticleObjectProvider : see my issue [here](https://github.com/sulu/SuluArticleBundle/issues/675))
