### ISSUE TITLE
Lists with pagination in Sulu admin are no longer a consistent width

### ISSUE THREAD

**Issue by NeuralClone** [sulu/sulu#7389]
| Q | A
| --- | ---
| Sulu Version | 2.6.0
| PHP Version | 8.2
| DB Version | --
| Browser Version | Firefox 125.0.3, Chrome 124.0.6367.119

# Actual Behavior

All list views in the Sulu admin now have a variable width:

![Screenshot 2024-05-02 181849](https://github.com/sulu/sulu/assets/678221/b2bf4195-63c0-4f01-bcd9-732da4b8bf3f)

![Screenshot 2024-05-02 182842](https://github.com/sulu/sulu/assets/678221/7a3842ba-b029-494d-aa6f-283a405d85ee)

There's a max width of 820px in effect that's being applied to search results to prevent the results from becoming wider than the search box. It's also being applied to pagination elsewhere in the Sulu admin. The container will expand beyond 820px if it's wider. But it won't expand to 100% automatically.

# Expected Behavior

Lists should expand to fill the screen:

![Screenshot 2024-05-02 181923](https://github.com/sulu/sulu/assets/678221/de0f4592-2bdc-4b81-9867-4e02f4addbc0)

# Steps to Reproduce

1. Create a project based on `sulu/skeleton` and Sulu 2.6.0.
2. Navigate to any of the default Sulu admin sections with pagination.

# Possible Solutions

Perhaps there's a way to limit the max width introduced in the CSS [`resultsContainer`](https://github.com/sulu/sulu/blob/2a0253378d2b209ec294d1c378f56314fd616ef3/src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/pagination.scss#L33) class to only apply to search results and not to other lists?

**Comment by alexander-schranz** [comment]
@NeuralClone Thx for the report I think we need to revert the CSS changes in the pagination here: https://github.com/sulu/sulu/pull/7228/files

And move the width changes into the `searchResult.scss` so it has not side effects to the other lists.

@NeuralClone If you want to create a pull request for it let me know.

**Comment by NeuralClone** [comment]
Sure, I can take a look at it.

**Comment by NeuralClone** [comment]
Opened a pull request to address this here: #7399.
