### ISSUE TITLE
Page delete Reference Error

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#739]
I get the following error by page delete
`request.CRITICAL: Uncaught PHP Exception PHPCR\ReferentialIntegrityException: "HTTP 409:    dc57583c-00f8-4d72-a760-62d7cb0a4964 cannot be removed because it is still being referenced" at 
/var/data/websites/sulu.lo/vendor/jackalope/jackalope-jackrabbit/src/Jackalope/Transport/Jackrabbit/Request.php line 546 {"exception":"[object] (PHPCR\\ReferentialIntegrityException(code: 0): HTTP 409: dc57583c-00f8-4d72-a760-62d7cb0a4964 cannot be removed because it is still being referenced at /var/data/websites/sulu.lo/vendor/jackalope/jackalope-jackrabbit/src/Jackalope/Transport/Jackrabbit/Request.php:546
`

**Comment by danrot** [comment]
I guess you get this error only when deleting which is linked in some way on a different page, right?

**Comment by alexander-schranz** [comment]
yeah on this project we deleted the internal link fields so its something like a ghost link that still exists. It should be possible to delete a page also when the page is linked somewhere.

**Comment by danrot** [comment]
This issue has already been fixed in https://github.com/sulu/sulu/pull/1709, but is currently broken because of https://github.com/sulu/sulu/issues/2752. I still close this, because the other issue explains the current problem in more detail.
