### ISSUE TITLE
Symfony\Component\Cache\Psr16Cache is incompatible with jackalope-doctrine-dbal

### ISSUE THREAD

**Issue by ghost** [sulu/sulu#7394]
| Q | A
| --- | ---
| Sulu Version | 2.6.0
| PHP Version | 8.3.0

In the [UPGRADE.md](https://github.com/sulu/sulu/blob/2.6/UPGRADE.md#phpcr-and-jackalope-update) it is recommended to update jackalope and then adjust the cache configuration. However, the Symfony cache adapter is not compatible with jackalope.

I get the following error:
```
Symfony\Component\Cache\Exception\InvalidArgumentException
Cache key "workspace:_default" contains reserved characters "{}()/\@:"."
```

This is caused by the following key:
https://github.com/jackalope/jackalope-doctrine-dbal/blob/78cf8b9cef45a41cb3fb2c776ed3ef779a40b152/src/Jackalope/Transport/DoctrineDBAL/CachedClient.php#L125

But even when I correct this key, I get other errors related to the keys used.

I can reliably reproduce it by doing a reindex in the article bundle:
```
bin/console sulu:article:reindex --drop --env=prod --no-interaction
```

**Comment by alexander-schranz** [comment]
@flogado Thx for the report can you share the output of `composer info`?

**Comment by ghost** [comment]
Unfortunately, I am not allowed to share the dependencies and versions used by the project.

Do you have any specific dependencies in mind that need to be checked?

**Comment by alexander-schranz** [comment]
@flogado

```
composer info | grep jackalope
composer info | grep cache
composer info | grep phpcr
```

**Comment by alexander-schranz** [comment]
@flogado Can you give https://github.com/jackalope/jackalope-doctrine-dbal/pull/447 a try?

**Comment by ghost** [comment]
That's exactly what I tried to do. But then the next error appears.

```
Cache key "nodetypes__a_1_{i_0;s_15_"nt_unstructured";}" contains reserved characters "{}()/\@:"
```

If we replace all reserved characters:

```
        $this->keySanitizer = static function ($cacheKey) {
            return str_replace(
                [' ', ':', '{', '}', '(', ')', '.', '@', '/', '"', '\\'],
                ['_', '|', '[', ']', '[', ']', '|', 'a', '|', '\'', '|'],
                $cacheKey
            );
        };
```

this error appears:

```
Jackalope\Transport\DoctrineDBAL\CachedClient::getNode(): Return value must be of type stdClass, null returned 
```

**Comment by alexander-schranz** [comment]
And only happening when the Cache is active? For `dev` where no cache is active no error is happening?

**Comment by ghost** [comment]
Yes, there are no problems in the dev environment.

**Comment by alexander-schranz** [comment]
I did some changes on the `CachedClient::get` can you check if that fixes also the issue for you: https://github.com/jackalope/jackalope-doctrine-dbal/pull/447

**Comment by alexander-schranz** [comment]
This was fixed in the latest jackalope doctrine dbal versions. Thx for the report @flogado

**Comment by ghost** [comment]
It works for me. Thank you very much.
