### ISSUE TITLE
Reference query in media does not work

### ISSUE THREAD

**Issue by ghost** [sulu/sulu#7395]
| Q | A
| --- | ---
| Sulu Version | 2.6.0
| PHP Version | 8.3

# Actual Behavior

Due to an incorrect database query, no references are displayed in the media management.

```
[Semantical Error] line 0, col 102 near 'enabled, reference.name,': Error: Class Sulu\Bundle\Reference­Bundle\Domain\Model\Reference has no field or association named enabled
```

# Steps to Reproduce

1. Open insights of a media file.
```
/admin/#/media/de/1000/insights/references?limit=1000
```
2. See fetch in network.
```
/admin/api/references?page=1&locale=de&resourceKey=media&resourceId=1000&limit=1000&fields=referenceTitle,referenceLocale,referenceResourceKey,referenceContext,referenceProperty,enabled,name,id&flat=true
```

# Possible Solutions

Remove `enable` from URL?

**Comment by alexander-schranz** [comment]
@flogado do you know where the field `enabled` comes from it is not listed in our list configuration: https://github.com/sulu/sulu/blob/2.6/src/Sulu/Bundle/ReferenceBundle/Resources/config/lists/references.xml

**Comment by ghost** [comment]
The list is a good hint, because we already have a list with the key “references”. I will rename the list. Thank you very much.
