### ISSUE TITLE
Symfony 7 compatibililty

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#7413]
# Problem description

Bring Symfony 7 compatibility to Sulu 2.6, but keep compatibility to Symfony 5 and 6.

Projects:

 - [x] sulu/sulu (running): https://github.com/sulu/sulu/pull/7156
 - [x] sulu/skeleton (running): https://github.com/sulu/skeleton/pull/246
 - [x] sulu/messenger: https://github.com/sulu/messenger/pull/6
 - [x] sulu/SuluContentBundle https://github.com/sulu/SuluContentBundle/pull/258
 - [x] sulu/SuluThemeBundle https://github.com/sulu/SuluThemeBundle/pull/35
     - [x] sylius/SyliusThemeBundle: https://github.com/Sylius/SyliusThemeBundle/pull/131
     - [x] sylius/SyliusThemeBundle: https://github.com/Sylius/SyliusThemeBundle/pull/134
 - [x] sulu/SuluArticleBundle https://github.com/sulu/SuluArticleBundle/pull/684
    - [x] Requires HeadlessBundle
    - [x] Requires AutomationBundle
 - [x] sulu/SuluAutomationBundle https://github.com/sulu/SuluAutomationBundle/pull/75
    - [x] https://github.com/php-task/php-task/ https://github.com/php-task/php-task/pull/49
    - [x] https://github.com/php-task/taskbundle https://github.com/php-task/TaskBundle/pull/55
 - [x] sulu/SuluHeadlessBundle https://github.com/sulu/SuluHeadlessBundle/pull/139
 - [x] sulu/SuluRedirectBundle  https://github.com/sulu/SuluRedirectBundle/pull/92
 - [x] sulu/SuluFormBundle https://github.com/sulu/SuluFormBundle/pull/390
 - [x] sulu/SuluCommentBundle https://github.com/sulu/SuluCommentBundle/pull/53
 - [x] sulu/SuluCommunityBundle https://github.com/sulu/SuluCommunityBundle/pull/172
 - [x] sulu/SuluSyliusConsumerBundle https://github.com/sulu/SuluSyliusConsumerBundle/pull/133
 - ~~[sulu/SuluSyliusProducerPlugin](https://github.com/sulu/SuluSyliusProducerPlugin)~~ This is related to the Sylius eco System: https://github.com/Sylius/Sylius/issues/15481 so currently we can not tackle it.

Add compatibility to Symfony 7, the bundles should still be compatible to PHP 8.0 and Sulu 2.5.

# Proposed solution

Mostly upgrade and see what is failing and check such things where changed in Symfony 7 support for Sulu. Mostly bundles need also add support for doctrine/persistence 3 before they can upgrade to Symfony 6.4 / 7.0.

Compatibility Sulu Core:

 - [x] doctrine-bridge 6.3 with validator 7.0: `Testing PHP Fatal error:  Declaration of Symfony\Bridge\Doctrine\Validator\DoctrineInitializer::initialize(object $object) must be compatible with Symfony\Component\Validator\ObjectInitializerInterface::initialize(object $object): void in /home/runner/work/sulu/sulu/vendor/symfony/doctrine-bridge/Validator/DoctrineInitializer.php on line 34` ( https://github.com/symfony/symfony/pull/51630 )
 - [x] sulu SecurityBundle and security-http 7.0 `PHP Fatal error:  Declaration of Sulu\Bundle\SecurityBundle\Security\AuthenticationEntryPoint::start(Symfony\Component\HttpFoundation\Request $request, ?Symfony\Component\Security\Core\Exception\AuthenticationException $authException = null) must be compatible with Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface::start(Symfony\Component\HttpFoundation\Request $request, ?Symfony\Component\Security\Core\Exception\AuthenticationException $authException = null): Symfony\Component\HttpFoundation\Response in /home/runner/work/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Security/AuthenticationEntryPoint.php on line 25` 
 - [x] doctrine/persistence 3.0 support
    - [x] Fix deprecations https://github.com/sulu/sulu/pull/7134
    - [x] Fix merge deprecations in fixtures https://github.com/sulu/sulu/issues/7184
    - [x] Allow doctrine/persistence 3.0 support https://github.com/sulu/sulu/pull/6643
    - [x] https://github.com/sulu/sulu/issues/7198
 - [x] Declaration of Sulu\Component\Content\Form\DataTransformer\DocumentToUuidTransformer::transform($document) must be compatible with Symfony\Component\Form\DataTransformerInterface::transform(mixed $value): mixed in /home/runner/work/sulu/sulu/src/Sulu/Component/Content/Form/DataTransformer/DocumentToUuidTransformer.php on line 32 https://github.com/sulu/sulu/pull/7190
 - [x] https://github.com/sulu/sulu/pull/7347
    - [x] VoterInterface changes
    - [x] UserProviderInterface changes
    - [x] Security Class changes
 - [x] https://github.com/sulu/sulu/pull/7357
    - [x] ContainerAwareInterface removal
 - [x] https://github.com/sulu/sulu/pull/7359
    - [x] LoaderInterface changes
    - [x] ExpressionLanguageProvider changes 
 - [x] https://github.com/sulu/sulu/pull/7371
    - [x] Add compatibility to Symfony 7 to ActivateResolveTargetEntityResolverPas
 - [x] https://github.com/sulu/sulu/pull/7368
    - [x] Add Symfony 7 compatibility to FieldDescriptorFactory
 - [x] https://github.com/sulu/sulu/pull/7369
    - [x] Fix PreviewKernel and RefreshCommand compatibility
 - [x] https://github.com/sulu/sulu/pull/7374
    - [x] Refactor doctrine.event_subscriber to doctrine.event_listener for Symfony 7 compatibility
 - [x] https://github.com/sulu/sulu/pull/7380
    - [x] Refactor JMS/Serializer annotations to attributes
 - [x] https://github.com/sulu/sulu/pull/7382
    - [x] Refactor ParameterBag in InputBag in Core Tests
 - [x] https://github.com/sulu/sulu/pull/7390
    - [x] Refactor HeaderBag to InputBag in Core Tests
 - [x] https://github.com/sulu/sulu/pull/7392
    - [x] Fix some return types in tests expections

Dependencies:

 - [x] friendsofsymfony/http-cache-bundle
    - [x] https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/613
    - [x] 3.x release
    - [x] Sulu compatibility: https://github.com/sulu/sulu/pull/7452
 - [x] friendsofsymfony/http-cache
    - [x] https://github.com/FriendsOfSymfony/FOSHttpCache/pull/552
    - [x] 3.x release
 - [x] dantleech/phpcr-migrations-bundle
    - [x] dantleech/phpcr-migrations (https://github.com/phpcr/phpcr-migrations/pull/18)
    - [x] requires doctrine/phpcr-bundle
    - [x] requires symfony-cmf/testing
 - [x] doctrine/phpcr-bundle
    - [x] https://github.com/doctrine/DoctrinePHPCRBundle/pull/387
 - [x] doctrine/doctrine-fixtures-bundle (Requires 4.0: https://github.com/doctrine/DoctrineFixturesBundle/pull/395)
    - [x] https://github.com/sulu/sulu/pull/7161
 - [x] friendsofsymfony/rest-bundle
    - [x] https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2400
 - [x] friendsofsymfony/jsrouting-bundle
    - [x] https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/471
 - [x] handcraftedinthealps/rest-routing-bundle
    - [x] requires friendsofsymfony/rest-bundle
 - [x] jms/serializer-bundle
    - [x] https://github.com/schmittjoh/JMSSerializerBundle/pull/937
 - [x] massive/build-bundle
    - [x] requires matthiasnoback/symfony-dependency-injection-test Symfony 7 support
    - [x] https://github.com/massiveart/MassiveBuildBundle/pull/25
 - [x] massive/search-bundle
    - [x] requires matthiasnoback/symfony-dependency-injection-test Symfony 7 support
    - [x] https://github.com/massiveart/MassiveSearchBundle/pull/172
 - [x] symfony-cmf/routing-bundle
    - [x] https://github.com/symfony-cmf/routing-bundle/pull/488
 - [x] matthiasnoback/symfony-config-test https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/releases/tag/5.0.0
 - [x] matthiasnoback/symfony-dependency-injection-test https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/releases/tag/5.0.0
 - [x] phpcr/phpcr-shell https://github.com/phpcr/phpcr-shell/pull/224
     - [x] https://github.com/phpcr/phpcr-utils/pull/214 (release missing)
     - [x] https://github.com/phpspec/phpspec/pull/1452
     - [x] https://github.com/Behat/Behat/pull/1442
 - [x] scheb/2fa-bundle
     - [x] Allow 7.x version https://github.com/sulu/sulu/pull/7254
     - [x] own 7.x version: https://github.com/scheb/2fa/blob/7.x/composer.json
 - [x] toflar/psr6-symfony-http-cache-store
    - [x] https://github.com/Toflar/psr6-symfony-http-cache-store/pull/46
 - [x] stof/doctrine-extensions-bundle
    - [x] requires first gedmo/extension https://github.com/doctrine-extensions/DoctrineExtensions

**Comment by TheCadien** [comment]
SuluHeadlessBundle Support: https://github.com/sulu/SuluHeadlessBundle/pull/139

**Comment by TheCadien** [comment]
SuluContentBundle: https://github.com/sulu/SuluContentBundle/pull/258

**Comment by TheCadien** [comment]
SuluCommentBundle: https://github.com/sulu/SuluCommentBundle/pull/53

**Comment by alexander-schranz** [comment]
Added also: https://github.com/php-task/php-task/ and https://github.com/php-task/TaskBundle to the list.

PS: we should keep all Sulu bundles compatible to PHP 8.0 and Sulu 2.5.

**Comment by alexander-schranz** [comment]
@TheCadien I updated https://github.com/sulu/SuluHeadlessBundle/pull/139 to show a better example how we can test current Pull Requests against Symfony 7 and also keep the supports for older Symfony and PHP versions. Which should not require newer versions if not really needed.

**Comment by alexander-schranz** [comment]
@TheCadien the core is merged which should make updating and testing the upgrade easier as we not longer need to set the fork.

**Comment by alexander-schranz** [comment]
@TheCadien Two bundles missing:

 - https://github.com/sulu/SuluSyliusConsumerBundle
 - https://github.com/sulu/SuluSyliusProducerPlugin
 
:)

**Comment by TheCadien** [comment]
@alexander-schranz I'm already on it 🫡

**Comment by alexander-schranz** [comment]
All Bundles are tagged with Symfony 7 Support. New Version of the core is coming soon so we  finally can close this one 🎉
