### ISSUE TITLE
A global block in a global block leads to 500 errors

### ISSUE THREAD

**Issue by ghost** [sulu/sulu#7414]
| Q | A
| --- | ---
| Sulu Version | 2.6.0
| PHP Version | 8.3

# Actual Behavior

If a global block (e.g. `foo`) is loaded into another global block (e.g. `bar`), this results in a 500 error for `/admin/config` due to a recursion. This was not a problem with includes.

# Steps to Reproduce

I have created a small example (with text_block and text_block**2**):
https://github.com/flogado/sulu-global-blocks/commit/adaab4a398e975de089e9265a019f0f1f74ff26c

# Possible Solutions

The recursion seems to happen in the `GlobalBlocksTypedFormMetadataVisitor::getGlobalBlockMetadata`.

**Comment by ghost** [comment]
Do you have a favorite approach? Then I would try to implement it myself. But right now I don't really know how to solve the recursion.

**Comment by lubomirfiala** [comment]
I ran into the same problem, but my findings are slightly different: my container was able to handle 2 global blocks inside another global block, but not more.

**Comment by alexander-schranz** [comment]
@flogado Thank you for the reproducer this helps. @wachterjohannes will have a look at this, currently not sure but we think recursion happening here: https://github.com/sulu/sulu/blob/5f79200e16461d586d42bd629ae6a5b25d141073/src/Sulu/Component/Content/Types/Metadata/GlobalBlocksTypedFormMetadataVisitor.php#L80 .

@lubomirfiala if you have another example we should check please let us know.

**Comment by alexander-schranz** [comment]
@flogado @lubomirfiala maybe you can give #7423 a try to test if this solve all your issues.

**Comment by ghost** [comment]
The recursion is gone, but now I get the following error in the browser:

```
Uncaught (in promise) Error: can't resolve reference #/definitions/app-product-category-overview-box from id #
```

Admin build was successful

```
rm -rf node_modules package-lock.json
npm i
npm run build
```

**Comment by ghost** [comment]
I have found the special case that leads to problems. Whenever a regular block comes first, which then contains a block that loads global blocks, this leads to an error.

Example page template:

```xml
<?xml version="1.0" ?>
<template
    xmlns="http://schemas.sulu.io/template/template"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd"
>
    <!-- ... -->
    <properties>
        <!-- ... -->
        <block name="foo" default-type="bar">
            <types>
                <type name="bar">
                    <properties>
                        <block name="baz" default-type="app-card">
                            <types>
                                <type ref="app-card" />
                            </types>
                        </block>
                    </properties>
                </type>
            </types>
        </block>
    </properties>
</template>
```

This results in:

```
Error: can't resolve reference #/definitions/app-card from id #
```
