### ISSUE TITLE
Set shared_max_age: 0 / s-maxage: 0 disable whole serverside http cache

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#7441]
| Q | A
| --- | ---
| Sulu Version | 2.6.2
| PHP Version | 8.3.7
| DB Version | -
| Browser Version | -

# Actual Behavior

Set shared_max_age: 0 disable whole http cache.

```yaml
sulu_http_cache:
    cache:
        max_age: 0
        shared_max_age: 0
```

# Expected Behavior

The configuraiton for shared cache should not automatically disables the server side cache. This is mostly related because to `$response->getCacheable();` in the Symfony configruation.

https://github.com/symfony/symfony/blob/1f90bc30c32b375ed2cdc3234f56d26b8b99cb53/src/Symfony/Component/HttpFoundation/Response.php#L562 

 - The isCacheable calls `isFresh` which is `$this->getTtl() > 0;`
 - The `getTtl` is `$this->getMaxAge()`
 - The `getMaxAge` is based on s-maxage: https://github.com/symfony/symfony/blob/1f90bc30c32b375ed2cdc3234f56d26b8b99cb53/src/Symfony/Component/HttpFoundation/Response.php#L760

Which is checked before storing: 

https://github.com/symfony/symfony/blob/cdbc32ab1c7efdb77334aa649e84c8fc7986fe65/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L422C24-L422C35

I would expect the [`CustomTtlListener`](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/3.x/src/SymfonyCache/CustomTtlListener.php) should disable depending on the `s-maxage` header but maybe that something Symfony can not do it. Maybe @dbu as a hint here for us.

But I think I need to debug here: https://github.com/FriendsOfSymfony/FOSHttpCache/blob/2b2ccae740c164c55ea43c6ccf5fca3011d00537/src/SymfonyCache/CustomTtlListener.php#L63 

# Workaround

```yaml
sulu_http_cache:
    cache:
        max_age: 0
        shared_max_age: 1
```

**Comment by dbu** [comment]
the idea is that if you set a custom-ttl, this would be respected by the cache regardless of s-maxage / max-age. the CustomTtlListener you linked temporarily [replaces](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/2b2ccae740c164c55ea43c6ccf5fca3011d00537/src/SymfonyCache/CustomTtlListener.php#L63) s-maxage with the custom-ttl value for the symfony cache and then [restores](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/2b2ccae740c164c55ea43c6ccf5fca3011d00537/src/SymfonyCache/CustomTtlListener.php#L86) it before returning the response to the client

do you configure a custom ttl on fos http cache in addition to the max-age and s-maxage, is this behaviour broken? 

FOSHttpCache seem to only have a [unit test](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/3.x/tests/Unit/SymfonyCache/CustomTtlListenerTest.php) for the CustomTtlListener but no end-to-end test. the [functional test](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/3.x/tests/Functional/Symfony/EventDispatchingHttpCacheTest.php) for the http cache does only verify that the plugin removes the custom ttl header.
if thinks seem broken, we should try to reproduce the issue with a unit or functional test in FOSHttpCache.

**Comment by alexander-schranz** [comment]
@dbu It seems not the fault of the FOSHttpCache component. The FOSHttpCache is in this case not even called because Symfony HttpCache is not calling it because the response is based on Symfony not `Cachable` the Cache Listeners are only called for responses which are already some kind of cacheable via a s-maxage.

https://github.com/symfony/symfony/blob/04f9e6dc07cc228fb3023579c0a63a6ae06a4674/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L408-L410


isCacheable: https://github.com/symfony/symfony/blob/04f9e6dc07cc228fb3023579c0a63a6ae06a4674/src/Symfony/Component/HttpFoundation/Response.php#L538-L548

isFresh: https://github.com/symfony/symfony/blob/04f9e6dc07cc228fb3023579c0a63a6ae06a4674/src/Symfony/Component/HttpFoundation/Response.php#L560-L563

getMaxAge: https://github.com/symfony/symfony/blob/04f9e6dc07cc228fb3023579c0a63a6ae06a4674/src/Symfony/Component/HttpFoundation/Response.php#L758-L774 (don't support custom headers and the listener is called only when store is called)

At current state listeners can only make cachable responses uncacheable but they can not make not cacheable responses cacheable.

**Comment by dbu** [comment]
uh. maybe that changed since when we implemented the event dispatching http cache - or we never noticed that issue. i do think the intention was to allow the listener also to make something uncacheable cacheable. the inheritance pattern makes things a bit fragile here. 

i consider this a bug in FOSHttpCache, it clearly was the intention, and with varnish cache the custom ttl works independently of s-maxage. i had a look at the EventDispatchingHttpCache class and CustomTtlListener. i think we should change https://github.com/FriendsOfSymfony/FOSHttpCache/blob/3.x/src/SymfonyCache/CustomTtlListener.php#L99 to ask for PRE_HANDLE instead of PRE_STORE. that would avoid the issue, right?

**Comment by alexander-schranz** [comment]
@dbu as I did have a look at PreHandle is too early there I think not even the response exist yet.

As I understand it is:

 - PreHandle
 - Handle -> Response -> isCacheable -> store ->
    - PreStore
 - PostStore

There is no way to hook between the handle and the store process without we registering a ResponseListener.

**Comment by dbu** [comment]
oh, you are right of course :facepalm: no response available at PRE_HANDLE. i dug a bit more in core HttpCache and i think the right moment would be to decorate the `HttpCache::forward` method and have a new event PostForward (and we could also do PreForward, while we are at it, could be interesting to hook into that place - e.g. varnish does have a hook for that step). then we could change CustomTtlListener to look into the response at PostForward instead of PreStore, updating it so that it will be stored. does that make more sense than my previous idea?

(and looking at the size and complexity of HttpCache, using decoration instead of inheritance seems rather unrealistic, we would need to basically reimplement the HttpCache class then...)

**Comment by alexander-schranz** [comment]
@dbu What I was thinking about also was moving the `isCacheable` check inside the store method:

```diff
diff --git a/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php b/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php
index 184666978c..462e0668a9 100644
--- a/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php
+++ b/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php
@@ -419,9 +419,7 @@ class HttpCache implements HttpKernelInterface, TerminableInterface
             $this->record($request, 'invalid');
         }

-        if ($response->isCacheable()) {
-            $this->store($request, $response);
-        }
+        $this->store($request, $response);

         return $response;
     }
@@ -447,9 +445,7 @@ class HttpCache implements HttpKernelInterface, TerminableInterface

         $response = $this->forward($subRequest, $catch);

-        if ($response->isCacheable()) {
-            $this->store($request, $response);
-        }
+        $this->store($request, $response);

         return $response;
     }
@@ -601,6 +597,10 @@ class HttpCache implements HttpKernelInterface, TerminableInterface
      */
     protected function store(Request $request, Response $response)
     {
+        if ($response->isCacheable()) {
+            return;
+        }
+
         try {
             $restoreHeaders = [];
             foreach ($this->options['skip_response_headers'] as $header) {
```

Then the PreStore hook is always called.

But that would be a Symfony Core change and would then required major changes or could be a bc break in the Symfony core.

But a forward and PostForward event may could be a solution work for all Symfony versions. I just to unfamiliar about the different callstacks here if forward is in all called in similar stack traces as the store method.

**Comment by dbu** [comment]
changing symfony core would be difficult, and could have weird/dangerous side effects for anyone extending the HttpCache class.

i created https://github.com/FriendsOfSymfony/FOSHttpCache/pull/577 - can you check if that indeed fixes the issue?

**Comment by alexander-schranz** [comment]
@dbu yes it works like I expected.

The only part which we may need to recheck is the `CustomTtlListener` makes now `private` requests always public, specially in case of `$fallbackToSmaxAge = false`.

If we want that `private` responses are never cached also when `CustomTtlListener` is used we would require:

```diff
diff --git a/src/SymfonyCache/CustomTtlListener.php b/src/SymfonyCache/CustomTtlListener.php
index 4be17d9..9ff303e 100644
--- a/src/SymfonyCache/CustomTtlListener.php
+++ b/src/SymfonyCache/CustomTtlListener.php
@@ -77,12 +77,18 @@ class CustomTtlListener implements EventSubscriberInterface
             ? $response->headers->getCacheControlDirective('s-maxage')
             : 'false'
         ;
+
         $response->headers->set(static::SMAXAGE_BACKUP, $backup);
+        $isPrivate = $response->headers->getCacheControlDirective('private');
+        // calling setTtl will make a response public, so we need to set it back to private if it was private before
         $response->setTtl(
             $response->headers->has($this->ttlHeader)
                 ? $response->headers->get($this->ttlHeader)
                 : 0
         );
+        if ($isPrivate) {
+            $response->setPrivate();
+        }
     }

     /**
```

Or alternative us `addCacheControlDirective` instead of `setTtl`:

```diff
diff --git a/src/SymfonyCache/CustomTtlListener.php b/src/SymfonyCache/CustomTtlListener.php
index 4be17d9..31126f3 100644
--- a/src/SymfonyCache/CustomTtlListener.php
+++ b/src/SymfonyCache/CustomTtlListener.php
@@ -77,8 +77,11 @@ class CustomTtlListener implements EventSubscriberInterface
             ? $response->headers->getCacheControlDirective('s-maxage')
             : 'false'
         ;
+
         $response->headers->set(static::SMAXAGE_BACKUP, $backup);
-        $response->setTtl(
+
+        $response->headers->addCacheControlDirective(
+            's-maxage',
             $response->headers->has($this->ttlHeader)
                 ? $response->headers->get($this->ttlHeader)
                 : 0
```

@dbu What do you think would be expected behaviour for:

```php
$response = new Response();
$response->setPrivate(0);
$response->header->set('X-Reverse-Proxy-TTL', 1200);
```

Current version (2.15.3) would not cache it. With https://github.com/FriendsOfSymfony/FOSHttpCache/pull/577 and `CustomTtlListener(fallbackToSmaxage: false)` it will now be cached. But I think explicit set private responses should not be cached even when a custom ttl is set? As example private response with a s-maxage defined is also not cached.

**Comment by alexander-schranz** [comment]
Fixed in https://github.com/sulu/sulu/pull/7540 and the FOSHttpCache package.
