### ISSUE TITLE
[Feature Request] Access currently used page localization in template

### ISSUE THREAD

**Issue by spackmat** [sulu/sulu#7443]
# Problem description

The `localizations` variable in Twig only has access to the configured localizations of the current webspace, but does not allow to determine, which of the localizations is currently used. I dumped all variables in twig but did not find that information in any of these. The only way I could find is to check the `request.resourceLocatorPrefix` for the language, but that is only an indirect test and could differ between webspaces depending on their config. 

I need that information to remove the current language from the language switcher (or mark it as active or whatever).

At the moment I only have to deal with two languages, so testing `request.resourceLocatorPrefix` against `null` to check if we are on the default language or not is sufficient, but I thing that is a limitation that hurts everyone who has to build a language switcher that is not just a dumb list of available languages.

# Proposed solution

I suggest to add an `active` boolean to the properties `locale`, `url` and `country` of the `localization` elements, so that a language switcher can depend on that.

Or, if that information is already available at another place, document that at https://docs.sulu.io/en/2.6/book/localization.html#usage-of-localizations

**Comment by alexander-schranz** [comment]
There is no specific Sulu things here the current locale is in the Symfony way under the locale request objec tso you get in in twig `app.request.locale`. Example can be found in the demo: https://github.com/sulu/sulu-demo/blob/8a66e447ecb2729afd99d702c0d31409e8d1dbf7/templates/includes/navbar.html.twig#L28

We don't want to duplicate such data too much and keep things as near as possible to Symfony.

**Comment by spackmat** [comment]
> We don't want to duplicate such data too much and keep things as near as possible to Symfony.

A good idea, I didn't expect that as my brain was within Sulu-specific stuff. Then maybe that should be noted in the documentation
