### ISSUE TITLE
OpenId SSO default locale user

### ISSUE THREAD

**Issue by just-alexis** [sulu/sulu#7444]
| Q | A
| --- | ---
| Sulu Version | 2.6.2
| PHP Version | 8.3.7
| DB Version | PGSQL
| Browser Version | Brave 1.66

# Actual Behavior

Hello,

I did the upgrade to sulu 2.6 and also the OpenId Integration with our Azure active directory for authentification.
I just have a problem with the default locale ("en" or "de") for each connection.

In the class OpenIdSingleSignOnAdapter, at line 277, at each connection the locale is set to the default value "en". But in my project i have define the default value to "fr" because we maintain our website only with "fr" locale.
I have to set "fr" again in DB to give the right access to my user.
Currently it is impossible to use for me, because at each connection the bdd field is set to "en" and erase my "fr".

Also when a new user connect, the default role locale is set to ["en", "de"] (line 269) instead of the global variable defaultLocale "fr". So i have to manualy fix this every time.

# Expected Behavior

Use the global variable defaultLocale for default locale when user connect.

Or can i have a workaround to force default locale to fr with Azure. The attribute "locale" doesn't exist in the call getUserInfo at Azure.

**Comment by alexander-schranz** [comment]
Thx for the issue.

**A. System Locale**

Normally in OpenId Connect Specification the OpenId Provider can provide the locale for the User. Via the locale attribute: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

What does azure send you as `$attributes['locale']` for that user? Is your open id provider configure to provide a locale here or did you miss to activate that claim for the user.


**B. User Role Locales**

For the default user role locale we maybe should switch instead of giving new users always access to all locales instead of `de` `en` only. See https://github.com/sulu/sulu/blob/a57671127bde0227699c4e609052a514ecba9c98/src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php#L115 as example how to get all locales. Do you want to create a merge request for this?

**Comment by just-alexis** [comment]
Thx for your answer.

**A.**
Locale attribute is not specified, i have the same response as Microsoft shows in their documentation : https://learn.microsoft.com/en-us/entra/identity-platform/userinfo#calling-the-api
I tried multiple thing to add the locale attribute in the response but it seem not possible with Azure.

**B.**
Hum i have never done a pull request or something in a public repository. It was for information or if i miss something.

**Comment by steeven-otd** [comment]
Hi
I have the same problem with Azure. When I log in, it changes the locale to EN even though I had changed it in the user account settings.

**Comment by steeven-th** [comment]
Hi
I have the same problem with Azure. When I log in, it changes the locale to EN even though I had changed it in the user account settings.

**Comment by alexander-schranz** [comment]
Make sure that you configure Azure the way that it provides your users locale via OpenId. Then you should get the correct locale here: https://github.com/sulu/sulu/blob/9ee10853304f2dc39e84a3a91da8e3e193d74391/src/Sulu/Bundle/SecurityBundle/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapter.php#L275. Currently it fallbacks to `en` if not defined.

**Comment by steeven-th** [comment]
The locale is not sent by default by Microsoft Azure Entra. To retrieve it, you need to authorize access to User.Read.All, and it must also be included in the scope of the query along with ‘openid email phone profile address’. After that, you will receive an attribute called ‘preferredLanguage’ in the format en_EN.
You should check if the user exists, and if the ‘locale’ attribute is null, do not set the user’s locale, keep what is already stored in the database.

Check if the user has a locale :
```php
$locale = (isset($attributes['locale']) && \in_array($attributes['locale'], $this->translations, true)) ? $attributes['locale'] : ($user instanceof User && $user->getLocale() ? $user->getLocale() : 'en');
```

https://github.com/sulu/sulu/blob/9ee10853304f2dc39e84a3a91da8e3e193d74391/src/Sulu/Bundle/SecurityBundle/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapter.php#L275-L276

**Comment by steeven-th** [comment]
I have created a PR : https://github.com/sulu/sulu/pull/7590#issue-2536261287
