### ISSUE TITLE
Contacts list cannot be sorted by categories

### ISSUE THREAD

**Issue by datenwerk-at** [sulu/sulu#7445]
| Q | A
| --- | ---
| Sulu Version | 2.6.2
| PHP Version | 8.2.0
| DB Version | n/a
| Browser Version | n/a

# Actual Behavior

After sorting the BE contacts list by categoryNames, the list is empty.
API returns a 500 response with exception:
`[Semantical Error] line 0, col 530 near 'SuluCategoryBundle_CategoryTranslation.translation': Error: 'SuluCategoryBundle_CategoryTranslation' is not defined.`

Since the selected sorting option is stored in the database, the contacts list won't work anymore at all untill you clear the se_user_settings table.

# Expected Behavior

Contacts list should not be be empty and be sorted by categoryNames.

# Steps to Reproduce

1. Fresh Sulu 2.6 install
2. Create some conatcts
3. Go to column options and select Categories column to be visible
4. Sort by categories

**Comment by mamazu** [comment]
Fixed
