### ISSUE TITLE
Wrong url when copying content from one language to another (type="link")

### ISSUE THREAD

**Issue by harunbuljubasic** [sulu/sulu#7446]
| Q | A
| --- | ---
| Sulu Version |  2.5.1 
| PHP Version |  8.1 
| DB Version | -
| Browser Version | -

# Actual Behavior

When I try to copy content from one language to another, the url of "link" content type stays the same.
For example if homepage is selected in the page selection, after copying the old url will be shown.

INFO: The same works with "single_page_selection", only with "link" not.

# Expected Behavior

After copying the page, the page url from the target language should be shown.

**Comment by alexander-schranz** [comment]
I think this may was already fixed in 2.5.10 here: https://github.com/sulu/sulu/pull/7121 @harunbuljubasic please let us know if that resolve the issue.

**Comment by harunbuljubasic** [comment]
Yes, that resolve the issue, thanks.
