### ISSUE TITLE
Preview for file versions from history not working

### ISSUE THREAD

**Issue by harunbuljubasic** [sulu/sulu#7448]
| Q | A
| --- | ---
| Sulu Version | 2.5.12
| PHP Version | 8.1
| DB Version | MySQL 8.0.34
| Browser Version | 

# Actual Behavior

By click on file version preview in Sulu Admin (Media->History) comes an error: `File not found: 5006 File version 2 of the Media with id 9423`. 

# Possible Solutions

This bug only occurs in Sulu versions `>= 2.5.12`, so it probably has something to do with this enhancement: https://github.com/sulu/sulu/pull/7259/files

**Comment by alexander-schranz** [comment]
I think this is duplicated to: https://github.com/sulu/sulu/issues/7319 so closing this one.
