### ISSUE TITLE
Custom Admin Build errors with: Module not found: Error: Can't resolve 'node:url'

### ISSUE THREAD

**Issue by patrick-tassa-cafpi** [sulu/sulu#7449]
| Q | A
| --- | ---
| Sulu Version | 
| PHP Version | 
| DB Version | 
| Browser Version | 

# Actual Behavior

Run `npm install && npm run build` on assets/admin folder ending error with : 
`Module not found: Error: Can't resolve 'node:url' in '/var/www/html/sources/assets/admin/node_modules/fast-uri'`

# Expected Behavior

No error when runnning `npm install && npm run build` 

# Steps to Reproduce

`cd $project/assets/admin`
`npm install && npm run build`

# Possible Solutions
inside your $project/assets/admin/package.json, link the package with a previous version

```diff
   "dependencies": {
+        "ajv": "8.14.0"
   }
```

**Comment by alexander-schranz** [comment]
Reference to the ajv which 8.15 release is causing the issue https://github.com/ajv-validator/ajv/issues/2446 while also the 2.3.0 release last year of fast-uri did break the version for browser I think also https://github.com/fastify/fast-uri/issues/82

**Comment by alexander-schranz** [comment]
Should be fixed now in https://github.com/ajv-validator/ajv/issues/2446 can you confirm? @patrick-tassa-cafpi
