### ISSUE TITLE
 Template appears in dropdown despite missing Twig file

### ISSUE THREAD

**Issue by mcoiffier** [sulu/sulu#7476]
| Q | A
| --- | ---
| Sulu Version | 2.6.2 
| PHP Version | 8.2.20
| SuluThemeBundle | ^3.1 
| Browser Version | Chrome  v.125.0.6422.142

# Actual Behavior
When I **only** create an XML template in `/config/templates/pages/hello.xml`.
Hello appears in the dropdown list when choosing the template of a page
![sulu_error](https://github.com/sulu/sulu/assets/6615246/281b0ecc-5aae-4951-853f-5e0bb983f954)

Resuming the default.xml template: with only these changes:

```
<key>hello</key>

<view>pages/hello</view>
<controller>Sulu\Bundle\WebsiteBundle\Controller\DefaultController::indexAction</controller>
<cacheLifetime>604800</cacheLifetime>

<meta>
    <title lang="en">Hello</title>
    <title lang="de">Hello</title>
</meta>
```

# Expected Behavior
According to the documentation https://docs.sulu.io/en/2.6/book/templates.html, the Hello template should not appear in the dropdown list.

> A template is shown in the dropdown only if both the XML and the Twig file exist! If you can’t see your template, double-check the directories config/templates/pages and templates/pages.

# Others information 
When using the command `sulu:content:validate:webspaces`, there is indeed an error indicating: **failed: Unable to find template "pages/hello.html.twig"**

# Possible Solutions

Is the documentation no longer up-to-date, and do we now need to use the `excluded-templates` node?
_A bit off-topic:_
If we need to use the excluded-templates node, then I'm having to go through each webspace (I have 8+) and declare the file to be excluded every time I create a new template. Is this the only solution?

**Comment by mamazu** [comment]
Alternatively we could just show it grayed out and when hovering display the message that the template is missing. Making it easier to discover what exactly went wrong.

**Comment by alexander-schranz** [comment]
This sentence is not longer true and expected behaviour for 2.x of Sulu. To exclude templates configure specific templates as excluded inside your webspace.xml file.

**Comment by mamazu** [comment]
Then I suggest moving this issue to the docs and updating the docs.

**Comment by mcoiffier** [comment]
Ok i've just created the "bug" https://github.com/sulu/sulu-docs/issues/808 and the PR https://github.com/sulu/sulu-docs/pull/809 in the sulu-docs repo.
Maybe we can close this issue as it is not related to the Sulu core.

**Comment by mamazu** [comment]
Thanks, looks good to me.
