### ISSUE TITLE
Performance issues when working with smart contents and many categories

### ISSUE THREAD

**Issue by friemt** [sulu/sulu#7485]
| Q | A
| --- | ---
| Sulu Version | 2.5.9
| PHP Version | 8.1
| DB Version | MySQL 8.0
| Browser Version | n/a

# Actual Behavior

When working with a larger amount of categories the SQL statements generated for smart-contents become exceptionally inefficient.

The function `\Sulu\Component\SmartContent\Orm\DataProviderRepositoryTrait::findByFilters` is used to retrieve data for contacts or accounts which in turn gets joins via a call to the respective repositories `appendJoins` function. Contacts and Accounts have several many-to-many relations, like `tags` and `categories` added to the query in this function. In our case this produces a result set of about ~12k rows for 6 requested contacts. Not only have those rows to be returned to the php process, doctrine also has to merge them back into 6 entities, which is tremendously inefficient.

Furthermore, since order-by are defined on the entity ORM files, several order-by clauses are automatically added, which can not be removed programmatically. This clause alone slows down the statement by a factor 10 to 100.

`ORDER BY co_accounts.id ASC, co_emails.id ASC, co_faxes.id ASC, co_urls.id ASC, ta_tags.name ASC, ca_categories.id ASC, co_phones.id ASC`

<details><summary>SQL Explain</summary>
<pre>
-> Sort row IDs: c0_.id, c1_.id, c5_.id, c7_.id, t9_.`name`, c10_.id, c3_.id  (actual time=190..247 rows=11149 loops=1)
    -> Table scan on <temporary>  (cost=2394..2443 rows=3691) (actual time=124..140 rows=11149 loops=1)
        -> Temporary table  (cost=2394..2394 rows=3691) (actual time=124..124 rows=11149 loops=1)
            -> Nested loop left join  (cost=2025 rows=3691) (actual time=1.71..19.9 rows=11149 loops=1)
                -> Nested loop left join  (cost=318 rows=1082) (actual time=1.59..8.01 rows=1862 loops=1)
                    -> Nested loop left join  (cost=173 rows=1082) (actual time=1.49..5.06 rows=1862 loops=1)
                        -> Nested loop left join  (cost=53.1 rows=43.3) (actual time=1.41..4.42 rows=23 loops=1)
                            -> Nested loop left join  (cost=43.9 rows=43.3) (actual time=1.39..4.29 rows=23 loops=1)
                                -> Nested loop left join  (cost=36.2 rows=13.3) (actual time=1.34..4.21 rows=6 loops=1)
                                    -> Nested loop left join  (cost=33.4 rows=13.3) (actual time=1.33..4.2 rows=6 loops=1)
                                        -> Nested loop left join  (cost=30.6 rows=13.3) (actual time=1.32..4.18 rows=6 loops=1)
                                            -> Nested loop left join  (cost=25.9 rows=13.3) (actual time=1.27..4.11 rows=6 loops=1)
                                                -> Nested loop left join  (cost=23.1 rows=13.3) (actual time=1.24..4.08 rows=6 loops=1)
                                                    -> Nested loop left join  (cost=17.9 rows=13.3) (actual time=1.17..4 rows=6 loops=1)
                                                        -> Nested loop left join  (cost=13.3 rows=13) (actual time=1.14..3.95 rows=6 loops=1)
                                                            -> Nested loop left join  (cost=10.5 rows=13) (actual time=1.1..3.91 rows=6 loops=1)
                                                                -> Nested loop left join  (cost=6.03 rows=13) (actual time=1.06..3.84 rows=6 loops=1)
                                                                    -> Left hash join (c2_.id = c1_.idEmailTypes)  (cost=1.64 rows=12.4) (actual time=0.979..3.73 rows=6 loops=1)
                                                                        -> Nested loop left join  (cost=7.01 rows=6.2) (actual time=0.271..3.02 rows=6 loops=1)
                                                                            -> Nested loop left join  (cost=4.84 rows=6.2) (actual time=0.209..2.92 rows=6 loops=1)
                                                                                -> Filter: (c0_.id in (279,281,305,407,419,441))  (cost=2.72 rows=6) (actual time=0.165..2.86 rows=6 loops=1)
                                                                                    -> Index range scan on c0_ using PRIMARY over (id = 279) OR (id = 281) OR (4 more)  (cost=2.72 rows=6) (actual time=0.156..2.84 rows=6 loops=1)
                                                                                -> Covering index lookup on c12_ using IDX_3E246FC3996BB4F7 (idAccounts=c0_.id)  (cost=0.267 rows=1.03) (actual time=0.00891..0.00992 rows=1 loops=6)
                                                                            -> Single-row index lookup on c1_ using PRIMARY (id=c12_.idEmails)  (cost=0.266 rows=1) (actual time=0.0158..0.0158 rows=1 loops=6)
                                                                        -> Hash
                                                                            -> Table scan on c2_  (cost=0.083 rows=2) (actual time=0.391..0.413 rows=2 loops=1)
                                                                    -> Covering index lookup on c13_ using IDX_918DA964996BB4F7 (idAccounts=c0_.id)  (cost=0.258 rows=1.05) (actual time=0.015..0.0159 rows=0.833 loops=6)
                                                                -> Single-row index lookup on c3_ using PRIMARY (id=c13_.idPhones)  (cost=0.25 rows=1) (actual time=0.0114..0.0114 rows=0.833 loops=6)
                                                            -> Single-row index lookup on c4_ using PRIMARY (id=c3_.idPhoneTypes)  (cost=0.129 rows=1) (actual time=0.00696..0.00696 rows=0.833 loops=6)
                                                        -> Covering index lookup on c14_ using IDX_7A4E77DC996BB4F7 (idAccounts=c0_.id)  (cost=0.258 rows=1.02) (actual time=0.00653..0.00699 rows=0.333 loops=6)
                                                    -> Single-row index lookup on c5_ using PRIMARY (id=c14_.idFaxes)  (cost=0.297 rows=1) (actual time=0.0122..0.0122 rows=0.333 loops=6)
                                                -> Single-row index lookup on c6_ using PRIMARY (id=c5_.idFaxTypes)  (cost=0.123 rows=1) (actual time=0.00521..0.00521 rows=0.333 loops=6)
                                            -> Covering index lookup on c15_ using PRIMARY (idAccounts=c0_.id)  (cost=0.258 rows=1) (actual time=0.0111..0.0111 rows=0 loops=6)
                                        -> Single-row index lookup on c7_ using PRIMARY (id=c15_.idUrls)  (cost=0.12 rows=1) (actual time=0.00306..0.00306 rows=0 loops=6)
                                    -> Single-row index lookup on c8_ using PRIMARY (id=c7_.idUrlTypes)  (cost=0.12 rows=1) (actual time=611e-6..611e-6 rows=0 loops=6)
                                -> Covering index lookup on c16_ using IDX_E8D92005996BB4F7 (idAccounts=c0_.id)  (cost=0.275 rows=3.26) (actual time=0.0116..0.0132 rows=3.5 loops=6)
                            -> Single-row index lookup on t9_ using PRIMARY (id=c16_.idTags)  (cost=0.115 rows=1) (actual time=0.00529..0.00531 rows=0.913 loops=23)
                        -> Covering index lookup on c17_ using IDX_B60E9510996BB4F7 (idAccounts=c0_.id)  (cost=0.316 rows=25) (actual time=0.00757..0.0231 rows=81 loops=23)
                    -> Single-row index lookup on c10_ using PRIMARY (id=c17_.idCategories)  (cost=0.0347 rows=1) (actual time=0.0014..0.00143 rows=1 loops=1862)
                -> Index lookup on c11_ using IDX_5DCED5E3B8075882 (idCategories=c10_.id)  (cost=1.24 rows=3.41) (actual time=0.00153..0.00589 rows=5.99 loops=1862)
</pre>
</details> 

# Expected Behavior

~1k categories do not result in excessive server resource usage.

# Steps to Reproduce

- Take any sulu instance.
- Profile smart-content SQL statements and result sets.

# Possible Solutions

- Remove at least the many-to-many joins from the `appendJoin` function to avoid larger than necessary result sets.
- Remove hard coded order-by clauses from the entity ORM files.

**Comment by mamazu** [comment]
Could it be that iterating over the tag names would be the problem as they might not be indexed?

**Comment by alexander-schranz** [comment]
@friemt as discussed we will currently remove the hardcoded order-bys: https://github.com/sulu/sulu/pull/7487 still I think your suggestion better use lazy loading of doctrine instead of overfetch things is a better default for us, @friemt let us know how it works in your project then we can check out to get this pack to sulu core.

@mamazu names are index they even have a unique index on them.

**Comment by friemt** [comment]
Found the same issue here: `\Sulu\Bundle\MediaBundle\Entity\MediaRepository::findMediaById`. In our case the query produces a result set of up to ~4k rows for a single media entity. Without the tag and category joins it's a maximum of 50.

**Comment by alexander-schranz** [comment]
I even thinking about if Categories and Tags should be extra lazy relations for all cases. But have not yet enough experience with it. You may could create a doctrine metadata listener which sets the relation to extra lazy.

In cases of filters based on categories and tags they are always joined. But maybe not a problem when not being selected 🤔 .

**Comment by alexander-schranz** [comment]
fixed in #7529 thx @friemt
