### ISSUE TITLE
CMS: Show which fields are invalid, and/or log validation errors in the developer console

### ISSUE THREAD

**Issue by AdamReece-WebBox** [sulu/sulu#7522]
| Q | A
| --- | ---
| Sulu Version | 2.4.17
| PHP Version | 8.2.21
| DB Version | 10.6.18-MariaDB
| Browser Version | Chrome 126

# Actual Behaviour

When submitting a form in the CMS with an invalid value a generic "The form contains invalid values" error appears, but doesn't show which field(s) are the problem.

![image](https://github.com/sulu/sulu/assets/16222407/a4dddebf-ab9d-4d18-a1e0-713bf4fe4878)

# Expected Behaviour

Indication within the form as to which fields are the problem.

# Steps to Reproduce

Edit a user with the intention of renaming their first or last name, then try to save your change.

# Possible Solutions

Ideally an indicator against all the invalid fields individually.

In all cases, including where it may not be possible to place an indicator, the field name/path should be output in the browser console so that developers can see what the problem is. Currently it's amazingly difficult to find out, particularly as this validation is happening client side.

# Other Information

This is a continuation of https://github.com/sulu/sulu/issues/3749 though a bit old to continue commenting on.

**Comment by alexander-schranz** [comment]
Thanks for the report this is no bug, just a feature which does not exist yet.

Please add your thoughts to the existing issue here https://github.com/sulu/sulu/issues/5809

**Comment by AdamReece-WebBox** [comment]
Thanks for your response Alexander, I'll keep track of that issue.

From an end user perspective though, regular use of the CMS, how could they know what's wrong with the form their submitting? In that context all they experience is an unfit UI. (This is for the standard user form mind, without customisations.)

If there was a console log message outputting invalid field names or paths we could at least replicate their form and tell them what is not being accepted. These log messages wouldn't even need to contain a detailed reason.
