### ISSUE TITLE
Textarea Component Placeholder not working

### ISSUE THREAD

**Issue by rhp-zellerd** [sulu/sulu#7531]
| Q | A
| --- | ---
| Sulu Version | 2.6.3
| PHP Version | 8.2
| Browser Version | Chrome 126

# Actual Behavior

When you include the official Sulu Textarea into your React Views and set a placeholder no placeholder appears.

```
const [value, setValue] = React.useState('');

<TextArea
    value={value}
    placeholder="Tell me something about yourself..."
    onChange={setValue}
    onFinish={() => alert('TextArea lost focus!')}
/>
```

# Expected Behavior

Placeholder is displayed correctly

**Comment by alexander-schranz** [comment]
Did you import the correct `TextArea` component and not accidently something else? I don't see why the placeholder should not work. It is set here: https://github.com/sulu/sulu/blob/647f02faad088672ac0c261d4984ae067a8eda5f/src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/TextArea.js#L65 

The rest the browser should take care of.

**Comment by rhp-zellerd** [comment]
Okay thats the culprit. It autoimported `import {TextArea} from "sulu-admin-bundle/containers/Form";` and not the correct one under `import TextArea from "sulu-admin-bundle/components/TextArea/TextArea";` Maybe this should be visible in the docs which is the correct one 😁

**Comment by alexander-schranz** [comment]
It always depends on what you want to use. The JS components are structured into:

 - components
 - containers
 - views
 - (stores, utils, services)
 
which is a common practice for react applications. The raw components live in the components directory. The containers mostly have application specific logic in it and access to stores and states. So if you want the raw component currently also possible to import it via:

```js
import {TextArea} from "sulu-admin-bundle/components";
```

As the index.js there also export it like the containers. https://github.com/sulu/sulu/blob/2.6/src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js. Strange your IDE suggested container over components.
