### ISSUE TITLE
RequestListener portal information not work with User Context Based Caching

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#7551]
| Q | A
| --- | ---
| Sulu Version | 2.5.10
| PHP Version | -
| DB Version | -
| Browser Version | -

# Actual Behavior

RequestListener portal information not work with UserContextBased caching.

Even the reuqest analyzer is disabled the analyzer still runs and set a prefix here:

https://github.com/sulu/sulu/blob/43fa5d35eb0b97ae48470846289d33c1104d8a9c/src/Sulu/Bundle/WebsiteBundle/Routing/RequestListener.php#L43-L56

As a prefix was already set for `/_fos_http_cache_user_context` which ends in locale `en`.
The setting is skipped for the real call of `/zh/login`.

# Expected Behavior

It should still work.

# Steps to Reproduce

Webspace:

```xml
<url language="en">{host}</url>
<url language="zh">{host}/zh</url>
```

`/zh` renderens `sulu_community.login` as `/login` instead of `/zh/login`

As reported by @Quehnie

# Possible Solutions

User context controller should may not call the request analyzer.

A. Solution a do not call it if RequestAnalyzer is set to false (requires documentation)
B. Always set the `prefix` (is may an issue with subrequest ESI, ...)
C. Always set it if the request is a `MainRequest` this may the best solution as it fixes for existing projects without adoption.

**Comment by mamazu** [comment]
This should be done right?

**Comment by alexander-schranz** [comment]
Yes this is already merged
