### ISSUE TITLE
Admin frontend config and navigation is not reloaded when logging in as different user

### ISSUE THREAD

**Issue by stollr** [sulu/sulu#7560]
| Q | A
| --- | ---
| Sulu Version | 2.5 branch
| PHP Version | 8.2
| Browser Version | Firefox 115.13.0esr

# Actual Behavior

When I log in to the admin area, logout again and relogin with another user (**without refreshing the site**) the `/admin/config` is not requested again and thus the navigation shows the name of the previous user and the same navigation items - even if the user should see different navigation items due to more or less privileges.

When I reload the page, the UI is correctly refreshed. So it is just a frontend issue ;-)

# Expected Behavior

The config has to be reloaded after each login and navigation has to be refreshed.

**Comment by stollr** [comment]
Looks like this issue only happens, because of some customizations in our system. It is not reproducable in a fresh installation of Sulu. So I'll close this for now.

**Comment by stollr** [comment]
Sorry. After another test I realized, that this issue exists, but only if 2FA is enabled.

**Comment by alexander-schranz** [comment]
@Prokyonn did a lot of changes for loading of configs in #7626. the current released version is there little buggy. Can you check if #7626 fixes this issue? You need a manually rebuild of the JS to test it.

**Comment by stollr** [comment]
I am closing this issue, because the PR #7632 has been merged.
