### ISSUE TITLE
Get rid of country table and use symfony regionbundle

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#758]
RegionBundle from Symfony Component have all we need for countries. We should just store the countryShort ('at') in the contact and use e.g.: \Symfony\Component\Intl\Intl::getRegionBundle()->getCountryNames() to get Countries it also returns translated names.

**Comment by dantleech** [comment]
++1

**Comment by wachterjohannes** [comment]
+1

**Comment by danrot** [comment]
+1

**Comment by chirimoya** [comment]
+1

**Comment by dmetzler1988** [comment]
+1

**Comment by danrot** [comment]
@chirimoya Something related came up once more. I've added this to the 2.0 milestone, because I think it would make sense. @alexander-schranz sounded very motivated in fixing this, so that might be ready before the release :smiley:
