### ISSUE TITLE
sulu_admin.external_link translation failed

### ISSUE THREAD

**Issue by hual7** [sulu/sulu#7601]
| Q | A
| --- | ---
| Sulu Version | 2.6.5
| PHP Version | 8.3
| DB Version | MariaDB 10.11
| Browser Version | Chrome 129

# Actual Behavior

`sulu_admin.external_link` hasn't been translated.

<img width="787" alt="Bildschirmfoto 2024-10-06 um 10 14 15" src="https://github.com/user-attachments/assets/a3b48e27-745d-46aa-8836-4df25dfa36c6">
<img width="266" alt="Bildschirmfoto 2024-10-06 um 10 14 51" src="https://github.com/user-attachments/assets/fc58bd4c-5bbc-43e1-9c40-605b5ac5c2a9">

**Comment by Prokyonn** [comment]
@hual7 thank you for bringing up this issue!

It looks like there is a timing issue, because the link type is registered with the translation before the translations are initialized, therefore the translation was missing at this point.

https://github.com/sulu/sulu/pull/7606 should fix it. If you have time I would appreciate if you can test the branch 😄

**Comment by hual7** [comment]
Working with the #7606 branch.

Just for info - if I change my profile system language to German, I get the following warning:
<img width="649" alt="Bildschirmfoto 2024-10-08 um 10 06 17" src="https://github.com/user-attachments/assets/4dd08fea-2221-4b0f-9378-00dd7e45685f">

**Comment by Prokyonn** [comment]
> Working with the #7606 branch.
> 
> Just for info - if I change my profile system language to German, I get the following warning: <img alt="Bildschirmfoto 2024-10-08 um 10 06 17" width="649" src="https://private-user-images.githubusercontent.com/89628357/374466691-4dd08fea-2221-4b0f-9378-00dd7e45685f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTcyNTEsIm5iZiI6MTczMDE5Njk1MSwicGF0aCI6Ii84OTYyODM1Ny8zNzQ0NjY2OTEtNGRkMDhmZWEtMjIyMS00YjBmLTkzNzgtMDBkZDdlNDU2ODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEwMTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OTlmYTFmOWZlZTZhOTc4MGE3MmIxMTFjYWRjZmQzZThmMDc4NGIzMGVlODY4MmM3YjQ1OGZhYjg2N2E0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zkjvk5hw4kTWLtef5_drcTN4y2q8foFT4ob87OVrAwc">

@hual7 Thank you!
Sorry for the late response, I've added the missing locale in https://github.com/sulu/sulu/pull/7630
