### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Donder172** [sulu/sulu#7603]
While I was working on an issue of my own with setting up a project with Sulu, I stumbled across the answer to it. Though, this issue, as the title suggests, is not about that.

My issue is that the command within the [documentation](https://docs.sulu.io/en/latest/book/getting-started.html) does not seem to be correct, specifically of creating a default admin. It gives the command `bin/adminconsole sulu:build dev` to do so. However, using this command, in my experience, only opens adminconsole and does nothing else.

Within this [issue](https://github.com/sulu/sulu/issues/6863), I came across the correct command, `php bin/adminconsole sulu:build dev`.
![Knipsel](https://github.com/user-attachments/assets/c53ff713-bd55-402b-aa8a-665af6b307b4)

**Comment by mamazu** [comment]
I don't understand what your problem is. Could you be more specific on what behaviour you want to be documented. Running the admin build command in dev shows me this:
```
Build Targets
=============

+---+--------------------+---------------------------------------------------------------------------------+
| # | Builder            | Deps                                                                            |
+---+--------------------+---------------------------------------------------------------------------------+
| 0 | database           |                                                                                 |
| 1 | phpcr              | database                                                                        |
| 2 | phpcr_migrations   | phpcr                                                                           |
| 3 | fixtures           | database, phpcr                                                                 |
| 4 | user               | fixtures, database                                                              |
| 5 | system_collections | database, fixtures                                                              |
| 6 | security           | fixtures, database                                                              |
| 7 | dev                | database, fixtures, phpcr, user, phpcr_migrations, system_collections, security |
+---+--------------------+---------------------------------------------------------------------------------+
````

If you only want to set up the user however, you probably want to run `bin/adminconsole sulu:build user`.

**Comment by alexander-schranz** [comment]
this will be fixed in https://github.com/sulu/sulu-docs/pull/821.

On none Unix based Operaton systems I recommend a unix based terminal emulator for PHP developing. 

 - git bash
 - ConEmu
 - Cmder
 - maybe powershell also works but not tried

Or use WSL Linux when on windows.
