### ISSUE TITLE
UploadFileSubscriber causes problem for multi-dimensional file array

### ISSUE THREAD

**Issue by NicoHaase** [sulu/sulu#7604]
| Q | A
| --- | ---
| Sulu Version | 2.6.5
| PHP Version | 8.2
| DB Version | irrelevant
| Browser Version | irrelevant

# Actual Behavior

Our application uses a file upload function within EasyAdmin (which we use besides Sulu), where file upload fields are used in array shape. This is how the `files` array looks like when debugged in PhpStorm:

![grafik](https://github.com/user-attachments/assets/dfa9f08a-c670-48c5-9891-50d0151e091c)

As you can see, the structure is a multi-dimensional array, and not only one with simple keys and files as values. As the `UploadFileSubscriber` can't handle such a structure, the request fails pretty hard. And as Sulu binds this pretty close on **any** incoming request, there's no nice way to get around this (for example, as we don't need it in our application, or as any form request from the frontend should not trigger this)

# Expected Behavior

The `UploadFileSubscriber` would either try to work on a multi-dimensional structure, or skip checking the content of this array.

# Steps to Reproduce

Use any kind of form with upload fields with multi-dimensional structure, like 

```
<input type="file" name="Product[thumbnail][file]">
```

and trigger an upload.

# Possible Solutions

- put this more closely into Sulu's own responsibilties (such that this check is only triggered when run from within Sulu code)
- detect whether the FILES array is multi-dimensional, and handle this structure properly in the subscriber

**Comment by wachterjohannes** [comment]
@NicoHaase thanks for reporting this. I have already created PR for the upcoming release.

It would be great if you could test the changes (https://github.com/sulu/sulu/pull/7607) in your system that we can be ensure that your usecase will be covered.

**Comment by mhnrm** [comment]
Same here, Sulu Community Bundles Profile Form fails due to being nested. The PR fixes the issue for me.

**Comment by NicoHaase** [comment]
@wachterjohannes sorry for not repsonding here... your fix is working for me, thank you!
