### ISSUE TITLE
Ordering the page entries alphabetically

### ISSUE THREAD

**Issue by mamazu** [sulu/sulu#7625]
# Problem description

In the webspace overview currently there is an option to manually sort entries to the users liking. However this is very impractical when you have a lot of entries.

# Proposed solution

Add an option to the UI to sort the entries alphabetically.

**Comment by alexander-schranz** [comment]
I'm unsure about add something like this to the core. Reordering data by title is something which ends still in unexpected state in other languages. So at current state I personally would not add such things to the core.

If somebody want to output the pages on the website by title they can still use the smart content and select there order by title, where it is clear it is then only in the output and not effects accidently other languages.

For your project I think it would be possible todo it as a save listener for new pages to put them in the tree where you think make sense.

**Comment by mamazu** [comment]
I see that this isn't as easy in multi language system because one page could be ordered differently based on the different titles. Then I'll try to implement this only in our stack.

However I don't think that a save listener is going to be enough because we want to sort all nodes under a given parent when a button is clicked and not just one document into the right position. Or does it make sense in the save listener to also order all children?

**Comment by alexander-schranz** [comment]
I mean more you can configure a path in your project or better a parent uuid via ENV VAR which the listener can use to sort then in your project only the childs of that specific parent page on save.

**Comment by alexander-schranz** [comment]
For nodes with many child we normally recommend migrate them to the unstructered article bundle as the tree isn't suitable from UI/UX perspective for such mass data.

**Comment by mamazu** [comment]
Or I'll just write a one off command that sorts them with a cli tool and that's it. :D I don't want to maintain this feature if you say that it's going to cause problems later.
