### ISSUE TITLE
Content Type color cant be reseted to be empty 

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#764]
If you set a color and wanted later to set the field to empty its not possible in the frontend maybe a husky bug.

**Comment by wachterjohannes** [comment]
yes its a husky bug and i have created there a new issue

**Comment by danrot** [comment]
Can we close this issue then in favour of the other?

**Comment by wachterjohannes** [comment]
hmm the other issue is on husky ... perhaps we let this open otherwise we get here another one ...

**Comment by alexander-schranz** [comment]
seems to be fixed
