### ISSUE TITLE
Versioning support for jackalope/jackalope-doctrine-dbal

### ISSUE THREAD

**Issue by RafaelKr** [sulu/sulu#7649]
# Problem description

The docs about [Versioning](https://docs.sulu.io/en/2.6/bundles/page/versioning.html) state that it's only supported for Apache Jackrabbit. It's a limitation of using Jackalope as it's not supported for their https://github.com/jackalope/jackalope-doctrine-dbal implementation.

As I don't have any experience in managing Apache Jackrabbit and there isn't much content (yet) I'd like to keep it simple by also using Postgres for the content. But when going to production versioning is required for our project.

Are there any plans supporting Versioning for Doctrine DBAL if the upstream limitation vanishes?

# Proposed solution

There are long standing PRs (since 2015) to support versioning for Doctrine DBAL: https://github.com/jackalope/jackalope-doctrine-dbal/pull/316 and https://github.com/jackalope/jackalope/pull/296

Is there any interest or are there any plans by the sulu teams moving this forward?

**Comment by alexander-schranz** [comment]
Hello @RafaelKr, We are moving away from PHPCR / Jackalope and will so not investigate to add new features to jackalope-doctrine-dbal implementation. Instead the new Content Storage will support versioning out of the box and not longer use PHPCR under the hood which we are currently working on for Sulu 3.0.

**Comment by RafaelKr** [comment]
Thanks for clarifying! Will there be an easy migration path to v3.0?

And I know we developers hate that question 😂 but is there already a roughly estimated release date?

**Comment by alexander-schranz** [comment]
Data migration is covered by https://github.com/sulu/SuluPHPCRMigrationBundle whic migrates Pages, Articles and Snippets to the new Content Storage. Code usage of PHPCR, Jackalope, Document Manager you need manually migrate to the new Services, but if you didn't use that services it will be straight forward.

No release date yet, some pre-version in December.

**Comment by RafaelKr** [comment]
Thanks. We're just starting out with our first Sulu project, everything looking good so far!
So we'll try to not use those components and see how it works for us.

**Comment by alexander-schranz** [comment]
So closing this as we target versioning support for 3.x for the new storage.
