### ISSUE TITLE
Website permissions check enabled on every page

### ISSUE THREAD

**Issue by dev-newvisibility** [sulu/sulu#7660]
| Q | A
| --- | ---
| Sulu Version | 2.6.5
| PHP Version | 8.3.11

We've enabled the webspace's permission check flag, but now every page returns the following error after the user logs in on the frontend:

```
Permission "view" in localization "it" for context "sulu.webspaces.xxx" and object with id "xxx-xxx-xxx" and type "Sulu\Bundle\PageBundle\Document\PageDocument" not granted
```

Webspace config:

```xml
<webspace>
    <!-- ... -->
    <security permission-check="true">
        <system>Website</system>
    </security>
</webspace>
```

# Actual Behavior

Pages that don't have permissions enabled can't be accessed by logged in users, anonymous users can see them.

# Expected Behavior

Pages without permissions enabled should be accessible to everyone.

# Steps to Reproduce

1. Set to true the "permission-check" flag of the webspace
2. Install the SuluCommunity bundle
3. Register and login to the frontend
4. Go to the homepage or every other page without permissions set
5. AccessDeniedHttpException

# Possible Solutions

We think that here we should check that document's permissions array contains the 'view' key
https://github.com/sulu/sulu/blob/c4364a34afb62ca7057337db0aa3d36c8bd5eb6e/src/Sulu/Bundle/WebsiteBundle/EventListener/SecurityListener.php#L71

Like the ContentMapper already does: https://github.com/sulu/sulu/blob/c4364a34afb62ca7057337db0aa3d36c8bd5eb6e/src/Sulu/Component/Content/Mapper/ContentMapper.php#L640

**Comment by alexander-schranz** [comment]
Thx for report, can you try something out for me. **Attention** only on a Dev / Machine Database. If you destroy your database and make sure to reinit the security:

```bash
rm -rf var/cache

bin/console sulu:build dev --destroy

bin/console sulu:security:init

rm -rf var/cache
```

Does the bug still appear for new created pages in both webspaces?

**Comment by dev-newvisibility** [comment]
Hi,

I've tried your commands and with a clean db everything works as expected. Then I tried just running the "sulu:security:init" on the real db and then a cache clear and the problem doesn't occur anymore. So it seems that the problem doesn't exist, I missed the need to run the cli command after the permission-check flag was enabled.

Thanks for your help.

**Comment by alexander-schranz** [comment]
Thx for the feedback nice that it works now.
