### ISSUE TITLE
`composer recipes:update doctrine/doctrine-bundle` leads to `null value in column "id" of relation "the_table" violates not-null constraint`

### ISSUE THREAD

**Issue by RafaelKr** [sulu/sulu#7663]
| Q | A
| --- | ---
| Sulu Version | 2.6
| PHP Version | 8.2
| DB Version | Postgres 16 
| Browser Version | –

# Foreword
This issue is a cross-reference to https://github.com/symfony/recipes/issues/1363
It is not directly related to Sulu. But we stumbled across this in our Sulu project using Postgres and I wanted to add this issue here if anyone else runs into this.

It may be relevant to Sulu when migrating to Doctrine DBAL v4, see https://www.doctrine-project.org/projects/doctrine-dbal/en/stable/how-to/postgresql-identity-migration.html#migration-to-identity-columns-on-postgresql

# Actual Behavior

When using Postgres and running `composer recipes:update doctrine/doctrine-bundle` afterwards we will get a lot of not-null constraint errors whenever the database needs to generate an identifier. This happens when trying to create a page/snippet/media/...

The error the database logs are showing and those appearing in the Browser DevTools network tab look like:
`An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "id" of relation "the_table" violates not-null constraint`

This happens because the flex recipe update adds the following lines to the `config/packages/doctrine.yaml`:
```yaml
 identity_generation_preferences: 
     Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity 
```

A more thorough description and a reproduction is provided in the Symfony Flex Recipe issue: https://github.com/symfony/recipes/issues/1363

# Expected Behavior

–

# Steps to Reproduce

See https://github.com/symfony/recipes/issues/1363

# Possible Solutions

Revert the change that the recipe update made (revert `config/packages/doctrine.yaml` and `symfony.lock`)

**Comment by alexander-schranz** [comment]
```
 identity_generation_preferences: 
     Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity 
```

Means you change the `id` from `Sequences` to `Auto Increment` identifier. This requires a database schema update. I'm not sure how good doctrine here is. After you changed the value did in the config, the following command may should check if your schema did change:

```bash
bin/console doctrine:schema:update --dump-sql
```

Does it output something? If not it sounds like a bug in Doctrine Diff Checker.

**Comment by RafaelKr** [comment]
> ```
>  identity_generation_preferences: 
>      Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity 
> ```
> 
> Means you change the `id` from `Sequences` to `Auto Increment` identifier. This requires a database schema update.

Yes, but this is only required starting from DBAL v4. And the composer.lock of my Sulu project shows `doctrine/dbal` version 3.9.3. So I'm not sure if it's correct that flex is already updating that config.

> I'm not sure how good doctrine here is. After you changed the value did in the config, the following command may should check if your schema did change:
> 
> ```shell
> bin/console doctrine:schema:update --dump-sql
> ```
> 
> Does it output something? If not it sounds like a bug in Doctrine Diff Checker.

But good catch, it outputs an update for every table id:
```SQL
CREATE SEQUENCE tr_trash_items_id_seq;
SELECT setval('tr_trash_items_id_seq', (SELECT MAX(id) FROM tr_trash_items));
ALTER TABLE tr_trash_items ALTER id SET DEFAULT nextval('tr_trash_items_id_seq');
CREATE SEQUENCE tr_trash_item_translations_id_seq;
SELECT setval('tr_trash_item_translations_id_seq', (SELECT MAX(id) FROM tr_trash_item_translations));
ALTER TABLE tr_trash_item_translations ALTER id SET DEFAULT nextval('tr_trash_item_translations_id_seq'
[...]
CREATE SEQUENCE ro_routes_id_seq;
SELECT setval('ro_routes_id_seq', (SELECT MAX(id) FROM ro_routes));
ALTER TABLE ro_routes ALTER id SET DEFAULT nextval('ro_routes_id_seq');
```

But as those are Sulu "internal" tables, I think it would be up to sulu/sulu to do those Migrations, right? Maybe you want to do this starting from v3?

**Comment by alexander-schranz** [comment]
Flex recipes are based on doctrine bundle version and are current recommendation to start a new project. If you dont want a new setting yet remove it.

The update of the tables need to be done by the project if you switch we personally using doctrine migration bundles which does create correct migrations based on your database and database version.

**Comment by RafaelKr** [comment]
Okay, so if I understand you correctly we could safely update our project to the new `identity_generation_preferences`, run the migrations and won't run into any problems, correct?

Also if you would do any internal migrations for the upgrade to Sulu v3 this would not break?

**Comment by alexander-schranz** [comment]
> Also if you would do any internal migrations for the upgrade to Sulu v3 this would not break?

Sulu doesn't provide any database migrations. Sulu is build ontop of doctrine and doctrine supports a wide range of databases and which again have a wide range of versions which behave differently.

Keep your database uptodate Sulu provides tools from the doctrine bundle. You can use `doctrine:schema:update --force` for quickly update your database. For more professional uses we recommend that you install doctrine migrations and create migrations files which are then part of your review process.

Sulu does not care if you use identity_generation_preferences `identity` or not. Aslong as doctrine behaves still the same way. MySQL uses auto increment which is similar to identity and PostGreSQL did use `sequence` in the past but identity is now also supported and looks like the new recommendation for new projects. Feel free to upgrade to it or keep what you want.

As said recipe update provides recommendation, this changes always are some kind of bc breaks which you need to validate if it breaks your project and what you need to change in your code or in this case database to support the new option. If you run into any issues related in Sulu core code let us know.

**Comment by RafaelKr** [comment]
Thanks for the very detailed explanation! Now that makes it clear to me, thanks.
