### ISSUE TITLE
Preview should load WebsiteKernel Bundles

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#771]
I created some custom bundles which have also some twig extensions this twig extensions don't work in the preview until I added the Bundles to AbstractKernel instead of WebsiteKernel.

Same for routes which are only registered in the website kernel. e.g.
 `{{ path('my_custom_website_route') }}`

**Comment by wachterjohannes** [comment]
the preview renderer is placed in the admin ... so you have to put your bundles there ... @chirimoya @danrot how should we handle this in the future?

**Comment by alexander-schranz** [comment]
When I did add my bundle to the AbstractKernel when the user then access the sulu webspace content he was logout the sulu automaticly. Maybe some routing problem? when is the user redirected to logout/login?

**Comment by danrot** [comment]
This is done when the session expired for whatever reason.

Regarding the actual issue I don't really know how to handle this... It would be optimal if the website bundles are only loaded in the preview, otherwise the splitting makes no sense. But I don't know how to achieve that...

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu-standard/issues/621

**Comment by danrot** [comment]
Fixed in #2535
