### ISSUE TITLE
Feature Request isEmpty for Block or Section in Template

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#804]
If I create a new template/theme and have a block or section in the Template like the following example it would be awesome to have a check function if this fields of a **section/block** are **not empty**.

``` xml
        <section name="simple">
            <meta>
                <title lang="de">Section</title>
                <title lang="en">Section</title>
            </meta>
            <properties>
                <property name="title_1" type="text_line">
                    <meta>
                        <title lang="de">Titel 1</title>
                        <title lang="en">Titel 1</title>
                    </meta>
                 </property>
                <property name="title_2" type="text_line">
                    <meta>
                        <title lang="de">Titel 2</title>
                        <title lang="en">Titel 2</title>
                    </meta>
                 </property>
                <property name="title_3" type="text_line">
                    <meta>
                        <title lang="de">Titel 3</title>
                        <title lang="en">Titel 3</title>
                    </meta>
                 </property>
                <property name="title_4" type="text_line">
                    <meta>
                        <title lang="de">Titel 4</title>
                        <title lang="en">Titel 4</title>
                    </meta>
                 </property>
           </properties>
         </section>
```

**Currently** i need to do the following:

``` twig
{% if content.title_1 is not empty or content.title_2 is not empty or ....
```

It would be **better** to have something like this:  

``` twig
{% if section_not_empty('simple') %}
{# or #}
{% if not content.sections.simple.empty %}
```

The same should also work for a **block** of multiple.

For this I think we need to add for every content type an `isEmpty`function which we should add to the `PropertyInterface`?

This have no priority but think it would be a nice feature for theme developers. Please give me feedback what you think about this feature.

**Comment by danrot** [comment]
I would prefer the option with the twig function, because the data should IMHO still only be data, not any additional (meta) information. Could imagine that this is a very useful feature for theme developers.

**Comment by alexander-schranz** [comment]
As sections are just for UX and blocks would mess with the preview and I never had the need for this the last 3 years and nobody else did response to this issue. I close this issue.
