### ISSUE TITLE
Remove sulu.preview.update event in favour of sulu.content.changed

### ISSUE THREAD

**Issue by danrot** [sulu/sulu#811]
In every validation type I can find there are the following lines for handling changes:

``` javascript
    var dataChangedHandler = function(data, $el) {
        App.emit('sulu.preview.update', $el, data);
        App.emit('sulu.content.changed');
    };
```

So it looks to me like the `sulu.preview.update`-event can be deleted, and we append the additional data (`$el` and `data`) to the `sulu.content.changed`-event. Would also make sense to me, since it might make sense to have this data in this event.

An additional benefit would be that the content types don't have to be aware of the preview, which would make it easier to extract the preview into an own component one day.

**Comment by wachterjohannes** [comment]
+1

**Comment by danrot** [comment]
In Sulu 2.0 that will change completely, and in the old UI we probably won't fix it, so I am closing it.
