### ISSUE TITLE
Add Tidy HTML

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu#815]
Hi,
can you please insert a tidy HTML function - so than in zoolu?
greetz
Daniel M.

**Comment by wachterjohannes** [comment]
we should include this bundle https://github.com/wachterjohannes/AsapoTidyBundle but it doesn´t work with symfony 2.6 actually ... we should update it and integrate it!

**Comment by dantleech** [comment]
What would this function do?

**Comment by danrot** [comment]
Tidy is a tool which cleans the HTML (wrong tags, nice formatting, ...) before actually sending the response.

**Comment by alexander-schranz** [comment]
features documented here: http://tidy.sourceforge.net/docs/quickref.html

**Comment by dantleech** [comment]
performance killer?

**Comment by danrot** [comment]
Mainly a SEO-booster :-P Don't think it takes too much time.

**Comment by alexander-schranz** [comment]
And when the page is cached it dont runs tidy again and adding a disable option into the config should not be a lot of work?

**Comment by dantleech** [comment]
Why does it boost SEO? If we have wrong tags we should fix them, hiding the problem will just cause other problems..

**Comment by alexander-schranz** [comment]
I think its for the website/them devs not for the sulu backend.

**Comment by danrot** [comment]
No, if you don't have valid HTML on the website it will have a VERY BAD effect on your page ranking.

**Comment by dantleech** [comment]
Well, then we should have valid HTML :) Automatically trying to correct invalid HTML means that the original problem remains unresolved and hidden, and there is also the chance that the "fixing" algorithim will fix something in an unexpected way.

**Comment by danrot** [comment]
Can be easily overseen, and valid HTML is always better than invalid. It's also fixing other less obvious stuff, so we should definitely include it.

**Comment by dantleech** [comment]
But it shouldn't be fixing anything .. things shouldn't be broken. It
would be better to have a command which checks the validity of the HTML.

If things are fixed automatically then there is no oversight, and the
computer does "what it wants" which is not what the developer might have
intended. This creates a situation where strange things can happen which
will be hard to debug.

It also adds overhead.

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu/issues/815

**Comment by webmozart** [comment]
@chirimoya Was your intention to self-reference this issue? :)

**Comment by chirimoya** [comment]
@webmozart don't know ;-) https://github.com/sulu-io/sulu-standard/issues/143

**Comment by patkar** [comment]
If damaged output is a SEO horror, I would prefer fixing with Tidy. But if Tidy must fix the HTML this should be logged and quickly accessible for the editor.

**Comment by wachterjohannes** [comment]
i have started a small bundle for tidy (https://github.com/wachterjohannes/AsapoTidyBundle) long time ago ... maybe we could reactivate it and include it into sulu. the errors there will be logged. maybe they could also be displayed in the admin-interface.

**Comment by wachterjohannes** [comment]
i have tested it and it would be quite easy. only require it in sulu-standard, add it to website-kernel and return a TidyResponse in the `SuluWebsiteBundle:Default:indexAction`

**Comment by wachterjohannes** [comment]
but then we have the additional dependency to php-tidy which is (at least in mac-brew) not installed automatically. /cc @danrot @chirimoya

**Comment by alexander-schranz** [comment]
@wachterjohannes correct me if im wrong but the current php tidy library is based on html4 which will `fix/crash` things which are valid in html5 e.g. an a tag can include block elements. I think currently this library will crash more things in html5 then fix so I would avoid it to include it in any project.

**Comment by wachterjohannes** [comment]
also at least in brew there is a new tidy-html5 which will be automatically installed and i didn´t get any "html5" errors on the first look.

**Comment by dantleech** [comment]
would still much prefer a bundle that told you that your HTML was invalid and told you how to fix it. its not the responsiblity of the application to fix HTML. And it is not guaranteed that the "fixed" results will actually look correct, its just another layer of "wtf" imo.

**Comment by wachterjohannes** [comment]
this is done by the tidy-bundle which says you in the profiler what should be done in the template to make it "clean" and in production it would clean it automatically.

**Comment by chirimoya** [comment]
+1

**Comment by danrot** [comment]
@chirimoya Do we still want to have something like this included? Would be something @ReneZumtobel could have a look at.

**Comment by wachterjohannes** [comment]
after a short look the bundle i mentioned a few comments before should work and could be used easily.

**Comment by danrot** [comment]
Consulted some developers, and it seems they don't really need this feature. And since it is already over 3 years old, I am going to close it.
