### ISSUE TITLE
Inconsistency in Node API

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#858]
https://github.com/sulu-cmf/sulu/pull/857/files#r25063284

return of node api returns for column-navigation id and for "filter by id" uuid as id key

**Comment by danrot** [comment]
@wachterjohannes What do you mean by that? Is that still an issue?

**Comment by wachterjohannes** [comment]
yes it still is. all the node-api-endpoints should return id instead (or additionally) of uuid. because all the components which are not implemented for the nodes will expect that.

**Comment by wachterjohannes** [comment]
the node api will be refactored completely in 2.0
