### ISSUE TITLE
Missing sort order of categories

### ISSUE THREAD

**Issue by xandrej** [sulu/sulu#900]
In mainmenu choose categories. The categories are sorted randomly.

**Comment by chirimoya** [comment]
please english, thx

**Comment by danrot** [comment]
Should probably sorted by name...

**Comment by xandrej** [comment]
There is nothing else than name...

**Comment by danrot** [comment]
I guess they are not sorted at all, so it's probably the creation date at the moment.

**Comment by xandrej** [comment]
If it will be sorted by creation date the date should be displayed also. At the moment they are thrown
randomly.

**Comment by danrot** [comment]
I said at the moment. They should definitely be sorted by name by default.

**Comment by wachterjohannes** [comment]
is it possible to set a default sorted column?

**Comment by danrot** [comment]
I think so, but I am not sure how...

**Comment by wachterjohannes** [comment]
currently it is not possible to set a default sort! this have to implemented in husky first!

**Comment by patkar** [comment]
The request goes with `fields=id,name` to the API.

**Comment by wachterjohannes** [comment]
@patkar we have to refactor the category api because that doesn´t match the current standard ... so it is not really a easy-pick i will remove that label now (=

**Comment by chirimoya** [comment]
https://github.com/sulu/sulu/pull/2600
