### ISSUE TITLE
Shadow Page has wrong sort order of smart content shadow pages

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#956]
**Startpage DE**
SmartContent sort order "last changed" with page1, page2, page3
Those pages are shadows in DE-AT

**Startpage DE-AT**
is a shadow page to DE and the sort order of the SmartContent pages refer to the change date of the shadow pages in DE-AT instead of the change date to the original DE page1, page2, page3

If the smart content is shown as a slider in DE (all pages original pages), the order is correct: page1, page2, page3 but in DE-AT it should be the same not page3, page1, page2 for example (change date from DE-AT instead of DE)

**Comment by wachterjohannes** [comment]
should not be to hard to fix! in the `SmartContentQueryBuilder::buildOrder` is the locale used ... here the shadow-locale should be used. The question is can we achieve this with a single query or if we need to reorder the result at the end. /cc @danrot

**Comment by danrot** [comment]
I guess it has to be solved with a single query, otherwise the limit probably doesn't work correctly.

**Comment by thomasduenser** [comment]
@wachterjohannes No need for a new issue, I've already created this one. Seems like this is not solved yet.

**Comment by danrot** [comment]
Just tested it, seems to be fixed.
